"""Punta Hermosa (150126): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150126"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Antonio Ricardo Díaz Zamalloa", "Ahora Nación", "ahora-nacion-an", [
        P("social", "Gestionar un hospital tipo 2, una farmacia municipal con medicinas a bajo costo y una línea de respuesta rápida de emergencias", 10, "Gestionar la construcción de un Hospital tipo 2"),
        P("agua_riesgos", "Búnkeres equipados con alimentos y equipos en distintas zonas para la respuesta inicial ante emergencias", 11, "Implementar Bunkers en distintas zonas del distrito"),
        P("urbano", "Habilitar una vía de acceso a la zona alta, gestionar servicios básicos donde faltan y regularizar predios", 11, "Solicitar la habilitación de una vía de acceso a la zona alta"),
        P("social", "Casa del adulto mayor, centro de ayuda psicológica familiar y centro de apoyo al desempleado", 11, "Construir e implementar la casa del adulto mayor"),
        P("seguridad", "Adquirir vehículos motorizados de respuesta rápida y equipar las camionetas de seguridad ciudadana", 11, "Adquirir y equipar las camionetas de seguridad ciudadana"),
        P("transporte", "Crear y señalizar estacionamientos, construir gibas y controlar que transportistas respeten paraderos", 12, "Crear y señalizar lugares de estacionamiento"),
        P("agua_riesgos", "Construir una planta de tratamiento de aguas servidas", 13, "Construir una planta de tratamiento de aguas servidas"),
        P("ambiente", "Plantar árboles captadores de CO2, ampliar el recojo de desechos a todo el distrito y aumentar las áreas verdes", 13, "Aumentar las aéreas verdes en un 100%", "Aumentar las áreas verdes en 100 %"),
        P("gestion", "Implementar la norma ISO anticorrupción, publicar en la web costos y plazos de las obras y abrir las sesiones de concejo", 13, "Implementar el ISO anticorrupción"),
        P("gestion", "Centro de Innovación y Ciudadanía Digital con capacitación tecnológica gratuita y una app municipal con identidad y trámites digitales", 14, "Centro de Innovación y Ciudadanía Digital Inteligente"),
        P("economia", "Programa «Turismo 365 días» con eventos de surf, bienestar, gastronomía, tecnología y cultura durante todo el año", 15, "Turismo todo el año"),
    ]),
    ("Jorge Humberto Olaechea Reyes", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("social", "Gestionar un centro de salud 24 horas y una ambulancia municipal para emergencias", 6, "Gestionar un Centro de Salud 24 horas", "1 proyecto de centro de salud gestionado y 1 ambulancia municipal operativa"),
        P("social", "Gestionar la creación de un centro materno infantil", 6, "Gestionar la creación de un Centro Materno Infantil", "1 proyecto de centro materno infantil gestionado"),
        P("social", "Talleres deportivos, culturales y recreativos municipales gratuitos", 6, "8 talleres deportivos", "8 talleres deportivos y 6 talleres culturales"),
        P("social", "Gestionar la creación de un instituto tecnológico en el distrito", 6, "un Instituto MINEDU y gestionado", "1 proyecto de instituto tecnológico gestionado"),
        P("seguridad", "Acciones preventivas, patrullaje integrado y sistemas de videovigilancia", 7, "patrullaje integrado y sistemas de videovigilancia"),
        P("economia", "Bolsa de trabajo municipal y actividades de promoción del empleo", 4, "Implementar una bolsa de trabajo municipal", "12 actividades de empleo por año"),
        P("economia", "Fortalecer la Cámara de Turismo, capacitar a operadores turísticos y promover eventos turísticos y gastronómicos", 5, "Fortalecer la Cámara de Turismo", "4 eventos turísticos anuales"),
        P("ambiente", "Campañas permanentes de limpieza de playas", 5, "Campañas permanentes de limpieza de playas", "12 campañas por año"),
        P("ambiente", "Programas de educación ambiental y protección de áreas verdes con participación vecinal", 5, "Programas de educación ambiental", "24 actividades ambientales en la gestión y 100 % de áreas verdes en programas de conservación"),
        P("gestion", "Actualizar los instrumentos de gestión y capacitar al personal municipal en atención al ciudadano", 8, "100% de instrumentos actualizados", "100 % de instrumentos actualizados y 2 capacitaciones anuales"),
        P("gestion", "Transparencia en contrataciones y obras, control interno y rendición periódica de cuentas", 6, "Transparencia en contrataciones y obras públicas", "2 audiencias públicas por año y publicación periódica de informes"),
    ]),
    ("Héctor Portugal Marín", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("social", "Gestionar ante el Ministerio de Salud la construcción de un centro de salud con atención las 24 horas", 3, "Construcción de un moderno Centro de Salud con atención de 24 horas"),
        P("urbano", "Construcción de pistas y veredas", 3, "Construcción de pistas y veredas para mejorar"),
        P("social", "Gestionar infraestructura, mobiliario y equipamiento educativo adecuados", 4, "Gestionar una adecuada infraestructura educativa"),
        P("seguridad", "Patrullaje constante con el programa «Punta Hermosa Segura»", 4, "patrullaje constante a través del Programa"),
        P("transporte", "Organizar el tránsito vehicular en la temporada de verano", 4, "Organizar el tránsito vehicular en la temporada de verano"),
        P("social", "Servicio de terapias y talleres para personas con discapacidad", 4, "Brindar un adecuado servicio de terapias y talleres"),
        P("economia", "Promover el turismo y atraer inversión privada para generar empleo", 4, "Atraer la Inversión privada"),
        P("agua_riesgos", "Instalar el sistema de alcantarillado en el sector que no lo tiene para reducir los silos", 4, "Instalación del sistema de alcantarillado"),
        P("urbano", "Controlar la construcción indiscriminada y mantener la zonificación residencial del distrito", 5, "mantener la zonificación del distrito"),
        P("ambiente", "Incrementar los metros cuadrados de vegetación por residente", 5, "Incremento de metros cuadrados de vegetación por residente"),
        P("gestion", "Capacitar al personal municipal para mejorar la atención al vecino", 5, "Capacitación al personal para que brinde un servicio de calidad"),
    ]),
    ("Jhon Anderson Ortega Torres", "Cooperación, Verdad y Honradez", "cooperacion-verdad-y-honradez", [
        P("economia", "Construir y modernizar el mercado municipal", 2, "Construcción y modernización del Mercado Municipal"),
        P("economia", "Escuela Municipal de Oficios vinculada a una bolsa laboral distrital, y formalización y capacitación de emprendedores", 2, "Creación de la Escuela Municipal de Oficios"),
        P("economia", "Promoción turística activa durante todo el año", 2, "Promoción turística activa durante todo el año"),
        P("agua_riesgos", "Priorizar proyectos de agua y alcantarillado", 2, "Priorización de proyectos de Agua y Alcantarillado"),
        P("urbano", "Oficina de Saneamiento Físico-Legal y actualización del catastro municipal", 3, "instalación de la Oficina de Saneamiento Físico-Legal", "En los primeros 90 días"),
        P("ambiente", "«Puntos Limpios» para la gestión de residuos", 2, "Sostenibilidad: Implementación de"),
        P("seguridad", "Videovigilancia con inteligencia artificial para detectar placas y reconocimiento facial en zonas de alta afluencia", 2, "Sistema de video vigilancia con Inteligencia Artificial", "Plan piloto en los primeros 90 días"),
        P("seguridad", "Nuevos puestos de serenazgo en la zona este y patrullaje mixto permanente en todos los sectores", 2, "nuevos puestos de Serenazgo en la Zona Este"),
        P("gestion", "Gobierno digital para trámites rápidos y un portal que muestre en qué se gasta cada sol del presupuesto", 3, "Implementación de Gobierno Digital para trámites"),
        P("gestion", "Mesa Distrital por Sectores y audiencias públicas de rendición de cuentas", 3, "Creación de la Mesa Distrital por Sectores", "Audiencia pública semestral y anual"),
        P("social", "Expedientes técnicos para un hospital, un colegio emblemático, una clínica veterinaria y la modernización de la comisaría", 4, "Hospital de Punta Hermosa"),
    ]),
    ("Luis Felipe Moreno Torres", "Fuerza Popular", "fuerza-popular", [
        P("agua_riesgos", "Estación de bomberos con ambulancia en alianza con la empresa privada y la Superintendencia de Bomberos", 3, "implementación de una estación de bomberos"),
        P("seguridad", "Combatir a las mafias de tráfico de terrenos en la zona este", 3, "mafias de traficantes de terrenos"),
        P("seguridad", "Central de monitoreo con la PNP, inteligencia artificial, más videovigilancia, patrullaje por cuadrantes y aplicativo vecinal de alerta", 3, "Patrullaje integrado por cuadrantes"),
        P("agua_riesgos", "Actualizar el plan distrital de prevención de riesgos, desastres y tsunamis con el CENEPRED", 4, "Plan distrital de prevención de riesgos, desastres y tsunamis"),
        P("transporte", "Elaborar el plan vial del distrito y eliminar progresivamente los puntos críticos de congestión", 4, "Eliminación progresiva de puntos críticos de congestión"),
        P("urbano", "Actualizar el Plan de Desarrollo Urbano, fiscalizar edificaciones, regular el crecimiento inmobiliario y construir el palacio municipal", 4, "Actualización del Plan de Desarrollo Urbano"),
        P("gestion", "Digitalizar licencias y trámites para acelerar su atención", 4, "Digitalización de licencias y trámites"),
        P("social", "Biblioteca y centro cultural municipal y Escuela Municipal de Liderazgo Juvenil", 5, "Biblioteca y Centro Cultural municipal"),
        P("economia", "Convenios con universidades e institutos para capacitar a jóvenes en gastronomía y turismo", 5, "mejorando sus habilidades en gastronomía y turismo"),
        P("social", "Programa de taichí y yoga para adultos mayores por días y zonas", 5, "programa de practica de Taichi y Yoga"),
        P("gestion", "Portal de transparencia en tiempo real, presupuesto participativo vinculante y declaración jurada de intereses de funcionarios", 5, "Audiencias públicas trimestrales", "Audiencias públicas trimestrales"),
    ]),
    ("José Jhonnatan Saldaña Vásquez", "Partido del Buen Gobierno", "partido-del-buen-gobierno", [
        P("social", "Convenio con el MINSA para un centro materno infantil 24 horas, ambulancia municipal, «Médico en tu casa» y Farma MINSA", 5, "CENTRO MATERNO INFANTIL 24 HORAS", "40 % más de acceso oportuno a servicios de salud"),
        P("social", "Programa con el MINEDU para reducir la deserción escolar y los jóvenes que no estudian", 6, "reducir la deserción y mejorar el rendimiento escolar", "Reducir a la mitad la deserción escolar y los jóvenes que no estudian al 2030"),
        P("social", "Complejo deportivo, escuelas deportivas gratuitas o a costo social y promoción del surf", 7, "Construcción de un complejo deportivo", "50 % más vecinos en actividades deportivas al 2030"),
        P("social", "Fortalecer el Centro Integral del Adulto Mayor y un sistema de donación y reparación de sillas de ruedas y otras ayudas", 7, "Implementar un sistema de apoyo al adulto mayor", "40 % más adultos mayores en servicios municipales al 2030"),
        P("seguridad", "Gestionar una comisaría, modernizar la videovigilancia, botones de alerta vecinales y una oficina del Centro de Emergencia Mujer", 8, "Gestionar e impulsar la construcción de la Comisaria", "Reducir en 30 % la incidencia delictiva al 2030"),
        P("agua_riesgos", "Obra en el cauce del huaico, alerta temprana, rutas de evacuación y simulacros de sismo y tsunami", 8, "tramo del cauce natural del huaico", "100 % de las actividades del plan de riesgo de desastres al 2030"),
        P("transporte", "Semáforos, ciclovías hacia las playas, registro de conductores y programa «Taxi Seguro»", 9, "Implementación del programa municipal", "Duplicar los operativos de tránsito e implementar «Taxi Seguro» al 2030"),
        P("ambiente", "Recolección selectiva con recicladores formalizados, compostaje y eco-puntos para residuos especiales", 10, "escalar la recolección selectiva con recicladores formalizados", "35 % de viviendas priorizadas que segregan y al menos 8 eco-puntos al 2030"),
        P("ambiente", "Plan de arbolado e infraestructura verde con especies de bajo consumo de agua y «Adopta un árbol / adopta un parque»", 10, "Plan Distrital de Arbolado e Infraestructura Verde", "300 árboles nuevos y 5 000 m² de áreas verdes al 2030"),
        P("economia", "Programa de emprendimiento con módulos «Av. El Emprendedor», capacitaciones y acceso a capital semilla", 12, "La construcción de 15 módulos", "15 módulos; duplicar los emprendedores beneficiados al 2030"),
        P("gestion", "Ventanilla virtual, carpeta ciudadana y trámites del TUPA en línea con pagos y seguimiento de expedientes", 14, "ventanilla virtual y carpeta ciudadana municipal"),
    ]),
    ("Mónica Cecilia Mundaca Becerra", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("social", "Programas para jóvenes y adultos mayores y actividades deportivas y culturales para todas las edades", 7, "CREAR Y FOMENTAR PROGRAMAS PARA JÓVENES Y ADULTOS MAYORES"),
        P("social", "Complejo deportivo con piscina semiolímpica techada y temperada a costo social y un simulador de surf", 7, "CONSTRUCCIÓN DE PISCINA SEMIOLÍMPICA"),
        P("urbano", "Remodelar las áreas verdes existentes e incluir más en el diseño urbano", 7, "REMODELACIÓN Y RECREACIÓN DE LAS ÁREAS VERDES EXISTENTES"),
        P("seguridad", "Casetas de seguridad de concreto y tranqueras eléctricas en lugar de manuales", 7, "MODERNIZAR LAS TRANQUERAS EXISTENTES DE SEGURIDAD"),
        P("social", "Centro de salud con mayor disponibilidad de atención primaria", 7, "CENTRO DE SALUD CON MAYOR DISPONIBILIDAD"),
        P("ambiente", "Veterinaria municipal y desparasitación y esterilización de animales abandonados", 7, "VETERINARIA MUNICIPAL CON PERSONAL CALIFICADO"),
        P("economia", "Capacitación laboral, formalización y asistencia técnica para pequeños negocios", 8, "PROGRAMAS DE CAPACITACIÓN LABORAL"),
        P("economia", "Ordenar el comercio ambulatorio y los mercados con servicios básicos y agua potable", 8, "MEJORAR Y ORDENAR EL COMERCIO AMBULATORIO"),
        P("ambiente", "Reforestación de parques, más contenedores y recolección de residuos, y educación ambiental", 8, "REFORESTACIÓN URBANA Y RURAL DE PARQUES"),
        P("urbano", "Asfaltado de pistas y veredas donde se requiera", 8, "ASFALTADO DE PISTAS Y VEREDAS"),
        P("gestion", "Gobierno abierto, datos abiertos y seguimiento público de obras; reducir y digitalizar trámites", 9, "MECANISMOS DE GOBIERNO ABIERTO, DATOS ABIERTOS"),
    ]),
    ("Max Andre Ampuero Leandro", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Centro de control y monitoreo con cámaras, análisis de imágenes y drones, y patrullaje integrado con licenciados de las Fuerzas Armadas", 7, "Moderno Centro de Control, Monitoreo y Comunicaciones"),
        P("seguridad", "Programas vecinales «Madres Brigadistas», «Wachimán Seguro» y «Mototaxi Alerta», y redes vecinales digitales", 7, "orientado a fortalecer la vigilancia preventiva y la protección de niños"),
        P("social", "Centro Preventorio Municipal de Salud y campañas médicas descentralizadas", 8, "Centro Preventorio Municipal de Salud"),
        P("social", "Casa de la Mujer con asesoría legal gratuita y acompañamiento psicológico", 11, "fortaleciendo la Casa de la Mujer"),
        P("economia", "Centro Municipal de Desarrollo Económico y Emprendimiento con capacitación, formalización y acceso al crédito", 12, "Centro Municipal de Desarrollo Económico y Emprendimiento"),
        P("economia", "Marca turística, circuito turístico costero y modernización del malecón", 14, "Circuito Turístico Costero de Punta Hermosa"),
        P("urbano", "Programa «Tu Propiedad Segura» con brigadas que asesoran gratis en saneamiento físico legal", 15, "Brigadas Municipales de Formalización"),
        P("agua_riesgos", "Mapa de brechas de servicios básicos y gestión de proyectos de agua, alcantarillado y drenaje", 16, "Mapa Distrital de Brechas de Servicios Básicos"),
        P("urbano", "Programa «Pistas y Veredas para Todos» con cofinanciamiento entre municipalidad y vecinos", 19, "programas de cofinanciamiento"),
        P("ambiente", "Programa de limpieza «Punta Hermosa Te Quiero Limpia», «Mi Techo Limpio» y reciclaje con recicladores formalizados", 22, "Mi Techo Limpio"),
        P("gestion", "Sistema de control interno, declaraciones juradas anticorrupción de proveedores y canal seguro de denuncias", 25, "Declaraciones Juradas Anticorrupción"),
    ]),
    ("Jenny Leila Romero Chaucayanqui", "Pueblo Consciente", "partido-politico-pueblo-consciente", [
        P("social", "Programa municipal contra la anemia infantil con el MINSA y el MIDIS", 8, "programa municipal de prevención y control de anemia", "Reducir la anemia infantil al 18 % al 2030"),
        P("social", "Clínica jurídica municipal gratuita para víctimas de violencia familiar", 10, "clínica jurídica municipal gratuita", "Operativa al primer semestre de 2027; al menos 15 personas atendidas por mes al 2028"),
        P("seguridad", "Centros de videovigilancia con lectura de placas y cámaras PTZ en puntos críticos", 9, "centros de videovigilancia integrada", "Al menos 30 cámaras activas al 2028; respuesta en 8 minutos o menos al 2029"),
        P("transporte", "Ordenar y formalizar las mototaxis con registro, paraderos autorizados, señalización y fiscalización", 12, "Programa Municipal de Ordenamiento y Formalización del Transporte Menor", "80 % de mototaxistas formalizados y al menos 10 paraderos al 2028"),
        P("urbano", "Compactar y afirmar trochas carrozables priorizadas con presupuesto participativo y obras por impuestos", 12, "compactación y afirmado de trochas carrozables", "Al menos 8 km de vías mejoradas al 2030"),
        P("urbano", "Saneamiento físico-legal con COFOPRI y revisión de ordenanzas que traban la titulación", 15, "Impulsar saneamiento físico-legal en coordinación con COFOPRI", "Al menos 300 títulos gestionados al 2030"),
        P("agua_riesgos", "Gestionar la ampliación de redes de agua, desagüe, electricidad y gas natural", 16, "ampliación de redes de agua, desagüe", "Al menos 200 conexiones nuevas de agua y desagüe al 2030"),
        P("economia", "Centro de Emprendimiento y Formalización Municipal con asesoría gratuita", 13, "Centro de Emprendimiento y Formalización Municipal", "Al menos 100 comercios formalizados al 2029"),
        P("economia", "Circuito turístico de lomas, playas y sitios arqueológicos con ciclovías y señalética", 15, "Implementar circuito turístico integrado", "Circuito inaugurado al 2028; 30 % más visitantes al 2030"),
        P("ambiente", "Reforestación y arborización, incluida la franja marginal de la quebrada Malanche", 17, "programa de reforestación y arborización", "4 m² de área verde por habitante y al menos 2 000 árboles al 2030"),
        P("gestion", "Plataforma de trámites y pagos municipales en línea", 19, "plataforma de trámites y pagos municipales en línea", "Al menos 10 trámites en línea al 2028; 30 % de pagos digitales al 2029"),
    ]),
    ("Federico Guillermo Abraham Kajatt Kajatt", "PPC", "partido-popular-cristiano-ppc", [
        P("social", "Gestionar la recategorización y ampliación del centro de salud con pediatría, ginecología, psicología y geriatría", 7, "Gestionar la recategorización, fortalecimiento y ampliación progresiva"),
        P("seguridad", "Modernizar el serenazgo y la videovigilancia con cámaras de reconocimiento facial en puntos estratégicos", 8, "cámaras con reconocimiento facial en puntos estratégicos"),
        P("seguridad", "Patrullaje integrado con distritos vecinos y gestión de mayor presencia policial", 8, "seguridad sin fronteras"),
        P("agua_riesgos", "Fortalecer la brigada municipal de respuesta ante emergencias y desastres", 8, "brigada municipal de respuesta ante emergencias y desastres"),
        P("social", "Programas contra el bullying, el acoso escolar y la violencia familiar, y mejoras educativas con la UGEL", 10, "programas de prevención contra el bullying"),
        P("social", "Escuelas deportivas municipales con surf y otras disciplinas, y losas deportivas iluminadas", 10, "Fortalecer escuelas deportivas municipales, incluyendo surf"),
        P("social", "Biblioteca municipal moderna para estudio, tecnología y capacitación", 10, "biblioteca municipal moderna orientada a estudios"),
        P("urbano", "Programa progresivo de pistas y veredas y recuperación de parques con áreas verdes e iluminación", 11, "programa progresivo de pistas y veredas"),
        P("ambiente", "Fortalecer la limpieza pública, el reciclaje y la arborización, y controlar la contaminación sonora", 11, "Fortalecer la limpieza pública, reciclaje, arborización"),
        P("economia", "Agenda de turismo, deporte y gastronomía todo el año, capacitación a emprendedores y bolsa laboral local", 12, "agenda de turismo, deporte, cultura y gastronomía durante todo el año"),
        P("gestion", "Gestión de puertas abiertas, publicación de avances, presupuesto participativo y tolerancia cero a la corrupción", 13, "política de tolerancia cero frente a la corrupción"),
    ]),
    ("Jorge Luis Linares Vera Portocarrero", "Renovación Popular", "renovacion-popular-peru", [
        P("social", "Gestionar atención de emergencias las 24 horas los 365 días y ambulancia permanente", 12, "Gestionar la atención permanente de emergencias las 24 horas"),
        P("social", "Gestionar la creación de un instituto de educación superior con carreras de turismo, gastronomía y tecnología", 13, "Gestionar la creación de un Instituto de Educación Superior en Punta Hermosa"),
        P("social", "Programa «Deporte Todo el Año» y fortalecimiento de la Escuela Municipal de Surf", 14, "Fortalecer la Escuela Municipal de Surf"),
        P("ambiente", "Veterinaria municipal con campañas de vacunación, esterilización y adopción responsable", 15, "Implementar la Veterinaria Municipal de Punta Hermosa"),
        P("economia", "Programa «Punta Hermosa Trabaja Todo el Año» con capacitación laboral y ferias permanentes de emprendedores", 16, "Punta Hermosa Trabaja Todo el Año"),
        P("transporte", "Plan integral de tránsito y ordenamiento del ingreso y salida de buses y micros", 23, "Gestionar el ordenamiento de los puntos de ingreso y salida del transporte público"),
        P("urbano", "Aumentar la inversión municipal en la zona este con infraestructura, iluminación y servicios", 24, "Incrementar la inversión municipal en la zona este"),
        P("seguridad", "Fortalecer el serenazgo, la videovigilancia, la iluminación pública y la coordinación interinstitucional", 36, "Fortalecimiento de serenazgo, videovigilancia, iluminación pública"),
        P("agua_riesgos", "Preparación ante sismos y tsunamis con simulacros periódicos y señalización de rutas de evacuación", 28, "Mejorar la señalización de rutas de evacuación"),
        P("ambiente", "Programa «Playas Limpias Todo el Año»", 30, "Playas Limpias Todo el Año"),
        P("gestion", "Digitalizar progresivamente los trámites municipales y la atención al ciudadano", 32, "Impulsar la digitalización progresiva de trámites municipales"),
    ]),
    ("Richard Manuel Pereira Núñez", "Un Camino Diferente", "un-camino-diferente", [
        P("seguridad", "Fortalecer el serenazgo, ampliar la videovigilancia, mejorar el patrullaje preventivo y recuperar espacios públicos", 6, "Fortaleceremos el serenazgo"),
        P("urbano", "Titulación de predios y ampliación de servicios básicos en la zona este", 6, "titulación de predios, la ampliación de servicios básicos"),
        P("agua_riesgos", "Acciones permanentes de prevención frente a huaicos en la zona este", 6, "acciones permanentes de prevención frente a huaicos"),
        P("social", "Promoción de un instituto tecnológico y programas de capacitación laboral", 6, "promoción de un instituto tecnológico"),
        P("gestion", "Gobierno electrónico con trámites virtuales y plataformas de atención ciudadana", 6, "gobierno electrónico, trámites"),
        P("transporte", "Herramientas de gestión inteligente del tránsito", 6, "gestión inteligente del tránsito"),
        P("economia", "Boulevard Playa El Silencio y recuperación paisajística del litoral", 6, "Boulevard Playa El Silencio"),
        P("economia", "Festival Internacional del Pacífico, eventos gastronómicos y deportivos y promoción hotelera", 6, "Festival Internacional del Pacífico"),
        P("social", "Atención médica las 24 horas y llegada de una clínica privada", 6, "atención médica las 24 horas, la llegada de una clínica privada"),
        P("social", "Ampliar la oferta educativa privada y programas para jóvenes y adultos mayores", 6, "ampliación de la oferta educativa privada"),
        P("gestion", "Rendición de cuentas, presupuesto participativo, licencias rápidas y oficina municipal de promoción de inversiones", 6, "oficina municipal de promoción de inversiones"),
    ]),
]
