"""Puente Piedra (150125): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150125"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Juan Carlos Merino Huamán", "Acción Popular", "accion-popular", [
        P("seguridad", "Sistema Integral de Seguridad Ciudadana con central de monitoreo, cámaras, puestos de auxilio rápido y unidades móviles conectadas por fibra óptica con la PNP", 6, "Creación del Sistema Integral de Seguridad Ciudadana con una central de monitoreo"),
        P("seguridad", "Escuela de Serenos creada por ordenanza, con instructores vinculados a la Policía y los bomberos", 11, "la Escuela de Serenos del distrito de Puente Piedra"),
        P("transporte", "Gestionar con la Municipalidad de Lima el mejoramiento vial de las avenidas principales del distrito", 6, "Gestión con la MML para el Mejoramiento vial de las avenidas principales del distrito"),
        P("transporte", "Registro de unidades de transporte público con características uniformes y capacitación gratuita a los conductores", 7, "Crear registro de unidades prestadoras de servicio de transporte público"),
        P("social", "Mejorar la infraestructura de seis centros de salud del distrito y crear un Policlínico Municipal", 6, "Mejoramiento de infraestructura en los Centro de Salud Jerusalem"),
        P("agua_riesgos", "Acelerar con el Ministerio de Vivienda y Sedapal el proyecto de agua y desagüe en La Ensenada, Laderas y otros sectores", 6, "Celeridad de la Ejecución del Proyecto de Agua y Desagüe en Sector Ensenada"),
        P("agua_riesgos", "Gestionar más muros de contención en los sectores Laderas y La Ensenada", 7, "más muros de contención en el Sector Laderas"),
        P("urbano", "Gestionar títulos de propiedad y saneamiento de las asociaciones, y catastro municipal en todo el distrito", 6, "Gestión de entrega de Títulos de Propiedad en las diferentes Asociaciones del Distrito"),
        P("economia", "Módulos de emprendedores en distintas zonas y bolsa laboral con el Estado y empresas privadas", 6, "Creación de Módulos de Emprendedores en diferentes zonas del Distrito"),
        P("ambiente", "Reforestar parques y calles con participación vecinal y proyectos de arborización con la Universidad Agraria", 7, "Coordinar con la Universidad Agraria para la ejecución de Proyectos de Arborización"),
        P("gestion", "Ejecutar obras por administración directa para reducir costos, y obras por impuestos con el sector privado", 7, "Ejecución de obras por Administración Directa, con la finalidad de minimizar costos"),
    ]),
    ("Luis Andrés Eustaquio Sánchez", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Serenazgo descentralizado con patrullaje motorizado permanente, de día y de noche, en los 17 sectores", 7, "Serenazgo descentralizado por sectores"),
        P("seguridad", "Central de videovigilancia con cámaras de reconocimiento facial y de placas en las zonas de mayor incidencia delictiva", 7, "cámaras de reconocimiento facial y de placas"),
        P("social", "Casa de la Mujer con defensa legal gratuita, apoyo psicológico y talleres de prevención de la violencia en escuelas", 4, "Creación de la Casa de la Mujer de Puente Piedra"),
        P("social", "Mega Centro de Salud Municipal y boticas municipales con precios sociales, descentralizadas por zonas", 8, "Construcción de un Mega Centro de Salud Municipal"),
        P("economia", "Formalizar a los comerciantes ambulantes con cronogramas, espacios de venta ordenados y capacitación", 4, "Formalización de los comerciantes ambulantes"),
        P("economia", "Programa de crédito municipal para pequeños emprendedores, en convenio con entidades financieras locales", 4, "Programa de crédito municipal para pequeños emprendedores"),
        P("gestion", "Portal de transparencia en tiempo real y rendición de cuentas semestral abierta a los vecinos de cada zona", 5, "Rendición de cuentas pública semestral", "Rendición de cuentas cada seis meses"),
        P("urbano", "Pavimentación masiva en los 17 sectores, con prácticas de estudiantes de ingeniería y arquitectura de la UNI y la UNMSM", 5, "Pavimentación masiva en los 17 sectores"),
        P("ambiente", "Programa «Puente Piedra Verde» de siembra de árboles y un vivero municipal junto al río Chillón", 5, "Vivero Municipal cerca del Río Chillón"),
        P("transporte", "Empadronamiento obligatorio de mototaxistas con SOAT y placa, y una aplicación de mototaxis con conductor identificado", 7, "Formalización y empadronamiento obligatorio de mototaxistas"),
        P("agua_riesgos", "Mapa de riesgo con INDECI, almacenes de emergencia y simulacros de sismo en colegios, mercados y espacios públicos", 7, "Simulacros obligatorios de sismo dos veces al año", "Simulacros dos veces al año"),
    ]),
    ("Judith Marisol Ramírez Rodríguez", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Más unidades y personal para el serenazgo y patrullaje integrado con la Policía", 44, "Incorporar 30 camionetas y 50 motocicletas equipadas", "30 camionetas, 50 motocicletas y respuesta en menos de 10 minutos"),
        P("seguridad", "Cámaras con identificación facial y de placas, red de fibra óptica, alarmas y central de monitoreo modernizada", 44, "Implementar 1,000 cámaras de", "1 000 cámaras de videovigilancia"),
        P("urbano", "Formalización de la propiedad con catastro multipropósito digital, habilitación de oficio y convenio con COFOPRI", 45, "Beneficiar a 20,000 familias con títulos", "20 000 familias con títulos de propiedad"),
        P("agua_riesgos", "Gestionar proyectos de agua, desagüe y electrificación en los sectores sin servicios básicos", 45, "Beneficiar a 10,000 familias con acceso a servicios básicos", "10 000 familias con agua, desagüe y energía eléctrica"),
        P("social", "Policlínico Municipal, gestión de nuevos establecimientos de salud y ambulancias para emergencias", 45, "creciente Policlínico Municipal", "Más de 100 000 vecinos con servicios de salud"),
        P("social", "Campañas de prevención, tamizaje y seguimiento de la anemia infantil", 46, "Beneficiar a más de 20,000 niños con acciones de prevención", "Más de 20 000 niños atendidos"),
        P("social", "Instituto Tecnológico Municipal, Academia Municipal Preuniversitaria y Biblioteca Municipal del Conocimiento", 47, "Academia Municipal Preuniversitaria y 1 Biblioteca Municipal del Conocimiento", "Un instituto, una academia y una biblioteca para más de 10 000 estudiantes"),
        P("transporte", "Formalización del servicio de mototaxis con registro, capacitación y ordenamiento", 48, "Formalizar al menos el 80% de mototaxistas", "Al menos 80 % de mototaxistas formalizados"),
        P("economia", "«Casa del Emprendedor Puentepedrino» con capacitación y asesoría, y ferias mensuales descentralizadas", 49, "Casa del Emprendedor Puentepedrino"),
        P("ambiente", "Programa de limpieza pública todo el año en todos los sectores, con tachos diferenciados y contenedores en puntos críticos", 40, "Puente Piedra Limpio los 365 Días del Año"),
        P("gestion", "Aplicación de denuncia anónima de corrupción y plataforma para seguir en línea el avance de las obras municipales", 51, "Implementar la app en el 100% del distrito como canal oficial de denuncias", "100 % de las obras municipales registradas en la plataforma"),
    ]),
    (None, "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("social", "Construir un Policlínico Municipal para atención primaria con un área especializada en cáncer", 22, "Al 2030 Puente Piedra contara con 01 Policlínico Municipal", "1 policlínico municipal en funcionamiento al 2030"),
        P("social", "Plan de nutrición infantil para reducir la desnutrición crónica en escolares", 22, "Al 2030 la DCI de niños de educación primaria disminuye al 5 %", "Desnutrición crónica en primaria al 5 % al 2030"),
        P("social", "Programa «De la Chacra a la Olla» con biohuertos, granjas familiares, banco de alimentos y apoyo a comedores y ollas comunes", 20, "PROGRAMA BANDERA"),
        P("seguridad", "Plan Integrado de Seguridad Ciudadana con unidades móviles nuevas y serenos capacitados", 25, "adquisición de, 50 unidades móviles para el servicio de serenazgo", "50 unidades móviles, 100 % de serenos capacitados y percepción de seguridad al 50 % al 2030"),
        P("urbano", "Vías de acceso seguro y escaleras de concreto en las laderas del distrito", 24, "construcción de 60,000 metros cuadrados de vías seguras", "60 000 m² de vías seguras y 460 escaleras al 2030"),
        P("urbano", "Saneamiento físico legal de predios urbanos y rústicos y actualización de la zonificación", 27, "Al 2030 el 40 % de predios urbanos cuentan con título de propiedad", "40 % de predios urbanos titulados al 2030"),
        P("agua_riesgos", "Gestionar con Sedapal y el Ministerio de Vivienda redes de agua, alcantarillado y reservorios para los asentamientos humanos", 26, "Beneficiar a 20,000 familias y gestionar la incorporación de 50", "20 000 familias beneficiadas y 50 asentamientos humanos incorporados a proyectos"),
        P("economia", "Formalizar el comercio ambulatorio y crear nuevas zonas de desarrollo comercial", 26, "Al 2030 Puente Piedra cuenta con 50 nuevos espacios para el desarrollo comercial", "50 nuevos espacios comerciales y 100 % del comercio ambulatorio ordenado"),
        P("transporte", "Empadronamiento y formalización de las empresas de vehículos menores", 27, "Al 2030 el 70 % de vehículos menores se halla formalizado", "70 % de vehículos menores formalizados al 2030"),
        P("ambiente", "Tratamiento y reutilización de aguas residuales para regar áreas verdes, y viveros municipales", 28, "abastezca al menos el 60% de las áreas verdes del distrito", "Agua tratada para al menos el 60 % de las áreas verdes y 10 viveros al 2030"),
        P("gestion", "Transformación digital con procedimientos automatizados e interoperables entre las áreas municipales", 29, "Digitalizar y automatizar el 100% de los procedimientos administrativos prioritarios", "100 % de procedimientos prioritarios digitalizados al 2030"),
    ]),
    ("Zusan Lizzet Sánchez Ponce", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("social", "«Puente Piedra Nutritivo»: complementación alimentaria, control nutricional itinerante y talleres para comedores populares", 7, "Reducir la desnutrición crónica infantil a menos del 10%", "Desnutrición crónica escolar por debajo del 10 % al 2030"),
        P("social", "«Puente Piedra Lee y Aprende»: alfabetización descentralizada en locales comunales, en convenio con el Minedu", 8, "Programa municipal descentralizado de alfabetización", "Analfabetismo adulto al 5 % o menos al 2030"),
        P("seguridad", "«Puente Piedra Seguro 24/7»: serenazgo modernizado, patrullaje integrado con la PNP y cámaras de alta definición", 8, "Modernización del serenazgo municipal, optimización del patrullaje integrado", "Victimización al 20 % y videovigilancia interconectada en los 18 sectores"),
        P("agua_riesgos", "«Agua y Dignidad»: gestión ante Sedapal de redes públicas y optimización de los 12 pozos profundos del distrito", 9, "optimización de los 12 pozos profundos locales", "90 % de cobertura de agua potable y saneamiento al 2030"),
        P("social", "Red de Soporte Familiar: DEMUNA, CIAM y OMAPED descentralizados con asistencia social itinerante", 9, "Fortalecimiento de la DEMUNA, el CIAM y la OMAPED", "Pobreza distrital al 15 % al 2030"),
        P("economia", "«Emprende Puente Piedra»: formalización de bodegas, ordenamiento del comercio ambulatorio y bolsa laboral técnica", 10, "Programa de formalización de bodegas y comercios locales", "Desempleo y subempleo informal al 40 % al 2030"),
        P("economia", "Escuela Municipal de Gestión de Negocios con asesoría gratuita en contabilidad y marketing digital", 11, "Creación de la Escuela Municipal de Gestión de Negocios", "60 % de los pequeños comercios del directorio formalizados"),
        P("urbano", "«Pistas para tu Salud»: asfaltado de vías, veredas y habilitación urbana en calles rústicas", 12, "Proyectos de inversión pública para el asfaltado de vías", "Déficit de pavimentación en asentamientos humanos reducido al 40 %"),
        P("ambiente", "«Puente Piedra Limpio y Verde»: nuevas rutas de recolección, cierre de chancherías clandestinas y segregación en la fuente", 12, "clausura de chancherías clandestinas", "100 % de recolección eficiente y botaderos clandestinos erradicados"),
        P("transporte", "Mesa técnica permanente con la ATU, el MTC y la Policía de Tránsito para fiscalizar y diseñar paraderos formales", 15, "Mesa Técnica Permanente entre la Municipalidad, la ATU"),
        P("gestion", "Modernización tributaria con simplificación de trámites y actualización del padrón de contribuyentes", 14, "actualización del padrón de contribuyentes", "Recaudación real al 80 % de lo presupuestado"),
    ]),
    ("Paulo Aníbal Casas Pinedo", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Repotenciar el Centro de Monitoreo con cámaras inteligentes Full HD, data center y radiocomunicación", 118, "adquisición de 100 cámaras de videovigilancia inteligentes", "100 cámaras de videovigilancia"),
        P("seguridad", "Nuevas camionetas y motocicletas para el patrullaje del serenazgo", 118, "Adquirir 14 camionetas pick up", "14 camionetas y 21 motocicletas"),
        P("social", "Campañas de salud preventiva pueblo por pueblo con medicina general, nutrición y psicología", 121, "Desarrollar campañas permanentes (2 por año)", "2 campañas por año"),
        P("social", "Programa nutricional municipal contra la anemia en gestantes y niños, con suplementación y controles", 122, "Programa Municipal Nutricional"),
        P("transporte", "Repotenciar el Plan Regulador de Vehículos Menores, con libro de reclamaciones obligatorio en cada paradero oficial", 129, "Plan Regulador de Vehículos Menores"),
        P("transporte", "Operativos de alcoholemia con la PNP y la Fiscalía, sobre todo los fines de semana", 130, "adquiriendo como mínimo cuatro alcoholímetros", "Al menos 4 alcoholímetros"),
        P("gestion", "Capacitación semestral del personal «El ciudadano primero» para acortar los tiempos de atención", 132, "no debe pasar de los 3 minutos", "Atención en no más de 3 minutos"),
        P("agua_riesgos", "Sistema de alerta sísmica distrital con sirenas que avisen segundos antes de un sismo", 133, "Implementar un Sistema de alerta sísmica distrital descentralizado"),
        P("economia", "Plan de Reordenamiento del Comercio Ambulatorio para liberar espacios públicos y formalizar a los ambulantes", 135, "Plan de Reordenamiento del Comercio Ambulatorio"),
        P("urbano", "Fortalecer la Gerencia de Formalización de la Propiedad para titular y sanear centros urbanos, y nuevo catastro", 138, "Gerencia de Formalización de la Propiedad"),
        P("ambiente", "Dos pozos de tratamiento de aguas servidas para regar parques y contenedores ecológicos en puntos críticos", 143, "Promover la creación de dos pozos de tratamientos de aguas servidas", "2 pozos de tratamiento de aguas servidas"),
    ]),
    ("Leónidas Cordero Villarreal", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("social", "Gestionar la construcción de un Policlínico Municipal con diversas especialidades y una unidad oncológica", 10, "construcción de Policlínico Municipal con diversas especialidades"),
        P("social", "Ambulancias nuevas para emergencias en las zonas Sur, Norte y Oeste", 10, "Adquisición de 03 nuevas unidades", "3 ambulancias nuevas"),
        P("social", "Velatorios municipales en los tres sectores del distrito", 11, "Construcción de 03 Velatorios Municipales", "3 velatorios municipales"),
        P("social", "Centros de preparación preuniversitaria «CEPRE MUNI» en las zonas Norte y Centro", 13, "Construir dos Centros de Formación Académica", "2 centros CEPRE MUNI"),
        P("agua_riesgos", "Muros de contención y escaleras de concreto en laderas, vía presupuesto participativo y gestión con los sectores", 12, "Gestionar la construcción de muros de contención a través del Presupuesto Participativo"),
        P("seguridad", "Plan «Serenazgo y Videocámaras sin Fronteras» coordinado con otros distritos, con cámaras en puntos críticos", 14, "Construcción e implementación de 02 Centros de Monitoreo", "2 centros de monitoreo y vigilancia"),
        P("economia", "Campo ferial comercial para que los microempresarios exhiban y vendan sus productos", 16, "Construcción del campo ferial comercial"),
        P("transporte", "Empadronamiento y formalización de las empresas de vehículos menores", 16, "Empadronamiento y formalización de las empresas de"),
        P("urbano", "Convenios con COFOPRI, SUNARP y la Municipalidad de Lima para el saneamiento legal de predios", 16, "Convenios con COFOPRI, SUNARP y Municipalidad de"),
        P("ambiente", "Relleno sanitario en la zona Norte, planta de tratamiento de aguas servidas para riego y vivero municipal", 17, "un relleno sanitario en la zona Norte del distrito"),
        P("gestion", "Capacitación permanente de funcionarios e incentivos al desempeño basados en la meritocracia", 18, "Promover un sistema de incentivos por desempeño en base a la meritocracia"),
    ]),
    ("Virginia Sandy Meza Pucho", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Geolocalizar los puntos de extorsión y asalto, con cámaras y equipos para cada sereno en apoyo de la PNP", 2, "Geolocalización de los puntos de altos índices", "Victimización por debajo del 15 %"),
        P("social", "Programas de asistencia social para los grupos vulnerables", 1, "Cobertura del 100% en programas de asistencia social", "100 % de cobertura en programas de asistencia social"),
        P("economia", "Capacitación en gestión para micro y pequeños empresarios", 1, "Capacitar a 5,000 emprendedores anualmente", "5 000 emprendedores capacitados al año"),
        P("economia", "Acelerar la entrega de licencias de funcionamiento", 1, "Reducir emisión de licencias a 24 horas", "Licencias en 24 horas"),
        P("agua_riesgos", "Muros de contención y sistemas de alerta temprana en asentamientos humanos con riesgo geológico", 2, "muros de contención y sistemas de alerta temprana", "Vulnerabilidad física reducida al 30 %"),
        P("transporte", "Más pavimentación en zonas periféricas, con participación de las juntas vecinales", 2, "Incremento de la pavimentación en zonas periféricas"),
        P("social", "Mejorar locales escolares con déficit y becas para estudiantes de bajos recursos sin exigir alto rendimiento", 2, "becas a estudiantes de bajos recursos económicos"),
        P("ambiente", "Arborización en vías y terrenos eriazos y programa «Mi árbol frutal en casa»", 2, "Mi árbol frutal en casa"),
        P("social", "Programa de ayuda y geolocalización de niños, adolescentes y madres solteras en desamparo", 2, "madres solteras puentepiedrinos"),
        P("urbano", "Entrega de títulos de propiedad y ejecución de servicios de agua y desagüe", 3, "Entrega de títulos de propiedad y ejecución de servicios básicos"),
        P("gestion", "«Municipio Digital» con trámites virtuales y alta ejecución presupuestal; dos audiencias públicas al año", 2, "Ejecución superior al 95%", "Trámites 100 % virtuales y ejecución presupuestal superior al 95 %"),
    ]),
    ("Rennan Santiago Espinoza Venegas", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Renovar la flota del serenazgo para patrullar todas las vías del distrito", 48, "30 CAMIONETAS Y 30 MOTOCICLETAS", "30 camionetas y 30 motocicletas en 4 años"),
        P("seguridad", "Cámaras adicionales con inteligencia artificial para reconocimiento de rostros y vehículos", 48, "Adquirir e instalar 1,000 CÁMARAS DE VIDEOVIGILANCIA", "1 000 cámaras adicionales"),
        P("social", "Dos centros de salud de nivel I-2 en Gallinazos y Copacabana y dos ambulancias nuevas", 50, "construcción de dos (02) establecimientos de salud especializados", "2 centros de salud y 4 ambulancias en total"),
        P("social", "Aulas equipadas en colegios públicos y losas multideportivas en los sectores del distrito", 52, "Construir 30 NUEVAS AULAS EQUIPADAS", "30 aulas y 50 losas multideportivas"),
        P("agua_riesgos", "Muros de contención en asentamientos humanos de ladera y zonas de alto riesgo", 54, "Construir 20 MUROS DE CONTENCIÓN", "20 muros de contención"),
        P("transporte", "Construir o gestionar 11 vías colectoras y arteriales no priorizadas por la Municipalidad de Lima", 54, "Construir y/o gestionar la construcción de las PRINCIPALES VÍAS"),
        P("urbano", "Proyectos de pistas y veredas en asociaciones de vivienda que ya cuentan con agua, desagüe y luz", 55, "Construir 30 PROYECTOS DE PISTAS Y VEREDAS", "30 proyectos de pistas y veredas"),
        P("urbano", "Habilitaciones urbanas de oficio y saneamiento físico legal para titular predios", 55, "70% DE PREDIOS TITULADOS", "70 % de predios titulados"),
        P("economia", "Incubadora Municipal de Negocios para emprendimientos nuevos y en riesgo", 56, "Crear la INCUBADORA MUNICIPAL DE NEGOCIOS"),
        P("ambiente", "Contenedores soterrados en zonas críticas y nuevos camiones compactadores y barredora", 60, "Implementar 20 CONTENEDORES SOTERRADOS", "20 contenedores soterrados y 5 camiones compactadores"),
        P("gestion", "Centros de Atención al Vecino con atención inmediata de trámites como licencias y certificados", 62, "atención inmediata (máximo 15 minutos)", "Atención en máximo 15 minutos"),
    ]),
    ("Antonio Germán Rodríguez Jaureguiza", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Ampliar la videovigilancia, el patrullaje integrado y la organización de juntas vecinales", 1, "ampliación de la videovigilancia, patrullaje integrado", "100 cámaras, 50 % más de patrullaje y 50 juntas vecinales"),
        P("agua_riesgos", "Gestionar agua potable y saneamiento para las familias de las zonas altas", 1, "cobertura de agua potable y saneamiento para las familias de las zonas altas", "5 000 hogares beneficiados"),
        P("urbano", "Construir o rehabilitar parques y espacios deportivos y recreativos", 1, "50 parques construidos o rehabilitados", "50 parques"),
        P("economia", "Programas de capacitación laboral y desarrollo económico", 1, "programas de capacitación laboral y desarrollo económico", "5 000 personas capacitadas"),
        P("economia", "Asistencia técnica para emprendedores locales", 1, "2,000 emprendedores beneficiados", "2 000 emprendedores beneficiados"),
        P("economia", "Ferias y eventos de promoción económica", 1, "40 ferias y eventos realizados", "40 ferias y eventos"),
        P("economia", "Proyecto de hub logístico y comercial de Lima Norte y modernización de mercados tradicionales", 1, "mercados tradicionales en proceso de modernización", "1 proyecto de hub logístico gestionado y 50 % de mercados en modernización"),
        P("ambiente", "Recuperar y mantener áreas verdes en el distrito", 1, "Incrementar en 50 hectáreas las áreas verdes", "50 hectáreas más de áreas verdes"),
        P("ambiente", "Puntos de segregación y reciclaje y campañas de limpieza pública", 2, "Implementar 100 puntos de segregación y reciclaje", "100 puntos de segregación y reciclaje"),
        P("gestion", "Digitalizar los trámites municipales más demandados", 2, "Digitalizar el 80% de los trámites municipales", "80 % de los trámites más demandados digitalizados"),
        P("gestion", "Audiencias públicas de rendición de cuentas durante la gestión", 2, "Realizar 16 audiencias públicas de rendición de cuentas", "16 audiencias públicas"),
    ]),
    ("Fernando Guillermo Agurto Montesinos", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Central Integrada de Videovigilancia y Respuesta articulada con serenazgo, juntas vecinales y la PNP", 95, "CENTRAL INTEGRADA DE VIDEOVIGILANCIA Y RESPUESTA MUNICIPAL", "40 % más de cobertura de vigilancia y capacidad de respuesta en sectores priorizados"),
        P("seguridad", "Programa «Mi Barrio Seguro» de juntas vecinales y vigilancia comunitaria", 96, "Fortalecimiento de la organización vecinal mediante juntas vecinales", "60 % más de participación vecinal organizada en seguridad"),
        P("social", "Centro Municipal de Salud Preventiva y Salud Mental con orientación psicológica y atención comunitaria", 93, "CENTRO MUNICIPAL DE SALUD PREVENTIVA Y SALUD MENTAL", "Más de 10 000 vecinos al año en programas de salud mental"),
        P("social", "Programa distrital contra la anemia articulado con establecimientos de salud y centros educativos", 93, "PROGRAMA DISTRITAL DE LUCHA CONTRA LA ANEMIA"),
        P("social", "Escuelas municipales deportivas y culturales permanentes para niños, adolescentes y jóvenes", 94, "ESCUELAS MUNICIPALES DEPORTIVAS Y CULTURALES", "Más de 15 000 niños y jóvenes al año"),
        P("economia", "Bolsa de Trabajo Municipal, programas de primer empleo y ferias laborales", 94, "BOLSA DE TRABAJO MUNICIPAL", "Más de 10 000 jóvenes al año en programas de empleabilidad"),
        P("economia", "Programa de formalización empresarial con asesoría técnica y simplificación administrativa", 94, "PROGRAMA DE FORMALIZACIÓN EMPRESARIAL", "Formalizar al menos el 60 % de los negocios informales identificados"),
        P("urbano", "Programa «Parques para Todos» de recuperación y ampliación de parques y espacios públicos", 95, "Recuperación, mantenimiento y ampliación de parques", "80 % de los espacios públicos priorizados recuperados"),
        P("ambiente", "Programa «Puente Piedra Limpia» de limpieza pública, reciclaje y educación ambiental", 96, "Fortalecimiento de la limpieza pública, educación ambiental, reciclaje"),
        P("agua_riesgos", "Plan distrital de espacios seguros y evacuación, con señalización y acondicionamiento ante desastres", 96, "PLAN DISTRITAL DE ESPACIOS SEGUROS Y EVACUACIÓN ANTE DESASTRES"),
        P("gestion", "Plataforma integral de gobierno digital con trámites virtuales", 95, "PLATAFORMA INTEGRAL DE GOBIERNO DIGITAL"),
    ]),
    ("Esteban Felizardo Monzón Fernández", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Tecnología de punta para el serenazgo, con nuevo software de seguridad ciudadana", 13, "Incorporación de Tecnología de punta en el servicio de SSCC"),
        P("seguridad", "Programa «Condominio Seguro» con control de acceso en los barrios monitoreado por la municipalidad", 13, "Implementación del programa Condominio Seguro"),
        P("social", "Academias municipales preuniversitarias", 15, "Creación 3 academia municipal preuniversitaria", "3 academias preuniversitarias"),
        P("social", "Ampliar el fondo de becas universitarias y las bibliotecas municipales descentralizadas", 15, "Se ampliará el fondo de Beca Universitario"),
        P("social", "Reabrir los estadios Santa Rosa y Central y equipar losas deportivas en las tres zonas", 15, "Toldeado y iluminación de 30 lozas", "30 losas toldeadas e iluminadas"),
        P("social", "Convenio con SISOL para un hospital municipal y Hospitales de la Solidaridad en las zonas Norte y Sur", 18, "Instalación de Hospitales de la Solidaridad en la Zona Norte y Sur"),
        P("social", "Local habilitado para adultos mayores en cada zona del distrito", 19, "Local habilitado para las personas de la tercera edad en cada zona"),
        P("gestion", "Política «Papel Cero», firma digital en todas las unidades y audiencias públicas en las tres zonas", 21, "Implementación de la Firma Digital en todas las Unidades Orgánicas"),
        P("ambiente", "Contenedores soterrados en zonas densas y nuevas compactadoras para el recojo de residuos", 24, "Construcción de contenedores soterrados en zonas con alta densidad"),
        P("ambiente", "Pozos tubulares, reservorios y riego tecnificado, con siembra de árboles en las tres zonas", 25, "Construcción de 10 pozos tubulares", "10 pozos tubulares, 10 reservorios y 1 000 árboles por año"),
        P("economia", "Zonas comerciales con incentivos tributarios y operativos contra el comercio informal en espacios públicos", 26, "habilitación y promoción de zonas comerciales con incentivos tributarios"),
    ]),
]
