"""El Agustino (150111): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150111"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Ernesto Mikhajil Colqui Bedregal", "Acción Popular", "accion-popular", [
        P("seguridad", "Centro de Monitoreo Inteligente con cámaras HD, lectura de placas, vigilancia las 24 horas e integración con la Policía", 8, "500 cámaras de videovigilancia HD", "500 cámaras de videovigilancia"),
        P("seguridad", "Más serenos y compra de motocicletas, camionetas y bicicletas para el patrullaje", 9, "Duplicar el número de serenos", "Duplicar el número de serenos"),
        P("seguridad", "Programa «Barrio seguro» con alarmas vecinales y aplicativo de emergencias, priorizando 7 de Octubre, Ancieta, Tayacaja, Santoyo, Villa Hermosa y San Cayetano", 9, "Organización vecinal, redes comunitarias, alarmas vecinales", "Reducir la delincuencia en 50 %"),
        P("urbano", "Programas «Pistas para todos» y «Veredas seguras» con rampas para personas con discapacidad", 10, "Renovación de 100 km. de pistas", "100 km de pistas renovadas"),
        P("urbano", "Cambio de luminarias a LED e instalación de postes en zonas oscuras", 10, "Sustitución de luminarias por LED", "100 % de calles principales iluminadas"),
        P("ambiente", "Reforestación distrital y conversión de terrenos abandonados en parques", 11, "50 000 árboles", "50 000 árboles, 100 000 plantas ornamentales y 50 % más de áreas verdes"),
        P("ambiente", "Programa «Basura cero»: nuevas compactadoras, rutas optimizadas y reciclaje con segregación en origen e incentivos a recicladores", 11, "Renovación de la flota de compactadoras"),
        P("economia", "Centro Municipal de Emprendimiento, bolsa de trabajo, programa «Mujer emprendedora» y ventanilla única de formalización", 12, "Capacitar a 10 000 vecinos emprendedores", "10 000 emprendedores capacitados, 5 000 empleos promovidos y más de 300 negocios formalizados"),
        P("transporte", "Formalizar mototaxis y mejorar la seguridad vial con rompemuelles, señalización y educación vial", 12, "Formalización de mototaxis"),
        P("social", "Campañas de salud en los barrios, atención psicológica gratuita y lucha contra la anemia con el MINSA", 15, "Reducir la anemia infantil en 20%", "Reducir la anemia infantil en 20 %"),
        P("gestion", "Municipalidad digital con trámites virtuales, expediente electrónico, aplicativo de reclamos y rendición trimestral de cuentas", 17, "80% de trámites digitalizados", "80 % de trámites digitalizados"),
    ]),
    ("Miguel Hernán García Arias", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Sistema Distrital de Seguridad Inteligente con más videovigilancia, monitoreo y patrullaje integrado, y juntas vecinales fortalecidas", 5, "Implementar el Sistema Distrital de Seguridad Inteligente en todo el distrito", "Sistema implementado en todo el distrito al término del período"),
        P("social", "Modernizar la infraestructura y el equipamiento del Policlínico Municipal y hacer campañas médicas descentralizadas", 6, "Fortalecimiento del Policlínico Municipal"),
        P("social", "Programa contra la anemia infantil con tamizaje y educación alimentaria, más prevención dental y visual para escolares", 6, "Programa Distrital de Reducción de la Anemia Infantil"),
        P("social", "Construir y equipar el Teatro Municipal y recuperar la infraestructura deportiva, recreativa y cultural", 7, "construir, equipar y poner en funcionamiento el Teatro Municipal", "100 % de la infraestructura priorizada recuperada, modernizada o implementada"),
        P("social", "Red de centros de capacitación gratuita en competencias digitales, inteligencia artificial y emprendimiento para jóvenes", 8, "Red Distrital de Innovación, Tecnología e Inteligencia Artificial"),
        P("economia", "Talleres municipales equipados (gastronomía, confección, corte láser) cuyos egresados pueden usar los equipos pagando solo costos operativos", 11, "pagando únicamente costos operativos básicos"),
        P("economia", "Equipar a comedores populares y ollas comunes que emprendan en gastronomía con hornos, cámaras de refrigeración y otros equipos", 11, "equipamiento progresivo de comedores populares"),
        P("gestion", "Plan Obligatorio de Rendición de Cuentas con audiencias públicas", 10, "al menos dos audiencias públicas anuales", "Al menos 2 audiencias públicas al año"),
        P("gestion", "Municipalidad Digital con servicios virtuales, expedientes electrónicos, firmas digitales y pagos en línea", 9, "expedientes electrónicos, firmas digitales y pagos en línea"),
        P("ambiente", "Plan de arborización, riego tecnificado y apoyo a la formalización de recicladores", 12, "Plan Distrital de Arborización y Cobertura Verde"),
        P("agua_riesgos", "Fortalecer la gestión del riesgo de desastres con acciones preventivas ante lluvias, deslizamientos e inundaciones", 12, "acciones preventivas frente a lluvias intensas, deslizamientos e inundaciones urbanas"),
    ]),
    ("Víctor Modesto Salcedo Ríos", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Programa «El Agustino Seguro 24 Horas»: central de monitoreo, drones, botón de pánico por aplicativo, alarmas comunitarias y patrullaje con la PNP", 6, "Implementación de drones de vigilancia", "Reducir en 40 % los delitos de mayor incidencia y duplicar la cobertura de videovigilancia al 2030"),
        P("social", "Reactivar la planta de oxígeno, recuperar el Policlínico Municipal y llevar brigadas médicas a los asentamientos humanos", 7, "Reactivación de la Planta de Oxigeno", "Reducir la anemia infantil en 30 % al 2030"),
        P("social", "Programa de becas municipales y academias preuniversitaria, prepolicial y premilitar", 9, "Otorgar 2,000 becas municipales", "2 000 becas y 10 000 estudiantes beneficiados al 2030"),
        P("economia", "Programa «El Agustino Emprende» con asesoría gratuita para formalizar y capacitación en marketing digital y comercio electrónico", 14, "Formalizar 5,000 negocios", "5 000 negocios formalizados y 15 000 emprendedores capacitados al 2030"),
        P("economia", "Bolsa Municipal de Trabajo, plataforma digital de empleo y Programa Primer Empleo", 14, "20,000 vecinos colocados laboralmente", "20 000 vecinos colocados y 500 convenios empresariales al 2030"),
        P("gestion", "Programa «Municipalidad Inteligente» con expediente electrónico, firma digital, aplicativo y atención virtual las 24 horas", 19, "90% de trámites digitalizados", "90 % de trámites digitalizados y 70 % menos en tiempos de atención al 2030"),
        P("ambiente", "Programa «El Agustino Verde» con arborización, corredores ecológicos y reforestación de laderas", 28, "Plantar 50,000 árboles", "50 000 árboles y 40 % más de áreas verdes al 2030"),
        P("ambiente", "Nuevas compactadoras, contenedores inteligentes, centros de acopio y formalización de recicladores", 29, "Reducción del 50% de puntos críticos de residuos", "100 % de cobertura de recolección y 50 % menos puntos críticos al 2030"),
        P("urbano", "Pavimentación de vías, veredas, escaleras en zonas altas y accesibilidad universal", 34, "100 kilómetros de vías mejoradas", "100 km de vías mejoradas al 2030"),
        P("transporte", "Plan Integral de Movilidad Urbana con semáforos inteligentes, mejores paraderos y fiscalización del transporte informal", 34, "Implementación de semáforos inteligentes"),
        P("agua_riesgos", "Actualizar el mapa de riesgos, sistema de alerta temprana, simulacros y equipamiento de Defensa Civil", 31, "Actualización del mapa de riesgos"),
    ]),
    ("Juan David Barrientos Arce", "Alianza Regional por el Perú", "alianza-regional-por-el-peru", [
        P("seguridad", "Ampliar el serenazgo, reorganizado por zonas y con geolocalización", 7, "Incremento de Serenos hasta 300 efectivos", "Hasta 300 serenos; reducir 50 % la percepción de inseguridad al 2030"),
        P("social", "Red de promotores de salud para prevenir la anemia, la tuberculosis y enfermedades crónicas", 7, "Red de promotores de salud para prevención de anemia", "Reducir la anemia infantil en 50 % al 2030"),
        P("social", "Programa «Agustino con los Jóvenes» con deporte, cultura y talleres preventivos en escuelas", 7, "deporte, cultura y talleres preventivos en escuelas"),
        P("social", "Casas Refugio para víctimas de violencia familiar y fortalecimiento de la DEMUNA", 7, "Casas Refugio para víctimas de violencia familiar"),
        P("economia", "Formalizar el comercio ambulante y las mototaxis con regulación y seguridad", 8, "Formalización del comercio ambulante y mototaxis", "100 % de formalización del comercio al 2030"),
        P("economia", "Convenios con instituciones técnicas para capacitar a jóvenes en oficios", 8, "Convenios con instituciones técnicas para capacitación de jóvenes", "Reducir el desempleo juvenil en 50 % al 2030"),
        P("transporte", "Teleféricos en las zonas elevadas y mejoramiento de las vías principales", 8, "teleféricos en zonas elevadas", "2 teleféricos operativos al 2030"),
        P("urbano", "Actualizar el catastro y elaborar un Plan Urbano integral", 8, "Catastro actualizado y Plan Urbano integral", "100 % del territorio formalizado al 2030"),
        P("ambiente", "Forestación urbana y ampliación de áreas verdes, con reciclaje y compostaje", 8, "Forestación urbana y ampliación de áreas verdes", "Mínimo 8 m² de áreas verdes por habitante y 100 % de residuos gestionados al 2030"),
        P("agua_riesgos", "Programas de prevención ante sismos y otros desastres", 8, "Programas de prevención ante riesgos sísmicos"),
        P("gestion", "Evaluaciones trimestrales de proyectos publicadas en medios digitales y audiencias, y portal de transparencia de presupuestos y obras", 8, "Evaluaciones trimestrales de los proyectos y políticas municipales"),
    ]),
    ("Irellis Lisbbet Muchaypiña Barriales", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Sistema de vigilancia integral con cámaras y aplicativo para el serenazgo y las organizaciones vecinales", 19, "Implementación del Sistema de Vigilancia integral e inteligente"),
        P("seguridad", "Nuevas camionetas, motos y equipos de comunicación conectados al centro de control, y cámaras según el mapa del delito", 22, "Equipamiento en unidades nuevas para el servicio de Seguridad Ciudadana"),
        P("social", "Farmacia municipal en el Hospital de la Solidaridad con medicamentos genéricos a precio de fábrica", 20, "farmacia municipal donde todos puedan acceder a medicamentos genéricos"),
        P("social", "Plan TBCero contra la tuberculosis en alianza con el MINSA, la Dirección de Salud Lima Este y la UGEL 05", 23, "Elaboración e Implementación del Plan TBCero"),
        P("agua_riesgos", "Mejorar la red domiciliaria de agua y alcantarillado con micromedición y campañas de uso racional del agua", 20, "instalación de micro medición"),
        P("transporte", "Ciclovías en las vías principales y control automatizado de velocidad en las arterias del distrito", 21, "Construcción de ciclovías en las principales vías"),
        P("urbano", "Recuperar las riberas del río Rímac con un boulevard ribereño como área verde y pública", 19, "Boulevar Ribereño Rímac"),
        P("economia", "Crédito municipal con la MML y la Caja Municipal para jóvenes emprendedores con proyectos competitivos", 24, "hasta 3,000 soles por proyecto", "Hasta S/ 3 000 por proyecto"),
        P("ambiente", "Plan de reforestación con forestación de cerros regada con aguas residuales tratadas, con apoyo del Ministerio de Vivienda y SEDAPAL", 26, "triplicar el número de árboles y duplicar las áreas verdes", "Triplicar los árboles y duplicar las áreas verdes"),
        P("ambiente", "Plan Integral de Residuos Sólidos y monitoreo de la calidad del aire en puntos críticos", 26, "en seis meses un Plan Integral de Residuos", "Plan de residuos en seis meses"),
        P("gestion", "Agencias municipales descentralizadas en las partes altas y automatización de servicios con gobierno electrónico", 27, "creando agencias descentralizadas y priorizando las partes altas"),
    ]),
    ("Jackeline Stephany Muñoz Calderón", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("seguridad", "Cámaras, alarmas vecinales, patrullaje integrado serenazgo-PNP y juntas vecinales fortalecidas", 10, "Instalar 300 cámaras de videovigilancia", "300 cámaras, 100 juntas vecinales fortalecidas y más de 30 000 vecinos beneficiados"),
        P("social", "Programa «El Agustino Te Escucha» con brigadas psicológicas itinerantes y orientación psicológica gratuita", 10, "brigadas psicológicas itinerantes", "Más de 20 000 vecinos atendidos"),
        P("social", "Campañas integrales de salud con atención médica, odontológica, visual y nutricional en asentamientos humanos", 10, "Realizar al menos 150 campañas integrales de salud", "Al menos 150 campañas y más de 50 000 vecinos beneficiados"),
        P("social", "Fortalecer comedores populares, campañas contra la anemia y huertos comunitarios", 11, "Fortalecer el 100% de comedores populares registrados", "100 % de comedores registrados y más de 15 000 vecinos beneficiados"),
        P("agua_riesgos", "Mapas de riesgo, brigadas comunitarias, simulacros descentralizados y capacitación en primeros auxilios", 13, "Capacitar a más de 5,000 vecinos y conformar brigadas comunitarias", "Más de 5 000 vecinos capacitados y brigadas en todos los sectores priorizados"),
        P("ambiente", "Segregación en la fuente con puntos ecológicos y formalización de recicladores", 13, "Incorporar a 20,000 hogares en programas de segregación", "20 000 hogares en segregación y reciclaje"),
        P("ambiente", "Plan distrital de arborización y recuperación de parques y bermas", 13, "Plantar 10,000 árboles y recuperar 30 espacios públicos", "10 000 árboles y 30 espacios públicos y áreas verdes recuperados"),
        P("ambiente", "Registro de rescatistas, esterilizaciones gratuitas, adopción responsable y registro de mascotas", 12, "Registro Municipal de Rescatistas y Protectores Animales", "12 000 esterilizaciones, 2 000 adopciones y 15 000 mascotas registradas"),
        P("economia", "Concurso anual «Emprendedor Agustiniano del Año» con capital semilla, mentoría y seguimiento", 15, "Emprendedor Agustiniano del Año", "Al menos 200 emprendimientos financiados y acompañados"),
        P("economia", "Ventanilla Única del Emprendedor con asesoría gratuita para constituir empresas y jornadas de formalización", 16, "Contribuir a la formalización de 1,500 negocios", "1 500 negocios formalizados"),
        P("gestion", "Rendición de cuentas y publicación accesible de la ejecución presupuestal, con audiencias descentralizadas", 18, "Realizar rendiciones de cuentas semestrales", "Rendiciones de cuentas semestrales"),
    ]),
    ("Félix Mario Ventura Rivera", "Fuerza Popular", "fuerza-popular", [
        P("social", "Programa «Salud y Nutrición con Orden» con comedores y Vaso de Leche: tamizajes y complementos ricos en hierro en asentamientos vulnerables", 2, "Salud y Nutrición con Orden", "Reducir la anemia infantil al 18 % al 2030"),
        P("social", "Capacitación productiva temprana para escolares de secundaria en convenio con CETPRO y empresas locales", 2, "en convenios con CETPROs y empresas locales", "Deserción escolar de 1,5 % o menos al 2030"),
        P("urbano", "Recuperar losas deportivas y parques con iluminación LED y videovigilancia", 2, "iluminación LED y videovigilancia integrada", "100 % de losas deportivas y parques recuperados"),
        P("economia", "Estrategia «Licencia Express» para formalizar a las micro y pequeñas empresas", 2, "para la formalización inmediata de las", "Informalidad comercial al 60 % al 2030"),
        P("economia", "Bolsas de trabajo distritales vinculadas a incentivos tributarios para empresas locales", 2, "bolsas de trabajo distritales ligadas a incentivos"),
        P("urbano", "Saneamiento físico-legal y formalización de planos con COFOPRI y la MML para destrabar servicios básicos en los cerros", 2, "en coordinación estrecha con COFOPRI", "Formalización y visación del 80 % de sectores pendientes"),
        P("ambiente", "Recolección fiscalizada por GPS y erradicación de puntos críticos en Av. Riva Agüero, Av. José Carlos Mariátegui y la ribera del Rímac", 2, "Av. José Carlos Mariátegui y la ribera del río", "Reciclaje y segregación distrital al 25 % al 2030"),
        P("ambiente", "Programa «El Agustino Verde» con riego tecnificado para ampliar las áreas verdes", 2, "para expandir los metros cuadrados de áreas verdes por habitante", "Mínimo 4 m² de áreas verdes por habitante al 2030"),
        P("ambiente", "Programa «Vecino Recicla» de capacitación en segregación en origen", 2, "para capacitar formalmente a 15,000 ciudadanos", "15 000 vecinos capacitados"),
        P("seguridad", "Serenazgo con enfoque de Tolerancia Cero, patrullaje con la PNP y cámaras con reconocimiento facial y de placas en Puente Nuevo y la Vía de Evitamiento", 2, "cámaras de última generación con analítica de reconocimiento", "Percepción de inseguridad al 45 % al 2030"),
        P("gestion", "Presupuesto participativo con herramientas virtuales para fiscalizar obras y trámites 100 % digitales", 2, "involucrar a más de 7,000 vecinos", "Al menos 7 000 vecinos participando; 50 % menos plazos de trámite"),
    ]),
    ("Agustín Rojas Guzmán", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Plan Integral de Seguridad con más videovigilancia y serenazgo, comités vecinales, brigadas juveniles y rondas urbanas", 1, "Ampliación del sistema de videovigilancia", "100 % de zonas críticas monitoreadas, 110 juntas vecinales y 30 % menos delitos de mayor incidencia"),
        P("social", "Campañas permanentes de salud preventiva y programas de nutrición comunitaria", 2, "40 campañas anuales", "40 campañas al año y 50 000 vecinos beneficiados"),
        P("social", "Escuelas deportivas municipales, bibliotecas físicas y virtuales y talleres artísticos", 2, "5 escuelas deportivas activas", "5 escuelas deportivas, 5 bibliotecas digitales y 15 000 beneficiarios"),
        P("economia", "Centro Municipal de Desarrollo Empresarial con capacitación, ferias y formalización", 2, "Centro Municipal de Desarrollo Empresarial", "1 000 MYPES capacitadas y 500 negocios formalizados"),
        P("economia", "Bolsa de trabajo municipal y capacitación técnica en convenio con SENATI e institutos", 2, "Convenios con SENATI e institutos", "5 000 personas capacitadas y 3 000 empleos promovidos"),
        P("gestion", "Educación tributaria, incentivos al contribuyente puntual y modernización del sistema tributario", 3, "Incentivos al contribuyente puntual", "25 % más de recaudación y 20 % menos morosidad"),
        P("ambiente", "Arborización de cerros y avenidas, viveros municipales y programa «Un vecino, un árbol»", 3, "Arborización de cerros y avenidas", "50 000 árboles y 100 000 m² recuperados"),
        P("ambiente", "Segregación en la fuente, formalización de recicladores y educación ambiental", 3, "Formalización de recicladores", "40 % más de reciclaje y recolección en el 100 % del distrito"),
        P("ambiente", "Fiscalización ambiental, campañas de descontaminación del río Rímac y control de emisiones vehiculares", 3, "Control de emisiones vehiculares", "Recuperar el 80 % de puntos críticos"),
        P("gestion", "Gobierno digital con simplificación administrativa y digitalización de trámites", 4, "90% de trámites virtualizados", "90 % de trámites virtualizados y 50 % menos tiempo de atención"),
        P("gestion", "Portal de transparencia en tiempo real, audiencias públicas y vigilancia ciudadana de obras", 4, "Audiencias públicas semestrales", "2 audiencias públicas al año y 100 % de proyectos con información pública"),
    ]),
    ("Jorge Vivanco Zarate", "Partido de los Trabajadores y Emprendedores PTE Perú", "partido-de-los-trabajadores-y-emprendedores-pte-peru-comunidad-politica-inka-peru", [
        P("seguridad", "«Serenazgo Simétrico»: compra de vehículos y contratación de nuevos agentes, con paridad de género y capacitación en resolución de conflictos", 2, "Compra de 80 nuevos vehículos", "80 vehículos y 120 nuevos agentes"),
        P("seguridad", "Ampliar el patrullaje integrado serenazgo–PNP y subsidiar la conexión de cámaras vecinales a la central del CODISEC", 2, "de 5 a 9 sectores", "Patrullaje integrado de 5 a 9 sectores; 100 % de sectores al 2030"),
        P("social", "«Ruta de Atención a Mujeres Víctimas» en centros de salud y comisarías, casas de refugio temporal y capacitación de serenos y policías", 2, "Ruta de Atención a Mujeres Víctimas", "Denuncias de violencia contra la mujer de 7,9 a 6,5 por cada 10 000 habitantes al 2030"),
        P("social", "Programa «Nivelación INKA» con docentes contratados y refuerzo escolar en los colegios con menor rendimiento", 2, "Nivelación INKA", "15 instituciones educativas con menor rendimiento"),
        P("social", "Sala de cómputo con internet de alta velocidad en los colegios públicos", 3, "Tecnología para el Futuro", "100 % de las instituciones educativas públicas"),
        P("social", "Programa «Cuna Saludable» contra la anemia: visitas domiciliarias y entrega de multimicronutrientes a madres de niños de 0 a 12 meses", 3, "Cuna Saludable", "Anemia en niños de 6 a 35 meses del 35,3 % al 16,8 % al 2030"),
        P("economia", "Ventanilla Única para Emprendedores con asesoría legal, contable y de marketing digital gratuita", 3, "Ventanilla Única para Emprendedores"),
        P("economia", "«Bono Municipal de Formalización»: descuento total en licencias y multas por un año para MYPES que se formalicen en el primer semestre", 3, "Bono Municipal de Formalización", "Emprendedores formalizados de 3 000 a 5 250 al 2030"),
        P("ambiente", "Limpieza en emergencia de los puntos críticos de basura, programa «Adopta un Parque» y Malecón Ecológico del Rímac", 4, "29 puntos críticos de basura", "100 % de puntos críticos erradicados; áreas verdes de 1,37 a 1,65 m² por habitante"),
        P("ambiente", "Segregación en la fuente «Separa en Casa, Gana el Barrio» y planta de valorización de residuos orgánicos para producir compost", 4, "Separa en Casa, Gana el Barrio", "Residuos reciclados del 1,57 % al 4,5 %"),
        P("gestion", "Plataforma «Tu Trámite en Línea» para los trámites más demandados (licencias, partidas, etc.)", 4, "Tu Trámite en Línea", "10 procedimientos con plazo reducido a 48 horas"),
    ]),
    ("Carlos Alexander Ramos Amante", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Interconectar todas las cámaras municipales con las comisarías El Agustino, San Pedro, Villa Hermosa y San Cayetano, con patrullaje integrado las 24 horas", 10, "Interconectar tecnológicamente el 100% de las cámaras", "100 % de cámaras municipales interconectadas con las comisarías"),
        P("seguridad", "Plan «Escudo Agustino Inteligente»: red de cámaras con reconocimiento facial e IA en puntos críticos (Puente Nuevo, Riva Agüero) y duplicar las unidades de serenazgo", 17, "200 cámaras con reconocimiento facial", "200 cámaras; reducir en 55 % la percepción e incidencia delictiva al término de la gestión"),
        P("social", "Programa «Cunas Agustinas sin Anemia» con ollas comunes y comedores: hierro, alimentos fortificados y control mensual en un policlínico móvil", 16, "Cunas Agustinas sin Anemia", "Anemia infantil por debajo de 15 % al 2030"),
        P("social", "Centro de Atención Psicológica Municipal gratuito para prevenir la violencia familiar y tratar adicciones", 11, "Centro de Atención Psicológica Municipal"),
        P("social", "Becas con universidades e institutos para jóvenes destacados y Festival Deportivo Anual Interbarrios e Interescolar", 12, "Festival Deportivo Anual Interbarrios", "40 % más de uso vecinal de losas deportivas recuperadas"),
        P("economia", "Plataforma «Emprende Agustino Ya»: licencia de funcionamiento digital gratuita en 24 horas a cambio de capacitación, y ferias de productores", 17, "Emprende Agustino Ya", "6 000 microcomerciantes y emprendedores formalizados al 2030"),
        P("economia", "Escuela Municipal de Innovación y Oficios Digitales con cursos gratuitos certificados de programación, marketing digital y robótica", 17, "Escuela Municipal de Innovación y Oficios Digitales", "4 000 jóvenes insertados en empleo formal o autoempleo"),
        P("ambiente", "Arborización masiva de los cerros con riego por goteo con aguas tratadas, recuperación de bermas y techos verdes", 18, "El Agustino Verde y Oxigenado", "5,5 m² de áreas verdes por habitante al 2030"),
        P("ambiente", "Programa «Tu Basura Vale»: descuentos en arbitrios por segregar plástico, vidrio y cartón, y flota de recojo con rutas por GPS", 18, "Tu Basura Vale", "75 % de segregación en origen y 100 % de botaderos erradicados"),
        P("agua_riesgos", "Muros de contención y escaleras con pasamanos en laderas, y gestión ante SEDAPAL de redes de agua y alcantarillado para los sectores altos", 13, "muros de contención de concreto armado"),
        P("gestion", "Aplicación «Municipio Digital 24/7» para partidas, pagos y quejas, y transmisión en vivo de sesiones de concejo y licitaciones", 19, "Municipio Digital 24/7", "70 % menos tiempo de tramitación"),
    ]),
    ("Ana Cecilia Buleje Castillo", "Somos Perú", "partido-democratico-somos-peru", [
        P("gestion", "Audiencias públicas, cabildos y mesas de diálogo como sistema distrital de participación ciudadana", 25, "Realizar al menos 4 audiencias públicas", "Al menos 4 audiencias públicas y 12 mesas de diálogo por año"),
        P("social", "Escuelas deportivas y talleres culturales descentralizados", 25, "Implementar escuelas deportivas y talleres culturales descentralizados", "Programas permanentes en el 100 % de sectores"),
        P("seguridad", "Fortalecer la seguridad ciudadana con patrullaje integrado, tecnología y participación vecinal", 26, "Fortalecer la seguridad ciudadana mediante patrullaje integrado", "50 % más capacidad operativa de seguridad ciudadana"),
        P("social", "Comités Sectoriales de Acción Rápida para atender casos de violencia contra la mujer y la familia", 26, "Comités Sectoriales de Acción Rápida", "100 % de sectores con un comité operativo"),
        P("social", "Programas preventivos de orientación familiar y salud mental en coordinación con colegios y centros de salud", 26, "programas preventivos de orientación familiar y salud mental", "100 % de colegios en programas preventivos"),
        P("social", "Fortalecer el Policlínico Municipal de El Agustino", 26, "Fortalecer el Policlínico Municipal", "Expediente técnico aprobado"),
        P("transporte", "Plan Distrital de Movilidad Urbana Sostenible e intervención de intersecciones críticas", 26, "Plan Distrital de Movilidad Urbana Sostenible", "Reducir en 30 % los puntos críticos de congestión vehicular"),
        P("agua_riesgos", "Mejorar la infraestructura y el equipamiento de las compañías de bomberos del distrito", 27, "compañías de bomberos del distrito", "Modernizar el 100 % de la infraestructura y equipamiento disponible"),
        P("economia", "Capacitación de emprendedores y simplificación de trámites para la formalización", 27, "Capacitar a 5,000 emprendedores", "5 000 emprendedores capacitados durante la gestión"),
        P("ambiente", "Plan Distrital de Manejo de Residuos Sólidos y programa de arborización «Agustino Verde»", 28, "Plan Distrital de Manejo de Residuos", "30 % más de reciclaje formal y 20 % más de áreas verdes públicas"),
        P("gestion", "Gobierno Digital Municipal y simplificación de procedimientos administrativos", 28, "Digitalizar el 80% de los trámites municipales", "80 % de trámites digitalizados y 50 % menos tiempo de atención"),
    ]),
    (None, "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Sistema de alerta ciudadana para que los vecinos reporten delitos y el serenazgo acuda de inmediato, con descentralización del centro de operaciones", 15, "sistema de atención de alerta ciudadana"),
        P("seguridad", "Ampliar las cámaras de videovigilancia y alarmas en zonas críticas y donde lo pidan los comités vecinales", 15, "Ampliar la cobertura de cámaras de video vigilancia"),
        P("social", "Casa Municipal de la Salud con programas de prevención para reducir los casos de tuberculosis", 17, "Casa Municipal de la Salud"),
        P("transporte", "Aplicativo para formalizar el servicio de mototaxis, con los datos de cada conductor", 19, "similar al uber"),
        P("transporte", "Revisiones técnicas para vehículos menores, sincronización de semáforos y prohibición del ingreso de vehículos de carga pesada", 20, "Implementar revisiones técnicas para vehículos menores"),
        P("social", "Centro Municipal de Educación Infantil para niños de 1 a 5 años y descentralización de la academia preuniversitaria PREMUNI", 24, "Crear el Centro Municipal de Educación infantil"),
        P("agua_riesgos", "Gestionar con las instituciones competentes la cobertura de agua y saneamiento en todo el distrito", 27, "para disminuir el déficit de agua a nivel distrital a 0%", "Déficit de agua y de saneamiento a 0 %"),
        P("economia", "Centro de innovación y desarrollo empresarial, y empadronamiento, capacitación y formalización del comercio ambulatorio", 29, "Centro de innovación y desarrollo empresarial"),
        P("gestion", "Actualizar el catastro distrital y vincularlo al Sistema Nacional Integrado de Catastro y al registro de predios", 34, "Sistema Nacional Integrado de Catastro"),
        P("ambiente", "Programas de reciclaje con microempresas, compra de compactadoras y monitoreo para eliminar puntos críticos de basura", 36, "Establecer programas de Reciclaje con apoyo a micro-empresas"),
        P("urbano", "Muros de contención, veredas y escaleras en las zonas altas, Malecón de la Amistad en el río Rímac y proyecto de teleférico", 42, "Construcción del Malecón de la Amistad Rio Rímac"),
    ]),
    ("Carlos Manuel Juscamayta Cosme", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Cámaras vinculadas en tiempo real con el centro de control y tele alarmas vecinales con pulsadores", 47, "Implementación progresiva de 1000 Cámaras", "1 000 cámaras y 100 tele alarmas vecinales"),
        P("seguridad", "Grupo de Operaciones Especiales con exmiembros de la PNP y las Fuerzas Armadas, y grupo de pilotos de drones para patrullaje aéreo", 47, "Grupo de Operaciones Especiales"),
        P("social", "Academia Municipal Preuniversitaria y de Formación Técnica, con becas y convenios con universidades e institutos", 46, "Academia Municipal Preuniversitaria"),
        P("social", "Casa de la Familia con orientación psicológica, asesoría legal, prevención de la violencia familiar y atención en salud mental", 49, "CASA DE LA FAMILIA"),
        P("social", "Primer Centro Municipal Integral para personas con Trastorno del Espectro Autista, con terapias a costo social", 50, "Trastorno del Espectro Autista"),
        P("ambiente", "Programa «RECAPACICLA» de segregación en la fuente, reciclaje, valorización de residuos y formalización de recicladores", 47, "RECAPACICLA"),
        P("economia", "Centro Municipal de Emprendimiento, Innovación y Empleo con capacitación en gestión empresarial, finanzas y comercio electrónico", 49, "Centro Municipal de Emprendimiento, Innovación y Empleo"),
        P("agua_riesgos", "Escaleras, muros de contención, barandas y obras de mitigación de riesgos en las zonas altas y la ribera del río", 49, "Programa de Construcción y Mejoramiento de Escaleras"),
        P("urbano", "Construcción, rehabilitación y mantenimiento de pistas y veredas en todos los sectores, priorizando las zonas más olvidadas", 51, "PLAN 100 CUADRAS PARA EL AGUSTINO", "100 cuadras"),
        P("transporte", "Cuerpos de inspectores municipales de transporte por tipo de servicio y semáforos con sensor de movimiento", 52, "Crear 6 cuerpos de inspectores Municipales de Transporte", "6 cuerpos de inspectores"),
        P("gestion", "Programa «El Agustino Digital»: internet en espacios públicos, trámites municipales digitales y alfabetización tecnológica", 50, "El Agustino Digital"),
    ]),
    (None, "Podemos Perú", "podemos-peru", [
        P("seguridad", "Más cámaras de videovigilancia con inteligencia artificial, más serenos capacitados y nuevas camionetas para el patrullaje integrado", 63, "Incrementar en 500 cámaras de videovigilancia", "500 cámaras, 600 serenos más y 20 camionetas"),
        P("seguridad", "Programa «Comunidad Segura» (alarmas, cámaras, juntas vecinales) y tercera etapa de iluminación de avenidas, parques y espacios públicos", 64, "COMUNIDAD SEGURA", "S/ 3 millones para la III etapa de iluminación"),
        P("social", "Continuidad de «Muni Becas», monitoreo de estudiantes en riesgo de abandono y fondo de apoyo escolar con la empresa privada", 67, "Continuidad del Programa Municipal"),
        P("social", "Policlínico Municipal para atención primaria y Farmacia Municipal con medicamentos a bajo costo", 69, "Farmacia Municipal para promover el acceso a medicamentos", "1 500 adultos mayores atendidos en el Policlínico Municipal al 2030"),
        P("social", "Albergue temporal para víctimas de violencia familiar y sexual", 70, "Albergue temporal para atención a victimas"),
        P("ambiente", "Segregación en la fuente en viviendas y comercios, puntos de acopio «ReciclaElAgustino» y mercados con contenedores diferenciados", 78, "ReciclaElAgustino", "3,8 % de residuos sólidos valorizados al 2030"),
        P("agua_riesgos", "Gestionar ante el Ministerio de Vivienda y SEDAPAL la renovación de conexiones de agua y desagüe, y unidad técnica para titulación", 85, "Frente 1 y Frente 2", "2 proyectos de renovación de agua y desagüe con expediente técnico"),
        P("transporte", "Intercambio vial entre las avenidas Riva Agüero y Nicolás Ayllón, y vía adicional en el Puente Atarjea hacia Santa Anita", 86, "Construcción de Intercambio Vial entre la Av"),
        P("urbano", "Programa «Pueblo en Acción» de obras comunitarias (muros de contención, escaleras, espacios deportivos) con participación vecinal", 87, "Pueblo en Acción", "30 asentamientos humanos y comunidades atendidos al 2030"),
        P("economia", "Programa «Formalízate y Gana» con orientación gratuita, licencias simplificadas y ventanilla única empresarial", 92, "Formalizate y Gana", "6,98 % de mipymes en programas de formalización al 2030"),
        P("gestion", "Audiencias públicas descentralizadas de rendición de cuentas y mapa digital de obras ejecutadas, en proceso y planificadas", 82, "mapa digital de obras", "100 % de zonales con audiencias públicas descentralizadas"),
    ]),
    ("Carmen Carolina Castillo Yataco", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Central Smart El Agustino 360° con videovigilancia, inteligencia artificial, reconocimiento facial y de placas, drones y patrullaje integrado", 12, "Central Smart El Agustino 360", "1 central operativa, 250 cámaras inteligentes y 20 drones; patrullaje integrado en el 100 % de sectores"),
        P("seguridad", "Redes vecinales digitales y alarmas comunitarias", 13, "Implementar Redes Vecinales Digitales y Alarmas Comunitarias", "100 redes vecinales digitales y 500 alarmas comunitarias"),
        P("transporte", "Programa «Mototaxi Formal» de registro, empadronamiento y regulación de mototaxis", 14, "Programa Mototaxi Formal", "5 000 mototaxis registradas y formalizadas"),
        P("urbano", "Programa «La Familia Vuelve al Parque» para modernizar y mantener parques y áreas recreativas", 14, "La Familia Vuelve al Parque", "60 parques y espacios públicos recuperados"),
        P("economia", "Reordenar el comercio informal con alternativas de formalización o reubicación", 14, "Reordenamiento del comercio informal con alternativas formales", "1 500 comerciantes formalizados o reubicados"),
        P("gestion", "Programa «Municipio en tu Mano – El Agustino Digital» para atención al vecino y pago de tributos en línea", 15, "plataforma digital de atención al vecino", "80 % de trámites y pagos disponibles en línea"),
        P("economia", "Museo del Migrante Peruano y corredor gastronómico de comidas típicas de Lima Este", 16, "Museo del Migrante Peruano", "1 museo abierto y 80 establecimientos en el corredor gastronómico"),
        P("urbano", "Programa «Tu Barrio Conectado» para mejorar pistas, veredas, muros de contención y accesibilidad urbana", 17, "Tu Barrio Conectado", "150 000 m² de pistas, veredas, muros y accesos mejorados"),
        P("ambiente", "Programa «El Agustino Más Verde» de arborización y mantenimiento de áreas verdes", 17, "arborización y mantenimiento de áreas verdes", "10 000 árboles plantados y 20 hectáreas de áreas verdes recuperadas"),
        P("social", "Casa de la Mujer Agustiniana para prevenir la violencia familiar y atender a las víctimas", 17, "Casa de la Mujer Agustiniana", "10 000 mujeres atendidas"),
        P("social", "Programa «Edad Dorada» de atención integral a adultos mayores (servicios médicos, recreación y clubes)", 18, "Programa Edad Dorada", "15 000 adultos mayores atendidos durante la gestión"),
    ]),
]
