"""Lince (150116): propuestas principales de los 11 planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150116"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Víctor Manuel Noriega Salazar", "Acción Popular", "accion-popular", [
        P("seguridad", "Programa «Lince Seguro 360»: más serenos, patrullaje por cuadrantes y central de monitoreo modernizada con cámaras con analítica de video", 6, "Implementar patrullaje por cuadrantes"),
        P("seguridad", "Recuperación de la «Zona Rosa»: fiscalización de establecimientos, prevención de la trata de personas e intervención urbana con iluminación y cámaras", 6, "Recuperación Integral de la Zona Rosa"),
        P("social", "Programa «Adulto Mayor 360» con salud preventiva, nutrición, actividad física, acompañamiento psicológico y alfabetización digital", 7, "Programa Adulto Mayor 360"),
        P("social", "Escuela Municipal de Tecnología e Innovación con cursos de programación, inteligencia artificial, robótica y comercio electrónico", 7, "Escuela Municipal de Tecnología e Innovación", "Al menos 2 000 vecinos capacitados en competencias digitales"),
        P("urbano", "Programa «Lince Sin Barreras» para adecuar rampas, cruces, señalización y espacios públicos accesibles", 7, "Programa Lince Sin Barreras"),
        P("economia", "Centro Municipal de Desarrollo Empresarial con asesoría en formalización, licencias, tributación, costos y marketing", 8, "Centro Municipal de Desarrollo Empresarial", "Formalizar u orientar al menos 500 unidades económicas"),
        P("economia", "Bolsa Laboral Distrital conectada con empresas y ferias laborales semestrales", 8, "Bolsa Laboral Distrital conectada", "Al menos 1 500 orientaciones o inserciones laborales"),
        P("ambiente", "Contenedores soterrados en zonas estratégicas y programa «Lince Recicla» con segregación en la fuente y recicladores formalizados", 9, "Programa Lince Recicla"),
        P("transporte", "Mejorar ciclovías y su conexión con ejes metropolitanos, bicicleteros públicos y cruces peatonales señalizados cerca de colegios", 10, "Mejoramiento de ciclovías existentes"),
        P("gestion", "Expediente electrónico con trazabilidad de trámites, mesa de partes virtual y tablero de control municipal con indicadores", 10, "Expediente electrónico y trazabilidad de trámites", "Al menos 80 % de los trámites priorizados digitalizados"),
        P("agua_riesgos", "Actualizar mapas de riesgo, crear brigadas comunitarias por zonas vecinales y realizar simulacros periódicos", 11, "Brigadas comunitarias por zonas vecinales"),
    ]),
    ("Nidia Alegría Herrera", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Instalar cámaras de vigilancia modernas, mejorar el centro de control y crear postes SOS y una app con botón de pánico", 5, "Implementación de 200 cámaras de vigilancia modernas", "200 cámaras operativas en 18 meses"),
        P("seguridad", "Ingreso al serenazgo por concurso público y reorganización en 9 cuadrantes con patrullaje en camionetas, motos, bicicletas y a pie", 5, "división en 9 cuadrantes", "Reducir los delitos denunciados 10 % el primer año y 20 % al tercer año"),
        P("transporte", "Subgerencia de Tránsito, serenos municipales de tránsito en avenidas principales y retiro de vehículos abandonados con un programa de chatarreo", 7, "Inventario y retiro de autos abandonados", "200 vehículos retirados el primer año"),
        P("gestion", "Gerencia de Participación Ciudadana, cabildos abiertos por zonas, app de relación directa con la alcaldía y Defensoría del Vecino", 7, "Crear Gerencia de Participación Ciudadana", "12 cabildos abiertos al año"),
        P("social", "Recuperar losas deportivas, programación cultural anual, bibliotecas móviles y el parque Castilla como Parque de la Literatura", 8, "Parque de la Literatura", "4 espacios recuperados el primer año y 3 bibliotecas móviles"),
        P("social", "Ampliar horarios del centro de salud mediante convenio con el MINSA, campañas preventivas y un plan de salud mental", 10, "Campañas periódicas de salud preventiva", "10 000 acciones preventivas al año"),
        P("urbano", "Rehabilitar veredas y reforzar el control de obras privadas y de edificaciones de más de 4 pisos", 11, "Rehabilitación y mantenimiento prioritario de veredas", "30 % de veredas reconstruidas el primer año"),
        P("agua_riesgos", "Plan de Defensa Civil ante sismos e incendios con brigadistas comunitarios y rutas de evacuación señalizadas", 11, "Plan de Defensa Civil y contingencia ante sismos", "Plan aprobado y 300 brigadistas capacitados en 12 meses"),
        P("economia", "Centro de Desarrollo Empresarial con capacitación e incubación, modernización de mercados y un tour gastronómico", 12, "Crear Centro de Desarrollo Empresarial local", "500 emprendedores atendidos al año"),
        P("ambiente", "Recolección diferenciada en zonas piloto y programa de arborización con especies frondosas y campañas escolares", 13, "Programa de arborización: identificación de zonas sin cobertura", "2 000 árboles plantados con 80 % de supervivencia y 40 % de hogares con recolección diferenciada en zonas piloto"),
        P("gestion", "Portal de transparencia con contratos, obras e ingresos por residuos valorizados, y ventanilla única digital para licencias", 14, "crear ventanilla única digital para licencias y permisos", "80 % de trámites digitalizados en 18 meses"),
    ]),
    ("Luis Ernesto Flores Reátegui", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "«Lince Interconectado»: renovar la videovigilancia con cámaras de reconocimiento de placas y analítica, conectadas en tiempo real con comisarías y distritos vecinos", 5, "Lince Interconectado", "100 % de las cámaras principales con reconocimiento de placas en las avenidas principales"),
        P("seguridad", "Serenazgo capacitado en marco legal y derechos humanos, más patrullaje integrado con la PNP y un observatorio distrital del delito", 5, "Serenazgo Vecinal Integrado", "40 % más patrullaje integrado en los cuadrantes críticos"),
        P("social", "Convenios para abrir a los vecinos las losas y patios de colegios nacionales e institutos por las tardes y los fines de semana", 6, "patios de colegios nacionales", "5 000 vecinos al mes"),
        P("social", "Consultorios municipales periféricos de medicina general, pediatría y geriatría en locales comunales, con universidades, y ferias de salud semanales", 9, "consultorios municipales periféricos", "1 500 atenciones al mes y 48 ferias al año"),
        P("social", "Atención médica y de enfermería a domicilio para adultos mayores que viven solos y personas con movilidad reducida, por central telefónica", 10, "atención médica y de enfermería a domicilio", "80 % del padrón cubierto"),
        P("urbano", "Plan «Veredas Seguras»: reparar veredas rotas, desniveles y rampas en calles secundarias, con multas a inmobiliarias que dañen el espacio público", 10, "realizar auditoría urbana inmediata", "10 000 metros lineales intervenidos"),
        P("transporte", "Ordenar el tránsito en la entrada y salida de colegios con fiscalizadores, cruces pintados y rompemuelles", 10, "Instalación de rompemuelles técnicos", "100 % de colegios emblemáticos protegidos"),
        P("economia", "Licencias provisionales para negocios de bajo riesgo con trámite 100 % digital, y primera fiscalización orientativa sin multa por faltas menores", 14, "Fiscalización Orientativa", "Licencias en menos de 24 horas"),
        P("economia", "Convenios con hoteles, restaurantes, constructoras e inmobiliarias del distrito para contratar mano de obra local", 15, "porcentaje de contratación de mano de obra local", "500 vecinos empleados formalmente al año"),
        P("ambiente", "Compostaje de residuos de mercados y de poda, y riego tecnificado de parques con aguas tratadas", 17, "Migrar del riego por inundación al riego tecnificado"),
        P("gestion", "Mesa de partes digital única «Cero Papel» que permita seguir el trámite desde el celular, y portal de transparencia con mapas interactivos", 20, "Mesa de Partes Digital", "85 % de los expedientes tramitados de forma digital"),
    ]),
    ("Otilia Merino García", "Fuerza Popular", "fuerza-popular", [
        P("seguridad", "Proyecto «Lince Seguro 24 Horas»: central de monitoreo con cámaras de alta resolución, analítica con inteligencia artificial y reconocimiento de placas", 5, "Sistema Automatizado de Reconocimiento de Placas"),
        P("seguridad", "Modernizar el serenazgo y fortalecer el patrullaje integrado con la Policía Nacional", 10, "Modernización integral del Serenazgo"),
        P("seguridad", "Programa contra la prostitución y la trata: clausura de locales clandestinos y operativos permanentes con la PNP y el Ministerio Público", 6, "Clausura de locales clandestinos"),
        P("social", "Centro Médico Municipal con varias especialidades y farmacia municipal de bajo costo", 6, "Farmacia Municipal de bajo costo"),
        P("social", "Programa «Lince Inclusivo» para niños y adolescentes con discapacidad, con convenios para terapias y equipos ortopédicos", 7, "orientado a promover la inclusión y el desarrollo integral de niños"),
        P("social", "Academia preuniversitaria municipal, centro de capacitación tecnológica con cursos de inteligencia artificial y becas para jóvenes", 8, "Academia preuniversitaria municipal"),
        P("social", "Gimnasio municipal y escuelas deportivas gratuitas de natación, fútbol, vóley, karate y ajedrez", 8, "Escuelas deportivas gratuitas"),
        P("social", "Casa Integral del Adulto Mayor con terapias físicas, atención preventiva, talleres y acompañamiento", 9, "Casa Integral del Adulto Mayor"),
        P("ambiente", "Reciclaje casa por casa, más árboles, mantenimiento del Parque Ramón Castilla y campañas de vacunación y esterilización de mascotas", 9, "Programas de reciclaje, casa por casa"),
        P("economia", "Bolsa de trabajo, capacitación a MYPES y ferias comerciales y gastronómicas con espacios gratuitos para adultos mayores", 9, "Espacios gratuitos para adultos mayores"),
        P("gestion", "Audiencias públicas semestrales de rendición de cuentas y publicación del avance de metas en el portal de transparencia", 11, "Audiencias públicas de rendición de cuentas de manera semestral"),
    ]),
    ("Yvan Alexis Villavicencio Alvildo", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("seguridad", "Cámaras con inteligencia artificial, reconocimiento facial y lectura de placas, y una app vecinal con botón de pánico conectada al centro de monitoreo", 11, "Superar las 300 cámaras de videovigilancia", "Más de 300 cámaras"),
        P("seguridad", "Equipar al serenazgo con armamento no letal y crear una Brigada de Serenazgo Paramédico capacitada en primeros auxilios", 11, "Brigada de Serenazgo Paramédico"),
        P("seguridad", "Gestionar con el MININTER la contratación de suboficiales en retiro para labores administrativas en comisarías y liberar policías para el patrullaje", 11, "contratación de suboficiales en situación de retiro"),
        P("social", "Gestionar ante el MINSA la ampliación del Centro de Salud para convertirlo en Hospital de Lince con emergencias las 24 horas", 12, "Construcción del Hospital de Lince"),
        P("social", "Centro Cultural de Lince con salas de exposición, teatros y aulas de formación artística en el área de la laguna", 13, "Construcción del Centro Cultural de Lince", "2 000 m²"),
        P("economia", "Zona Empresarial Distrital con incentivos tributarios temporales para inmobiliarias y empresas que instalen oficinas en Lince", 10, "Creación de la Zona Empresarial Distrital"),
        P("economia", "«Burocracia cero»: licencias de funcionamiento provisionales automáticas con declaración jurada y fiscalización posterior", 11, "automáticas en un plazo máximo de 24 horas", "Licencias provisionales en un máximo de 24 horas"),
        P("transporte", "Central de Gestión del Tránsito con semáforos inteligentes regulados en tiempo real en las intersecciones más congestionadas", 12, "Central de Gestión del Tránsito"),
        P("urbano", "Plan de pavimentación participativa «Vecinos en Acción»: pistas y veredas fiscalizadas por juntas vecinales con participación de la Fiscalía y la Contraloría", 13, "Plan de Pavimentación Participativa"),
        P("ambiente", "Sincronizar las rutas de recojo e instalar contenedores herméticos y soterrados diferenciados en mercados y zonas residenciales críticas", 13, "contenedores herméticos y soterrados"),
        P("gestion", "Trámites municipales digitales por la web, una aplicación y WhatsApp con inteligencia artificial", 11, "Digitalización de los trámites administrativos"),
    ]),
    ("José Antonio Aliaga Pajares", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Poner en funcionamiento las cámaras actuales, sumar cámaras nuevas con software de reconocimiento facial y de placas, y drones en puntos estratégicos", 29, "al menos cuatro (4) drones", "200 cámaras actuales operativas, 200 cámaras adicionales y al menos 4 drones"),
        P("seguridad", "Observatorio del delito, más serenos las 24 horas, comités de seguridad en mercados y clausura de locales de explotación con la PNP y el Ministerio Público", 29, "Implementación de un observatorio del delito"),
        P("social", "Gestionar con la DIRIS/MINSA un centro materno infantil con atención las 24 horas y una estrategia contra la anemia y la obesidad infantil", 25, "centro materno infantil con atención las 24 horas"),
        P("social", "Revalorar la Casa del Adulto Mayor, sumar asistencia legal, psicológica y social al CIAM y llevar cuidados a domicilio a los más vulnerables", 24, "Se habilitará cuidados domiciliarios"),
        P("economia", "Ventanilla única y licencias simplificadas, capacitación y asesoría legal y financiera gratuita a microempresarios, y convenios con bancos y cajas", 27, "implementar una ventanilla única y simplificación de licencias"),
        P("ambiente", "Huertos comunitarios en azoteas, techos y muros verdes, arborización de calles y bermas y recuperación de espacios abandonados", 28, "huertos comunitarios en azoteas"),
        P("urbano", "Boulevard peatonal en la Av. Ignacio Merino con tránsito calmado y recuperación de calles como Manuel Candamo y León Velarde", 30, "Implementar en la Av. Ignacio Merino un boulevard"),
        P("urbano", "Cambiar las luminarias del distrito a LED e incorporar iluminación con carga solar", 30, "Modernización del 100% de luminarias del distrito", "100 % de luminarias con focos LED"),
        P("transporte", "Parqueo gratuito y rotativo (hasta 2 horas para vecinos y 1 hora para visitantes) y grúa municipal", 31, "volviendo el parqueo gratuito y rotativo"),
        P("gestion", "«Consejo de Notables» trimestral, sesiones de concejo abiertas a los vecinos y control concurrente de la inversión", 30, "Consejo de Notables"),
        P("agua_riesgos", "Modernizar el COE distrital y gestionar donaciones para el equipamiento de la Bomba Lince N.° 4", 31, "Modernización del COE distrital"),
    ]),
    ("Miguel Ángel Espinoza Saavedra", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Patrullaje integrado, atención oportuna de ocurrencias y equipamiento del serenazgo, articulados con la PNP, el CODISEC y las juntas vecinales", 36, "Fortalecimientodelsistemadeseguridadciudadanamediantepatrullaje", "93 % de ocurrencias atendidas oportunamente por el serenazgo y 4,5 % de población víctima de algún delito al 2030"),
        P("social", "Salud preventiva, primeros auxilios, educación sanitaria y campañas de atención integral para niños, adultos mayores y población vulnerable", 35, "Fortalecimientodelosserviciosmunicipalesdesaludpreventiva"),
        P("social", "Programas de apoyo social y alimentario para población vulnerable, con orientación nutricional y prevención de la violencia familiar", 35, "Implementaciónprogresivadeprogramasdeapoyosocialyalimentario", "3,6 % de la población con acceso a programas de apoyo social y alimentario al 2030"),
        P("social", "Talleres de prevención de la violencia, igualdad de género y diversidad en las juntas vecinales", 30, "realizadosen juntasvecinales", "12 talleres en 2030"),
        P("economia", "Formalización, capacitación y asistencia técnica para emprendedores y comercios, y bolsa laboral municipal con intermediación", 35, "Impulsodeprogramasdeformalización"),
        P("economia", "Ferias y circuitos gastronómicos, culturales y comerciales para dinamizar la economía local", 36, "Promocióndeferias,circuitosgastronómicos"),
        P("ambiente", "Segregación en la fuente, reciclaje, compostaje vecinal y biohuertos municipales", 36, "segregaciónenlafuente,reciclaje", "5 % de los residuos recolectados destinados al reciclaje al 2030"),
        P("ambiente", "Campañas de sanidad animal y tenencia responsable de mascotas", 30, "campañasde sanidadanimaly", "20 campañas en 2030"),
        P("urbano", "Recuperar espacios públicos ocupados por puntos de acumulación de residuos y chatarra", 33, "residuosy chatarreo", "50 % de los espacios recuperados al 2030"),
        P("transporte", "Implementar ciclovías seguras y estacionamientos", 33, "deciclovías segurasy", "60 % de la infraestructura implementada al 2030"),
        P("gestion", "Audiencias públicas semestrales de rendición de cuentas y reportes ciudadanos del avance de metas en lenguaje claro", 37, "Audienciaspúblicassemestralesderendicióndecuentas"),
    ]),
    ("Arturo Ronald Bejarano Gurmendi", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Convertir la Central de Seguridad en un centro inteligente de monitoreo interconectado con la PNP, bomberos y SAMU, con analítica de video e inteligencia artificial", 27, "Centro Inteligente de Monitoreo y Respuesta Inmediata"),
        P("seguridad", "Aplicación para reportar emergencias y hechos sospechosos con un botón de pánico georreferenciado", 28, "Aplicación móvil y botón de pánico vecinal"),
        P("social", "Centros de Atención Integral Municipal con orientación médica, atención psicológica, telemedicina y rehabilitación", 16, "Centros de Atención Integral Municipal"),
        P("social", "Programas para adultos mayores de acompañamiento, recreación, salud preventiva y atención psicológica", 11, "Atención integral al adulto mayor"),
        P("agua_riesgos", "Programa «Lince Resiliente y Preparado»: mantenimiento y limpieza del drenaje urbano para reducir aniegos, y mapa de riesgos actualizado", 37, "Mejoramiento del sistema de drenaje urbano"),
        P("ambiente", "Riego tecnificado y uso eficiente del agua en áreas verdes, y campañas permanentes de arborización", 38, "Implementación de sistemas de riego tecnificado"),
        P("urbano", "Transformar áreas deterioradas o subutilizadas en espacios recreativos, deportivos y de encuentro", 38, "Recuperación de espacios abandonados"),
        P("transporte", "Plan de ordenamiento de vehículos menores, con rutas y paraderos organizados", 32, "Plan Integral de Ordenamiento de Vehículos Menores"),
        P("transporte", "Programa «Lince Pedalea»: nuevas ciclovías conectadas en las principales avenidas y estacionamientos para bicicletas", 50, "Implementación y ampliación de ciclovías"),
        P("economia", "Ventanilla única empresarial y asistencia técnica a pequeños empresarios en formalización, innovación y marketing digital", 52, "Ventanilla Única Empresarial"),
        P("gestion", "Observatorio de obras y contrataciones municipales que publique su estado, presupuesto y avance, y vigilancia ciudadana de las obras", 47, "Observatorio de Obras y Contrataciones Municipales"),
    ]),
    ("Eduardo Danilo Albarracín Ugarte", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Patrullaje por zonas con motorizados y una camioneta con un policía y serenos con armas no letales y chalecos, apoyado por drones y cámaras con reconocimiento facial", 3, "Se priorizará el patrullaje en motocicletas", "2 motorizados y 1 vehículo 4x4 por zona"),
        P("seguridad", "Convenio con el Poder Judicial para instalar un juzgado de flagrancia en Lince y con el MININTER para sumar policías en sus días de franco", 3, "Establecimiento de un Juzgado de Flagrancia"),
        P("seguridad", "Centro C5 de comando y control con videovigilancia, lectura de placas, botones de auxilio y la app «SOS Lince» con audio, video y geolocalización", 5, "Centro de Comando, Control, Comunicaciones y Contacto Ciudadano"),
        P("transporte", "Unidad de apoyo al tránsito coordinada con la PNP y la ATU, con drones y cámaras en tierra", 4, "Unidad de apoyo al tránsito vehicular"),
        P("agua_riesgos", "Plan de prevención y respuesta ante desastres con brigadas de voluntarios, mochilas de emergencia y un equipo de búsqueda y rescate en estructuras colapsadas", 6, "Se entregarán más de 4,000 mochilas de emergencia", "Más de 4 000 mochilas de emergencia"),
        P("social", "Centro de Atención de Urgencias las 24 horas en el actual centro de salud, con consultas a bajo costo o gratuitas, previa transferencia del MINSA", 6, "Centro de Atención de Urgencias: que atenderá las 24 horas"),
        P("social", "«Distrito Cardioprotegido»: paramédicos en moto con desfibriladores, desfibriladores en lugares públicos y capacitación en reanimación", 6, "Distrito Cardioprotegido", "4 paramédicos en motocicleta con desfibrilador"),
        P("urbano", "Adecuar pistas y veredas para el tránsito seguro de adultos mayores y personas con discapacidad", 7, "Adecuación de la infraestructura vial (pistas y veredas)"),
        P("economia", "Licencias de funcionamiento y certificados de Defensa Civil con costos reducidos y documentación mínima", 10, "Entrega en menos de 60 minutos", "Entrega en menos de 60 minutos; permisos de anuncios en 24 horas"),
        P("ambiente", "Recojo de basura programado e inopinado las 24 horas, más camiones recolectores, tachos y personal de barrido", 11, "Recojo programado y recojo inopinado de basura las 24 horas"),
        P("gestion", "Auditoría externa e independiente de las gestiones anteriores y sistema antisoborno ISO 37001", 12, "se realizará una auditoria externa e independiente de los 12 últimos años"),
    ]),
    ("Luis Miguel Alonzo Ramírez", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Red de videovigilancia con cámaras que identifican placas y movimientos sospechosos, monitoreo las 24 horas, drones y botones de pánico", 20, "Red de Videovigilancia Inteligente"),
        P("seguridad", "Unidad municipal contra la trata y la extorsión con la PNP y el Ministerio Público: mapa de zonas de riesgo, fiscalización de locales clandestinos y denuncia confidencial", 21, "Unidad contra trata y extorsión"),
        P("urbano", "Luminarias LED y postes inteligentes integrados a las cámaras para eliminar los puntos oscuros, priorizando parques, colegios y mercados", 21, "alumbrado LED inteligente para la eliminación total de puntos oscuros"),
        P("urbano", "Programa de gestión vial con mantenimiento preventivo de pistas y veredas, veredas accesibles y señalización moderna", 22, "programa integral de gestión vial"),
        P("social", "Gestión por resultados para el CIAM y la OMAPED con talleres y servicios para adultos mayores y personas con discapacidad", 24, "Modelo de gestión por resultados para CIAM y OMAPED"),
        P("social", "Escuelas deportivas municipales gratuitas o de bajo costo con entrenadores certificados y detección de talentos", 38, "Escuelas Deportivas Municipales y Detección de Talentos"),
        P("economia", "Programa «Lince Emprende Digital» de capacitación en marketing digital y comercio electrónico para emprendedores y pequeños negocios", 26, "Lince Emprende Digital"),
        P("ambiente", "Sistema integral de residuos con segregación, reciclaje y puntos ecológicos", 29, "sistema integral de gestión de residuos sólidos y reciclaje"),
        P("ambiente", "Clínicas veterinarias municipales accesibles y campañas de vacunación y esterilización de mascotas", 34, "Clínicas Veterinarias Municipales"),
        P("transporte", "Estudio de tráfico con rutas alternas, carriles exclusivos, señalización clara y semáforos inteligentes", 31, "Estudio de tráfico y rutas alternas"),
        P("transporte", "Mantenimiento de vías y ciclovías seguras con estacionamientos para bicicletas", 32, "Construcción y mantenimiento de vías y ciclovías con estacionamientos seguros"),
    ]),
    ("Mirtha Sebastiana Uribe Soriano", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Programa «Lince Seguro 360»: CECOM repotenciado, cámaras con reconocimiento facial, analítica de video y drones con visión nocturna", 7, "Uso de drones con visión nocturna", "100 % de zonas críticas mapeadas el primer año"),
        P("seguridad", "Ampliar los convenios del «Serenazgo sin Fronteras» con distritos colindantes y fortalecer el patrullaje integrado con la PNP", 7, "Fortalecimiento del Serenazgo sin Fronteras"),
        P("social", "Programa «PoliLince Salud» con campañas preventivas y campañas de salud mental y prevención de la depresión", 8, "Implementación del programa PoliLince Salud"),
        P("social", "Repotenciar el Centro de Salud de la Av. Militar", 8, "Repotenciación del Centro de Salud ubicado en la Av. Militar"),
        P("social", "Recuperar los centros polideportivos y repotenciar la biblioteca infantil y la escuela musical", 8, "Recuperación progresiva de los centros polideportivos"),
        P("economia", "Programa «Lince Emprende» de capacitación y formalización, con fiscalización orientadora mediante notificaciones preventivas", 8, "Fiscalización orientadora, con comunicaciones preventivas"),
        P("economia", "Ruta gastronómica «Lince Distrito Gastronómico» y regreso del Festival del Sabor Linceño", 8, "Fortalecimiento del Festival del Sabor Linceño", "Festival del Sabor Linceño cada año"),
        P("ambiente", "Programa «Lince Recicla» en colegios, mercados, juntas vecinales y comercios, y repotenciación del vivero municipal", 9, "Programa Lince Recicla en colegios"),
        P("urbano", "Plan integral de mantenimiento urbano de parques, jardines y bermas, con iluminación peatonal y rampas de accesibilidad", 9, "Plan Integral de Mantenimiento Urbano"),
        P("transporte", "Gestionar ante la Municipalidad de Lima mejoras en la semaforización y la planificación vial", 9, "para el mejoramiento de la semaforización"),
        P("gestion", "Modelo de Integridad Pública Municipal, más trámites y seguimiento de expedientes en línea, y catastro urbano modernizado", 9, "Implementar el Modelo de Integridad Pública Municipal"),
    ]),
]
