"""Villa El Salvador (150142): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150142"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("José Luis Flores Llauca", "Acción Popular", "accion-popular", [
        P("social", "Academia preuniversitaria municipal gratuita con docentes y material académico para preparar a jóvenes del distrito", 7, "Academia Gratuita Municipal Preuniversitaria"),
        P("social", "Programa «Salud en tu Sector»: complejos multiusos en áreas recreativas con gimnasio municipal gratuito y cancha multiusos", 7, "destinando una mitad a un gimnasio municipal gratuito"),
        P("social", "Consultorio médico municipal de pediatría y geriatría con atención y control preventivo gratuito a niños y adultos mayores vulnerables", 7, "Consultorio Médico Municipal Especializado en Pediatría y Geriatría"),
        P("seguridad", "Sistema Vecinal de Alerta Temprana para que las organizaciones comunales reporten incidencias al serenazgo, la PNP y la municipalidad", 7, "Sistema Vecinal de Alerta Temprana"),
        P("seguridad", "Convenio «Serenazgo Sin Fronteras del Cono Sur»: interconexión radial y de cámaras con distritos colindantes y «Plan Cerco Distrital»", 9, "Convenio de Serenazgo Sin Fronteras del Cono Sur"),
        P("economia", "Programa «Techo Limpio»: recojo de materiales en desuso de los techos a cambio de descuentos en arbitrios", 8, "descuentos escalonados y directos en el pago de arbitrios"),
        P("economia", "«Licencia de Funcionamiento Exprés» con digitalización y reducción de barreras para formalizar micro y pequeñas empresas", 8, "Licencia de Funcionamiento Exprés"),
        P("transporte", "Reestructurar pistas con drenaje subterráneo, pavimento rígido e impermeable y desarenado preventivo para evitar inundaciones y lodo", 8, "Plan Integral de Reestructuración de Pistas"),
        P("agua_riesgos", "Mesa permanente con SEDAPAL para exigir presión estable del agua de 1:00 p. m. a 6:00 p. m.", 9, "Mesa de Coordinación Interinstitucional Permanente con SEDAPAL"),
        P("ambiente", "Horarios fijos de recojo de basura por sectores y renovación progresiva de la flota de compactadoras", 9, "Horarios Estrictos de Recojo de Basura por Sectores"),
        P("gestion", "Portal de datos y rendición de cuentas en tiempo real sobre uso de recursos y avance de obras", 10, "portal de datos y rendición de cuentas en tiempo real"),
    ]),
    ("Genaro Soto Mendoza", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Sistema integral de cámaras monitoreadas con inteligencia artificial que integre cámaras particulares, y Observatorio Distrital de Seguridad Ciudadana", 8, "integrando las camas de vigilancia particulares", "Reducir la victimización por persona en 50%"),
        P("social", "Construir y equipar Casas de la Juventud y Cultura en convenio con grupos residenciales y asociaciones de vivienda", 11, "Construir y equipar 30 Casas de la Juventud y Cultura", "30 Casas de la Juventud y Cultura"),
        P("social", "Recuperar el complejo deportivo Iván Elías La Rosa para uso público y equipar e iluminar losas deportivas", 12, "Desprivatizar el complejo deportivo municipal Iván Elías La Rosa", "Equipar e iluminar 200 losas deportivas"),
        P("social", "Diversificar proveedores de insumos del Vaso de Leche y actualizar cada semestre el padrón de beneficiarios y comedores", 15, "Actualizar en forma semestral el padrón de beneficiarios"),
        P("transporte", "Programa de ordenamiento de mototaxis según estudio de demanda, formalizando informales y limitando nuevas unidades", 19, "Ejecutar un programa de ordenamiento de servicio de mototaxis"),
        P("economia", "Modernizar mercados cooperativos y asociativos, formalizar ambulantes y reubicar mercados informales", 20, "Formalizar al 30% de los comerciantes ambulantes", "Modernizar más del 80% de mercados cooperativos y asociativos; formalizar al 30% de los comerciantes ambulantes"),
        P("economia", "Proyectos de infraestructura urbana y comercial en el Parque Industrial, con ordenamiento vehicular y seguridad", 17, "proyectos de infraestructura urbana básica y comercial en el PIVES", "10 proyectos de infraestructura urbana básica y comercial en el PIVES"),
        P("ambiente", "Recojo domiciliario diario por rutas en todo el distrito y relanzar el incentivo «Bono Verde» para la segregación", 22, "se recuperará el incentivo económico"),
        P("ambiente", "Equipar parques con almacenamiento de agua y riego y enverdecerlos con árboles nativos", 23, "Equipar 200 parques de los grupos residenciales", "Equipar 200 parques y enverdecer 300,000 m2 de áreas verdes"),
        P("gestion", "Relanzar el presupuesto participativo con consultas ciudadanas, destinando 20 millones de soles anuales del FONCOMUN", 27, "destinando un fondo de 20 millones de soles anuales", "Ampliar el fondo de inversión del PPxR de 6 a 20 millones de soles"),
        P("gestion", "Digitalizar los trámites documentarios y usar inteligencia artificial en trámites y monitoreo de cámaras", 27, "Digitalización del 100% de los trámites documentarios", "Digitalización del 100% de los trámites documentarios"),
    ]),
    ("Marcelino Huamán Cano", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("social", "Campañas periódicas de salud y nutrición contra la anemia y la desnutrición infantil", 1, "Campañas periódicas de salud y nutrición"),
        P("social", "Gestionar una clínica de rehabilitación e hidroterapia", 1, "Gestionar clínica de rehabilitación e hidroterapia"),
        P("social", "Veterinaria municipal y adquisición de ambulancias municipales", 1, "Adquisición de ambulancias municipales"),
        P("social", "Convenios con universidades e institutos para ampliar el acceso a educación superior", 2, "Convenios con universidades e institutos"),
        P("seguridad", "Fortalecer la videovigilancia y la seguridad integral, y mejorar la iluminación de calles, parques y losas", 2, "Fortalecer videovigilancia y seguridad integral"),
        P("transporte", "Formalización y reordenamiento vehicular", 2, "Formalización y y reordenamiento vehicular"),
        P("ambiente", "Fortalecer segregación, recolección y valorización de residuos y renovar el parque automotor de limpieza", 2, "Fortalecer segregación, recolección y valorización", "25% de residuos aprovechables valorizados; 75% de cobertura de limpieza pública"),
        P("urbano", "Implementar el catastro distrital y bibliotecas sectoriales", 2, "Implementar catastro distrital"),
        P("urbano", "Gestionar una Casa de la Mujer, un centro para personas con discapacidad y una Plaza de Armas distrital", 3, "Ausencia de Plaza de Armas distrital"),
        P("gestion", "Digitalización y simplificación administrativa y actualización de ROF, CAP, TUPA y demás instrumentos", 3, "Actualizar ROF, CAP, TUPA y demás instrumentos", "90% actualizados al 2030"),
        P("gestion", "Fortalecer el presupuesto participativo y articular proyectos por APP y obras por impuestos", 3, "Articular proyectos APP y OxI", "5% de participación al 2030"),
    ]),
    (None, "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Programa de prevención social para niños y adolescentes de zonas de alto riesgo mediante deporte, artes y animación cultural", 5, "Programa de Prevención Social de Seguridad ciudadana", "Reducir la victimización por persona en 10%"),
        P("social", "Crear casas de la juventud, recuperar los complejos deportivos municipales y programas de deporte y cultura de verano", 6, "Creación de trece casas de la juventud", "Trece casas de la juventud y recuperación de tres complejos deportivos municipales"),
        P("social", "Reconocer e incluir a nuevos comedores y ollas comunes en el programa de apoyo alimentario con subsidio", 6, "Reconocimiento y subsidio del 100% de nuevos comedores", "Reconocimiento y subsidio del 100% de nuevos comedores y ollas comunes"),
        P("social", "Acondicionar accesos peatonales para personas con discapacidad y generar empleo para jefes de hogar con discapacidad", 6, "Acondicionamiento de accesos peatonales para personas", "100% de grupos residenciales"),
        P("social", "Centros Integrales de Atención al Adulto Mayor en convenio con asociaciones de adultos mayores", 6, "Creación de cinco Centros Integrales de Atención al Adulto Mayor", "Cinco Centros Integrales de Atención al Adulto Mayor"),
        P("transporte", "Ordenar el servicio de mototaxis según estudio de oferta y demanda y formalizar los informales", 6, "Formalizar el 100% de vehículos de transporte de pasajeros", "Formalizar el 100% de mototaxis informales; reducir en 50% los accidentes de vehículos menores"),
        P("economia", "Modernizar mercados, formalizar ambulantes, reubicar mercados informales y ferias en el Parque Industrial", 7, "Modernizar del 50% de mercados cooperativos", "Modernizar el 50% de mercados cooperativos y asociativos; formalizar al 30% de los ambulantes"),
        P("economia", "Colocar a jóvenes en empleos formales y capacitarlos en habilidades para la empleabilidad", 7, "Colocar a 4000 jóvenes en puestos de trabajo formales", "4000 jóvenes colocados y 8000 capacitados"),
        P("ambiente", "Recojo domiciliario de residuos por rutas con frecuencia diaria en todos los sectores y fomento del reciclaje en hogares", 8, "con una frecuencia diaria para todos los sectores", "Lograr que el 50% de los hogares introduzcan el habito de la reducción y reciclaje"),
        P("ambiente", "Esterilización de canes y gatos e instalación de tachos para excrementos de canes en espacios públicos", 8, "Esterilizar 20,000 canes y 4,00 gatos", "Esterilizar 20,000 canes y 4,00 gatos con hogar; 500 tachos"),
        P("gestion", "Recuperar el presupuesto participativo por resultados con vigilancia de la Contraloría y comités en contrataciones", 10, "Asignación de no menos de 10 millones de soles anuales al PPxR", "No menos de 10 millones de soles anuales al PPxR"),
    ]),
    ("Juan José Díaz Ayquipa", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("social", "Programa «Crece Sano»: suplementación nutricional, huertos familiares y seguimiento de gestantes y niños contra la anemia", 10, "suplementación nutricional, promoción del consumo de alimentos ricos en hierro", "Reducir la anemia infantil de 10.8% a menos de 5%"),
        P("seguridad", "«Villa El Salvador Seguro»: más videovigilancia, serenazgo modernizado, patrullaje integrado con la PNP e iluminación de espacios públicos", 12, "ampliación del sistema de videovigilancia, modernización del serenazgo", "Reducir en 20% la incidencia de delitos patrimoniales"),
        P("social", "Tres centros integrados de cultura, deporte y juventud con talleres de artes, emprendimiento y salud mental", 12, "Implementar tres centros integrados de cultura, deporte y juventud"),
        P("agua_riesgos", "Gestionar con Sedapal proyectos de agua y alcantarillado, ampliar electrificación periurbana y abastecimiento provisional en sectores sin servicio", 13, "gestión de proyectos de agua potable y alcantarillado en coordinación con Sedapal", "Incrementar en 20 puntos porcentuales la cobertura de agua y saneamiento"),
        P("economia", "«Emprende Villa El Salvador»: asistencia para formalizar negocios, bolsa de empleo local e incubación de emprendimientos", 13, "asistencia técnica para la formalización de negocios, bolsa de empleo local", "Reducir la informalidad laboral en 15 puntos porcentuales"),
        P("economia", "Puesta en valor de Playa Venecia, circuitos turísticos y culturales y recuperación de monumentos", 14, "puesta en valor de Playa Venecia", "Incrementar en 50% el flujo de visitantes al distrito"),
        P("transporte", "Plan de conectividad urbana: mejoramiento de pistas y veredas, modernización de mercados y ordenamiento del comercio", 15, "Plan Integral de Competitividad y Conectividad Urbana", "Mejorar 50 km de vías urbanas estratégicas"),
        P("ambiente", "Erradicar puntos críticos de basura, segregación en la fuente, formalización de recicladores y centros de acopio", 15, "erradicación de puntos críticos de basura", "Valorizar al menos el 30% de los residuos sólidos"),
        P("ambiente", "«Guardianes de los Pantanos de Villa»: recuperar áreas degradadas, controlar focos contaminantes y promover el ecoturismo", 16, "Guardianes de los Pantanos de Villa"),
        P("agua_riesgos", "Plan de gestión del riesgo: simulacros, brigadas vecinales, rutas de evacuación señalizadas y programas de vivienda segura", 16, "simulacros comunitarios, fortalecimiento de brigadas vecinales"),
        P("gestion", "Expediente electrónico, mesa de partes virtual, aplicativo municipal y seguimiento en línea de trámites", 17, "implementación del expediente electrónico, mesa de partes virtual", "Digitalizar el 100% de los trámites prioritarios"),
    ]),
    ("Ricardo Gil Espadín", "Fuerza Popular", "fuerza-popular", [
        P("seguridad", "Construir una base de serenazgo y una de videovigilancia, con cámaras según el mapeo del delito y sub-bases", 91, "Construcción de la Base de Serenazgo", "Tres sub-bases"),
        P("seguridad", "Escuela de capacitación técnico-operativa para serenos de los distritos de Lima Sur", 92, "Creación de la Escuela de Capacitación Técnica-Operativa"),
        P("social", "Construir una casa refugio para mujeres e hijos víctimas de violencia familiar y trata de personas", 92, "Casa Refugio para Mujeres de Villa El Salvador"),
        P("social", "Desayuno escolar en todos los colegios públicos del distrito contra la desnutrición y el bajo rendimiento", 93, "en todos centros educativos públicos del distrito, como medio de combate"),
        P("social", "Construir la Villa Deportiva Olímpica de Villa El Salvador y organizar olimpiadas interescolares e interuniversitarias anuales", 94, "Construcción de la Villa Deportiva Olímpica de Villa El Salvador"),
        P("social", "Construir y equipar un Centro Materno Infantil en convenio con el MINSA y mejorar centros y postas médicas", 94, "Construcción y equipamiento del Centro Materno Infantil"),
        P("economia", "Articular con APEMIVES y la PNP la seguridad integral del Parque Industrial y de sus visitantes", 96, "garantizar la seguridad integral del Parque Industrial"),
        P("urbano", "Fortalecer el comité técnico de habilitaciones urbanas de oficio para el saneamiento físico-legal de propiedades y límites", 95, "comité técnico de habilitaciones urbanas de oficio"),
        P("transporte", "Plan director de transporte y vialidad y plan de descongestión vehicular en las principales avenidas", 96, "Plan Director de Transporte y Vialidad sostenible"),
        P("ambiente", "Instalar más contenedores de basura en todas las urbanizaciones y aumentar el reciclaje de residuos inorgánicos", 97, "Incrementar hasta un 90% el reciclaje de residuos sólidos inorgánicos", "Incrementar hasta un 90% el reciclaje de residuos sólidos inorgánicos al 2018"),
        P("gestion", "Servicios municipales en línea por internet y sistema de gestión de calidad", 98, "transacciones en línea vía INTERNET en un 100%", "100% de servicios municipales en línea"),
    ]),
    ("William Dwight Vargas Matos", "Juntos por el Perú", "juntos-por-el-peru", [
        P("social", "Capacitación técnica y superior de jóvenes en instituciones educativas y becas para los más destacados", 5, "Promover capacitación técnica y superior de los jóvenes"),
        P("social", "Ampliar actividades deportivas escolares y comunitarias, incluidas ajedrez y atletismo, hasta realizar una olimpiada escolar", 5, "lograr una formación deportiva que permita una Olimpiada Escolar"),
        P("social", "Convenio entre municipalidad, instituciones de salud y bomberos para un sistema de ambulancias y traslado de pacientes", 6, "Fortalecer un sistema de Ambulancias"),
        P("social", "Gestionar con el Ministerio de Salud un establecimiento de salud del primer nivel en el sector 1, cerca del Cerro Papa", 6, "Edificar Un IPRESS de nivel I-IV"),
        P("social", "Casas del Adulto Mayor en los propios grupos residenciales, en coordinación con el DAIPAM", 6, "Construcción de Casas del Adulto mayor en sus propios Grupos Residenciales"),
        P("seguridad", "Plan de seguridad y orientación en colegios para proteger a estudiantes y aplicar la ley de reinserción escolar de alumnas madres", 6, "hacer cumplir la Ley N° 29600", "Disminuir el 15 % de embrazadas existente"),
        P("urbano", "Construir una alameda peatonal en el sector 1, grupo 24, junto a la IE Perú – EEUU", 7, "Construcción de la Alameda peatonal en el sector 1 Grupo 24"),
        P("ambiente", "Gestionar con la comunidad el retiro del cableado aéreo en desuso de los postes", 7, "Recuperar nuestras calles de los Cables de comunicación en desuso"),
        P("gestion", "Sistema de atención telefónica en tiempo real y oficinas descentralizadas de proyectos en las agencias municipales", 8, "Crear un Sistema de atención, vía telefónica y en tiempo real", "Mejorar la cobertura de los servicios en 10% optimizando costos"),
        P("gestion", "Proyectos de inversión priorizados por los grupos residenciales en talleres de presupuesto participativo", 8, "Elaborarse proyectos de inversión pública priorizados por los Grupos Residenciales"),
        P("gestion", "Rendición de cuentas anual en lugar público con presencia de la población organizada y transmisión digital", 8, "Rendición de Cuentas, una ves al año, en lugar público"),
    ]),
    ("Edgard Asunción Cordero Marichini", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("seguridad", "Central distrital de videovigilancia con cámaras inteligentes y patrullaje integrado serenazgo-PNP por zonas", 7, "Implementar una Central Distrital de Videovigilancia con cámaras inteligentes", "Instalar 1,000 cámaras más de vigilancia; reducir en 30% los delitos denunciados"),
        P("seguridad", "Gestionar con el Ministerio del Interior dos comisarías más e instalar alarmas vecinales en todos los grupos residenciales", 7, "la construcción de dos Comisarías Más"),
        P("economia", "Marca «Hecho en Villa El Salvador», bolsa de trabajo distrital, ferias laborales trimestrales y centro de innovación", 8, "Implementar una Bolsa de Trabajo Distrital", "Generar 10,000 nuevos puestos de trabajo; formalizar 3,000 negocios"),
        P("transporte", "Pavimentar las calles pendientes del distrito con pistas y veredas y construir ciclovías", 8, "Pavimentación integral de calles pendientes", "Pavimentar 100 km de vías; construir 20 km de ciclovías"),
        P("transporte", "Condonar deudas por infracciones de mototaxis en el depósito municipal y primera papeleta con derecho de gracia", 8, "Condonación de deudas por infracción al 100% de vehículos menores"),
        P("ambiente", "Plantar árboles, programa «El vivero de mi Barrio», riego tecnificado y programa «Adopta un Parque»", 9, "Plantar 100,000 árboles durante la gestión", "Plantar 100,000 árboles; incrementar en 50% las áreas verdes"),
        P("ambiente", "Comprar más compactadoras para el recojo de residuos con cronogramas por sector y promover el reciclaje", 9, "Comprar más camiones Recolectores o Compactadoras", "Reciclar 30% de los residuos sólidos"),
        P("social", "Academia municipal preuniversitaria y becas en convenio con universidades para jóvenes y deportistas destacados", 10, "Academia Municipal Preuniversitaria", "Otorgar 1,000 becas municipales"),
        P("social", "Campañas médicas permanentes con las redes de salud, lucha contra la anemia y programa «Adulto Mayor Protegido»", 10, "Campañas médicas permanentes en coordinación", "Reducción la anemia infantil en 20%"),
        P("gestion", "Condonar deudas de autoavalúo, arbitrios y multas mediante ordenanza y revisar la valoración de predios", 12, "hasta 30% de deuda actual y 100%.de deudas de años anteriores"),
        P("gestion", "Presupuesto participativo digital, audiencias públicas trimestrales, portal de transparencia en tiempo real y aplicativo de denuncias y trámites", 12, "Presupuesto participativo digital", "Atención de reclamos en máximo 72 horas"),
    ]),
    ("Nils René Antonio Siccos", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Red de videovigilancia inteligente con cámaras de reconocimiento facial y de placas, priorizando zonas críticas", 11, "cámara de video vigilancia con sistema de reconocimiento facial"),
        P("seguridad", "Escuela de formación estratégica y táctica para serenos y fiscalizadores municipales", 11, "escuela de formación estratégica y táctica para el personal de serenazgo"),
        P("ambiente", "Plantar árboles y arbustos adaptados al clima árido y crear un «Bosque Urbano VES» en terrenos eriazos", 12, "Plantar 15,000 árboles y arbustos", "15,000 árboles y arbustos; al menos 5 m² de área verde por habitante al año 4"),
        P("ambiente", "Segregación en todas las manzanas, puntos limpios y centro de acopio y clasificación de residuos", 14, "Instalación de 80 puntos limpios estratégicos", "80 puntos limpios; centro de acopio de 50 toneladas diarias; erradicar 45 puntos críticos"),
        P("ambiente", "Formalizar recicladores de base con equipos de protección, vehículos y rutas integradas a la recolección municipal", 13, "Formalizar y fortalecer a más de 300 recicladores de base", "Más de 300 recicladores formalizados"),
        P("urbano", "Rehabilitar parques con iluminación LED solar, juegos inclusivos y wifi gratuito, y crear tres parques temáticos", 14, "Rehabilitación integral de 20 parques priorizados", "20 parques rehabilitados"),
        P("transporte", "Proyectos de pistas y veredas, ciclovías interconectadas y tránsitos peatonales", 17, "Construcción de ciclovías interconectadas en el distrito"),
        P("social", "Crear un policlínico y una farmacia municipal y campañas itinerantes contra enfermedades no transmisibles", 18, "Creación de policlínico y farmacia municipal"),
        P("social", "Museo Distrital Interactivo «Villa El Salvador, ciudad mensajera de la Paz» y circuito turístico del patrimonio histórico", 18, "Creación del Museo Distrital Interactivo"),
        P("economia", "Ruta turística del mueble, ferias para pequeños emprendedores y programas de formalización", 18, "Creación de la ruta turística del mueble"),
        P("gestion", "Reestructuración organizacional con gerencias o agencias municipales rediseñadas en diversas zonas del distrito", 25, "50% de gerencias y/o agencias municipales rediseñadas", "50% de gerencias y/o agencias rediseñadas al 2030"),
    ]),
    ("Yolanda Inés Peña Valdivia", "Partido del Buen Gobierno", "partido-del-buen-gobierno", [
        P("seguridad", "Nuevas cámaras de videovigilancia en zonas críticas y patrullaje integrado entre serenazgo y Policía Nacional", 12, "Implementar nuevas cámaras de videovigilancia en zonas críticas", "Cobertura del 100% de los sectores priorizados"),
        P("seguridad", "Herramientas digitales para reportes y alertas ciudadanas y fortalecimiento de juntas vecinales", 12, "Implementar herramientas digitales para reportes y alertas ciudadanas"),
        P("social", "Centros de atención integral para niños, adultos mayores, mujeres y personas con discapacidad", 13, "Implementar centros de atención integral para poblaciones vulnerables", "Cobertura del 80% de la población vulnerable identificada"),
        P("urbano", "Recuperar parques, losas deportivas y espacios recreativos con iluminación, mobiliario y actividades permanentes", 13, "Recuperar parques, losas deportivas y espacios recreativos", "Recuperar y activar 50 espacios públicos"),
        P("economia", "Asesoría para formalización empresarial, capacitación en gestión y digitalización e incentivos a negocios formalizados", 14, "Implementar programas de asesoría para formalización empresarial", "Incrementar en 25% la formalización de MYPE"),
        P("economia", "Bolsas de trabajo distritales, capacitación técnica y certificación laboral para jóvenes y mujeres", 14, "Implementar bolsas de trabajo distritales", "Beneficiar a 5,000 jóvenes y mujeres"),
        P("economia", "Ruedas de negocio y articulación de proveedores locales con el Parque Industrial", 15, "Articular proveedores locales con el Parque Industrial", "Incorporar al 60% de las empresas participantes en redes de articulación"),
        P("ambiente", "Segregación en la fuente en hogares y negocios, apoyo a recicladores formalizados y erradicación de puntos críticos", 15, "Implementar programas de segregación en la fuente", "Incrementar en 40% el reciclaje de residuos sólidos"),
        P("ambiente", "Recuperar parques y jardines, programas de arborización urbana y uso eficiente del agua para riego", 16, "Implementar programas de arborización urbana", "Incrementar en 20% la superficie de áreas verdes"),
        P("agua_riesgos", "Educación ambiental, adaptación al cambio climático y gestión de riesgos ante eventos ambientales en colegios y organizaciones vecinales", 16, "Fortalecer la gestión de riesgos ante eventos ambientales", "80% de participación en programas de educación ambiental y resiliencia climática"),
        P("gestion", "Plataforma integral de trámites digitales, reducción de requisitos e interoperabilidad de sistemas municipales", 18, "Implementar una plataforma integral de trámites digitales", "Digitalizar el 80% de los trámites prioritarios"),
    ]),
    ("Clodoaldo Kevin Yñigo Peralta", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Adquirir e instalar 1 000 cámaras adicionales de videovigilancia para monitoreo preventivo y respuesta oportuna", 34, "Adquisición e instalación de 1,000 cámaras adicionales", "1 000 cámaras adicionales"),
        P("seguridad", "Construir dos comisarías, en Oasis y el Primer Sector, con el Ministerio del Interior y la PNP", 34, "Construcción de dos comisarías en Oasis y el Primer Sector", "2 comisarías"),
        P("social", "Construir la Academia Preuniversitaria, dos piscinas temperadas, dos complejos deportivos y un skate park en Oasis", 32, "Construcción de 2 piscinas temperadas", "2 piscinas temperadas y 2 complejos deportivos"),
        P("social", "Construir la Casa del Adulto Mayor, la Casa de la Mujer y un centro de atención para niños con habilidades diferentes", 32, "Construcción de la Casa del Adulto Mayor"),
        P("transporte", "Construir el Depósito Municipal e implementar la Grúa Municipal para controlar vehículos mal estacionados o abandonados", 35, "Construcción del Depósito Municipal e implementación de la Grúa Municipal"),
        P("urbano", "Modernizar y equipar las playas Venecia y Barlovento como espacios recreativos, turísticos y de integración familiar", 36, "equipamiento urbano en las playas Venecia y Barlovento"),
        P("economia", "Simplificar los procedimientos de licencias de funcionamiento e ITSE, reduciendo plazos y requisitos", 37, "Simplificación administrativa de los procedimientos vinculados a licencias"),
        P("ambiente", "Adquirir cuatro barredoras mecánicas para las principales avenidas y modernizar la maestranza municipal", 42, "Adquisición de cuatro barredoras mecánicas", "4 barredoras mecánicas"),
        P("ambiente", "Implementar nuevas áreas verdes, riego tecnificado en 60 parques y sembrar unos 10 000 árboles al año con SERPAR", 43, "de áreas verdes adicionales durante el periodo", "250 mil m² adicionales de áreas verdes; 4 m² por habitante al 2030"),
        P("agua_riesgos", "Sistema distrital de alerta temprana ante sismos y emergencias, y señalización de rutas de evacuación y zonas seguras", 45, "sistema distrital de alerta temprana y comunicación ante sismos"),
        P("gestion", "Plataforma única de atención «MAC Express» para trámites, pagos, seguimiento de expedientes y denuncias", 46, "MAC Express, que integre trámites"),
    ]),
    (None, "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Nueva central de monitoreo en Pachacamac («El Ojo Integral») y reemplazo de las cámaras inoperativas", 25, "nueva central de monitoreo en la zona de Pachacamac", "Reducción acumulada de la delincuencia de 80 % al 2030"),
        P("seguridad", "Unidades de serenazgo con GPS enlazadas a un sistema de control de patrullaje (SIPCOP-M) y patrullaje integrado con la PNP", 25, "Sistema Informático de Planificación y Control de Patrullaje Municipal"),
        P("social", "Gestionar ante DIRIS Lima Sur mejoras en los establecimientos de salud I-2 e I-3 y construir un crematorio municipal", 27, "Construcción del Crematorio Municipal"),
        P("social", "Programa «Villa Educa y Crea» de talleres y concursos en lectura, matemáticas, ciencia y arte", 28, "orientado a fortalecer las competencias de lectura", "Brecha de locales escolares inadecuados de 38 % al 2030"),
        P("urbano", "Priorizar pistas, veredas y transitabilidad en la zona de playa y sectores con mayor déficit urbano", 29, "proyectos de transitabilidad en la zona de playa", "85 % de cobertura de pistas y veredas en la zona de playa al 2030"),
        P("agua_riesgos", "Gestionar redes de agua, alcantarillado, drenaje pluvial y electrificación en la zona de playa", 29, "ampliación de redes de agua potable, alcantarillado, drenaje pluvial", "95 % de población de la zona de playa con servicios básicos al 2030"),
        P("agua_riesgos", "Obras de drenaje, muros de contención y adaptación al cambio climático en la zona costera", 30, "Ejecutar obras de drenaje, muros de contención", "100 % de zonas críticas intervenidas al 2030"),
        P("transporte", "Depurar el registro de mototaxis, formalizar empresas, identificación visible de unidades y capacitación obligatoria de conductores", 32, "Actualizar y depurar el registro municipal de operadores", "95 % de unidades formalizadas al 2030"),
        P("economia", "Fortalecer la Ventanilla Única del emprendedor, incubadoras de negocios y ferias productivas y gastronómicas", 33, "Fortalecer la Ventanilla Única de atención al emprendedor", "30 % más de negocios formalizados al 2030"),
        P("ambiente", "Arborización de parques y avenidas, y recuperación de espacios degradados como áreas verdes", 35, "Implementar programas de arborización urbana", "6 m² de áreas verdes por habitante al 2030"),
        P("gestion", "Ordenanza de audiencias públicas semestrales de rendición de cuentas y transmisión en línea de las sesiones de concejo", 37, "Transmitir en línea las sesiones del Concejo Municipal", "2 audiencias públicas por año"),
    ]),
    ("Migman Pinchi Caro", "Partido Morado", "partido-morado", [
        P("social", "Crear un policlínico y farmacia municipal articulados con el MINSA y EsSalud", 6, "Crear un policlínico y farmacia municipal", "Policlínico municipal en funcionamiento antes del 2028"),
        P("social", "Escuelas de Oficios Digitales con formación en programación, marketing digital y diseño gráfico", 8, "Crear Escuelas de Oficios Digitales"),
        P("social", "Aumentar el presupuesto de cultura y deporte, reactivar el área de deportes y programar actividades descentralizadas", 8, "Asignar al menos el 8% del presupuesto distrital", "Al menos 8 % del presupuesto distrital a cultura y deporte"),
        P("economia", "«Villa Formalízate»: licencias de funcionamiento en 48 horas", 10, "sistema de licencias de funcionamiento en 48 horas", "Incrementar en 25 % la formalización de negocios"),
        P("economia", "Zonas de comercio ambulatorio ordenado con un sistema transparente de permisos", 11, "zonas de comercio ambulatorio ordenado"),
        P("urbano", "Corredores interdistritales en zonas límite con pavimentación, veredas accesibles, ciclovías e iluminación LED", 12, "Implementar pavimentación, veredas accesibles, ciclovías, iluminación LED"),
        P("transporte", "«Ciclovilla»: ciclovías interconectadas y mejora de la infraestructura peatonal", 12, "Construcción de ciclovías interconectadas"),
        P("ambiente", "Sensores volumétricos en contenedores para optimizar las rutas de recolección de residuos", 13, "sensores volumétricos en contenedores"),
        P("agua_riesgos", "Plan de drenaje pluvial: limpieza y ampliación de canales, rejillas en puntos críticos y coordinación con SEDAPAL", 14, "programa progresivo de drenaje pluvial", "Intervenciones de drenaje en avenidas principales y zonas vulnerables antes del 2028"),
        P("gestion", "«Ojo Ciudadano»: transmitir en vivo licitaciones, compras públicas y avances de obras", 14, "Transmitir en vivo licitaciones, compras públicas"),
        P("seguridad", "Centro de Mando Villa 24/7 articulado con subcentrales de videovigilancia y una app municipal de reportes", 15, "Centro de Mando articulado con subcentrales de videovigilancia"),
    ]),
    ("Lucero Echevarría Quispe", "Partido Patriótico del Perú", "partido-patriotico-del-peru", [
        P("seguridad", "Comisión Mixta de Seguridad Ciudadana con PNP, Fuerzas Armadas, municipalidad y comunidad, con un plan de emergencia", 5, "Creación de la Comisión Mixta para la Seguridad Ciudadana"),
        P("seguridad", "Profesionalizar al serenazgo: defensa personal, exámenes toxicológicos, armas no letales y capacitación con la PNP", 6, "ADQUISICION DE ARMAS NO LETALES"),
        P("seguridad", "Ampliar las subcentrales de monitoreo con cámaras de reconocimiento facial enlazadas a la PNP y el Ministerio Público", 6, "Adquirir cámaras inteligentes con reconocimiento facial"),
        P("ambiente", "Programa «Villa Limpia»: contenedores subterráneos e incentivos tributarios a vecinos que participen", 8, "implementación de contenedores subterráneos", "Reducir en 50 % los desechos acumulados en un año y llegar a 10 % al final del periodo"),
        P("ambiente", "Programa «Villa Verde»: arborización de avenidas, mejora de parques y ecopuntos de acopio", 9, "Puntos verdes distritales", "4 campañas anuales de arborización"),
        P("social", "Certificar capacidades técnicas de estudiantes de los dos últimos años de secundaria, en coordinación con UGEL y APAFA", 7, "Certificar las capacidades técnicas de los estudiantes", "Reducir al 1 % la deserción escolar"),
        P("economia", "Programa «Mi Primera Chamba» con el sector privado para egresados de la educación básica", 7, "Promover la inserción laboral de la PEA desocupada", "Reducir a 10 % la PEA desocupada"),
        P("economia", "Ordenanza de promoción de ferias y comercio minorista los fines de semana", 8, "Ordenanza de Promoción de Ferias y comercio minorista", "Ferias 2 días por semana"),
        P("economia", "Centro de Desarrollo Empresarial Municipal y multas graduadas según la infracción y la reincidencia", 8, "reducir y graduar las multas administrativas", "1 Centro de Desarrollo Empresarial Municipal"),
        P("gestion", "Cabildos abiertos trimestrales de rendición de cuentas y comités de cogestión para fiscalizar obras", 9, "Cabildos Abiertos trimestrales", "4 asambleas ciudadanas anuales de rendición de cuentas"),
        P("social", "Crear la Gerencia de la Juventud con una escuela de líderes y programas de cultura, deporte y empleo", 10, "CREACIÓN DE LA GERENCIA DE LA JUVENTUD", "1 Gerencia de la Juventud"),
    ]),
    ("Milton Tomás Lluque Sosa", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "200 cámaras adicionales en los 15 puntos críticos identificados por la PNP y patrullaje integrado nocturno", 8, "Implementar 200 cámaras de videovigilancia adicionales", "200 cámaras adicionales"),
        P("social", "Programa «VES Honra a sus Fundadores»: brigadas médicas domiciliarias y clínica móvil para adultos mayores fundadores", 10, "atención médica domiciliaria gratuita y prioritaria", "1 000 adultos mayores atendidos al año"),
        P("social", "Academia Municipal Preuniversitaria gratuita en dos turnos, en convenio con la UNTELS", 17, "Academia Municipal Preuniversitaria VES", "200 becas por ciclo; 600 alumnos al año"),
        P("transporte", "Red «Villa Integrada»: tres rutas de buses alimentadores a la estación VES de la Línea 1 con tarifa social de S/ 1", 11, "buses alimentadores de mediana capacidad con tarifa social", "Viaje total alimentador más Metro de hasta S/ 2.50"),
        P("transporte", "Formalizar mototaxis con registro único y código QR, GPS y botón de pánico conectado al serenazgo", 13, "Registro Único de Vehículos Menores (RUVM-VES)", "90 % formalizadas en 4 años; 100 % con QR al 2030"),
        P("ambiente", "Sustituir el riego por camión cisterna por aspersión y goteo en parques y bermas", 21, "sustitución progresiva del riego por camión", "100 % tecnificado y 70 % de ahorro de agua al cuarto año"),
        P("ambiente", "Programa «VES Verde»: sembrar árboles y plantas y recuperar parques y bermas con participación vecinal", 21, "siembra de 50,000 árboles y plantas en 4 años", "50 000 árboles y plantas; 20 parques recuperados"),
        P("economia", "Centro de Desarrollo Empresarial VES con asesoría gratuita en formalización, crédito y exportación para MYPE del Parque Industrial", 14, "Centro de Desarrollo Empresarial VES"),
        P("economia", "Reducir el plazo de las licencias de funcionamiento mediante ventanilla única digital", 23, "licencias de funcionamiento de 30 días a 5 días hábiles", "De 30 días a 5 días hábiles"),
        P("gestion", "«Portal Digital VES»: web y app para trámites en línea con pago electrónico y seguimiento", 23, "realizar el 80% de los trámites municipales en línea", "80 % de los trámites en línea"),
        P("gestion", "Presupuesto participativo con votación vecinal digital y audiencias trimestrales en los 9 sectores", 23, "al menos el 15% del presupuesto de inversión", "Al menos 15 % del presupuesto de inversión decidido por los vecinos"),
    ]),
    ("Sugey Tatiana Bernuy Cueva", "PRIN", "partido-politico-prin", [
        P("seguridad", "Reubicar y ampliar cámaras en pasajes, escalinatas, Lomo de Corvina y playas para eliminar puntos ciegos", 2, "Eliminación total de puntos ciegos", "Cobertura del 100 %; reducción del 90 % de delitos"),
        P("seguridad", "Integrar el monitoreo en tiempo real con la Policía, la Fiscalía y los juzgados para intervenir ante alertas", 2, "Integración en tiempo real con Policía, Fiscalía y Juzgados", "Intervención en menos de 5 minutos"),
        P("seguridad", "Plan contra la extorsión y el cobro de cupos, con protección a denunciantes", 2, "guerra frontal contra la extorsión y cobro de cupos"),
        P("ambiente", "Recolección diaria con metas por resultados y eliminación de basurales y vertederos ilegales", 2, "Eliminación definitiva de todos los basurales"),
        P("ambiente", "Recuperar las playas Venecia y Barlovento y crear áreas verdes con plantas nativas y riego tecnificado", 3, "Creación y recuperación de áreas verdes con plantas nativas", "+50 hectáreas de nuevas áreas verdes"),
        P("urbano", "Plan de asfaltado y veredas, con prioridad en asentamientos humanos y accesos al Parque Industrial", 3, "Plan masivo de asfaltado y construcción de veredas", "Cero calles sin pavimentar en zonas habitadas"),
        P("agua_riesgos", "Muros de contención, escaleras y estabilización de suelos en zonas de alto riesgo, y mejora del drenaje pluvial", 3, "Ejecución urgente de muros de contención", "100 % de zonas críticas protegidas"),
        P("economia", "Licencia única en 72 horas y menores arbitrios en el Parque Industrial, con mejoras de vías, energía y agua", 3, "licencia única en 72 horas", "30 % más empresas; más de 15 000 empleos formales"),
        P("economia", "«Ruta de la Identidad» turística por los lugares históricos del distrito y miradores en Lomo de Corvina", 3, "Recuperación de miradores naturales en Lomo de Corvina"),
        P("social", "Convenios con academias deportivas y culturales para escuelas gratuitas en Lomo de Corvina, con campeonatos y ferias mensuales", 4, "Lomo de Corvina Activo y Cultural"),
    ]),
    ("Paúl Dino Carrasco Salazar", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Plan «Villa Segura» de control territorial por zonas, con camionetas de dos serenos y un policía", 12, "integradas por dos serenos y un efectivo de la Policía Nacional"),
        P("seguridad", "Ampliar las cámaras de alta resolución con identificación de rostros y placas", 11, "cámaras de alta resolución con identificador de rostros y placas"),
        P("social", "Crear la Defensoría municipal de la mujer con abogados, psicólogos y trabajadores sociales", 13, "Crearemos la Defensoría municipal de la mujer"),
        P("social", "Programa itinerante de salud mental en colegios, en convenio con la UGEL 01", 13, "Crearemos el programa itinerante de salud mental", "Al menos cuatro equipos de profesionales"),
        P("social", "Recuperar el Coliseo de la Paz, crear la escuela municipal del deporte y construir piscinas temperadas", 15, "Construiremos dos piscinas temperadas", "2 piscinas temperadas"),
        P("economia", "Academia municipal de gastronomía y certificación de restaurantes por categorías", 15, "Contaremos con una academia de gastronomía"),
        P("transporte", "Instalar semáforos en intersecciones que no los tienen, junto con la Municipalidad de Lima, y mantener los existentes", 16, "instalaremos semáforos en las diferentes intersecciones"),
        P("urbano", "Centros descentralizados de atención múltiple con casa de la cultura, atención al adulto mayor y espacios deportivos", 16, "CENTROS DESCENTRALIZADOS DE ATENCIÓN MÚLTIPLE"),
        P("ambiente", "Plan de recojo de residuos con rutas, frecuencias y horarios fijos, barrido y recolección selectiva", 16, "Recogeremos las más de 400 toneladas de basura", "Más de 400 toneladas de basura recogidas al día"),
        P("ambiente", "Centros municipales de rescate animal con esterilización, adopción responsable y vacunación antirrábica", 17, "centros municipales de rescate y protección animal"),
        P("gestion", "Digitalizar la administración municipal y actualizar el TUPA para agilizar los trámites", 18, "Adecuaremos y actualizaremos el Texto Único de Procedimientos"),
    ]),
    ("Walter Quispe Vilcas", "Podemos Perú", "podemos-peru", [
        P("economia", "Amnistías y exoneraciones en licencias de funcionamiento y construcción para formalizar negocios familiares", 4, "Promover amnistías municipales y exoneraciones en licencias de funcionamiento"),
        P("transporte", "Formalizar los vehículos menores informales con un estudio de oferta y demanda con participación de usuarios", 4, "FORMALIZACION DE LOS VEHICULOS MENORES INFORMALES"),
        P("transporte", "Gestionar túneles de acceso entre la Panamericana Sur y avenidas del distrito, como José Carlos Mariátegui", 6, "TUNEL DE ACCESO DE LA Av. JOSE CARLOS MARITEGUI"),
        P("urbano", "Proyecto de densificación urbana con viviendas verticales, con apoyo de colegios profesionales y universidades", 7, "DENSIDIFICACION URBANA DE VILLA EL SALVADOR"),
        P("ambiente", "Contenedores subterráneos fabricados en el Parque Industrial e invernaderos de árboles en parques («Un árbol, una casa»)", 7, "contenedores subterráneos con adecuad identificación"),
        P("gestion", "Programa CADEMUNIVES: canje de deuda de arbitrios por servicios comunales de los vecinos", 7, "canje de deuda con servicios comunales"),
        P("agua_riesgos", "Brigadas de defensa civil y bóvedas en avenidas centrales con maquinaria y material para emergencias", 9, "CONSTRUIR BOVEDAS DE DEFENSA CIVIL EN LAS AVENIDAS CENTRALES"),
        P("seguridad", "CODISEC ampliado con reuniones semanales y patrullaje integrado PNP-serenazgo según mapas de incidencia", 11, "Crear un Comité Distrital de Seguridad (CODISEC ampliado)"),
        P("seguridad", "Cámaras en ejes de mayor incidencia con centro de monitoreo conectado a la PNP", 13, "instalar 20% de cámaras planificadas", "20 % de las cámaras planificadas en los primeros 6 meses"),
        P("social", "Fortalecer el Centro de Emergencia Mujer de VES con atención 24/7", 12, "Fortalecer el Centro de Emergencia Mujer (CEM) en VES"),
        P("social", "Programa «Jóvenes con Futuro»: talleres de oficios, mentoría y deporte en barrios de mayor riesgo", 12, "talleres de oficios, mentoría, actividades deportivas", "Piloto en 3 sectores entre los 6 y 18 meses"),
    ]),
    ("Alberto Luis Peralta Huatuco", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Cámaras con analítica, iluminación LED e interconexión serenazgo-PNP en 12 zonas críticas y las avenidas 200 Millas, Pachacútec y Revolución", 8, "cámaras de videovigilancia analítica, iluminación LED", "90 % de cobertura en las 12 zonas críticas"),
        P("urbano", "Adecuar vías y veredas con criterios de accesibilidad universal para personas con discapacidad y adultos mayores", 8, "criterios universales de accesibilidad", "100 % de km de corredores adecuados"),
        P("social", "Mesas de trabajo y redes vecinales contra la violencia familiar y de género, con las DEMUNA", 8, "redes vecinales de protección contra la violencia familiar", "50 comités sectoriales fortalecidos"),
        P("social", "Convenios con el MINSA para centros de salud mental comunitaria y prevención de adicciones en adolescentes", 8, "salud mental comunitaria y la prevención de adicciones", "6 centros de salud mental comunitaria"),
        P("agua_riesgos", "Proyectos y mesas técnicas con la EPS para redes y conexiones de agua y alcantarillado en los sectores 11, 12 y 13", 10, "conexiones domiciliarias de agua potable y alcantarillado", "95 % de viviendas con agua y 95 % con desagüe"),
        P("transporte", "Plan distrital de pavimentación y bacheo en las calzadas y veredas de las 35 rutas de transporte público afectadas", 10, "plan distrital de pavimentación y bacheo asfaltico", "100 % de las 35 rutas rehabilitadas"),
        P("ambiente", "Arborización, erradicación de botaderos y conversión de espacios degradados en parques con riego eficiente", 10, "programa municipal de arborización masiva", "100 % de parques recuperados"),
        P("economia", "Fiscalización sanitaria y asistencia técnica para certificar los 8 mercados zonales", 10, "certificación de los 8 mercados zonales", "8 mercados certificados"),
        P("economia", "Ventanilla única de formalización MYPE con asistencia técnica integral", 12, "Ventanilla única de Formalización MYPE", "Reducir la informalidad al 30 %"),
        P("gestion", "Plataforma «Municipalidad en tu Móvil» para digitalizar trámites", 13, "Municipalidad en tu Movil", "90 % de trámites en línea"),
        P("gestion", "Presupuesto participativo con votación electrónica para obras barriales y observatorio de transparencia", 13, "votación electrónica para obras de infraestructura barrial"),
    ]),
]
