"""Chorrillos (150108): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150108"

# Planes que no se resumen, con la razón que se muestra junto a la candidatura
NOTAS = {
    "fuerza-popular": "El plan inscrito ante el JNE (3 páginas) solo contiene el ideario y la visión de la organización: no presenta propuestas que resumir. Puedes revisarlo en Voto Informado del JNE.",
}

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Luis Alberto Jiménez Caichihua", "Acción Popular", "accion-popular", [
        P("seguridad", "Dos Centros Integrados de Seguridad y Control Municipal, uno en cada margen del distrito, que reúnan serenazgo, fiscalización, tránsito, videovigilancia y emergencias", 28, "Centros Integrados de Seguridad y Control Municipal", "2 centros, uno por margen"),
        P("seguridad", "Plataforma «Alerta Chorrillos» con botón de pánico y geolocalización, y patrullaje integrado de serenazgo y PNP las 24 horas", 29, "con botón de pánico, geolocalización"),
        P("social", "Programa «Acción Mujer» con orientación psicológica y legal gratuita, y un centro de protección temporal «Wasi Warmi» para víctimas en alto riesgo", 31, "Centro Municipal de Protección Temporal", "100 % del personal de serenazgo capacitado en protocolos de violencia"),
        P("social", "Programa «Nutrición en Acción», registro y capacitación de ollas comunes y comedores, y panaderías municipales comunitarias", 35, "Panaderías Municipales Comunitarias", "Asistencia técnica al 100 % de ollas comunes y comedores registrados"),
        P("agua_riesgos", "Sistema distrital de alerta temprana, mapas de riesgo y rutas de evacuación, simulacros de sismo y tsunami, y brigadas comunitarias", 40, "Sistema Distrital de Alerta Temprana"),
        P("urbano", "Saneamiento físico-legal y titulación de predios de asentamientos humanos y asociaciones de vivienda mediante convenios con COFOPRI", 63, "Organismo de Formalización de la Propiedad Informal"),
        P("ambiente", "Programa «Un Vecino, Un Árbol», corredores ecológicos, puntos limpios de reciclaje y riego tecnificado en parques", 64, "Un Vecino, Un Árbol", "30 % más áreas verdes, 50 000 árboles, 40 % menos residuos a disposición final y riego tecnificado en el 100 % de parques"),
        P("transporte", "Plan distrital de ordenamiento vial y movilidad, semaforización inteligente y una auditoría de accesibilidad peatonal", 58, "Auditoría Integral de Accesibilidad Peatonal"),
        P("transporte", "Red distrital de ciclovías interconectada con distritos vecinos y rutas turísticas en bicicleta (Morro Solar, Pantanos de Villa, Malecón Grau)", 61, "Red Distrital de Ciclovías Seguras"),
        P("economia", "Bolsa de Trabajo Municipal en plataforma digital gratuita y programa de capacitación laboral para jóvenes de escasos recursos", 55, "Bolsa de Trabajo Municipal de Chorrillos"),
        P("gestion", "Plataforma de trámites en línea 24 horas, aplicación «Mi Chorrillos», expediente digital y portal de transparencia interactivo", 70, "aplicación móvil municipal", "100 % de trámites prioritarios digitales, 70 % menos tiempo de atención y 80 % de vecinos usando servicios digitales"),
    ]),
    ("Henry Hernán Herrera Alemán", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Destacamentos Integrados Municipales de Seguridad Ciudadana en cada sector policial, con más operadores y flota de patrullaje", 6, "Destacamentos Integrados Municipales de Seguridad Ciudadana", "Un destacamento por sector"),
        P("seguridad", "Patrullaje aéreo inteligente con drones", 6, "Implementar el Patrullaje Aéreo Inteligente", "12 drones"),
        P("transporte", "Plan contra la congestión vehicular y los paraderos informales, y ordenanza para reordenar los mototaxis", 7, "Aprobar normativa para el reordenamiento de mototaxis", "1 plan y 1 ordenanza"),
        P("agua_riesgos", "Alerta temprana ante tsunami en las zonas residenciales costeras, Centro de Operaciones de Emergencia Distrital y almacén soterrado", 7, "alerta temprana en zonas residenciales costeras", "100 % de zonas residenciales costeras cubiertas"),
        P("agua_riesgos", "Limpieza y descolmatación del río Surco para evitar aniegos", 8, "limpieza y descolmatado del rio Surco", "3 campañas anuales"),
        P("ambiente", "Reordenar la frecuencia de recojo de residuos, días fijos de reciclaje y compra de camiones recolectores", 7, "Adquisición de camiones recolectores", "2 camiones recolectores"),
        P("social", "Farmacias municipales y centros médicos de primer nivel a costo social en ambas márgenes del distrito", 11, "Crear Farmacias Municipales", "3 farmacias municipales y 2 centros médicos de nivel 1"),
        P("ambiente", "Parque ecológico, parques temáticos, un parque zonal y un bosque en la zona de La Chira", 13, "Creación de un bosque en la zona de La Chira", "5 parques temáticos, 1 parque zonal y 1 bosque"),
        P("economia", "Simplificación de licencias, formalización en convenio con el sector público y privado, y comercio ordenado en espacios autorizados", 14, "Simplificación administrativa efectiva y eficaz", "15 % más empleo, 20 % más licencias otorgadas y 5 % menos comercio informal"),
        P("urbano", "Proyectos de inversión con financiamiento público-privado: ampliación de la Av. El Sol hasta Barranco, recuperación del Cercado, pistas, veredas y escaleras", 15, "Ampliación de la Av. El Sol hasta Barranco", "20 km de pistas, 30 km de veredas y 30 escaleras"),
        P("gestion", "Rendición de cuentas dos veces al año, certificación antisoborno ISO 37001 y digitalización de documentos y procesos", 16, "certificación ISO 37001", "80 % de la documentación y procesos digitalizados"),
    ]),
    ("Richard Cortez Melgarejo", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Serenazgo fortalecido, videovigilancia y patrullaje integrado con la PNP en zonas críticas como La Curva, Matellini y Defensores del Morro", 1, "video vigilancia tecnológica y patrullaje integrado", "Reducir 40 % la tasa de victimización respecto a 2026"),
        P("social", "Programa «Jóvenes del Futuro Chorrillos 2030» de competencias digitales, liderazgo, deporte, cultura y empleabilidad", 1, "Jóvenes del Futuro Chorrillos 2030", "25 000 beneficiarios durante la gestión"),
        P("social", "Sistema distrital de prevención y atención de la violencia familiar y escolar, articulado con el MIMP y el MINEDU", 1, "sistema distrital de prevención, atención y sanción de la violencia familiar", "90 % de atención oportuna y 15 escuelas con programas de mediación al 2030"),
        P("economia", "Bolsa Municipal de Empleo y Centro de Formación Técnica Municipal para jóvenes", 2, "Centro de Formación Técnica Municipal", "3 000 empleos gestionados y 2 000 personas capacitadas por año"),
        P("economia", "Formalización de MYPE con un Centro de Desarrollo Empresarial y licencias simplificadas", 2, "Formalizar MYPE mediante el Centro de Desarrollo Empresarial", "2 000 MYPE formalizadas por año y licencias de bajo riesgo en 24 horas al 2030"),
        P("economia", "Plan Maestro del Litoral Chorrillano y proyecto Gran Malecón de Chorrillos 2030 para turismo y gastronomía", 2, "Plan Maestro del Litoral Chorrillano", "60 % más turistas en el litoral respecto a 2026 y 5 inversiones privadas al 2030"),
        P("ambiente", "Modernizar la limpieza pública y extender la segregación de residuos en la fuente", 3, "programa de segregación en la fuente", "30 % de aprovechamiento de residuos y 30 000 viviendas segregando al 2030"),
        P("agua_riesgos", "Actualizar el plan de prevención de riesgos, señalizar rutas de evacuación, hacer simulacros y capacitar brigadas", 3, "actualización del PPRRD", "80 % de la población costera capacitada en evacuación y 500 brigadistas al 2030"),
        P("urbano", "Programa integral de rehabilitación vial y mejoramiento del espacio público", 3, "rehabilitación vial y mejoramiento del espacio público", "80 % de vías principales y 70 % de secundarias recuperadas al 2030"),
        P("transporte", "Semaforización inteligente, ciclovías, accesibilidad universal y gestión del tránsito", 4, "semaforización inteligente, ciclovías, accesibilidad universal", "25 km de ciclovías al 2030"),
        P("gestion", "Trámites municipales digitales, aplicación del vecino y menos tiempo de atención presencial", 4, "aplicación móvil del vecino", "80 % de trámites digitalizados y atención presencial en menos de 15 minutos al 2030"),
    ]),
    ("Ricardo Herminio Bejarano Fernández", "Fe en el Perú", "fe-en-el-peru", [
        P("seguridad", "«Escudo Digital Chorrillos»: cámaras con lectura de placas y una app de alerta vecinal georreferenciada que activa al sereno más cercano", 10, "App de Alerta Vecinal Geo-referenciada", "Respuesta en menos de 5 minutos"),
        P("seguridad", "Drones con cámaras térmicas para vigilar playas y acantilados, organizados por cuadrantes", 10, "Drones de Vigilancia Costera"),
        P("seguridad", "Estaciones de serenazgo en zonas estratégicas del distrito", 11, "estaciones de Serenazgo en zonas estratégicamente", "20 a 30 estaciones"),
        P("agua_riesgos", "Primera planta desalinizadora de agua de mar para consumo humano", 8, "planta desalinizadora de agua de mar"),
        P("ambiente", "Primera planta de reciclaje municipal, con entrega de bolsas para residuos", 8, "primera planta de reciclaje municipal"),
        P("transporte", "Revisar y sincronizar los semáforos de las avenidas y mejorar el circuito vehicular", 8, "sincronizar los semáforos de nuestras avenidas"),
        P("urbano", "Playa de estacionamiento subterráneo en el Parque Fátima para la zona de Defensores del Morro", 16, "Estacionamiento Subterráneo en el Parque Fátima"),
        P("economia", "Programa «Chorrillos Emprende» de formalización con cero arbitrios el primer año para negocios de mujeres y jóvenes", 17, "Chorrillos Emprende"),
        P("economia", "Corredor gastronómico y turístico con circuito peatonal entre el Salto del Fraile, el Muelle de Pescadores y La Herradura", 18, "Puesta en valor de la zona del Salto del Fraile"),
        P("social", "Centros municipales de innovación tecnológica para que niños y jóvenes aprendan robótica, programación y artes digitales", 15, "Centros de Innovación Tecnológica (CIT)"),
        P("gestion", "Expediente electrónico y firma digital, pagos de tributos trazables en blockchain y asistente virtual por WhatsApp", 6, "Plataforma de Pagos Blockchain", "Licencias de funcionamiento y de construcción 100 % en línea"),
    ]),
    ("María del Rosario Neyra Onofre", "Fuerza Popular", "fuerza-popular", []),
    ("Josian Tatiana Calmet León", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Central integrada de videovigilancia 24 horas, patrullaje integrado serenazgo-policía y programa «Barrio Seguro» con juntas vecinales", 2, "Central integrada de videovigilancia 24 horas", "30 % menos delitos denunciados, 40 % menos puntos críticos y respuesta en menos de 10 minutos"),
        P("seguridad", "Observatorio distrital del delito, botones de pánico vecinales y cámaras con reconocimiento de placas", 5, "Creación de observatorio distrital del delito"),
        P("ambiente", "Contenedores diferenciados, formalización de recicladores, arborización masiva y recuperación de playas y humedales", 2, "Formalización de recicladores", "50 % más áreas verdes y 25 % de residuos reciclados"),
        P("urbano", "Pavimentación integral de vías y renovación de veredas", 3, "Pavimentación integral de vías", "100 km de vías rehabilitadas"),
        P("urbano", "Construcción de parques modernos y mantenimiento permanente de la infraestructura urbana", 3, "Construcción de parques modernos", "100 % de parques con mantenimiento permanente"),
        P("transporte", "Semaforización inteligente, ordenamiento del transporte local, ciclovías y fiscalización del transporte informal", 3, "Semaforización inteligente. Ordenamiento del transporte local", "20 % menos tiempo de desplazamiento y señalización vial en todo el distrito"),
        P("economia", "Centro Municipal de Emprendimiento, bolsa de empleo distrital, ferias y capacitación en transformación digital", 3, "Centro Municipal de Emprendimiento. Bolsa de empleo distrital", "10 000 vecinos capacitados y 5 000 empleos facilitados"),
        P("economia", "Ruta turística de playas, circuito histórico y gastronómico y marca territorial «Chorrillos»", 3, "Ruta turística de playas"),
        P("social", "Campañas médicas gratuitas, atención preventiva al adulto mayor, salud mental comunitaria y lucha contra la anemia infantil", 3, "Lucha contra la anemia infantil"),
        P("social", "Academias deportivas, escuelas de arte y música, bibliotecas digitales y becas de capacitación técnica", 4, "Escuelas de arte y música", "20 000 beneficiarios por año"),
        P("gestion", "Municipalidad digital con aplicación móvil, mesa de partes virtual, expediente electrónico y portal de transparencia en tiempo real", 4, "Portal de transparencia en tiempo real", "100 % de trámites digitalizados, 50 % menos tiempo de atención e indicadores publicados cada mes"),
    ]),
    ("Giuliano Fabrizio Bacigalupo Padilla", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("social", "Equipar el centro de salud y una central de emergencias con motoambulancias, ambulancia y personal médico las 24 horas", 13, "Equipar el centro de salud", "5 motoambulancias, 1 ambulancia, 5 equipos de RCP y 1 sala de emergencia equipada"),
        P("agua_riesgos", "Búnkeres equipados con alimentos y equipos en distintas zonas y capacitación de todo el personal municipal ante desastres", 13, "12 bunkers subterráneos", "12 búnkeres subterráneos y 100 % del personal capacitado"),
        P("seguridad", "Central de emergencias de Chorrillos con unidades motorizadas y personal capacitado", 14, "10 cuatrimotos", "1 puesto de monitoreo, 10 cuatrimotos, 4 camionetas y 80 % menos delincuencia"),
        P("seguridad", "Drones con estaciones de vuelo y carga, centro de monitoreo aéreo y cámaras con detección de rostros", 12, "Construcción de estaciones de vuelo y carga para drones"),
        P("urbano", "Constancias de posesión y gestión de alumbrado, agua y desagüe para asentamientos humanos sin servicios", 14, "constancias de posesión", "100 % de habitantes de esas zonas con constancia de posesión, electricidad y alumbrado"),
        P("urbano", "Construcción de pistas y veredas y señalización de calles", 14, "Construir 20 km de pistas", "20 km de pistas y veredas y 100 % de calles señalizadas"),
        P("economia", "Promover la inversión privada y el turismo todo el año, y priorizar la contratación de vecinos", 14, "Disminuir en un 50% la", "50 % menos desempleo, 200 % más turismo y 80 % del personal municipal vecino del distrito"),
        P("transporte", "Circuito de ciclovías que conecte el distrito", 14, "ciclovías que conecten", "50 km de ciclovías"),
        P("agua_riesgos", "Planta moderna de tratamiento de aguas servidas", 15, "planta de tratamiento de aguas", "Capacidad de 20 000 m³ o más"),
        P("ambiente", "Plantar árboles captadores de CO2", 15, "Plantar 10 000 árboles", "10 000 árboles"),
        P("gestion", "Sesiones de concejo abiertas con sala de prensa, publicación de costo, plazo y beneficiarios de cada obra y norma ISO anticorrupción", 15, "Crear el salón de la prensa", "100 % de sesiones públicas y 100 % de obras publicadas"),
    ]),
    ("Luciano Tuñoque Mori", "Partido Demócrata Unido Perú", "partido-democrata-unido-peru", [
        P("seguridad", "Sistema integrado de seguridad entre municipio, comisaría, gobernación, juzgados y empresa privada, con módulos descentralizados y cámaras", 6, "Sistema Integrado de Seguridad Ciudadana"),
        P("seguridad", "Convenio para contratar policías en sus días de franco y más serenos capacitados", 6, "efectivos policiales durante sus días de franco"),
        P("social", "Cunas municipales gratuitas en ambas márgenes para hijos de madres que trabajan, de 1 a 4 años", 4, "CUNAS MUNICIPALES INFANTILES"),
        P("social", "Convenio con SENATI para instalar una sede en el distrito con carreras técnicas para jóvenes", 4, "Servicio Nacional de Adiestramiento en Trabajo Industrial"),
        P("social", "Recuperar la clínica ChorriSalud con tarifas sociales para la comunidad", 4, "Recuperación de la Clínica CHORRISALUD"),
        P("social", "Más raciones en el Vaso de Leche, los comedores populares y las ollas comunes", 5, "Incremento de raciones en los tres"),
        P("gestion", "Sesiones de concejo descentralizadas en locales comunales de ambas márgenes", 4, "Sesiones de Concejo Descentralizadas"),
        P("gestion", "Comités vecinales que vigilen el inicio, avance y término de cada obra municipal en su sector", 4, "COMITES VECINALES en todas las Obras"),
        P("ambiente", "Compra de compactadoras y un camión madrina para el recojo y traslado de residuos sin pagar a terceros", 5, "Se adquirirán 10 COMPACTADORAS", "10 compactadoras y 1 camión madrina"),
        P("urbano", "Apoyo en saneamiento físico-legal de lotes y en agua y alcantarillado para ambas márgenes", 5, "Saneamiento Físico Legal de sus terrenos"),
        P("urbano", "Escaleras que conecten laderas y cerros, más áreas verdes y limpieza pública en esas zonas", 6, "construcción de escaleras como medio de conexión"),
    ]),
    ("Ricardo Santiago Vásquez Laguna", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Acciones de prevención de delitos y faltas en coordinación con las instituciones públicas", 18, "Reducir en 80% las incidencias de delitos y faltas", "Reducir en 80 % las incidencias de delitos y faltas al 2030"),
        P("social", "Prevenir y reducir la violencia hacia la mujer en el distrito", 20, "Reducir en un 30% la incidencia de todo tipo de violencia hacia la mujer", "Reducir en 30 % la incidencia de violencia hacia la mujer al 2030"),
        P("social", "Recuperar obras municipales como el Hogar del Niño, el Asilo de Ancianos y la Maternidad Municipal", 17, "La recuperación de las Obras Municipales"),
        P("social", "Construir un hospital municipal de nivel 3 para emergencias y controles médicos de los vecinos", 13, "construcción de un Hospital Municipal nivel 3"),
        P("social", "Construir una veterinaria municipal para que los vecinos de menos recursos atiendan a sus mascotas", 21, "Construcción de una veterinaria municipal"),
        P("transporte", "Mecanismo de formalización y control de los mototaxistas", 21, "Establecer un mecanismo de formalización y control para los mototaxistas"),
        P("urbano", "Pistas y veredas en Delicias de Villa, San Juan de la Libertad y otros pueblos que las necesitan, y parchado de huecos", 17, "Pistas y Veredas en las Delicias de villa"),
        P("economia", "Programa municipal que canalice oportunidades laborales en alianza con las empresas", 22, "1 programa implementado para canalizar la formación y oferta laboral", "1 programa implementado"),
        P("ambiente", "Mejorar el recojo y la segregación de residuos, con islas de contenedores soterrados en los puntos de acumulación", 24, "Instalar en los puntos de gran acumulación de residuos sólidos islas de"),
        P("agua_riesgos", "Vigilar y controlar las zonas del Morro Solar expuestas a invasiones con riesgo de derrumbes", 25, "Realizar un mejor cuidado y control de las áreas que puedan ser pasibles de invasión"),
        P("gestion", "Portal web de fácil consulta sobre la gestión y los servicios, con un espacio para opiniones de los vecinos", 25, "Diseñar un portal web de fácil consulta sobre información de la gestión"),
    ]),
    ("Kruger Kelvin Vidal Quispe", "Partido Morado", "partido-morado", [
        P("seguridad", "Programa «Caminos Seguros» de urbanismo táctico y Serenazgo Comunitario en zonas críticas", 9, "Implementación del programa de urbanismo táctico", "Delitos contra el patrimonio por debajo de 7,0 por cada 1 000 habitantes y percepción de inseguridad menor al 70 % al 2030"),
        P("seguridad", "Conectar los vehículos del serenazgo al sistema de rastreo SIPCOP-M del MININTER para coordinar con la PNP", 10, "Integración tecnológica de la flota vehicular", "100 % de la flota operativa (76 unidades) integrada al SIPCOP-M"),
        P("social", "Red Nutricional «Ollas de Hierro» con pescadores, mercados y comités comunitarios contra la anemia infantil", 11, "Creación de la Red distrital Nutricional", "Anemia en niños de 6 a 35 meses por debajo de 22 % al 2030"),
        P("social", "Consultorio Veterinario Municipal en el Parque Urbano San Genaro, campañas itinerantes y albergue de animales rescatados", 12, "Consultorio Veterinario Municipal de atención primaria", "5 000 atenciones en 2028; 2 000 esterilizaciones y 8 000 vacunaciones al año"),
        P("urbano", "Auditoría y rediseño de estadios, complejos y losas como espacios polivalentes con iluminación y mobiliario inclusivo", 13, "Ejecución de una auditoría técnica de los estadios", "Inventario completo y 3 primeras intervenciones polivalentes en los sectores III y IV"),
        P("economia", "Programa «Chorrillos Trabaja»: bolsa de trabajo en la web municipal, aula piloto y talleres de empleabilidad", 14, "Integrar una bolsa laboral en la web municipal", "200 vecinos en empleos validados y 1 000 independientes capacitados en 2028"),
        P("economia", "Programa «Muelle con Historia»: veredas, iluminación y señalización en el entorno del muelle y certificación de pescadores como guías", 16, "Ejecutar un plan de acondicionamiento urbano menor", "50 pescadores capacitados en 2027 y 100 % de paseos con certificación municipal al 2030"),
        P("ambiente", "Demoler el estadio paralizado de San Genaro y convertir el terreno en el Parque Urbano-Cultural San Genaro con huertos y árboles", 17, "Realizar el peritaje técnico-legal y demolición", "Parque entregado en 2030"),
        P("ambiente", "Puntos Limpios y estaciones de reciclaje en los 7 sectores y planta de compostaje con residuos orgánicos de mercados", 18, "Planta de Compostaje mediante el sistema", "70 % de los mercados con separación de orgánicos en 2028"),
        P("transporte", "Red de municipios escolares con «Ficha de Alerta Escolar» y pasos peatonales seguros e iluminación en entornos de colegios", 21, "Ficha de Alerta Escolar", "Señalización del 100 % de los entornos de los 10 primeros colegios en 2028"),
        P("gestion", "Ventanilla Única Virtual con formularios en línea y avisos por SMS o correo sobre el estado del expediente", 19, "Ventanilla Única Virtual Inteligente", "20 trámites en línea en 2027 y 50 % menos tiempo de respuesta en 2028"),
    ]),
    ("Jorge Luis Chicata Moreno", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Convenios para pagar los días de franco de policías y zonificar el distrito en 8 zonas de vigilancia", 8, "Zonificación del distrito (8 zonas)"),
        P("seguridad", "Comprar cámaras de vigilancia, drones y vehículos para el serenazgo", 8, "Compra de 64 camionetas, 64 autos y 64 motos", "64 camionetas, 64 autos y 64 motos"),
        P("agua_riesgos", "Gestionar el acceso al agua potable para la población que no la tiene", 8, "apoyaremos a más del 30% de la población Chorrillana"),
        P("social", "Construir policlínicos municipales con especialidades básicas, ambulancia y atención a bajo costo", 8, "Construcción e implementación de 4 Policínicos Municipales", "4 policlínicos"),
        P("social", "Pre-academias municipales y carreras técnicas cortas mediante convenios, y apoyo con desayuno escolar", 9, "Pre-Academias Municipales"),
        P("social", "Escuelas deportivas gratuitas todo el año y apoyo a ligas y deportistas, incluidos los que tienen discapacidad", 9, "Escuela deportivas gratuitas todo el año"),
        P("transporte", "Coordinar con Lima el bypass del óvalo La Curva, ampliar la Av. Guardia Civil y culminar la vía alterna de La Herradura", 10, "construcción del ByPass del Ovalo la Curva"),
        P("transporte", "Reorganizar las rutas y fiscalizar el transporte público y escolar", 11, "Fiscalización y control al servicio público y escolar"),
        P("economia", "Ferias periódicas y dominicales para las MYPES, con facilidades para su formalización", 10, "ferias periódicas y dominicales"),
        P("ambiente", "Fiscalizar con cámaras a quienes sacan la basura fuera de horario y controlar los camiones recolectores", 11, "Fiscalización con cámaras para los vecinos"),
        P("urbano", "Construir pistas y veredas donde no existen y convenio con Cofopri", 12, "Construcción de pistas y veredas en zonas que no tienen"),
    ]),
    (None, "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Central Inteligente de Monitoreo, videovigilancia con reconocimiento facial y lectura de placas, y drones", 2, "Implementar una Central Inteligente de Monitoreo"),
        P("seguridad", "Patrullaje integrado con la PNP y juntas vecinales de seguridad por sectores", 2, "Crear juntas vecinales de seguridad por sectores"),
        P("social", "Centros de salud por obras por impuestos, campañas médicas y convenios con universidades y clínicas para atención gratuita o de bajo costo", 2, "Convenios con universidades y clínicas para atención gratuita"),
        P("social", "Programa «Salud Inclusiva para Todos»: atención preferente y terapias para niños con discapacidad en las postas", 10, "Salud Inclusiva para Todos"),
        P("social", "Instituto Técnico Municipal con carreras de construcción, electricidad, mecánica, gastronomía, tecnología y turismo", 12, "INSTITUTO TÉCNICO MUNICIPAL DE CHORRILLOS"),
        P("economia", "Programa «Chorrillos Inclusivo Trabaja» con bolsa de trabajo y capacitación para personas con discapacidad", 11, "Incorporar a 1,000 personas con discapacidad", "1 000 personas con discapacidad con empleo formal, 2 000 capacitadas y convenios con 100 empresas"),
        P("economia", "Programa «Mujer Emprende Chorrillos»: comedores populares como centros de capacitación, con guarderías comunitarias", 8, "Transformar los comedores populares y locales comunales"),
        P("economia", "Recuperar el malecón, promover circuitos históricos y crear la marca turística «Chorrillos Todo el Año»", 4, "Chorrillos Todo el Año"),
        P("urbano", "Recuperar y modernizar losas deportivas e iluminar espacios deportivos, con gimnasios al aire libre", 7, "Recuperación y modernización de losas deportivas"),
        P("ambiente", "Planta municipal de segregación y valorización de residuos y formalización de recicladores", 5, "Implementar una planta municipal de segregación y valorización"),
        P("gestion", "Publicación mensual de ingresos y gastos y audiencias trimestrales de rendición de cuentas", 4, "Publicación mensual de ingresos y gastos municipales"),
    ]),
    ("Jorge Ignacio Guzmán Niño", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Patrullaje integrado por cuadrantes, más vehículos y cámaras con analítica de datos e inteligencia artificial", 5, "Expansión del patrullaje municipal permanente", "Reducir la incidencia delictiva a una tasa acumulada de -6,6 % al 2030"),
        P("urbano", "Formalizar habilitaciones urbanas en zonas aptas para mejorar el acceso de los asentamientos a servicios básicos", 7, "Lograr el 75% de habilitaciones urbanas formalizadas", "75 % de habilitaciones urbanas formalizadas en el territorio apto"),
        P("social", "Visitas domiciliarias de control contra la anemia infantil, con el MINSA, Vaso de Leche y comedores", 7, "5,800 visitas anuales de control y prevención", "5 800 visitas anuales"),
        P("social", "Escuelas municipales descentralizadas para niños y jóvenes de 3 a 17 años y atención contra la violencia familiar con el CEM", 5, "escuelas municipales descentralizadas para jóvenes de 3 a 17 años"),
        P("economia", "Operativos preventivos de fiscalización para llevar al comercio informal hacia la formalidad", 7, "Incrementar a 16.96% la tasa de variación", "Incrementar a 16,96 % la tasa de variación de agentes económicos formales"),
        P("economia", "Talleres técnico-productivos y de comercio electrónico para microempresarios", 7, "50 empresarios capacitados participando anualmente", "50 empresarios capacitados al año"),
        P("economia", "Programa de Desarrollo Turístico con infraestructura en el Malecón Grau, playas de la Costa Verde y rutas históricas", 7, "Ejecutar 20 acciones estratégicas de desarrollo e impacto turístico", "20 acciones estratégicas de desarrollo turístico"),
        P("ambiente", "Programa de segregación en la fuente para elevar el reciclaje inorgánico", 6, "programa de segregación en la fuente", "Reciclaje inorgánico al 1,56 % de la masa total distrital"),
        P("ambiente", "Normas de fiscalización ambiental para controlar gases, humos y ruidos en zonas comerciales y residenciales", 6, "controlar la emisión de gases, humos y ruidos"),
        P("agua_riesgos", "Fortalecer el Centro de Operaciones de Emergencia Local y preparar a la comunidad ante sismos y tsunamis", 8, "Consolidar y mantener el 100% de la capacidad operativa básica del COEL", "100 % de la capacidad operativa básica del COEL"),
        P("gestion", "Actualizar el catastro urbano y mejorar la recaudación de arbitrios e impuesto predial", 8, "Incrementar la recaudación efectiva oportuna al 71.43%", "Recaudación efectiva de 71,43 % de lo emitido"),
    ]),
    ("Dionisio Navarro de la O", "Progresemos", "progresemos", [
        P("seguridad", "Plan «Paradero Seguro» con brigadas de serenazgo en paraderos, drones y empadronamiento de mototaxis", 8, "Paradero Seguro: Corredores Chorrillanos", "Reducir en 45 % los delitos en paraderos críticos al 2030"),
        P("seguridad", "Central de Despacho Unificado con serenazgo y policías de las cuatro comisarías en una sola plataforma", 8, "Central de Despacho Unificado Chorrillos Seguro", "Tiempo de respuesta menor a 5 minutos al 2030"),
        P("urbano", "Programa «Iluminando Espacios Críticos»: luminarias LED en pasajes de laderas y zonas junto a los Pantanos de Villa", 8, "Iluminando Espacios Críticos", "150 puntos ciegos recuperados al 2030"),
        P("social", "Programa «Chorrillos Nutritivo» con tamizaje de hemoglobina y micronutrientes a través de comedores y ollas comunes", 10, "anemia ferropénica en niños menores de 3 años en las zonas de laderas críticas", "Anemia en menores de 3 años en laderas al 12 % al 2030"),
        P("social", "Centros de Escucha y Bienestar Emocional con psicólogos en San Genaro, Mateo Pumacahua y Buenos Aires de Villa", 10, "Red de Centros Municipales de Escucha y Bienestar Emocional", "25 000 atenciones psicológicas al año al 2030"),
        P("social", "«Aulas Digitales Conectadas»: contenidos pedagógicos sin internet, equipos portátiles y capacitación docente en colegios de laderas", 11, "Aulas Digitales Conectadas", "100 % de colegios públicos periféricos con laboratorios y conectividad al 2030"),
        P("urbano", "Programa «Losa Segura, Vida Activa»: rehabilitar losas barriales con iluminación LED solar para uso nocturno gratuito", 17, "Losa Segura, Vida Activa", "85 % de las losas deterioradas recuperadas al 2030"),
        P("economia", "Ventanilla de acompañamiento al emprendedor para formalización, licencias y orientación tributaria", 20, "más de 4,000 emprendedores y microempresarios", "Más de 4 000 emprendedores asistidos y 50 % menos tiempo en licencias"),
        P("economia", "Escuela Municipal de Empleo y Emprendimiento con capacitación técnica para jóvenes, mujeres y adultos", 20, "Se capacitará a más de 6,000 vecinos", "Más de 6 000 vecinos capacitados y 2 000 oportunidades de inserción laboral"),
        P("ambiente", "Programa «Chorrillos Limpio» con nuevas rutas de recolección y fiscalización de puntos críticos", 22, "Reducir en un 80% los puntos críticos", "Reducir en 80 % los puntos críticos de residuos en 2027-2030"),
        P("gestion", "«Municipio Digital 24/7» para pagar, consultar y hacer seguimiento de trámites en línea", 25, "trámites más demandados por los vecinos puedan realizarse de manera virtual", "80 % de los trámites más demandados en línea y 50 % menos tiempo de atención"),
    ]),
    ("Roberto Carlos Pizarro López", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Dividir el distrito en 8 bases operativas con centro de monitoreo, cámaras inteligentes y personal, en coordinación con la PNP", 7, "dividiendo el distrito en 8 bases operativas"),
        P("seguridad", "Reactivar los Centros de Asistencia Rápida y cámaras con reconocimiento facial en puntos estratégicos", 7, "Reactivar y modernizar Centros de Asistencia Rápida"),
        P("ambiente", "Contenedores en zonas de alta densidad, servicio de fono limpieza las 24 horas y renovación de la flota municipal", 8, "servicio de fono limpieza"),
        P("economia", "Circuito turístico desde la Costa Verde hasta los Pantanos de Villa y museo histórico de Chorrillos", 8, "Creación del circuito turístico en nuestro distrito"),
        P("social", "Escuela Municipal de Alto Rendimiento Deportivo y recuperación de campos y losas con grass natural y sintético", 9, "Escuela de alto rendimiento Municipal del Deporte"),
        P("social", "Modernizar la Clínica Municipal con especialidades básicas como pediatría, ginecología, odontología y laboratorio", 10, "Complejo Asistencial de Salud (Clinica Municipal)"),
        P("social", "Casa de la Mujer con atención psicológica, social y jurídica a víctimas de violencia, y modernizar la casa del adulto mayor", 11, "Creación de la casa de la mujer"),
        P("economia", "Complejos comerciales con la empresa privada para formalizar al comercio informal y licencias más rápidas y baratas", 12, "construcción de modernos complejos comerciales"),
        P("transporte", "Obras viales peatonales y vehiculares prioritarias, con semaforización y señalización", 13, "Ejecutar con prioridad obras de infraestructura vial"),
        P("agua_riesgos", "Cobertura total de agua y desagüe en coordinación con entidades públicas y privadas, y Techo Propio Municipal", 13, "Promover la cobertura total al 100% de los servicios de agua y desagüe", "100 % de cobertura de agua y desagüe"),
        P("gestion", "Municipalidad con trámites totalmente virtuales y sistema digital de quejas y sugerencias", 14, "Implementar una Municipalidad con tramites al 100% virtual", "100 % de trámites virtuales"),
    ]),
]
