"""La Victoria (150115): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150115"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Luis Álvaro Pletikosic Guzmán", "Acción Popular", "accion-popular", [
        P("seguridad", "Plan Integral de Seguridad Humana Territorial: todas las cámaras interconectadas con lectura de placas y rostros, serenazgo descentralizado con módulos en puntos críticos y programa «Vecino Sereno»", 15, "Plan Integral de Seguridad Humana Territorial", "Reducir en 45 % la incidencia delictiva común al 2030"),
        P("urbano", "Rehabilitar losas deportivas, parques y plazas con iluminación LED, y mejorar los accesos peatonales en las faldas de los cerros con escaleras y barandas", 16, "Renovación de Infraestructura Cívica y Espacios Públicos", "Recuperar el 100 % de los parques zonales y plazas residenciales desatendidas al 2030"),
        P("economia", "Formalización del comercio ambulante con registro técnico, corredores comerciales temporales regulados e incubadoras empresariales municipales con capacitación y facilidades tributarias", 17, "registro técnico de comerciantes autónomos", "Formalizar al 50 % del comercio autónomo itinerante al 2030"),
        P("transporte", "Padrón municipal de mototaxis con paraderos autorizados y señalizados, y horarios exclusivos de carga y descarga para liberar las vías en horas punta", 18, "padrón municipal estricto de vehículos de transporte menor", "Ordenar el 100 % de las rutas de transporte menor al 2030"),
        P("ambiente", "Reestructurar rutas y frecuencias de las compactadoras y exigir segregación y recolección selectiva a los grandes generadores comerciales e industriales", 18, "recolección selectiva obligatoria para grandes generadores", "Eliminar el 100 % de los puntos críticos de acumulación de basura al 2030"),
        P("ambiente", "Programa «Un Árbol, Un Vecino»: arborización de bermas centrales y recuperación de jardines con plantas nativas de bajo consumo de agua", 19, "plantas nativas de bajo consumo de agua", "Duplicar la superficie de áreas verdes al 2030"),
        P("social", "Apoyo logístico y sanitario a ollas comunes y comedores populares de El Pino, San Cosme, El Porvenir y Matute para reducir la anemia infantil", 10, "fortalecerá logística y sanitariamente a las ollas comunes"),
        P("gestion", "Municipio Digital: todos los trámites por internet y licencias de funcionamiento digitales automáticas para comercios de bajo riesgo", 20, "licencias de funcionamiento digitales automáticas", "Virtualizar la totalidad del TUPA al 2030"),
        P("gestion", "Cámaras corporales obligatorias para los inspectores municipales en cada intervención", 20, "cámaras corporales (bodycams) obligatorias"),
        P("gestion", "Portal «Gamarra y La Victoria Transparente» con el avance físico y financiero de cada obra, enlazado al sistema de seguimiento del MEF", 23, "Dashboard de Obras Abiertas", "100 % de las obras ejecutadas publicadas en la plataforma"),
        P("gestion", "Cabildos abiertos y audiencias de rendición de cuentas itinerantes en Matute, Balconcillo, El Porvenir, San Cosme y El Pino", 23, "Cabildos Abiertos Descentralizados y Audiencias de Rendición de Cuentas", "Cada seis meses"),
    ]),
    ("Nilda Esperanza Carranza Rodríguez", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Sistema integral de videovigilancia, patrullaje conjunto con la Policía Nacional y programas de prevención juvenil", 19, "sistema integral de videovigilancia, patrullaje conjunto", "Reducir en 25 % la delincuencia en zonas críticas"),
        P("economia", "Formalización progresiva de comerciantes de Gamarra y de los mercados locales, con incentivos tributarios", 19, "Estrategias progresivas para integrar comerciantes de Gamarra", "Formalizar al menos el 40 % de los comerciantes informales en Gamarra"),
        P("economia", "Incubadoras municipales y acceso a microcréditos para emprendedores", 19, "Creación de incubadoras municipales y acceso a microcréditos"),
        P("ambiente", "Plantas de reciclaje y programas de segregación de residuos en la fuente", 20, "Implementar plantas de reciclaje y programas de segregación en la fuente", "Reciclar el 30 % de los residuos sólidos"),
        P("urbano", "Recuperar parques y plazas con arborización y áreas recreativas", 20, "Recuperar 15 espacios públicos con infraestructura verde", "15 espacios públicos recuperados"),
        P("transporte", "Promover ciclovías, un transporte público eficiente y menos contaminación vehicular", 20, "Promover ciclovías, transporte público eficiente"),
        P("gestion", "Digitalizar trámites y servicios municipales", 20, "Digitalizar el 70% de trámites municipales", "70 % de los trámites municipales digitalizados"),
        P("gestion", "Consejos vecinales, plataformas de consulta pública, auditorías ciudadanas y rendición de cuentas semestral", 20, "Auditorías ciudadanas y rendición de cuentas semestral"),
        P("social", "Campañas de prevención de tuberculosis, hipertensión y salud mental; fortalecer las postas médicas y los convenios con hospitales", 23, "campañas de prevención contra tuberculosis"),
        P("social", "Programas de becas técnicas y superiores y mejora de la infraestructura escolar", 24, "Crear programas de becas técnicas y superiores"),
        P("urbano", "Programas de renovación urbana y mejoramiento de viviendas tugurizadas", 24, "Programas de renovación urbana y mejoramiento de tugurios"),
    ]),
    ("Joaquín Reynaldo Albarracín Ramos", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Cámaras de videovigilancia HD con inteligencia artificial y lectura de placas integradas al Centro de Control, y flota del serenazgo operativa al 100 %", 6, "Instalación de 200 cámaras de videovigilancia HD", "200 cámaras; victimización de 42,5 % a menos de 25 % al 2030"),
        P("urbano", "Proyecto «Parques Seguros La Victoria»: parques con iluminación LED solar y mobiliario inclusivo, y nuevas losas deportivas multifuncionales", 6, "Parques Seguros La Victoria", "Recuperar el 100 % de los parques, plazas y losas en abandono"),
        P("agua_riesgos", "Ampliar el equipo de inspectores técnicos de seguridad en edificaciones y fiscalizar el almacenamiento de inflamables en las galerías de Gamarra", 6, "Ampliar el equipo de inspectores de ITSE de 8 a 25", "De 8 a 25 inspectores; 80 % de cobertura de inspecciones en inmuebles de riesgo"),
        P("social", "Local municipal para el Centro de Salud Mental Comunitario y equipamiento de terapia para niños con autismo y TDAH", 7, "Garantizar la continuidad y optimización del Centro de Salud Mental Comunitario"),
        P("social", "Academia Municipal preuniversitaria gratuita para estudiantes destacados y becas con apadrinamiento de empresas de Gamarra", 8, "Creación de la Academia Municipal de La Victoria", "100 becas piloto (2027-2028) y 200 en la segunda promoción"),
        P("economia", "Registro digital georreferenciado del comercio ambulatorio y nuevas ferias modulares para reubicar a comerciantes de la vía pública", 10, "Crear 3 nuevas ferias modulares con puestos normados", "3 ferias modulares; formalizar al 60 % de los comerciantes ambulatorios censados"),
        P("economia", "Plataforma «Licencia Express La Victoria»: licencia de funcionamiento 100 % en línea con pago electrónico", 10, "Licencia Express La Victoria", "Licencias de 45 a 10 días hábiles"),
        P("transporte", "Plan de Movilidad Local y paraderos formales señalizados para mototaxis y vehículos menores, con grúas municipales operativas", 10, "Señalizar y habilitar 40 paraderos formales", "40 paraderos formales y 70 % menos paraderos informales"),
        P("ambiente", "Rutas de recolección con análisis GIS, eco-puntos de reciclaje y formalización de 200 recicladores en el programa «La Victoria Recicla»", 16, "Instalar 150 eco-puntos de reciclaje", "150 eco-puntos; eliminar los 35 puntos críticos el primer año y segregar el 25 % de los residuos al 2030"),
        P("ambiente", "Programa «La Victoria Verde»: arborización de bermas con especies nativas y riego por goteo con aguas residuales tratadas", 17, "arborización de 15 km de bermas centrales", "15 km de bermas; de menos de 2 a 5 m² de áreas verdes por habitante al 2030"),
        P("gestion", "Portal Ciudadano con todos los trámites en línea, aplicación móvil municipal y expediente virtual con firma electrónica", 20, "Lanzar el Portal Ciudadano La Victoria Digital", "80 % de los trámites digitalizados al 2030"),
    ]),
    ("Joe Zanabria Soberón", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Sistema distrital de seguridad inteligente con cámaras y mejor tiempo de respuesta del serenazgo", 14, "1,000 cámaras inteligentes", "1 000 cámaras inteligentes y respuesta en 5 minutos o menos al 2030"),
        P("seguridad", "Enfrentar la extorsión, el cobro de cupos y el crimen organizado para recuperar el principio de autoridad", 14, "Reducir la criminalidad organizada y recuperar el principio de autoridad", "Reducir en 45 % los delitos al 2030"),
        P("social", "Red distrital de salud mental comunitaria con atención psicológica gratuita", 15, "Implementar red distrital de salud mental comunitaria", "150 000 atenciones psicológicas acumuladas al 2030"),
        P("social", "Recuperar espacios culturales, deportivos y comunitarios", 15, "Recuperar infraestructura social y comunitaria", "50 espacios públicos recuperados al 2030"),
        P("economia", "Formalización empresarial simplificada con licencias digitales", 15, "Impulsar formalización empresarial simplificada", "40 % de negocios formalizados al 2030"),
        P("economia", "Convertir Gamarra en un hub textil internacional con un centro de innovación textil y comercio electrónico", 15, "Transformar Gamarra en hub textil internacional", "80 % de los negocios incorporados al ecosistema digital al 2030"),
        P("transporte", "Retirar del distrito a las empresas de transporte interprovincial y de carga, revocando sus licencias por incompatibilidad con la zonificación", 16, "Erradicar a las empresas de transportes interprovinciales", "Reducir la congestión en 50 % al 2030"),
        P("urbano", "Aplicativo «Aló Baches» para que los vecinos reporten baches y se reparen pistas y veredas", 16, "implementando el aplicativo digital", "70 % de las vías críticas rehabilitadas al 2030"),
        P("ambiente", "Optimizar la limpieza pública y la recolección, promover el reciclaje con alianzas y actualizar las tasas según el costo real del servicio", 17, "45.8% valorización de residuos", "45,8 % de residuos valorizados al 2030"),
        P("ambiente", "Aumentar las áreas verdes con ONG, empresas e instituciones que siembren y mantengan árboles y espacios públicos", 17, "Incrementar las áreas verdes urbanas mediante alianzas estratégicas", "50 % más de áreas verdes al 2030"),
        P("gestion", "Mesa de partes digital, Licencia Express, Plataforma Vecino Digital y expediente electrónico municipal", 12, "Plataforma Vecino Digital", "100 % de trámites digitalizados"),
    ]),
    ("Walter Ciro Pérez Noreña", "Batalla Perú", "batalla-peru", [
        P("seguridad", "Seguridad ciudadana descentralizada por zonas de juntas vecinales, cada base con cámaras, central de monitoreo, unidades de auxilio y radios", 14, "43 Bases Descentralizadas de Seguridad Ciudadana", "43 bases descentralizadas de seguridad ciudadana"),
        P("seguridad", "Serenos asignados a una sola zona y patrullando en bicicleta, con evaluación conjunta de resultados con la PNP", 15, "evaluando cada 15 días conjuntamente con la Municipalidad", "Evaluación conjunta cada 15 días"),
        P("social", "Hospital o policlínico municipal con especialidades básicas a bajo costo, mediante tercerización de servicios", 18, "Construir un moderno Complejo Asistencial de Salud"),
        P("social", "Losas deportivas en cada sector y escuela municipal de deportes", 19, "Creación de la escuela municipal de deportes masivos"),
        P("urbano", "Actualizar el catastro distrital y formular un Plan Maestro de Desarrollo Integral con colegios profesionales y universidades", 19, "actualización del Catastro Distrital dentro de los primeros 180 días", "Catastro actualizado en los primeros 180 días"),
        P("transporte", "Plan Maestro Vial, sincronización de semáforos con Lima Metropolitana, señalización y reparación de baches y veredas", 20, "Iniciar un Plan Maestro Vial"),
        P("urbano", "Complejo deportivo de integración vecinal y construcción y equipamiento de la Casa de la Juventud", 20, "Construcción y equipamiento de la Casa de la Juventud"),
        P("ambiente", "Tercerizar el recojo de basura con exigencias a los proveedores y crear una empresa municipal de reciclaje fuera del distrito", 20, "Empresa Municipal de reciclaje"),
        P("economia", "Escuela municipal de gestión empresarial, incentivos tributarios a la inversión y canje de deuda por obras pequeñas", 21, "Escuela municipal de gestión empresarial"),
        P("economia", "Exigir que las empresas contraten un porcentaje de trabajadores del distrito", 21, "contratar en un porcentaje a trabajadores del distrito"),
        P("gestion", "Estructura orgánica plana con dos instancias para resolver expedientes y planilla municipal reducida", 22, "por cada 1,000 habitantes", "Menos de 3 servidores por cada 1 000 habitantes"),
    ]),
    ("Martín Jorge Luis Guevara Martínez", "Fuerza Popular", "fuerza-popular", [
        P("seguridad", "Modelo integral de seguridad con plan cuadrante, subestaciones de control y monitoreo, recuperación de espacios públicos y formación de líderes vecinales", 7, "Sub Estaciones de Control y Monitoreo", "Reducir en 20 % al año la violencia y la delincuencia"),
        P("social", "Academia preuniversitaria municipal gratuita y plan de becas para jóvenes de escasos recursos", 9, "Implementar una academia preuniversitaria municipal y plan de Becas", "10 % más al año de jóvenes de escasos recursos con acceso a la educación superior"),
        P("social", "Centros médicos itinerantes de atención primaria y una central médica telefónica conectada a la red de salud del distrito", 12, "implementando centros médicos itinerantes"),
        P("transporte", "Programa «Bacheo tu calle»: rehabilitación del asfalto, semaforización digital, señalización y accesibilidad para personas con discapacidad", 10, "rehabilitación de la carpeta asfáltica del pavimento"),
        P("transporte", "Ordenar el uso de la vía pública por las empresas de transporte interprovincial y construir estacionamientos subterráneos", 10, "plan de estacionamientos subterráneos en diversos puntos"),
        P("agua_riesgos", "Muros de contención en las zonas peatonales de los cerros San Cosme y El Pino", 11, "prevenir los accidentes en las zonas peatonales del Cerro San Cosme"),
        P("economia", "Plan de competitividad para Gamarra con el Gobierno Central y los gremios, capacitación a mypes y ferias nacionales e internacionales", 13, "plan de desarrollo integral para mejorar los niveles de competitividad"),
        P("economia", "Beneficios tributarios y simplificación administrativa para formalizar negocios, y reordenamiento del comercio ambulatorio", 14, "Reducir 50% a informalidad", "Reducir en 50 % la informalidad"),
        P("ambiente", "Rutas de recolección según cada zona y contenedores de gran volumen en los puntos de mayor generación de residuos", 15, "contenedores de gran volumen superficiales", "100 % de cobertura del recojo de residuos"),
        P("ambiente", "Recuperación de áreas verdes con empresas, colegios e iglesias, y riego tecnificado por aspersión en los parques", 15, "riego tecnificado por aspersión"),
        P("gestion", "Pedir a la Contraloría que acompañe las principales compras y contrataciones, y canales seguros para denunciar corrupción", 16, "acompañen los procesos de adquisiciones y contrataciones"),
    ]),
    (None, "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Videovigilancia inteligente centralizada las 24 horas y aplicativo con botón de pánico conectado al centro de monitoreo", 1, "aplicativo móvil que incorpore un botón de pánico"),
        P("urbano", "Renovación masiva del alumbrado público con luminarias LED en avenidas y parques", 1, "Renovación masiva del alumbrado público"),
        P("economia", "Primer empleo para jóvenes del distrito mediante convenios con Gamarra y capital semilla para mypes con COFIDE", 1, "inserción laboral formal de jóvenes residentes"),
        P("transporte", "Priorizar una salida vehicular continua desde la Av. Isabel la Católica hacia el emporio de Gamarra", 4, "salida vehicular continua y fluida"),
        P("gestion", "Trámites en línea con horario extendido, aplicativo municipal de autogestión y WiFi gratuito en plazas y parques", 2, "redes de WiFi gratuito y seguro"),
        P("social", "Escuelas deportivas gratuitas, talleres de música, danza y producción audiovisual, y convenio con Alianza Lima para escolares", 2, "Escuelas municipales deportivas multidisciplinarias"),
        P("ambiente", "Recojo de basura de 8 a.m. a 10 p.m. y gestión de un relleno sanitario con planta de valorización energética de residuos", 3, "planta de valorización energética de residuos"),
        P("agua_riesgos", "Escaleras y muros de contención en las laderas de los cerros El Pino y San Cosme", 3, "Construcción de escaleras y muros de contención"),
        P("gestion", "Transmisión en tiempo real de las licitaciones y plataforma pública de seguimiento físico y financiero de las obras", 3, "Transmisión pública y en tiempo real"),
        P("social", "Construir la Casa del Adulto Mayor e implementar un velatorio municipal", 4, "Casa del Adulto Mayor"),
        P("economia", "Rebajar las tasas de arbitrios y las multas administrativas vigentes", 4, "Reducción del 25% en las tasas de arbitrios", "25 % menos en arbitrios y 50 % menos en multas"),
    ]),
    ("Alberto Fernando Moreno Mejía", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Dividir el distrito en bases operativas de seguridad (San Cosme, El Pino, El Porvenir, Gamarra, Santa Catalina y La Victoria Antigua) con monitoreo, cámaras y personal", 8, "dividiendo el distrito en 6 bases operativas", "6 bases operativas"),
        P("seguridad", "Reactivar y modernizar los Centros de Asistencia Rápida e integrarlos al sistema central de monitoreo", 8, "Reactivar y modernizar los 18 Centros de Asistencia", "18 Centros de Asistencia Rápida"),
        P("ambiente", "Contenedores soterrados en sectores densos, flota municipal propia de limpieza y atención de limpieza por teléfono las 24 horas", 9, "Instalación de contenedores soterrados para residuos sólidos"),
        P("social", "Escuela Municipal del Deporte con un complejo deportivo municipal y campeonatos vecinales y escolares", 10, "Se creará la Escuela Municipal del Deporte"),
        P("social", "Hospital o policlínico municipal con especialidades básicas, mediante tercerización del personal y el equipamiento", 11, "construir un moderno Complejo Asistencial de Salud"),
        P("social", "Casa de la Mujer y el Adulto Mayor con atención psicológica, social y jurídica a víctimas de violencia y actividades para adultos mayores", 12, "LA CASA DE LA MUJER Y EL ADULTO MAYOR"),
        P("economia", "Formalizar al comercio informal con capacitación y complejos comerciales construidos con la empresa privada y los comerciantes", 13, "Trato especial al comercio informal para capacitarlos"),
        P("transporte", "Priorizar obras viales peatonales y vehiculares, semaforización y señalización", 14, "Ejecutar con prioridad obras de infraestructura vial"),
        P("agua_riesgos", "Coordinar con entidades públicas y privadas la ampliación de los servicios de agua y desagüe", 14, "cobertura total al 100% de los servicios de agua y desagüe", "Cobertura total de agua y desagüe (100 %)"),
        P("urbano", "Programa «La Victoria Moderna» de mantenimiento y mejora de fachadas precarias, con las juntas vecinales", 15, "programa integral de mantenimiento y mejoramiento de fachadas"),
        P("gestion", "Municipalidad con trámites virtuales y sistema digital de quejas y sugerencias sobre los servicios municipales", 15, "Implementar una Municipalidad con tramites al 100% virtual", "100 % de trámites virtuales"),
    ]),
    ("María Teresa Rosas García", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Patrullaje integrado con la PNP, ampliación de la videovigilancia inteligente y articulación de las juntas vecinales", 1, "la ampliación de la red de videovigilancia inteligente"),
        P("urbano", "Ordenamiento territorial y titulación en las laderas de los cerros San Cosme y El Pino, con estudios de mitigación de riesgos", 1, "Entregar 5,000 títulos de propiedad en laderas", "5 000 títulos de propiedad en laderas"),
        P("social", "Atención primaria con el MINSA contra la tuberculosis y la desnutrición infantil, con campañas de nutrición y tamizaje", 2, "erradicar focos epidemiológicos de Tuberculosis"),
        P("economia", "Formalizar a ambulantes con incentivos tributarios, capacitación empresarial y uso de galerías comerciales subutilizadas", 2, "aprovechamiento de galerías comerciales subutilizadas", "Capacitación para 1 200 mypes al año"),
        P("seguridad", "Operativos conjuntos con Fiscalía y Policía contra la extorsión, el cobro de cupos y la lotización de calles en Gamarra y el Mercado de Frutas", 2, "Ejecutar 150 macro operativos al año", "150 macro operativos al año"),
        P("transporte", "Captar inversión privada (APP u obras por impuestos) para rediseñar la logística vehicular y los paraderos formales del Mercado de Frutas", 3, "rediseñar la logística vehicular y paraderos formales", "Cartera de proyectos de S/ 50 millones"),
        P("ambiente", "Recolección selectiva, control de horarios de la basura comercial y erradicación de los botaderos informales", 3, "erradicar de manera definitiva los botaderos informales"),
        P("ambiente", "Arborización urbana masiva y recuperación de plazas y parques deteriorados", 4, "Ejecutar proyectos de arborización urbana masiva"),
        P("ambiente", "Plantas de valorización que conviertan residuos orgánicos y follaje en abono para el mantenimiento municipal", 4, "plantas de valorización para convertir residuos orgánicos", "Ahorro de S/ 10 000 mensuales en mantenimiento"),
        P("gestion", "Gobierno abierto digital, simplificación administrativa y canal de denuncia anónima en licencias y fiscalización", 4, "herramientas digitales de gobierno abierto"),
        P("gestion", "Ejecutar el presupuesto de inversiones en obras para no devolver recursos al Tesoro Público", 5, "ejecución presupuestal superior al 85% anual", "Ejecución presupuestal mayor al 85 % anual"),
    ]),
    ("Florencio Froilán Fierro Flores", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Central de Operaciones de Videovigilancia con reconocimiento facial y lectura de placas en los accesos al distrito", 39, "Central de Operaciones de Videovigilancia (COV)"),
        P("seguridad", "«Serenazgo Sin Fronteras» con San Luis, Lince y el Cercado, y cámaras corporales obligatorias para los fiscalizadores", 40, "la ejecución del programa Serenazgo Sin Fronteras"),
        P("economia", "Licencia provisional digital para negocios de riesgo bajo y medio con aprobación automática y fiscalización posterior", 44, "Licencia Provisional Digital", "Licencia en un plazo máximo de 24 horas"),
        P("economia", "Plan «Gamarra 4.0»: centros logísticos verticales mediante APP para sacar el almacenamiento de viviendas precarias", 45, "Centros Logísticos Verticales Inteligentes", "Reducir 20 % el costo logístico de la mype"),
        P("social", "Policlínico móvil «Salud en Tu Barrio» para barrios periféricos y laderas, y veterinaria municipal con esterilizaciones", 50, "El pilar operativo de nuestra red será el Policlínico Móvil"),
        P("social", "Red de cunas municipales «Emprende Madre» cerca de Gamarra y el Mercado de Frutas para hijos de trabajadoras", 51, "Implementaremos la red de Cunas Municipales"),
        P("ambiente", "Recolección de residuos solo en horario nocturno, con rutas recalculadas por software", 53, "Sistema de Recolección Nocturna", "100 % de la recolección entre las 22:00 y las 05:00"),
        P("ambiente", "Contenedores soterrados en las avenidas Aviación, Huánuco, 28 de Julio y México", 53, "Contenerización Estratégica Soterrada"),
        P("urbano", "Escalinatas de concreto e iluminación LED en las laderas de San Cosme y El Pino, y ordenamiento del cableado aéreo", 55, "escalinatas de concreto armado de alta resistencia", "Iluminación LED en el 100 % de las vías de acceso a las laderas"),
        P("transporte", "«Ola Verde» semafórica con Protránsito en las avenidas México, Bausate y Meza y 28 de Julio", 56, "Ola Verde Semafórica e Inteligencia de Tráfico", "Reducir 30 % el tiempo de tránsito"),
        P("gestion", "Portal de datos abiertos «La Victoria Transparente» con el avance del pago de la deuda histórica y auditores ciudadanos", 58, "Portal de Datos Abiertos"),
    ]),
    ("Aldo Horacio Rosales Pacheco", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Programa «Victoria Segura 24/7»: más serenazgo, patrullaje integrado con la PNP, cámaras, centro de monitoreo y botón de pánico", 7, "Programa Victoria Segura 24/7", "200 cámaras inteligentes y reducir la delincuencia en 30 %"),
        P("urbano", "Recuperar parques y espacios públicos con losas deportivas, iluminación LED, gimnasios al aire libre y juegos infantiles", 8, "Recuperación de 50 parques y espacios públicos", "50 espacios públicos recuperados"),
        P("economia", "Centro Municipal de Desarrollo Empresarial con asesoría legal y tributaria gratuita, formalización y Escuela del Emprendedor", 8, "Centro Municipal de Desarrollo Empresarial", "10 000 negocios formalizados y 20 000 emprendedores capacitados"),
        P("ambiente", "Programa «La Victoria Limpia» para eliminar microbasurales, nuevas rutas de recolección y reciclaje", 9, "Programa La Victoria Limpia"),
        P("social", "Clínicas municipales con medicina general, pediatría, psicología y nutrición, y programas contra la anemia y la tuberculosis", 10, "Clínicas Municipales de La Victoria"),
        P("social", "Programa «Victoria Joven Trabaja» de capacitación para el empleo y bolsa de trabajo municipal", 11, "Programa Victoria Joven Trabaja", "10 000 jóvenes capacitados para el empleo"),
        P("social", "Programa «Mujer Emprende y Progresa» de capacitación para madres solteras y mujeres vulnerables", 11, "Programa Mujer Emprende y Progresa", "8 000 madres solteras y mujeres vulnerables capacitadas"),
        P("gestion", "Programa «43 Zonas, 43 Soluciones»: comité vecinal, responsable municipal y plan de mejoras en cada zona", 13, "Programa 43 Zonas, 43 Soluciones", "43 comités vecinales"),
        P("gestion", "Gobierno digital con trámites virtuales, aplicación municipal y transparencia digital", 14, "EJE 9: MUNICIPALIDAD MODERNA Y SERVICIO DE CALIDAD", "80 % de los trámites digitalizados"),
        P("transporte", "Reordenamiento vial, gestión inteligente del tránsito y reforma del sistema de grúas con auditoría y tarifas transparentes", 15, "Reforma Integral del Sistema de Grúas"),
        P("ambiente", "Clínica veterinaria y refugio municipal de mascotas con campañas de vacunación, esterilización y adopción", 16, "Refugio Municipal de Mascotas", "15 000 esterilizaciones"),
    ]),
    ("César Rafael Ibarra Nureña", "PPC", "partido-popular-cristiano-ppc", [
        P("social", "Reactivar los parques biblioteca de San Cosme y El Porvenir y crear un tercero en La Victoria Antigua", 4, "Creacion del tercer Parque Biblioteca de La Victoria"),
        P("social", "Polideportivos multipropósito en Cerro El Pino, Balconcillo y Santa Catalina, según disponibilidad de predios y presupuesto", 4, "polideportivos multiproposito en Cerro El Pino"),
        P("seguridad", "Gestionar ante el Mininter y la PNP una comisaría sectorial para Santa Catalina y zonas vinculadas", 4, "Comisaria Sectorial para Santa Catalina"),
        P("seguridad", "Videovigilancia «Cúpula de Hierro Victoriana» en accesos al distrito, con lectura de placas y cámaras en paneles publicitarios", 5, "Cupula de Hierro Victoriana"),
        P("economia", "Empadronamiento georreferenciado de ambulantes y reubicación en pisos altos de Gamarra mediante convenios con galerías", 6, "Empadronamiento real, verificable y georreferenciado"),
        P("transporte", "Ventanas horarias para carga pesada fuera de horas punta y fotopapeletas con cámaras lectoras de placas", 7, "Plan de Gestion Inteligente del Transporte de Carga"),
        P("economia", "Nuevos polos económicos complementarios a Gamarra, incluida una «Zona 2» de comercio, servicios y emprendimiento", 8, "Consolidar al menos dos nuevos polos", "Al menos 2 nuevos polos económicos al 2030"),
        P("urbano", "Plan «Veredas Seguras» y recuperación de La Victoria Antigua con obras por impuestos", 8, "Plan Veredas Seguras"),
        P("ambiente", "Más arbolado urbano y riego tecnificado para reducir el uso de camiones cisterna", 9, "Reducir la dependencia exclusiva de camiones cisterna"),
        P("ambiente", "Contenedores soterrados en puntos críticos y plan de recojo de basura en Cerro El Pino y San Cosme", 9, "contenedores soterrados en zonas criticas"),
        P("gestion", "Portal «La Victoria Cumple» con seguimiento del plan y Defensoría del Vecino Victoriano", 10, "Crear el portal La Victoria Cumple", "Balances semestrales del plan"),
    ]),
    ("Mesías Máximo Gonzales Sánchez", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Más patrullaje a pie y en motocicleta por sectores y capacitación de serenos con instructores especializados", 7, "incrementar el patrullaje a pie y en motocicletas"),
        P("seguridad", "Repotenciar la central de monitoreo y aumentar las cámaras de video en todos los sectores", 7, "repotenciar la central de monitoreo de cámaras"),
        P("transporte", "Gestionar con Lima Metropolitana, el presupuesto participativo y el Gobierno central la renovación de pistas principales", 7, "renovación de pistas en las vías principales"),
        P("transporte", "Operativos con la policía de tránsito contra la congestión y fiscalización de mototaxis informales", 8, "utilizando moto taxis informales"),
        P("economia", "Programas de formalización de ambulantes con ferias gastronómicas y artesanales y reubicación", 9, "programas de formalización para los vendedores informales"),
        P("economia", "Crear una caja municipal de ahorro y crédito para las mypes", 10, "Implementación de una caja municipal de ahorro y crédito"),
        P("economia", "Promover una marca colectiva o de certificación de Gamarra con las entidades y gremios", 10, "marca colectiva de Gamarra"),
        P("economia", "Revisar el régimen de sanciones para priorizar el orden sobre la recaudación y evaluar descuentos en multas", 11, "Promover la revisión del RAS"),
        P("social", "Repotenciar los programas de apoyo al adulto mayor y a la niñez y crear zonas de recreación familiar", 8, "repotenciara los programas de apoyo al adulto mayor"),
        P("ambiente", "Zonas de acopio con contenedores, fomento del reciclaje y fiscalización a infractores ambientales", 11, "implementar zonas de acopio con contenedores"),
        P("gestion", "Auditar la deuda municipal heredada y reducirla con acciones legales y pagos parciales", 13, "Auditoria a efectos de determinar el monto real de la deuda"),
    ]),
    ("Susana Liliana Saldaña Ramos", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Adquirir nuevas cámaras, construir la Central de Monitoreo y Videovigilancia y casetas de auxilio rápido, priorizando Santa Catalina", 10, "Culminar la implementación del proceso de adquisición de 100 nuevas cámaras", "60 % más de capacidad de videovigilancia al 2030"),
        P("seguridad", "Gestionar camionetas y motos para el patrullaje integrado con la PNP y fortalecer las juntas vecinales", 10, "adquisición de 20 camionetas y 50 motos", "20 camionetas y 50 motos; reducir 50 % la percepción de inseguridad"),
        P("social", "Centro de Noche para adultos mayores, mujeres y niños que duermen en la calle", 11, "Implementar un Centro de Noche para adultos mayores", "1 Centro de Noche operativo"),
        P("social", "Clínica deportiva para deportistas de alto rendimiento del distrito, con nutrición, fisioterapia y apoyo psicológico", 16, "Implementar una clínica deportiva", "Clínica deportiva funcionando al 2030"),
        P("economia", "Campañas «Licencias al Toque» e «ITSE en tus manos» y simplificación de trámites de formalización", 24, "LICENCIAS AL TOKE e ITSE EN TUS MANOS", "20 % más de formalización en los corredores económicos al 2030"),
        P("urbano", "Mejorar los Dameros A, B y C de Gamarra, el Boulevard El Misti, el Mirador de San Cosme y conectores peatonales con la Línea 1", 24, "mejoramiento del Damero A y Damero B de Gamarra", "Dameros A, B y C mejorados al 2030"),
        P("urbano", "Gestionar el recapeo de las vías internas y completar la iluminación LED de las calles", 25, "Gestionar el recapeo de todas las vías internas", "50 % de las vías internas recapeadas"),
        P("economia", "Programa «Plan Chamba» de inserción laboral e incubadora municipal de emprendimientos", 26, "Implementar el Programa Plan Chamba", "Inserción laboral de hasta 70 000 victorianos y 24 proyectos de incubación"),
        P("agua_riesgos", "Muros de contención en San Cosme y El Pino y limpieza del canal de Huatica para el riego de parques", 29, "muros de contención en las zonas vulnerables", "50 % de los muros priorizados y canal de Huatica al 100 %"),
        P("ambiente", "Ejecutar los expedientes pendientes de recuperación de parques hasta completar los parques priorizados", 29, "21 expedientes técnicos de recuperación de parques", "100 % de los 75 parques priorizados al 2030"),
        P("gestion", "Aplicativo móvil para trámites y reportes ciudadanos, y monitoreo por GPS de la recolección y el serenazgo", 34, "Desarrollar un aplicativo móvil institucional", "Procedimientos del TUPA digitalizados al 2030"),
    ]),
]
