"""Jesús María (150113): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150113"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Jorge Luis Quintana García Godos", "Acción Popular", "accion-popular", [
        P("social", "Programa «Jesús María Te Cuida» para adultos mayores: red de cuidado, centros de día y visitas domiciliarias preventivas", 50, "5,000 adultos mayores incorporados a programas municipales", "5 000 adultos mayores en programas, 10 000 visitas domiciliarias y 2 centros de día al 2030"),
        P("seguridad", "Plan de seguridad inteligente con más videovigilancia, recuperación de puntos críticos y patrullaje preventivo", 50, "Reducir en 30% el tiempo de respuesta del serenazgo", "Duplicar la videovigilancia, recuperar 30 puntos críticos y 30 % menos tiempo de respuesta"),
        P("social", "Programa «Jesús María Saludable» con campañas de despistaje y promotores comunitarios de salud", 50, "40,000 atenciones preventivas realizadas", "200 campañas y 40 000 atenciones preventivas acumuladas al 2030"),
        P("social", "Programa de oportunidades para jóvenes con centro de innovación, becas y escuelas deportivas y culturales", 51, "8,000 jóvenes beneficiados; 500 becas", "8 000 jóvenes, 500 becas y 20 escuelas deportivas y culturales al 2030"),
        P("economia", "Centro Municipal de Desarrollo Empresarial con asesorías y transformación digital de las mypes", 52, "3,000 empresas capacitadas", "3 000 empresas capacitadas y 1 500 negocios digitalizados al 2030"),
        P("economia", "Fortalecer corredores comerciales y simplificar los trámites para empresas", 52, "reducción de 50% en tiempos de trámites empresariales", "50 % menos tiempo en trámites empresariales"),
        P("transporte", "Mejorar la accesibilidad de los corredores comerciales e implementar un sistema inteligente de estacionamientos", 53, "implementar sistema inteligente de estacionamientos"),
        P("ambiente", "Programa de infraestructura verde: recuperar áreas verdes, arborizar e intervenir todos los parques", 53, "plantar 5,000 árboles", "50 000 m² de áreas verdes recuperadas y 5 000 árboles al 2030"),
        P("agua_riesgos", "Riego tecnificado en parques y miniplantas que traten aguas residuales para regar", 54, "3 miniplantas de tratamiento de agua para riego urbano", "100 % de parques con riego eficiente, 30 % menos agua de riego y 3 miniplantas"),
        P("ambiente", "Programa de reciclaje y valorización de residuos con participación de hogares y recicladores formalizados", 54, "incorporar 10,000 hogares al programa", "50 % más segregación y 10 000 hogares en el programa"),
        P("gestion", "Gobierno digital y rendición de cuentas con publicación trimestral de indicadores de gestión", 56, "Digitalizar 80% de trámites municipales", "80 % de trámites digitales y 2 rendiciones de cuentas al año"),
    ]),
    ("Raphael Christian Valencia Diestra", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Duplicar el equipamiento de seguridad con camionetas, motos y cámaras con inteligencia artificial, y más serenos", 13, "Incrementaremos el doble del equipamiento de seguridad ciudadana", "Duplicar el equipamiento de seguridad ciudadana"),
        P("seguridad", "Segunda central de seguridad y videovigilancia, y mapa del delito en tiempo real con datos de PNP, serenazgo y vecinos", 13, "Implementaremos una segunda Central de Seguridad Integral"),
        P("seguridad", "Aplicación «Alerta Mujer Jesús María» conectada al serenazgo para reportar riesgos y pedir ayuda inmediata", 21, "Alerta Mujer Jesús María"),
        P("social", "Academia municipal con servicios educativos técnicos y preuniversitarios", 16, "Implementar la academia municipal"),
        P("social", "Gestionar la conclusión del nuevo Centro de Salud de la cuadra 17 de Arnaldo Márquez, con 27 consultorios y emergencia", 20, "27 consultorios, áreas de emergencia y diagnóstico"),
        P("economia", "Licencias de funcionamiento rápidas y programa «Yo me formalizo» con campañas de formalización y luego fiscalización", 35, "Emisión de licencias de funcionamiento en menos de 30 minutos", "Licencias en menos de 30 minutos"),
        P("urbano", "Mejorar pistas, veredas e iluminación del distrito", 23, "Se realizarán las mejoras de las pistas, veredas e iluminación"),
        P("ambiente", "Instalar contenedores soterrados y semisoterrados inteligentes", 36, "10 contenedores soterrados y 10 semisoterrados inteligentes", "10 soterrados y 10 semisoterrados"),
        P("ambiente", "Ampliar la arborización urbana", 36, "1000 árboles sembrados", "1 000 árboles sembrados"),
        P("agua_riesgos", "Riego tecnificado por aspersión con sensores de humedad en lugar de cisternas", 36, "Implementar el riego tecnificado por aspersión y sensores de humedad"),
        P("gestion", "Sistema integrado de trámites municipales y audiencias vecinales en cada zona del distrito", 37, "Implementar audiencias vecinales en cada zona del distrito"),
    ]),
    ("Renato Aldo Rossini Valenzuela", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Fortalecer el patrullaje integrado, instalar cámaras y articular con el CODISEC", 11, "Fortalecimiento del patrullaje integrado, instalación de cámaras"),
        P("seguridad", "Nuevas estaciones de serenazgo y más cámaras de videovigilancia con mejor red de fibra óptica", 12, "Número del Incremento de estaciones de serenazgo", "5 estaciones de serenazgo más y 50 cámaras por año"),
        P("agua_riesgos", "Brigadas vecinales de gestión de riesgos entrenadas y equipadas, almacenes por zona y equipo de búsqueda y rescate", 13, "01 brigada por zona 01 almacén GRD por zona", "1 brigada y 1 almacén por zona, y 1 equipo de rescate certificado por INDECI"),
        P("social", "Nuevos programas de actividades saludables, deportivas y artísticas para adultos mayores", 12, "Implementación de nuevos programas que promuevan actividades saludables para el adulto mayor"),
        P("gestion", "Organizar y reconocer comités vecinales con talleres de capacitación", 13, "organizar y reconocer comités vecinales", "3 comités vecinales y 1 taller trimestral por zona"),
        P("economia", "Programa de apoyo a emprendedores y ferias artesanales", 14, "Programa de apoyo a emprendedores vecinales", "6 ferias al año"),
        P("transporte", "Más estacionamiento vehicular y mejor mantenimiento y señalización de vías en zonas comerciales", 14, "Incrementar áreas de estacionamiento vehicular, mantenimiento y señalización de vías", "10 zonas priorizadas"),
        P("urbano", "Actualizar el Plan de Desarrollo Urbano con participación vecinal y coordinación con Lima Metropolitana", 15, "Actualizar Plan de Desarrollo Urbano"),
        P("ambiente", "Más especies forestales en áreas verdes, riego tecnificado y programa de techos verdes", 15, "Incrementar las especies forestales en las áreas verdes", "15 % más de especies forestales"),
        P("ambiente", "Programa de puesta en valor del Campo de Marte", 16, "Puesta en valor del Campo de Marte"),
        P("gestion", "Plataformas digitales para trámites en línea y transparencia en adquisiciones", 16, "Implementación de plataformas digitales para trámites en línea"),
    ]),
    ("Luis Enrique Ocrospoma Pella", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Brigada aérea de drones con videovigilancia y georreferenciación", 23, "Implementación de la Brigada aérea"),
        P("seguridad", "Identificación facial y vehicular con inteligencia artificial y cámaras corporales para serenos", 23, "Identificación facial y vehicular con IA"),
        P("social", "Construir un policlínico municipal e implementar el bus médico y la atención a domicilio", 21, "Construcción de policlínico municipal"),
        P("social", "Implementar un Centro de Emergencia Mujer con asesoría y atención psicológica", 21, "Implementación del Centro de Emergencia Mujer"),
        P("agua_riesgos", "Control preventivo de casonas, quintas y casas antiguas, refugios temporales y brigadistas por edificio", 23, "Control preventivo especial para casonas, quintas y casas antiguas"),
        P("economia", "Programa de formalización, registro y ordenamiento del comercio informal en la vía pública", 25, "Programa de formalización, registro y ordenamiento de los comerciantes informales", "100 % de comerciantes ambulantes formalizados"),
        P("economia", "Corredor gastronómico y turístico en la Av. Cuba y otras zonas", 25, "Implementación del corredor gastronómico y turístico en la Av. Cuba"),
        P("urbano", "Construir el Boulevard de la Alameda de la Av. Salaverry y rehabilitar pistas y veredas", 26, "Construcción del Boulevard de la Alameda de la Av. Salaverry"),
        P("ambiente", "Planta de tratamiento de aguas residuales para regar parques y jardines", 26, "Planta de tratamiento de aguas residuales - PTAR para regadío"),
        P("transporte", "Semáforos con inteligencia artificial, ampliación de ciclovías y estacionamientos subterráneos", 26, "Instalación de sistema semafóricos en el distrito aplicando inteligencia artificial"),
        P("gestion", "Gobierno abierto con sistema antisoborno y anticorrupción, y proyecto de ciudad inteligente", 27, "sistema de gobierno abierto e integridad corporativo"),
    ]),
    ("Roberto Antonio Aymar Silva", "Fuerza Popular", "fuerza-popular", [
        P("social", "Programa «Salud Bucal Escolar Solidaria» con clínicas odontológicas móviles en colegios públicos", 3, "Salud Bucal Escolar Solidaria"),
        P("social", "Red de respuesta médica rápida con motos y ambulancias para adultos mayores y gestantes", 4, "Red de Respuesta Médica Rápida Vecinal", "Respuesta a domicilio en menos de 5 minutos"),
        P("urbano", "«Plan Veredas Seguras»: nivelar veredas, construir rampas e instalar pavimento podotáctil", 4, "Plan Veredas Seguras"),
        P("economia", "Incubadora municipal de startups con fondo concursable de capital semilla para jóvenes", 5, "Incubadora Municipal de Empresas de Base Tecnológica"),
        P("economia", "Red de centros de coworking municipales gratuitos con fibra óptica", 5, "Co-working Municipal Gratuito"),
        P("ambiente", "Hospital veterinario municipal con atención las 24 horas y tarifas sociales", 6, "Hospital Veterinario Municipal de Alta Complejidad"),
        P("transporte", "Ciclovías iluminadas y segregadas en las avenidas Salaverry, San Felipe, Cuba y de la Peruanidad", 7, "Red de Ciclovías Iluminadas"),
        P("ambiente", "Renovar la flota municipal con vehículos y motos eléctricas", 8, "libres de combustión fósil"),
        P("seguridad", "Pórticos con cámaras de lectura de placas y reconocimiento facial en los accesos del distrito", 8, "Pórticos de Control Fronterizo Inteligente"),
        P("seguridad", "Patrullaje con drones en zonas de mayor incidencia delictiva, conectados a la central C4", 9, "Patrullaje Táctico con Drones"),
        P("gestion", "Tablero público en Power BI para seguir finanzas, obras y servicios municipales", 10, "Tablero de Control Ciudadano en Power BI"),
    ]),
    ("María Luisa Lanatta Pino", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("seguridad", "Optimizar la videovigilancia del CECOM y la tecnología de seguridad en coordinación con la PNP", 4, "Optimización del sistema de video vigilancia"),
        P("seguridad", "Comité Antidroga Distrital para prevenir el consumo de drogas en jóvenes", 4, "Formación del Comité Antidroga Distrital"),
        P("social", "Escuelas abiertas de deporte para formar deportistas en disciplinas olímpicas", 4, "Fomentar la práctica como mínimo de 6 disciplinas", "Al menos 6 disciplinas olímpicas"),
        P("urbano", "Fiscalizar las nuevas edificaciones para que respeten la zonificación y el número de pisos permitidos", 4, "respetando las zonificaciones y número de pisos permitidos"),
        P("agua_riesgos", "Brigadistas por edificio, mapa de riesgos actualizado y almacén de ayuda humanitaria", 5, "Conformación de brigadistas por edificios"),
        P("urbano", "Rehabilitar pistas y veredas, continuar los pasajes y remodelar el Campo de Marte", 5, "Rehabilitación total de pistas y veredas"),
        P("ambiente", "Más contenedores soterrados, arborización y riego por aspersión", 6, "Incrementar la utilización de los Contenedores Soterrados"),
        P("economia", "Centro empresarial municipal que apoye la constitución y formalización de negocios", 6, "Implementación un Centro Empresarial de apoyo"),
        P("social", "Programa de médico y ambulancia a domicilio, y DEMUNA descentralizada", 7, "Programa Medico y Ambulancia a Domicilio"),
        P("social", "Consultorios psicológicos gratuitos y descentralizados frente a la violencia contra mujeres, niños y jóvenes", 8, "Crear los Consultorios Psicológicos descentralizados y gratuitos"),
        P("gestion", "Mejorar el municipio digital para trámites, consultas, reclamos y pagos en línea", 10, "Mejorar el verdadero funcionamiento el municipio digital"),
    ]),
    ("José Luis Herrera Urueta", "Partido Cívico Obras", "partido-civico-obras", [
        P("transporte", "Regular el transporte, modernizar el parque automotor y usar semaforización inteligente", 9, "uso de semaforización inteligente"),
        P("seguridad", "Prevención con cámaras y participación vecinal, en coordinación con la Policía Nacional", 10, "Fortalecimiento de la seguridad ciudadana con prevención"),
        P("seguridad", "Juntas vecinales, planes de seguridad y prevención vial", 14, "implementando juntas vecinales, planes de seguridad y prevención vial"),
        P("social", "Impulsar la creación de un policlínico municipal", 12, "Impulsar la creación de un policlínico municipal"),
        P("social", "Centros de cuidado infantil", 11, "Implementar centros de cuidado infantil"),
        P("social", "Apoyo a mujeres víctimas de violencia o discriminación, con centros de atención y asesoría legal", 11, "Brindar apoyo a mujeres víctimas de violencia"),
        P("social", "Sistema municipal del deporte con mejor infraestructura y uso de espacios públicos", 12, "Crear un sistema municipal del deporte"),
        P("economia", "Escuelas de oficio para desarrollar capacidades laborales y emprendimiento", 11, "emprendimiento (escuelas de oficio)"),
        P("economia", "Microcréditos con asistencia técnica para familias de bajos recursos", 12, "microcréditos para familias de bajos recursos"),
        P("ambiente", "Consejo Municipal Ambiental con educación ambiental, reciclaje y protección animal", 14, "se fortalecerá la protección animal y campañas de salud"),
        P("gestion", "Modernizar el catastro, los trámites y los sistemas de información municipal", 16, "Modernizar sistemas como el catastro"),
    ]),
    ("Luiz Carlos Reátegui del Águila", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Programa «Jesús María 360°»: cámaras con reconocimiento facial y de placas, drones, policía municipal y un sereno por manzana", 1, "Un efectivo de serenazgo por manzana", "Reducir delitos en 90 % y respuesta en menos de 4 minutos"),
        P("social", "Centro de salud vecinal y seguro municipal para el adulto mayor, con farmacia social y atención domiciliaria", 1, "Promover un seguro municipal para el adulto mayor", "12 000 adultos mayores afiliados y 35 000 consultas anuales"),
        P("social", "Loncherita, comedor y panadería municipal contra la anemia y la mala alimentación", 2, "Loncherita Jesusmariana", "Anemia por debajo del 5 % y 1 000 raciones diarias"),
        P("urbano", "Programa «Cielos Libres» para ordenar los cables en la vía pública con las empresas de servicios", 2, "Implementar el programa Cielos Libres", "100 % de reordenamiento de la infraestructura aérea"),
        P("transporte", "Carriles reversibles en horas punta coordinados con Lima Metropolitana y red completa de ciclovías", 3, "carriles reversibles en horas punta", "100 % de ciclovías implementadas"),
        P("social", "Escuela técnica y centro preuniversitario municipal para jóvenes y adultos", 4, "Creación de la escuela técnica y el centro preuniversitario", "1 000 estudiantes por año y 400 ingresantes universitarios 2027–2030"),
        P("economia", "«Programa Emprendedor Jesusmariano» con arbitrio cero por 3 meses para nuevos negocios y fondo de emprendimiento", 4, "Arbitrio Cero por 3 meses para los nuevos negocios", "1 500 emprendimientos formalizados"),
        P("ambiente", "Plan de arborización con vivero municipal, jardines verticales y corredores ecológicos", 5, "Plan 3000 árboles 2027-2030", "3 000 árboles al 2030"),
        P("ambiente", "Economía circular con reciclaje inteligente, contenedores inteligentes y barredoras mecánicas", 5, "Reciclar 40% de residuos", "40 % de residuos reciclados y 35 % menos al relleno sanitario"),
        P("gestion", "Gobierno digital «cero papeles» y cabildos abiertos semanales con el alcalde y los gerentes", 6, "Realizar cabildos abiertos semanales", "52 cabildos al año"),
        P("gestion", "Auditar las gestiones anteriores en los primeros cien días y remitir los resultados a la Fiscalía", 6, "Ejecutar auditorias de las gestiones anteriores en los primeros cien días", "Auditar los últimos 16 años de gestión"),
    ]),
    ("María del Pilar Albarracín Valverde", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Gestionar una fiscalía móvil en el distrito para agilizar los procesos por delitos comunes", 7, "creación de una fiscalía móvil en el distrito"),
        P("seguridad", "Serenazgo con armas no letales y unidades móviles con cámaras, lectura de placas e identificación de huellas", 7, "UNIDADES MÓVILES INTELIGENTES"),
        P("transporte", "Semáforos sincronizados con «olas verdes» desde un sistema integrado de control", 8, "Sistematización e implementación de semáforos, olas verdes"),
        P("transporte", "Parquímetros gratuitos para vecinos en horarios determinados y estudio de estacionamiento subterráneo en la plaza San José", 8, "Impulsaremos el uso de parquímetros"),
        P("social", "Policlínico municipal con geriatría, pediatría y emergencia las 24 horas, en el local de la Casa de la Juventud", 9, "Gestionar la creación del Policlínico Municipal"),
        P("economia", "Primer empleo para jóvenes en la bolsa de trabajo municipal y beneficios tributarios a empresas que contraten vecinos", 10, "Asegurar el primer empleo a nuestros jóvenes"),
        P("economia", "Licencia de funcionamiento inmediata para negocios de bajo riesgo, con inspección posterior", 12, "dar la licencia de funcionamiento Inmediata en 24 horas", "Licencia en 24 horas"),
        P("ambiente", "Pedir la declaratoria de emergencia ambiental del Campo de Marte, ampliar su riego tecnificado y crear un observatorio ambiental", 13, "Declarar en Emergencia Ambiental el Campo de Marte"),
        P("urbano", "Límite de altura de 5 a 12 pisos según el ancho de la calle, y techos verdes y reúso de aguas grises en nuevos proyectos", 14, "entre 5 a 12 pisos según ancho de la calle"),
        P("ambiente", "Más contenedores subterráneos en el Damero comercial y otras zonas", 14, "Implementación de más contenedores de Subterráneos"),
        P("gestion", "Transmitir en vivo todas las sesiones de concejo y publicar un informe mensual del trabajo de cada regidor", 15, "Trasmisión en vivo de TODAS las sesiones de Concejo"),
    ]),
    ("Julissa Rocío Fernández Fernández", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Casetas de Auxilio Rápido por cuadrantes para descentralizar la respuesta ante emergencias", 4, "Reducir el tiempo de respuesta ante emergencias a menos de 3 minutos", "Respuesta en menos de 3 minutos y 100 % de casetas planificadas"),
        P("seguridad", "Central de seguridad con analítica predictiva por IA y red de monitoreo con condominios y comercios", 4, "integren a la red de monitoreo participativo", "40 % de condominios y comercios en la red al 2030"),
        P("transporte", "Sincronizar semáforos con Lima Metropolitana y crear un carril de desaceleración frente al Hospital Militar", 5, "implementar el carril de desaceleración del Hospital Militar", "100 % de semáforos de avenidas principales integrados al 2028"),
        P("transporte", "Reubicar las ciclovías críticas en avenidas peligrosas e instalar estaciones de micromovilidad", 5, "Completar la reubicación técnica del 100% de las ciclovías críticas", "100 % de ciclovías críticas reubicadas y 10 estaciones al 2029"),
        P("urbano", "Remodelar los pasajes tradicionales e implementar zonas bajo el modelo de Grandes Manzanas", 5, "Remodelar y recuperar el 100% de los pasajes tradicionales", "100 % de pasajes y 3 zonas de Grandes Manzanas al 2030"),
        P("social", "Red de atención preventiva médica y psicológica a costo social", 5, "Salud Preventiva Descentralizada y", "Más de 10 000 atenciones anuales al 2030"),
        P("social", "Academia Preuniversitaria Municipal para escolares de colegios públicos", 7, "lograr una tasa de ingreso superior al 45%", "Más de 500 jóvenes por ciclo y más de 45 % de ingreso al 2029"),
        P("economia", "Programa «Incuba Jesús María» de incubación y formalización exprés de emprendimientos", 7, "Lograr la incubación de más de 1,000 emprendimientos, formalizar más de 1500", "Más de 1 000 emprendimientos incubados y 1 500 negocios formalizados al 2030"),
        P("ambiente", "Recuperar áreas verdes abandonadas con un plan de manejo fitosanitario en las seis zonas", 6, "Recuperar el 100% de las áreas verdes y parques en estado de abandono", "100 % de áreas verdes abandonadas recuperadas al 2028"),
        P("gestion", "Digitalizar los trámites y servicios tributarios con una ventanilla única digital", 6, "Lograr la digitalización e interoperabilidad del 100% de los trámites", "100 % de trámites tributarios digitales al 2028"),
        P("gestion", "Financiar grandes obras viales y peatonales mediante Obras por Impuestos y publicar auditorías anuales", 6, "financiar al menos el 30% de las grandes obras", "30 % de las grandes obras por Obras por Impuestos al 2030"),
    ]),
    ("Ernesto Enrique Delhonte Cagna", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Cámaras con identificación de personas y placas sobre fibra óptica, y aplicativos de emergencia", 7, "instalación de fibra óptica con un sistema que permita la identificación de personas y placas"),
        P("seguridad", "Bicicletas y segways para el serenazgo", 16, "Aumento de vehículos menores", "50 bicicletas y 20 segways al año"),
        P("seguridad", "Programa «Colegio Seguro» con presencia de serenos en las instituciones educativas", 16, "Implementación y fortalecimiento del programa"),
        P("agua_riesgos", "Almacenes soterrados con alimentos, medicinas y grupos electrógenos, y brigadistas en las 9 zonas", 16, "Contar con almacenes soterrados"),
        P("gestion", "Audiencias vecinales en las nueve zonas, con atención directa del alcalde sin cita previa", 8, "Se realizarán audiencias vecinales en cada una de las nueve zonas"),
        P("social", "Programa de liderazgo para niños de 7 a 12 años y centros de preparación preuniversitaria", 9, "Programa de Liderazgo para niños y niñas de 7 a 12 años"),
        P("urbano", "Rampas y bandas podotáctiles en las calles del distrito", 9, "construcción de rampas en las diversas calles del distrito"),
        P("economia", "Boulevard en la Av. General Garzón y corredor gastronómico y turístico en las avenidas Cuba y República Dominicana", 18, "Implementar el boulevard de la"),
        P("transporte", "Construir ciclovías, instalar semáforos inteligentes y rehabilitar pistas y veredas", 18, "Promover la construccion de ciclovías"),
        P("ambiente", "Riego por aspersión en todos los parques y áreas verdes", 11, "implementación del sistema de riego por aspersión en todos los parques"),
        P("gestion", "Reducir la morosidad tributaria con nuevas estrategias de cobranza con beneficios", 20, "Bajar el índice de morosidad aplicando nuevas estrategias", "3 % anual de reducción"),
    ]),
    ("Daniel Ricardo Li León", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Videovigilancia operativa las 24 horas y serenos en los módulos de auxilio todo el día", 57, "Asegurar la operatividad del 100% de las cámaras", "100 % de cámaras operativas las 24 horas"),
        P("seguridad", "Patrullaje integrado por sectores con rutas y horarios según zonas de riesgo", 57, "Implementar patrullaje integrado sectorizado con rutas y horarios"),
        P("urbano", "Mejorar e incrementar la iluminación pública en zonas inseguras", 57, "Mejorar e incrementar la iluminación pública en zonas identificadas como inseguras"),
        P("social", "Ampliar la academia preuniversitaria municipal para poblaciones vulnerables y reactivar la academia de informática", 58, "Ampliar el acceso a la academia preuniversitaria municipal"),
        P("social", "Programas de prevención y seguimiento nutricional contra la anemia y la desnutrición infantil", 58, "Implementar programas integrales de prevención, control y seguimiento nutricional"),
        P("social", "Campañas de salud preventiva en parques con chequeos, salud bucal y orientación psicológica", 58, "Desarrollaremos campañas permanentes de salud preventiva en parques"),
        P("economia", "Programas de capacitación y ferias descentralizadas para emprendedores del distrito", 59, "Desarrollaremos programas de capacitación y ferias distritales descentralizadas", "16 programas y ferias en 4 años"),
        P("urbano", "Elaborar un Plan de Desarrollo Urbano Distrital para equilibrar crecimiento y servicios", 59, "Desarrollar un Plan de Desarrollo Urbano Distrital"),
        P("agua_riesgos", "Riego por goteo y microaspersión para un uso más eficiente del agua en áreas verdes", 60, "Implementar sistemas de riego por goteo"),
        P("ambiente", "Programa integral de animales en abandono con esterilización, adopción y tenencia responsable", 60, "Reducción del 50% de la población de animales en abandono", "50 % menos animales en abandono y esterilización del 70 % en riesgo"),
        P("gestion", "Simplificar y digitalizar trámites y reducir los tiempos de atención", 60, "80% de trámites digitalizados Reducción del 50% en tiempos de atención", "80 % de trámites digitales y 50 % menos tiempo de atención"),
    ]),
]
