"""Villa María del Triunfo (150143): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150143"

# Planes que no se resumen, con la razón que se muestra junto a la candidatura
NOTAS = {
    "partido-popular-cristiano-ppc": "El plan inscrito ante el JNE para Villa María del Triunfo desarrolla otro distrito (San Juan de Miraflores), con otro candidato en la portada, y no menciona Villa María del Triunfo. Por eso no se resumen sus propuestas; puedes revisarlo en Voto Informado del JNE.",
    "fuerza-popular": "El plan inscrito ante el JNE (2 páginas) solo contiene el ideario, los objetivos generales y la visión de la organización: no presenta propuestas que resumir. Puedes revisarlo en Voto Informado del JNE.",
}

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Roger Edinsson Parra Taboada", "Acción Popular", "accion-popular", [
        P("seguridad", "Módulo multidisciplinario con carceleta, base policial, serenazgo, Ministerio Público y juzgado de flagrancia, mediante un convenio mancomunado", 9, "una agencia de modulo multidisciplinario que albergue una carceleta"),
        P("seguridad", "Operativos con la PNP contra la receptación de vehículos robados y clausura de los locales y cocheras donde se ocultan", 9, "atacaremos el delito de receptación"),
        P("seguridad", "Reactivar los módulos de seguridad abandonados, instalar casetas en zonas peligrosas y cámaras inteligentes, con patrullaje integrado en las siete zonas", 10, "Pondremos en funcionamiento los módulos de seguridad ciudadana abandonados"),
        P("transporte", "Semaforización de cruces congestionados, señalización y paraderos, estudio de rutas y obligación de que los mototaxis pertenezcan a empresas formales", 13, "planteamos una semaforización en las zonas"),
        P("urbano", "Asfaltar las vías pendientes y construir veredas, rampas, escaleras y muros de contención en las siete zonas", 14, "el objetivo es tener el 100% asfaltado", "100 % de vías asfaltadas"),
        P("urbano", "Apoyar a COFOPRI con asistencia técnica para acelerar la titulación en urbanizaciones y asentamientos humanos", 13, "en coordinación con COFOPRI el proceso de titulación"),
        P("agua_riesgos", "Tramitar expedientes técnicos de agua y desagüe para asentamientos humanos sin servicio y actualizar el plan de prevención de riesgos", 13, "obras de agua y desagüe de los Asentamientos Humanos"),
        P("ambiente", "Comprar más compactadoras a GNV para reducir la tercerización del recojo, y control vecinal del servicio con fotos y videos en redes", 11, "adquisición de más compactadores se buscará que sean a GNV"),
        P("social", "Iluminar todos los campos multideportivos para uso nocturno y apoyar a las asociaciones deportivas de cada zona", 12, "iluminación de todos los campos multideportivos"),
        P("economia", "Formalizar a los ambulantes con participación privada, ferias temporales y facilidades de licencia para mypes", 15, "Promover la Formalización de los ambulantes"),
        P("gestion", "Crear una oficina defensorial del vecino para atender casos urgentes directamente con el alcalde", 8, "Crear e implementar una oficina defensorial al servicio del vecino"),
    ]),
    ("Víctor Manuel Calderón Rodríguez", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Centros zonales de monitoreo y videovigilancia integrados al sistema de seguridad ciudadana", 1, "Instalar 500 cámaras en 7 Centros de Monitoreo", "500 cámaras en 7 centros de monitoreo y 20 % menos delitos"),
        P("seguridad", "Ampliar la flota de serenazgo con patrulleros y motos", 1, "Flota de 30 patrulleros y 21 motos", "30 patrulleros y 21 motos"),
        P("social", "Reducir la anemia infantil con alianzas con el MINSA, centros de salud móviles, campañas médicas y una Clínica Municipal", 1, "Erradicar la anemia infantil mediante alianzas con MINSA", "15 % menos anemia, 35 campañas médicas al año y Clínica Municipal operativa al término de la gestión"),
        P("social", "CETPRO Municipal con certificación nacional y ferias de empleo descentralizadas para jóvenes que no estudian ni trabajan", 1, "inserción laboral mediante el CETPRO Municipal", "600 jóvenes certificados al año y 16 ferias laborales por año"),
        P("economia", "Oficinas «Emprende VMT» por zona con asesoría técnica y contable gratuita para formalizar mypes y comercio ambulatorio", 2, "asesoría técnica-contable gratuita", "Oficina «Emprende VMT» en las 7 zonas"),
        P("urbano", "Mantenimiento vial, muros de contención y escaleras con pasamanos en laderas, y veredas con accesibilidad universal", 2, "Construir 200 muros de contención en laderas", "200 muros de contención y 100 escaleras"),
        P("transporte", "Formalizar los mototaxis, eliminar paraderos informales con la MML e identificar los vehículos con código QR", 2, "control de vehículos por código QR", "100 % de vehículos registrados con código QR"),
        P("ambiente", "Puntos ecológicos en avenidas, campañas de reciclaje, formalización de recicladores y planta de compostaje", 2, "formalización de recicladores y planta de compostaje", "100 % de asociaciones de recicladores formalizadas"),
        P("ambiente", "«Cinturón Verde Villamariano», cuidado de las Lomas de Paraíso y circuitos de ecoturismo comunitario", 2, "Cinturón Verde Villamariano", "2.5 m² de área verde por habitante y 2 circuitos ecoturísticos"),
        P("gestion", "Portal de transparencia y tablero de control ciudadano, transmisión de todas las sesiones del Concejo y audiencias semestrales en las 7 zonas", 3, "Portal de Transparencia y Tablero de Control Ciudadano", "100 % de sesiones del Concejo transmitidas desde el primer mes"),
        P("gestion", "Plataforma digital unificada con pagos en línea de trámites del TUPA y gestión documental y tributaria digital", 3, "Sistema tributario digital integrado al primer año", "Plataforma unificada y sistema tributario digital operativos en el primer año de gestión"),
    ]),
    ("David Andrés Morales Cárdenas", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Centro de Formación de Serenazgo Lima Sur para capacitar y certificar al personal operativo, abierto a distritos vecinos", 22, "Implementar el Centro de Formación de Serenazgo Lima Sur", "100 % del personal operativo certificado"),
        P("seguridad", "Bases descentralizadas de serenazgo en las siete zonas del distrito para reducir tiempos de respuesta", 19, "se implementarán bases operativas descentralizadas"),
        P("seguridad", "Centro C4-VMT que integre serenazgo, fiscalización, transporte, gestión de riesgos, PNP, bomberos y juntas vecinales con cámaras y GPS", 22, "como plataforma distrital de interoperabilidad"),
        P("economia", "Corredores comerciales ordenados con iluminación LED, videovigilancia y fiscalización preventiva", 18, "corredores comerciales ordenados con iluminación LED"),
        P("economia", "Programa de modernización de infraestructura, salubridad y tecnología de los mercados tradicionales", 29, "programa integral de modernización para los mercados tradicionales", "60 % de los mercados tradicionales modernizados"),
        P("social", "Centro Juvenil Municipal con capacitación técnica, cultura, deporte, emprendimiento y tecnología", 18, "Centro Juvenil Municipal Espacio integral para"),
        P("social", "Veterinaria municipal con esterilización de perros y gatos a costo social y campañas de adopción", 26, "Implementar una veterinaria municipal"),
        P("transporte", "Formalización, identificación y registro digital de los mototaxis del distrito", 32, "integral de formalización, identificación y registro digital del servicio de mototaxis", "70 % del parque de mototaxis formalizado y registrado"),
        P("agua_riesgos", "Estrategias diferenciadas de seguridad y gestión del riesgo en laderas y zonas altas", 29, "estrategias diferenciadas de seguridad y gestión del riesgo en laderas", "50 % más de cobertura operativa"),
        P("ambiente", "Atrapanieblas para captar agua en las lomas y usarla en su reforestación", 34, "captación del recurso hídrico natural del distrito para la reforestación"),
        P("gestion", "Certificar la municipalidad con las normas ISO 37001 (antisoborno) y 9001 (gestión de calidad)", 39, "37001 (anti soborno) y 9001 (Gestión de calidad)"),
    ]),
    ("Daniel Fernández Núñez", "Cooperación, Verdad y Honradez", "cooperacion-verdad-y-honradez", [
        P("seguridad", "Patrullaje por cuadrantes y tecnología de vigilancia en paraderos y zonas comerciales críticas", 2, "sistema de patrullaje por cuadrantes", "35 % menos robos y hurtos en paraderos de alto riesgo"),
        P("transporte", "Control del transporte menor con empadronamiento de mototaxis y código QR de seguridad", 2, "mototaxis formales plenamente empadronadas con código QR", "100 % de mototaxis empadronadas con código QR"),
        P("social", "Integrar ollas comunes y comedores al programa «Alacena Municipal» para reducir la anemia infantil", 2, "ollas comunes integradas eficazmente al programa integral", "100 % de ollas comunes integradas y 15 puntos porcentuales menos de anemia infantil"),
        P("economia", "Formalizar mypes con licencias provisionales de costo cero", 2, "licencias provisionales con costo cero", "3,500 nuevas MYPES formalizadas"),
        P("economia", "Escuela de Oficios con capacitación técnica alineada a la demanda industrial de Lima Sur", 2, "1,500 jóvenes certificados anualmente mediante la Escuela de Oficios", "1,500 jóvenes certificados al año"),
        P("economia", "Reordenamiento urbano, comercial y de seguridad del entorno del Terminal Pesquero como hub gastronómico y pesquero", 3, "Hub Gastronómico y Pesquero de VMT", "40 % más afluencia turística comercial"),
        P("ambiente", "Reingeniería de rutas de recojo de residuos y programa de reciclaje con incentivos tributarios", 3, "programa de reciclaje con incentivos tributarios directos", "40 % de la población participando en el reciclaje"),
        P("ambiente", "Erradicar los botaderos informales identificados en la vía pública", 3, "Eliminación del 90% de los botaderos informales mapeados", "90 % de botaderos informales eliminados"),
        P("ambiente", "Delimitar físicamente y proteger del tráfico de terrenos las Lomas de Paraíso y Virgen de Lourdes, con uso ecoturístico", 3, "Lomas de Paraíso y Virgen de Lourdes delimitadas físicamente", "100 % de ambas lomas delimitadas"),
        P("agua_riesgos", "Muros de contención y escaleras de acceso en zonas altas financiados con Obras por Impuestos", 4, "Construcción de 150 muros de contención estratégicos", "150 muros de contención y escaleras"),
        P("gestion", "Transformación digital «Cero Papel» de trámites y licencias, con auditorías públicas semestrales del plan", 4, "80% de los trámites y licencias municipales digitalizados", "80 % de trámites digitalizados y 50 % menos tiempo de espera"),
    ]),
    ("Franklin Villarruel Álvarez", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("social", "Programa «VMT Sin Anemia»: suplementación nutricional con comedores y ollas comunes de zonas altas y seguimiento de gestantes y niños", 9, "articulada con los comedores populares y ollas comunes", "Anemia infantil por debajo del 12 % al 2030"),
        P("social", "Hogares de refugio temporal municipales con talleres de emprendimiento y DEMUNA descentralizada en las 7 zonas", 11, "Hogares de Refugio Temporal (HRT) municipales", "50 % más capacidad de atención y albergue a mujeres víctimas de violencia"),
        P("seguridad", "Sistema de videovigilancia con centrales de monitoreo descentralizadas, patrullaje integrado y equipamiento de juntas vecinales", 11, "Instalación de 150 cámaras de seguridad", "150 cámaras de seguridad"),
        P("agua_riesgos", "Plan «Agua y Luz para VMT»: asistencia técnica a comités vecinales ante SEDAPAL y eléctricas, y pilones públicos provisionales", 10, "viabilización de perfiles ante SEDAPAL y empresas eléctricas", "85 % de hogares con agua, saneamiento y luz al 2030"),
        P("agua_riesgos", "Muros de contención y andenería en laderas, sistemas de alerta temprana ante deslizamientos y capacitación de comités de Defensa Civil", 17, "Sistemas de Alerta Temprana (SAT) ante deslizamientos"),
        P("economia", "«Formaliza VMT»: licencias más simples y baratas, y reubicación de ambulantes en mercados zonales", 12, "reubicación y ordenamiento en mercados zonales para comerciantes ambulantes", "20 % menos comercio ambulatorio en avenidas principales al 2030"),
        P("economia", "Escuela Municipal de Emprendimiento y Oficios gratuita y bolsa de trabajo móvil en las 7 zonas", 13, "Bolsa de Trabajo Municipal Móvil en las 7 zonas", "3,000 ciudadanos capacitados y certificados al 2030"),
        P("ambiente", "Programa «VMT Limpio y Sostenible»: rediseño de rutas y horarios de recojo, contenedores públicos y multas a botaderos clandestinos", 13, "Rediseño de las rutas y horarios de recolección", "100 % de cobertura del recojo residencial"),
        P("ambiente", "Conservación de lomas con delimitación física, hitos de concreto y reforestación con plantas nativas", 14, "delimitación física e hitos de concreto", "100 % de las lomas delimitadas al 2030"),
        P("urbano", "Reestructurar fiscalización y catastro para vigilar laderas y operativos con la PNP contra el tráfico de tierras", 16, "Operativos conjuntos permanentes con la PNP para prevenir el tráfico de tierras"),
        P("gestion", "Mesa de partes virtual, licencias digitales y audiencias de rendición de cuentas en cada zona", 17, "Mesa de Partes Virtual y emisión", "80 % de trámites digitalizados al 2030"),
    ]),
    ("Carlos Walter Mejía Escajadillo", "Fuerza Popular", "fuerza-popular", []),
    ("René Alfredo Yucra Verástegui", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Central distrital de serenazgo equipada y módulos de seguridad en las 7 zonas con patrullaje integrado", 5, "construcción de módulos de seguridad en las 07 zonas"),
        P("seguridad", "Centro de monitoreo con cámaras en las siete zonas y escuela de capacitación para serenazgo, juntas vecinales y sociedad civil", 9, "monitoreo con cámaras de video vigilancia en las (7) siete zonas"),
        P("transporte", "Estudios de viabilidad de puentes vehiculares y peatonales sobre la línea del tren eléctrico entre Inca Pachacútec y Cercado", 8, "Puentes Vehicular entre la Zona de Inca Pachacutec y Cercado"),
        P("urbano", "Programas de titulación con COFOPRI en asentamientos humanos sin título y nuevo catastro urbano", 8, "Impulsar programas de TITULACION en los AA.HH"),
        P("urbano", "Pistas, veredas y parques, y muros y escaleras en las partes altas del distrito", 5, "altas (construcción de muros y escaleras)"),
        P("agua_riesgos", "Priorizar las gestiones para ejecutar proyectos de agua y desagüe", 8, "Priorizar el apoyo en las gestiones para la ejecución de los proyectos de servicios básicos de agua y desagüe"),
        P("social", "Construir la Casa de la Mujer, la Casa del Adulto Mayor y una Academia Preuniversitaria Municipal", 5, "Construcción de la Casa de la Mujer"),
        P("social", "Apoyar la remodelación del estadio «Héctor Chumpitaz» y proponer una unidad deportiva multidisciplinaria", 11, "remodelación y construcción del estadio"),
        P("economia", "Centro de Apoyo Empresarial con asesoría jurídica y financiera, y bolsa de trabajo para profesionales y técnicos del distrito", 18, "a través de un Centro de Apoyo Empresarial"),
        P("ambiente", "Estudiar una planta de reciclaje de residuos y una empresa paramunicipal de recolección y disposición final", 19, "instalación de una planta de reciclado de residuos"),
        P("gestion", "Rendición de cuentas semestral del gasto, actualización del catastro y licitaciones conforme a ley", 21, "rendición de cuentas semestral de cada centavo"),
    ]),
    ("Juan José Castillo Ángeles", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Cámaras con inteligencia artificial y reconocimiento facial integradas al centro de monitoreo en las 7 zonas", 9, "Cámaras con IA y reconocimiento facial"),
        P("social", "Centros de salud mental comunitaria con atención gratuita en cada zona", 7, "Garantizar la atención gratuita en los CSMC para cada zona de VMT"),
        P("social", "Consolidar ollas comunes y comedores con raciones que cumplan estándares nutricionales", 6, "Consolidación de Ollas Comunes y Comedores"),
        P("urbano", "Titulación y saneamiento físico-legal de predios informales", 6, "Titulación y saneamiento físico-legal"),
        P("economia", "Formalizar el comercio minorista trasladándolo a mercados modernos", 13, "Traslado a mercados modernos"),
        P("economia", "Poner en valor las Lomas de Paraíso como atractivo turístico, con atrapanieblas para riego", 8, "Consolidar a Lomas de VMT como un atractivo turístico"),
        P("transporte", "Semáforos inteligentes sincronizados por inteligencia artificial en avenidas principales", 9, "Semáforos inteligente sincronizados por IA"),
        P("agua_riesgos", "Sensores de alerta temprana ante sismos y derrumbes en zonas de riesgo, y muros de contención y andenes", 9, "Incorporación de sensores en las zonas más vulnerables"),
        P("ambiente", "Primera planta distrital de tratamiento de residuos sólidos", 10, "Inauguración de la primera planta de tratamiento de residuos"),
        P("ambiente", "Reúso de aguas residuales tratadas para regar parques", 10, "Reúso de aguas para riego de parques"),
        P("gestion", "Gobierno digital con todos los trámites municipales en línea", 9, "Plataforma de trámites al 100% en todos los procesos", "100 % de trámites en línea"),
    ]),
    ("Guido Íñigo Peralta", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Cámaras con reconocimiento de rostro y placas y siete subcentrales descentralizadas de videovigilancia", 23, "Adquirir 1,000 cámaras de videovigilancia que se sumarán a las 650 existentes", "1 000 cámaras nuevas, 7 subcentrales y 50 % menos delitos priorizados"),
        P("seguridad", "Más serenos distribuidos en las 7 zonas y camionetas eléctricas, con servicio de serenazgo con IA", 23, "Incrementar de 62 a 82 el número", "De 528 a 700 serenos y de 62 a 82 camionetas"),
        P("social", "Palacio Distrital de la Cultura con biblioteca digital, complejos multideportivos por zona y losas multiusos", 24, "Construir 7 complejos multideportivos, uno en cada zona", "7 complejos multideportivos y 35 losas multiusos"),
        P("social", "Casa del Adulto Mayor Distrital, espacios inclusivos por zona y casa de la mujer emprendedora en las 7 zonas", 25, "Construir la Casa del Adulto Mayor Distrital", "80 % de cobertura de la población vulnerable"),
        P("urbano", "Pistas de concreto, veredas, escaleras urbanas y muros de contención", 25, "80 % de vías urbanas con pistas de concreto en buen estado", "80 % de vías y veredas, 70 % de escaleras y 60 % de muros"),
        P("economia", "Ferias laborales, capacitaciones en emprendimiento y apoyo a emprendedores locales", 27, "Realizar 20 ferias laborales durante el periodo", "20 ferias laborales, 200 capacitaciones y 5 000 emprendedores beneficiados"),
        P("transporte", "Formalizar y fiscalizar el servicio de mototaxis", 28, "80 % de unidades de mototaxis formalizadas", "80 % de mototaxis formalizadas"),
        P("ambiente", "Compra de compactadoras a GNV y programas de reciclaje para mejorar la recolección", 29, "Adquisición de 20 compactadoras a GNV", "20 compactadoras a GNV, 50 operativas y 90 % de cobertura"),
        P("ambiente", "Construir o rehabilitar parques temáticos, alamedas y espacios públicos, y una veterinaria municipal", 30, "rehabilitar 230 parques temáticos, alamedas", "230 parques y espacios públicos y 80 % más áreas verdes"),
        P("agua_riesgos", "Simulacros y capacitaciones en gestión del riesgo para reducir la población asentada en zonas de riesgo", 30, "Realizar 10 simulacros de emergencia a nivel distrital", "10 simulacros, 160 capacitaciones y 40 % menos población en zonas de riesgo"),
        P("gestion", "Digitalizar los trámites municipales con plataformas integradas de atención", 31, "Digitalizar el 80 % de los trámites municipales", "80 % de trámites digitalizados y 3 plataformas"),
    ]),
    (None, "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Duplicar la flota y el personal de serenazgo y crear la Escuela de Serenazgo de Villa María del Triunfo", 5, "Duplicaremos la flota vehicular y el personal de Serenazgo"),
        P("seguridad", "Escuadrón de drones conectado a centros de control y cámaras con reconocimiento facial y lectura de placas", 11, "Escuadrón aéreo a través de drones"),
        P("social", "Centros municipales de rehabilitación para jóvenes en pandillas o con consumo de drogas", 12, "Centros de rehabilitación municipal, dirigidos a los jóvenes"),
        P("social", "Gestionar becas anuales para jóvenes de bajos recursos en convenio con empresas del distrito", 9, "GESTIONAR 100 BECAS ANUALES PARA JOVENES", "100 becas anuales"),
        P("social", "Guarderías municipales, casa del adulto mayor en cada zona y formalización de ollas comunes", 11, "Creación e implementación de Guarderías Municipales"),
        P("economia", "Formalizar a vendedores ambulantes y empresas con licencias de funcionamiento y certificados ITSE", 6, "Formalizar en un plazo de dos años a todos los vendedores ambulantes", "En dos años (diciembre de 2028)"),
        P("economia", "Parques industriales en las siete zonas del distrito y talleres productivos en locales comunales", 11, "Creación de parques industriales en las siete zonas"),
        P("ambiente", "Proyectos para el tratamiento e industrialización de la basura, recojo por horarios y formalización de recicladores", 6, "la basura beneficiando al 95% de", "95 % de la población beneficiada (diciembre de 2029)"),
        P("urbano", "Muros de contención, escaleras y pistas de concreto en las zonas altas, y polideportivos en las 7 zonas", 10, "Construcción de escaleras y pistas de concreto en las zonas altas"),
        P("agua_riesgos", "Promover la ampliación y mejora del agua potable y alcantarillado del esquema 300", 10, "sistemas de agua potable y alcantarillado del esquema 300"),
        P("gestion", "Sistema de gestión ISO 9001 y código de ética para proveedores y funcionarios con apoyo de la Contraloría", 6, "sistema integrado de gestión ISO 9001", "En un año (diciembre de 2027)"),
    ]),
    ("Juan Carlos Medina Morillo", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "«Plan Centinela»: cámaras en calles de alta incidencia delictiva de las 7 zonas, repotenciación de las existentes y central de monitoreo", 7, "Instalación de cámaras en avenidas y calles de alto índice criminal", "800 cámaras operativas al 2030 (línea base: 120)"),
        P("seguridad", "Serenazgo con selección de personal, motos y camionetas por sector y una ambulancia por zona", 7, "Adquisición de motos y camionetas para vigilancia preventiva", "500 serenos activos; 4 unidades móviles por sector; 7 ambulancias operativas"),
        P("social", "Programa «Nutrición Infantil VMT»: charlas a madres contra la anemia, suplementación nutricional y brigadas de salud móviles en las 7 zonas", 8, "Charlas de capacitación a madres de familia", "Anemia infantil reducida al 15 % al 2030 (línea base: más de 30 %)"),
        P("social", "Una botica municipal en cada agencia zonal para dar acceso a medicamentos básicos, con convenios con el MINSA", 8, "Implementación de una botica municipal en cada agencia distrital", "7 boticas municipales operativas al 2028"),
        P("social", "Construir un polideportivo con pista atlética y campo de fútbol, y un coliseo para vóley y básquet", 8, "Construcción de un polideportivo con pista atlética", "1 polideportivo y 1 coliseo construidos"),
        P("economia", "Alamedas y espacios comerciales en los cerros (zonas altas) para impulsar a nuevos emprendedores", 10, "Construcción de alamedas y espacios comerciales en los cerros", "Alamedas operativas al 2028; 200 emprendedores beneficiados por año"),
        P("ambiente", "Segregación en la fuente, formalización de recicladores, volquetes para desmonte y motocars para recoger residuos en pendientes", 11, "Formalización de recicladores", "95 % de cobertura y 0 puntos críticos al 2030 (línea base: más de 80)"),
        P("ambiente", "Plantar árboles en vías, parques y lomas y crear viveros municipales", 11, "Plantación de 50,000 árboles en vías, parques y lomas", "50 000 árboles plantados y 7 viveros operativos al 2030"),
        P("urbano", "Pavimentación progresiva de calles y avenidas en las 7 zonas, priorizando los accesos a las zonas altas, con cofinanciamiento del MTC y el MVCS", 12, "Ejecución progresiva de pavimentación de calles y avenidas priorizadas"),
        P("agua_riesgos", "Muros de contención, estabilización de taludes y escaleras de concreto en los cerros para prevenir deslizamientos", 12, "Construcción de muros de contención y obras de estabilización de taludes"),
        P("gestion", "Trasladar servicios a agencias municipales modernizadas en las 7 zonas para que el vecino no vaya a la sede central", 13, "Traslado de servicios a las agencias municipales en las 7 zonas", "7 agencias operativas y 80 % de trámites resueltos en la zona al 2030"),
    ]),
    ("Víctor Edward Colán Huamán", "Partido Patriótico del Perú", "partido-patriotico-del-peru", [
        P("seguridad", "Ampliar el patrullaje preventivo del serenazgo en avenidas, parques, mercados, colegios y zonas comerciales", 21, "ampliación progresiva del patrullaje preventivo en avenidas"),
        P("seguridad", "Modernizar el sistema de videovigilancia distrital recuperando y reforzando las cámaras de seguridad", 21, "modernización progresiva del sistema de videovigilancia distrital"),
        P("seguridad", "Corredores urbanos seguros: patrullaje, videovigilancia, iluminación y fiscalización en las avenidas de mayor circulación", 48, "Propuesta de fortalecimiento de corredores urbanos seguros"),
        P("urbano", "Programas permanentes de mantenimiento de pistas, veredas, parques y bermas en los sectores más deteriorados", 21, "mantenimiento y recuperación progresiva de pistas, veredas, parques, bermas"),
        P("urbano", "Fiscalización permanente de la ocupación indebida de espacios públicos y del comercio informal desordenado", 22, "ocupación indebida de espacios públicos, comercio informal desordenado"),
        P("urbano", "Recuperar y modernizar parques y espacios públicos con iluminación, mantenimiento de áreas verdes y mobiliario urbano", 49, "Propuesta de recuperación y modernización de parques y espacios públicos"),
        P("ambiente", "Reforzar la recolección de residuos en sectores con acumulación de basura y hacer campañas de educación ambiental", 23, "mecanismos de recolección de residuos sólidos"),
        P("transporte", "Mantenimiento de vías urbanas, señalización y recuperación de espacios para el tránsito peatonal", 25, "fortalecimiento de señalización territorial"),
        P("social", "Actividades deportivas, culturales y recreativas para fortalecer la integración vecinal de niños, jóvenes, adultos mayores y familias", 23, "actividades deportivas, culturales, recreativas y comunitarias"),
        P("economia", "Programa de desarrollo económico local con organización comercial y formalización progresiva, en coordinación con comerciantes y emprendedores", 25, "Programa de Desarrollo Económico Local y Fortalecimiento del Emprendimiento Distrital"),
        P("gestion", "Programa de gobierno digital y ciudad inteligente: plataformas para atención vecinal, monitoreo urbano y fiscalización", 47, "Programa de Gobierno Digital, Innovación Urbana y Ciudad Inteligente"),
    ]),
    ("Carlos Armando Chávez Montoya", "Perú Primero", "partido-politico-peru-primero", [
        P("economia", "Reforzar la ventanilla de desarrollo económico local para agilizar los trámites de licencias de funcionamiento", 29, "Reforzar la ventanilla de desarrollo económico local", "Reducir en 50 % el tiempo de emisión de licencias"),
        P("economia", "Empadronar a los ambulantes de las 7 zonas y formalizarlos, con espacios comerciales autorizados y fiscalización permanente", 30, "Programa Integral de Ordenamiento y Formalización del Comercio Ambulatorio", "Formalizar al menos el 50 % de los ambulantes identificados y recuperar el 70 % de los espacios públicos invadidos"),
        P("social", "Gestionar ante el Gobierno Nacional y el Regional nuevos hospitales y centros de salud, y mejorar y equipar las postas existentes", 31, "la construcción de nuevos hospitales y centros de salud", "Gestionar al menos 2 hospitales nuevos y modernizar el 100 % de las postas"),
        P("social", "Fondo municipal de becas o subsidios para útiles, uniformes y transporte de escolares en pobreza extrema con riesgo de abandono", 32, "Crear un fondo municipal de apoyo educativo", "95 % de esos estudiantes asisten regularmente a clases"),
        P("seguridad", "Gestionar una base central de serenazgo, una central de videovigilancia y tres sub-bases, con cámaras según el mapa del delito", 34, "Gestionar la Base de Serenazgo", "Una base central, una central de videovigilancia y 3 sub-bases"),
        P("seguridad", "Convenio «Serenazgo Sin Fronteras» con municipalidades de la Mancomunidad de Lima Sur para patrullaje y operativos conjuntos", 35, "entre municipalidades pertenecientes a la Mancomunidad de Lima Sur", "500 operativos conjuntos y 40 % menos incidencia delictiva en los sectores del programa"),
        P("social", "Gestionar la construcción de una Casa Refugio para mujeres e hijos víctimas de violencia familiar y trata de personas", 36, "donde se albergará a mujeres e hijos", "Atención integral a más de 2000 mujeres, niños y adolescentes"),
        P("transporte", "Construir, rehabilitar y mantener vías de acceso a los asentamientos de las zonas altas para transporte público y vehículos de emergencia", 37, "plan de mejoramiento de la accesibilidad vial en zonas altas", "90 % de la población de los cerros con acceso seguro al transporte"),
        P("ambiente", "Programa de arborización con nuevos parques, corredores verdes, viveros municipales y campañas masivas de plantación", 38, "Programa Distrital de Arborización y Recuperación de Áreas Verdes", "70 % más áreas verdes y al menos 50 000 árboles plantados"),
        P("ambiente", "Contenedores de gran capacidad, puntos de acopio temporal de desmonte y reciclaje comunitario", 38, "instalación de contenedores de gran capacidad", "500 contenedores instalados y 90 % menos puntos críticos de basura y desmonte"),
        P("gestion", "Control urbano para que licencias, visación de planos y obras se autoricen solo en zonas seguras, con evaluación de riesgo", 40, "Implementar un mecanismo de control urbano", "Al menos 95 % de autorizaciones urbanas en zonas seguras"),
    ]),
    ("Cresencio Gonzales Ccapcha", "PPC", "partido-popular-cristiano-ppc", []),
    ("Edgard Freddy Paucar Calero", "Perú Moderno", "peru-moderno", [
        P("social", "Gestionar ante las autoridades la construcción del Hospital José Carlos Mariátegui, declarado de interés nacional por la Ley N.º 32528", 10, "la pronta construcción de dicho hospital"),
        P("social", "Gestionar ante el IPD el acceso de los vecinos al Complejo Deportivo Andrés Avelino Cáceres", 10, "Es necesario gestionar ante el IPD la apertura"),
        P("economia", "«Licencia Rápida»: menos burocracia para obtener licencias de funcionamiento y formalizar negocios", 11, "Reducir la burocracia en la obtención de licencias de funcionamiento"),
        P("economia", "Centro de Desarrollo Empresarial VMT con capacitación gratuita en gestión, marketing digital y finanzas para pequeños empresarios", 12, "Centro de Desarrollo Empresarial VMT"),
        P("economia", "Feria «Consume Villa María»: ferias itinerantes mensuales de artesanos y comerciantes locales", 12, "ferias itinerantes mensuales"),
        P("economia", "Ruta turística a lomas y zonas naturales, y puesta en valor del cementerio de Nueva Esperanza para turismo vivencial y gastronómico", 12, "Puesta en Valor del Cementerio de Nueva Esperanza"),
        P("urbano", "Plan de reordenamiento de zonas comerciales para ordenar el comercio ambulatorio y liberar las vías", 12, "Plan de Reordenamiento de Zonas Comerciales"),
        P("ambiente", "Más cobertura de recolección en las 7 zonas, segregación casa por casa y erradicación de puntos críticos de basura", 13, "segregación en la fuente (reciclaje) casa por casa"),
        P("ambiente", "Supervisar el impacto ambiental de la planta de cemento UNACEM y gestionar ante el OEFA el cumplimiento de los límites permisibles", 13, "Supervisar el impacto ambiental de la planta de cemento UNACEM"),
        P("ambiente", "Reforestación de cerros y laderas y conversión de espacios abandonados en parques ecológicos", 13, "Reforestación de cerros y laderas"),
        P("gestion", "Espacios de diálogo descentralizado por zonas y estudio sociodemográfico actualizado del distrito", 16, "Zonas de diálogo descentralizado"),
    ]),
    ("Carlos Francisco Hinostroza Rodríguez", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Equipar casetas de serenazgo, nuevas unidades móviles y cámaras de videovigilancia para las siete zonas", 50, "Equipamiento de las casetas de serenazgos"),
        P("social", "Gestionar el financiamiento y la construcción de un policlínico municipal", 29, "Gestión para financiamiento de un Policlínico Municipal"),
        P("social", "Construir la Casa de la Mujer y la Casa del Adulto Mayor", 31, "Construcción de la Casa de la Mujer y de la Casa del Adulto Mayor"),
        P("social", "Escuelas de oficio para jóvenes, madres solteras y adultos mayores", 32, "a través del funcionamiento de escuelas de oficio"),
        P("transporte", "Ordenar y fiscalizar los mototaxis y generalizar la semaforización inteligente, en coordinación con Lima Metropolitana", 27, "mejorando la organización y fiscalización de los servicios de vehículos menores"),
        P("economia", "Proyectos de centros comerciales para reubicar a los comerciantes ambulantes", 51, "reubicación de los comerciantes ambulantes"),
        P("ambiente", "Recolección diferenciada de residuos y una planta de procesamiento de basura", 39, "instalación de una Planta de Procesamiento de la basura"),
        P("ambiente", "Tratar aguas servidas para regar áreas verdes de vías, parques y jardines", 52, "tratamiento de aguas servidas para el riego"),
        P("urbano", "Sistema de Administración de Pavimentos para planificar ampliación, conservación y rehabilitación de pistas", 42, "Implementar un Sistema de Administración de Pavimentos"),
        P("urbano", "Promover la entrega de títulos de propiedad y el saneamiento físico legal ante COFOPRI y Lima Metropolitana", 46, "Fomentar y promover la entrega de Títulos de Propiedad"),
        P("gestion", "Audiencias públicas descentralizadas de rendición de cuentas al cierre de cada año fiscal", 44, "audiencias públicas de rendición de cuentas, que se realizarán al concluir cada año fiscal"),
    ]),
    ("Víctor Tito Sotomayor Bernaola", "Progresemos", "progresemos", [
        P("seguridad", "Patrullaje motorizado descentralizado las 24 horas en las siete zonas y renovación del parque automotor de seguridad", 12, "patrullaje motorizado descentralizado las 24 horas", "Parque automotor de seguridad ciudadana reflotado en un 30 %"),
        P("seguridad", "App comunitaria «Escudo digital» conectada a la central de monitoreo de cada zona para reportar emergencias", 13, "Implementación de una app comunitaria conectada directamente a la central de monitoreo", "Llegar en menos de 7 minutos"),
        P("seguridad", "Central municipal de asesoría legal y psicológica para comerciantes víctimas de cobro de cupos, en coordinación con la DIVINCRI", 13, "central municipal que asesore y acompañe legal y psicológicamente"),
        P("social", "Biblioteca Villamariana abierta las 24 horas, con espacios de aprendizaje, auditorios y bases de datos", 17, "BIBLIOTECA VILLAMARIANA con un servicio 24/7"),
        P("social", "Crear un policlínico municipal y hacer campañas mensuales de prevención de cáncer de mama y de cuello uterino", 19, "Creación de un policlínico municipal"),
        P("agua_riesgos", "Programas «La escalera no espera» y «Muro seguro» para el acceso seguro y la protección de viviendas en zonas altas", 20, "LA ESCALERA NO ESPERA"),
        P("economia", "Programas «Villa María Produce» de capacitación técnica y «Chamba Joven VMT» con prácticas laborales en empresas", 23, "Chamba Joven VMT", "Incluir al 20 % de la población sin oficio o profesión"),
        P("economia", "Plataforma comercial municipal para promocionar productos y servicios de emprendedores villamarianos", 22, "plataforma comercial donde se promocionen los productos"),
        P("ambiente", "Recolección con rutas sectorizadas y monitoreo GPS, y más contenedores cerca de paraderos, colegios y zonas comerciales", 24, "rutas sectorizadas y monitoreo GPS", "Reducir 25 % por año los puntos críticos y duplicar los contenedores"),
        P("ambiente", "Crear un hospital veterinario municipal y una subgerencia de turismo para promover las Lomas de VMT", 27, "Creación del Hospital Veterinario Municipal"),
        P("gestion", "Asambleas públicas rotativas en las 7 zonas sobre finanzas y avance de obras, con actas de corrección vinculantes para funcionarios", 31, "Asambleas públicas obligatorias de forma rotativa en las 7 zonas"),
    ]),
    ("Robert Joel Ludeña Guerra", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Compra de drones para vigilancia aérea de zonas críticas", 6, "Sistema de vigilancia aérea para zonas críticas"),
        P("seguridad", "Equipar a las juntas vecinales con radios, chalecos y alarmas, y capacitarlas", 6, "Radios, chalecos, alarmas y capacitación"),
        P("seguridad", "Central de monitoreo con cámaras con inteligencia artificial", 7, "Cámaras con inteligencia artificial"),
        P("seguridad", "Gestionar la construcción y el equipamiento de la Comisaría de Nueva Esperanza", 7, "Gestión, construcción y equipamiento integral"),
        P("urbano", "Pistas y veredas de concreto armado, escaleras solidarias y parques familiares", 9, "PISTAS Y VEREDAS DE CONCRETO ARMADO"),
        P("agua_riesgos", "Programa «Muros que salvan vidas» de muros de contención", 9, "PROGRAMA MUROS QUE SALVAN VIDAS"),
        P("social", "Crear un estadio municipal y nuevas losas deportivas", 9, "CREACIÓN DEL ESTADIO MUNICIPAL"),
        P("social", "Nueva Casa de la Juventud y Casa de la Mujer Villamariana", 9, "CASA DE LA MUJER VILLAMARIANA"),
        P("social", "Academia preuniversitaria municipal y Escuela Municipal de Liderazgo", 14, "PREUNIVERSITARIA MUNICIPAL"),
        P("ambiente", "Planta de reciclaje, renovación de compactadoras y compra de una barredora industrial", 16, "Planta de reciclaje"),
        P("ambiente", "Programa «Un árbol, una vida», «Adopta un parque» y recuperación de áreas verdes", 17, "Programa Un Arbol"),
    ]),
    ("Magaly Rosy Copez Gutiérrez", "Salvemos al Perú", "salvemos-al-peru", [
        P("seguridad", "Más cámaras de videovigilancia y una central de monitoreo reforzada para responder más rápido a emergencias", 2, "Ampliación y modernización del sistema de videovigilancia", "Reducir la percepción de inseguridad en 20 % al 2030"),
        P("seguridad", "Patrullaje conjunto de serenazgo y PNP por cuadrantes, con horarios y rutas en los sectores de mayor incidencia delictiva", 2, "Patrullaje integrado y por cuadrantes"),
        P("social", "Programa municipal de asistencia técnica y logística a ollas comunes, gestionando donaciones de alimentos ante el MIDIS y el sector privado", 2, "Plan de Apoyo a Ollas Comunes", "Asistir al 100 % de las ollas comunes que lo requieran"),
        P("social", "Gestionar con el MIMP un Centro de Acogida Residencial para niñas, adolescentes y mujeres víctimas de violencia", 3, "Creación del Centro de Acogida Residencial", "Implementado antes del segundo año de gestión"),
        P("transporte", "Censo de vehículos menores para formalizarlos, con paraderos y rutas autorizadas, y talleres de educación vial para mototaxistas", 3, "censo de los vehículos menores que operan en el distrito", "Formalizar el 80 % del transporte público informal al 2030"),
        P("urbano", "Unidad especializada de fiscalización de construcciones y de ocupación de espacios públicos, con enfoque preventivo", 3, "unidad especializada para la supervisión de construcciones", "Cero construcciones que obstruyan el espacio público"),
        P("economia", "Digitalizar y agilizar las licencias de construcción y de funcionamiento", 3, "Digitalizar y agilizar el procedimiento para obtener licencias", "Licencias en 15 días hábiles"),
        P("agua_riesgos", "Comisión de seguimiento ciudadano para fiscalizar las obras del proyecto de agua y saneamiento de S/ 510 millones y planificar la operación de la PTAR", 4, "comisión de seguimiento ciudadano para fiscalizar", "Culminación del 100 % del proyecto de agua y saneamiento"),
        P("ambiente", "Rutas eficientes de recolección y campañas de segregación en la fuente con recicladores formalizados", 4, "campañas de segregación en la fuente", "15 % más cobertura de recolección de residuos"),
        P("ambiente", "Recuperar y mantener parques y áreas verdes como espacios seguros para la recreación familiar", 4, "Recuperación de espacios públicos", "Recuperar y mantener 10 parques principales"),
        P("gestion", "Ventanilla única virtual para trámites y pagos, y portal de datos abiertos sobre presupuesto, contrataciones y metas", 4, "Ventanilla única virtual", "Digitalizar el 80 % de los procedimientos principales"),
    ]),
]
