"""Chaclacayo (150107): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150107"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Manuel Javier Campos Sologuren", "Acción Popular", "accion-popular", [
        P("seguridad", "Bases de Monitoreo y Alerta Vecinal en los 6 sectores del distrito y serenazgo con motos, bicicletas y unidades con GPS", 20, "Bases de Monitoreo y Alerta Vecinal"),
        P("seguridad", "Cámaras, megáfonos, sirenas y pulsadores de emergencia en parques, conectados con la PNP y los Bomberos", 21, "megáfonos de alerta pública, sirenas disuasivas"),
        P("transporte", "Estudios y financiamiento para un teleférico turístico que conecte zonas paisajísticas y recreativas del distrito", 21, "Teleférico Turístico de Chaclacayo"),
        P("social", "Policlínico Municipal «Carlos Bazán Zender» para atención primaria, soporte psicológico y terapias infantiles", 21, "Creación e implementación del Policlínico Municipal"),
        P("social", "Academia Preuniversitaria Municipal a costo social, priorizando según la clasificación del SISFOH, y convenios de becas", 22, "primera Academia Preuniversitaria Municipal"),
        P("urbano", "Estudios y proyecto para cambiar todo el alumbrado público a luminarias LED e iluminar el Malecón de Chaclacayo", 26, "cambio al 100% de las luminarias", "100 % de luminarias con LED"),
        P("economia", "Constituir la Cámara de Comercio de Chaclacayo y reactivar las asociaciones de comerciantes", 27, "Cámara de Comercio de Chaclacayo"),
        P("agua_riesgos", "Proyectos para cambiar las redes de agua y alcantarillado con más de 50 años y gestionar agua las 24 horas con SEDAPAL", 30, "redes de agua potable y alcantarillado obsoletas"),
        P("agua_riesgos", "Mallas metálicas en laderas y quebradas críticas, revegetación de taludes y brigadas vecinales de defensa civil", 31, "mallas geo metálicas en laderas"),
        P("ambiente", "Nuevos camiones compactadores y programa de segregación en la fuente y reciclaje", 31, "segregación en la fuente, minimización de residuos", "100 % de los residuos no reutilizables con disposición final en rellenos sanitarios"),
        P("gestion", "Sistema antisoborno con certificación ISO 37001 y procesos de atención con ISO 9001", 36, "ISO 37001 (Sistema de Gestión Antisoborno)"),
    ]),
    ("Rique Danny Aguilar Quispe", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Centro de Monitoreo con 100 cámaras con reconocimiento facial en mercados, colegios e ingresos, conectado a la comisaría", 26, "Instalar 100 cámaras con reconocimiento facial", "100 cámaras y 30 % menos robos al 2028"),
        P("seguridad", "«Operación Cerrojo»: pórticos con lectores de placas en los 4 accesos al distrito, con cierre solo ante delitos flagrantes graves", 26, "Operación Cerrojo (accesos controlados)", "En 12 meses"),
        P("seguridad", "Convenio con la PNP para rondas mixtas semanales de policía, serenazgo y juntas vecinales", 27, "12 rondas por trimestre (una por semana)", "12 rondas por trimestre (una por semana)"),
        P("agua_riesgos", "Limpieza y descolmatación anual de las quebradas Huascarán y Cuadro antes de la temporada de lluvias", 28, "Limpieza anual de quebradas", "Cada año antes del 30 de noviembre"),
        P("agua_riesgos", "Constituir la EPS comunal «Aguas de Chaclacayo» y ejecutar con el PNSU un proyecto de agua de S/ 43,7 millones", 29, "Constituir legalmente la Entidad Prestadora de Servicios", "Cobertura de agua potable del 89 % al 95 % al 2029"),
        P("urbano", "Inventario de luminarias dañadas y reemplazo con LED, priorizando zonas oscuras; ordenanza para retirar cables aéreos", 30, "Recuperación del alumbrado público Inventario", "100 % de calles con alumbrado funcionando"),
        P("ambiente", "Monitoreo satelital de los camiones de basura con aviso de horario al vecino y planta de compostaje", 30, "monitoreo satelital para los camiones de basura"),
        P("economia", "Ventanilla Única del Emprendedor: licencias de funcionamiento en 48 horas con asesoría legal y contable gratuita", 31, "Ventanilla Única del Emprendedor Implementar", "100 licencias en 48 horas al 2028"),
        P("social", "Reemplazar al proveedor del Vaso de Leche por bonos «Mi Chacla» canjeables en bodegas, ligados a controles de salud", 33, "Reemplazar al proveedor SANUT S.A.", "Reducir 10 % la anemia infantil al 2029"),
        P("social", "Estipendio mensual para socias de comedores populares financiado con el FONCOMUN", 33, "Implementar estipendio mensual para 50 socias", "50 socias con estipendio"),
        P("gestion", "Respaldo documentario para todo gasto «sin producto» y tablero de control de gestión en cada gerencia", 35, "Tablero de Control de Gestión en todas las gerencias", "Menos del 10 % del gasto en el código «sin producto» al 2028"),
    ]),
    ("Leónidas Iván Altamirano Matus", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Videovigilancia con inteligencia artificial, drones, alarmas vecinales y «Serenazgo sin Fronteras» con Chosica y Ate", 3, "Serenazgo sin Fronteras", "Reducir en 30 % la victimización delictiva al 2030"),
        P("agua_riesgos", "Gestionar diques y mallas en las quebradas Los Cóndores, Cusipata y Huascarán", 3, "quebradas Los Cóndores, Cusipata y Huascarán", "100 % de quebradas críticas con alerta temprana y obras de protección al 2030"),
        P("social", "Programa «Médico a tu Puerta» para adultos mayores y personas vulnerables, y recategorización de centros de salud", 3, "Médico a tu Puerta", "90 % de cobertura en programas preventivos de salud al 2030"),
        P("economia", "Corredor gastronómico y turístico «Chaclacayo Tradición» con incentivos tributarios temporales y ferias de fin de semana", 3, "Corredor Gastronómico y Turístico", "40 % más afluencia turística anual al 2030"),
        P("economia", "Programa «Chamba Joven Chaclacayo» con bolsa de trabajo con empresas de Lima Este e incubadora de emprendimientos", 4, "Chamba Joven Chaclacayo", "500 jóvenes beneficiados al año"),
        P("economia", "Reubicar el comercio ambulatorio en ferias modelo y licencias de funcionamiento a costo social («Licencia Cero»)", 4, "reubicación ordenada en ferias modelo", "70 % de comerciantes informales formalizados al 2030"),
        P("ambiente", "Renovar la flota de recolección y programa «Chaclacayo Recicla» con descuentos en arbitrios por segregar", 4, "Chaclacayo Recicla", "30 % de segregación en origen al 2030"),
        P("urbano", "Recuperar parques emblemáticos con riego tecnificado e impulsar el Parque Lineal Río Rímac", 4, "Parque Lineal Río Rímac", "9 m² de área verde por habitante"),
        P("ambiente", "Control de emisiones vehiculares y de ruido con equipos homologados, con operativos en la Carretera Central", 4, "control de emisiones vehiculares y niveles de ruido", "24 operativos de control ambiental al año"),
        P("gestion", "Gobierno digital «Chaclacayo Clic»: todos los trámites del TUPA en línea y licencias automáticas para negocios de bajo riesgo", 4, "digitalización del 100% de los trámites del TUPA", "Licencias de bajo riesgo en máximo 48 horas"),
        P("gestion", "Sistema antisoborno ISO 37001 con auditoría externa y cabildos abiertos trimestrales descentralizados", 5, "Implementación de la norma ISO 37001"),
    ]),
    ("Elsa Stephany Álvarez Bonifaz", "Fe en el Perú", "fe-en-el-peru", [
        P("agua_riesgos", "Comisión de seguimiento y mesa mensual con la ANIN para culminar las defensas ribereñas y la protección de quebradas", 9, "California, Cóndores, Cusipata, Huascarán, Santa Inés", "Protección de toda la ribera y de 5 quebradas al 2030"),
        P("seguridad", "Central de monitoreo en Ñaña con cámaras con IA, ambulancia municipal, policía canina y patrullaje en bicicletas, motos y camionetas", 10, "Meta al 2030: 200 cámaras con inteligencia artificial", "200 cámaras con IA y respuesta en 5 minutos o menos al 2030"),
        P("gestion", "Oficina de Gestión de Proyectos, digitalización de expedientes y ventanilla única virtual", 10, "Implementación de una Oficina de Gestión de Proyectos", "80 % de procesos automatizados al 2030"),
        P("seguridad", "Escuela de formación para inspectores y serenos y más efectivos de serenazgo con pago puntual", 10, "Incrementar en un 50 por ciento los efectivos de serenazgo", "50 % más serenos"),
        P("agua_riesgos", "Declarar en emergencia y reemplazar las redes de agua y alcantarillado de los sectores 4 y 5, con medidores y cloración", 11, "reemplazo integral de redes de agua potable y alcantarillado", "100 % de redes renovadas y 99 % de continuidad al 2030"),
        P("social", "Mejorar los 9 establecimientos de salud del primer nivel con equipamiento y remodelación, en convenio con la DIRIS Lima Este", 11, "Mejoramiento integral de los 9 establecimientos de salud"),
        P("economia", "Ventanilla única de licencias, ferias «Hecho en Chaclacayo» y capacitación digital para mypes", 14, "Crear una ventanilla única de licencias de funcionamiento", "Más de 100 mypes formalizadas y 10 % más empleo formal al 2030"),
        P("transporte", "Señalización vial horizontal y vertical en todas las vías del distrito, con reductores de velocidad", 14, "Señalización vial completa en todas las vías del distrito", "100 % de vías señalizadas, 50 km de señalización horizontal y 500 señales verticales"),
        P("urbano", "Pavimentación por etapas de las partes altas y asentamientos humanos periféricos (Santa Rosa, Villa Mercedes, Huascata, Perla del Sol)", 14, "Pavimentación de sectores más alejados del distrito"),
        P("ambiente", "Operación «Río Vivo»: limpieza semestral, recojo gratuito de desmonte y fiscalización con drones en la ribera del Rímac", 15, "limpieza, fiscalización y recojo de desmonte", "12 km de ribera limpia (100 % del tramo distrital)"),
        P("urbano", "Gestionar la viabilidad, financiamiento y construcción del parque lineal entre el puente Ñaña y el puente Los Girasoles", 16, "Concreción del proyecto de parque lineal"),
    ]),
    ("Karen Elizabeth Acevedo Salvatierra", "Fuerza Ciudadana", "fuerza-ciudadana", [
        P("agua_riesgos", "Muros de contención, diques secos y barreras dinámicas por etapas en quebradas, y rutas de evacuación señalizadas", 12, "diques secos trapezoidales y barreras dinámicas"),
        P("agua_riesgos", "Simulacros calendarizados en los sectores más expuestos y fortalecimiento de brigadas comunitarias", 15, "Simulacros focalizados y calendarizados por sectores"),
        P("seguridad", "Plan «Luz y Orden para la Seguridad» en parques, escaleras, paraderos, zonas comerciales y accesos barriales", 17, "Luz y Orden para la Seguridad"),
        P("seguridad", "Apps vecinal y de patrullaje, mapa del delito en tiempo real y videovigilancia con IA y lectura de placas en los accesos", 18, "accesos estratégicos (Filampa, Ñaña, Los Girasoles, Puente Los Ángeles)"),
        P("social", "Centro Municipal de Orientación y Ayuda Especializada con soporte legal y psicológico, y modernización de la Casa de la Mujer", 24, "Centro Municipal de Orientación y Ayuda Especializada"),
        P("urbano", "Plan barrial de accesibilidad peatonal y recuperación de parques, losas, escaleras y muros en zonas priorizadas", 22, "Plan barrial de accesibilidad y conectividad peatonal segura"),
        P("ambiente", "Programas «Mi parque, mi jardín» y «Mi hijo, mi árbol» con riego tecnificado y participación vecinal", 22, "con riego tecnificado y apropiación comunitaria"),
        P("gestion", "Gestión documental «Cero Papel» con expediente electrónico, firma y notificación digital y pagos electrónicos", 23, "expediente electrónico, firma digital, notificación electrónica"),
        P("economia", "Ventanilla ágil de licencias con seguimiento de expedientes y escuela de habilidades comerciales y finanzas digitales", 27, "Ventanilla ágil para licencias"),
        P("economia", "Oficina de Promoción de la Inversión, Banco de Proyectos y Red Turística de Chaclacayo", 30, "Oficina de Promoción de la Inversión y la Competitividad Local"),
        P("gestion", "Implementar ISO 37001 en contrataciones, fiscalización y obras, e ISO 9001 en atención y licencias", 32, "Implementación gradual de ISO 37001 en procesos de riesgo"),
    ]),
    ("Mario Daniel Cubas Romero", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Central de videovigilancia conectada a la Policía y a los puntos de entrada y salida del distrito", 9, "Central de video vigilancia conectada a la policía nacional"),
        P("seguridad", "Modernizar el serenazgo y reforzar el patrullaje integrado por sectores con la PNP", 8, "Implementar, modernizar un cuerpo de serenazgo"),
        P("urbano", "Priorizar el catastro de todo el distrito y talleres de saneamiento físico legal de predios", 6, "Corresponde darle prioridad al catastro a todo el distrito"),
        P("agua_riesgos", "Priorizar un Centro de Operaciones de Emergencia con local para logística y simulacros en colegios", 6, "El Centro de Operaciones de Emergencia realmente inoperativo"),
        P("agua_riesgos", "Atender el desabastecimiento de agua con una fuente primaria y planta de potabilización", 7, "ni planta de tratamiento de potabilización de agua"),
        P("transporte", "Ordenar paraderos y mototaxis en puntos estratégicos y señalizar las calles", 7, "Ordenamiento de paraderos y unidades motorizadas (Mototaxi)"),
        P("urbano", "Pistas y veredas para el sector 1 y mejora del servicio de mototaxis", 13, "le corresponde implementar pistas y veredas"),
        P("social", "Remodelar los estadios con servicios higiénicos, vestuarios, tribunas techadas y riego del grass", 8, "es vital una remodelación de dichos estadios"),
        P("economia", "Censar y ordenar el comercio ambulatorio y promover mercados de abastos", 8, "Regular y controlar el comercio ambulatorio, censar a los ambulantes"),
        P("economia", "Promover la construcción de un terminal pesquero para productores y pequeños empresarios", 8, "construcción de un Terrminal Pesquero"),
        P("ambiente", "Proyectos de áreas verdes y espacios públicos con la MML, SERPAR, SEDAPAL y el MINAM", 4, "9.5 m2 de área verde por habitante", "9,5 m² de área verde por habitante al 2030"),
    ]),
    ("Víctor Luis Urrutia Condori", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Fortalecer el serenazgo, optimizar la videovigilancia y promover el patrullaje integrado con la PNP", 7, "Optimizar el sistema de videovigilancia municipal"),
        P("seguridad", "Fortalecer las juntas vecinales de seguridad ciudadana", 7, "Fortalecer las juntas vecinales de seguridad ciudadana"),
        P("social", "Fortalecer la OMAPED y la DEMUNA y promover programas para el adulto mayor", 7, "Fortalecer la atención de personas con discapacidad mediante OMAPED"),
        P("economia", "Estrategia de promoción territorial «Marca Chaclacayo» con ferias productivas, comerciales y gastronómicas", 8, "estrategia de promoción territorial"),
        P("economia", "Capacitación a emprendedores y pequeños negocios y promoción de la formalización empresarial", 8, "Promover la formalización empresarial"),
        P("ambiente", "Programas de arborización urbana y recuperación de áreas verdes y espacios públicos", 9, "Implementar programas de arborización urbana"),
        P("ambiente", "Promover la segregación y valorización de residuos sólidos", 9, "Promover la segregación y valorización de residuos sólidos"),
        P("agua_riesgos", "Intervenciones preventivas en quebradas y zonas vulnerables y capacitación comunitaria en gestión del riesgo", 9, "Gestionar intervenciones preventivas en quebradas y zonas vulnerables"),
        P("agua_riesgos", "Gestionar la ampliación y mejora de agua y alcantarillado y la formalización de conexiones domiciliarias", 9, "priorización de proyectos de ampliación y mejoramiento de los servicios de agua potable"),
        P("gestion", "Control concurrente de la Contraloría en las contrataciones mayores a 8 UIT, con informes publicados", 11, "contratación del pliego mayor a las 8 UIT"),
        P("gestion", "Mesa de concertación mensual del Valle de Chaclacayo transmitida en vivo y plataforma «Vigilancia Verde» de riesgos", 12, "Mesa de Concertación y Diálogo del Valle de Chaclacayo"),
    ]),
    ("Carmen Rosario Cárdenas Alcarraz", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "«Plan Cerco Distrital» de control en Los Ángeles, Filampa, Girasoles, Puente Morón y Puente Ñaña, con sistema inteligente de seguridad", 22, "Plan Cerco Distrital en 5 puntos estratégicos", "5 puntos de control"),
        P("seguridad", "WhatsApp de emergencias, alerta móvil y Escuela de Seguridad Comunitaria", 22, "WhatsApp de Emergencias y Alerta Móvil Chaclacayo"),
        P("social", "Caravana Integral de Salud, Farmadiris con la DIRIS Lima Este y atención de 24 horas en el C. S. López Silva", 22, "CS López Silva con servicio de 24 horas ampliado"),
        P("social", "Programa «Chaclacayo Te Escucha» de atención psicológica comunitaria y red de salud mental", 22, "Programa Chaclacayo Te Escucha con atención psicológica"),
        P("urbano", "Recuperar las losas deportivas, el skate park Miguel Grau y los gimnasios al aire libre", 24, "Todas las losas deportivas del distrito recuperadas progresivamente"),
        P("economia", "Centro de emprendimiento con PRODUCE, SUNAT, MINTRA, MINCETUR y la Cámara de Comercio", 24, "Centro de emprendimiento implementado progresivamente"),
        P("economia", "Circuito turístico Colchón de Nubes y ruta arqueológica (Cerro Culebra, Huascata, Alfonso Cobián) con el Ministerio de Cultura", 25, "Circuito Turístico Colchón de Nubes implementado"),
        P("agua_riesgos", "Programa «Chaclacayo Preparado»: monitoreo de quebradas todo el año, brigadas comunitarias y gestión de diques", 26, "Monitoreo permanente de quebradas y zonas vulnerables"),
        P("agua_riesgos", "Diagnóstico técnico de los sistemas de agua y alcantarillado y revisión transparente de la tarifa", 27, "Diagnóstico técnico integral actualizado de los sistemas de agua potable", "Diagnóstico al 2027"),
        P("ambiente", "Programa «Escuelas Verdes» con promotores ambientales y huertos escolares", 28, "100% de II.EE. participando en programas ambientales", "100 % de colegios en programas ambientales al 2029"),
        P("gestion", "Auditoría integral de la gestión recibida e informe de los primeros 100 días; «Alcaldía en tu Barrio» en los 5 sectores", 29, "Informe de los Primeros 100 Días presentado"),
    ]),
    ("Adolfo Dennis Ojeda García", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Serenazgo descentralizado en los 5 sectores con módulos y puntos de apoyo", 34, "Fortalecimiento de la Seguridad Ciudadana Descentralizada"),
        P("seguridad", "Videovigilancia con reconocimiento facial y analítica en accesos y zonas críticas, integrada con la PNP", 35, "Sistema Inteligente de Seguridad y Reconocimiento Preventivo"),
        P("seguridad", "Escuadrón motorizado de respuesta rápida para atender alertas de vecinos y cámaras", 37, "Creación del Escuadrón de Respuesta Rápida"),
        P("social", "DEMUNA descentralizada y Red de Alerta Vecinal contra la violencia familiar, con talleres en locales comunales", 29, "Red de Alerta Vecinal Comunitaria contra la violencia familiar"),
        P("social", "Módulos itinerantes de estimulación temprana y nutrición infantil articulados con ollas comunes y Vaso de Leche", 30, "PROGRAMA INICIAL DE ESTIMULACIÓN TEMPRANA Y NUTRICIÓN"),
        P("urbano", "Programa «Chaclacayo Accesible»: juegos inclusivos y rampas en plazas y parques", 29, "juegos inclusivos y rampas de acceso"),
        P("economia", "Promover la formalización de mypes con un centro de emprendimiento y escuela de negocios digitales", 27, "Tasa de informalidad general en las micro", "Informalidad de las mypes de 84,8 % a 58 % al 2030"),
        P("economia", "Bolsa de trabajo municipal y feria del empleo descentralizada", 32, "Bolsa de Trabajo Municipal", "Feria del empleo dos veces al año"),
        P("ambiente", "Riego tecnificado por goteo en parques y uso de aguas grises tratadas en lugar de cisternas", 39, "introduciendo el uso de aguas grises tratadas"),
        P("ambiente", "Segregación en la fuente con recicladores formalizados («Conoce a tu Reciclador») y compostaje de residuos de mercados", 40, "Conoce a tu Reciclador"),
        P("transporte", "Reordenar rutas de mototaxis y paraderos e interconectar ciclovías", 42, "Plan de Reordenamiento del Transporte Público Interno"),
    ]),
    ("Vicente Felipe Castillo Jiménez", "Perú Libre", "partido-politico-nacional-peru-libre", [
        P("seguridad", "Mesa Distrital contra el Crimen Organizado, cámaras con lectura de placas y centro de monitoreo las 24 horas", 2, "Mesa Distrital contra el Crimen Organizado", "100 % de zonas críticas monitoreadas"),
        P("seguridad", "Patrullaje integrado permanente, corredores seguros, alarmas vecinales y programa «Vecino Vigilante»", 3, "Implementación de corredores seguros", "30 % menos robos al paso, 50 juntas vecinales y respuesta en menos de 5 minutos"),
        P("seguridad", "Drones para patrullaje, aplicativo de emergencia conectado al serenazgo e integración con la Central 105", 3, "Uso de drones para patrullaje preventivo", "90 % de operatividad tecnológica"),
        P("gestion", "Observatorio Ciudadano de Seguridad, audiencias trimestrales y publicación mensual de estadísticas delictivas", 3, "Creación del Observatorio Ciudadano de Seguridad", "100 % de transparencia en adquisiciones"),
        P("agua_riesgos", "Proteger la ribera del Rímac con muros verdes y barreras naturales", 8, "Protección de la ribera del río Rímac con muros verdes"),
        P("ambiente", "Planta de segregación primaria con recicladores formales, compostaje y puntos ecológicos", 8, "planta de segregación primaria en coordinación con recicladores"),
        P("ambiente", "Ordenanzas contra la quema de residuos, la tala ilegal y el ruido, y plataforma de denuncias ambientales", 9, "Ordenanzas contra la quema de residuos, tala ilegal y contaminación sonora"),
        P("ambiente", "Arborización con especies nativas en parques y laderas y recuperación de áreas verdes degradadas", 10, "Arborización con especies nativas en parques y laderas", "3 m² más de área verde por habitante al 2030"),
        P("agua_riesgos", "Reforestación de quebradas, limpieza de cauces y sistemas de alerta temprana ante huaicos e inundaciones", 10, "Sistemas de alerta temprana ante huaicos e inundaciones", "10 ha reforestadas en zonas críticas al 2030"),
        P("ambiente", "Promover la segregación de residuos en los hogares", 10, "40% de hogares urbanos segregando residuos en origen", "40 % de hogares segregando al 2030"),
    ]),
    ("Marco Antonio Tello Castro", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Torre Integrada de Videovigilancia y Monitoreo con la PNP, el Grupo Terna y la Fiscalía, financiada con el FESC", 25, "Torre Integrada de Videovigilancia", "Torre operativa al 2027; 40 % menos tiempo de respuesta y el doble de operativos conjuntos al 2030"),
        P("social", "Recuperar la capacidad de establecimientos de salud del primer nivel e impulsar un policlínico distrital", 26, "Recuperar la capacidad resolutiva de 4 establecimientos", "4 establecimientos y desnutrición crónica del 5 % al 4 % al 2030"),
        P("social", "Programa «Chaclacayo Educa y Crea» y convenios con PRONIED para mejorar locales escolares", 27, "Chaclacayo Educa y Crea", "Brecha de locales escolares inadecuados en 38 % al 2030"),
        P("agua_riesgos", "Modernizar pozos, reservorios y redes de agua y alcantarillado administrados por la municipalidad", 28, "Programa Integral de Modernización de los Servicios de Agua Potable", "100 % de cobertura en zonas administradas por la municipalidad al 2030"),
        P("urbano", "Construir y rehabilitar pistas, veredas y accesos peatonales y recuperar parques", 29, "Construiremos, rehabilitaremos y mejoraremos pistas, veredas", "100 % de cierre de brechas de infraestructura pública al 2030"),
        P("social", "Casa de la Mujer y la Familia con capacitación técnica, emprendimiento y orientación psicológica", 31, "Crearemos la Casa de la Mujer y la Familia"),
        P("transporte", "Formalizar el transporte menor con rutas, zonas de operación y paraderos autorizados y señalizados", 32, "programa integral de formalización del transporte menor", "85 % de asociaciones de mototaxis formalizadas y 100 % de paraderos autorizados al 2030"),
        P("economia", "Centro de Desarrollo Empresarial y Emprendimiento y Plan de Desarrollo Económico Local", 33, "Implementación del Centro de Desarrollo Empresarial y Emprendimiento", "120 empresas por cada 1 000 habitantes al 2030"),
        P("agua_riesgos", "Obras de mitigación en zonas de riesgo (descolmatación, muros, drenajes), brigadas y simulacros distritales", 35, "zonas de riesgo alto y medio intervenidas", "100 % de zonas de riesgo alto y medio intervenidas al 2030 y 2 simulacros al año"),
        P("ambiente", "Plan de arborización urbana y ampliación de parques y corredores verdes", 36, "plan de arborización urbana", "8,2 m² de área verde por habitante al 2030"),
        P("gestion", "Ordenanza de audiencias públicas semestrales y transmisión en línea de las sesiones de concejo", 37, "audiencias públicas semestrales de rendición de cuentas", "2 audiencias al año"),
    ]),
    ("Carlos Alberto Ysla Durán", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Nuevos puntos de videovigilancia con reconocimiento en accesos y límites, patrullaje integrado con la comisaría y apoyo a juntas vecinales", 6, "Instalar nuevos puntos de videovigilancia equipados con tecnología de reconocimiento"),
        P("social", "Gestionar ante los ministerios más vacantes de Pensión 65, Contigo y Beca 18, y ampliar talleres del CIAM y la OMAPED", 6, "ampliación de vacantes en el distrito (Pensión 65, Contigo, Beca 18)"),
        P("urbano", "Equipo técnico itinerante y asesoría legal gratuita para el saneamiento físico-legal de asentamientos humanos", 7, "Conformar un equipo técnico multidisciplinario itinerante"),
        P("social", "Nuevas disciplinas en las escuelas deportivas, torneos interbarrios y mantenimiento de losas", 7, "Organizar torneos interbarrios periódicos"),
        P("agua_riesgos", "Estudio técnico para una tarifa de agua diferenciada entre consumo residencial y comercial", 8, "nuevo esquema tarifario diferenciado entre consumo residencial y comercial"),
        P("economia", "Plataforma «Emprende Chaclacayo» para licencias automatizadas y línea virtual de formalización", 8, "para trámites automatizados de licencias"),
        P("economia", "Programa «Descubre Chaclacayo»: ferias gastronómicas y artesanales y circuitos turísticos junto al río Rímac", 9, "Organizar ferias gastronómicas y artesanales periódicas"),
        P("agua_riesgos", "Perfiles técnicos para diques y mallas dinámicas en quebradas críticas y descolmatación del Rímac antes de las lluvias", 9, "diques de contención y colocación de mallas dinámicas"),
        P("ambiente", "Programa «Chacla Recicla» con estaciones de reciclaje, campañas puerta a puerta y formalización de recicladores", 10, "Adquirir e instalar estaciones de reciclaje"),
        P("urbano", "Reasfaltado y bacheo continuo de vías locales y red de ecoparaderos con paneles solares", 11, "programa municipal de reasfaltado y bacheo continuo"),
        P("gestion", "Ventanilla Única Virtual y aplicación para reportar incidencias de servicios con geolocalización", 12, "aplicación móvil municipal que permita a los vecinos reportar incidencias"),
    ]),
]
