"""Comas (150110): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150110"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Pierre Orlando Apian Castillo", "Acción Popular", "accion-popular", [
        P("seguridad", "Más serenos y vehículos, y plan preventivo «Vecindario Seguro» con el MININTER y la PNP", 10, "VECINDARIO SEGURO", "Percepción de inseguridad por debajo del 50 % y 50 % menos victimización"),
        P("seguridad", "Cámaras de videovigilancia con identificación facial e inteligencia artificial, y reportes vecinales por WhatsApp y aplicativo", 11, "primera fase de 2,000 cámaras de video vigilancia", "2 000 cámaras en la primera fase"),
        P("social", "Botones de pánico en parques, colegios, mercados y paraderos, y seguimiento de todos los casos de violencia familiar", 12, "botones de pánico físicos en puntos estratégicos", "100 % de casos denunciados con seguimiento y hasta 80 % menos casos de maltrato a la mujer"),
        P("social", "Cunas y guarderías municipales para apoyar a madres trabajadoras", 13, "Crear cunas y guarderías municipales"),
        P("economia", "Bolsa de Trabajo Municipal «Comas Emplea» para insertar jóvenes en el empleo formal", 15, "Incorporar 5,000 jóvenes al mercado laboral", "5 000 jóvenes insertados laboralmente"),
        P("urbano", "Pavimentar y rehabilitar vías priorizadas y mejorar la conectividad entre las zonales", 21, "Pavimentar y/o rehabilitar entre el 60% y 80% de las vías priorizadas", "Entre 60 % y 80 % de las vías priorizadas"),
        P("transporte", "Semaforización inteligente en zonas de alta congestión, paraderos seguros y señalización", 22, "semaforización inteligente en zonas de alta congestión", "30 % menos puntos críticos de congestión"),
        P("economia", "Capacitación técnica certificada y en habilidades digitales con inserción laboral", 24, "Capacitar a más de 10,000 ciudadanos", "Más de 10 000 capacitados y 40 % de inserción laboral"),
        P("ambiente", "Arborización y recuperación de áreas verdes y parques con riego tecnificado", 28, "Plantar y mantener al menos 10,000 árboles", "Al menos 10 000 árboles y 30 % más de cobertura de áreas verdes"),
        P("agua_riesgos", "Sistema distrital de gestión del riesgo de desastres, monitoreo de zonas de riesgo y simulacros anuales", 29, "Implementar sistema GRD al 100% operativo", "30 % menos incidentes por desastres"),
        P("gestion", "Control interno digital, capacitación en ética pública y plataforma «Comas Conectado» de participación", 32, "Capacitar al 100% de funcionarios en ética pública", "100 % de funcionarios capacitados en ética pública"),
    ]),
    ("César Augusto Cosiche Tenorio", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Centro Integral de Seguridad Ciudadana que integre monitoreo inteligente, videovigilancia y patrullaje", 6, "Centro Integral de Seguridad Ciudadana Inversión"),
        P("seguridad", "Red de cámaras inteligentes con reconocimiento facial y lectura de placas", 6, "Red de Cámaras Inteligentes", "1 000 cámaras"),
        P("seguridad", "Serenazgo moderno con equipamiento, vehículos y drones", 6, "Serenazgo Moderno", "Reducir 40 % los delitos denunciados"),
        P("urbano", "Programa «500 Cuadras» de rehabilitación vial y Plan Veredas Seguras", 6, "Programa 500 Cuadras Inversión", "500 cuadras rehabilitadas al 2030"),
        P("urbano", "Iluminación LED en todo el distrito", 7, "Iluminación LED Total", "80 % de vías en buen estado"),
        P("economia", "Centro de Innovación Empresarial, Mercado Digital Comas y Bolsa Laboral Metropolitana", 7, "Centro de Innovación Empresarial", "20 000 empleos promovidos"),
        P("ambiente", "Programa «100 Mil Árboles», recuperación de parques y gestión inteligente de residuos", 7, "Programa 100 Mil Árboles", "40 % más de áreas verdes"),
        P("social", "Hospital Municipal de Atención Primaria con enfoque preventivo", 19, "Objetivo: Atención médica preventiva", "Entre 2028 y 2030"),
        P("social", "Escuelas Municipales Tecnológicas y Centros Integrales para Adultos Mayores", 7, "Escuelas Municipales Tecnológicas", "100 000 beneficiarios directos"),
        P("gestion", "Municipalidad digital y plataforma ciudadana de atención las 24 horas", 8, "Plataforma Ciudadana 24/7", "100 % de trámites digitalizados"),
        P("agua_riesgos", "Escaleras seguras y muros de contención en Collique, junto con parques vecinales", 8, "Escaleras seguras"),
    ]),
    ("Roxana Marylia Ari Acuña", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Centro Metropolitano de Seguridad Inteligente con cámaras con analítica, central única, integración con la PNP, botón de pánico y aplicativo vecinal", 34, "Centro Metropolitano de Seguridad Inteligente de Lima Norte", "Reducir en 40 % los puntos críticos del mapa del delito"),
        P("urbano", "Red de Parques Seguros: recuperación de parques con iluminación LED, videovigilancia y áreas deportivas", 35, "Red de Parques Seguros y Espacios Recuperados"),
        P("social", "Academia popular municipal con becas para alumnos destacados de bajos recursos y acompañamiento psicológico", 34, "Academia popular municipal"),
        P("social", "Complejo deportivo municipal con la reapertura de la piscina municipal y becas para deportistas", 38, "Reapertura de la piscina municipal"),
        P("gestion", "Programa «Comas Digital»: trámites y expedientes digitales, plataforma única de atención, catastro y datos abiertos", 36, "Digitalizar trámites y expedientes municipales"),
        P("economia", "Corredor Económico Trapiche como eje logístico, comercial y gastronómico, articulado con Ancón y Chancay", 36, "Corredor Económico Trapiche como eje estratégico"),
        P("ambiente", "Plan Verde Comas 2030 con más áreas verdes, riego tecnificado con agua tratada y arborización", 36, "Plan Verde Comas 2030 incluirá"),
        P("ambiente", "Modernizar la limpieza pública, intervenir puntos críticos de basura y colocar contenedores soterrados", 31, "contenedores soterrados y sistemas modernos de disposición", "Reducir en 40 % los puntos críticos de acumulación de residuos"),
        P("economia", "Programa de formalización de MYPES y plataforma digital «Chamba es Chamba» para buscar empleo en el distrito", 40, "para buscar empleo dentro del distrito", "En los primeros 100 días de gestión"),
        P("transporte", "Plan Integral de Movilidad Urbana, ordenamiento de paraderos informales y ciclovías progresivas", 40, "Inicio de formulación del Plan Integral de Movilidad Urbana", "Inicio en los primeros 100 días de gestión"),
        P("gestion", "Reportes semestrales de avance, tablero de indicadores y mesas vecinales por zonales", 46, "Publicar reportes semestrales de avance del plan", "Reportes semestrales durante 2027–2030"),
    ]),
    ("Raúl Díaz Pérez", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Cámaras con reconocimiento facial e inteligencia artificial, alarmas inteligentes y retorno del grupo Tucuy Ricuy de inteligencia", 20, "Implementación de 1000 cámaras de video vigilancia", "1 000 cámaras; delitos contra el patrimonio de 8,73 a 2 por cada mil habitantes al 2030"),
        P("seguridad", "Más serenos con camionetas, motos, radios y armas no letales, y ocho centrales de monitoreo", 21, "incremento a 500 serenos", "500 serenos y 8 centrales de monitoreo"),
        P("social", "Farmacias municipales descentralizadas en las zonales", 22, "Farmacias Municipales descentralizadas"),
        P("social", "Academia Municipal Preuniversitaria, Centro de Idiomas y fibra óptica en colegios públicos", 22, "Academia Municipal Pre Universitaria y Centro de Idiomas", "41 % de alumnos de 2.º de secundaria con nivel satisfactorio en lectura al 2030"),
        P("economia", "Plan de Desarrollo Económico Local y campaña masiva de formalización de emprendedores", 23, "Elaboración del Plan de Desarrollo Económico Local", "75 % de cumplimiento del plan al 2030"),
        P("transporte", "Gestionar una vía paralela a la Av. Túpac Amaru en las partes altas, ampliar la Av. Condorcanqui y un puente hacia Puente Piedra", 27, "vía paralela a la avenida Tupac Amaru"),
        P("agua_riesgos", "Brigadas de defensa civil equipadas en las comunidades de riesgo alto", 25, "Conformación de brigadas de defensa civil"),
        P("ambiente", "Compactadoras propias, planta municipal de reciclaje y contenedores soterrados en puntos críticos", 25, "Creación de la planta de reciclaje municipal"),
        P("ambiente", "Catorce Parques de la Familia, corredores verdes y riego con pozos tubulares", 26, "14 Parques de la Familia", "De 2,81 a 2,86 m² de áreas verdes por habitante al 2030"),
        P("urbano", "Planta municipal de concreto o asfalto, programa «bache cero» y escaleras y muros con «Pueblo en Acción»", 27, "planta de producción de concreto"),
        P("gestion", "Plataforma digital de pagos y trámites, Sistema de Integridad Pública y audiencias públicas por zonales", 28, "plataforma digital para pagos y digitalización de trámites", "99 % de ejecución del presupuesto municipal al 2030"),
    ]),
    ("Samuel Horacio Guerrero Castillo", "Fuerza Popular", "fuerza-popular", [
        P("seguridad", "Prevención del delito con cámaras de vigilancia, camionetas de seguridad y centros de videovigilancia", 14, "200 cámaras de vigilancia", "200 cámaras, 15 camionetas y 14 centros de videovigilancia"),
        P("transporte", "Gestionar los estudios del megaproyecto de vía expresa de la Av. Túpac Amaru y semáforos inteligentes con la MML", 14, "Expresa de la Av. Túpac Amaru en todo su recorrido"),
        P("social", "Gestionar con el MINSA la construcción del nuevo Hospital Sergio Bernales", 16, "NUEVO HOSPITAL SERGIO BERNALES", "100 000 pobladores beneficiados"),
        P("social", "Sistema comunitario de vigilancia contra la desnutrición crónica y la anemia para niños de 0 a 5 años", 17, "SISTEMA COMUNITARIO DE VIGILANCIA CONTRA LA DESNUTRICIÓN", "20 000 niños; desnutrición crónica al 1 % y anemia al 5 %"),
        P("social", "Casas de refugio para víctimas de violencia familiar y sexual", 18, "04 casas amigas de refugio", "4 casas de refugio operando"),
        P("economia", "Bolsa laboral municipal para colocar a adolescentes y jóvenes en empleos públicos y privados", 20, "01 bolsa laboral que coloca a 3000 adolescentes", "3 000 jóvenes colocados"),
        P("economia", "Programa «Mi Empresa» para mejorar la gestión de pequeñas y medianas empresas", 21, "programa mi empresa que beneficia a 15000", "15 000 mypes beneficiadas"),
        P("gestion", "Suspender temporalmente el cobro de multas y cobranzas coactivas para revisarlas, y cobrar arbitrios según el servicio prestado", 21, "Suspensión temporal del cobro de multas"),
        P("urbano", "Programa «Viviendas Dignas y Saludables» en las zonas más vulnerables", 22, "VIVIENDA DIGNAS Y SALUDABLES", "30 000 viviendas beneficiadas"),
        P("ambiente", "Flota municipal propia para el recojo de residuos y recuperación de áreas verdes con riego de aguas tratadas", 23, "flota propia para la atención del recojo", "Flota propia al término de la gestión y 25 % de áreas verdes recuperadas el primer año"),
        P("urbano", "Obras de asfaltado y veredas en los pueblos del distrito y concretera municipal", 25, "OBRAS DE ASFALTADO Y VEREDAS", "50 % de las necesidades de asfaltado cubiertas"),
    ]),
    ("Nicolás Octavio Kusunoki Fuero", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Modernizar el Centro de Seguridad Inteligente y colocar cámaras en mercados, colegios, avenidas, parques y paraderos", 2, "Modernizar el Centro de Seguridad Inteligente de Comas"),
        P("social", "Programa «Comas sin Dengue» y Centro Municipal de Prevención y Tratamiento Oncológico y Telesalud", 3, "Implementar el programa Comas sin Dengue"),
        P("social", "Casas de Día para el Adulto Mayor y red «Comas te Acompaña» contra el abandono y la violencia", 3, "Implementar Casas de Día para el Adulto Mayor"),
        P("social", "Convertir locales comunales en «Casas de Barrio Inteligentes» con talleres, deporte y Liga Barrial", 4, "Casas de Barrio Inteligentes"),
        P("ambiente", "Programa «Comas Esteriliza», DNI Mascotero Comeño, adopciones y brigada contra el maltrato animal", 4, "Crear DNI Mascotero Comeño"),
        P("economia", "Escuela Municipal de Oficios, Tecnología y Empleo con cursos técnicos y digitales", 5, "Crear la Escuela Municipal de Oficios"),
        P("economia", "Licencia Rápida para negocios de bajo riesgo y Ventanilla Única del Emprendedor", 6, "Implementar Licencia Rápida para negocios de bajo riesgo"),
        P("ambiente", "Programa «Comas Limpio 360»: recojo por zonales con horarios fijos, GPS en compactadoras y compostaje", 7, "Instalar GPS en compactadoras"),
        P("ambiente", "Parque Lineal Río Chillón con limpieza de riberas, fiscalización de vertimientos y defensa ribereña coordinada", 8, "Impulsar el Parque Lineal Río Chillón"),
        P("urbano", "Pistas, veredas, rampas, escaleras y muros de contención priorizando zonas altas, con cuadrillas de mantenimiento rápido", 9, "Crear cuadrillas de mantenimiento rápido"),
        P("gestion", "Semáforo Digital de Obras que publique presupuesto, contratista, plazo, avance y fotografías de cada obra", 11, "Implementar Semáforo Digital de Obras"),
    ]),
    ("Javier Sosimo Carrasco Condori", "Partido de los Trabajadores y Emprendedores PTE Perú", "partido-de-los-trabajadores-y-emprendedores-pte-peru-comunidad-politica-inka-peru", [
        P("social", "Estudios técnicos y económicos con la Municipalidad de Lima para construir el estadio municipal Daniel Hernani Tovar", 1, "realizará los estudios técnicos y económicos para realizar su construcción"),
        P("seguridad", "Operativos y clausura de locales con licencia de bar que funcionan como prostíbulos", 2, "clausuras y tapiados de estos locales"),
        P("ambiente", "Limpieza pública administrada directamente por la municipalidad con unidades propias", 3, "servicio de limpieza sea administrado directamente por la municipalidad", "90 rutas con S/ 30 millones en cuatro años"),
        P("urbano", "Maquinaria semipesada municipal para mantenimiento y pavimentación de calles, pistas y veredas", 3, "pull de maquinarias semi pesadas"),
        P("economia", "Fondo rotatorio con tasas preferenciales para micro y pequeños empresarios", 4, "fondo rotatorio se iniciara con un monto de 100000 dólares", "Fondo inicial de 100 000 dólares"),
        P("economia", "Apoyo técnico y financiero para formalizar y reubicar el comercio ambulatorio en zonas y horarios adecuados", 4, "formalización en un 50% en los cuatro años", "50 % formalizado en cuatro años"),
        P("seguridad", "Cámaras y drones en puntos críticos y patrullaje mixto de serenazgo y Policía", 5, "Se instalarán cámaras y drones de alta tecnología"),
        P("social", "Becas y semibecas para institutos y universidades, y bibliotecas comunales digitales", 7, "más de 100 becas y semi-becas educativas", "Más de 100 becas y semibecas"),
        P("social", "Casa del adulto mayor, de la mujer y del niño en un mismo complejo", 8, "implementar la casa del adulto mayor, el de la mujer y el niño en un mismo complejo"),
        P("transporte", "Ordenar el servicio de mototaxis definiendo áreas, número de unidades y autorizaciones", 9, "Definir las áreas donde se prestará el servicio de transporte de mototaxis"),
        P("agua_riesgos", "Muros de contención y vegetación en las laderas, y gestión de terrenos del Estado para viviendas en zonas seguras", 9, "Proponemos la construcción de muros de contención"),
    ]),
    ("Ana Yuriko Niño de Guzmán Tengan", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Más serenos en las 14 zonales con la PNP y programa «Serenazgo Sin Fronteras» con la Mancomunidad de Lima Norte", 15, "Serenazgo Sin Fronteras"),
        P("seguridad", "Interconectar por fibra óptica cámaras privadas y vecinales, y gestionar cámaras con reconocimiento facial", 16, "Interconexión de cámaras con fibra óptica"),
        P("social", "Gestionar la construcción de un Hospital Municipal con tarifas de costo social", 18, "Gestionar la Construcción del Hospital Municipal"),
        P("social", "Casa Refugio para niños, adolescentes y mujeres en situación de violencia, coordinada con el MIMP", 19, "Casa Refugio para Niños, Adolescentes y Mujeres"),
        P("social", "Gestionar ante el MEF más presupuesto para el Vaso de Leche y elevar el monto por ración", 23, "se eleve la ración a 0.70 céntimos", "Ración de 0,70 céntimos (hoy 0,30)"),
        P("economia", "Ventanilla Única Empresarial VUE-Comas presencial y virtual, con convenios con PRODUCE y SUNAT", 29, "VUE-COMAS VENTANILLA UNICA EMPRESARIAL"),
        P("transporte", "Cuerpo de inspectores de transporte con la MML y la PNP, y pedir la nulidad de la ordenanza de estacionamiento 602-2021", 32, "Conformar el Cuerpo de Inspectores de transporte"),
        P("ambiente", "Comprar compactadoras para reducir la tercerización del recojo de residuos", 35, "ADQUISICIÓN DE 10 COMPACTADORAS", "10 compactadoras y recojo municipal del 30 % al 50 %"),
        P("agua_riesgos", "Plantas de tratamiento de aguas residuales en las zonales 1 a 5 y reservorios sumergidos para regar parques", 37, "plantas de tratamiento de aguas residuales en las zonales 1"),
        P("agua_riesgos", "Centro de Operaciones de Emergencia Distrital, alerta temprana con INDECI y formación de brigadistas", 42, "Centro De Operaciones De Emergencia Distrital se construirá", "Monitoreo las 24 horas, los 365 días"),
        P("gestion", "Defensoría del Vecino para recibir quejas y denuncias de abusos en la atención municipal", 41, "Crearemos la Defensoría del Vecino"),
    ]),
    ("Josmell Max Peralta Peña", "Partido Morado", "partido-morado", [
        P("seguridad", "Programa «Comas Seguro e Inteligente»: integrar cámaras privadas, comerciales y vecinales a la Central de Monitoreo y coordinar con la PNP y juntas vecinales", 8, "Comas Seguro e Inteligente", "1 000 cámaras integradas entre municipales y vecinales"),
        P("seguridad", "Dirigentes de las 14 zonales validan el cumplimiento de las rutas de patrullaje del serenazgo en puntos de control vecinal", 8, "Control Vecinal del Patrullaje", "Las 14 zonales integradas al sistema de supervisión vecinal del serenazgo"),
        P("social", "Supervisión de los programas alimentarios con auditorías, padrones digitales y renovación democrática de dirigentes de comedores y Vaso de Leche", 9, "Transparencia y Modernización de los Programas Alimentarios", "100 % de organizaciones alimentarias supervisadas cada año, con padrones digitalizados"),
        P("social", "Academia municipal gratuita para que jóvenes de escasos recursos postulen a universidades públicas como la UNI y San Marcos", 11, "Academia Municipal de Oportunidades", "200 estudiantes capacitados"),
        P("urbano", "Mejorar losas deportivas con malla raschel e iluminación LED y construir nuevas losas multideportivas en sectores con déficit", 12, "Programa de Mejoramiento de Losas Deportivas", "50 losas mejoradas y 20 nuevas losas multideportivas"),
        P("urbano", "Construir el Mirador de Comas en la Huaca Collique Bajo II y recuperar la Muralla de Tungasuca como circuito turístico y cultural", 13, "Mirador de Comas", "Mirador construido y Muralla de Tungasuca recuperada"),
        P("economia", "Notificación preventiva: los pequeños negocios reciben orientación y plazo para corregir observaciones antes de ser sancionados", 16, "Notificación Preventiva Empresarial", "80 % de observaciones corregidas sin procedimiento sancionador"),
        P("economia", "Programa «Comas Startup» con capacitación, mentoría, asesoría legal y tributaria, y orientación para acceder a financiamiento", 16, "Comas Startup", "2 000 emprendedores capacitados y asesorados"),
        P("ambiente", "Recuperar el entorno del río Chillón con arborización, limpieza y corredores verdes", 18, "Recuperación Ambiental del Río Chillón", "10 000 árboles plantados"),
        P("ambiente", "Planta municipal de compostaje con residuos orgánicos de mercados y áreas verdes, para abonar parques y jardines", 19, "Planta Municipal de Compostaje", "Aprovechar al menos el 50 % de los residuos orgánicos de los mercados incorporados"),
        P("gestion", "Plataforma de Gobierno Abierto con información sobre obras, presupuesto, contrataciones, licencias y cumplimiento de metas", 20, "Gobierno Abierto Comas", "100 % de la información obligatoria y estratégica en formato abierto"),
    ]),
    ("Óscar Alfredo Quevedo Pérez", "Perú Acción", "partido-politico-peru-accion", [
        P("seguridad", "Reorganizar el serenazgo para apoyar a la PNP, con patrullaje a pie, vehicular y en moto por cuadrantes", 10, "Patrullaje de serenazgo a pie, vehicular y en moto por cuadrantes"),
        P("seguridad", "Instalar videovigilancia con identificación facial y descentralizar las casetas de seguridad", 10, "Instalación de video Vigilancia con identificación facial"),
        P("seguridad", "Presentar un proyecto de ley para que los locales comerciales tengan seguridad obligatoria y sus dueños puedan portar armas frente a extorsionadores", 10, "Formular Proyecto de Ley a fin de los locales comerciales"),
        P("social", "Reactivar los comedores populares y crear un albergue para adultos mayores en situación de necesidad", 11, "Se reactivará los Comedores Populares"),
        P("social", "Aplicar en postas y policlínicos el modelo de atención primaria de Singapur, con quirófanos para operaciones menores y emergencias", 11, "el modelo del sistema de la salud de Singapur", "Atención hasta 18 horas al día"),
        P("social", "Becas en academias preuniversitarias para estudiantes de quinto de secundaria", 11, "dar beca a nuestros estudiantes de 5to de secundaria"),
        P("urbano", "Obras de transitabilidad vehicular y peatonal en asentamientos humanos y remodelación de parques, ejecutando primero las que ya tienen perfil y código", 12, "Se seleccionará en el primer año las obra", "Selección de obras con perfil y código único en el primer año"),
        P("economia", "Licencias de funcionamiento inmediatas y automáticas, y donación de carros desayuneros y mototaxis en asentamientos humanos", 12, "Licencias inmediatas y automáticas a negocios"),
        P("agua_riesgos", "Impulsar el Cuarto Esquema de agua: actualizar planos, levantar observaciones del Ministerio de Vivienda y buscar presupuesto para ejecutarlo por tramos", 15, "CUARTO ESQUEMA DE AGUA"),
        P("ambiente", "Regar parques con agua de plantas de tratamiento, mejorar el recojo de basura y aplicar el programa «Recicla»", 13, "Regado de parques y jardines a través de la construcción de plantas de tratamiento"),
        P("gestion", "Peritaje contable de la gestión anterior, revisión de contratos y reorganización del personal municipal", 14, "Realizar un peritaje contable de la administración anterior"),
    ]),
    ("Rosa Lidia Corzo Saldarriaga", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Centro Inteligente de Monitoreo y Respuesta Inmediata conectado con PNP, Bomberos y SAMU, con analítica de video y mapa del delito", 38, "Centro Inteligente de Monitoreo y Respuesta Inmediata"),
        P("seguridad", "Programa «Comas Seguro 24 Horas»: reincorporar las unidades de serenazgo fuera de servicio y mejorar equipamiento y comunicaciones", 38, "Comas Seguro 24 Horas"),
        P("social", "Programa «Comas te Escucha»: espacios de orientación emocional con el MINSA, escuelas para padres y prevención del bullying y las drogas", 18, "Comas te Escucha"),
        P("social", "Programa contra la tuberculosis: entrega oportuna de canastas PANTBC, mesa multisectorial y apoyo psicológico a pacientes y familias", 25, "Comas Libre de Tuberculosis"),
        P("social", "Puntos de estabilización y primeros auxilios en las zonas altas, articulados con el SAMU", 23, "puntos de estabilización y primeros auxilios"),
        P("urbano", "Recuperar veredas invadidas por rejas y mejorar la accesibilidad para personas con discapacidad en las zonas altas", 25, "Recuperación de veredas invadidas por rejas"),
        P("transporte", "Programa «Comas se Mueve con Orden»: ordenar y formalizar mototaxis, nuevo plan regulador y paraderos señalizados", 44, "Comas se Mueve con Orden"),
        P("transporte", "Programa «Comas Pedalea» con nuevas ciclovías en avenidas principales y estacionamientos para bicicletas", 70, "Comas Pedalea"),
        P("agua_riesgos", "Programa «Comas Resiliente y Preparado»: muros de contención, drenajes pluviales, defensas ribereñas en el Chillón y alerta temprana", 51, "Comas Resiliente y Preparado"),
        P("ambiente", "Recuperar parques con riego tecnificado, arborización y el programa «Adopta un Parque» con empresas y vecinos", 53, "Adopta un Parque"),
        P("gestion", "Programa «Ciudadano Fiscalizador» para vigilar obras y publicación de adicionales y ampliaciones de plazo", 66, "Ciudadano Fiscalizador"),
    ]),
    ("Juan Carlos Condori Chávez", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Observatorio de seguridad con mapa de calor y reorganización del serenazgo por zonas, con más unidades motorizadas", 1, "Reingeniería integral y zonificación estratégica del Serenazgo"),
        P("social", "Supervisar y facilitar la culminación y puesta en marcha del nuevo Hospital Sergio Bernales en Collique", 2, "Nuevo Hospital Sergio Bernales"),
        P("social", "Campañas de vacunación y prevención con el MINSA en todos los sectores del distrito", 2, "campañas de vacunación y control de epidemias", "Programas de prevención y salud comunitaria en el 100 % de los sectores"),
        P("social", "Equipar el Instituto Tecnológico Carlos Cueto Fernandini y crear módulos educativos y culturales itinerantes", 2, "Instituto Tecnológico Carlos Cueto Fernandini"),
        P("economia", "Reactivar el Consejo de Desarrollo Económico (CODEC) y crear una escuela municipal de formación técnico-empresarial", 3, "Escuela Municipal de Formación Técnico-Empresarial"),
        P("economia", "Habilitar un parque industrial descentralizado y un programa juvenil de emprendimiento con fondos semilla", 4, "Parque Industrial Descentralizado de Comas"),
        P("agua_riesgos", "Oficina de asesoramiento gratuito para elaborar expedientes de ampliación de redes de agua y desagüe", 4, "Oficina Técnica de Asesoramiento Gratuito", "Cobertura masiva de redes de agua hacia el 2030"),
        P("ambiente", "Flota municipal de camiones compactadores para que el recojo de basura sea de administración directa, en tres turnos", 5, "moderna flota de camiones compactadores", "Sistema de limpieza pública autónomo al 100 % en 2028"),
        P("urbano", "Oficina municipal para el levantamiento catastral y la titulación masiva de predios ante COFOPRI", 5, "levantamiento técnico-catastral", "Formalizar y reducir al 70 % los terrenos informales"),
        P("transporte", "Plan de reordenamiento integral del transporte local de vehículos menores", 6, "Reordenamiento Integral del Sistema de Transporte Local"),
        P("gestion", "Central de atención telefónica con inteligencia artificial, trámites digitales y licitaciones en actos públicos abiertos", 6, "Call Center interactivo"),
    ]),
    ("Nerio Wilson Sánchez Quiroz", "Perú Moderno", "peru-moderno", [
        P("seguridad", "Seguridad con participación vecinal: comités de seguridad activos y casetas de serenazgo en cada zonal", 6, "50 comités activos; 2 casetas por zonal", "Reducir delitos en 40 %, 50 comités activos y 2 casetas por zonal"),
        P("social", "Erradicar la desnutrición crónica infantil en el distrito", 6, "Reducir desnutrición crónica a menos de 5%", "Desnutrición crónica por debajo del 5 %"),
        P("social", "Prevenir la violencia familiar y sexual y atender todas las denuncias", 6, "50% de reducción de casos", "50 % menos casos"),
        P("urbano", "Regularizar la tierra y ordenar el territorio con un Plan de Desarrollo Urbano", 7, "Regularizar la tierra y ordenar el territorio", "500 hectáreas regularizadas y plan vigente"),
        P("agua_riesgos", "Obras de mitigación y atención a familias reubicadas para reducir el riesgo de desastres", 7, "Proteger a las familias comeñas del riesgo de desastres", "20 obras y 1 000 familias atendidas"),
        P("economia", "Caja Municipal de Ahorro y Crédito y formalización de micro y pequeñas empresas", 8, "2,000 MYPES formalizadas; S/ 10 millones en créditos otorgados", "2 000 MYPES formalizadas y S/ 10 millones en créditos"),
        P("economia", "Construir mercados y reubicar en ellos al comercio ambulante", 8, "5 mercados nuevos; 3,000 comerciantes reubicados", "5 mercados nuevos y 3 000 comerciantes reubicados"),
        P("transporte", "Rehabilitar pistas para el comercio y la movilidad", 9, "Rehabilitar vías para el comercio y la movilidad productiva", "200 km rehabilitados y 90 % de vías en buen estado"),
        P("ambiente", "Plantar árboles y fiscalizar fuentes de contaminación para mejorar la calidad del aire", 9, "Reducir contaminación en 25%; 100,000 árboles plantados", "100 000 árboles y 25 % menos contaminación"),
        P("ambiente", "Proteger las Lomas de Collique frente a invasiones y tráfico de terrenos", 10, "Proteger las Lomas de Collique como patrimonio natural del distrito", "100 % de invasiones desalojadas y 100 % de denuncias atendidas"),
        P("gestion", "Digitalizar todos los trámites municipales", 10, "100% de trámites digitales; 80% de satisfacción", "100 % de trámites digitales y 80 % de satisfacción ciudadana"),
    ]),
    ("Carmen Mónica Acuña Jara", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Red de cámaras con inteligencia artificial, reconocimiento de rostros y lectura de placas, y tótems con botón de pánico en paraderos", 9, "Escudo Tecnológico Inteligente"),
        P("seguridad", "Centrales de monitoreo zonales y patrullaje integrado con la PNP en las 14 zonales, coordinado con distritos vecinos", 9, "4 Centrales de Monitoreo Zonales", "4 centrales de monitoreo zonales"),
        P("agua_riesgos", "Programa «Muros y Escaleras de Vida»: muros de contención y escaleras con barandas e iluminación solar en laderas", 10, "Muros y Escaleras de Vida"),
        P("social", "Programa «Comas Sin Anemia» con ollas comunes y comedores, tamizajes y suplementos; CIAM y casas de la juventud descentralizadas", 10, "Comas Sin Anemia"),
        P("social", "Reactivar la OMAPED y crear centros de terapia física y psicológica para personas con discapacidad y autismo", 10, "Reactivar la OMAPED"),
        P("economia", "Licencias de funcionamiento por plataforma digital para actividades de bajo y mediano riesgo", 10, "Licencia Express", "Licencias en un plazo máximo de 24 horas"),
        P("ambiente", "Recojo de basura con rutas monitoreadas por GPS, contenedores soterrados y sanciones a quien arroje desmonte en laderas", 11, "Optimización e Industrialización del Recojo de Residuos"),
        P("ambiente", "Recuperar las áreas verdes de avenidas principales con riego por goteo y aguas tratadas", 11, "Plan Verde y Riego Sostenible"),
        P("transporte", "Plan vial «Comas Fluye»: bacheo, pavimentación y señalización en vías internas y paraderos autorizados de mototaxis", 11, "Comas Fluye"),
        P("gestion", "Plataforma «Municipio Digital» para pagos, trámites y denuncias desde una aplicación móvil", 12, "Municipio Digital", "90 % de los trámites y consultas digitalizados"),
        P("gestion", "Oficina anticorrupción con denuncias anónimas y publicación mensual de estados financieros y gastos de obras", 12, "Oficina Anticorrupción y Auditoría Ciudadana"),
    ]),
    ("Victoria Villanueva Quiñones", "Progresemos", "progresemos", [
        P("seguridad", "Centro de control y comando con inteligencia artificial para reconocer placas y rostros de personas con requisitoria", 22, "Centro de Control y Comando Distrital con inteligencia artificial", "Centro operativo en 2028; victimización del 35 % al 20 %"),
        P("seguridad", "Escuela municipal de serenazgo y más serenos, patrulleros y motos en 20 cuadrantes conectados a las comisarías", 23, "Reclutaremos 1000 Serenos para el año 2030", "1 000 serenos al 2030; 50 patrulleros y 50 motos"),
        P("social", "Programa para madres solteras en situación vulnerable: guardería municipal, bolsa de trabajo con horario flexible y talleres", 25, "Guardería Municipal"),
        P("social", "Campañas médicas itinerantes y programa contra la anemia infantil", 25, "Campañas Médicas Itinerantes", "100 campañas y 40 000 atenciones al año; anemia de 28 % a 15 %"),
        P("social", "Programa «Comas Estudia y Emprende» con becas técnicas en alianza con SENATI, institutos y universidades", 25, "Comas Estudia y Emprende", "3 000 becas técnicas"),
        P("urbano", "Centros juveniles deportivos: nuevos complejos deportivos y rehabilitación de losas", 25, "Construcción de 10 complejos deportivos", "10 complejos deportivos y 50 losas rehabilitadas"),
        P("economia", "Parque industrial ligero para micro y pequeñas empresas", 26, "Parque Industrial Ligero", "20 hectáreas y 3 000 empleos directos"),
        P("economia", "Fondo rotatorio municipal con créditos blandos para pequeñas empresas", 26, "Fondo Rotatorio Municipal", "S/ 20 millones iniciales; créditos al 8–12 %"),
        P("ambiente", "Reforestar laderas y crear un parque ecológico de lomas", 26, "Reforestación de Laderas", "120 hectáreas y 100 000 árboles plantados"),
        P("gestion", "Digitalización total de trámites con firma digital", 26, "100% trámites online", "100 % de trámites en línea y 60 % menos tiempo de trámite"),
        P("gestion", "Actualización catastral georreferenciada y sistema tributario digital con pago en línea", 27, "100% predios georreferenciados", "100 % de predios georreferenciados; recaudación predial +60 %"),
    ]),
    ("Jean Pool Granados Lazo", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Sistema de Seguridad Ciudadana Integral y Tecnológica (SISECIT) que integre a todos los sectores del distrito", 18, "Sistema de Seguridad Ciudadana Integral y Tecnológica", "100 % de los sectores integrados al SISECIT"),
        P("seguridad", "Repotenciar el PARMET e instalar cámaras de videovigilancia en los puntos críticos del mapa del delito", 19, "Repotenciar el PARMET e instalar cámaras", "Videovigilancia en el 100 % de los puntos críticos identificados"),
        P("economia", "Terminal Pesquero de Comas en alianza con el sector privado", 20, "implementación del Terminal Pesquero de Comas", "Atender a más de 10 000 familias por mes"),
        P("economia", "Proyecto «Licencias de Funcionamiento al Toque» para negocios de bajo riesgo", 21, "Licencias de Funcionamiento al Toque", "Licencias en máximo 48 horas para actividades de bajo riesgo"),
        P("social", "Academia premilitar y preuniversitaria municipal para jóvenes", 21, "Academia Pre Militar y Pre Universitaria", "5 000 jóvenes beneficiados"),
        P("social", "Centro municipal de salud CEMA SALUD", 25, "Centro Municipal CEMA SALUD", "1 centro con 100 000 atenciones anuales"),
        P("urbano", "Titulación y saneamiento físico legal de predios", 23, "Titulación y Saneamiento Físico Legal", "10 000 familias con saneamiento físico legal culminado"),
        P("transporte", "Construir y mejorar vías, veredas y escaleras con criterios de accesibilidad", 23, "Sistema Vial y Accesibilidad para Todos", "100 km de vías, veredas y escaleras"),
        P("agua_riesgos", "Formar brigadas comunitarias de Defensa Civil y elaborar el mapa de riesgos del distrito", 24, "Formación de Brigadas de Defensa Civil", "200 brigadas comunitarias capacitadas"),
        P("ambiente", "Planta de tratamiento y valorización de residuos sólidos", 24, "Planta de Tratamiento y Valorización de Residuos Sólidos", "1 planta operativa y valorización del 40 % de los residuos reciclables"),
        P("gestion", "Plan de gobierno electrónico con plataforma de trámites en línea", 27, "Plan Estratégico de Gobierno Electrónico", "80 % de los trámites municipales disponibles en línea"),
    ]),
]
