"""Carabayllo (150106): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150106"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Carlos Faustino Núñez Calderón", "Acción Popular", "accion-popular", [
        P("seguridad", "Plan «Escudo Carabayllo 360°»: Centro Integrado de Seguridad Ciudadana, más videovigilancia, drones, serenazgo por zonas y patrullaje integrado con la PNP", 28, "Centro Integrado de Seguridad Ciudadana (CISC)"),
        P("social", "Programa «Salud Cerca de Ti» con clínica rodante municipal, campañas médicas descentralizadas y salud escolar", 28, "Clínica Rodante Municipal"),
        P("social", "Farmacia Solidaria Municipal con medicamentos esenciales a precios sociales y farmacia itinerante para zonas alejadas", 29, "Medicamentos esenciales a precios sociales"),
        P("transporte", "Programa «Mototaxi Seguro y Formal»: escuela del transportista, formalización, paraderos georreferenciados y red contra la extorsión", 34, "Paraderos ordenados y georreferenciados"),
        P("economia", "Programa «Carabayllo Emprende» con Centro Municipal del Emprendedor, asistencia técnica y ferias de negocios", 35, "Centro Municipal del Emprendedor"),
        P("urbano", "Programa «Carabayllo Propietario»: oficina de formalización, convenio con COFOPRI y brigadas zonales de titulación", 44, "Brigadas Zonales de Formalización"),
        P("urbano", "Programa «Carabayllo Sin Polvo» de pistas y veredas en sectores que aún no las tienen", 45, "Carabayllo Sin Polvo"),
        P("agua_riesgos", "Programa «Agua para Todos»: mesa permanente del agua y gestión ante Sedapal priorizando zonas altas", 45, "Mesa Permanente del Agua"),
        P("agua_riesgos", "Muros de contención, protección de taludes, drenaje pluvial y actualización del mapa distrital de riesgos", 46, "Actualización del Mapa Distrital de Riesgos"),
        P("ambiente", "«Red EcoCarabayllo»: centros de acopio zonales, planta de compactación, bono por reciclar y formalización de recicladores", 47, "Centros de Acopio Zonales"),
        P("gestion", "Programa «Carabayllo Digital» con mesa de partes virtual, seguimiento de expedientes y aplicación municipal", 53, "Seguimiento digital de expedientes"),
    ]),
    ("Ignacio Jorge Sebastián Távara Arroyo", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Nuevas cámaras con reconocimiento facial y de placas en los accesos al distrito y dos minicentrales de monitoreo en Lomas y El Progreso", 5, "600 nuevas cámaras de videovigilancia", "600 cámaras nuevas"),
        P("seguridad", "Serenazgo por cuadrantes con más agentes, convenios de persecución con Comas y Puente Piedra y patrullaje con la PNP", 6, "Serenazgo Sin Fronteras", "800 agentes y 60 % de camionetas con patrullaje integrado"),
        P("transporte", "Programa «Pavimento Barrial» de asfaltado de vías en Torre Blanca, San Benito y Lomas, y gestión de semáforos en la Av. Túpac Amaru", 7, "asfaltado de 40 kilómetros de vías colectoras", "40 km de vías asfaltadas"),
        P("urbano", "Escaleras con pasamanos e iluminación solar y muros de contención en laderas de alto riesgo", 7, "150 escaleras solidarias", "150 escaleras y 120 muros de contención"),
        P("agua_riesgos", "Equipo técnico gratuito para que los asentamientos obtengan constancias de posesión y se destraben los proyectos de agua de Sedapal", 7, "Equipo Técnico de Apoyo a la Formalización de Saneamiento"),
        P("agua_riesgos", "Mapa de riesgos actualizado, sirenas de alerta temprana en quebradas y simulacros con brigadas vecinales", 9, "sistemas comunitarios de alerta temprana"),
        P("social", "Promotoras de salud municipales para detectar anemia casa por casa y entregar suplementos de hierro", 8, "150 promotoras de salud municipales", "150 promotoras; anemia en sectores vulnerables de 41,2 % a 16 % al 2031"),
        P("social", "Equipar ollas comunes y comedores con cocinas industriales y gas a tarifa social, con padrón digital", 8, "equipar a las 180 ollas comunes", "180 ollas comunes y comedores equipados"),
        P("social", "Dos policlínicos municipales de atención rápida y un centro municipal de atención psicológica", 8, "2 Policlínicos Municipales de atención rápida", "2 policlínicos municipales"),
        P("ambiente", "«Cinturón Verde de Carabayllo» con árboles nativos regados con agua tratada y fiscalización del arrojo de desmonte en el Chillón", 9, "Cinturón Verde de Carabayllo", "15 000 árboles"),
        P("economia", "Licencias de funcionamiento y certificados ITSE virtuales para comercios de riesgo bajo y medio", 9, "Formalización Fácil y Licencias en 24 Horas", "Licencias en máximo 24 horas"),
    ]),
    ("Juan Ladislao Espinoza Ortiz", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("social", "Unidades móviles materno-infantiles en Lomas, San Benito y Torre Blanca y programa «Carabayllo Crece Sano» contra la anemia", 9, "6 Unidades Móviles Materno-Infantiles", "6 módulos itinerantes al 2028 y anemia infantil reducida en 30 % al 2030"),
        P("seguridad", "Central de monitoreo con cámaras con reconocimiento facial en puntos críticos como Chimpu Ocllo y Universitaria", 11, "300 cámaras al 2029", "300 cámaras al 2029"),
        P("seguridad", "Más serenos, vehículos y motos, con turnos 24/7 por cuadrantes", 11, "mínimo 600 serenos al 2028", "600 serenos al 2028"),
        P("seguridad", "Reactivar y equipar las juntas vecinales y lanzar la app «Vecino Seguro Carabayllo» con respuesta en menos de 10 minutos", 12, "100 juntas vecinales activas y acreditadas al 2028", "100 juntas vecinales activas al 2028"),
        P("urbano", "Plan de formalización con COFOPRI y SUNARP para acelerar la titulación de predios", 13, "Plan Integral de Formalización en coordinación con COFOPRI", "2 000 predios titulados al 2028"),
        P("agua_riesgos", "Supervisar la continuidad del Esquema Integral Carabayllo de agua y alcantarillado", 13, "12,000 nuevas conexiones domiciliarias", "Más de 12 000 nuevas conexiones de agua potable"),
        P("urbano", "Pavimentar vías de acceso, veredas y escaleras en asentamientos humanos y zonas vulnerables", 14, "50 km de pistas y veredas", "50 km de pistas y veredas al 2030"),
        P("transporte", "Formalizar y ordenar las rutas de mototaxis con paraderos señalizados y capacitación en seguridad vial", 18, "formalizar y ordenar las rutas de mototaxis"),
        P("economia", "Ferias laborales con el Ministerio de Trabajo y asesoría gratuita para formalizar microempresas", 16, "500 MYPEs formalizadas por año al 2028", "12 ferias laborales al año y 500 MYPE formalizadas por año"),
        P("agua_riesgos", "Plan distrital de gestión del riesgo con alerta temprana y obras de estabilización de taludes", 19, "Meta: 10 obras al 2030", "10 obras de mitigación al 2030"),
        P("gestion", "Plataforma de gobierno digital con trámites y pagos en línea y portal de transparencia en datos abiertos", 20, "80% de trámites municipales disponibles en línea al 2029", "80 % de trámites en línea al 2029"),
    ]),
    ("Joe Peter Robles Escobedo", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Gestionar ante el Mininter una base central de patrullaje motorizado tipo «Halcones» articulada con serenazgo y cámaras", 22, "Base Central de Patrullaje Integrado"),
        P("seguridad", "Equipar al serenazgo y aumentar los operativos conjuntos con la PNP y las juntas vecinales", 14, "Serenos equipados hacia 400", "400 serenos equipados y 40 operativos con la PNP al 2030"),
        P("social", "Clínica municipal de bajo costo con atención preventiva, laboratorio y farmacia accesible, mediante convenios", 23, "Clínica Municipal de Bajo Costo y Salud Preventiva"),
        P("social", "Mantenimiento de los entornos y accesos a los colegios y gestión de mejoras de infraestructura ante el sector Educación", 14, "Mantenimiento de entornos y vías de acceso a las IIEE", "100 % de colegios o entornos con apoyo municipal al 2030"),
        P("economia", "Gran Centro Tecnológico Industrial para formación técnica y certificación laboral en matricería, automatización y mecánica", 23, "Gran Centro Tecnológico Industrial de Carabayllo"),
        P("economia", "Gestionar un parque industrial para atraer inversión y formalizar a micro y pequeñas empresas", 24, "Parque Industrial para Carabayllo"),
        P("economia", "Ruta turística y puesta en valor del patrimonio del valle del Chillón", 17, "Poner en valor el patrimonio y desarrollar circuitos turísticos locales", "70 % de recursos turísticos operativos al 2030"),
        P("transporte", "Pistas, veredas, accesos peatonales y señalización en vías locales como Ampliación Juan Pablo II y Casa Huerta", 18, "Ampliación Juan Pablo II, Casa Huerta"),
        P("urbano", "Saneamiento físico legal de predios y control de la ocupación informal en zonas de riesgo", 18, "Ordenar la expansión urbana y promover el saneamiento físico legal", "65 % de predios saneados al 2030"),
        P("ambiente", "Atención de puntos críticos de basura, segregación y reciclaje, arborización y limpieza de calles", 19, "segregación y valorización de residuos; arborización", "30 % de reciclaje de inorgánicos y 8 500 árboles al 2030"),
        P("gestion", "Tablero público de metas con reportes y audiencias de rendición de cuentas", 21, "Tablero público de metas y, como mínimo, cuatro reportes", "Al menos 4 reportes y audiencias al año"),
    ]),
    ("Héctor Manuel Cochón Barrientos", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("social", "Programa «Cunas sin Anemia»: padrón de menores de 3 años, agentes comunitarios, visitas domiciliarias y alimentos ricos en hierro", 10, "Cunas sin Anemia", "Anemia infantil de alrededor de 40 % a 10 % al 2030"),
        P("social", "Comisión técnica y mesas con MINSA y MEF para sanear el terreno e iniciar el hospital del distrito", 10, "Lograr el 100% del saneamiento legal del terreno", "Terreno saneado e inicio de obras antes del tercer año de gestión"),
        P("social", "Academia municipal preuniversitaria gratuita, prevención del embarazo adolescente y becas con empresas e institutos", 11, "Crear la academia municipal", "Más de 2 000 jóvenes al año y tránsito a educación superior de 25 % a 45 %"),
        P("social", "Programa «Proteína para el Progreso» para ollas comunes y comedores, biohuertos y padrón digital del Vaso de Leche", 11, "Abastecer al 100% de las 130 ollas comunes", "100 % de las 130 ollas comunes con insumos proteicos mensuales"),
        P("seguridad", "Programa «Ojos y Oídos de Carabayllo»: más cámaras, flota renovada, drones y red de alerta para mujeres", 12, "ampliar de 72 a 300 cámaras", "35 % menos robos, de 72 a 300 cámaras y respuesta en menos de 7 minutos"),
        P("agua_riesgos", "Oficina para destrabar saneamiento, visación de planos, cisternas supervisadas y muros de contención", 12, "Elevar agua por red a 75%", "Agua por red al 75 %, alcantarillado al 70 % y 50 muros de contención"),
        P("urbano", "Programa «Mi Losa de Primera»: refaccionar losas deportivas, eliminar cobros informales e iluminarlas con LED", 12, "Mi Losa de Primera", "100 % de losas en deterioro severo refaccionadas"),
        P("ambiente", "Servicio municipal directo de limpieza con flota propia y plan para erradicar puntos críticos", 13, "Crear el Servicio Municipal Directo de Limpieza Pública", "100 % del recojo a cargo de la municipalidad y basurales históricos eliminados al 2030"),
        P("ambiente", "Recojo con motofurgones y contenedores herméticos en laderas y calles estrechas", 13, "Muni-Motos Ambiental", "100 % de cobertura en laderas altas al 2030"),
        P("economia", "Bolsa de trabajo municipal, talleres técnico-productivos y convenios con empresas de Lima Norte", 14, "Crear la Bolsa de Trabajo Municipal"),
        P("gestion", "Agencias municipales descentralizadas con ventanillas de tesorería, mesa de partes, DEMUNA y OMAPED", 15, "con ventanillas de tesorería, mesa de partes", "Agencias operativas en las principales zonas periféricas al 2030"),
    ]),
    ("Belica Julia Bravo Alcántara", "Fuerza Popular", "fuerza-popular", [
        P("seguridad", "Fortalecer serenazgo y COE y coordinar con la Policía para reducir la inseguridad", 2, "Disminuir la inseguridad fortaleciendo serenazgo", "35 % menos incidencia delictiva, 85 % de cobertura de patrullaje integrado y respuesta en menos de 10 minutos"),
        P("social", "Ampliar la atención a víctimas de violencia familiar (CEM, casas refugio) y la prevención comunitaria", 2, "Ampliar servicios de atención (CEM, casas refugio)", "90 % de atención oportuna, 40 % menos reincidencia y programas en el 100 % de sectores"),
        P("agua_riesgos", "Ampliar la cobertura de agua potable, alcantarillado y atención primaria de salud", 3, "Alcanzar 92% agua potable", "92 % de agua potable y 88 % de alcantarillado"),
        P("urbano", "Formalización de predios y ampliación de infraestructura básica en zonas urbanizadas sin servicios", 3, "80% de predios formalizados", "80 % de predios formalizados y 95 % de acceso a servicios básicos"),
        P("transporte", "Formalizar el transporte y rehabilitar vías para reducir la congestión", 3, "Congestión vehicular transporte informal", "70 % de transporte formalizado, 60 km de vías rehabilitadas y 30 % menos tiempo de viaje"),
        P("economia", "Formalización de negocios, ferias y mercados modelo", 3, "3 mercados modelo implementados", "75 % de negocios formalizados, 12 ferias al año y 3 mercados modelo"),
        P("ambiente", "Recuperar espacios públicos y arborizar para ampliar las áreas verdes", 3, "rehabilitar 90% de parques", "4 m² de área verde por habitante y 90 % de parques rehabilitados"),
        P("ambiente", "Sistema integral de residuos con segregación en la fuente y reciclaje municipal", 4, "60% segregación en fuente", "60 % de segregación y 50 % de reciclaje"),
        P("ambiente", "Control de fuentes contaminantes y monitoreo de la calidad del aire", 4, "Control de fuentes contaminantes y monitoreo ambiental", "30 % menos contaminación y 100 % de fuentes monitoreadas"),
        P("gestion", "Simplificación administrativa y digitalización de trámites", 4, "80% digitalización", "80 % de trámites digitales y 50 % menos tiempo de atención"),
        P("gestion", "Audiencias públicas semestrales por sectores y plataforma digital con el avance de proyectos y metas", 5, "Audiencias públicas descentralizadas semestrales"),
    ]),
    ("Juan Carlos Huayanay Mormontoy", "Juntos por el Perú", "juntos-por-el-peru", [
        P("agua_riesgos", "Ampliar las conexiones de agua y desagüe para la población más desfavorecida", 9, "Incrementar la conectividad de agua y desagüe"),
        P("social", "Convenios, campañas e intervención directa para prevenir y combatir la anemia infantil", 9, "prevenir y combatir la anemia infantil"),
        P("seguridad", "Más unidades, cámaras de video y personal capacitado frente a la delincuencia y el pandillaje", 9, "Implementación con unidades, cámaras de video"),
        P("social", "Prevención del alcoholismo, la drogadicción y la delincuencia juvenil", 9, "Disminución en un 60 % los problemas sociales", "60 % menos problemas sociales que afectan a niños y adolescentes"),
        P("urbano", "Apoyo a la formalización de terrenos informales", 9, "Apoyar en la formalización de terrenos no formales"),
        P("economia", "Capacitación en carreras de mayor demanda con institutos técnicos y apoyo a empresas autogestionarias", 9, "Capacitación en carreras de mayor demanda laboral"),
        P("economia", "Formalizar a los ambulantes en espacios ordenados y seguros", 9, "formalización de ambulantes con espacios ordenados"),
        P("economia", "Acuerdo de cooperación interinstitucional para comprometer a la inversión privada en el desarrollo local", 10, "acuerdo de cooperación interinstitucional"),
        P("ambiente", "Más unidades de recojo de basura y campañas contra la contaminación", 10, "Incremento de unidades para el recojo de basura"),
        P("gestion", "Gobierno electrónico, gestión por resultados y reorganización de la municipalidad (ROF y MOF)", 10, "integrándolo al gobierno electrónico"),
    ]),
    ("Pascual Eutiquinio Poma Torrez", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("seguridad", "Actualizar el plan de seguridad con patrullaje integrado, cámaras y juntas vecinales por sectores", 7, "60 juntas vecinales reactivadas", "Patrullaje integrado en el 100 % de sectores priorizados, 80 cámaras o puntos monitoreados y 60 juntas vecinales al 2030"),
        P("social", "Campañas sociales descentralizadas y padrón de población vulnerable", 7, "Realizar 12 campañas integrales por año", "12 campañas al año y 20 000 casos atendidos o derivados"),
        P("social", "Escuelas y talleres deportivos, culturales y educativos para niños y jóvenes", 7, "Implementar 20 escuelas o talleres municipales anuales", "20 talleres al año, 10 000 beneficiarios y 40 espacios públicos activados al 2030"),
        P("social", "Gestionar un hospital estatal de mayor capacidad en el distrito", 9, "Gran hospital estatal para Carabayllo"),
        P("economia", "Ferias laborales, bolsa de trabajo y capacitación técnica", 7, "Realizar 4 ferias laborales por año", "4 ferias al año, 8 000 personas capacitadas y 3 000 colocaciones"),
        P("economia", "Rutas turísticas en Punchauca, Lomas de Carabayllo, el Fortín y la Muralla de Tungasuca", 7, "implementar 6 rutas turísticas priorizadas", "6 rutas turísticas"),
        P("transporte", "Gestionar un puente vial de gran escala que conecte Lima Norte con el eje de Chancay y alivie el Puente San Martín", 9, "Gran puente vial de integración Lima Norte"),
        P("ambiente", "Recuperar puntos críticos de basura y ampliar la segregación y el reciclaje", 8, "Recuperar 80 puntos críticos al 2030", "80 puntos críticos y 20 000 hogares o negocios segregando al 2030"),
        P("ambiente", "Arborización y recuperación de áreas verdes, riberas y lomas", 8, "Plantar y mantener 20,000 árboles al 2030", "20 000 árboles y 100 000 m² intervenidos al 2030"),
        P("agua_riesgos", "Catastro con herramientas digitales, mapa de riesgos e inspecciones preventivas en zonas críticas", 8, "mapa de riesgos priorizado al 2028", "Mapa de riesgos al 2028 e inspecciones semestrales en el 100 % de zonas críticas"),
        P("gestion", "Digitalizar los trámites más demandados y reducir los tiempos de atención", 8, "los 30 trámites municipales más demandados", "30 trámites digitales y 30 % menos tiempo de atención al 2030"),
    ]),
    ("Alejandro Hipólito Ramos Rivera", "Partido Cívico Obras", "partido-civico-obras", [
        P("social", "Programa «Educación para el Desarrollo Integral» de reforzamiento escolar y orientación juvenil, y alfabetización de adultos", 8, "Beneficiar a 10,000 estudiantes, jóvenes y adultos", "10 000 beneficiarios y 20 programas de reforzamiento"),
        P("ambiente", "Programa «Carabayllo Siempre Limpio» con más vehículos de limpieza y equipos de protección para el personal", 9, "Incorporar 20 nuevas unidades entre compactadoras", "100 % de cobertura de recolección y 20 nuevas unidades"),
        P("ambiente", "Programa «Obras Verdes» para recuperar y mantener parques, jardines y bermas", 9, "Plantar y mantener 20,000 árboles en espacios públicos", "300 000 m² de áreas verdes, 20 000 árboles y 100 parques"),
        P("urbano", "Gestionar financiamiento para pistas y veredas en asentamientos humanos y urbanizaciones", 10, "Construir y mejorar 120 kilómetros de veredas", "80 km de pistas, 120 km de veredas y 40 % menos brecha vial"),
        P("seguridad", "Cámaras de videovigilancia, camionetas y motos de patrullaje y personal especializado en monitoreo", 11, "300 cámaras de videovigilancia en zonas estratégicas", "300 cámaras, 50 unidades de patrullaje y 30 % menos tiempo de respuesta"),
        P("social", "Gestionar nuevos puestos de salud y campañas de atención primaria", 12, "Gestionar e implementar 5 nuevos puestos de salud", "5 puestos de salud y 50 000 vecinos en campañas"),
        P("economia", "Circuitos turísticos, miradores y espacios culturales y gastronómicos con los ministerios de Agricultura y Cultura", 14, "Implementar 5 circuitos turísticos integrados", "5 circuitos turísticos y 10 miradores"),
        P("economia", "Formalización progresiva de comerciantes con ferias itinerantes y mercados temporales ordenados", 15, "Formalizar progresivamente a 5,000 comerciantes", "5 000 comerciantes formalizados y 50 ferias itinerantes"),
        P("agua_riesgos", "Recuperar las riberas del río Chillón y gestionar obras de defensa ribereña", 19, "10 km de obras de protección ribereña", "15 km de riberas recuperadas y 10 km de defensas ribereñas"),
        P("urbano", "Catastro actualizado y digitalizado, zonificación oficial y titulación de predios", 22, "80% de predios con título inscrito", "100 % del territorio con catastro y 80 % de predios con título"),
        P("gestion", "Plataforma integral de trámites en línea y agencias municipales más eficientes", 24, "90% de trámites municipales digitalizados", "90 % de trámites digitales y 50 % menos tiempo de atención"),
    ]),
    ("Rosario Peláez Ramírez", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Centro de Monitoreo Inteligente, más cámaras, alarmas comunitarias y patrullaje integrado con la PNP", 11, "Centro de Monitoreo Inteligente de Carabayllo", "500 cámaras y 30 % menos delitos contra el patrimonio al 2030"),
        P("social", "Policlínico municipal, botica a precios sociales, «Médico en tu Barrio» y telemedicina", 12, "Creación del Policlínico Municipal de Atención Primaria", "1 policlínico, 1 botica y 50 campañas integrales al año"),
        P("social", "Programa municipal contra la anemia con seguimiento nutricional y suplementos mediante convenios", 13, "Programa Municipal contra la Anemia", "Reducir la anemia infantil en 30 %"),
        P("social", "Centro integral de atención a la mujer, casa refugio para víctimas de violencia y programa «Mujer Emprende»", 16, "Casa Refugio Temporal", "15 000 mujeres beneficiadas"),
        P("economia", "Centro municipal de empleo, programa «Trabaja Carabayllo» y escuela municipal de oficios", 20, "Escuela Municipal de Oficios", "20 000 personas capacitadas, 8 000 insertadas y 100 ferias laborales al 2030"),
        P("economia", "Modernizar mercados y reubicar progresivamente el comercio ambulatorio", 23, "Formalizar 3,000 comerciantes", "3 000 comerciantes formalizados"),
        P("economia", "Gestionar un parque industrial con estudios técnicos y promoción de inversiones", 24, "Generar más de 5,000 empleos directos e indirectos", "Proyecto integral y más de 5 000 empleos al 2030"),
        P("ambiente", "Nueva flota de limpieza, rutas inteligentes de recolección y eliminación de puntos críticos", 29, "Eliminar el 90% de puntos críticos", "100 % de cobertura y 90 % de puntos críticos eliminados"),
        P("ambiente", "Programa «Carabayllo Verde» con vivero municipal y recuperación de parques con riego tecnificado", 31, "Plantar 5,000 árboles", "5 000 árboles, 40 % más áreas verdes y 100 parques recuperados"),
        P("agua_riesgos", "Plan de adaptación climática con muros de contención, drenajes, defensa ribereña y alerta temprana", 32, "Plan Distrital de Adaptación Climática"),
        P("gestion", "Plataforma de gobierno digital, expediente electrónico y aplicación municipal", 38, "Digitalizar el 80% de los trámites municipales", "80 % de trámites digitales y 100 000 usuarios"),
    ]),
    ("Pablo Alejandro González Villanueva", "Partido País para Todos", "partido-pais-para-todos", [
        P("agua_riesgos", "Proyecto de agua, desagüe y electrificación (S/ 184 millones) con el Ministerio de Vivienda para 223 pueblos y 17 000 familias", 16, "223 pueblos y 17,000 familias", "15 000 viviendas con servicios básicos (5 000 por año, 2027-2029)"),
        P("urbano", "Saneamiento físico-legal de la propiedad en asentamientos humanos, con convenios con COFOPRI, SUNARP y otras entidades", 6, "Suscripción de convenios marco o específicos con COFOPRI"),
        P("urbano", "Paquete de perfiles de muros de contención y escaleras para asentamientos humanos y centros poblados", 7, "Formular un paquete de 2,000 perfiles", "2 000 perfiles"),
        P("transporte", "Construcción de los puentes Olfa Huarangal y Huatocay para centros poblados que quedan aislados en época de lluvias", 7, "CONSTRUCCION DEL PUENTE OLFA HUARANGAL"),
        P("social", "Construir un policlínico, una farmacia y un velatorio municipales", 7, "Policlínico, farmacia y un velatorio Municipal"),
        P("seguridad", "Modernizar el serenazgo, ampliar la videovigilancia y reforzar el patrullaje integrado con la PNP y las juntas vecinales", 16, "350 cámaras, 30 unidades móviles, 450 serenos al 2027", "350 cámaras, 30 unidades móviles y 450 serenos al 2027; reducir 80 % el índice delictivo"),
        P("seguridad", "Puestos de auxilio rápido y casetas de vigilancia con cámaras en sectores críticos", 8, "Implementar 15 puestos de auxilio rápido", "15 puestos de auxilio rápido"),
        P("ambiente", "Recuperación ambiental del río Chillón con corredores recreativos, turísticos y ecológicos", 14, "recuperación y reforzamiento ambiental del Río Chillón"),
        P("economia", "Programas permanentes de asistencia técnica, ferias y asociatividad para productores agropecuarios", 10, "Implementar programas permanentes de asistencia técnica agropecuaria"),
        P("economia", "Formalizar el comercio y el transporte menor, y capacitar a las asociaciones de mototaxistas", 13, "Fortalecer la organización y capacitación de asociaciones de mototaxistas"),
        P("gestion", "Portal de transparencia, simplificación de trámites y cabildos abiertos semestrales", 17, "cabildos abiertos semestrales", "Cabildos abiertos semestrales"),
    ]),
    ("Gianfranco Antonie Soriano Linares", "Partido Patriótico del Perú", "partido-patriotico-del-peru", [
        P("seguridad", "Ampliar el patrullaje preventivo del serenazgo en avenidas, parques, mercados, colegios y zonas comerciales", 22, "ampliación progresiva del patrullaje preventivo en avenidas"),
        P("seguridad", "Modernizar el sistema de videovigilancia distrital recuperando y reforzando las cámaras", 22, "modernización progresiva del sistema de videovigilancia distrital"),
        P("seguridad", "Recuperar espacios públicos inseguros con iluminación y supervisión, en coordinación con la PNP y las juntas vecinales", 23, "mediante iluminación pública, supervisión territorial"),
        P("urbano", "Programas permanentes de mantenimiento de pistas, veredas, parques y bermas en los sectores más deteriorados", 23, "mantenimiento y recuperación progresiva de pistas, veredas, parques, bermas"),
        P("economia", "Fiscalizar la ocupación indebida del espacio público y el comercio informal desordenado", 24, "ocupación indebida de espacios públicos, comercio informal desordenado"),
        P("ambiente", "Reforzar la recolección de residuos en sectores con acumulación de basura y hacer campañas de educación ambiental", 24, "mecanismos de recolección de residuos sólidos"),
        P("gestion", "Simplificación administrativa y herramientas digitales para reducir los tiempos de atención al vecino", 26, "simplificación administrativa, fortalecimiento tecnológico"),
        P("transporte", "Mantenimiento de vías urbanas, señalización y recuperación de espacios para el tránsito peatonal", 26, "fortalecimiento de señalización territorial"),
        P("social", "Actividades deportivas, culturales y educativas para prevenir la violencia juvenil y el consumo de drogas", 28, "prevenir violencia juvenil, consumo de drogas"),
        P("social", "Actividades recreativas y comunitarias para adultos mayores y familias vulnerables", 29, "fortalecer protección y atención progresiva de adultos mayores"),
        P("economia", "Ordenar mercados y zonas comerciales en coordinación con comerciantes y emprendedores", 29, "transitabilidad en mercados y zonas comerciales"),
    ]),
    ("Daniel Josué Carbajal Ugarte", "Partido Político ADP", "partido-politico-adp", [
        P("seguridad", "Central de monitoreo con inteligencia artificial: lectura de placas en entradas y salidas del distrito y reconocimiento facial", 24, "Central de Monitoreo con Analítica de Datos"),
        P("seguridad", "Drones de vigilancia para patrullar zonas altas como Lomas de Carabayllo, San Benito y San Pedro", 25, "Drones de Vigilancia"),
        P("transporte", "Plan «Mototaxi Segura»: empadronamiento obligatorio de asociaciones y código QR visible en cada unidad", 25, "Formalización y empadronamiento obligatorio de todas las asociaciones"),
        P("agua_riesgos", "Piletas públicas y tanques comunales con agua clorada en Lomas de Carabayllo y San Benito mientras avanzan las obras de SEDAPAL", 27, "sistemas de piletas públicas reguladas", "Reducir a la mitad el costo que cobran las cisternas informales"),
        P("urbano", "Oficina municipal de saneamiento físico-legal con brigadas técnicas para acelerar la titulación, en convenio con COFOPRI y la MML", 13, "Oficina Municipal de Saneamiento Físico-Legal"),
        P("economia", "Ordenanza para que las empresas que ganen obras públicas contraten mano de obra no calificada de la zona", 14, "contraten obligatoriamente un porcentaje mínimo", "Entre 30 % y 40 % de mano de obra local"),
        P("social", "Estrategia contra la anemia: tamizajes de hemoglobina con el MINSA y alimentos ricos en hierro en ollas, comedores y Vaso de Leche", 15, "tamizajes masivos y obligatorios de hemoglobina", "Reducir en 50 % la anemia infantil"),
        P("social", "Equipar ollas comunes con módulos de material noble, cocinas y gas, y convertirlas en centros de nutrición", 16, "Equipar y formalizar al 100% de las Ollas Comunes activas", "100 % de las ollas comunes activas equipadas y formalizadas"),
        P("social", "Clínicas municipales móviles en laderas y asentamientos, y puntos de telemedicina en locales comunales", 21, "48 campañas macro al año", "48 campañas al año y 10 puntos de telemedicina"),
        P("ambiente", "Gestionar la remediación de la zona del antiguo botadero El Zapallal para convertirla en un bosque urbano o parque zonal", 27, "Bosque Urbano El Zapallal"),
        P("gestion", "Oficina de Cumplimiento Estratégico que monitorea semanalmente a las gerencias y plataforma digital con el avance de cada promesa", 37, "Oficina de Cumplimiento Estratégico"),
    ]),
    ("Claudio Rodríguez Mansilla", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Central distrital de videovigilancia inteligente, más cámaras de seguridad y sistema de botones de pánico", 17, "Implementación de 500 Cámaras de Seguridad progresivamente", "500 cámaras de seguridad"),
        P("seguridad", "Programa «Paraderos Seguros»: paraderos formales con cámara, iluminación y botón SOS", 9, "Organización de paraderos formales en todo el distrito"),
        P("agua_riesgos", "Ampliar las redes de agua potable y alcantarillado y construir reservorios", 15, "Alcanzar una cobertura de agua potable superior al 90%", "Cobertura de agua potable superior al 90 % y 50 % menos población sin alcantarillado"),
        P("transporte", "Programa integral de pavimentación con pistas, veredas, ciclovías e infraestructura peatonal inclusiva", 16, "Reducir en 50% la población sin acceso adecuado a pistas y veredas", "Reducir en 50 % la población sin acceso adecuado a pistas y veredas"),
        P("social", "Construir y mejorar colegios, con bibliotecas virtuales y aulas digitales", 15, "Reducir en 30% la brecha de infraestructura educativa al año 2030", "Reducir en 30 % la brecha de infraestructura educativa al 2030"),
        P("social", "Gestionar nuevos establecimientos de salud de primer nivel y centros de salud municipales", 15, "Reducir en 25% la brecha de equipamiento de establecimientos de salud", "Reducir en 25 % la brecha de equipamiento de salud"),
        P("social", "Usar el Estadio Ricardo Palma para enseñar disciplinas olímpicas y crear la Copa Carabayllo entre colegios", 7, "Implementación del Estadio Ricardo Palma"),
        P("economia", "Reubicar el comercio informal construyendo mercados ordenados y limpios", 10, "Construcción de mercados apropiados"),
        P("ambiente", "Programa «Carabayllo Verde» con reciclaje de residuos y reforestación de parques, avenidas y laderas", 16, "Incrementar en 30% los espacios públicos verdes", "30 % más de espacios públicos verdes"),
        P("ambiente", "Clausura definitiva de los rellenos sanitarios del distrito y planta distrital de compost y reciclaje", 10, "Clausura definitiva de los rellenos sanitarios"),
        P("gestion", "Plataforma de gobierno digital, centro digital municipal y wifi gratuito en plazas", 16, "Digitalizar el 100% de los principales trámites municipales", "100 % de los principales trámites digitalizados"),
    ]),
    ("Renso Evert Aguilar Velarde", "PRIN", "partido-politico-prin", [
        P("social", "Academia preuniversitaria municipal gratuita y bibliotecas populares digitales con internet gratuito", 44, "Academia Preuniversitaria Municipal Gratuita y a las Bibliotecas Populares Digitales", "35 % de la población infantil y juvenil accede cada año"),
        P("social", "Policlínicos itinerantes municipales en las agencias del distrito y un centro municipal de salud mental comunitaria", 47, "Policlínicos Itinerantes Municipales", "150 000 atenciones preventivas acumuladas al 2030"),
        P("seguridad", "Más serenos y un policía a bordo en todas las unidades del serenazgo, con patrullaje por microcuadrantes", 55, "Incrementar la fuerza operativa a 1.5 serenos", "1,5 serenos por cada 1 000 habitantes; reducir 20 % al año los delitos patrimoniales"),
        P("seguridad", "Lectura de placas y reconocimiento facial en los accesos viales, e integración de cámaras privadas a la red municipal", 56, "Integrar un mínimo de 500 cámaras privadas", "IA en el 100 % de accesos viales y 500 cámaras privadas integradas"),
        P("urbano", "Recuperar e iluminar losas deportivas y parques abandonados, con reflectores solares en paraderos, puentes e ingresos escolares", 56, "Instalar 1,000 reflectores LED solares", "1 000 reflectores LED solares y 80 losas y parques recuperados"),
        P("agua_riesgos", "Destrabar con SEDAPAL los proyectos de agua potable y alcantarillado priorizados para el distrito", 66, "red pública de agua potable y alcantarillado del 95% de viviendas", "95 % de viviendas con agua y alcantarillado"),
        P("economia", "Programa «Carabayllo Emprende»: ventanilla única con asesoría gratuita y ferias itinerantes para formalizar negocios", 70, "Lograr la formalización de 2,500 MYPEs", "2 500 MYPE formalizadas"),
        P("transporte", "Gestionar tres puentes de doble vía sobre el Chillón (Huarangal, Prolongación Chimpu Ocllo y Camino Real) y rehabilitar la red vial local", 91, "Huarangal, Prolongación Chimpu Ocllo", "3 puentes y 45 % de la red vial local rehabilitada"),
        P("ambiente", "Recolección de residuos con rutas optimizadas y estaciones de contenedores subterráneos en zonas comerciales", 81, "20 estaciones de contenedores subterráneos", "100 % de recolección en zonas urbanas, 95 % en zonas altas y 20 estaciones de contenedores al 2030"),
        P("ambiente", "Declarar las Lomas de Primavera como área de conservación y plantar árboles nativos con el programa «Carabayllo Verde»", 86, "1,700 hectáreas de las Lomas de Primavera", "Protección de 1 700 ha de lomas y 100 000 árboles nativos al 2030"),
        P("gestion", "Auditoría forense y anticorrupción integral con la Contraloría y la Fiscalía al inicio de la gestión", 101, "Auditoría Forense y Anticorrupción integral", "Dentro de los primeros 30 días de gestión"),
    ]),
    ("Dennis Antonio Huapaya Bravo", "PPC", "partido-popular-cristiano-ppc", [
        P("social", "Ampliar las sedes de la DEMUNA para atender la violencia familiar", 15, "Ampliar el numero de sedes de DEMUNA a 6", "6 sedes de DEMUNA"),
        P("social", "Ampliar la OMAPED con convenios para atender a personas con discapacidad", 16, "dicha población 17,000 personas", "17 000 personas atendidas"),
        P("social", "Gestionar un centro de salud de categoría II-1 en el distrito", 16, "Un Centro de Salud Categoría II-1 para el 2030", "Un centro de salud II-1 al 2030"),
        P("social", "Gestionar la instalación de una universidad o institutos superiores tecnológicos en el distrito", 17, "debería haber 2 IST", "2 institutos superiores tecnológicos al 2030"),
        P("urbano", "Oficina de orientación para el saneamiento físico-legal de predios y la ampliación de servicios básicos", 16, "Implementar una oficina de promoción de saneamiento al 2030", "Oficina implementada al 2030"),
        P("seguridad", "Centro de monitoreo con cámaras inteligentes articulado con la PNP y gestión de nuevas comisarías", 18, "seguridad con 100 cámaras y articulado con la policía nacional", "Centro de monitoreo con 100 cámaras"),
        P("gestion", "Plataformas digitales para trámites y atención virtual al vecino", 17, "se debería atender al 40% de los contribuyentes", "40 % de contribuyentes atendidos por medios virtuales al 2030"),
        P("gestion", "Audiencias públicas y cabildos abiertos semestrales, datos abiertos y más participación en el presupuesto participativo", 18, "audiencias públicas y cabildos abiertos semestrales", "Más de 1 000 ciudadanos en el presupuesto participativo al 2030"),
        P("economia", "Identificar un espacio público para el comercio en cada sector del distrito y una oficina de promoción de la MYPE", 19, "un espacio publico para cada sector del distrito (11 sectores)", "Un espacio en cada uno de los 11 sectores"),
        P("ambiente", "Riego de parques y áreas verdes con aguas superficiales y subterráneas del río Chillón", 21, "el 30% de las áreas verdes estarán regadas", "30 % de áreas verdes con riego tecnificado al 2030"),
        P("agua_riesgos", "Muros de contención, diques y defensas ribereñas en zonas vulnerables y en la cuenca del Chillón", 22, "muros de contención, diques y defensas ribereñas"),
    ]),
    ("Eduardo Urbina Santillana", "Partido Unidad y Paz", "partido-unidad-y-paz", [
        P("seguridad", "Central de videovigilancia mixta, más cámaras y nuevas camionetas, motos y equipamiento para el serenazgo", 3, "Central de Videovigilancia Mixta de Carabayllo"),
        P("seguridad", "Drones de vigilancia y gestión de un módulo de flagrancia delictiva y de personal del Grupo Terna", 3, "modulo de flagrancia delictiva"),
        P("social", "Construir un hospital municipal y gestionar ante el MINSA un hospital de nivel II", 4, "Construccion del Hospital Municipal de Carabayllo"),
        P("social", "Construir el Palacio de la Juventud y gestionar una universidad y un instituto tecnológico en el distrito", 4, "Construccion del Palacio de la Juventud"),
        P("social", "Construir la Casa del Adulto Mayor y la Casa de las Personas con Discapacidad", 7, "Construccion de la Casa de las Personas con Discapacidad"),
        P("economia", "Crear la Caja Municipal de Carabayllo", 5, "Construccion de la Caja Municipal de Carabayllo"),
        P("transporte", "Gestionar un puente sobre el río Chillón entre la Av. Parque Zonal y la Av. Colectora", 5, "entre la avenida Parque Zonal y la avenida Colectora"),
        P("transporte", "Gestionar un bypass entre los kilómetros 19 y 21 de la Av. Túpac Amaru", 5, "bypass entre los kilometros 19 y 21"),
        P("urbano", "Construir la Plaza de Armas de Carabayllo", 5, "Construccion de la Plaza de Armas de Carabayllo"),
        P("ambiente", "Riego tecnificado de áreas verdes, faroles solares, arborización y programas de reciclaje", 6, "Implementacion de sistemas de riego tecnificado para areas verdes"),
    ]),
    ("Michael Alonso Tineo Mendoza", "Perú Moderno", "peru-moderno", [
        P("seguridad", "Seis bases de serenazgo (Chocas, El Progreso, Las Lomas, San Pedro, Santo Domingo y Torre Blanca), cada una con central de monitoreo, cámaras con IA y drones", 24, "Proyecto 06 Centrales De Monitoreo", "6 bases y 6 centrales de monitoreo"),
        P("seguridad", "Ampliar la flota de patrullaje del serenazgo con carros y motos", 23, "incrementar a 60 el número de las unidades móviles", "60 carros y 60 motos patrulla"),
        P("ambiente", "Comprar compactadoras y motofurgones propios para el recojo de basura, con monitoreo por GPS", 26, "contar con 20 compactadoras de basura propias", "20 compactadoras y 25 motofurgones"),
        P("social", "Gestionar un hospital emblemático en terreno municipal y un segundo Hospital de la Solidaridad", 27, "segundo hospital de la solidaridad"),
        P("social", "Expandir la DEMUNA a todos los sectores del distrito", 34, "expandir las oficinas de la DEMUNA a los 11 sectores", "DEMUNA en los 11 sectores"),
        P("gestion", "App municipal única para trámites, licencias y pagos, y licencias y permisos en el día", 29, "no superando las 24 horas", "Trámites en no más de 24 horas"),
        P("economia", "Licencias y permisos sin costo para el comercio en el primer año, con capacitación y asesoría", 30, "permisos y licencias para el sector comercio será sin costo", "Sin costo durante el primer año de gestión"),
        P("transporte", "Impulsar los puentes Huatocay y Olfa Huarangal para conectar los centros poblados en época de crecida del Chillón", 37, "Proyecto Puente Olfa Huarangal"),
        P("agua_riesgos", "Almacenes de contingencia con productos esenciales en cada sector y muros de contención sismorresistentes", 37, "almacenes de contingencia en cada uno de los 11 sectores", "Abastecimiento de 30 días en los 11 sectores"),
        P("urbano", "Titulación gratuita de predios para los propietarios del distrito y control del tráfico de terrenos", 42, "Titulación Al 100%", "100 % de titulación"),
        P("ambiente", "Reforestar el distrito en zonas urbanas, parques, ribera del Chillón y Lomas de Primavera", 44, "reforestar Carabayllo con 2 millones de árboles", "2 millones de árboles"),
    ]),
    ("Wilmer Roberto Valverde Valverde", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Integrar la videovigilancia al centro de control metropolitano C5, sumar cámaras con reconocimiento facial y cámaras de vecinos", 22, "Incorporación del sistema de videovigilancia del distrito de Carabayllo al PROYECTO C5", "58 881 incidencias atendidas en 2030"),
        P("seguridad", "Unidad de flagrancia, puestos de auxilio rápido, alarmas comunitarias y app para reportar delitos y emergencias", 22, "Creación de la unidad de flagrancia"),
        P("social", "Casa de la juventud con tecnología, casa de la mujer emprendedora, casa campestre del adulto mayor y casa de acogida temporal", 24, "Creación de la casa campestre para el adulto mayor"),
        P("social", "Gestionar un hospital municipal de nivel II, una botica municipal y ambulancias que se piden por aplicativo", 25, "Hospital Municipal nivel II"),
        P("social", "Ejecutar el Centro Materno Infantil en Lomas de Carabayllo", 26, "Centro Materno Infantil en Lomas de Carabayllo"),
        P("economia", "Construir un mega mercado municipal y organizar ferias y mercados itinerantes", 26, "Construcción de un mega mercado municipal"),
        P("agua_riesgos", "Descolmatación y muros de contención en las riberas del río Chillón", 27, "Descolmatación y construcción de muros de contención en las riberas"),
        P("urbano", "Planta municipal de concreto para construir pistas y veredas de concreto", 28, "Creación de la planta municipal de producción de concreto"),
        P("transporte", "Nueva vía entre la Carretera a Canta y la Panamericana Norte, puente en la Av. Parque Zonal y corredor para mototaxis", 28, "nueva vía que conecta la Carretera Canta con la Av. panamericana norte", "24 vías mejoradas en 2030"),
        P("ambiente", "Planta integral de reciclaje y valorización de residuos para generar energía en el Valle Chillón", 29, "Planta Integral de Reciclaje y Valorización de Residuos Sólidos", "12,9 % de residuos inorgánicos valorizados en 2030"),
        P("gestion", "Crear la Defensoría Municipal del Vecino y digitalizar los trámites municipales", 30, "Creación de la Defensoría Municipal del Vecino"),
    ]),
    ("Nandy Janeth Córdova Morales", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Plan «Carabayllo Seguro 24/7»: patrullaje integrado, videovigilancia y recuperación de espacios públicos inseguros", 4, "Implementar 120 cámaras de videovigilancia", "120 cámaras y 50 espacios públicos recuperados"),
        P("social", "Programa «Deporte para Todos» con recuperación de espacios deportivos y programas para niños y jóvenes", 4, "Recuperar 30 espacios deportivos", "30 espacios deportivos y más de 15 000 niños y jóvenes"),
        P("social", "Campañas descentralizadas de salud preventiva en los sectores con mayores brechas", 4, "Realizar campañas descentralizadas de salud preventiva"),
        P("ambiente", "Programa «Carabayllo Limpio»: eliminar puntos críticos de basura y ampliar la limpieza pública con segregación en la fuente", 5, "Reducir progresivamente los puntos críticos de acumulación"),
        P("ambiente", "Riego tecnificado, arborización y vivero municipal para recuperar áreas verdes", 5, "sistemas de riego tecnificado, arborización"),
        P("ambiente", "«Guardianes del Río Chillón»: limpieza, vigilancia y recuperación de su faja marginal", 6, "faja marginal del río Chillón"),
        P("agua_riesgos", "Gestionar proyectos para ampliar el agua y el saneamiento en los sectores con mayores brechas", 5, "Gestionar proyectos que contribuyan a ampliar la cobertura de agua"),
        P("transporte", "Infraestructura segura para peatones y ciclistas en zonas estratégicas", 6, "infraestructura segura para peatones y ciclistas"),
        P("economia", "Modernizar mercados de abasto priorizados en infraestructura, salubridad y seguridad", 7, "mejoramiento y modernización en mercados priorizados"),
        P("urbano", "Programa «Título Seguro»: saneamiento físico-legal de predios y prevención del tráfico de terrenos", 7, "TÍTULO SEGURO, FUTURO SEGURO"),
        P("gestion", "Simplificar trámites, digitalizar los servicios más demandados y llevar la atención municipal a los barrios", 9, "digitalizar los principales servicios de mayor demanda ciudadana"),
    ]),
]
