"""Santiago de Surco (150140): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150140"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Oswaldo Martín Moreno Rivera", "Acción Popular", "accion-popular", [
        P("seguridad", "Filtros en zigzag, bolardos y pavimento rugoso en los accesos de pasajes de los sectores 2, 3 y 4 para frenar el ingreso de motos", 19, "Chicanas y Filtros de Acceso en Sectores 2, 3 y 4", "30 accesos críticos intervenidos"),
        P("seguridad", "Aplicativo municipal para reportar incidencias y descuento en arbitrios a vecinos y negocios que integren sus cámaras privadas al monitoreo distrital", 22, "Incentivo tributario (descuento en arbitrios)", "500 cámaras privadas integradas a la red municipal de monitoreo"),
        P("social", "Escuadrón de moto-ambulancias con paramédicos en cuatro bases y desfibriladores (DEA) en centros comerciales, estaciones del Metro y mercados", 25, "Escuadrón de Moto-Ambulancias con bases en Surco Pueblo", "100 DEAs instalados y primera respuesta < 5 minutos en el 90% de los casos"),
        P("social", "Red de centros de escucha con soporte psicológico primario, uno por zona, para detectar violencia de género e ideación suicida", 27, "9 espacios descentralizados de soporte psicológico primario", "9 centros de escucha (uno por zona)"),
        P("urbano", "Programa «Surco: Calle por Calle»: rehabilitar pistas y veredas con accesibilidad universal, priorizadas según el mapa de vulnerabilidad", 28, "Rehabilitación de pistas y veredas con accesibilidad universal", "50 km de pistas y veredas rehabilitadas en el periodo"),
        P("transporte", "Semáforos adaptativos con olas verdes en Benavides, Caminos del Inca, Velasco Astete, Primavera y Encalada, y aplicativo de estacionamientos", 32, "creando olas verdes en Benavides, Caminos del Inca", "Reducción del 20% del tiempo de viaje en avenidas intervenidas"),
        P("transporte", "Buses eléctricos municipales como alimentadores hacia el Metro y el Metropolitano, paraderos inteligentes y red de ciclovías continuas", 40, "9 buses eléctricos (cero emisiones) como alimentadores", "9 buses eléctricos y 25 km de ciclovías continuas"),
        P("agua_riesgos", "Construir tres albergues antisísmicos con iluminación solar en las zonas críticas de La Encantada de Villa, Cercado de Surco y Ex Susana Higuchi", 31, "Construcción de 3 albergues antisísmicos", "3 albergues con capacidad total de 1,500 personas"),
        P("gestion", "Aplicativo municipal único, expediente 100 % digital y licencias comerciales en un máximo de 72 horas", 31, "licencias comerciales en máximo 72 horas desde el año 1", "Licencias en 72 horas desde el año 1"),
        P("economia", "Festival mensual permanente, recuperación de Surco Pueblo como polo turístico-gastronómico y Escuela Municipal de Arte", 33, "Recuperación de Surco Pueblo como polo turístico-gastronómico-cultural", "12 festivales al año y 5,000 visitantes mensuales a Surco Pueblo"),
        P("ambiente", "Riego por goteo con sensores y desvío de agua del Canal del Río Surco, tratada, hacia los parques", 35, "desvío de venas del Canal del Río Surco hacia parques", "80% con riego tecnificado y 40% menos gasto en agua potable"),
    ]),
    ("José Manuel Fernández Chávez", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Descentralizar la Central Alerta Surco y articular su inteligencia artificial con cuadrantes vecinales y juntas vecinales bajo un protocolo común", 5, "Descentralizar tácticamente la Central Alerta Surco", "Reducir la percepción de inseguridad del 89.3% al 39%, con respuesta máxima de 3 minutos"),
        P("seguridad", "Reasignar 10 % del gasto corriente en consultorías y publicidad al mantenimiento de la flota de serenazgo y al patrullaje por sectores", 6, "Se reasignará el 10% del gasto corriente en consultorías"),
        P("social", "Centros de Innovación, Deporte y Cultura (CENIDEC) en losas deportivas recuperadas de los sectores populares, con talleres digitales", 6, "Centros de Innovación, Deporte y Cultura (CENIDEC)", "Cobertura del 100% de los sectores populares (2, 5, 7, 8 y 9)"),
        P("urbano", "Brigada municipal gratuita de abogados y arquitectos para sanear, titular e independizar predios y quintas del Surco tradicional", 8, "independización de 3,500 lotes, quintas y viviendas", "3,500 lotes, quintas y viviendas saneados"),
        P("urbano", "Ordenanza para congelar los parámetros urbanísticos y frenar alturas y densidades no previstas en las zonas residenciales", 12, "congelamiento y la intangibilidad paramétrica del distrito"),
        P("economia", "Eje turístico, histórico y gastronómico del Surco Viejo con formalización predial, incentivos tributarios y simplificación de trámites para MYPES", 9, "Eje Turístico, Histórico y Gastronómico del Surco Viejo", "500 nuevas MYPES formalizadas"),
        P("economia", "Exonerar de tasas de tramitación las licencias de giros tradicionales de escala barrial en el Surco Viejo", 9, "exoneración temporal del 100% de tasas de tramitación TUPA", "Exoneración del 100 % durante el primer año de gestión"),
        P("ambiente", "Defender el Parque Zonal 22-A y los espacios públicos de Los Álamos de Monterrico y no aprobar licencias que vulneren la zonificación", 10, "consolidación física total del Parque Zonal 22-A", "Cero licencias que vulneren la zonificación residencial"),
        P("transporte", "Semaforización inteligente centralizada con sensores en los cinco nudos más congestionados, financiada con parte del presupuesto de bacheo", 10, "Semaforización Inteligente y Centralizada en los 5 nudos", "Disminuir en un 25% el tiempo de espera y congestión vehicular"),
        P("transporte", "Gestionar con el MTC y el Ministerio de Vivienda el cofinanciamiento de viaductos y pasos a desnivel en Benavides, Primavera y Encalada", 14, "co-financiamiento de viaductos y pasos a desnivel"),
        P("gestion", "Unidad de promoción de la inversión privada para obras por impuestos, con cartera anual de proyectos y certificados CIPRL más rápidos", 15, "Reducción de 90 a 30 días", "Trámite de CIPRL de 90 a 30 días"),
    ]),
    ("Jean Pierre Combe Portocarrero", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("social", "Campañas periódicas de salud y nutrición para reducir la anemia infantil", 1, "Campañas periódicas de salud y nutrición", "Reducir la anemia en niños menores de 5 años en 20%"),
        P("social", "Proyectos sociales para niñez, adultos mayores, mujeres, jóvenes y personas con discapacidad, e implementación de la OMAPED", 1, "Implementar OMAPED"),
        P("social", "Convenios con el MINSA y el sector privado, e infraestructura municipal de salud propia", 1, "Desarrollo propio de infraestructura de salud"),
        P("seguridad", "Mejorar la iluminación de calles, parques y losas deportivas", 1, "Mejorar iluminación de calles, parques y losas"),
        P("seguridad", "Fortalecer la videovigilancia y el patrullaje", 2, "Fortalecer videovigilancia, patrullaje y seguridad integral"),
        P("transporte", "Formalizar y reordenar el transporte, reduciendo paraderos y transporte informal, con un plan regulador actualizado", 2, "Disminución de paraderos y transporte informal"),
        P("social", "Renovar y ampliar los convenios con universidades e institutos para el acceso a educación técnica y superior", 2, "Renovar e incrementar convenios con universidades e institutos"),
        P("economia", "Promover la formalización comercial, el turismo y la capacitación para el empleo", 2, "Promover formalización comercial"),
        P("ambiente", "Nuevos parques y áreas verdes, y valorización de residuos con enfoque de economía circular", 2, "Implementar nuevos parques y áreas verdes", "5m² de áreas verdes por habitante"),
        P("urbano", "Implementar el catastro distrital y nuevas bibliotecas municipales, modernizando las existentes", 2, "Implementar catastro distrital"),
        P("gestion", "Digitalizar y simplificar trámites, y actualizar ROF, CAP, TUPA y demás instrumentos de gestión", 2, "Actualizar ROF, CAP, TUPA y demás instrumentos", "90% actualizados al 2030"),
    ]),
    (None, "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Plan «Surco Seguro»: nuevas cámaras con reconocimiento facial y lectura de placas, y aumento del cuerpo de serenazgo con prioridad nocturna", 10, "200 nuevas cámaras inteligentes con reconocimiento facial", "200 cámaras, 40 % más serenos y victimización reducida al 18% al 2030"),
        P("social", "Cuatro Centros de Atención Municipal de Salud Preventiva y unidades móviles de salud que recorran los sectores", 10, "Centros de Atención Municipal de Salud Preventiva (CAMPS)", "4 CAMPS operativos al 2029; 80,000 atenciones preventivas anuales al 2030"),
        P("social", "Casa de la Mujer de Surco con atención psicológica, asesoría legal, capacitación laboral y albergue temporal para víctimas de violencia", 11, "Crear la Casa de la Mujer de Surco", "500 mujeres atendidas/año al 2028"),
        P("social", "Programa «Surco Aprende» de reforzamiento escolar gratuito y Academia Municipal Preuniversitaria gratuita", 11, "Academia Municipal Preuniversitaria gratuita", "5,000 estudiantes beneficiados al 2030"),
        P("transporte", "Gestionar con el MTC y la Municipalidad de Lima la solución de los cuellos de botella en Primavera, Benavides y Circunvalación", 12, "cuellos de botella viales en la Av. Primavera, Benavides y Circunvalación"),
        P("transporte", "Ampliar la red de ciclovías conectando zonas residenciales con centros comerciales, parques y estaciones de transporte masivo", 15, "Ampliar la red de ciclovías del distrito en 15 km adicionales", "15 km de ciclovías al 2030"),
        P("economia", "Licencias de funcionamiento para negocios de bajo riesgo en 72 horas y campañas de formalización con reducción temporal de tasas", 13, "máximo de 72 horas para negocios de bajo riesgo", "Reducir la informalidad al 30% al 2030; otorgar 3,000 nuevas licencias en el periodo"),
        P("economia", "Circuito turístico-arqueológico «Huacas de Surco» con señalización y guías, y Festival Gastronómico Anual", 14, "puesta en valor de las huacas Limatambo y Buenavista", "10,000 visitantes/año al circuito arqueológico al 2030"),
        P("ambiente", "Renovar la flota de limpieza y programa «Surco Recicla» de segregación con incentivos tributarios", 15, "8 compactadores modernos de bajo consumo", "100% de cobertura al 2028; 15% de residuos valorizados al 2030"),
        P("ambiente", "Nuevos parques, jardines lineales y corredor verde «Paseo de la Vida», y recuperación de 20 parques en mal estado", 15, "Incrementar el índice de áreas verdes por habitante", "Alcanzar 7 m²/habitante al 2030"),
        P("gestion", "Plataforma «Surco Digital» como ventanilla única virtual para trámites, pagos y seguimiento de expedientes", 17, "ventanilla única virtual para la realización de trámites", "80% de trámites digitalizados al 2029"),
    ]),
    ("Jhon Cautivo Hancco Chumpitaz", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("gestion", "Ecosistema digital «Surco 360» para reportar incidencias, hacer trámites, seguir solicitudes y participar en consultas", 5, "SURCO 360 sera el principal sistema de transformacion digital"),
        P("seguridad", "Patrullaje por microzonas de vigilancia adaptado a las necesidades de cada sector", 7, "modelo de patrullaje basado en microzonas de vigilancia"),
        P("seguridad", "Uso de drones y otras tecnologías de monitoreo para vigilancia preventiva y respuesta ante emergencias", 7, "Potenciaremos el uso de drones"),
        P("gestion", "Publicar periódicamente el avance de los compromisos del plan y un tablero de obras e indicadores de gestión", 9, "Publicaremos periodicamente el estado de cumplimiento"),
        P("economia", "Programa «Surco Emprende» de capacitación, digitalización y formalización, con alianzas con universidades, empresas y cámaras empresariales", 10, "alianzas con universidades, institutos, empresas, camaras empresariales"),
        P("social", "Descentralizar los servicios municipales de salud mediante módulos, programas itinerantes y nuevos puntos de atención", 12, "mediante modulos, programas itinerantes y nuevos puntos de atencion"),
        P("social", "Programa «Surco Salud en Casa» de atención domiciliaria para adultos mayores con movilidad reducida y personas con discapacidad", 13, "programa de atencion domiciliaria para vecinos en situacion de vulnerabilidad"),
        P("transporte", "Modernizar la red semafórica con sistemas de gestión inteligente, en coordinación con las entidades competentes", 14, "modernizacion progresiva de la infraestructura semaforica"),
        P("transporte", "Evaluar el «Urbanito Surcano»: rutas de conexión vecinal hacia estaciones del Metro y corredores de transporte", 15, "rutas de conexion vecinal que faciliten el acceso a estaciones del Metro"),
        P("urbano", "Mejorar veredas, cruces peatonales y rampas de accesibilidad en los espacios públicos", 15, "mejoras progresivas en veredas, cruces peatonales, rampas"),
        P("ambiente", "Campañas de atención veterinaria, esterilización y adopción responsable, y convenios para espacios de recuperación de animales abandonados", 16, "atencion veterinaria, esterilizacion, adopcion responsable"),
    ]),
    ("María Luisa Meneses Martínez", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Escuela de Serenazgo para la selección y capacitación especializada del personal", 4, "Crear la Escuela de Serenazgo"),
        P("seguridad", "Cámaras de videovigilancia con inteligencia artificial y módulos de atención rápida con policías y serenos en colegios, paraderos y puentes", 4, "Adquirir 500 cámaras video vigilancia con IA", "500 cámaras"),
        P("social", "Servicio de ambulancia municipal las 24 horas con personal médico y protocolo epidemiológico ante brotes y pandemias", 5, "Servicio de Ambulancia Municipal Continuo (24/7)", "Tiempo de respuesta menor a 10 minutos al 2030"),
        P("social", "Red de talleres ocupacionales inclusivos para personas con discapacidad, con incentivos a empresas que las contraten", 6, "Red Municipal de Talleres Ocupacionales Inclusivos", "Alcanzar 180 inserciones laborales directas"),
        P("social", "Cuna Municipal Verde piloto con paneles solares, biohuerto y horarios flexibles para familias trabajadoras", 7, "Cuna Municipal Verde como modelo piloto referente", "Capacidad máxima de 120 niños"),
        P("economia", "Aplicativo «Surco Verde Conectado» para registrar, auditar y conectar a técnicos y trabajadores independientes con los vecinos", 10, "Plataforma Digital y Aplicativo Móvil Oficial", "Incrementar el padrón a 1,000 trabajadores independientes"),
        P("economia", "Modernizar mercados con un modelo de cogestión entre municipalidad, asociaciones de comerciantes e inversión privada, con puestos para reubicar ambulantes", 11, "articulación y co-gestión entre la Municipalidad", "Mercado piloto co-gestionado en operación al 2030"),
        P("urbano", "Actualizar el Plan de Desarrollo Urbano y el catastro, y usar la mayor recaudación predial para mantener pistas y veredas", 16, "el Plan de Desarrollo Urbano y el catastro municipal", "80% del catastro modernizado al 2030"),
        P("ambiente", "Segregación en la fuente, integración de recicladores, riego con aguas residuales tratadas y ampliación de áreas verdes", 18, "priorizando la valorización de residuos (reciclaje)", "25% de residuos aprovechables valorizados y 15 % más áreas verdes al 2029"),
        P("ambiente", "Red de Asistencia Veterinaria Municipal Gratuita, campañas de esterilización itinerantes y fiscalización contra el maltrato animal", 3, "Red de Asistencia Veterinaria Municipal Gratuita"),
        P("gestion", "Procuraduría de defensa territorial para impulsar la demarcación con Chorrillos y San Juan de Miraflores y reforzar servicios en zonas limítrofes", 24, "Procuraduría Especializada en Defensa Territorial de Surco", "100% de los expedientes con dictamen favorable al 2030"),
    ]),
    ("Arturo Miguel Guillermo Bobbio Carranza", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Modernizar el C4 Alerta Surco con interoperabilidad, analítica de video, mapas de calor y modelos predictivos para el patrullaje", 45, "Reducir en 40% las denuncias por delitos contra el patrimonio", "40 % menos denuncias por delitos contra el patrimonio y 50 % menos tiempo de respuesta"),
        P("seguridad", "Modelo «Serenazgo 4.0»: capacitación y certificación continua del personal en el centro CECAM, con especialización y entrenamiento táctico", 127, "Implementar el modelo Serenazgo 4.0", "700 efectivos capacitados y certificados anualmente"),
        P("urbano", "Continuar y ampliar el programa Techo Propio Surcano, con cofinanciamiento del Bono Familiar Habitacional del MVCS", 121, "Programa Techo Propio Surcano: Continuidad y Experiencia"),
        P("social", "Integrar FES, Supérate, Academia Surcana y Preuniversitaria Surcana en una ruta de apoyo escolar, becas y preparación preuniversitaria", 124, "FES, Supérate, Academia Surcana y Preuniversitaria Surcana", "Al menos 2,000 beneficiarios anuales"),
        P("social", "Programa «Loncheritas Surcanas» de nutrición escolar, tamizajes y educación alimentaria en colegios públicos priorizados", 123, "Programa Loncheritas Surcanas: Nutrición Escolar Surcana", "Intervención anual en el 100% de instituciones educativas públicas priorizadas"),
        P("economia", "Asesoría técnica preventiva «Antes de Alquilar, Consulta» y módulos descentralizados para agilizar licencias de funcionamiento e ITSE", 130, "Antes de Alquilar, Consulta", "Mínimo 5.000 atenciones preventivas gratuitas y 30% de reducción en tiempos de formalización"),
        P("economia", "«Boulevard Surco Pueblo»: reglamento de terrazas gastronómicas con incentivos y agenda turística y cultural permanente", 131, "Reglamentación de Terrazas Gastronómicas", "Mínimo 40 nuevos negocios con terrazas y 24 activaciones o ferias al año"),
        P("transporte", "Ampliar e integrar la red de ciclovías con estaciones para bicicletas cerca de la Línea 1 del Metro", 133, "ampliar la red ciclística de 4.8 km a 10 km", "10 km de ciclovías y 3 estaciones para bicicletas"),
        P("transporte", "Servicio municipal de transporte vecinal «Surcanito» con rutas piloto, paraderos accesibles y unidades de bajas emisiones", 133, "Programa Transporte Vecinal Sostenible y Accesible", "2 rutas y 4 unidades de transporte"),
        P("ambiente", "Ampliar la conducción de agua del Canal Surco–Ate y construir reservorios para regar áreas verdes sin agua potable", 138, "Expansión Hídrica del Canal Milenario", "50% de áreas verdes abastecidas por agua de canal al 2030"),
        P("gestion", "Programa «Surco Digital 360»: trámites digitales, expediente electrónico único, firma digital y aplicativo móvil unificado", 143, "Surco Digital 360", "90% de los trámites realizados virtualmente"),
    ]),
    ("Betty Fani Fernández Gallarday", "Partido Morado", "partido-morado", [
        P("social", "Teleasistencia las 24 horas para mayores de 70 años mediante botón de pánico o pulsera, en alianza con entidades privadas de salud", 8, "servicio de teleasistencia sociosanitaria para adultos mayores", "500 adultos mayores beneficiados inicialmente"),
        P("social", "Cunas municipales de horario extendido para niños de 1 a 3 años de familias trabajadoras", 9, "Cunas Municipales de horario extendido", "2 cunas piloto y 200 niños el primer año"),
        P("social", "Programa «Salud Responsable»: convenios con clínicas del distrito para descuentos en consultas y exámenes mediante una tarjeta municipal", 11, "descuentos de hasta el 30% en consultas médicas", "20,000 vecinos el primer año y convenios con al menos 10 clínicas"),
        P("social", "Programa «Educación Responsable»: descuentos en universidades y colegios privados y gestión de becas con embajadas", 13, "descuentos de hasta el 30% en las pensiones de estudios", "Convenios con 10 universidades y 20 colegios; al menos 100 becas"),
        P("economia", "Programa «Marca Surco» con sello de reconocimiento, plataforma digital y circuitos turísticos y gastronómicos", 14, "Diseñar y desarrollar la identidad de la Marca Surco", "Al menos 1,000 empresas y establecimientos incorporados"),
        P("economia", "Moneda digital «SurcoCoin» para premiar el pago puntual, el reciclaje y la participación, canjeable en comercios afiliados", 17, "Crear la Moneda Digital SurcoCoin", "30,000 vecinos y 1,000 comercios afiliados el primer año"),
        P("economia", "Centro de emprendimiento con incubadora de negocios municipal, capacitación y fondo de capital semilla", 19, "Implementar una Incubadora de Negocios Municipal", "200 nuevos emprendimientos incubados el primer año"),
        P("gestion", "Billetera Digital Surco para pagar tributos y arbitrios, recibir beneficios municipales y cobrar en comercios del distrito", 16, "Crear la Billetera Digital Surco, una aplicación móvil", "50,000 usuarios afiliados el primer año"),
        P("ambiente", "Descuentos en arbitrios para viviendas y empresas que instalen paneles solares, y paneles en locales municipales", 25, "instalación y funcionamiento de paneles solares", "1,000 viviendas y establecimientos en el primer año"),
        P("ambiente", "Programa «Huella Verde» con «Adopta un Árbol, Adopta un Parque» e incentivos tributarios por arborización y techos verdes", 27, "Adopta un Árbol, Adopta un Parque", "Más de 10,000 árboles sembrados o recuperados en la gestión"),
        P("gestion", "Plataforma «Agenda Transparente» con la agenda del alcalde y funcionarios, seguimiento de compromisos e indicadores de gestión", 30, "agenda institucional del alcalde, regidores y funcionarios", "100% de las agendas institucionales publicadas"),
    ]),
    ("José Carlos Bolívar Mejía", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Centro Integrado de Inteligencia Distrital que reúna cámaras, reconocimiento de placas, georreferenciación del delito, mapas de calor y alertas en tiempo real", 29, "Centro Integrado de Inteligencia Distrital"),
        P("seguridad", "Convenios con Miraflores, San Borja, La Molina y Barranco para compartir información y seguir a delincuentes que se desplazan entre distritos", 29, "Sistema Metropolitano de Seguridad Compartida"),
        P("social", "Fortalecer el primer nivel de atención con modernización de centros de salud, laboratorios básicos e historia clínica digital interoperable", 34, "Resolver al menos el 80% de los problemas de salud", "Resolver al menos el 80% de los problemas de salud sin derivación hospitalaria"),
        P("social", "Construir y equipar dos centros de salud de nivel I-4 con medicina general, pediatría, ginecología y salud mental", 50, "dos Centros Integrales de Salud de nivel I-4", "2 centros de salud I-4"),
        P("social", "Crear tres nuevos Centros Integrales de Atención al Adulto Mayor (CIAM) en zonas estratégicas del distrito", 50, "tres nuevos Centros Integrales de Atención al Adulto Mayor", "3 nuevos CIAM"),
        P("social", "Red de multilosas con iluminación LED, cámaras, wifi público y accesibilidad universal, construidas o renovadas en los barrios", 39, "Construcción o renovación de 20 a 30 espacios deportivos", "Construcción o renovación de 20 a 30 espacios deportivos barriales"),
        P("economia", "Construir dos Centros de Desarrollo Empresarial para capacitación, asesoría, formalización y acceso a financiamiento de emprendedores", 51, "dos Centros de Desarrollo Empresarial (CDE)", "Más de 10,000 emprendedores y microempresarios atendidos"),
        P("ambiente", "Planta municipal de valorización de residuos orgánicos de mercados, áreas verdes y comercios para producir compost para los parques", 51, "Planta Municipal de Valorización de Residuos Orgánicos"),
        P("transporte", "Ampliar la red de ciclovías interconectadas, con estacionamientos para bicicletas en centros comerciales, colegios y espacios públicos", 52, "red de ciclovías interconectadas con estaciones", "De 32 a 50 km de ciclovías y corredores sostenibles al 2030"),
        P("transporte", "Modernizar intersecciones con semaforización inteligente, sensores de tráfico y señalización horizontal y vertical", 52, "semaforización inteligente, sensores de tráfico"),
        P("gestion", "Gobierno digital municipal con atención virtual, expediente electrónico, interoperabilidad y digitalización de trámites", 52, "Gobierno Digital Municipal con atención virtual", "95 % de trámites digitalizados al 2030"),
    ]),
    ("Gardo Antonio Gómez Jiménez", "Integridad Democrática", "partido-politico-integridad-democratica", [
        P("seguridad", "«Surco Seguro por Cuadrantes»: microcuadrantes con serenazgo y PNP, cámaras públicas y privadas en una plataforma y tiempos de respuesta publicados", 2, "Surco Seguro por Cuadrantes", "100 % de los cuadrantes con patrullaje integrado y vigilancia aérea con la PNP al 2030"),
        P("social", "«Clínica de la Familia»: atención primaria descentralizada mediante convenios con EsSalud y MINSA, con pediatría, ginecología y salud mental", 4, "Clínica de la Familia: Establecimiento y puesta en marcha", "1 red de Clínicas de la Familia al 2030"),
        P("transporte", "Semáforos inteligentes con sensores y sincronización «Ola Verde» en Caminos del Inca, Velasco Astete, Benavides, Primavera y otras avenidas", 6, "Plan de Circulación y Semanforización Inteligente", "100 % de los ejes viales críticos con sincronización en Ola Verde al 2030"),
        P("transporte", "Gestionar y cofinanciar con la MML pasos a desnivel en las vías expresas Angamos y Benavides y en otros nudos viales", 8, "Eje Vía Expresa Benavides", "Inicio de obra de 2 corredores con pasos a desnivel al 2030"),
        P("transporte", "Empadronamiento digital de mototaxis con código QR y plan piloto para reemplazarlas por unidades colectivas eléctricas en los sectores 1, 2 y 7", 7, "Formalización y Reemplazo Progresivo de Vehículos Menores", "100 % de mototaxis formalizadas y unidades colectivas en 3 sectores piloto al 2030"),
        P("economia", "Destinar al menos el 30 % de las compras y contrataciones municipales a mypes formalizadas con domicilio fiscal en Surco", 9, "al menos el 30% de los procesos de compras", "Al menos 30 % de las compras y contrataciones directas"),
        P("ambiente", "Dejar de regar parques con agua potable y cisternas contratadas, usando agua tratada de plantas y canales con riego tecnificado", 10, "Eliminación del Uso de Agua Potable y Cisternas Contratadas", "Reducción del 25 % anual del agua potable para riego y 0 % de cisternas privadas al 2030"),
        P("ambiente", "Islas de contenedores soterrados para residuos segregados en puntos clave de los sectores, en reemplazo del recojo en aceras", 12, "islas de contenedores soterrados"),
        P("agua_riesgos", "Crear la Gerencia de Defensa Civil y Gestión del Riesgo de Desastres, con sensores IoT, sistema de información geográfica y observatorio de riesgos", 14, "nueva Gerencia de Defensa Civil y Gestión del Riesgo de Desastres", "100 % del ecosistema Smart GRD operativo al 2030"),
        P("gestion", "«App Única Surco» que reúne trámites, pagos, alertas y reportes, con un módulo para seguir el avance del presupuesto participativo", 17, "una sola aplicación móvil integrada para teléfonos inteligentes"),
        P("urbano", "Equipo «Fonoparchado» que atiende por la app baches, veredas rotas, luminarias y señalización", 18, "en un plazo no mayor a 48 horas desde el reporte vecinal", "Atención en un plazo no mayor a 48 horas desde el reporte"),
    ]),
    ("David Ignacio Vera Trujillo", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Plataforma digital de gestión integral de la seguridad con video wall y una sala de gestión de crisis", 5, "Plataforma Digital de Gestión Integral e Interoperable", "01 video wall de 12 pantallas instalado"),
        P("seguridad", "Pórticos de videovigilancia vehicular en las vías de ingreso y salida del distrito para registrar en tiempo real los vehículos", 5, "Pórticos de Video Vigilancia Vehicular colocados sobre las vías", "45 pórticos y 266 cámaras de videovigilancia vehicular; 74 vías y 133 carriles cubiertos"),
        P("seguridad", "Integrar vecinos, vigilantes y conserjes con el CCO, el serenazgo y la PNP en un sistema de vigilancia y alarma con aplicativo", 5, "vigilantes y conserjes integrados con el CCO", "700 personas integradas"),
        P("transporte", "Crear una línea de transporte urbano municipal («Surcanito») con ómnibus a gas, eléctricos o híbridos", 6, "línea de trasporte urbano municipal (Surcanito)", "01 línea nueva y 04 ómnibus eléctricos o híbridos"),
        P("transporte", "Pasos a desnivel en puntos de congestión, radares de velocidad, paraderos con paneles solares y erradicación de paraderos informales", 6, "Construcción de pasos a desnivel (By Pass)", "02 pasos a desnivel, 05 radares y 05 paraderos con paneles solares"),
        P("social", "«Tayta Wasi»: guardería municipal para adultos mayores dependientes, atendidos por profesionales mientras sus familiares trabajan", 7, "Guarderia Municipal para el adulto mayor Surcano", "60 adultos mayores y sus familias beneficiadas"),
        P("social", "«Casa de Día» de la OMAPED para personas con discapacidad mientras sus familiares trabajan", 8, "para personas con discapacidad (OMAPED) mientras sus familiares trabajan"),
        P("economia", "Reducir trámites para abrir negocios y orientar la fiscalización hacia la prevención antes que la sanción", 8, "Apoyo a los Emprendedores en el Distrito de Surco con menos tramitología"),
        P("ambiente", "Canalizar el río Surco en la nueva Av. La Castellana (cuadras 9 a 11) y crear un parque emblemático con arborización", 8, "Canalización del rio Surco en el área comprendida", "300 m lineales de canalización y 30 árboles nuevos"),
        P("ambiente", "Control de animales domésticos en la calle con campañas de esterilización y vacunación", 9, "04 campañas anuales de esterilización", "04 campañas anuales de esterilización y 12 de vacunación"),
        P("gestion", "Gobierno electrónico para reducir al mínimo los trámites presenciales, incluidos los de desarrollo urbano", 9, "80% de trámites virtuales como mínimo", "80 % de trámites virtuales como mínimo"),
    ]),
    ("Hugo Roberto Encalada Chumbile", "Partido Unidad y Paz", "partido-unidad-y-paz", [
        P("seguridad", "Contingente permanente de serenos y efectivos de la PNP en servicios extraordinarios, asignados por cuadrante territorial", 51, "desplegar un contingente permanente de 2,500 serenos municipales", "2,500 serenos y 100 efectivos de la PNP en 2027; 25 % menos victimización al 2030"),
        P("seguridad", "Cámaras con reconocimiento de placas y analítica de video en las avenidas Tomás Marsano, Benavides y Caminos del Inca", 52, "reconocimiento de placas vehiculares (LPR)"),
        P("social", "Construir una Casa de la Juventud con laboratorios de innovación digital, coworking, estudios audiovisuales e incubadora de emprendimiento", 53, "Casa de la Juventud moderna, equipada y operativa", "01 Casa de la Juventud operativa para 2028"),
        P("social", "Equipar los centros del adulto mayor con accesibilidad, consultorios de salud preventiva, talleres y asesoría legal gratuita", 54, "equipamiento integral al 100% de los centros del adulto mayor", "100 % de los centros equipados al 2029"),
        P("social", "Reducir las tarifas de los complejos deportivos municipales y crear un carnet vecinal con horarios gratuitos para escolares y adultos mayores", 59, "reducción drástica del 40% en las tarifas", "40 % menos en las tarifas en 2027"),
        P("urbano", "Ordenanza de parámetros urbanísticos que congele alturas excepcionales y exija estudios de impacto vial y factibilidad de agua y luz", 56, "congelará la aplicación de alturas excepcionales", "Ordenanza en el primer trimestre de 2027"),
        P("economia", "Programa de formalización exprés de comerciantes informales y espacios alternativos regulados para reducir el comercio ambulatorio", 60, "formalización efectiva y verificable del 35% al 40%", "35–40 % de comerciantes formalizados y 50–55 % menos comercio ambulatorio al 2030"),
        P("ambiente", "Auditar los contratos de recojo de residuos y trasladar los ahorros a los arbitrios; plan piloto de contenedores soterrados", 62, "auditoría integral y fiscalización del 100% de los contratos", "100 % de contratos auditados en 2027 y hasta 10 % de ahorro en costos"),
        P("ambiente", "Cuadrillas de contingencia para el mantenimiento de áreas verdes del Sector 1 y riego tecnificado con agua residual tratada", 63, "capacidad de 50 operarios en el año 2027", "50 operarios en 2027 y 100 % de áreas verdes con mantenimiento y riego tecnificado al 2030"),
        P("agua_riesgos", "Estudio de capacidad de las redes de agua y luz para condicionar licencias y exigir a SEDAPAL y Luz del Sur renovar redes", 64, "Estudio Técnico de Capacidad de Soporte del Subsuelo", "Estudio culminado en 2028; 100 % de nuevas licencias multifamiliares con factibilidad certificada al 2030"),
        P("gestion", "Plataforma digital única para trámites, pagos y licencias, y alfabetización digital para adultos mayores en los CIAM", 69, "Integrar el 100% de los trámites administrativos digitalizables del TUPA", "100 % de trámites digitalizables del TUPA en la plataforma al 2030"),
    ]),
    ("Ruth Candelaria Bisbal Oyague", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Patrullaje sectorizado con rutas asignadas según mapas de calor del delito y un policía en las unidades del serenazgo en cada turno", 12, "plan de patrullaje sectorizado inteligente", "98 % de los patrullajes en zonas críticas bajo modalidad integrada al 2030"),
        P("seguridad", "Renovar la videovigilancia con cámaras de alta definición e inteligencia artificial para reconocimiento de placas y alertas de vehículos sospechosos", 13, "reconocimiento automático de placas vehiculares (LPR)", "100 % de la red de videovigilancia integrada con inteligencia artificial al 2030"),
        P("transporte", "Semáforos inteligentes con sincronización adaptativa en tiempo real, priorizando las avenidas Benavides y Primavera", 18, "semáforos inteligentes y sincronización vial adaptativa", "Reducir el Índice de Tiempo de Viaje a 1.2 veces al 2030"),
        P("transporte", "Educación vial y obras de seguridad en zonas residenciales, comerciales y escolares, con reductores de velocidad y pasos peatonales elevados", 20, "instalando reductores de velocidad homologados", "Reducción del 50 % en el índice de siniestralidad vial al 2030"),
        P("social", "Modernizar Surco Salud con equipamiento biomédico, más especialidades preventivas y agendamiento electrónico de citas", 31, "servicios e infraestructura de Surco Salud", "100 % de los servicios municipales de salud preventiva modernizados y digitalizados al 2030"),
        P("economia", "Ventanilla Única Digital y aprobación automática de licencias para giros de riesgo bajo y medio («Licencia Cero»)", 71, "aprobación automática para giros de riesgo bajo y medio", "Licencias en un máximo de 24 horas"),
        P("economia", "Ruta Turística e Histórica de Surco Pueblo (Iglesia Santiago Apóstol, bodegas vitivinícolas, casonas) articulada con restaurantes tradicionales", 77, "Ruta Turística e Histórica de Surco Pueblo", "150,000 visitantes anuales al 2030"),
        P("ambiente", "Ampliar los servicios veterinarios de Surco Pet, con más equipamiento quirúrgico, horarios de urgencias y campañas itinerantes de vacunación", 82, "fortalecimiento y ampliación de los servicios de Surco Pet", "30,000 atenciones veterinarias anuales al 2030"),
        P("ambiente", "Reemplazar el riego por inundación o cisterna por riego tecnificado por goteo y microaspersión con agua tratada", 91, "riego tecnificado por goteo y microaspersión alimentados con agua tratada", "90 % de la infraestructura verde con riego tecnificado y agua tratada al 2030"),
        P("urbano", "Programa «Surco Ordenado y Residencial» para proteger la identidad residencial y fiscalizar la zonificación y los usos del suelo", 95, "marco de intangibilidad y protección de la identidad residencial"),
        P("gestion", "Aplicación móvil «Surco 24/7» con trámites, alertas de seguridad, reportes de ornato y pagos, más asistentes virtuales", 112, "empaquetando trámites claves, alertas de seguridad", "75 % de las interacciones vecinales en plataformas digitales al 2030"),
    ]),
    ("Óscar Mario Aco Miranda", "Progresemos", "progresemos", [
        P("seguridad", "Red sectorial en la que cada sector cuente con vehículos de serenazgo y policía, motos y comunicación radial y telefónica", 15, "Crear la red sectorial, en la que cada sector cuente con vehículos"),
        P("social", "Centros Municipales de Bienestar Emocional con atención psicológica preventiva y campañas de salud mental en colegios", 13, "Centros Municipales de Bienestar Emocional"),
        P("social", "Programa «Deporte Gratuito para Todos» con escuelas deportivas municipales gratuitas y uso intensivo del Estadio Julio Montjoy", 13, "Uso intensivo del Estadio Julio Montjoy"),
        P("economia", "Primer inventario distrital de actividades económicas y comercio ambulatorio, con formalización progresiva del comercio ambulante", 18, "primer Inventario Distrital de Actividades Económicas"),
        P("economia", "Ventanilla Única Empresarial, licencias digitales y programa «Licencia Rápida Surco» para pequeños negocios de bajo riesgo", 18, "Crear la Ventanilla Única Empresarial para simplificar trámites"),
        P("ambiente", "Nuevas veterinarias municipales, más albergues para animales abandonados y campañas gratuitas de vacunación y esterilización", 20, "Implementación de nuevas veterinarias municipales"),
        P("ambiente", "Riego tecnificado en parques y bermas y uso de aguas residuales tratadas para regar áreas verdes", 20, "uso de aguas residuales tratadas en el riego de áreas verdes"),
        P("agua_riesgos", "Actualizar el mapa de riesgos, identificar zonas vulnerables y formar brigadas vecinales con simulacros en colegios y mercados", 21, "Actualización permanente del mapa de riesgos del distrito"),
        P("transporte", "Estudios de circulación, semaforización inteligente en puntos críticos y seguridad vial en zonas escolares y comerciales", 23, "Semaforización inteligente en puntos críticos"),
        P("urbano", "Programa de mantenimiento y rehabilitación de pistas y veredas, priorizando las vías más deterioradas", 23, "Programa integral de mantenimiento y rehabilitación de pistas y veredas"),
        P("gestion", "Digitalización de trámites, plataforma virtual de atención y seguimiento en línea de expedientes", 24, "Seguimiento en línea de expedientes"),
    ]),
    ("Juan Alejandro Palma Aurazo", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "«Serenazgo sin puntos ciegos»: reactivar bases y patrullaje a pie en Monterrico Sur, Prolongación Benavides, La Cruceta e Higuereta", 64, "reactivación y ampliación de bases y patrullaje interno a pie"),
        P("seguridad", "Auditar y reparar las cámaras inoperativas e integrarlas al Centro de Inteligencia de Seguridad del proyecto Surco Seguro 360°", 64, "auditoría, reparación y repotenciación de las cámaras"),
        P("social", "Centro de urgencias abierto las 24 horas y una flota municipal de ambulancias", 68, "CENTRO DE URGENCIAS LAS 24 HORAS"),
        P("social", "Implementar tres centros de salud mental con equipos multidisciplinarios", 69, "Implementación de tres centros de salud mental", "Tres centros de salud mental operativos"),
        P("social", "Construir un polideportivo moderno de referencia metropolitana y reacondicionar losas deportivas en los parques", 70, "POLIDEPORTIVO MÁS MODERNO DE LIMA METROPOLITANA"),
        P("transporte", "Prolongar la Av. Surco hasta la Av. Jorge Chávez, gestionando el terreno de la FAP", 71, "PROLONGACIÓN DE LA AV. SURCO PARA CONECTAR CON LA AV. JORGE CHÁVEZ"),
        P("transporte", "By-pass paralelo al tren eléctrico en La Bolichera para reducir la congestión", 71, "BY-PASS PARALELO AL TREN ELÉCTRICO EN LA BOLICHERA"),
        P("ambiente", "Recuperar la Loma Amarilla como parque ecológico con cobertura vegetal, senderos y educación ambiental", 67, "RECUPERACIÓN Y RELANZAMIENTO DE LA LOMA AMARILLA"),
        P("economia", "Programa «Surco Emprende Digital» con Escuela Municipal de Emprendedores, centro de innovación y Marketplace Surcano", 41, "Escuela Municipal de Emprendedores"),
        P("urbano", "Revisar los parámetros urbanísticos frente a la proliferación de edificios que afectan la residencialidad", 65, "revisión de los parámetros urbanísticos frente a la proliferación de edificios"),
        P("gestion", "Devolver a los vecinos la administración de locales comunales y concertar la ubicación de nuevas Casas del Vecino", 65, "devolución de la administración de locales comunales"),
    ]),
]
