"""Rímac (150128): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150128"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Javier Víctor Revilla Belisario", "Acción Popular", "accion-popular", [
        P("seguridad", "Seguridad ciudadana integral con participación conjunta de la municipalidad, los vecinos y la Policía Nacional", 13, "seguridad ciudadana integral en la que participen la Municipalidad"),
        P("gestion", "Reorganizar el área de Rentas, actualizar sus sistemas informáticos y promover la reducción de los arbitrios municipales", 18, "Promover la Reducción del monto por concepto de Arbitrios Municipales"),
        P("gestion", "Incrementar progresivamente el porcentaje del presupuesto destinado al Presupuesto Participativo para proyectos de inversión", 17, "porcentaje asignado al Presupuesto Participativo para Proyectos de Inversión"),
        P("social", "Construir e implementar la «Casa de la Juventud Rimense»", 18, "CASA DE LA JUVENTUD RIMENSE"),
        P("social", "«Mesa Educativa» liderada por la municipalidad con la UGEL, directores, docentes, padres de familia y estudiantes", 18, "liderada por el gobierno local del distrito, integrada por el director de la UGEL"),
        P("social", "Escuelas municipales de fútbol, vóley, básquet, boxeo y ajedrez para la formación de nuevos deportistas", 19, "de Futbol, Voley, Básquet, Boxeo y Ajedrez"),
        P("transporte", "Promover y construir ciclovías en las principales vías del distrito", 19, "CICLO VÍAS RIMENSES"),
        P("transporte", "Trabajar con la Municipalidad de Lima el teleférico que unirá el parque de la Muralla con el cerro San Cristóbal", 20, "que unirá el parque de la Muralla con el cerro San Cristóbal"),
        P("economia", "Rehabilitar la Alameda de los Descalzos como eje turístico e integrarla con el Paseo de Aguas", 20, "Rehabilitar la Alameda de los Descalzos para promover actividades culturales"),
        P("economia", "Empadronar al comercio informal e integrarlo a mesas de trabajo para apoyar la formalización de sus negocios", 21, "Empadronamiento del Comercio Informal e integrarlos a mesas de trabajo"),
        P("economia", "Programa «Trabajando Rímac»: bolsa de trabajo municipal con convenios para que empresas privadas soliciten personal", 21, "TRABAJANDO RIMAC"),
    ]),
    ("Jonathan Enrique Seña Manguinury", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Patrullaje integrado entre serenazgo, PNP y juntas vecinales con vigilancia sectorizada por cuadrantes, bajo el CODISEC", 2, "aplicando vigilancia sectorizada por cuadrantes", "Reducción de denuncias de 15 % (2027) y 45 % acumulada (2030)"),
        P("seguridad", "Central de monitoreo con cámaras con inteligencia artificial y arcos lectores de placas, interconectada con comisarías", 3, "600 cámaras y 12 arcos operativos", "200 cámaras (2027); 600 cámaras y 12 arcos (2030)"),
        P("seguridad", "Módulo «Rímac Te Cuida» de flagrancia delictiva en convenio con el Poder Judicial y el Ministerio Público", 3, "Módulo construido y operando con fiscales y jueces en tiempo real"),
        P("social", "Plan «Nutri-Rímac» articulado con comedores populares y huertos escolares para combatir la anemia y la desnutrición infantil", 4, "combatir la anemia y desnutrición crónica en el distrito", "Anemia en menores de 36 meses al 22 % (2027) y a menos del 10 % (2030)"),
        P("economia", "Ventanilla única de formalización para otorgar licencias e ITSE a las mypes en un máximo de 72 horas", 8, "en un plazo máximo de 72 horas para MYPES", "1,200 mypes formalizadas (2027) y 4,500 (2030)"),
        P("economia", "Corredor turístico-gastronómico Paseo de Aguas - Alameda de los Descalzos - Convento de los Descalzos con información digital", 8, "600,000 turistas anuales", "180,000 turistas anuales (2027) y 600,000 (2030)"),
        P("ambiente", "Campaña «Rímac Verde» de arborización de laderas con especies nativas y plantas de tratamiento de aguas residuales para riego", 11, "Campaña masiva de arborización y forestación urbana en laderas", "6.0 m² de área verde por habitante y 2 plantas de tratamiento (2030)"),
        P("urbano", "Plan distrital de pavimentación, bacheo y renovación de veredas con accesibilidad y bandas podotáctiles en vías secundarias", 13, "65 km de vías internas totalmente renovadas", "20 km (2027) y 65 km de vías renovadas (2030)"),
        P("agua_riesgos", "Plan de mitigación en laderas: muros de contención, estabilización de taludes y escaleras con barandas e iluminación solar", 13, "mediante andenerías y muros de contención", "90 infraestructuras de mitigación operativas al 2030"),
        P("transporte", "Registro integral de mototaxis, actualización del plan regulador y fiscalización con un aplicativo y código QR", 14, "aplicativo Android mediante lectura de código QR", "100 % de vehículos menores formalizados al 2030"),
        P("gestion", "Estrategia «Tramitología Cero»: digitalizar todos los procedimientos del TUPA en una ventanilla única virtual", 15, "Tramitología Cero", "55 % de trámites digitalizados (2027) y 100 % (2030)"),
    ]),
    ("Enrique Armando Peramas Díaz", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Tres módulos de intervención rápida en las zonas altas con motos y cuatrimotos, con patrullaje integrado sereno-policía", 2, "Módulos de Intervención Rápida", "Respuesta en los cerros de 02 horas a menos de 5 minutos en 06 meses"),
        P("seguridad", "Cambiar luminarias de sodio por LED en puntos críticos y recuperar plazas y huacas con actividades culturales", 3, "tecnología LED blanca de alta potencia en 40 puntos críticos", "100 % de puntos críticos iluminados en los primeros 12 meses"),
        P("seguridad", "Programa «Incentivo por tu Seguridad»: empresas financian vehículos, cámaras o casetas a cambio de beneficios u Obras por Impuestos", 4, "Incentivo por tu Seguridad", "Inversión privada equivalente al 40 % del presupuesto de seguridad"),
        P("transporte", "Empadronamiento digital obligatorio de mototaxis con chalecos con código QR y retiro de unidades no registradas", 4, "chalecos con Código QR", "100 % de formalización en un plazo no mayor a 9 meses"),
        P("urbano", "Fondo municipal para reparaciones urgentes en quintas y solares en riesgo: escaleras, balcones, pisos, cañerías y desagües", 5, "fondo ad-hoc municipal destinado a reparaciones urgentes", "Intervenir el 85 % de predios en riesgo crítico en el primer bienio"),
        P("economia", "Peatonalización progresiva de calles del Centro Histórico y circuito turístico de 18 estaciones", 5, "circuito turístico de 18 estaciones", "100 % del circuito peatonalizado en 24 meses; +250 % de turistas al 2030"),
        P("social", "Ampliar el programa «Rímac + Sinfonía» con campeonatos deportivos, cine comunitario y talleres contra el bullying", 6, "Masificación del programa", "Más de 5,000 menores incorporados en 3 años"),
        P("agua_riesgos", "Cartera priorizada de muros de contención en zonas altas financiada con cooperación técnica internacional", 7, "cartera de proyectos priorizados para la construcción de muros de contención", "100 % de la cartera viabilizada en 18 meses"),
        P("gestion", "Capacitación anticorrupción obligatoria del personal y audiencias mensuales descentralizadas «Tu Alcalde en tu Barrio»", 7, "Tu Alcalde en tu Barrio", "100 % del personal capacitado en los primeros 12 meses"),
        P("economia", "Plataforma «Rímac Digital: Licencia Express» con firma digital para emitir licencias de bajo riesgo", 8, "Rímac Digital: Licencia Express", "Licencias de bajo riesgo en un máximo de 24 horas"),
        P("ambiente", "Programa «Rímac Limpio y Sostenible»: rutas con GPS en compactadoras, contenedores soterrados y premios a barrios que reciclan", 9, "Rímac Limpio y Sostenible", "Erradicar el 90 % de botaderos informales en 18 meses"),
    ]),
    ("Adelina Rivera Escudero", "Fe en el Perú", "fe-en-el-peru", [
        P("seguridad", "Dividir el distrito en cuadrantes con responsables, rutas de patrullaje y mapa de incidencia delictiva", 8, "Cada cuadrante contará con responsables, rutas de patrullaje", "Reducir en 20 % las incidencias priorizadas"),
        P("seguridad", "Bases descentralizadas de serenazgo en Cerro San Cristóbal, San Juan de Amancaes, Mariscal Castilla y Centro Histórico", 8, "Se implementarán puntos operativos en zonas estratégicas", "Reducir en 30 % el tiempo promedio de respuesta"),
        P("seguridad", "Flota de drones para patrullaje y emergencias en zonas de difícil acceso", 8, "flota inicial de cuatro drones", "4 drones operativos"),
        P("social", "Policlínico municipal con medicina general, odontología, nutrición, psicología, obstetricia y laboratorio", 11, "Policlínico municipal integral", "1 policlínico operativo"),
        P("agua_riesgos", "Programa «Agua Segura»: almacenamiento seguro, educación sobre cloración y gestión de proyectos de agua en zonas con anemia", 11, "Programa Agua Segura", "Intervenir 80 % de zonas críticas"),
        P("ambiente", "Mapa georreferenciado de puntos críticos de basura, rutas de recojo rediseñadas y sanciones a reincidentes", 14, "mapa georreferenciado de puntos críticos de basura", "Reducir en 50 % los puntos críticos"),
        P("urbano", "Construir y rehabilitar escaleras con barandas, iluminación y señalización en zonas altas", 16, "Construcción y rehabilitación de escaleras con barandas", "100 rutas críticas intervenidas"),
        P("economia", "Ordenar el comercio con empadronamiento, zonas autorizadas, reglas claras y fiscalización gradual", 18, "Empadronamiento, zonas autorizadas, reglas claras", "2000 negocios formalizados"),
        P("transporte", "Formalizar mototaxis con empadronamiento, identificación de unidades, chalecos o códigos y zonas autorizadas", 20, "Empadronamiento, identificación de unidades, chalecos/códigos", "70 % de unidades formalizadas"),
        P("social", "CETPRO municipal con cursos de drywall, soldadura, electricidad, cocina, computación y gasfitería", 22, "CETPRO Municipal del Rímac", "1 CETPRO operativo y 4000 jóvenes capacitados"),
        P("gestion", "Actualizar el SISFOH, crear un mapa social georreferenciado y un panel de control municipal con indicadores por eje", 24, "Panel de control con indicadores por eje", "100 % de hogares priorizados empadronados"),
    ]),
    ("Luz Elena Flores Ledesma", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("social", "«Rímac Nutritivo y Saludable»: monitoreo nutricional itinerante y talleres de cocina rica en hierro en comedores y ollas comunes", 5, "centros de monitoreo nutricional itinerante", "Anemia infantil a menos del 15 % y desnutrición crónica a menos del 5 %"),
        P("seguridad", "«Rímac Seguro y Tradicional»: patrullaje integrado con la PNP, tótems de emergencia y reactivación de juntas vecinales", 6, "instalación de tótems de emergencia", "Victimización al 18 % y 100 % de cuadrantes interconectados a una central"),
        P("urbano", "«Vivienda Digna»: gestionar con SEDAPAL y eléctricas la renovación de redes y el reforzamiento de quintas y casonas", 7, "renovación de redes matrices, asistencia técnica para el reforzamiento estructural", "95 % de conexiones formales y seguras de servicios básicos"),
        P("economia", "«Emprende Rímac»: licencias simplificadas, asistencia técnica y ferias itinerantes para reubicar a comerciantes ambulantes", 8, "ferias comerciales itinerantes organizadas para la reubicación concertada", "Formalizar y reordenar al 60 % del comercio ambulatorio registrado"),
        P("economia", "«Rímac: Cuna de la Tradición»: corredores turísticos peatonales y ferias gastronómicas permanentes en las alamedas históricas", 8, "corredores turísticos peatonales seguros", "Duplicar el flujo turístico y formalizar 200 nuevos emprendimientos"),
        P("social", "«Infancia a Salvo»: operativos de rescate de niños en trabajo infantil y talleres gratuitos a contraturno escolar", 9, "Infancia a Salvo en el Rímac", "Trabajo infantil callejero a menos del 0.5 %"),
        P("agua_riesgos", "«Pasajes y Pistas para la Salud»: pavimentación de accesos, escaleras solidarias y muros de contención en laderas altas", 10, "construcción de escaleras solidarias y muros de contención en las laderas altas", "Reducir al 35 % el déficit de pavimentación en laderas"),
        P("ambiente", "«Rímac Limpio y Sostenible»: nuevas rutas de recojo, contenedores soterrados en zonas monumentales y segregación «Rímac Recicla»", 10, "instalación de contenedores soterrados en zonas monumentales", "100 % de recolección eficiente y erradicación de botaderos"),
        P("ambiente", "«Río Rímac Resplandece»: sancionar el arrojo de desmonte, videovigilancia ambiental en malecones y Parque Ribereño Ecológico", 10, "colocación de videovigilancia ambiental en los malecones", "Recuperar el 100 % del tramo ribereño del distrito"),
        P("gestion", "«Modernización Tributaria»: pago digital de tributos, amnistías con incentivos de obras y actualización catastral", 11, "Digitalización total del pago de tributos", "Recaudación al 75 % del presupuesto y morosidad reducida en 40 %"),
        P("transporte", "«Movilidad Ordenada»: fiscalización con la ATU y la PNP, rediseño de intersecciones y empadronamiento de mototaxis con QR", 13, "ordenamiento geométrico de intersecciones críticas", "100 % de asociaciones de mototaxis formalizadas"),
    ]),
    ("Felicidad Emperatriz Salhuana Serna", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("social", "Campañas médicas para la detección temprana de enfermedades, con alianzas con clínicas y hospitales privados", 11, "Llevar unas 30 campañas medica anuales al 2030", "30 campañas médicas anuales al 2030"),
        P("ambiente", "Colocar contenedores y coordinar con comerciantes para reducir la basura acumulada en mercados y zonas comerciales", 12, "Reducir en un 50% la acumulación de basura en los mercados", "Reducir en 50 % la basura en mercados en un año"),
        P("seguridad", "Talleres de reforzamiento escolar y vigilancia de serenos en las horas de entrada y salida de los colegios", 13, "fortalecer la vigilancia de los serenos en las horas de entradas y salidas", "50 % de participación de estudiantes en los talleres"),
        P("urbano", "Programas de rehabilitación y mantenimiento anual de edificios patrimoniales y monumentos", 13, "Disminuir en un 30% del abandono de edificios patrimoniales", "Disminuir en 30 % el abandono de edificios patrimoniales"),
        P("social", "Rampas, señalización y espacios accesibles, e inclusión laboral de personas con discapacidad en la municipalidad", 15, "Alcanzar entre 60% a 80% de veredas con rampas accesibles", "60 % a 80 % de veredas con rampas y 5 % de trabajadores con discapacidad"),
        P("economia", "Censar a los comerciantes informales y reubicarlos en mercados o ferias autorizadas", 16, "Registrar y censar al 100% de los comerciantes informales", "Reubicar al 60 a 70 % de vendedores en un plazo de 128 meses"),
        P("economia", "Ejecutar obras de infraestructura mediante Obras por Impuestos con empresas privadas", 16, "Alcanzar el 80% de proyectos de infraestructura se ejecuten dentro del plazo", "80 % de proyectos dentro del plazo en 3 años"),
        P("gestion", "Modernización tributaria con incentivos por pronto pago, actualización de la base de contribuyentes y campañas de educación tributaria", 17, "Disminuir la tasa de morosidad de un aproximadamente de 40% a 25% en un año", "Morosidad de 40 % a 25 % en un año; atención en 15 minutos"),
        P("seguridad", "Cámaras con enlace a la PNP en puntos vulnerables y comunicación unificada para responder a emergencias", 18, "Debe oscilar entre 5 a 10 minutos aproximadamente de respuesta rápida", "Respuesta de 5 a 10 minutos ante incidencias"),
        P("seguridad", "Convenios de mancomunidad con los municipios colindantes para la persecución de delincuentes", 18, "Logro de cuatro convenios con los municipios aledaños", "Cuatro convenios con municipios aledaños"),
        P("ambiente", "Ampliar la cobertura de recolección de basura aplicando el plan de manejo de residuos sólidos del Rímac", 20, "Ampliar cada año en un 20% a 30% de recolección de basura", "Ampliar la recolección entre 20 % y 30 % cada año"),
    ]),
    ("Roberto Abelardo Telles Jaramillo", "Partido del Buen Gobierno", "partido-del-buen-gobierno", [
        P("seguridad", "Crear la Escuela de Serenazgo Municipal, aumentar el personal y patrullar en forma integrada con la PNP", 9, "Creación e implementación de la Escuela de Serenazgo Municipal"),
        P("seguridad", "Cámaras con inteligencia artificial en ingresos y salidas del distrito, drones, alarmas vecinales y «Serenazgo sin fronteras»", 9, "principalmente en los ingresos y salidas del distrito"),
        P("social", "Casa de la Juventud, de la Mujer, del Adulto Mayor y de Personas con Discapacidad integradas en un solo espacio", 10, "integrados en un solo espacio"),
        P("social", "Academia preuniversitaria municipal y de emprendimiento gratuita, con alianzas con UGEL, universidades y CETPRO", 12, "Academia PreUniversitaria Municipal y de Emprendimiento Rimense"),
        P("social", "Repotenciar y reubicar el Policlínico Municipal con «Salud Municipal 24/7», telesalud y un bus médico móvil", 15, "Salud Municipal 24/7"),
        P("economia", "Plan de Desarrollo Económico Local y mesa distrital con los agentes económicos para ordenar y formalizar el comercio", 17, "Mesa Distrital de Promoción del Desarrollo Económico Local"),
        P("urbano", "Pistas, veredas, bermas, escaleras con barandas y muros de contención en las partes altas, y programa «Bacheo»", 18, "escaleras con barandas y muros de contención necesarias en las partes altas"),
        P("agua_riesgos", "Fortalecer la microzonificación para identificar zonas de mayor riesgo ante desastres y generar espacios de refugio", 18, "programas de microzonificación distrital"),
        P("transporte", "Programa «La calle no es cochera» contra vehículos abandonados y reordenamiento de rutas y paraderos de vehículos menores", 20, "La calle no es cochera"),
        P("ambiente", "Plan de recolección con rutas y horarios, vehículos de repaso y unidades adaptadas para las partes altas", 21, "vehículos de repaso para todos los sectores del distrito"),
        P("gestion", "Gobierno digital «Cero Trámites» con digitalización total de procesos y Defensoría del Vecino para quejas", 24, "Cero Trámites"),
    ]),
    ("Henry Alex Cifuentes Carrillo", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Convenios de patrullaje integrado entre serenazgo y las comisarías El Rímac, Piedra Liza y Ciudad y Campo", 9, "Piedra Liza y Ciudad y Campo"),
        P("seguridad", "Renovar la central de videovigilancia con cámaras con reconocimiento facial y de placas en entradas y salidas", 10, "reconocimiento facial y la detección automática de placas"),
        P("social", "Policlínicos municipales itinerantes semanales con consultas gratuitas, priorizando zonas altas y de difícil acceso", 10, "Programa de Policlínicos Municipales Itinerantes"),
        P("social", "Casa de la Mujer Rimense con refugio temporal, asesoría legal frente a la violencia y capacitación productiva", 12, "Implementación de la Casa de la Mujer Rímense"),
        P("urbano", "Oficina de saneamiento predial con brigadas técnico-legales para titular asentamientos humanos con COFOPRI", 14, "Oficina Distrital de Saneamiento y Formalización Predial"),
        P("agua_riesgos", "Programa de muros de contención y pircas técnicas en taludes críticos, y sirenas de alerta temprana en los cerros", 15, "Programa Masivo de Muros de Contención"),
        P("ambiente", "Rediseñar rutas y horarios de recojo con GPS en compactadoras y sancionar a quienes arrojen basura fuera de horario", 16, "fiscalización por GPS en los camiones compactadores"),
        P("transporte", "Empadronar y zonificar a las asociaciones de mototaxis con la ATU y la Policía de Tránsito, y erradicar paraderos informales", 17, "zonificación estricta de las asociaciones de mototaxis"),
        P("economia", "Corredor turístico seguro del Puente de Piedra a la Alameda de los Descalzos, custodiado por «Serenos del Turismo»", 18, "desde el Puente de Piedra hasta la Alameda de los Descalzos"),
        P("gestion", "Plataforma «Rímac Digital» de trámites sin papel con seguimiento en línea de licencias, pagos y mesa de partes", 20, "Plataforma de Trámite Cero Papel"),
        P("gestion", "Equipar las agencias municipales de las zonas altas para realizar trámites, pagos y denuncias sin ir a la sede central", 21, "Potenciación de Agencias Municipales Periféricas"),
    ]),
    ("José Alberto Angulo Domínguez", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Construir nuevos centros de monitoreo y renovar las cámaras de videovigilancia con inteligencia artificial", 5, "Construcción de nuevos centros de monitoreo de cámaras de vigilancia"),
        P("seguridad", "Escuela de formación de serenos del Rímac, con capacitación en convenio con el Ministerio del Interior", 6, "Creación de la escuela de formación de serenos del Rimac"),
        P("social", "Médicos de cabecera que visiten en sus hogares a adultos mayores y personas vulnerables identificadas", 6, "Programas de atención de médicos de cabecera"),
        P("social", "Convenios con academias, institutos y universidades para becas de estudio para jóvenes", 7, "acceder a becas de estudio en su preparación académica"),
        P("urbano", "Gestionar ante el Ministerio de Vivienda y el INC la mejora de las casonas antiguas declaradas patrimonio", 6, "mejoramiento de la infraestructura y habitabilidad de las casonas antiguas"),
        P("transporte", "Formalizar mototaxis: sensibilización, asociaciones de conductores formales, operativos y capacitación en normas de tránsito", 7, "Reducir los índices de informalidad de mototaxis"),
        P("economia", "Circuitos turísticos en lugares históricos, con convenios con el INC, MINCETUR, agencias y sector privado", 8, "generando circuitos turísticos"),
        P("economia", "Simplificar el trámite de licencias de funcionamiento y capacitar a comerciantes en gestión, tributos y ventas", 8, "Simplificación administrativa para las licencias de funcionamiento"),
        P("ambiente", "Planta de tratamiento de residuos sólidos concesionada por licitación, con programas de reciclaje vecinal", 9, "Contar con una planta de tratamiento de residuos sólidos"),
        P("agua_riesgos", "Reforzar las bases de las laderas y construir muros de contención en las vías en pendiente", 10, "Construcción de muros de contención que permitan reforzar las vías"),
        P("gestion", "Declarar en emergencia económica, financiera y administrativa a la municipalidad y buscar nuevas fuentes de financiamiento", 11, "Declarar en emergencia económica, financiera, administrativa y sanitaria"),
    ]),
    ("Jericó Edward Mosquera Torres", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Plan «Ojos del Rímac»: renovar la central de monitoreo con fibra óptica y cámaras con reconocimiento facial y de placas", 12, "instalación de 300 nuevas cámaras de videovigilancia", "300 nuevas cámaras con inteligencia artificial"),
        P("seguridad", "Duplicar progresivamente los serenos y patrullaje integrado con un policía por unidad móvil, en 8 cuadrantes vigilados", 12, "dividiendo el distrito en 8 cuadrantes", "Reducir en 45 % la percepción de inseguridad al 2030"),
        P("transporte", "Plan «Pistas Dignas»: reasfaltado y reparación de veredas en las avenidas Tarapacá, Alcázar, Pizarro, Amancaes y Tacna", 13, "Plan Intensivo de Rehabilitación Vial", "Recuperar la transitabilidad del 80 % de las vías colectoras e internas"),
        P("agua_riesgos", "Programa «Laderas Seguras»: muros de contención en zonas de alto riesgo y escaleras con barandas («Pasajes Solidarios»)", 13, "Laderas Seguras y Resilientes"),
        P("urbano", "Unidad técnica de asesoría gratuita para acelerar la titulación y habilitación urbana de asentamientos ante COFOPRI y SUNARP", 14, "Plan de Saneamiento Físico-Legal Urbano"),
        P("social", "Programa «Lozas de Mi Barrio»: rehabilitar, techar e iluminar lozas deportivas, con escuelas deportivas municipales gratuitas", 14, "Lozas de Mi Barrio", "Recuperar el 100 % de la infraestructura deportiva municipal"),
        P("social", "Policlínicos municipales móviles «Muni-Salud» que recorran semanalmente laderas y zonas tugurizadas con atención gratuita", 15, "Policlínicos Municipales Móviles"),
        P("economia", "«Muni-Emprende Fast»: licencias de funcionamiento provisionales gratuitas en 24 horas para negocios de bajo riesgo", 16, "Muni-Emprende Fast", "Incrementar en 50 % la formalización del comercio local"),
        P("economia", "Corredor turístico peatonal «El Rímac de Antaño» del Puente de Piedra al Paseo de Aguas, con serenazgo turístico", 16, "El Rímac de Antaño"),
        P("ambiente", "Reingeniería del recojo de basura con GPS en compactadoras y contenedores soterrados en puntos críticos", 17, "Eliminación de los 25 puntos críticos", "Eliminar los 25 puntos críticos de acumulación de basura"),
        P("gestion", "Auditoría forense independiente de gestiones anteriores y plan de refinanciamiento de la deuda municipal", 18, "Auditoría Forense Integral", "Auditoría en los primeros 60 días de gestión"),
    ]),
    ("Antonio Harry Cocha Camargo", "PRIN", "partido-politico-prin", [
        P("seguridad", "Plan «Rímac Seguro»: cámaras con inteligencia artificial interconectadas y patrullaje integrado vecinal-PNP-serenazgo por cuadrantes", 21, "Interconexión del 100% de cámaras", "100 % de cámaras interconectadas con inteligencia artificial"),
        P("seguridad", "Drones de vigilancia para supervisar zonas de difícil acceso y alta incidencia delictiva", 28, "Unidades de Vigilancia Aérea Táctica"),
        P("social", "Instituto Técnico Municipal gratuito con carreras de gastronomía, turismo, soporte tecnológico y edificaciones", 29, "Instituto Técnico Municipal Gratuito"),
        P("social", "Construir un colegio municipal piloto para atender el déficit de vacantes en sectores vulnerables", 29, "Colegio Municipal del Rímac"),
        P("agua_riesgos", "Programa «Laderas Seguras»: muros de contención certificados y escaleras con pasamanos en asentamientos humanos", 28, "construcción de muros de contención certificados y escaleras de concreto"),
        P("agua_riesgos", "Cronograma de limpieza de las riberas del río Rímac en coordinación con la Autoridad Nacional del Agua", 26, "Limpieza de cauces"),
        P("transporte", "Plan maestro de conectividad vial: renovar el asfalto de avenidas y vías locales con señalización y semáforos inteligentes", 28, "Plan Maestro de Conectividad Vial"),
        P("ambiente", "Reorganizar las rutas de recojo de basura, optimizar la flota de compactadoras y promover la segregación en la fuente", 29, "Gestión Ecoeficiente de Residuos Sólidos"),
        P("economia", "Corredor histórico «Abajo el Puente»: recuperar fachadas, iluminar monumentos y peatonalizar la Alameda y el Paseo de Aguas", 29, "Corredor Histórico"),
        P("economia", "Reubicar el comercio ambulatorio en mercados zonales y otorgar licencias digitales en 24 horas", 29, "licencias digitales en 24 horas", "Licencias digitales en 24 horas"),
        P("gestion", "«Municipio Digital»: virtualizar los procedimientos del TUPA para pagar arbitrios y tramitar licencias sin ir al municipio", 30, "Virtualización del 100% de los procedimientos del TUPA", "100 % de los procedimientos del TUPA virtualizados"),
    ]),
    ("Efigenia Rosario Arnao Infantas", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Centro de control y monitoreo con videovigilancia, en coordinación con el sector privado", 8, "Implementar un centro de control y monitoreo"),
        P("seguridad", "Observatorio del delito y mapa de riesgos sociales del distrito con el Comité Distrital de Seguridad Ciudadana", 8, "Implementar un observatorio del delito"),
        P("seguridad", "Programa «Serenazgo Ciudadano» con incentivos para las organizaciones sociales que participen", 8, "Serenazgo Ciudadano"),
        P("social", "Servicios de salud móvil en sectores vulnerables con poca cobertura médica", 9, "Implementar servicios de salud móvil"),
        P("social", "Plan de reinserción social para adolescentes y jóvenes que quieran integrarse a la vida comunitaria y productiva", 9, "Plan de Reinserción Social"),
        P("economia", "Asesoramiento municipal para formalizar el comercio ambulatorio y a las micro y pequeñas empresas", 9, "Apoyar la formalización del comercio ambulatorio"),
        P("urbano", "Promover la reconversión urbana de inmuebles deteriorados", 10, "reconversión urbana de inmuebles"),
        P("agua_riesgos", "Fortalecer la microzonificación para identificar las áreas de mayor riesgo frente a desastres", 10, "programas de microzonificación distrital"),
        P("ambiente", "Plan Distrital de Arborización del Rímac", 10, "Plan Distrital de Arborización"),
        P("transporte", "Coordinar con Lima Metropolitana la reestructuración de rutas de transporte público en zonas monumentales", 10, "reestructuración de las rutas de transporte público"),
        P("gestion", "Gobierno electrónico municipal que integre los servicios y digitalice la información para el vecino", 10, "Gobierno Electrónico Municipal"),
    ]),
    ("Katherine Angélica de la Rosa Menéndez", "Podemos Perú", "podemos-peru", [
        P("social", "Edificio inteligente multiusos en la actual biblioteca municipal, con espacios de salud, adulto mayor y juventud", 7, "Construir un Edificio Inteligente Multiusos"),
        P("social", "Mejorar la infraestructura y la calidad del servicio del Policlínico Municipal", 7, "sistema de calidad del servicio del Policlínico Municipal"),
        P("seguridad", "Cámaras con reconocimiento facial, drones, alarmas comunitarias con altavoz y botones de pánico", 8, "Cámaras inteligentes con reconocimiento facial"),
        P("seguridad", "Integrar la central de radio y video del serenazgo con la PNP y fortalecer el COE de gestión de riesgos", 8, "Integrar la Central de Radio y Video"),
        P("seguridad", "Repotenciar los Puestos de Auxilio Rápido y patrullajes integrados según el mapa del delito", 8, "Repotenciar los Puestos de Auxilio Rápido"),
        P("economia", "Registro del comercio ambulatorio y mesas de diálogo para ordenarlo y formalizarlo sin represión", 8, "Mesas de diálogo con el comercio informal"),
        P("economia", "Bolsa de empleo municipal y convenio con el Ministerio de Trabajo para capacitar a personas de escasos recursos", 8, "bolsa de empleo municipal"),
        P("ambiente", "Segregación en la fuente, recolección selectiva y ampliación del barrido a todas las calles", 9, "Plan de Ampliación del servicio de barrido"),
        P("transporte", "Plan de Seguridad Vial y empadronamiento de las empresas de transporte menor y sus vehículos", 9, "Empadronamiento general empresas de transporte menor"),
        P("urbano", "Elaborar el Plan Maestro de Infraestructura Urbana del distrito", 9, "Plan Maestro de Infraestructura urbana"),
        P("gestion", "Transformación digital de la gestión y simplificación de los procedimientos administrativos", 9, "Gobernanza y transformación digital"),
    ]),
    ("Víctor Antonio Cruz Huamán", "Progresemos", "progresemos", [
        P("seguridad", "Programas integrales de apoyo a la familia para reducir la violencia urbana y doméstica", 3, "Impulso de programas integrales en apoyo a la familia", "Un comité de vigilancia capacitado y política de prevención aprobada al final de 2029"),
        P("seguridad", "Completar e implementar el sistema de videovigilancia en las zonas priorizadas", 5, "implantación completa y operativa del sistema de videovigilancia", "100 % de equipos y puntos de monitoreo operativos a fines de 2028"),
        P("social", "Salud móvil en zonas desatendidas y construcción de un hospital municipal", 3, "construcción de un hospital municipal", "Atención efectiva al 30 % de los ciudadanos rimenses a fines de 2030"),
        P("urbano", "Obras en asentamientos humanos: lozas deportivas, veredas, escaleras, pistas y muros de contención", 3, "Recuperación de espacios y modernización de las zonas", "Obras en las zonas al término de 2029"),
        P("urbano", "Capacitar a vecinos y juntas vecinales en el parchado de pistas y el resane de veredas", 4, "Capacitar a los vecinos y juntas vecinales en técnicas básicas", "Todo el distrito en 2 años (2029)"),
        P("transporte", "Coordinar con Lima Metropolitana la reestructuración de rutas y restringir vehículos pesados en zonas monumentales", 4, "reestructuración de rutas de transporte público", "Acciones a corto plazo (1 a 2 años), 2029"),
        P("economia", "Promover el turismo, el comercio y los servicios mediante alianzas estratégicas", 3, "Promoción del turismo, comercio y servicios"),
        P("economia", "Asesoramiento municipal para formalizar al comercio ambulatorio y a las mypes, reduciendo tiempo y costo de licencias", 4, "Apoyo a la formalización del comercio ambulatorio"),
        P("ambiente", "Sistema integral de manejo de residuos sólidos con participación de los vecinos", 4, "Implementación de un sistema integral", "Implementación en 1 a 3 años"),
        P("ambiente", "Voluntariado vecinal y contraprestación de servicios para mejorar el ornato del distrito", 5, "Promoción de sistemas de voluntariado vecinal", "20 % más de vecinos activos"),
        P("gestion", "Diseñar una estructura de costos reales de los servicios municipales para fijar tributos justos", 4, "Diseñar una estructura de costos reales"),
    ]),
    ("Isabel del Rocío Ayala Melgarejo", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Patrullaje integrado con la PNP, chalecos antibalas para serenos y convenio con la Policía", 14, "100% de unidades móviles realizando patrullaje integrado", "100 % de unidades móviles en patrullaje integrado"),
        P("seguridad", "Conectar la central de operaciones con la central 105 de la PNP y mantener operativas cámaras y puestos de auxilio", 14, "central 105 de la PNP", "100 % de cámaras de videovigilancia operativas y 100 % de PAR operando"),
        P("agua_riesgos", "Actualizar el mapa de microzonificación sísmica, refugios temporales y capacitación en evacuación y simulacros", 14, "Implementación de 4 zonas de refugio temporal", "4 zonas de refugio temporal"),
        P("agua_riesgos", "Programa «Agua de Emergencia» para dotar de agua a los asentamientos humanos que aún no la tienen", 16, "Programa Agua de Emergencia", "Agua para el 100 % de los AAHH sin acceso"),
        P("social", "Repotenciar el policlínico con tarifas sociales, programa de salud mental y convenios con MINSA y EsSalud", 15, "Implementación del Programa de Salud Mental"),
        P("social", "Cuna Municipal con tarifas accesibles y Academia Municipal de acceso gratuito", 15, "Creación de la Cuna Municipal con tarifas accesibles"),
        P("transporte", "Mejorar ciclovías y señalización vial, y convenio con la ATU para regular el tránsito de vehículos menores y de carga", 18, "Mejorar el 100% de la red de ciclovías", "100 % de la red de ciclovías y de la señalización vial mejoradas"),
        P("economia", "Ruta peatonal del Puente a la Alameda, rutas gastronómicas y ferias en el Centro Histórico", 19, "Realización de 6 Ferias Gastronómicas", "6 ferias gastronómicas en el Centro Histórico"),
        P("economia", "Ventanilla única para licencias de funcionamiento y certificados ITSE, campañas de formalización y ferias comerciales", 19, "Plataforma de Ventanilla Única", "5 ferias comerciales temáticas"),
        P("ambiente", "Mejorar el recojo de residuos, servicio de recolección de desmonte, segregación en la fuente y alertas por WhatsApp", 20, "canal WhatsApp de alerta de residuos", "Ciudad 100 % limpia"),
        P("gestion", "Gestión documental cero papel, pagos en línea y plataforma «Rímac Compra» abierta al público para compras menores", 21, "Implementar la Plataforma Virtual"),
    ]),
]
