"""Santa Anita (150137): propuestas principales de los 13 planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150137"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Flora Maribel Fernández Rengifo", "Acción Popular", "accion-popular", [
        P("seguridad", "Centro de Seguridad Inteligente con videovigilancia, reconocimiento de placas y monitoreo en tiempo real, coordinado con Serenazgo, PNP, Bomberos y SAMU", 24, "reconocimiento de placas, monitoreo en tiempo real", "100 % de cobertura de videovigilancia y 40 % menos tiempo de respuesta al 2030"),
        P("seguridad", "Programa «Serenazgo de Tu Barrio»: patrullaje por sectores, GPS en todas las unidades, base operativa por sector y sereno referente por zona", 23, "GPS en todas las unidades"),
        P("transporte", "Rutas «Urbanitos de Santa Anita» alimentadoras hacia la Línea 2 y hacia centros comerciales y mercados", 46, "rutas alimentadoras hacia la Línea 2"),
        P("social", "Brigadas médicas itinerantes «Salud en tu Barrio» y programa «Niñez Sin Anemia» contra la anemia y la desnutrición infantil", 30, "Brigadas médicas itinerantes", "100 000 atenciones preventivas acumuladas al 2030"),
        P("social", "Complejo Deportivo Metropolitano con piscina semiolímpica, coliseo y gimnasio, y una Villa Deportiva Municipal en el Sector 5", 34, "piscina semiolímpica, coliseo multifuncional"),
        P("social", "Becas Talento Santa Anita para estudiantes destacados, deportistas, artistas y jóvenes de escasos recursos, y academia preuniversitaria municipal", 34, "Becas Talento Santa Anita", "2 000 becas y 10 000 jóvenes capacitados al 2030"),
        P("economia", "Ventanilla Única del Emprendedor para licencias y asesoría, programa de formalización y sello «Negocio Formal Santa Anita»", 36, "Ventanilla Única del Emprendedor", "5 000 negocios formalizados al 2030"),
        P("ambiente", "Programa «Un Vecino, Un Árbol», corredores verdes en avenidas, jardines verticales y riego tecnificado", 40, "Un Vecino, Un Árbol", "20 000 árboles y 30 % más de áreas verdes al 2030"),
        P("urbano", "Plan «Cerros con Futuro» para Lomas de Nocheto, Hijos de Perales, Cristo Rey y otras laderas: escaleras seguras, barandas, iluminación y rutas seguras", 43, "Construcción y rehabilitación de escaleras seguras"),
        P("agua_riesgos", "Gestionar ante el Ministerio de Vivienda y Sedapal proyectos de agua potable y alcantarillado, y apoyar el saneamiento físico legal de predios", 44, "Gestionar ante el Ministerio de Vivienda, Sedapal"),
        P("gestion", "Plataforma «Santa Anita Digital», aplicación «Mi Santa Anita», expediente electrónico y mesa de partes virtual", 43, "Crear la aplicación móvil", "90 % de trámites digitalizados al 2030"),
    ]),
    ("David Elías Alegría Liberato", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Descentralizar el centro de monitoreo en las cinco zonas del distrito, interconectado con Serenazgo y la PNP", 19, "DESCENTRALIZAR EL CENTRO DE MONITOREO DE SEGURIDAD CIUDADANA"),
        P("seguridad", "Cámaras con reconocimiento facial e inteligencia artificial que identifiquen vehículos, personas y comportamientos sospechosos, integradas a alarmas", 20, "cámaras de seguridad con reconocimiento facial"),
        P("seguridad", "Aplicativo «App Seguridad Santa Anita» con botón de pánico y alerta en tiempo real a la unidad de serenazgo más cercana", 21, "APP SEGURIDAD SANTA ANITA", "Respuesta en máximo 5 minutos y 20 000 vecinos registrados el primer año"),
        P("agua_riesgos", "Centro de Comando de Operaciones de Emergencia interconectado con comisarías, bomberos, SAMU, tránsito y defensa civil", 22, "CENTRO DE COMANDO DE OPERACIONES DE EMERGENCIA", "100 % de interconexión el primer año y despacho en menos de 3 minutos"),
        P("social", "Fortalecer la academia preuniversitaria municipal, crear un instituto municipal de formación técnica y un programa municipal de becas", 23, "Creación del INSTITUTO MUNICIPAL"),
        P("social", "Repotenciar la clínica municipal con atención de emergencias 24 horas y crear un centro de salud mental", 24, "REPOTENCIAR LA CLÍNICA MUNICIPAL"),
        P("social", "Mejorar el coliseo deportivo «Parodi», reconstruir la piscina temperada y crear un circuito de ciclovías conectado con Ate y La Molina", 27, "MEJORAMIENTO DEL COLISEO DEPORTIVO"),
        P("economia", "Panadería municipal «Pan y Chamba» con el vaso de leche y comedores populares, y continuidad de los mercados itinerantes", 29, "PANADERÍA MUNICIPAL"),
        P("urbano", "Cambios de zonificación para edificaciones de mayor altura, regularización de construcciones sin licencia y conclusión de habilitaciones urbanas", 33, "CAMBIOS DE ZONIFICACIÓN"),
        P("ambiente", "Planta de reciclaje de gran capacidad para ordenar la limpieza, reducir arbitrios y generar empleo", 34, "LA PLANTA DE RECICLAJE de gran capacidad"),
        P("gestion", "Plataforma de gobierno electrónico y trámites en línea para evitar que los vecinos acudan a los centros de atención", 44, "plataforma de Gobierno Electrónico"),
    ]),
    ("Eduardo Rimachi Martínez", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Centro de Control y Monitoreo Inteligente y aumento de las cámaras de videovigilancia con monitoreo las 24 horas", 32, "más del 200% las cámaras", "Más de 200 % de cámaras; 50 % menos índices delictivos y 60 % menos percepción de inseguridad"),
        P("seguridad", "Drones para vigilancia aérea, renovación de la flota de serenazgo y bases de seguridad por sectores", 33, "Incorporar drones para vigilancia aérea"),
        P("social", "Centros Integrales del Adulto Mayor descentralizados con atención médica, psicológica, recreativa y asesoría legal", 31, "Centros Integrales del Adulto Mayor descentralizados", "Más de 25 000 adultos mayores beneficiados"),
        P("social", "Gran Complejo Cultural y Deportivo y conversión progresiva de las losas deportivas en polideportivos vecinales", 32, "Gran Complejo Cultural y Deportivo", "100 % de espacios deportivos deteriorados recuperados"),
        P("social", "Academia Municipal Preuniversitaria Gratuita, becas de excelencia y centros de reforzamiento escolar", 34, "Academia Municipal Preuniversitaria Gratuita", "Más de 10 000 estudiantes beneficiados"),
        P("social", "Modernizar el Policlínico Municipal, botica municipal con precios sociales y telemedicina para adultos mayores y personas con discapacidad", 35, "Botica Municipal con medicamentos a precios sociales", "Más de 100 000 consultas y 25 % menos anemia infantil"),
        P("economia", "Articular y modernizar los mercados del distrito, como el Mayorista, Productores, Cooperativa Universal y Los Chancas", 36, "articulación y modernización de los principales centros de abastos"),
        P("economia", "Formalizar progresivamente el comercio ambulatorio mediante mercados temporales y espacios regulados", 37, "mercados temporales y espacios regulados", "80 % del comercio informal formalizado"),
        P("urbano", "Recuperar parques y vías, priorizando la Carretera Central y avenidas como Ferrocarril, Los Chancas, La Cultura y Huarochirí", 38, "priorizando intervenciones en la Carretera Central", "100 % de parques, avenidas y calles deterioradas recuperados"),
        P("ambiente", "Sistema de segregación y reciclaje, riego tecnificado de parques y huertos urbanos familiares", 38, "Crear huertos urbanos familiares", "30 % más áreas verdes y 40 % de residuos aprovechables reciclados"),
        P("gestion", "Gobierno Digital Municipal, presupuesto participativo digital y audiencias semestrales de rendición de cuentas", 40, "Presupuesto Participativo Digital", "100 % de trámites principales digitalizados y 50 % menos tiempo de atención"),
    ]),
    ("Judith Soledad Agüero Tinco", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("seguridad", "Instalar 80 cámaras de videovigilancia, ampliar el serenazgo a 24 horas y crear juntas vecinales en las cinco zonas", 9, "Implementar 80 cámaras de videovigilancia", "80 cámaras al 2027 y 30 % menos delitos contra la persona al 2028"),
        P("social", "Rehabilitar 12 instituciones educativas públicas con mobiliario y equipos, y crear 2 cuna-jardines municipales en zonas periféricas", 10, "Rehabilitar 12 instituciones educativas públicas", "12 IIEE rehabilitadas al 2028 y 1 500 niños más en cuna-jardín municipal"),
        P("social", "Brigadas de salud itinerante en 10 zonas, convenio con la DIRIS Lima Este para fortalecer 3 puestos de salud y salud mental comunitaria", 10, "brigadas de salud itinerante en 10 zonas", "15 000 atenciones preventivas anuales"),
        P("social", "Crear 2 Centros Integrales de Atención al Adulto Mayor, fortalecer el CEM e implementar el programa «Familia Fuerte»", 10, "crear 2 Centros Integrales de Atención al Adulto Mayor", "2 CIAM al 2027 y 25 % menos casos de violencia familiar al 2028"),
        P("ambiente", "Programa de arborización urbana, restricción de quemas a cielo abierto y coordinación con el MTC para renovar la flota de transporte público", 11, "Programa de arborización urbana", "5 000 árboles y PM2.5 en 18 μg/m3 al 2030"),
        P("ambiente", "Ampliar la segregación en la fuente a 30 000 viviendas, erradicar 20 puntos críticos y valorizar residuos orgánicos", 11, "segregación en la fuente a 30,000 viviendas", "20 % de residuos valorizados al 2028"),
        P("agua_riesgos", "Mapa de riesgos actualizado, sistema de alerta temprana, brigadas de Defensa Civil en 5 sectores y refuerzo de viviendas en zona de riesgo", 11, "implementar sistema de alerta temprana", "10 brigadas de Defensa Civil activas al 2027"),
        P("economia", "Centro de Emprendimiento y Formalización municipal, convenios con PRODUCE y MTPE, y trámites de licencia simplificados", 12, "Centro de Emprendimiento y Formalización", "500 mypes formalizadas al 2028 y 1 000 trabajadores capacitados al año"),
        P("economia", "Plataforma de precios mayoristas, encadenamiento de comerciantes con el Gran Mercado Mayorista y feria permanente de productores", 12, "plataforma de información de precios mayoristas", "200 comerciantes articulados al GMML al 2028"),
        P("gestion", "Presupuesto participativo digital, portal de transparencia mensual y 5 oficinas zonales de atención al ciudadano", 13, "instalar 5 oficinas zonales de atención", "5 oficinas zonales al 2027"),
        P("urbano", "Repavimentar 15 km de vías, renovar 1 000 puntos de alumbrado LED y rehabilitar veredas de alta circulación", 13, "Repavimentar 15 km de vías deterioradas", "15 km repavimentados al 2029 y 100 % de alumbrado LED al 2030"),
    ]),
    ("Ingrid Alcarraz Guía", "Juntos por el Perú", "juntos-por-el-peru", [
        P("social", "Convenio para traslado de pacientes con instituciones de salud y bomberos, compra de ambulancias y equipamiento del Policlínico Municipal", 12, "adquisición de ambulancias", "2 ambulancias"),
        P("social", "Patronato de becas para jóvenes destacados y convenios con instituciones educativas superiores para capacitación técnica", 12, "Conformar un Patronato de Becas", "30 % más jóvenes con capacitación técnica"),
        P("social", "Centro Municipal de Bienestar y Salud Animal con emergencias veterinarias, registro de mascotas y campañas de vacunación y esterilización", 12, "Crear el Centro Municipal de Bienestar y Salud"),
        P("seguridad", "Programa «Santa Anita Smart»: cámaras inteligentes interconectadas con serenazgo y comisarías, central de monitoreo y vigilancia con drones", 13, "Implementar la vigilancia aérea mediante drones"),
        P("seguridad", "Programa «Santa Anita segura 24/7»: más serenos, capacitación y un esquema de compensación para atraer personal", 14, "Santa Anita segura 24/7", "9 sobre 10 de satisfacción para el 2030"),
        P("economia", "Circuitos turísticos con el Ministerio de Cultura para recuperar las huacas Perales y Bellavista, y habilitar el Mirador de Santa Anita", 13, "Habilitar el Circuito Turístico Mirador de Santa Anita"),
        P("transporte", "Convenios con Lima Metropolitana y el MTC para ampliar la Av. César Vallejo, rehabilitar la Carretera Central y desviar vehículos pesados", 15, "rehabilitación de la Carretera Central"),
        P("urbano", "Programa «Bache Cero» de parchado rápido de pistas y veredas en mal estado", 15, "Programa “Bache Cero”", "80 % de pistas y veredas en buen estado"),
        P("agua_riesgos", "Planta de tratamiento de aguas del río Surco para regadío y riego tecnificado de áreas verdes", 17, "planta de tratamiento de aguas para regadío", "1 PTAR municipal para regadío"),
        P("ambiente", "Programa de segregación en la fuente y recolección selectiva de residuos, y contenedores para basura y heces de mascotas en parques", 17, "recolección selectiva de residuos sólidos", "100 % de parques con contenedores al 2030"),
        P("gestion", "Oficinas descentralizadas de proyectos, ejecución del presupuesto participativo y fortalecimiento de la unidad anticorrupción", 18, "unidad de integridad institucional anticorrupción"),
    ]),
    ("Maribel Albornoz Rosas", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Fortalecer la seguridad ciudadana y la convivencia vecinal", 8, "Fortalecer la seguridad ciudadana y la convivencia vecinal", "Reducir 30 % la percepción de inseguridad"),
        P("social", "Ampliar la cobertura de los servicios sociales municipales para la población vulnerable", 8, "Ampliar la cobertura de servicios sociales municipales", "50 % más beneficiarios atendidos"),
        P("urbano", "Recuperar y mejorar espacios públicos y recreativos", 8, "Recuperar y mejorar espacios públicos", "150 000 m² recuperados"),
        P("economia", "Promover la formalización empresarial de los emprendimientos", 8, "Promover la formalización", "10 000 emprendimientos formalizados"),
        P("economia", "Fortalecer la empleabilidad local con programas laborales", 8, "Fortalecer la empleabilidad local", "15 000 beneficiarios de programas laborales"),
        P("economia", "Modernizar mercados y espacios económicos del distrito", 8, "Mercados 15 modernizados", "15 mercados modernizados"),
        P("ambiente", "Incrementar la infraestructura verde para reducir el déficit de áreas verdes", 9, "Incrementar infraestructura verde", "150 000 m²"),
        P("ambiente", "Fortalecer el reciclaje y la valorización de residuos sólidos", 9, "Fortalecer reciclaje y valorización", "40 % de residuos valorizados"),
        P("ambiente", "Recuperar los espacios degradados críticos del distrito", 9, "Recuperar espacios críticos", "100 % de espacios recuperados"),
        P("gestion", "Digitalizar procedimientos municipales y cumplir la transparencia activa", 9, "% procedimientos digitalizados", "80 % de procedimientos digitalizados y 100 % de transparencia activa"),
        P("gestion", "Plataforma Digital Única de Obras Públicas de acceso público para reportar incidencias, con rendición de cuentas trimestral", 10, "Plataforma Digital Única de Obras Públicas"),
    ]),
    ("José Luis Nole Palomino", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "200 cámaras adicionales con IA y reconocimiento facial y de placas, y centrales de monitoreo en el Sector 5 (Nocheto) y la Urb. Miguel Grau", 15, "Doscientas (200) Cámaras adicionales", "200 cámaras adicionales y 360 cámaras con fibra óptica"),
        P("seguridad", "Aumentar el serenazgo con logística de seguridad, crear un Grupo de Operaciones Especiales y lanzar la app «Santa Anita Segura» con botón de pánico", 15, "Serenazgo a Doscientos (250) Serenos", "Serenazgo a «Doscientos (250)» serenos (así en el plan)"),
        P("transporte", "Actualizar el plan regulador de mototaxis, ordenar paraderos y coordinar con la ATU la erradicación de paraderos informales", 17, "Plan Regulador para el Transporte en Vehículos Menores"),
        P("transporte", "Gestionar un paso a desnivel sobre la Vía de Evitamiento que una Santa Rosa, Manuel Correa, Virgen de las Nieves, Perales y Nocheto con el distrito", 19, "cruce a desnivel de la autopista Vía de Evitamiento"),
        P("urbano", "Comprar un pool de maquinarias para mantener pistas y veredas por administración directa, con un equipo técnico de bacheo constante", 19, "Adquisición de un Pool de Maquinarias"),
        P("urbano", "Nuevo cambio de zonificación, habilitación urbana de oficio y saneamiento de predios mediante convenios con COFOPRI", 12, "Habilitación Urbana de Oficio"),
        P("agua_riesgos", "Tratar las aguas del río Surco para riego tecnificado de parques, y limpiar y canalizar su cauce", 13, "Tratamiento de las aguas del Río Surco"),
        P("ambiente", "Formalizar y capacitar a recicladores y centros de acopio para integrarlos al manejo de residuos sólidos", 13, "formalización y capacitación de los recicladores"),
        P("economia", "Organizar, capacitar y formalizar a comerciantes informales como mypes, con incentivos a la inversión comercial e industrial", 18, "formalización a los comerciantes informales"),
        P("social", "Construir el velatorio municipal, la casa del adulto mayor, una guardería, la casa de la OMAPED y una clínica veterinaria municipal", 19, "Construcción del Velatorio Municipal"),
        P("social", "Coliseo cerrado de uso múltiple, piscinas temperadas e instituto de educación técnica superior municipal", 20, "Coliseo Cerrado de uso múltiple"),
    ]),
    ("José Eleuterio Horna Saavedra", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Videovigilancia con reconocimiento de placas y rostro integrada al centro de monitoreo, más serenazgo motorizado y patrullaje integrado con la PNP", 2, "cámaras con reconocimiento de placas y rostro", "200 cámaras adicionales y 20 % menos denuncias"),
        P("social", "Programa «Santa Anita Recrea»: recuperar parques y losas deportivas, habilitar un centro cultural y polideportivo y escuelas deportivas", 3, "Habilitación del centro cultural y polideportivo", "30 parques y losas recuperados y 15 000 beneficiarios anuales"),
        P("social", "Centro de Emergencia Mujer municipal y ampliación de la cobertura del CIAM, la OMAPED y la DEMUNA", 3, "Centro de Emergencia Mujer municipal", "40 % más personas atendidas respecto a 2026"),
        P("economia", "Programa «Santa Anita Formal»: censo de comerciantes informales en el entorno del Mercado Mayorista y módulos de comercio formal en zonas autorizadas", 4, "Censo y registro actualizado de comerciantes informales", "2 000 comerciantes formalizados"),
        P("economia", "Programa «Santa Anita Emprende»: asistencia técnica a mypes, ferias y ruedas de negocios, y bolsa de trabajo municipal", 4, "ruedas de negocios distritales", "1 500 mypes capacitadas y 1 000 puestos de trabajo facilitados"),
        P("transporte", "Accesos peatonales, semaforización inteligente y ciclovías en torno a las cinco estaciones de la Línea 2 del Metro en el distrito", 4, "cinco estaciones de la Línea 2 presentes en el distrito", "10 km de ciclovías y mejora de accesos en las 5 estaciones"),
        P("transporte", "Reordenar con la ATU el tránsito de carga pesada hacia el Mercado Mayorista", 5, "Reordenamiento del tránsito de vehículos de carga pesada"),
        P("ambiente", "Erradicar puntos críticos de basura, ampliar la segregación en la fuente, fortalecer la planta de compostaje y formalizar recicladores", 5, "planta de valorización de residuos orgánicos", "100 % de puntos críticos erradicados y 50 % de viviendas con segregación"),
        P("ambiente", "Programa «Santa Anita Más Verde»: arborizar bermas y óvalos, y riego tecnificado evaluando el uso de aguas residuales tratadas", 5, "Recuperación y arborización de bermas centrales", "25 % más área verde por habitante y 5 000 árboles"),
        P("ambiente", "Estaciones de monitoreo de aire y ruido, y transición de la flota municipal a gas natural o vehículos eléctricos", 6, "estaciones de monitoreo de calidad del aire", "5 estaciones y 40 % de la flota municipal con tecnología limpia"),
        P("gestion", "Programa «Santa Anita Transparente»: portal con información presupuestal en tiempo real y audiencias trimestrales de rendición de cuentas por zonas", 6, "audiencias públicas trimestrales de rendición de cuentas", "4 audiencias públicas al año"),
    ]),
    ("Celia Laura Jorge", "Partido País para Todos", "partido-pais-para-todos", [
        P("social", "Dos centros de salud nivel I-4 en Los Jardines y Nocheto, y tres CIAM en Praderas, Viña San Francisco y Portada de Ceres", 28, "2 centros de salud nivel I-4", "2 centros de salud I-4 y 3 CIAM"),
        P("social", "Cuatro complejos deportivos y 12 losas multiusos en los AA. HH. 29 de Enero Nocheto, Huancayo y Santa Anita II", 28, "4 complejos deportivos y 12 losas multiusos", "4 complejos deportivos y 12 losas multiusos"),
        P("social", "Tres PRONOEI en Los Jardines, Nocheto y Virgen de las Nieves, y mejora de 15 colegios públicos con aulas, laboratorios e internet", 29, "Mejoramiento de 15 colegios públicos", "3 PRONOEI y 15 colegios mejorados"),
        P("economia", "Modernizar mercados de abastos como Las Praderas, Virgen de las Nieves y Huancayo", 28, "Modernización de 6 mercados de abastos", "6 mercados modernizados"),
        P("economia", "Dos Centros de Desarrollo Empresarial para capacitar y formalizar mypes, y un parque industrial tecnológico para mypes metalmecánicas", 28, "2 Centros de Desarrollo Empresarial", "12 000 mypes capacitadas y formalizadas"),
        P("ambiente", "Planta municipal de compostaje para residuos orgánicos de mercados y podas, y eco-aulas itinerantes en colegios", 28, "Planta de compostaje Municipal", "30 toneladas al día y 40 % menos basura al relleno"),
        P("ambiente", "Luminarias LED en vías principales y locales municipales con paneles solares", 28, "5,000 luminarias LED en vías principales", "5 000 luminarias LED y 10 locales municipales 100 % solares"),
        P("seguridad", "Construir dos centros de videovigilancia con cámaras en los 16 sectores", 29, "2 centros de videovigilancia con 300 cámaras", "2 centros y 300 cámaras en 16 sectores"),
        P("gestion", "Gobierno digital con atención virtual y trámites en línea, y 16 locales para juntas vecinales con presupuesto participativo", 29, "Plataformas de atención virtual", "100 % de trámites en línea y 16 locales vecinales"),
        P("urbano", "Pavimentar vías vecinales en trochas de la Cooperativa Andahuaylas, Praderas, 29 de Enero y Sol de Santa Anita", 29, "Pavimentación de 80 km de vías vecinales", "80 km de vías pavimentadas"),
        P("transporte", "Ciclovías interconectadas con bici parqueaderos en el Mercado Mayorista y semaforización inteligente en intersecciones", 29, "100 km de ciclovías interconectadas", "100 km de ciclovías, 5 bici parqueaderos y 60 intersecciones modernizadas"),
    ]),
    ("Marissa Melo Llaullipoma", "Perú Libre", "partido-politico-nacional-peru-libre", [
        P("seguridad", "Cámaras de alta definición con reconocimiento facial interconectadas con la división de requisitorias de la PNP, y drones con un helipuerto por cuadrante", 3, "interconectadas con la División de requisitoria", "80 % más cámaras y 50 % menos víctimas"),
        P("seguridad", "Aplicativo «botón de pánico» conectado con Serenazgo, Bomberos y Policía, y renovación de unidades y personal de serenazgo", 3, "interconectado con el Serenazgo Bomberos y la Policía"),
        P("social", "Construir 4 academias municipales y convenios con universidades y CETPRO para la formación técnica y el empleo juvenil", 4, "construcción de 04 Academias Municipales"),
        P("social", "Centro de Salud nivel I-3 en Santa Rosa de Quives (Zona 1), ambulancia municipal tipo II y triaje virtual hacia el Policlínico Municipal", 5, "Centro de Salud nivel I3 en la Zona I"),
        P("economia", "Caja municipal de crédito para mypes, programa PROCOMPITE Santa Anita y mercados itinerantes de la agricultura familiar", 7, "Caja municipal de Santa Anita para apoyar"),
        P("economia", "Boulevard comercial en el Óvalo Santa Anita, peatonalización de la calle Los Flamencos y red turística con las huacas Perales y Los Virreyes", 8, "peatonalización de la calle Los Flamencos"),
        P("transporte", "Capacitar a mototaxistas en seguridad vial, formalizar sus redes y rutas, y préstamos para renovar vehículos menores", 9, "Formalización de las redes de moto taxis", "90 % de conductores capacitados y 90 % de redes formalizadas"),
        P("transporte", "Gestionar un bypass subterráneo en la prolongación de la Av. Eucaliptos con la Av. 1° de Mayo y la conexión de la Av. Huarochirí con la Av. Prialé", 10, "Bypass subterráneo prolongación de la Av. Eucaliptos"),
        P("ambiente", "Parque ecológico «Cerros Verdes» en los cerros de la Zona 1, con geomallas, riego por goteo con atrapanieblas y miradores", 12, "Parque Ecológico en los cerros de Santa Anita", "350 000 m² de área verde"),
        P("agua_riesgos", "Crear una planta de tratamiento del río Surco para regar los parques con agua no contaminada", 15, "Crear una Planta de Tratamiento del río Surco"),
        P("gestion", "Mejorar la plataforma digital municipal, digitalizar arbitrios, sincerar su costo y promover obras por impuestos y asociaciones público-privadas", 16, "Digitalización de Arbitrios Municipales"),
    ]),
    ("Manuel Edgardo Mamani Rodríguez", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Más de 300 cámaras con analítica de video y pórticos con lectura automática de placas en los 6 accesos principales del distrito", 17, "pórticos inteligentes con lectura automática de placas", "Más de 300 cámaras y pórticos en el 100 % de los accesos principales"),
        P("seguridad", "Duplicar la flota del serenazgo, con cámaras corporales, GPS y patrullaje integrado con la PNP y juntas vecinales", 17, "Reducción del tiempo promedio de respuesta del Serenazgo", "Más del 100 % de flota y respuesta en menos de 4 minutos"),
        P("seguridad", "Cinco Puestos de Auxilio Rápido, uno por sector, operativos las 24 horas y conectados a la central de monitoreo", 17, "5 Puestos de Auxilio Rápido", "5 Puestos de Auxilio Rápido"),
        P("urbano", "Sustituir el alumbrado público por tecnología LED e instalar postes inteligentes con cámaras y botones de pánico", 18, "postes inteligentes con cámaras integradas", "100 % del alumbrado público con LED"),
        P("social", "Dos centros municipales especializados en trastorno del espectro autista y un centro integral de terapias para personas con habilidades especiales", 18, "2 Centros Municipales Especializados en Trastorno", "2 centros TEA y 1 centro integral de terapias"),
        P("social", "Dos piscinas municipales temperadas con natación gratuita para escolares y terapias acuáticas para personas con discapacidad", 19, "2 piscinas municipales temperadas", "2 piscinas y más de 5 000 escolares beneficiados"),
        P("social", "Becas integrales y parciales para estudios universitarios, técnicos y preuniversitarios mediante convenios, y preparación preuniversitaria gratuita", 20, "Otorgamiento de 2,000 becas integrales", "2 000 becas"),
        P("ambiente", "Plan Verde: arborización en avenidas y parques, programa «Parques Floridos» y riego tecnificado en parques", 21, "Arborización con más de 20,000 árboles", "Más de 20 000 árboles y 30 % más áreas verdes por habitante"),
        P("ambiente", "Renovar la flota de limpieza con compactadoras, contenedores soterrados y programa «Santa Anita Limpia 24/7» con monitoreo de rutas", 21, "Modernización del 100% de la flota de limpieza", "100 % de puntos críticos eliminados y más de 500 toneladas anuales recicladas"),
        P("economia", "Formalizar pequeños negocios y mypes y simplificar la tramitación de licencias comerciales", 37, "Formalizar de manera integral a 3,000 pequeños negocios", "3 000 negocios formalizados y 80 % menos tiempo de licencias"),
        P("gestion", "Aplicativo «Santa Anita Digital», trámites digitales, pagos en línea y centros de atención descentralizados en los cinco sectores", 23, "Centros de Atención Municipal Descentralizados", "100 % de trámites digitales y app con más de 50 000 usuarios"),
    ]),
    ("Leonor Chumbimune Cajahuaringa", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Cámaras con reconocimiento facial y de placas conectadas a una central de monitoreo con fibra óptica, y patrullaje con drones", 6, "reconocimiento facial y plaqueo vehicular", "1 000 cámaras y percepción de inseguridad menor al 65 %"),
        P("social", "Reactivar la Casa de la Juventud y el Instituto Técnico Municipal, con bolsa de trabajo, orientación vocacional y becas", 7, "Reactivar la Casa de la Juventud", "15 % más empleo juvenil"),
        P("social", "Ambulancia y área de hospitalización para la Clínica Municipal, y gestionar con el MINSA un hospital para Santa Anita", 7, "gestionar la construcción de un hospital para Santa Anita", "Hospital categoría II-1 y 80 % de familias con acceso a salud de calidad"),
        P("social", "Veterinaria municipal con albergue para animales abandonados, esterilización, vacunación y hospedaje temporal para mascotas", 7, "Implementar la Veterinaria Municipal con albergue", "Mínimo 1 000 atenciones anuales a animales"),
        P("social", "Reactivar la piscina municipal y la piscina temperada de la Urb. Universal, recuperar polideportivos y crear mini gimnasios en parques", 9, "piscina temperada de la Urb. Universal"),
        P("social", "Reactivar la Casa del Adulto Mayor y la Casa de la Mujer, ampliar guarderías municipales y crear la Casa de la Persona con Discapacidad", 9, "Reactivar e incrementar las guarderías municipales", "80 % menos casos de violencia"),
        P("economia", "Boulevard y mirador en Cristo Rey integrados a un circuito turístico con las huacas Bellavista y Perales", 10, "boulevard y un mirador en Cristo Rey", "50 % más inversión privada"),
        P("urbano", "Recuperar las avenidas Cascanueces y La Cultura, renovar el asfalto del distrito y construir alamedas en las avenidas Huarochirí y Manuel C. de la Torre", 10, "Recuperar la Av. Cascanueces y la Av. La Cultura", "100 % de Av. La Cultura y Cascanueces; 90 % de vías con asfalto en buen estado"),
        P("transporte", "Red de ciclovías, oficina de defensa del ciclista y semáforos inteligentes sonoros con rampas e indicaciones en braille", 11, "oficina de defensa del ciclista"),
        P("ambiente", "Estaciones de reciclaje para residuos especiales, recolección de orgánicos para fertilizantes y reutilización de las aguas del río Surco", 11, "estaciones de reciclaje para residuos especiales", "100 % de cumplimiento en la recolección de residuos"),
        P("gestion", "Retomar el modelo de municipio Smart City con trámites simples, rápidos y sin costos adicionales", 12, "Retomar el modelo de Municipio Smart City", "80 % de satisfacción ciudadana"),
    ]),
    ("Antero Maurine Pickmans Arenaza", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Más cámaras con inteligencia artificial y comunicación bidireccional que identifiquen placas, rostros y comportamientos inusuales", 20, "cámaras de videovigilancia con IA y comunicación bidireccional"),
        P("seguridad", "Puestos de vigilancia en las cinco zonas, modernización de casetas de serenazgo y puestos de comando móvil", 23, "Puestos de vigilancia en las cinco zonas de Santa Anita"),
        P("seguridad", "Botones de alerta vecinal en zonas de mayor incidencia y canal de WhatsApp «Alerta Santa Anita 24/7» con respuesta del serenazgo", 25, "Instalación de botones de alerta vecinal"),
        P("social", "Reestructurar la Clínica Municipal con precios sociales, más especialidades y horarios, e implementar una farmacia municipal", 31, "Se implementará una Farmacia Municipal"),
        P("social", "Centro Pre-Universitario Municipal (CEPREMUNI), refuerzo escolar y fondo educativo para estudiantes destacados", 34, "Centro Pre-Universitario Municipal (CEPREMUNI)"),
        P("agua_riesgos", "Construir y mantener muros de contención en puntos críticos de los sectores vulnerables", 37, "construcción y mantenimiento de muros de contención"),
        P("urbano", "Programa «Santa Anita sin Baches» con un grupo propio de bacheo asfáltico equipado", 38, "Crearemos un grupo de bacheo asfáltico"),
        P("urbano", "Habilitación urbana de oficio para zonas sin habilitación, como la Cooperativa Santa Rosa de Quives, para facilitar el acceso a servicios básicos", 39, "regularizar asentamientos humanos y asociaciones vecinales"),
        P("transporte", "Servicio Municipal de Auxilio Vehicular 24/7 para atender vehículos averiados en las vías y reducir la congestión", 39, "Servicio Municipal de Auxilio Vehicular 24/7"),
        P("economia", "Escuela Municipal de Emprendimiento y programa «Procompite Santa Anita» para cofinanciar planes de negocio por concurso", 52, "cofinanciar planes de negocio mediante concursos públicos"),
        P("ambiente", "Grupo de Acción Rápida de limpieza con volquetes y minicargadores para puntos críticos, y recuperación de botaderos como espacios públicos", 57, "Grupo de Acción Rápida para limpieza pública"),
    ]),
]
