"""Lurín (150119): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150119"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    (None, "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("social", "Gestionar la construcción del Hospital Municipal de Lurín y un Policlínico Municipal con emergencia las 24 horas", 7, "Hospital Municipal de Lurín y el Policlínico Municipal"),
        P("social", "Farmacias Municipales Solidarias en las cinco zonas del distrito, con medicamentos esenciales a costo social", 8, "Farmacias Municipales Solidarias en las 5 zonas"),
        P("seguridad", "Central Integrada de Videovigilancia y Monitoreo Inteligente conectada con la Policía Nacional y los servicios de emergencia", 9, "Central Integrada de Videovigilancia y Monitoreo Inteligente"),
        P("seguridad", "Modernizar el serenazgo con vehículos, motos, cuatrimotos y drones, y crear el aplicativo «Alerta Lurín» para avisos en tiempo real", 9, "Alerta Lurín"),
        P("agua_riesgos", "Supervisar la ejecución del proyecto de agua y alcantarillado «Esquema Lurín» y gestionar la ampliación de servicios básicos", 11, "Esquema Lurín"),
        P("agua_riesgos", "Plan de reducción de riesgo de desastres «Lurín Listo», con simulacros de sismo y señalización de zonas seguras", 30, "simulacros de sismo 6 veces al año", "Simulacros de sismo 6 veces al año"),
        P("transporte", "Estudio de factibilidad de 4 ejes viales, puentes peatonales en la Antigua Panamericana Sur y paraderos de transporte público", 14, "ejecución de 4 ejes viales"),
        P("economia", "Programa «Cómprale a Lurín» con ferias productivas, gastronómicas, artesanales y turísticas en las cinco zonas", 21, "Cómprale a Lurín"),
        P("economia", "Gestionar un muelle pesquero artesanal en la Playa San Pedro para los pescadores del distrito", 27, "infraestructura pesquera artesanal en Playa San Pedro"),
        P("ambiente", "Albergue Municipal de mascotas con el programa «Tenencia Responsable» y adopción de animales rescatados", 32, "Albergue Municipal de mascotas"),
        P("gestion", "Simplificar trámites con seguimiento de expedientes en tiempo real vía web y abrir oficinas de atención descentralizadas", 39, "seguimiento de expedientes en tiempo real vía web"),
    ]),
    ("Esther del Rosario Meza Atuncar", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Programa «Lurín Seguro 24/7»: Centro Integrado de Monitoreo con inteligencia artificial y lectura automática de placas", 8, "Centro Integrado de Monitoreo Distrital", "500 cámaras operativas al 2030"),
        P("seguridad", "Serenazgo de alta capacidad con camionetas, motocicletas, serenos capacitados y sistema GPS", 9, "200 serenos capacitados", "50 camionetas, 80 motocicletas y 200 serenos capacitados"),
        P("social", "Hospital Municipal de Lurín con emergencia 24 horas, pediatría, ginecología, laboratorio e imágenes", 10, "150,000 atenciones anuales", "150 000 atenciones anuales"),
        P("transporte", "Mejorar pistas del distrito y automatizar intersecciones con semáforos inteligentes", 10, "30 intersecciones automatizadas", "50 km de pistas mejoradas y 30 intersecciones automatizadas"),
        P("urbano", "Gran Parque Metropolitano del Valle de Lurín (20 a 30 ha) y programa de renovación de parques", 11, "100 PARQUES RENOVADOS", "100 parques renovados"),
        P("economia", "Centro de Formación Técnica e Industrial con soldadura, mecánica, automatización, logística y maquinaria pesada", 13, "3,000 estudiantes por año", "3 000 estudiantes por año"),
        P("economia", "Bolsa de Empleo Municipal para vecinos y ventanilla única empresarial para licencias", 13, "10,000 empleos formales", "10 000 empleos formales"),
        P("ambiente", "Programa «Lurín Verde» de recuperación de áreas verdes y «Lurín Limpio» con compactadoras y camiones nuevos", 14, "Programa Lurín Verde", "200 000 m² de áreas verdes recuperados"),
        P("agua_riesgos", "Programa «Lurín Agua para Todos» con convenio con Sedapal, reservorios y ampliación de redes de agua y alcantarillado", 16, "Reducir en al menos 80% las brechas", "Reducir en al menos 80 % las brechas de agua y saneamiento"),
        P("agua_riesgos", "Programa «Lurín Sin Aniegos» con colectores pluviales, canales de evacuación y pozos de infiltración", 17, "Reducir en 90% los puntos críticos de aniego", "Reducir en 90 % los puntos críticos de aniego"),
        P("gestion", "Gobierno digital con expediente electrónico y programa «Transparencia Total» con datos abiertos, tablero de obras y audiencias", 15, "Programa Transparencia Total"),
    ]),
    ("Diana Vanessa Herrera Zavala", "Fe en el Perú", "fe-en-el-peru", [
        P("seguridad", "Central única de cámaras con reconocimiento facial y de placas, conectada con la PNP, financiada por obras por impuestos", 17, "primera central única de cámaras"),
        P("seguridad", "Convenio con el Ministerio del Interior para que una unidad del grupo Terna opere de forma permanente en el distrito", 17, "unidad del grupo terna"),
        P("seguridad", "Iluminación con energía solar en las zonas críticas con altos índices de delincuencia", 17, "iluminación con sistema solar"),
        P("social", "Gestionar la construcción de un hospital de primer nivel en un terreno saneado del distrito", 13, "construcción de un Hospital de primer nivel"),
        P("social", "Policlínicos municipales en convenio con entidades privadas de salud mediante obras por impuestos", 13, "policlínicos de salud municipales"),
        P("social", "Centros de preparación preuniversitaria municipales en forma descentralizada", 13, "centros de preparación pre universitaria"),
        P("urbano", "Plan de Acondicionamiento y Ordenamiento Territorial y comisión técnica para definir los límites con Pachacámac y Villa El Salvador", 12, "Plan de Acondicionamiento y Ordenamiento Territorial"),
        P("economia", "Centro de atención a empresarios locales para reducir los tiempos de licencias de funcionamiento y pago de impuestos", 14, "centro de atención a los empresarios locales"),
        P("ambiente", "Proteger y conservar las zonas agrícolas del valle y apoyar a pequeños y medianos productores con convenios de venta", 9, "conservación y revaloración de nuestras zonas agrícolas"),
        P("gestion", "Módulos permanentes de asesoría y acompañamiento al vecino durante sus trámites municipales", 11, "MODULOS PERMANENTES DE ASESORIA"),
        P("gestion", "Actualizar y modernizar el catastro urbano y rural municipal", 16, "Actualizar y modernizar el sistema catastral"),
    ]),
    (None, "Fuerza Popular", "fuerza-popular", [
        P("seguridad", "Adquirir nuevos equipos de videovigilancia para el sistema de seguridad ciudadana", 5, "100 cámaras de video", "100 cámaras de videovigilancia"),
        P("seguridad", "Reunión mensual de coordinación con autoridades y vecinos sobre seguridad ciudadana", 6, "1 reunión mensual. coordinación", "1 reunión mensual"),
        P("social", "Crear un velatorio municipal con el equipamiento necesario", 5, "Crear un velatorio municipal"),
        P("urbano", "Rediseñar veredas, paraderos, avenidas y parques para el desplazamiento y la recreación de personas con discapacidad", 5, "Rediseñar espacios | Modificar la", "Mejorar los espacios de accesibilidad al 50 %"),
        P("urbano", "Plan de desarrollo urbano con catastro distrital y regularización de parámetros urbanos", 6, "Plano de catastro", "Regularizar parámetros urbanos del 80 % de instituciones públicas y 40 % de privadas"),
        P("economia", "Talleres y ferias para emprendedores, con una base de datos de emprendedores del distrito", 5, "01 feria / talleres", "Incrementar a un 60 % las ferias de emprendedores"),
        P("economia", "Brigadas escolares de emprendedores en las instituciones educativas del distrito", 6, "Una brigada escolar en", "80 % de formación de brigadas escolares en 10 instituciones educativas"),
        P("ambiente", "Charlas informativas sobre el cuidado del medio ambiente", 6, "ambiente con charlas", "1 charla al mes"),
        P("ambiente", "Mejorar la conservación y el mantenimiento de las áreas verdes del distrito", 6, "Mejorar el estado de", "Renovación de áreas verdes 1 vez a la semana"),
        P("gestion", "Publicar diariamente los ingresos y egresos municipales, con auditoría interna permanente y auditoría externa anual", 5, "permanente y auditoria externa"),
        P("gestion", "Sesiones de concejo municipal descentralizadas en los distintos cuadrantes del distrito", 6, "sesiones de consejo municipal de manera descentralizada", "Al menos cada cuatro meses"),
    ]),
    ("Antonio Caycho Cervantes", "Libertad Popular", "libertad-popular", [
        P("seguridad", "Programa «Lurín es Seguridad»: patrullaje integrado de PNP, serenazgo, fiscalización, defensa civil y personal de salud", 9, "Programa Lurín es Seguridad", "Patrullaje integrado operativo en las cinco zonas al 2030"),
        P("seguridad", "Descentralizar la seguridad con sedes o bases de serenazgo en cada zona del distrito", 10, "Implementar sedes y/o bases conexas", "Sedes o bases en las zonas A, B, C, D y E"),
        P("seguridad", "Software que interconecte cámaras de reconocimiento facial, cámaras testigo y botones de pánico, con uso de drones", 10, "Sistema integrado e interconectado con todas las cámaras"),
        P("seguridad", "Crear la Fuerza de Operaciones Municipales (FOM) y el Grupo Especial Municipal (GEM), con capacitación del serenazgo", 6, "Fuerza de Operaciones Municipales"),
        P("agua_riesgos", "Gestionar con empresas privadas pozos con ozonificación y purificadores para tener agua potable, y proyectos de agua por sector", 6, "posos ozonificados con purificadores"),
        P("transporte", "Adquirir puentes Bailey y crear zonas de embarque y desembarque para taxis y vehículos menores en puntos de congestión", 8, "adquisición de puentes baileys"),
        P("urbano", "Programa catastral y de saneamiento territorial, con apoyo al saneamiento físico-legal y control del tráfico de terrenos", 11, "Catastral y Saneamiento Territorial", "Catastro distrital actualizado al 2030"),
        P("economia", "Programa «Emprende con tu municipio» con asistencia técnica y formalización de MYPE, y bolsa de trabajo con empresas locales", 12, "emprende con tu municipio"),
        P("social", "Gestionar un centro de salud tipo 4 y ampliar la atención de los establecimientos a 24 horas", 8, "centro de salud tipo 4"),
        P("ambiente", "Programas «Basura Cero y Reciclaje Vecinal» y «Lurín Distrito Verde» de arborización y defensa de la ribera del río", 11, "Basura Cero y Reciclaje Vecinal"),
        P("gestion", "Programa cero papel con software integrado, audiencias públicas y cabildos abiertos", 14, "Cabildos abiertos mensuales y semestrales", "Cabildos abiertos mensuales y semestrales"),
    ]),
    ("Honorio César Paredes Gálvez", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("seguridad", "Sistema de vigilancia inteligente «Ojos de Lurín» y serenazgo con modelo preventivo-comunitario", 7, "Ojos de Lurín"),
        P("social", "Programa «Lurín Joven: Futuro Sin Adicciones» con centros de orientación en cada zona y recuperación de espacios públicos", 9, "Lurín Joven: Futuro Sin Adicciones"),
        P("urbano", "Red de «parques de sombra» inclusivos con arborización y mobiliario accesible en zonas densamente pobladas", 16, "Creación de 5 parques con arborización", "5 nuevos parques inclusivos"),
        P("urbano", "Renovar el alumbrado público con tecnología LED de alta eficiencia", 11, "Renovar el 60% de la red con tecnología LED", "60 % de la red con LED y 95 % de operatividad del alumbrado"),
        P("transporte", "Cruces peatonales elevados y reductores de velocidad cerca de colegios, y red de ciclovías con aceras rehabilitadas", 16, "Construcción de 12 km de ciclovías", "12 km de ciclovías y 8 km de aceras rehabilitadas"),
        P("economia", "Programa «Lurín Emprende» de formalización y capacitación de micro y pequeñas empresas", 16, "Formalización y capacitación de 300 MYPEs", "300 MYPE formalizadas y capacitadas"),
        P("economia", "Bolsa de Trabajo Municipal con capacitación técnica y vínculo con empresas locales", 16, "Inserción laboral de 200 jóvenes por año", "200 jóvenes insertados laboralmente por año"),
        P("agua_riesgos", "Recuperar la ribera y la faja marginal del río Lurín para prevenir inundaciones", 16, "Intervención en 3 km lineales del río Lurín", "3 km lineales de ribera recuperados"),
        P("ambiente", "Crear Áreas de Conservación Local para proteger ecosistemas nativos del valle", 16, "Protección de 2 áreas que resguarden", "2 áreas de conservación con al menos 100 hectáreas"),
        P("gestion", "Ventanilla única virtual, sistema ERP municipal y tablero de control de indicadores", 13, "Renovar la infraestructura tecnológica e implementar un sistema ERP"),
        P("gestion", "Comités de Vigilancia Ciudadana de Obras y aplicativo «Vecino Fiscalizador» para reportar avances y deficiencias", 8, "Vecino Fiscalizador"),
    ]),
    ("Bernardo Silva Beck", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Puestos de Auxilio Rápido con personal municipal y policial, las 24 horas, en las zonas del distrito", 29, "Nº PAR operativos Implementar 3 nuevos PAR", "3 nuevos Puestos de Auxilio Rápido"),
        P("seguridad", "Central de Monitoreo Municipal con cámaras en fibra óptica y policías y fiscales permanentes en las casetas", 21, "Central de Monitoreo Municipal"),
        P("economia", "Ordenanza «50 % Lurinense» con incentivos tributarios a empresas que contraten como mínimo la mitad de su personal entre residentes", 22, "50% Lurinense"),
        P("economia", "Recuperación integral de playas (Conchán, Mamacona, San Pedro) con servicios básicos e impulso a negocios locales", 31, "Recuperar 3 playas priorizadas", "3 playas priorizadas recuperadas"),
        P("ambiente", "Proyecto Malecón del Río Lurín: paseo ecológico con arborización, senderos, ciclovías e iluminación", 23, "5 km de paseo ecológico-productivo", "5 km de paseo ecológico"),
        P("ambiente", "Clausurar desagües clandestinos y construir un filtro físico de residuos en el límite con Pachacámac", 24, "filtro físico de residuos"),
        P("agua_riesgos", "Dragar la desembocadura del río Lurín y reforzar la defensa ribereña ante inundaciones", 24, "Dragar la desembocadura del río Lurín"),
        P("transporte", "Abrir y pavimentar nuevas salidas desde la Antigua Panamericana Sur hacia la Panamericana Nueva", 25, "nuevas salidas desde la Antigua Panamericana Sur"),
        P("urbano", "Iluminación LED inteligente en calles, avenidas, parques y espacios públicos", 29, "Renovar o instalar 3,000 luminarias LED", "3 000 luminarias LED"),
        P("gestion", "Programa «Papel Cero» con sistemas integrados tipo SAP y procesos digitalizados con trazabilidad", 34, "Digitalizar 70% de procesos internos prioritarios", "70 % de procesos internos prioritarios digitalizados"),
        P("gestion", "Reactivar las cinco agencias municipales con infraestructura y conexión al sistema digital", 26, "apertura de agencias municipales en las cinco zonas"),
    ]),
    ("César Ricardo Noa Casas", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Más vehículos y personal de serenazgo, y creación de la Escuela de Serenazgo de Lurín", 14, "Duplicaremos la flota vehicular y el personal de Serenazgo", "Duplicar la flota y el personal de serenazgo"),
        P("seguridad", "Centrales de monitoreo en las cinco zonas del distrito, con cámaras y drones", 20, "CENTRAL DE MONITOREOS EN LAS 5 ZONAS"),
        P("transporte", "Puente integrador El Olivar y semáforos inteligentes en puntos estratégicos", 14, "puente integrador el Olivar"),
        P("agua_riesgos", "Abastecer de agua potable a los pueblos de Lurín y construir una planta de tratamiento de agua para consumo humano", 15, "cubriendo en un 80% de la población", "80 % de la población a octubre de 2030"),
        P("agua_riesgos", "Brigada de emergencia para las cinco zonas y almacenes municipales ante desastres", 14, "brigada de emergencia del distrito de Lurín"),
        P("urbano", "Entrega de títulos de propiedad mediante convenio con COFOPRI para el saneamiento físico-legal", 15, "cubriendo un 90% de la población del distrito", "90 % de la población a octubre de 2030"),
        P("social", "Gestionar el hospital materno infantil de Lurín y el hospital de Lima Sur", 15, "hospital materno infantil"),
        P("social", "Becas de estudio para jóvenes de bajos recursos en convenio con empresas del distrito", 22, "100 BECAS ANUALES", "100 becas al año"),
        P("economia", "Formalizar a vendedores ambulantes y empresas con licencias de funcionamiento y certificados ITSE", 16, "Formalizar en un plazo de dos años", "A diciembre de 2028"),
        P("ambiente", "Proyectos de tratamiento e industrialización de la basura", 17, "tratamiento e industrialización de la basura", "A diciembre de 2029"),
        P("gestion", "Sistema integrado de gestión ISO 9001 en la municipalidad", 18, "sistema integrado de gestión ISO 9001", "A diciembre de 2027"),
    ]),
    ("Lizardo Alberto Ramos Rivas", "PPC", "partido-popular-cristiano-ppc", [
        P("social", "Primera Escuela Municipal de Artes, Cultura y Danzas financiada con responsabilidad social empresarial", 3, "PRIMERA ESCUELA MUNICIPAL DE LAS ARTES"),
        P("economia", "Gestionar una sede de SENATI y el «Plan Chamba Juvenil» para colocar a jóvenes según las especialidades que piden las empresas", 3, "GESTIONAR UNA NUEVA SEDE DE SENATI", "Mínimo 25 jóvenes capacitados como plan piloto"),
        P("transporte", "Plan vial con paraderos señalizados e iluminados y eliminación de paraderos informales de mototaxis", 4, "PLAN VIAL QUE GARANTICE EL ORDENAMIENTO"),
        P("transporte", "Gestionar con las mancomunidades de Lima Sur la vía costanera como vía alterna para el transporte pesado", 4, "CRISTALIZAR LA VIA COSTANERA"),
        P("seguridad", "Patrullaje preventivo integrado, municipal y con rondas mixtas, en zonas estratégicas de seguridad", 4, "MÍNIMO DE CINCO ZONAS ESTRATÉGICAS", "Mínimo 5 zonas estratégicas de seguridad"),
        P("social", "Atención de neuropediatras para niños con TDAH y TEA y apoyo en salud mental a través de los CLAS", 5, "NEUROPEDIATRAS PARA LA ATENCIÓN"),
        P("ambiente", "Parque lineal del río Lurín con espacios para deporte, arte, ciclovías y recreación familiar", 5, "PARQUE LINEAL DEL RÍO LURÍN"),
        P("ambiente", "Veterinarias municipales y campañas de tenencia responsable de mascotas", 5, "DOS VETERINARIAS AL SERVICIO", "2 veterinarias (zonas A y E)"),
        P("urbano", "Oficina municipal de acompañamiento para el saneamiento de los centros urbanos informales", 6, "OFICINA MUNICIPAL PARA EL ACOMPAÑAMIENTO"),
        P("agua_riesgos", "Plan para descontaminar los canales de regadío con mesa de trabajo de los sectores involucrados", 6, "PLAN PARA DESCONTAMINAR LOS CANALES"),
        P("gestion", "Relanzar las agencias municipales con plataformas virtuales de atención", 7, "5 AGENCIAS MUNICIPALES CON PLATAFORMAS VIRTUALES", "5 agencias municipales con plataformas virtuales"),
    ]),
    ("Ramón Andrés Córdova Arge", "Progresemos", "progresemos", [
        P("seguridad", "Serenazgo por cuadrantes con mapa del delito, cámaras, alarmas comunales y botones de alerta", 8, "Serenazgo por Cuadrantes"),
        P("transporte", "Intercambio vial (paso a desnivel) en el Puente Lurín para eliminar el cuello de botella vehicular", 8, "Perfil o estudio preliminar del Intercambio Vial Puente Lurín", "Perfil o estudio preliminar al 2030"),
        P("transporte", "Plan de circulación de carga pesada con rutas, horarios y zonas logísticas reguladas", 8, "Plan de Circulación de Carga Pesada aprobado", "Plan aprobado al 2030"),
        P("social", "Atención extendida y nocturna en establecimientos de salud, ambulancias, unidad móvil y ruta técnica para un Hospital II-1", 9, "Al menos un establecimiento con atención extendida", "Al menos un establecimiento con atención extendida al 2030"),
        P("social", "Remodelar los establecimientos de salud de Lurín con equipo básico de atención", 19, "remodelar los 06 establecimientos de salud", "6 establecimientos de salud remodelados"),
        P("economia", "Instituto Superior Tecnológico, CETPRO en la Zona E y educación dual, con la Bolsa Laboral «Lurín Primero»", 9, "Bolsa Laboral Lurín Primero"),
        P("economia", "Ordenanza «Lurín Primero» con incentivos a las empresas que contraten vecinos capacitados", 10, "Ordenanza Lurín Primero"),
        P("urbano", "Gran Malecón del Río Lurín: defensa ribereña, ciclovías, espacios deportivos y culturales y bulevar comercial", 12, "Gran Malecón del Río Lurín"),
        P("ambiente", "Arborización con especies de bajo consumo de agua y recuperación de parques", 22, "10,000 especies xerófilas", "10 % más de áreas verdes y 10 parques recuperados por año"),
        P("agua_riesgos", "Unidad municipal de articulación con Sedapal y el Ministerio de Vivienda para el seguimiento de obras de agua y desagüe", 7, "Agua y Desagüe para Todos"),
        P("gestion", "Mesas de concertación, tablero público de compromisos municipales y rendición de cuentas por zona", 7, "Cinco Mesas de Concertación", "5 mesas de concertación funcionando al 2030"),
    ]),
    ("Rosa Elva Torrejón Aragón", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Videovigilancia integrada con cámaras de alta resolución, drones y parlantes en puntos críticos", 25, "parlantes para persuadir actitudes sospechosas"),
        P("seguridad", "Botón de pánico en una aplicación gratuita conectado a la central, el serenazgo y la PNP, y vigilancia por cuadrantes", 26, "botón de pánico o de alerta por medio de una aplicación"),
        P("social", "Policlínico Municipal con farmacia municipal y ambulancias articuladas con el SAMU", 22, "La creación de un Policlínico Municipal"),
        P("urbano", "Convenio con COFOPRI y equipo técnico legal itinerante para formalizar la propiedad", 28, "equipo técnico legal itinerante"),
        P("agua_riesgos", "Conexiones domiciliarias de agua potable y desagüe en zonas urbanas, rurales y asentamientos humanos", 29, "85% de cobertura del sistema agua potable", "85 % de cobertura de agua potable y desagüe"),
        P("agua_riesgos", "Central de monitoreo de riesgos de desastres en Defensa Civil y programa de apoyo a los bomberos voluntarios", 64, "Programa de Apoyo al Cuerpo de Bomberos Voluntarios de Lurín"),
        P("transporte", "Semaforización con inteligencia artificial, señalización vial y peatonal y ciclovías", 42, "Semaforización con Inteligencia Artificial"),
        P("economia", "Consolidar la Ruta Gastronómica del Chicharrón como atractivo turístico y económico", 54, "Ruta Gastronómica del Chicharrón"),
        P("ambiente", "Albergue municipal «Patitas Felices» para animales abandonados y Centro Veterinario Municipal", 56, "Patitas Felices", "Atención integral al 100 % de los animales rescatados que ingresen"),
        P("gestion", "Diagnóstico integral de fondos y bienes municipales y fortalecimiento del control interno", 66, "diagnóstico integral de los fondos y bienes"),
        P("gestion", "Gestión documental «Cero Papel», mesa de partes virtual y casilla electrónica", 68, "Plataforma Digital de Gestión Documental"),
    ]),
]
