"""San Martín de Porres (150135): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150135"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Julio Abraham Chávez Chiong", "Acción Popular", "accion-popular", [
        P("seguridad", "Políticas preventivas con patrullaje integrado serenazgo–PNP por zonas, cuadrantes activos, cámaras inteligentes en calles y respuesta del serenazgo en menos de 5 minutos", 19, "Reducir en 70% los índices de delitos y faltas", "70 % menos delitos y faltas al 2030"),
        P("agua_riesgos", "Plan de prevención ante desastres con énfasis en quebradas, sismos e inundaciones, con muros de contención y campañas de concientización", 21, "Aumentar en 50% la inversión en planes y programas para el riesgo", "50 % más inversión en gestión de riesgos"),
        P("social", "Campañas de concientización y acciones para cumplir el compromiso del Programa de Incentivos en la lucha contra la anemia infantil", 22, "Reducir en 70 % los índices de anemia de los niños", "70 % menos anemia infantil al 2030"),
        P("social", "Políticas locales de igualdad de oportunidades con enfoque inclusivo, intercultural y de género, incluida la prevención de la violencia contra la mujer", 23, "Crear mecanismos orientados a la igualdad de oportunidades con enfoque inclusivo", "3 políticas locales implementadas"),
        P("urbano", "Cartera de proyectos de inversión con impacto distrital para cerrar brechas de infraestructura social, vial, ambiental y económica", 25, "Ejecutar proyectos de inversión con impacto distrital", "200 inversiones públicas al 2030"),
        P("urbano", "Saneamiento físico legal con apoyo de GPS y drones, y asistencia técnica legal gratuita en las zonas con mayor informalidad de la propiedad", 13, "asistencia técnica legal y gratuita en las zonas de mayor informalidad"),
        P("transporte", "Plan de corto plazo para ordenar, formalizar y fiscalizar el servicio de mototaxis en el distrito", 27, "Implementar una política de ordenamiento, formalización y fiscalización de transporte de mototaxis"),
        P("economia", "Intermediación laboral municipal entre empresas y vecinos que buscan empleo, junto con estrategias para reducir el comercio informal", 28, "Elevar en un 60% la integración de personas al mercado laboral formal", "60 % más inserción en el mercado laboral formal"),
        P("ambiente", "Programa de mejoramiento de parques y de arborización con creación de nuevas áreas verdes", 29, "Aumentar el porcentaje de metros cuadrados de áreas verdes por habitante", "200 parques y 50 % más áreas verdes por habitante"),
        P("ambiente", "Reforzar el programa de segregación en la fuente y la recolección de residuos orgánicos e inorgánicos, con inclusión de recicladores formalizados", 30, "Mejorar en un 80% la ejecución del Programa de segregación en la fuente", "80 % de mejora en la ejecución del programa"),
        P("gestion", "Rendición de cuentas semestral en audiencia pública con datos verificables, además de audiencias trimestrales por zonas del distrito", 16, "Se propone una Rendición de Cuentas cada seis meses"),
    ]),
    ("Aquiles Cirilo Collasos Villanueva", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Cámaras con inteligencia artificial conectadas a la PNP, nueva central de monitoreo C4 y patrullaje integrado las 24 horas en las 6 zonas del distrito", 4, "Instalar 1,500 cámaras con Inteligencia Artificial", "1 500 cámaras con IA"),
        P("agua_riesgos", "Mesas de trabajo con SEDAPAL y empresas eléctricas para llevar agua, desagüe y luz a los asentamientos humanos", 5, "Lograr que el 85% de las zonas que hoy no tienen agua inicien sus obras", "85 % de zonas sin agua con obras iniciadas"),
        P("urbano", "Instalar alumbrado LED e internet gratuito en todas las plazas del distrito", 5, "colocar luz LED e internet gratuito en el 100% de las plazas", "100 % de las plazas"),
        P("social", "Recuperar losas deportivas y crear Escuelas Técnicas Municipales gratuitas en herramientas digitales y emprendimiento para jóvenes", 5, "Techar, iluminar y arreglar 20 losas deportivas", "20 losas y 15 000 jóvenes capacitados"),
        P("economia", "Formalizar a los ambulantes sin violencia, reubicándolos en mercados zonales ordenados, empezando por el eje Caquetá–Zarumilla", 6, "Formalizar al 85% de los ambulantes censados", "85 % de ambulantes censados formalizados"),
        P("urbano", "Asfaltar las pistas vecinales con maquinaria municipal propia y sincronizar semáforos en los cruces más congestionados", 6, "Dejar el 100% de las pistas vecinales de las zonas residenciales asfaltadas", "100 % de pistas vecinales residenciales asfaltadas"),
        P("transporte", "Empadronar a los mototaxistas, con paraderos fijos iluminados y un código QR visible en cada unidad", 6, "Formalizar al 90% de los transportistas menores", "90 % de mototaxistas formalizados"),
        P("ambiente", "Nueva contrata de limpieza pública con camiones monitoreados por GPS y horarios fijos para eliminar los 55 puntos críticos de basura", 8, "Reducir a 0% los botaderos informales de basura", "0 % de botaderos informales"),
        P("ambiente", "Arborización masiva y riego tecnificado de parques con agua de pozos subterráneos en lugar de agua potable", 8, "Recuperar el 95% de los parques abandonados", "95 % de parques abandonados recuperados"),
        P("gestion", "Digitalizar pagos tributarios y licencias de pequeños negocios, con tablero digital de metas y portal de transparencia de contratos y gastos", 9, "Lograr que el 100% de los pagos tributarios y licencias comerciales", "100 % de pagos y licencias en línea"),
        P("social", "Clínicas móviles municipales gratuitas, una por zona, con medicina general, pediatría, psicología y control de anemia", 9, "Implementar 6 clínicas móviles municipales", "6 clínicas móviles"),
    ]),
    ("Adolfo Israel Mattos Piaggio", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Ampliar y modernizar la videovigilancia del distrito con fibra óptica y monitoreo en tiempo real", 13, "mediante el uso de fibra óptica, monitoreo en tiempo real"),
        P("seguridad", "Programa «Mi Barrio Seguro»: las juntas vecinales identifican zonas críticas y priorizan intervenciones preventivas", 13, "participación organizada de las juntas vecinales en la identificación de zonas críticas"),
        P("seguridad", "Mejorar el equipamiento, la movilidad y las comunicaciones del serenazgo y reforzar el comité distrital de seguridad ciudadana (CODISEC)", 12, "Fortalecer el servicio de Serenazgo Municipal mediante la mejora progresiva"),
        P("social", "Campañas permanentes de salud mental, atención odontológica, oftalmológica y medicina preventiva para la población vulnerable, mediante alianzas", 21, "atención de la salud atención odontológica"),
        P("social", "Programa de actividades comunitarias: concursos, festivales culturales, clases de baile, ferias vecinales e intercambio de colecciones en los sectores del distrito", 22, "encuentros de intercambio de colecciones y aficiones"),
        P("economia", "Ferias empresariales y ruedas de negocios para emprendedores, y creación de una marca distrital que promueva la economía y el turismo", 17, "ferias empresariales, ruedas de negocios"),
        P("agua_riesgos", "Gestionar con el Ministerio de Vivienda y SEDAPAL la ampliación y el mantenimiento del agua potable y el alcantarillado", 17, "Ministerio de Vivienda, Construcción y Saneamiento, SEDAPAL"),
        P("agua_riesgos", "Gestionar muros de contención, estabilización de taludes y recuperación de espacios públicos en zonas vulnerables", 18, "muros de contención, estabilización de taludes"),
        P("transporte", "Formular un Plan de Articulación Vial Distrital alineado con Lima Metropolitana para mejorar la conectividad y reducir la congestión", 18, "Plan de Articulación Vial Distrital"),
        P("urbano", "Gestionar cerramientos, accesos controlados, rejas e iluminación en urbanizaciones, en coordinación con las organizaciones vecinales", 23, "cerramientos, accesos controlados, rejas urbanizacionales"),
        P("gestion", "Audiencias públicas periódicas de rendición de cuentas a nivel distrital y por territorios, y transformación digital de los trámites", 19, "audiencias públicas de rendición de cuentas, tanto a nivel distrital como territorial"),
    ]),
    ("César Efraín Sifuentes Chávez", "Cooperación, Verdad y Honradez", "cooperacion-verdad-y-honradez", [
        P("seguridad", "Programa «SMP Seguro 2030»: prevención, vigilancia, recuperación de espacios públicos y trabajo conjunto con los vecinos", 2, "Programa integral de seguridad ciudadana orientado a fortalecer la prevención", "30 % menos percepción de inseguridad"),
        P("urbano", "Programa «Parques para Todos»: recuperación de parques, áreas verdes, espacios deportivos y de recreación familiar", 2, "Recuperar 150,000 m² de áreas verdes y espacios públicos", "150 000 m² recuperados"),
        P("economia", "Programa «SMP Emprende»: capacitación, asistencia técnica y formalización de emprendimientos y pequeños negocios", 2, "Formalizar 10,000 emprendimientos y pequeños negocios", "10 000 emprendimientos formalizados"),
        P("economia", "Programas de capacitación y empleabilidad para vecinos", 2, "Beneficiar a 15,000 vecinos mediante programas de capacitación", "15 000 vecinos beneficiados"),
        P("economia", "Modernizar mercados y espacios económicos del distrito", 4, "Modernizar espacios económicos Mercados 15 modernizados", "15 mercados modernizados"),
        P("social", "Ampliar la cobertura de servicios sociales municipales para la población vulnerable", 3, "Ampliar la Incremento de Incrementar 50", "50 % más beneficiarios"),
        P("ambiente", "Programa «SMP Verde»: arborización urbana, limpieza pública, reciclaje y valorización de residuos", 4, "Fortalecer reciclaje y valorización", "40 % de residuos valorizados"),
        P("gestion", "Programa «SMP Digital»: digitalización de procedimientos municipales y simplificación de trámites", 4, "gestión procedimientos municipal digitalizados", "80 % de procedimientos digitalizados"),
        P("gestion", "Audiencias públicas periódicas, informes de avance del plan y portal de transparencia sobre obras e inversiones", 4, "Realizaremos audiencias públicas periódicas", "100 % de cumplimiento de transparencia activa"),
    ]),
    ("César Augusto Vargas Gutiérrez", "Fe en el Perú", "fe-en-el-peru", [
        P("seguridad", "Fortalecer las juntas vecinales e instalar cámaras de videovigilancia con reconocimiento facial dentro de un plan integral de seguridad ciudadana", 36, "instalación de cámaras de video vigilancia y reconocimiento facial"),
        P("seguridad", "Construir bases integradas de seguridad ciudadana, capacitar al serenazgo con asesoría legal y psicológica y cerrar antros en acuerdo con empresarios", 36, "Construcción de bases Integradas de Seguridad Ciudadana"),
        P("social", "Módulos de salud por zonas en convenio con SISOL, ambulancias gratuitas las 24 horas, farmacia municipal y laboratorio clínico", 34, "Implementar módulos de salud en diferentes zonas del distrito en convenio con SISOL"),
        P("social", "Reforzamiento escolar con academias y preuniversitarios para 3.º a 5.º de secundaria, capacitación docente con universidades y convenios de becas", 35, "Programas de reforzamiento educativo en alianza con academias"),
        P("social", "Servicio municipal gratuito de médicos de cabecera para el adulto mayor, con talleres y atención social por línea telefónica", 42, "Médicos de Cabecera para el Adulto Mayor"),
        P("economia", "Crear un CITE industrial, organizar expoferias alimentarias, manufactureras y artesanales y dar talleres de gestión empresarial a mypes", 36, "Implementación de CITE industrial"),
        P("gestion", "Informar periódicamente en el periódico mural y la web municipal sobre el avance del plan y rendir cuentas de ingresos y egresos mensuales", 42, "rindiendo cuentas de los ingresos y egresos mensuales"),
        P("transporte", "Reordenar el tránsito de mototaxis en puntos críticos, mejorar vías alternas y pavimentar calles y avenidas deterioradas", 38, "Reordenamiento del transporte vehicular (Mototáxis) en los puntos críticos"),
        P("urbano", "Gestionar el Parque Lineal Ribereño Chuquitanta, construir el bulevar de Tomás Valle y un circuito turístico de huacas y haciendas", 38, "Gestión de la construcción del Parque Lineal Ribereño Chuquitanta"),
        P("agua_riesgos", "Postular al FONDES para muros de contención y defensas ribereñas en los ríos Chillón y Rímac, y cercar las márgenes del Rímac", 40, "para la construcción de muros de contención y defensa ribereñas"),
        P("ambiente", "Unidades motorizadas menores para recoger basura acumulada en la vía pública, segregación de residuos, contenedores y repotenciación del vivero municipal", 39, "Implementación de unidades menores motorizadas"),
    ]),
    ("Luis César Navarro Maldonado", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("seguridad", "Videovigilancia en todas las zonas críticas y un Centro Integrado de Seguridad", 4, "100% de cobertura de videovigilancia en zonas críticas", "100 % de zonas críticas con videovigilancia"),
        P("seguridad", "Ampliar el patrullaje integrado para reducir los delitos patrimoniales", 4, "Reducción del 30% de delitos patrimoniales", "30 % menos delitos patrimoniales y 50 % más patrullaje integrado"),
        P("social", "Cobertura total de programas para adultos mayores y apertura de nuevas bibliotecas digitales", 4, "10 nuevas bibliotecas digitales", "100 % de adultos mayores cubiertos y 10 bibliotecas digitales"),
        P("social", "Crear Centros Integrales Comunitarios y recuperar espacios deportivos", 4, "10 Centros Integrales Comunitarios, 50 espacios deportivos recuperados", "10 centros comunitarios y 50 espacios deportivos"),
        P("economia", "Generar puestos de trabajo en el distrito y formalizar licencias de funcionamiento de mypes", 4, "5,000 nuevos empleos", "5 000 empleos y 5 000 mypes formalizadas"),
        P("economia", "Promover la innovación empresarial con la apertura de centros de innovación", 4, "Promover la innovación Empresarial", "4 centros de innovación empresarial"),
        P("ambiente", "Cobertura total de limpieza pública y una planta de reciclaje en el distrito", 4, "Planta de reciclaje en el", "100 % de cobertura de limpieza pública"),
        P("ambiente", "Aumentar las áreas verdes por habitante e implementar un sistema de riego distrital", 4, "sistema de riego en smp"),
        P("gestion", "Portal de transparencia en tiempo real y certificación de gestión bajo normas ISO 9001, 14001, 45001 y SA 8000", 5, "transparencia en tiempo real"),
    ]),
    ("Carlos Alberto Albujar Corazón", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Central integrada de monitoreo, cámaras inteligentes, drones, serenazgo motorizado, nuevas camionetas y botón de pánico con aplicación móvil", 2, "500 cámaras inteligentes", "500 cámaras inteligentes y 40 % menos delitos"),
        P("transporte", "Ordenamiento de rutas, multas electrónicas y operativos integrados con la PNP contra el desorden vehicular y el comercio informal", 11, "Ordenamiento de rutas y multas electrónicas", "25 % menos infracciones"),
        P("urbano", "Plan integral de pistas y veredas, con muros de contención y escaleras en zonas que lo requieran", 3, "Plan Integral de Pistas y Veredas", "100 km de pistas y 150 km de veredas"),
        P("urbano", "Programa «100 parques»: recuperación de parques, plazas y losas deportivas con iluminación LED", 3, "100 parques recuperados", "100 parques recuperados"),
        P("social", "Hospital Municipal y programa «Médico en tu Barrio», con salud mental comunitaria", 3, "Médico en tu Barrio", "100 000 atenciones anuales"),
        P("social", "Programa contra la anemia infantil con programas alimentarios bajo control nutricional", 3, "Reducir anemia infantil en 20%", "20 % menos anemia infantil"),
        P("social", "Palacio de la Juventud, academia municipal gratuita, becas SMP y alfabetización digital", 3, "Academia Municipal Gratuita", "1 000 becas y 10 000 estudiantes beneficiados"),
        P("social", "Construir la Casa de la Mujer Sanmartiniana, programa «Mujer Emprende» y descentralizar la red del adulto mayor", 4, "Construcción de la Casa de la Mujer Sanmartiniana", "15 000 mujeres capacitadas"),
        P("economia", "Bolsa de trabajo municipal, centro de emprendimiento, ferias productivas y formalización empresarial", 4, "Bolsa de Trabajo Municipal", "20 000 empleos promovidos y 5 000 negocios formalizados"),
        P("ambiente", "Programa «SMP Verde» con ecoparques, arborización, gestión de residuos y un parque para mascotas", 4, "35% más áreas verdes", "50 000 árboles y 35 % más áreas verdes"),
        P("gestion", "Municipalidad digital y portal «Obras Transparentes», con presupuesto participativo y gobierno abierto", 5, "90% trámites digitalizados", "90 % de trámites digitalizados y 100 % de obras publicadas"),
    ]),
    ("Luis Paúl Cárdenas Sánchez", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Instalar cámaras de videovigilancia y alarmas comunitarias en el distrito", 10, "Implementar 100 cámaras de video vigilancia y 100 alarmas comunitarias", "100 cámaras y 100 alarmas comunitarias"),
        P("seguridad", "Convenio con el Ministerio del Interior y la PNP para patrullaje integrado y gestión para rotar al personal policial de comisarías cada seis meses", 10, "Gestionar la rotación del personal policial en las comisarías"),
        P("social", "Crear e implementar la segunda Casa Distrital del Adulto Mayor", 9, "Crear e implementar la segunda Casa Distrital del Adulto Mayor"),
        P("social", "Implementar dos policlínicos municipales, uno itinerante y otro permanente", 10, "Implementar 02 policlínicos municipales (itinerante y permanente)", "2 policlínicos municipales"),
        P("social", "Programa «Luchito» para atender a la población infantil con anemia", 11, "Implementación del Programa Luchito, para atender a la población con anemia"),
        P("ambiente", "Renovar la flota de recolección con compactadores nuevos y un sistema de repaso para evitar residuos acumulados en la vía pública", 12, "Adquisición de 08 vehículos compactadores", "8 vehículos compactadores"),
        P("transporte", "Construir ciclovías en las principales vías del distrito y fiscalizar la circulación de carga pesada en horarios no permitidos", 13, "Implementar 03 ciclovías en las principales vías del distrito", "3 ciclovías"),
        P("agua_riesgos", "Descolmatación anual del cauce del río Chillón y programa «Construyamos juntos» de asesoría técnica para construcciones seguras", 13, "descolmatación anual del cauce del río Chillón"),
        P("urbano", "Construir o reconstruir vías deterioradas y nuevas, gestionando el mantenimiento de avenidas como Perú, Naranjal, Paramonga y José Granda", 13, "Construcción y/o reconstrucción del 50% de las vías deterioradas", "50 % de vías deterioradas y 50 % de vías nuevas"),
        P("economia", "Escuela de Emprendimiento, programa «La Ruta Emprendedora», ferias laborales y bolsa de trabajo municipal", 15, "Realización de 05 ferias laborales al año", "5 ferias laborales al año"),
        P("gestion", "Certificaciones ISO 9001 de calidad e ISO 37001 antisoborno y reforma tributaria para reducir la morosidad", 16, "Reducir la morosidad tributaria al 50%", "Morosidad tributaria reducida al 50 %"),
    ]),
    ("Luis Alberto Flores Roldán", "Partido Morado", "partido-morado", [
        P("seguridad", "Serenazgo con patrullaje focalizado y control territorial en zonas críticas, articulado con la PNP, con escuela de formación y ascensos por mérito", 3, "Reducir delitos en 25%, lograr 100% de cobertura en zonas críticas", "25 % menos delitos; respuesta en menos de 10 minutos"),
        P("seguridad", "Cámaras en puntos críticos integradas a la central de monitoreo y sistema de inteligencia de incidencias compartido con la PNP", 4, "Instalar entre 150 y 250 cámaras", "150 a 250 cámaras"),
        P("social", "Programa «SMP sin Anemia»: tamizaje de hemoglobina, seguimiento nutricional y educación alimentaria con comedores, Vaso de Leche y colegios", 4, "Tamizaje de hemoglobina, seguimiento nutricional y educación alimentaria"),
        P("social", "Gestionar un hospital municipal de atención preventiva, consulta externa y urgencias básicas: preinversión, saneamiento del terreno y expediente técnico", 6, "Hospital Municipal de San Martín de Porres", "Viabilidad e inicio de la primera etapa al 2030"),
        P("social", "Programa «Jóvenes con Futuro» de capacitación e inserción laboral con empresas e institutos técnicos, y rehabilitación de 50 losas deportivas", 6, "Reducir la tasa NINI de 18.5% a 12%", "Tasa de jóvenes que no estudian ni trabajan de 18,5 % a 12 %"),
        P("economia", "Registro voluntario de comerciantes informales y ventanilla única que reúne RUC, licencia municipal y SIS, con tasas de licencia reducidas por 24 meses", 9, "Ventanilla única, con canal físico y digital", "1 000 comerciantes registrados el primer año"),
        P("economia", "Centro de Empleo en convenio con el MTPE, con bolsa de trabajo y capacitación certificada, más ferias itinerantes de empleo", 10, "Vincular 500 personas a empleo formal en el primer año", "500 personas con empleo formal el primer año"),
        P("transporte", "Seguridad vial: mapa de puntos negros, señalética en cruces críticos, reductores de velocidad y rampas de accesibilidad", 11, "Instalar 40 reductores en el primer año", "40 reductores y 10 cruces señalizados el primer año"),
        P("ambiente", "Fiscalización permanente y campañas para eliminar la quema de residuos, y control del ruido con sonómetros", 12, "Reducir la quema en 80% con fiscalización permanente", "80 % menos quema de residuos"),
        P("agua_riesgos", "Gestión ante SEDAPAL para priorizar obras en zonas vulnerables, fiscalización de su servicio y cisternas en zonas sin agua", 12, "atención de emergencias con cisternas en zonas sin servicio"),
        P("gestion", "Presupuesto participativo sobre parte de la inversión, audiencias descentralizadas y respuesta obligatoria a reportes ciudadanos en 15 días hábiles", 16, "alrededor del 10% de la inversión pública sea decidido con la ciudadanía", "Cerca del 10 % de la inversión decidida con la ciudadanía"),
    ]),
    ("Alan Rudy Vásquez Dávila", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Seguridad por cuadrantes con jefaturas subzonales, patrullaje integrado con la PNP y duplicación progresiva del número de serenos", 4, "Implementación del modelo de seguridad por cuadrantes", "40 % menos delitos contra el patrimonio"),
        P("seguridad", "Cámaras con central de monitoreo con inteligencia artificial conectada al 105, e iluminación LED en el 60 % del distrito", 5, "La adquisición de 500 cámaras requerirá una Central de Monitoreo", "500 cámaras nuevas y LED en el 60 % del distrito"),
        P("urbano", "Oficina técnica de obras y programa de obras comunales participativas, con recuperación de obras paralizadas", 5, "Ejecutar más de 150 obras vecinales", "Más de 150 obras vecinales"),
        P("social", "Construir el Gran Polideportivo Metropolitano y un anfiteatro municipal mediante fondos concursables u obras por impuestos", 5, "Construcción del Gran Polideportivo Metropolitano"),
        P("social", "Policlínico municipal mediante asociación público-privada, con campañas médicas descentralizadas y atención de salud mental", 6, "Creación del Policlínico Municipal con participación privada", "Más de 100 000 atenciones médicas al año"),
        P("social", "Reducir la anemia infantil con visitas domiciliarias y entrega de hierro mediante la Instancia de Articulación Local", 7, "Reducir en 20% los índices de anemia infantil", "20 % menos anemia infantil"),
        P("social", "Descentralizar las Casas del Adulto Mayor y la OMAPED, con inclusión laboral de personas con discapacidad y un albergue municipal", 8, "Implementar tres centros descentralizados para adultos mayores", "3 centros descentralizados para adultos mayores"),
        P("economia", "Mercado Municipal donde comerciantes informales compren sus puestos a largo plazo y licencia de funcionamiento digital automática", 10, "permitiendo que los mismos comerciantes informales compren sus puestos", "5 000 emprendimientos formalizados"),
        P("ambiente", "Arborización con vivero municipal hidropónico y riego por goteo desde pozos tubulares, más trimotos para limpieza en zonas de difícil acceso", 11, "Activación del Vivero Municipal", "100 000 árboles y 50 % más áreas verdes"),
        P("agua_riesgos", "Sistema de alerta temprana con sensores en el río Rímac y laderas, muros de contención y tres almacenes de ayuda humanitaria", 14, "Implementación del Sistema de Alerta Temprana (SAT) Comunitario", "3 almacenes de avanzada"),
        P("gestion", "Gobierno digital con mesa de partes virtual y aplicativo para seguir obras en tiempo real enlazado con Infobras", 12, "Digitalizar el 100% de los trámites municipales", "100 % de trámites digitalizados y 70 % menos tiempo de atención"),
    ]),
    ("Enrique Amador Escalante Carpio", "Perú Libre", "partido-politico-nacional-peru-libre", [
        P("seguridad", "Gestionar con el Ministerio del Interior cuatro nuevas comisarías y más efectivos policiales asignados al distrito", 2, "construcción e implementación de cuatro nuevas comisarías", "4 nuevas comisarías"),
        P("seguridad", "Cámaras inteligentes conectadas a una central de monitoreo permanente, bases descentralizadas de serenazgo y aplicación «Alerta Vecino SMP»", 2, "Implementar 2,000 cámaras inteligentes", "2 000 cámaras inteligentes"),
        P("ambiente", "Nueva flota de camiones compactadores, rutas inteligentes de recolección, contenedores en zonas comerciales y eliminación de puntos críticos de basura", 3, "Adquirir una nueva flota de camiones compactadores"),
        P("ambiente", "Recuperar parques con riego tecnificado, viveros municipales y arborización de bermas y jardines", 4, "Recuperar 100 parques durante la gestión", "100 parques recuperados"),
        P("economia", "Empadronar a comerciantes ambulantes y reordenarlos por rubros y zonas autorizadas, con ferias productivas distritales", 4, "Empadronamiento integral de comerciantes ambulantes"),
        P("economia", "Capacitación gratuita en emprendimiento, convenios con entidades financieras para créditos y formalización simplificada", 4, "Convenios con entidades financieras para acceso a créditos"),
        P("social", "Policlínico municipal, clínicas móviles, ambulancias, farmacia social y programa contra la anemia infantil", 5, "Construcción del Policlínico Municipal de San Martín de Porres"),
        P("social", "Academia preuniversitaria municipal gratuita, becas para estudiantes, bibliotecas digitales y escuelas deportivas gratuitas", 5, "Academia Preuniversitaria Municipal Gratuita"),
        P("urbano", "Pistas y veredas, iluminación LED, mejora de accesos en asentamientos humanos y gestión de proyectos de agua y saneamiento", 6, "Mejoramiento de accesos en asentamientos humanos"),
        P("social", "Fortalecer el Centro Integral del Adulto Mayor y la OMAPED, con atención médica domiciliaria y apoyo a comedores populares", 6, "Programas de atención médica domiciliaria"),
        P("gestion", "Rendición de cuentas semestral, transmisión en vivo de sesiones de concejo y fiscalización vecinal de obras", 6, "Transmisión en vivo de las sesiones de concejo"),
    ]),
    ("Víctor Vicente Santander Salvador", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Programa preventivo «Alerta 360» con enfoque territorial, que refuerza la videovigilancia con drones operados por serenos con licencia del MTC", 10, "se reforzará la videovigilancia con la compra de drones", "80 % menos delitos y faltas al 2030"),
        P("seguridad", "Cámaras de videovigilancia con inteligencia artificial: reconocimiento facial, detección de armas y conductas sospechosas y lectura de placas de vehículos robados", 10, "reconocimiento de placas para detectar vehículos robados"),
        P("seguridad", "Creación de dos comisarías: una en la Asociación Los Reyes (Chuquitanta) y otra en la avenida Paramonga con Sol de Naranjal", 11, "Creación de dos Comisarias una ubicada en la Asociación"),
        P("agua_riesgos", "Limpieza y descolmatación del río Chillón y construcción de diques de contención para prevenir inundaciones y desbordes", 11, "construcción de diques de contención para prevenir inundaciones", "50 % más inversión en riesgo de desastres"),
        P("transporte", "Obra de accesibilidad y transitabilidad en la zona de Villa Isolina para conectar con las avenidas Canta Callao y Chuquitanta", 11, "Obra de accesibilidad y transitabilidad en la Zona de Villa Isolina"),
        P("social", "Villa Deportiva en el terreno del antiguo Hospital Portada de Guía (Piñonate), mediante inversión privada bajo la modalidad de Proyecto en Activo", 12, "en el terreno ubicado en el barrio de Piñonate"),
        P("social", "Lucha contra la anemia con visitas domiciliarias y suplementación con hierro a niños y gestantes, articulada con el Programa de Incentivos Municipales", 12, "visitas domiciliarias y suplementación con hierro", "70 % menos anemia infantil"),
        P("social", "Construir una Casa de la Mujer con guardería para madres trabajadoras y vivienda para mujeres víctimas de violencia", 13, "Obra casa de la Mujer con la finalidad de brindar guardería"),
        P("ambiente", "Política de arborización «San Martín de Porres: distrito verde y saludable» para ampliar áreas verdes y parques", 15, "Implementación de la política de arborización", "50 % más m² de áreas verdes por habitante"),
        P("economia", "Intermediación laboral desde la municipalidad entre empresas y personas que buscan empleo", 26, "Promover la intermediación de oportunidades laborales", "60 % más integración al mercado laboral formal"),
        P("gestion", "Simplificar procedimientos administrativos y agilizar trámites, junto con buenas prácticas de gestión municipal replicables", 30, "10 procedimientos administrativos simplificados", "10 procedimientos simplificados"),
    ]),
    ("Yuri Luis Medina Barrios", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Aplicación de alerta vecinal «Alerta SMP» para reportar incidencias geolocalizadas en tiempo real", 7, "App de alerta vecinal (Alerta SMP)"),
        P("seguridad", "Cámaras con inteligencia artificial y reconocimiento facial en zonas de alto tránsito, y aplicación detectora de placas para Serenazgo y PNP", 7, "especializadas en reconocimiento facial en zonas de alto tránsito"),
        P("seguridad", "Centro de monitoreo con análisis predictivo para despachar patrullas y protocolo de custodia de evidencia digital para la Fiscalía", 7, "Creación del Protocolo de Evidencia digital"),
        P("urbano", "Obras por Impuestos con los principales contribuyentes para pistas, veredas y servicios básicos", 8, "Ejecución de proyectos bajo la modalidad de Obras por Impuestos"),
        P("urbano", "Asociación público-privada para renovar el alumbrado con luminarias LED inteligentes que sirvan de soporte a cámaras", 8, "renovación total del alumbrado público a luminarias LED inteligentes"),
        P("agua_riesgos", "Obras de infraestructura y saneamiento en zonas de expansión urbana mediante Proyectos en Activos con terrenos municipales", 8, "mediante el mecanismo de Proyectos en Activos"),
        P("economia", "Mercados modelo y centros comerciales descentralizados en zonas de expansión urbana para reubicar comercios y desaglomerar zonas saturadas", 9, "Desarrollo de Mercados Modelos y Centros Comerciales Descentralizados"),
        P("economia", "Fiscalización con acompañamiento técnico y plazos de gracia para la formalización voluntaria de micro y pequeñas empresas", 9, "Transformación de la Fiscalización en un Ente Promotor"),
        P("economia", "Incubadora municipal de base tecnológica y programa de digitalización y comercio electrónico para mypes", 9, "Lanzamiento de la Incubadora Municipal de Base Tecnológica"),
        P("gestion", "Reducir las gerencias operativas a cinco gerencias estratégicas y reasignar personal CAS a seguridad y fiscalización", 10, "reducir las gerencias operativas a 5 Gerencias Estratégicas", "5 gerencias estratégicas"),
        P("gestion", "Licencias de funcionamiento automatizadas para negocios de bajo riesgo, mesa de partes digital y tableros públicos sobre el presupuesto", 10, "en un plazo aproximado de 24 horas", "Licencias de bajo riesgo en unas 24 horas"),
    ]),
    ("Jiulliana Paola Herrera Moscoso", "Partido SíCreo", "partido-sicreo", [
        P("seguridad", "Instalar cámaras con inteligencia artificial, reconocimiento facial y lectura de placas conectadas a la PNP, financiadas mediante Obras por Impuestos", 4, "pasar de 100 cámaras operativas a 500 cámaras inteligentes operativas", "500 cámaras con IA al 2030"),
        P("seguridad", "Ampliar el serenazgo con equipamiento autorizado por ley (bodycams, chalecos, pistolas eléctricas), curso obligatorio de 200 horas y GPS público de patrulleros", 4, "pasar de aproximadamente 850 serenos actuales a 1 200 serenos", "1 200 serenos al 2030"),
        P("seguridad", "Patrullaje integrado PNP–serenazgo por cuadrantes, convenio de persecución en flagrancia con distritos vecinos y línea anónima contra la extorsión", 5, "Convenio formal MDSMP-PNP firmado en los primeros 30 días de gestión", "30 % menos homicidios al 2030"),
        P("ambiente", "Plan de choque para erradicar los 19 puntos críticos de basura, nueva licitación de limpieza con GPS y segregación en la fuente en la mitad de predios", 7, "Plan de Choque 100 días: erradicación física", "Cero puntos críticos al 2028"),
        P("ambiente", "Plan maestro de arborización con especies nativas, 100 nuevas áreas verdes y mantenimiento mensual de los 453 parques", 9, "plantar 10 000 árboles nativos por año", "40 000 árboles y 4 m² verdes por habitante al 2030"),
        P("social", "Cuatro Centros Integrales del Adulto Mayor con talleres productivos, ferias bimestrales de venta, atención médica y psicológica gratuita", 11, "Construcción de 4 centros estratégicamente ubicados", "4 CIAM operativos al cierre del año 2"),
        P("social", "Construir y rehabilitar losas deportivas con escuelas deportivas gratuitas y becas para talentos, junto con prevención del consumo de drogas", 15, "Construcción y rehabilitación de 100 canchas de losa", "100 losas en 4 años; 4 000 niños y jóvenes al año"),
        P("social", "Crear un Instituto Tecnológico Municipal gratuito con 8 carreras técnicas, becas, bolsa de empleo e incubadora de emprendimientos", 17, "Creación del Instituto de Educación Superior Tecnológico Municipal", "2 400 estudiantes en formación al 2030"),
        P("economia", "Licencia de funcionamiento en 72 horas para giros de bajo riesgo, trámite íntegramente en línea y ordenanza que permite operar 24 horas a ciertos giros", 13, "Licencia provisional automática para giros de bajo riesgo", "Licencia en 72 horas"),
        P("gestion", "Saneamiento fiscal con reforma catastral, auditoría externa y control concurrente, más digitalización total de trámites y pago en línea de tributos", 20, "100 % de trámites municipales digitalizados al 2028", "100 % de trámites digitalizados al 2028"),
        P("agua_riesgos", "Descolmatación del río Chillón en convenio con la ANA, sistema de alerta temprana de inundaciones y reubicación gradual de familias en alto riesgo", 20, "descolmatación anual de 3 km del Río Chillón", "3 km de descolmatación al año"),
    ]),
    ("Diego Armando López Jara", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Programa «San Martín de Porres +Seguridad +Vida»: drones y cámaras con lector facial en zonas críticas de alta criminalidad", 9, "adquisición de drones y cámaras de seguridad con lector facial"),
        P("transporte", "Pedir a Lima Metropolitana la transferencia de funciones para construir dos bypass en la avenida Perú y un corredor de segundo piso junto al río Chillón", 3, "construcción de 2 bypass en la avenida Perú"),
        P("transporte", "Programa Smart City «+Sanmartiniano»: observatorio de tráfico, semaforización automatizada y movilidad digital para reducir congestión y accidentes", 15, "se implementa un observatorio de tráfico"),
        P("urbano", "Mejorar kilómetros de pistas del distrito financiados mediante obras por impuestos", 8, "el mejoramiento de 33 kilómetros de pistas", "33 km de pistas"),
        P("ambiente", "Programa «Te quiero Verde»: proyecto forestal para plantar árboles y reducir la sensación térmica", 10, "el cual sembrará 3 millones de árboles", "3 millones de árboles"),
        P("ambiente", "Empresa social de residuos sólidos en alianza con los recicladores del distrito, con educación ambiental en colegios y empresas", 10, "creación de una empresa social de residuos sólidos"),
        P("social", "Becas municipales en carreras técnicas de servicios digitales para estudiantes con promedio final mayor a 15", 12, "programa de becas para todos los estudiantes que tengan más de 15"),
        P("social", "Construir un hospital de nivel III con cirugía de alta complejidad y tratamiento oncológico, además de un policlínico municipal y la Botica del Pueblo", 14, "Construcción de un hospital de Nivel III"),
        P("social", "Aplicativo «Amara» para prevenir y reportar violencia contra la mujer y «Patrulla ámbar» para vigilar el cumplimiento de órdenes de alejamiento", 13, "Programa: Patrulla ámbar, consiste en patrullar vecindarios"),
        P("economia", "Formalización progresiva de ambulantes, creación de mercados municipales con alquiler de bajo costo y capacitación en finanzas personales", 15, "Creación de mercados municipales, con alquiler a bajo costo"),
        P("gestion", "Gerencia de Inteligencia Tributaria, catastro georreferenciado con drones e imágenes satelitales y pago y notificación tributaria en línea", 16, "Creación de una Gerencia de Inteligencia Tributaria"),
    ]),
    ("Anndy Miguel Durán Núñez", "Progresemos", "progresemos", [
        P("seguridad", "Instalar 600 cámaras de videovigilancia de 360° interconectadas con los puestos de auxilio rápido y monitoreadas por personal capacitado", 8, "Instalación de 600 cámaras de videovigilancia", "600 cámaras de videovigilancia"),
        P("seguridad", "Construir 200 puestos de auxilio rápido en puntos críticos y crear un grupo especializado de serenazgo (GAR) que trabaje con la PNP", 8, "Construcción de 200 puestos de auxilio rápido", "200 puestos de auxilio rápido"),
        P("seguridad", "Botones de pánico en zonas críticas y aplicativo «Alerta S.M.P.» para que los vecinos reporten delitos y emergencias las 24 horas", 8, "aplicativo que sea interactivo y accesible para todos los vecinos 24/7"),
        P("social", "Campañas médicas móviles para adultos mayores, programa «Salud para todos» con inmunización y charlas contra la desnutrición, y farmacia municipal a costo social", 9, "se implementará la Farmacia Municipal a costo social"),
        P("social", "Crear una academia municipal y una escuela técnica municipal a costo social con cursos de electricidad, gasfitería, diseño gráfico y computación", 10, "Creación de la Academia Municipal y Escuela Técnica Municipal"),
        P("economia", "Aplicativo «Formalízate ya» para tramitar licencias de funcionamiento e ITSE en menos tiempo y simplificar la obtención de licencias", 12, "realizar tus trámites de obtención de Licencias de funcionamiento"),
        P("economia", "Formalizar el comercio ambulatorio y organizar ferias semanales en cada sector para la venta de productos de los ambulantes", 13, "Realizar ferias semanales en cada sector"),
        P("transporte", "Empadronar y formalizar a las empresas de mototaxis, curso de seguridad vial para sus conductores, paraderos señalizados y campañas de semaforización", 14, "Empadronar y formalizar a las empresas de transporte de vehículos menores"),
        P("agua_riesgos", "Evaluar riberas y suelos para actualizar el mapa de riesgos del distrito y crear brigadas de emergencia con hospitales, policía y bomberos", 14, "mapa de calor del distrito"),
        P("ambiente", "Bonos «Buen Vecino» con descuento en arbitrios por reciclar, contenedores en avenidas y campañas mensuales de eliminación de desmonte", 15, "bonos de Buen Vecino para el descuento en arbitrios"),
        P("gestion", "Oficina de integridad con canales de denuncia anónima, digitalización de trámites y una comisión de disciplina que denuncie y separe a funcionarios corruptos", 17, "oficina de integridad y lucha contra la corrupción"),
    ]),
    ("Peter Omar Jaime Cori", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Sistema de reconocimiento facial con inteligencia artificial para la central de videovigilancia, más cámaras y ampliación de la red de fibra óptica", 17, "Adquisición de sistema de reconocimiento facial con IA"),
        P("seguridad", "Convenio con la PNP para instalar una base del escuadrón verde en el distrito y promoción de los comités de seguridad ciudadana", 17, "Convenio con la PNP para establecer base de escuadrón verde", "70 % menos inseguridad ciudadana"),
        P("transporte", "Fiscalización de vehículos menores informales, revisión de licencias de transporte y plataforma de denuncias para usuarios y transportistas", 22, "Fiscalización y erradicación de vehículos menores informales"),
        P("social", "Programa «Becados» financiado por la municipalidad para cubrir estudios técnicos y universitarios de jóvenes de escasos recursos y con discapacidad", 29, "busca subvencionar los costos de educación técnica y universitaria"),
        P("social", "Programa «Mil Oficios» con el Ministerio de Educación para formación técnica en 4.° y 5.° de secundaria, más complejos deportivos descentralizados y teatro municipal", 29, "replicar esto al término del mandato a 4 centros educativos", "4 centros educativos técnico-industriales al final del mandato"),
        P("economia", "Programa «Formaliza-tú» para micro y pequeñas empresas, ferias itinerantes y plataforma laboral en convenio con el MINTRA", 37, "Creación de programa de formalización para las pequeñas y Microempresas", "30 % del comercio informal formalizado"),
        P("gestion", "Convenio con la PCM para instalar un centro MAC, pagos y trámites en línea y wifi gratuito en parques", 41, "Suscribir convenio con la PCM para la instalación de un MAC"),
        P("agua_riesgos", "Reformular el plan de gestión del riesgo de desastres, equipar almacenes, instalar alarmas de alerta y fortalecer brigadas de Defensa Civil", 47, "Reformular plan de gestión de riesgo de desastres"),
        P("ambiente", "Reciclaje distrital, planta de compostaje municipal, contenedores soterrados en puntos críticos y planta de tratamiento de PET", 50, "Implementación de planta de compostaje municipal", "35 % menos residuos sólidos"),
        P("ambiente", "Riego tecnificado con red de pozos tubulares, dos viveros municipales y programa de arborización «San Martín Verde» en avenidas principales", 51, "Construcción y habilitación de dos viveros municipales", "30 % más áreas verdes"),
        P("urbano", "Plan de inversiones con pistas y veredas, centro cultural, multideportivos, centro de salud de atención primaria y parques", 52, "asciende a la suma de S/. 160 000 000.00", "S/ 160 millones de inversión en 4 años"),
    ]),
]
