"""Magdalena del Mar (150120): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150120"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Mercedes Victoria Morocho Arias", "Acción Popular", "accion-popular", [
        P("seguridad", "Programa «Magdalena Segura 360°»: más cámaras inteligentes, red con inteligencia artificial, módulos modernizados y videovigilancia integrada con viviendas", 5, "duplicar la cantidad de cámaras inteligentes", "Duplicar las cámaras inteligentes y cubrir el 100 % del distrito con videovigilancia"),
        P("seguridad", "Plan «Fronteras Seguras» con patrullaje conjunto e interoperabilidad con las municipalidades limítrofes", 5, "Fronteras Seguras"),
        P("social", "Dos ambulancias municipales de apoyo y una central distrital de coordinación de emergencias médicas", 12, "Implementación progresiva de dos ambulancias", "Al menos 2 500 emergencias y traslados asistidos por año al 2030"),
        P("social", "Programa «Magdalena Te Escucha» de salud mental con talleres, campañas trimestrales y orientación psicológica inicial", 13, "Beneficiar a 10,000 vecinos", "10 000 vecinos beneficiados al 2030"),
        P("social", "Centro Cultural en la Costa Verde, museo municipal y conservatorio de artes", 14, "Centro Cultural Magdalena"),
        P("ambiente", "Red de infraestructura verde con sensores, riego inteligente y monitoreo ambiental en parques, calles y la Costa Verde", 17, "sistemas de riego inteligente, monitoreo ambiental"),
        P("ambiente", "Programa de economía circular «La vida es un ciclo» con segregación, reciclaje y compostaje", 17, "La vida es un ciclo"),
        P("transporte", "Programa «Magdalena Vuelve al Mar»: teleférico, buses eléctricos municipales y nuevas conexiones peatonales y ciclistas hacia la Costa Verde", 18, "Magdalena Vuelve al Mar"),
        P("urbano", "Macromanzana peatonal alrededor del Mercado de Magdalena, con terrazas gastronómicas y menos tráfico de paso", 22, "macromanzana peatonal"),
        P("economia", "Programa «Formal estoy mejor»: remodelación del Mercado Central, convenios tributarios y ordenamiento del comercio", 23, "Formal estoy mejor"),
        P("gestion", "Municipalidad sin papel con expediente electrónico por vecino e interoperabilidad con las bases de datos del Estado", 27, "Expediente electrónico por cada vecino"),
    ]),
    ("Franz Teseo Mario Neyra Barreda", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Patrullaje en cuatro modalidades en todos los sectores y aplicativo «Alerta Vecino Magdalense» para reportar delitos en tiempo real", 2, "Alerta Vecino Magdalense"),
        P("social", "Casa de la Juventud, Casa de la Mujer, Comedor Municipal y servicio de atención domiciliaria", 6, "Casa de la Juventud, Casa de la Mujer, Comedor Municipal", "Servicios implementados al 2030"),
        P("social", "Academia preuniversitaria gratuita y cursos gratuitos de conducción para jóvenes de 18 a 21 años", 7, "Academia preuniversitaria gratuita"),
        P("transporte", "«Magdalena Bus»: buses eléctricos municipales gratuitos que recorran las principales rutas del distrito", 19, "Dotación de 10 buses eléctricos", "10 buses eléctricos"),
        P("economia", "Licencia de funcionamiento exprés para negocios de bajo riesgo mediante un sistema digital", 10, "Licencia Express y Simplificación Administrativa", "Licencias de bajo riesgo en un máximo de 24 horas"),
        P("economia", "Formalización con asistencia técnica y legal gratuita, incentivos temporales y reubicación concertada en ferias itinerantes", 11, "formalización del 80% de los micro comerciantes", "80 % de los micro comerciantes censados formalizados"),
        P("economia", "Bolsa de empleo municipal «Chamba en Magdalena» que conecte a vecinos con vacantes de negocios locales", 11, "Insertar a un mínimo de 2,500 vecinos", "Al menos 2 500 vecinos insertados en empleo formal"),
        P("agua_riesgos", "Sistemas de alerta temprana ante sismos, brigadas vecinales de defensa civil y mochilas de emergencia para familias vulnerables", 13, "Implementación de 2 sistemas de alerta temprana", "2 sistemas de alerta, 100 brigadas y 2 000 mochilas de emergencia"),
        P("urbano", "Iluminación pública inteligente y plan de soterramiento progresivo del cableado aéreo", 15, "soterramiento progresivo de todo el cableado"),
        P("ambiente", "Programa «Magdalena recicla» con recojo diferenciado de residuos orgánicos e inorgánicos", 16, "Magdalena recicla"),
        P("gestion", "Firma digital en todos los documentos, mesa de partes virtual y transición del personal a la Ley Servir", 16, "Implementación de la firma digital para todo documento"),
    ]),
    ("Johan Fritz Chávez Sifuentes", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Fortalecer la seguridad ciudadana frente a hurtos y robos", 1, "-40% delitos, 90% cámaras", "40 % menos delitos, 90 % de cámaras operativas y respuesta en menos de 5 minutos"),
        P("social", "Programa UBAP Magdalena y fortalecimiento de la atención al adulto mayor", 1, "10,000 asegurados y 2 Casas del Adulto Mayor", "10 000 asegurados y 2 Casas del Adulto Mayor"),
        P("social", "Programa «Magdalena Emprende Joven» y becas para jóvenes", 1, "120 emprendimientos, 200 becas", "120 emprendimientos, 200 becas y 1 000 beneficiarios"),
        P("economia", "Formalización y competitividad empresarial", 1, "+35% licencias vigentes", "35 % más licencias vigentes"),
        P("economia", "Programa «Compra Magdalena» para digitalizar el comercio local", 1, "600 negocios y 900 comerciantes capacitados", "600 negocios afiliados y 900 comerciantes capacitados"),
        P("economia", "Fortalecer el Mercado de Magdalena y las ferias económicas", 1, "16 ferias económicas anuales", "16 ferias económicas al año"),
        P("ambiente", "Programa integral de limpieza y recuperación del espacio público", 1, "Programa integral de limpieza y recuperación", "100 % de microbasurales eliminados"),
        P("ambiente", "Ampliar las áreas verdes del distrito", 1, "Ampliar áreas verdes", "6 000 m² recuperados"),
        P("agua_riesgos", "Fortalecer el drenaje y la resiliencia urbana ante aniegos", 1, "Fortalecer drenaje y resiliencia urbana", "100 % de puntos críticos intervenidos"),
        P("transporte", "Mejorar la movilidad urbana interviniendo los principales nodos de congestión", 1, "Mejorar movilidad urbana"),
        P("gestion", "Gobierno digital y transparencia, con reportes trimestrales y audiencias públicas de rendición de cuentas", 1, "Gobierno digital y transparencia", "80 % de trámites digitalizados y 95 % de ejecución presupuestal"),
    ]),
    ("Carla Robbiano Montes de Allison", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Casetas de monitoreo descentralizado, botones de emergencia en plazas y parques, y vigilancia con drones en la Costa Verde", 3, "monitoreo con drones en el área de la Costa Verde"),
        P("seguridad", "Cámaras corporales para todo el personal de serenazgo, más motocicletas y capacitación permanente", 3, "cámaras corporales (body cam)"),
        P("urbano", "Culminar la iluminación LED de todas las calles, parques y espacios públicos", 4, "culminación del plan de iluminación LED total"),
        P("urbano", "Rehabilitar pistas y veredas en los jirones Echenique, Rutté, Graña y Libertad, entre otras vías prioritarias", 5, "Jr. Rutté cdras. 1 al 7"),
        P("transporte", "Bus municipal con ruta propia, gratuito o subsidiado, con prioridad para adultos mayores y personas con discapacidad", 5, "servicio de bus municipal con ruta propia"),
        P("ambiente", "Arborización de calles y avenidas con especies nativas y ampliación de áreas verdes en la Costa Verde", 6, "programa de arborización general de calles"),
        P("social", "Servicio de motoambulancia municipal las 24 horas y capacitación en RCP y primeros auxilios en colegios", 7, "servicio de motoambulancia municipal"),
        P("agua_riesgos", "Gestionar una planta potabilizadora de agua y campañas permanentes de prevención ante sismos con simulacros", 7, "planta potabilizadora de agua para el distrito"),
        P("social", "Casa de la Mujer con asesoría legal y psicológica, y sala cuna municipal para familias trabajadoras", 8, "Punto Mujer o Casa de la Mujer"),
        P("economia", "Campaña de formalización de comerciantes con trámites simplificados y ferias municipales periódicas", 9, "campaña de formalización de comerciantes"),
        P("gestion", "Wifi gratuito en plazas, parques y malecones, y canal digital de emergencias integrado al serenazgo", 14, "red de zonas de wifi gratuito"),
    ]),
    ("Jesús Adolfo Quispichuco Taico", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Plan «Magdalena 360°»: vigilancia por sectores con bases de monitoreo descentralizadas y cámaras particulares integradas al sistema municipal", 5, "bases de monitoreo descentralizadas"),
        P("seguridad", "Escuela de Serenos, alarmas vecinales y aplicativo «Alerta Magdalena» como botón de pánico", 5, "ALERTA MAGDALENA"),
        P("urbano", "Plan Urbano distrital para proteger la residencialidad, limitar alturas y peatonalizar algunas vías", 6, "Plan Urbano distrital para proteger la residencialidad"),
        P("transporte", "Cuerpo municipal de inspectores de tránsito para horas punta y semáforos inteligentes", 6, "cuerpo municipal de inspectores de tránsito"),
        P("ambiente", "Programa «Magdalena Recicla» con puntos de reciclaje; lo recaudado irá a la biblioteca infantil y la casa del adulto mayor", 7, "Magdalena Recicla"),
        P("social", "Política «Magdalena 100% Deporte»: convenios para usar campos del Hospital Larco Herrera y el Puericultorio, y gimnasio municipal", 8, "Magdalena 100% Deporte"),
        P("social", "Casa de la Juventud con talleres de arte y oficios, y sala de ensayo y grabación para músicos del distrito", 8, "sala de ensayo y grabación"),
        P("economia", "Capacitación a emprendedores y comerciantes, y expo ferias periódicas dentro y fuera del distrito", 9, "se organizarán periódicamente expo ferias"),
        P("agua_riesgos", "Almacenes municipales de emergencia para atender a los vecinos en desastres", 9, "almacenes de emergencia municipales"),
        P("social", "Guardería municipal en alianza con adultos mayores, comedor municipal y servicio de ambulancia", 10, "Se creará la Guardería Municipal"),
        P("gestion", "Sistema antisoborno ISO 37001, transmisión en vivo de las sesiones de concejo y boletines trimestrales de obras y contrataciones", 10, "Implementación del ISO 37001"),
    ]),
    (None, "Partido Morado", "partido-morado", [
        P("seguridad", "Programa «Magdalena Segura 360°» con cámaras de reconocimiento facial, drones, botón de pánico vecinal y patrullaje integrado", 5, "Reducir en 25% los delitos", "Reducir en 25 % los delitos"),
        P("urbano", "Piscina municipal con clases de natación, recuperación de canchas deportivas y mantenimiento de parques", 6, "Construcción de piscina municipal con clases de natación", "45 % más uso de espacios recreativos y deportivos"),
        P("social", "Programa «Buena Salud para Todos»: atención médica de S/ 5 y S/ 10 y campañas preventivas", 6, "Atención médica popular de S/5 y S/10", "40 % más acceso a servicios médicos municipales"),
        P("social", "Apoyo alimentario a familias de bajos recursos y adultos mayores mediante convenios con empresas", 6, "Convenios con empresas para entrega de víveres", "45 % más cobertura de asistencia alimentaria"),
        P("economia", "Remodelación de los mercados municipales y control de residuos en zonas comerciales", 7, "Modernizar en 100% los mercados municipales", "100 % de mercados modernizados y 60 % menos residuos en zonas comerciales"),
        P("economia", "Bolsa de trabajo «Magdalena Emplea» con ferias laborales y capacitaciones técnicas", 7, "Magdalena Emplea", "35 % más acceso a empleo formal y 30 % más capacitaciones"),
        P("ambiente", "Mapeo de los lugares con más ruido y prevención de ruidos molestos", 8, "Mapeo distrital de los lugares con altos niveles de ruido", "40 % menos denuncias por ruido"),
        P("transporte", "Mantenimiento de semáforos y señales, y promoción de bicicletas y scooters para trayectos cortos", 8, "disminuir en 25% la congestión vehicular", "25 % menos congestión en las vías principales"),
        P("ambiente", "Programa de tenencia responsable de mascotas con señalización y brigadas vecinales", 8, "Reducir en 55% la contaminación", "55 % menos contaminación por heces de mascotas"),
        P("ambiente", "Programa «Magdalena Verde» con reciclaje domiciliario y jornadas vecinales de limpieza", 9, "Incrementar en 50% la participación vecinal en programas ambientales", "50 % más participación vecinal en programas ambientales"),
        P("gestion", "Programa «Municipalidad de Puertas Abiertas»: atención directa del alcalde y reuniones con juntas vecinales", 9, "Reducir en 60% los tiempos de atención municipal", "60 % menos tiempo de atención municipal"),
    ]),
    ("Eduardo Roselló Montero", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Nuevas cámaras con reconocimiento facial y lectura de placas conectadas al centro de control municipal", 8, "Instalar 200 nuevas videocámaras", "200 cámaras instaladas en el primer año"),
        P("seguridad", "Serenazgo en 20 sectores, cada uno con un vehículo, una moto y un efectivo policial", 8, "dividiendo el distrito en 20 sectores", "Respuesta del serenazgo en no más de 5 minutos"),
        P("ambiente", "Recuperar áreas verdes en parques, malecones y bermas con especies nativas y riego eficiente", 9, "Recuperar y ampliar 100,000 m", "100 000 m² de áreas verdes"),
        P("social", "Polideportivo municipal con piscina semiolímpica techada y climatizada, gimnasio y tarifas sociales para vecinos", 13, "Polideportivo Municipal inaugurada antes del 2029", "Inaugurado antes de 2029"),
        P("transporte", "Estacionamiento subterráneo de tres niveles bajo la Plaza Manco Cápac, financiado con obras por impuestos o concesión", 13, "Estacionamiento subterráneo Plaza Manco Cápac con 300 plazas", "300 plazas operativas antes de 2030"),
        P("economia", "Modernización del Mercado Distrital con plan maestro, zona gastronómica, pagos digitales y wifi", 14, "Sistema de pagos digitales y WiFi gratuito", "Pagos digitales y wifi en el 100 % de puestos al 2028"),
        P("social", "Policlínico municipal a costo social con más de 20 especialidades y geriatría", 17, "Policlínico Municipal inaugurado en el primer año", "Inaugurado en el primer año"),
        P("social", "Segunda Casa del Adulto Mayor con horario extendido, fisioterapia a precio social y seguro de salud básico", 17, "2 sedes de Casa del Adulto Mayor operativas al 2028", "2 sedes al 2028 con más de 3 000 beneficiarios al año"),
        P("economia", "Formalización del comercio ambulatorio con zonas autorizadas y capacitación en gestión", 18, "Formalización del 80% del comercio ambulatorio", "80 % del comercio ambulatorio formalizado"),
        P("ambiente", "Programa «Magdalena Recicla y Gana»: ecopuntos inteligentes que pagan créditos por el material reciclado", 22, "20 Ecopuntos Inteligentes instalados al 2027", "20 ecopuntos al 2027"),
        P("gestion", "Gobierno digital con trámites en línea, app «Magdalena Digital» y presupuesto participativo con votación digital", 22, "80% de trámites municipales disponibles en línea al 2028", "80 % de trámites en línea al 2028 y 100 % al 2030"),
    ]),
    ("Richard Johnny Veramendi Oliva", "Pueblo Consciente", "partido-politico-pueblo-consciente", [
        P("seguridad", "Cámaras con inteligencia artificial, reconocimiento facial y lectura de placas en los accesos al distrito, integradas con la PNP", 1, "Instalación de 150 cámaras con", "150 cámaras en todos los accesos al distrito"),
        P("social", "Programa «Magdalena Saludable» con centros del adulto mayor repotenciados y salud móvil", 2, "Magdalena Saludable", "2 CIAM repotenciados y cobertura de salud móvil al 100 %"),
        P("social", "Clínica municipal las 24 horas con atención básica, emergencias y farmacia", 2, "Clínica Municipal 24 Horas"),
        P("economia", "Programa «Tu Negocio Consciente» para formalizar el comercio ambulatorio", 2, "Tu Negocio Consciente", "95 % de comercios ambulatorios formalizados"),
        P("economia", "Rutas gastronómicas señalizadas para posicionar la zona comercial como polo culinario", 2, "rutas gastronómicas señalizadas", "25 % más visitantes de otros distritos"),
        P("urbano", "Complejo polideportivo náutico en la Costa Verde y ciclovía conectada con los distritos colindantes", 2, "Complejo Polideportivo Náutico", "1 complejo náutico y ciclovía conectada al 100 %"),
        P("ambiente", "Segregación de residuos en edificios multifamiliares", 2, "Segregación vertical en edificios", "60 % de edificios multifamiliares reciclando en la fuente"),
        P("ambiente", "Paneles solares en oficinas públicas y alumbrado municipal", 2, "paneles solares en oficinas públicas", "30 % menos gasto energético"),
        P("gestion", "Trámites del TUPA digitales con respuesta por aplicación", 2, "Digitalización del 100% de los procedimientos", "100 % de procedimientos del TUPA digitalizados"),
        P("gestion", "Presupuestos participativos transmitidos en vivo y rendición de cuentas trimestral", 2, "4 presupuestos participativos anuales", "4 presupuestos participativos al año"),
        P("agua_riesgos", "Drones de apoyo en incendios y emergencias, y brigadas de respuesta rápida", 3, "Uso de drones para apoyo en incendios"),
    ]),
    ("Raúl Madueño Ortiz", "PPC", "partido-popular-cristiano-ppc", [
        P("social", "Ampliar la oferta cultural, educativa y de formación para niños, jóvenes y adultos", 1, "40 programas anuales al 2030", "40 programas anuales al 2030"),
        P("social", "Ampliar los programas de salud preventiva y atención comunitaria", 1, "20,000 atenciones acumuladas al 2030", "20 000 atenciones acumuladas al 2030"),
        P("social", "Promover la actividad física con infraestructura y programas deportivos inclusivos", 1, "Incrementar en 50% la participación vecinal al 2030", "50 % más participación vecinal al 2030"),
        P("economia", "Modernizar los procedimientos municipales para facilitar la inversión y el emprendimiento", 1, "Licencias emitidas en máximo 24 horas", "Licencias en un máximo de 24 horas"),
        P("economia", "Capacitación, asesoría y empleo local para emprendedores y empresarios", 1, "3,000 beneficiarios al 2030", "3 000 beneficiarios al 2030"),
        P("economia", "Posicionar a Magdalena como destino turístico, gastronómico y comercial", 1, "Posicionar a Magdalena como un destino turístico", "30 eventos turísticos anuales al 2030"),
        P("urbano", "Renovación urbana y recuperación de espacios públicos", 1, "Recuperar 50,000 m", "50 000 m² recuperados al 2030"),
        P("transporte", "Señalización y semaforización inteligente en las principales intersecciones", 1, "80% de intersecciones principales modernizadas", "80 % de intersecciones principales modernizadas"),
        P("ambiente", "Fortalecer la gestión ambiental y ampliar las áreas verdes", 1, "Incrementar 25% las áreas verdes", "25 % más áreas verdes al 2030"),
        P("gestion", "Gobierno digital eficiente y accesible para los vecinos", 1, "100% de trámites digitales al 2030", "100 % de trámites digitales al 2030"),
        P("gestion", "Procesos participativos y rendición pública de cuentas semestral", 1, "8 procesos participativos anuales", "8 procesos participativos y 2 rendiciones de cuentas al año"),
    ]),
    ("José Rafael Haro Zolezzi", "Podemos Perú", "podemos-peru", [
        P("social", "Unidad de urgencias de la Clínica Municipal con ambulancias y atención continua", 2, "del servicio de urgencias y ambulancia de la Clínica Municipal", "Urgencias y ambulancia disponibles 24/7"),
        P("social", "Centro Geriátrico Municipal integrado a la red de centros del adulto mayor", 2, "01 Centro Geriátrico Municipal construido", "1 Centro Geriátrico construido"),
        P("social", "Casa de la Juventud para coworking, innovación, cultura y empleabilidad", 3, "01 Casa de la Juventud construida", "1 Casa de la Juventud operativa"),
        P("social", "Piscina semiolímpica techada y climatizada en el Estadio Aldo Chamochumbi, con programas de hidroterapia", 3, "100% de ejecución del complejo acuático", "Complejo acuático ejecutado al 100 %"),
        P("seguridad", "Patrullaje integrado, analítica de video y serenazgo con enfoque de policía comunitaria («Sereno Amigo»)", 4, "Reducción del 10% del índice de victimización", "10 % menos victimización"),
        P("urbano", "Alumbrado público con tecnología LED y telegestión en avenidas y zonas vulnerables", 4, "100% del alumbrado público migrado", "100 % del alumbrado migrado a LED"),
        P("transporte", "Semáforos peatonales con pulsador en entornos escolares", 5, "100% de entornos escolares priorizados", "100 % de entornos escolares priorizados equipados"),
        P("transporte", "Complejo de estacionamientos subterráneos en el Parque Túpac Amaru", 1, "estacionamientos subterráneos en el Parque Túpac Amaru"),
        P("gestion", "Trámites del TUPA en línea y aplicación municipal para reportar incidencias urbanas", 5, "100% de trámites TUPA digitalizados", "100 % de trámites del TUPA en línea"),
        P("economia", "Plan de Formalización Progresiva del comercio con incentivos, simplificación y capacitación", 6, "Plan de Formalización Progresiva", "Comercio regulado y asistido al 100 %"),
        P("ambiente", "Islas de contenedores soterrados y parques con iluminación ecoeficiente", 7, "islas de contenedores de residuos soterrados"),
    ]),
    ("Víctor Raúl Paulini Sánchez", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Aplicativo «SOS Magdalena» para denunciar delitos, de uso exclusivo para vecinos del distrito", 7, "S.O.S MAGDALENA"),
        P("seguridad", "Reactivar el módulo tripartito de Echenique con Amazonas y nuevos módulos de seguridad en Gonzales Prada, Leoncio Prado, Sucre y la urb. Jacaranda", 7, "MODULO EN GONZALES PRADA CON JR. DANIEL HERNANDEZ"),
        P("transporte", "Subgerencia de tránsito, depósito y grúa municipal en convenio con la PNP, y control del estacionamiento indebido", 11, "IMPLEMENTACION DE DEPOSITO Y GRUA MUNICIPAL"),
        P("agua_riesgos", "Gestionar la recuperación de la compañía de bomberos del distrito, puntos de encuentro y simulacros de evacuación", 12, "COMPAÑÍA DE BOMBEROS MAGDALENA 36"),
        P("social", "Modernizar la clínica y la ambulancia municipal, y programa de médico a domicilio para adultos mayores", 14, "PROGRAMA MEDICO A DOMICILIO"),
        P("social", "Complejo deportivo municipal en la Costa Verde con canchas de fútbol, vóley, básquet, tenis, frontón y pádel", 14, "CONSTRUIR CANCHAS DE PADEL"),
        P("transporte", "Estacionamiento subterráneo en la Plaza Túpac Amaru por concesión, con horarios gratuitos para vecinos", 18, "ESTACIONAMIENTO SUBTERRANEO EN PLAZA TUPAC AMARU"),
        P("economia", "Zona de restaurantes en la Costa Verde solo para restaurantes del distrito, mediante concesión", 18, "ZONA DE RESTAURANTES TIPO BORDEMAR"),
        P("ambiente", "Parque con laguna artificial en la Costa Verde, más áreas verdes en Magdalena Antigua y contenedores subterráneos", 20, "MEGA PARQUE CON LAGUNA ARTIFICAL"),
        P("social", "Comedor popular municipal y cuna jardín municipal", 22, "CREACION DEL COMEDOR POPULAR MUNICIPAL"),
        P("gestion", "Certificación antisoborno y de calidad, sistema de denuncia contra malos funcionarios e información abierta sobre contrataciones", 23, "APLICAR A ISO ANTI CORRUPCION"),
    ]),
]
