"""San Juan de Miraflores (150133): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150133"

# Planes que no se resumen, con la razón que se muestra junto a la candidatura
NOTAS = {
    "fuerza-popular": "El plan inscrito ante el JNE (3 páginas) solo contiene el ideario y la visión de la organización: no presenta propuestas que resumir. Puedes revisarlo en Voto Informado del JNE.",
}

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Alex Fabio Trujillo Uscamayta", "Acción Popular", "accion-popular", [
        P("seguridad", "«Domo Seguridad SJM»: red de cámaras inteligentes en las seis zonas, lectura de placas e inteligencia artificial, con un Centro Integrado de Monitoreo las 24 horas", 55, "1000 cámaras inteligentes distribuidas estratégicamente", "1000 cámaras inteligentes operativas al 2030"),
        P("seguridad", "Ampliar el serenazgo, incorporar drones de vigilancia y bodycams, y sectorizar el patrullaje para acortar el tiempo de respuesta a emergencias", 59, "150 serenos operativos debidamente equipados", "150 serenos, 50 drones y respuesta entre 5 y 8 minutos al 2030"),
        P("transporte", "Teleférico San Juan con estaciones en Rinconada, Pamplona Alta, Pamplona Baja, Mercado Ciudad de Dios y Atocongo, conectado al Metro de Lima", 61, "Teleférico San Juan será un sistema de transporte por cable", "Primera fase de ejecución iniciada al 2030"),
        P("transporte", "Programa Ciclovías SJM con corredores para bicicletas y paraderos inteligentes con información digital, iluminación y accesibilidad", 63, "Programa Ciclovías SJM"),
        P("urbano", "Corredor Miotta: renovación de la Av. Pedro Miotta con veredas, mobiliario, iluminación, arborización y espacios para ferias", 62, "La Avenida Pedro Miotta se convertirá en un eje estratégico"),
        P("urbano", "Programa Ciudad Bella: recuperación de escaleras en zonas de ladera, miradores, fachadas y murales, con prioridad en Pamplona Alta, Pamplona Baja y Pampas", 67, "escaleras seguras en zonas de ladera"),
        P("ambiente", "Contenedores soterrados inteligentes para la recolección de residuos y corredores verdes con arborización y jardines", 68, "Contenedores Soterrados Inteligentes Implementación progresiva"),
        P("social", "Red de Parques Biblioteca en Rinconada, Pampas de San Juan y Pedro Miotta, con laboratorios tecnológicos y formación en inteligencia artificial y programación", 73, "construcción de 3 Parques Biblioteca", "3 Parques Biblioteca al 2030"),
        P("economia", "«Mercado Ciudad de Dios 2030»: modernizar el mercado con boulevard gastronómico, plaza cultural y ventas en línea, bajo la marca «Ciudad de Dios Sabores del Perú»", 74, "Transformar el Mercado Ciudad de Dios en un referente gastronómico"),
        P("economia", "Centro de Convenciones Lima Sur para congresos, ferias comerciales, eventos empresariales y actividades culturales", 63, "CENTRO DE CONVENCIONES LIMA SUR Objetivo Crear un espacio"),
        P("gestion", "Portal de obras e inversiones con cronogramas y avances, indicadores de desempeño por gerencia y financiamiento por Obras por Impuestos", 83, "Revisión trimestral de metas y resultados"),
    ]),
    ("Olis Yaranga Jacinto", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Usar inteligencia artificial para interconectar las cámaras de videovigilancia municipales y privadas, con cuadrantes monitoreados las 24 horas", 7, "municipalidad y privadas 2. tener cuadrantes de acción", "Cero atentados en 2030"),
        P("seguridad", "Dotar al serenazgo de indumentaria, vehículos y armas no letales, e instalar cámaras con reconocimiento facial", 7, "armas no letales al cuerpo de serenazgo"),
        P("social", "Construir un policlínico materno infantil y un policlínico pediátrico", 7, "Construcción de policlínico materno infantil y policlínico pediátrico"),
        P("social", "Fondos de estímulo y becas para los mejores alumnos de las instituciones educativas públicas", 7, "Creación de fondos de estimulo para los mejores alumnos"),
        P("social", "Recuperar canchas deportivas en todas las zonas y promover el programa «Domingos de familia y el deporte»", 8, "domingos de familia y el deporte"),
        P("urbano", "Promover el saneamiento físico legal de los pueblos de la Nueva Rinconada", 8, "Promover el saneamiento físico legal de los pueblos de la nueva rinconada"),
        P("transporte", "Instalar semáforos inteligentes y ordenar y señalizar los paraderos principales", 10, "Instalación de semáforos inteligentes"),
        P("economia", "Centro de Capacitación al Empresario de SJM, ferias laborales con gremios empresariales y ruedas de negocios", 9, "Creación del Centro de Capacitación al Empresario de SJM"),
        P("ambiente", "Arborización en Pamplona y Pampas de San Juan, incentivos a vecinos que reciclen y multas por incumplir el horario de recojo de residuos", 10, "Arborización integral en las zonas de pamplona y pampas de san juan"),
        P("gestion", "Módulos de atención descentralizada en alianza con mercados y una sede municipal en la zona Margen Derecha", 10, "Construcción de una sede en la zona Margen derecha", "Módulos de atención en los primeros 100 días"),
        P("gestion", "Descentralizar el pago del impuesto predial, permitir el pago por aplicativo y premiar al buen pagador con un seguro hospitalario", 11, "creación del seguro hospitalario en las clínicas del distrito"),
    ]),
    ("Luis Dante Mendieta Flores", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Ampliar la videovigilancia con nuevas cámaras HD conectadas al Centro de Monitoreo Municipal y cuadrantes cerrados en sectores críticos", 33, "incorporando al menos 120 nuevas cámaras HD", "Al menos 120 nuevas cámaras HD (300 % más capacidad) al 2030"),
        P("seguridad", "Convenio con la PNP para patrullaje conjunto con policías de franco en los cuadrantes del distrito y cinco sub bases de serenazgo", 34, "mínimo 30 policías en situación de franco", "30 policías en 20 cuadrantes antes de junio 2027; 5 sub bases antes de diciembre 2027"),
        P("social", "Construir la Casa del Adulto Mayor con salud preventiva, recreación, talleres y alimentación", 34, "Construir e implementar la Casa del Adulto Mayor", "Atención a al menos 100 personas diarias antes del 2028"),
        P("agua_riesgos", "Gestionar ante el Gobierno Central y el Congreso agua, desagüe y electrificación para las viviendas de la Rinconada y asentamientos sin servicios", 35, "al 100% de las viviendas de la Rinconada", "100 % de las viviendas sin servicios al 2030"),
        P("urbano", "Gestionar y ejecutar proyectos de mejoramiento vial e infraestructura urbana en las seis zonas, con vías priorizadas por zona", 35, "Gestionar y ejecutar 600 millones de soles", "S/ 600 millones con 100 % de ejecución al 2030"),
        P("agua_riesgos", "Construir muros de contención y escaleras de evacuación en zonas de alto riesgo de Pamplona Alta, La Rinconada y Pampas de San Juan", 38, "muros de contención y escaleras de evacuación", "100 % de las zonas de alto riesgo priorizadas al 2030"),
        P("social", "Construir la primera piscina municipal temperada en el Parque Reducto y el Complejo Deportivo «La Videnita»", 39, "primera piscina municipal temperada"),
        P("transporte", "Semáforos inteligentes de control adaptativo en Av. Los Héroes, Vargas Machuca, Pista Nueva y Av. San Juan", 40, "30 semáforos inteligentes con tecnología de control adaptativo", "30 semáforos y 30 % menos congestión en esas vías al 2030"),
        P("ambiente", "Reforestar zonas estratégicas del distrito en coordinación con el SERNANP y el MINAM", 40, "sembrar un mínimo de 10,000 árboles", "10 000 árboles con 70 % de supervivencia al 2030"),
        P("economia", "Reubicar a los comerciantes ambulantes en nuevas zonas comerciales habilitadas, con acompañamiento financiero y capacitación", 44, "Reubicar al 100% de los comerciantes ambulantes", "100 % de los ambulantes identificados reubicados al 2030"),
        P("gestion", "Programa «Asistente Municipal» con puntos de atención descentralizada en los sectores más alejados para orientación y trámites", 47, "con al menos 5 puntos de atención descentralizada", "5 puntos con al menos 500 vecinos atendidos por mes desde 2027"),
    ]),
    (None, "Alianza Regional por el Perú", "alianza-regional-por-el-peru", [
        P("seguridad", "Política integral de seguridad ciudadana con prevención del delito, patrullaje integrado de serenazgo y recuperación de espacios públicos", 2, "política integral de seguridad ciudadana, prevención del delito"),
        P("social", "Mejorar el acceso a salud y educación con atención preventiva y reducción de brechas educativas", 2, "promoviendo la atención preventiva, la reducción de brechas educativas"),
        P("social", "Crear y recuperar espacios recreativos, deportivos y culturales para la integración comunitaria", 3, "creación y recuperación de espacios recreativos, deportivos y culturales"),
        P("economia", "Formalización de negocios, ferias comerciales, programas de empleabilidad juvenil y alianzas con el sector privado", 3, "programas de empleabilidad juvenil y alianzas con el sector privado"),
        P("urbano", "Ordenar el desarrollo urbano mediante planificación territorial y recuperación de espacios públicos", 4, "Ordenar el desarrollo urbano del distrito mediante planificación territorial eficiente"),
        P("ambiente", "Ampliar las áreas verdes, mejorar la gestión de residuos sólidos y promover el reciclaje", 4, "ampliación de áreas verdes y fortalecimiento de la gestión ambiental"),
        P("gestion", "Digitalizar procesos y simplificar trámites municipales", 5, "digitalización de procesos, simplificación administrativa"),
        P("gestion", "Audiencias públicas semestrales de rendición de cuentas y comités de vigilancia vecinal para supervisar las obras", 5, "audiencias públicas semestrales"),
    ]),
    ("Jessica Loren Alcántara Silva", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("social", "Programa contra la anemia con «Ollas de Hierro Saludable» en comedores de las 7 zonas, nuevos módulos Cuna Más y módulo móvil de salud en ladera", 15, "módulo móvil cubriendo las zonas de ladera", "Anemia infantil de 18.3 % a menos de 13 % al 2030"),
        P("seguridad", "Plan de Seguridad por Cuadrantes en las 7 zonas y programa «San Juan te Observa» con cámaras e iluminación en puntos críticos de ladera", 16, "Plan de Seguridad por Cuadrantes en las 7 zonas"),
        P("seguridad", "Escuela de Formación de Serenos en extorsión y crimen organizado, y canal «Vigila San Juan» de denuncia anónima por WhatsApp y aplicativo", 17, "Crear la Escuela de Formación de Serenos", "25 % menos denuncias por los delitos de mayor incidencia al 2030"),
        P("urbano", "Orientación itinerante para titulación de predios en asentamientos humanos y asesoría técnica gratuita mensual en construcción segura («San Juan construye»)", 17, "espacios mensuales de asesoría técnica gratuita", "30 % más familias con titulación y mejora de vivienda al 2030"),
        P("ambiente", "Segregación en la fuente en las 7 zonas, formalización de recicladores y planta piloto de compostaje con residuos de mercados", 19, "Formalizar y organizar a los recicladores del distrito", "Valorización de 67.4 % a 85 % y 70 % de puntos críticos eliminados al 2030"),
        P("ambiente", "Vivero municipal, parques de bolsillo en espacios degradados de ladera y programa «Adopta un Parque» con juntas vecinales", 20, "Implementar parques de bolsillo en espacios públicos degradados", "Áreas verdes de 1.4 m²/hab. a 2.5 m²/hab. al 2030"),
        P("ambiente", "Plan de Gestión Local de la Loma Costera de Pamplona por ordenanza y circuito ecoturístico con guías vecinales", 20, "Plan de Gestión Local de la Loma Costera de Pamplona"),
        P("agua_riesgos", "Brigadas vecinales «Barrio Resiliente» y obras de muros de contención, escaleras de evacuación y drenajes pluviales en laderas de mayor riesgo", 21, "muros de contención, escaleras de evacuación y drenajes pluviales"),
        P("economia", "Licencia sin costo el primer año para negocios de supervivencia que se formalicen y capacitación a ambulantes, recicladores y mototaxistas", 22, "por el primer año para aquellos negocios de supervivencia", "Más de 100 negocios formalizados"),
        P("economia", "Estrategia Emprende Mujer: convertir ollas comunes y comedores en cooperativas de confección o panificación, con fondos concursables", 23, "cooperativas de confección textil y/o panificación", "5,000 mujeres emprendedoras con capital semilla y asistencia técnica"),
        P("gestion", "Auditoría de la deuda laboral y coactiva y cumplimiento trimestral del Compromiso de Ajuste Fiscal ante el MEF", 24, "Reducir el saldo de la Deuda Fiscal en un 90%", "Reducir la deuda fiscal en 90 % del valor actual"),
    ]),
    ("Anatoly Renán Bedriñana Córdova", "Fuerza Popular", "fuerza-popular", []),
    (None, "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Sistema de videovigilancia y monitoreo distrital conectado a los puntos críticos de cada sector, y modernización de la Central de Seguridad", 5, "Implementar progresivamente un sistema moderno de video vigilancia"),
        P("seguridad", "Plan Distrital «SJM Seguro y Unido» que articule serenazgo, PNP y juntas vecinales, con patrullaje preventivo en zonas de mayor incidencia", 8, "articulando serenazgo, Policía Nacional, juntas vecinales"),
        P("social", "Programa de prevención social del delito para adolescentes y jóvenes mediante deporte, cultura y formación ciudadana", 8, "prevención social del delito dirigido a adolescentes y jóvenes"),
        P("urbano", "Programa «Mi Barrio Digno» para mejorar pistas, veredas, escaleras, muros de contención y espacios comunales", 9, "para mejoramiento de pistas, veredas, escaleras, muros de contención"),
        P("ambiente", "Erradicar puntos críticos de basura y desmonte, y educación ambiental y reciclaje con colegios y organizaciones vecinales", 9, "erradicación de puntos críticos de basura y desmontes"),
        P("ambiente", "Defender el sistema de lomas del distrito con acciones de conservación de flora y fauna", 6, "Defensa del sistema de lomas del distrito"),
        P("economia", "Centro Municipal del Emprendedor SJM para orientar a pequeños negocios y ferias laborales bimestrales con capacitación", 6, "ferias laborales de manera bimestral"),
        P("social", "Red Distrital de Juventudes, Escuela Municipal de Liderazgo Juvenil y escuelas deportivas municipales gratuitas", 12, "Escuela Municipal de Liderazgo Juvenil"),
        P("social", "Acompañamiento a familias vulnerables, espacios comunitarios para adultos mayores y prevención de la violencia familiar", 11, "acompañamiento a familias en situación vulnerable"),
        P("gestion", "Programa «Municipalidad en tu Barrio» de atención descentralizada y sistema público de seguimiento de obras e inversiones", 13, "de seguimiento de obras e inversiones municipales"),
    ]),
    ("Jaime Javier Frías Reymundo", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Central inteligente de videovigilancia con cámaras con inteligencia artificial, serenazgo georreferenciado, botones de pánico vecinal y mapa digital del delito", 11, "Botones de pánico vecinal"),
        P("urbano", "Plan de recuperación del espacio público: reordenar el comercio ambulatorio y liberar veredas y calles ocupadas por talleres y cocheras informales", 10, "Recuperación de calles tomadas por talleres y cocheras informales"),
        P("urbano", "Modernizar el eje comercial de Av. San Juan y Av. Los Héroes con paso subterráneo, estacionamientos bajo suelo y pase peatonal adoquinado", 17, "By pass Av San Juan por subterraneo"),
        P("transporte", "Semaforización inteligente, modernización de paraderos y estudios de movilidad vertical en Pamplona Alta y zonas de ladera", 15, "Estudios para movilidad vertical moderna en Pamplona Alta"),
        P("social", "Construir el primer Centro Integral de Autismo y Discapacidad del distrito, con atención psicológica y terapéutica", 12, "Construcción del primer Centro Integral de Autismo y Discapacidad"),
        P("social", "Programa «Tren del Saber» y centros tecnológicos comunitarios con formación en computación, robótica e inteligencia artificial", 13, "Formación en computación, robótica e inteligencia artificial"),
        P("economia", "Centro Municipal de Servicios Empresariales, bolsa laboral distrital y capacitación en marketing digital", 16, "Creación del Centro Municipal de Servicios Empresariales"),
        P("agua_riesgos", "Muros de contención, drenaje pluvial, sistema de alertas tempranas, simulacros descentralizados y brigadas vecinales de emergencia", 22, "Sistema de alertas tempranas"),
        P("ambiente", "Riego tecnificado y con aguas grises en parques, arborización y planta de valorización de residuos sólidos", 25, "Uso de aguas grises para riego"),
        P("ambiente", "Centro Municipal Veterinario con albergue temporal, adopción responsable y esterilización gratuita", 28, "Creación del Centro Municipal Veterinario"),
        P("gestion", "Portal de obras en tiempo real, transmisión en vivo de las sesiones de concejo y supervisión vecinal de obras", 19, "Emisión en vivo de sesiones de concejo"),
    ]),
    ("Ricardo Rodrigo Salvatierra Paucar", "Partido del Buen Gobierno", "partido-del-buen-gobierno", [
        P("agua_riesgos", "Acceso universal a agua potable, alcantarillado y energía eléctrica, priorizando las zonas más vulnerables", 15, "Alcanzar una cobertura superior al 98% en servicios", "Cobertura superior al 98 % en servicios básicos al 2030"),
        P("social", "Construir centros materno-infantiles y programas para prevenir y erradicar la tuberculosis", 13, "la construcción de centros materno-infantiles"),
        P("social", "Ampliar el acceso a internet para estudiantes y fomentar la lectura desde los tres años", 13, "fomentando hábitos de lectura desde la primera infancia"),
        P("seguridad", "Trabajo articulado de municipalidad, serenazgo y PNP con cámaras inteligentes de videovigilancia y más iluminación pública", 15, "complementado con cámaras inteligentes de videovigilancia"),
        P("economia", "Priorizar a empresas del distrito en las obras públicas y crear una oficina de orientación para la inversión pública y privada", 14, "priorización de empresas del distrito en la ejecución de obras públicas"),
        P("economia", "Formalizar negocios simplificando trámites, licencias y permisos municipales, con acompañamiento técnico", 16, "Reducir la informalidad laboral del 84% al 60%", "Informalidad de 84 % a 60 % y 50 % más negocios formalizados al 2030"),
        P("economia", "Consolidar corredores comerciales en Panamericana Sur, San Juan, Pachacútec, Los Héroes y Pista Nueva", 17, "Consolidar corredores comerciales competitivos en las avenidas"),
        P("ambiente", "Incrementar progresivamente las áreas verdes urbanas por habitante", 14, "entre 1.5 y 3 metros cuadrados por habitante", "Entre 1.5 y 3 m² de área verde por habitante"),
        P("ambiente", "Centros de acopio en cada sector del distrito y promoción del reciclaje", 14, "centros de acopio en cada sector del distrito", "Recuperación de residuos de hasta el 50 %"),
        P("transporte", "Ordenar el tránsito, mejorar la señalización en vías principales y realizar campañas de educación vial", 20, "Reducir en 40% los accidentes de tránsito", "40 % menos accidentes de tránsito al 2030"),
        P("gestion", "Digitalizar los trámites y servicios para contribuyentes y realizar cabildos abiertos", 15, "al menos el 70 % de los trámites"),
    ]),
    ("Eloy Chávez Hernández", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Central integrada de videovigilancia y respuesta rápida con cámaras, analítica de video con inteligencia artificial y reconocimiento de placas", 51, "Implementar hasta 1,000 cámaras de videovigilancia integradas", "Hasta 1,000 cámaras; percepción de inseguridad de 92.8 % a 80 % o menos al 2030"),
        P("seguridad", "Planes de seguridad en Mall del Sur, Open Plaza Atocongo y mercados, y rutas seguras para escolares, mujeres y adultos mayores", 52, "como Mall del Sur, Open Plaza Atocongo, Mercado Ciudad de Dios"),
        P("social", "Academias municipales de reforzamiento escolar y preparación preuniversitaria, y bibliotecas comunales con internet", 52, "academias municipales de reforzamiento escolar y preparación preuniversitaria"),
        P("social", "Construir el Palacio de la Juventud con un Centro Cultural Municipal con salas para talleres, exposiciones y biblioteca", 53, "Construcción del Palacio de la Juventud"),
        P("social", "Ferias de salud itinerantes en las seis zonas con DIRIS Lima Sur y el Hospital María Auxiliadora, y campañas contra tuberculosis, anemia y dengue", 55, "ferias de salud itinerantes en las seis zonas del distrito"),
        P("economia", "Programa «Emprende San Juan» y ventanilla municipal de formalización para simplificar licencias e ITSE", 56, "Crear una ventanilla municipal de formalización empresarial"),
        P("economia", "Empadronar a los ambulantes, definir zonas autorizadas y restringidas, y reubicarlos en ferias y espacios comerciales regulados", 57, "Definir zonas autorizadas, restringidas y rígidas para comercio ambulatorio"),
        P("ambiente", "Adquirir camiones compactadores, monitorear las rutas de recolección por GPS y crear rutas con unidades menores en zonas de ladera", 58, "Adquisición de 20 camiones compactadores", "20 camiones compactadores"),
        P("ambiente", "Mantenimiento permanente de los 236 parques, riego tecnificado y arborización urbana", 59, "sembrando 1000 árboles en parques", "1000 árboles sembrados"),
        P("agua_riesgos", "Sistema de alerta temprana ante sismos articulado al COEL, con sirenas y perifoneo, y rutas de evacuación señalizadas", 60, "sistema distrital de alerta temprana y comunicación ante sismos"),
        P("gestion", "Cabildos vecinales descentralizados y plataforma digital de reporte ciudadano sobre limpieza, seguridad, alumbrado y comercio informal", 61, "Crear una plataforma digital de reporte ciudadano"),
    ]),
    ("Edgar Wuillington Mejía Rodríguez", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Programa «Calles Seguras 24/7»: mapa del delito y de puntos críticos de las 7 zonas para definir cuadrantes y horarios del patrullaje integrado con la PNP", 10, "Mapa del Delito, Riesgo y Puntos Críticos de las 7 zonas"),
        P("seguridad", "Corredores seguros en rutas escolares, mercados, paraderos y vías de alta circulación, con patrullaje, iluminación y señalización", 11, "Se implementarán corredores seguros en rutas escolares"),
        P("social", "Programa «Jóvenes con Futuro»: Ruta Joven SJM de orientación vocacional, ferias de oportunidades y bolsa joven de empleo y prácticas", 12, "Ruta Joven SJM: orientación vocacional y proyecto de vida"),
        P("social", "Programa «SJM Cuida»: mapa social de las 7 zonas y ventanilla social para derivar a las familias a servicios municipales y programas del Estado", 14, "Ventanilla Social SJM Cuida"),
        P("economia", "Programa «Mercados Competitivos y Saludables»: diagnóstico de mercados, campañas de salubridad y fiscalización orientadora", 22, "Diagnóstico de mercados y centros de abasto"),
        P("economia", "Escuela Mujer Emprende SJM con talleres de gestión de negocios, educación financiera y ventas digitales, y ferias de mujeres emprendedoras por zonas", 24, "Escuela Mujer Emprende SJM"),
        P("urbano", "Programa «Barrios Dignos»: mapa de brechas urbanas y banco de obras barriales priorizadas en cada una de las 7 zonas", 29, "Banco de obras barriales priorizadas"),
        P("agua_riesgos", "Programa «Laderas Seguras»: mapa de riesgos por zonas y brigadas comunitarias de emergencia en Nueva Rinconada, Pamplona Alta y Pampas de San Juan", 32, "Brigadas comunitarias de emergencia"),
        P("ambiente", "Programa «Recicla San Juan»: rutas selectivas de reciclaje con recicladores formalizados y puntos de acopio en mercados, colegios y parques", 34, "Rutas selectivas de reciclaje"),
        P("transporte", "Fiscalización y ordenamiento del transporte menor, control de paraderos informales y coordinación con la MML y la ATU", 36, "Fiscalización del transporte menor"),
        P("gestion", "«Tablero SJM Cumple»: tablero digital público con el avance de cada propuesta, obra y compromiso por zona", 42, "Tablero digital del plan de gobierno"),
    ]),
    ("Alan Freddy Mendoza Ramos", "Partido Morado", "partido-morado", [
        P("seguridad", "Convenio de cooperación con Corea o China para ampliar la red a 420 cámaras con reconocimiento facial y un Centro de Monitoreo Inteligente 24/7", 5, "hasta alcanzar a las 420 cámaras de videovigilancia", "420 cámaras de videovigilancia"),
        P("seguridad", "Botón de pánico digital en una app conectada al centro de monitoreo y alumbrado LED en las zonas con más delitos", 6, "botón de pánico digital (App móvil)", "Bajar la tasa de homicidios en un 30%"),
        P("social", "Ventanilla única de oportunidades para becas del Estado, empleo temporal con «Llamkasun Perú» y bolsa de trabajo municipal para jóvenes", 6, "Ventanilla única de oportunidades municipal", "1000 oportunidades de inserción laboral para jóvenes"),
        P("social", "Agentes comunitarios de salud con visitas domiciliarias y seguimiento con la DIRIS Lima Sur para que los niños con anemia completen su suplementación", 7, "Contratar y capacitar ACS para visitas domiciliarias", "Bajar la anemia en menores de 3 años del 38% al 20% al 2030"),
        P("social", "Programa de bienestar animal «Mi mejor amigo»: registro de albergues, módulo de adopción en línea y campañas de esterilización y vacunación", 8, "realizará un censo y registro oficial de todos los albergues", "Al menos 200 adopciones responsables por año desde el segundo año"),
        P("transporte", "Convenios con la ATU para operativos en puntos críticos, reordenamiento de rutas y mejora de paraderos y señalización", 9, "Coordinar con la ATU un plan de reordenamiento de rutas", "Informalidad vehicular del 92% al 70% al 2030 y 30% menos accidentes en zonas críticas"),
        P("economia", "Actualizar el padrón de comerciantes ambulatorios, otorgar autorizaciones temporales y recuperar espacios públicos con mobiliario urbano", 10, "recuperación de espacio público en 10 puntos críticos", "Formalizar al 50% de los comerciantes ambulatorios censados y recuperar 10 puntos críticos al 2030"),
        P("ambiente", "Centro de Acopio Municipal y recolección selectiva con recicladores; después, línea para convertir plástico en pellets", 11, "Centro de Acopio Municipal", "Reciclar el 25% de los residuos sólidos municipales al 2030"),
        P("ambiente", "Parques ecológicos en Pamplona Baja, UPIS Villa Solidaridad y Javier Heraud, y protección de las Lomas de Pamplona con accesos y miradores", 12, "Parques Ecológicos en Pamplona Baja", "Áreas verdes de 2.3 m² a 5.0 m² por habitante"),
        P("agua_riesgos", "Mesa de trabajo con SEDAPAL y padrón de viviendas para acelerar las conexiones de agua y desagüe en los asentamientos humanos", 12, "Conformar una mesa de trabajo con SEDAPAL", "Conexiones domiciliarias para 2,500 nuevas viviendas en AA.HH. y zonas periféricas"),
        P("gestion", "Portal web y app con pagos en línea, avance de obras y presupuesto en tiempo real y datos abiertos", 13, "Desarrollar portal web y app con módulos de transparencia", "Portal operativo en el primer año; índice de transparencia superior al 80% al 2030"),
    ]),
    ("Christian Marco Gutiérrez Guzmán", "Partido Patriótico del Perú", "partido-patriotico-del-peru", [
        P("seguridad", "Ampliar el patrullaje preventivo del serenazgo en avenidas, parques, mercados, colegios y zonas comerciales", 21, "ampliación progresiva del patrullaje preventivo en avenidas"),
        P("seguridad", "Modernizar el sistema de videovigilancia distrital recuperando y reforzando las cámaras de seguridad", 21, "modernización progresiva del sistema de videovigilancia distrital"),
        P("urbano", "Programas permanentes de mantenimiento de pistas, veredas, parques y bermas en los sectores más deteriorados", 21, "mantenimiento y recuperación progresiva de pistas, veredas, parques, bermas"),
        P("urbano", "Fiscalización permanente de la ocupación indebida de espacios públicos y del comercio informal desordenado", 22, "ocupación indebida de espacios públicos, comercio informal desordenado"),
        P("ambiente", "Reforzar la recolección de residuos en sectores con acumulación de basura y hacer campañas de educación ambiental", 23, "mecanismos de recolección de residuos sólidos"),
        P("social", "Actividades deportivas, culturales y recreativas para fortalecer la integración vecinal de niños, jóvenes, adultos mayores y familias", 23, "actividades deportivas, culturales, recreativas y comunitarias"),
        P("gestion", "Simplificación administrativa y herramientas digitales para reducir los tiempos de atención al vecino", 24, "simplificación administrativa, fortalecimiento tecnológico"),
        P("transporte", "Mantenimiento de vías urbanas, señalización y recuperación de espacios para el tránsito peatonal", 25, "fortalecimiento de señalización territorial"),
        P("economia", "Programa de desarrollo económico local con organización comercial y formalización progresiva, en coordinación con comerciantes y emprendedores", 25, "Programa de Desarrollo Económico Local y Fortalecimiento del Emprendimiento Distrital"),
        P("social", "Coordinación comunitaria para prevenir la violencia juvenil y el consumo de drogas", 27, "prevenir violencia juvenil, consumo de drogas"),
        P("social", "Actividades recreativas y comunitarias para adultos mayores y familias vulnerables", 27, "fortalecer protección y atención progresiva de adultos mayores"),
    ]),
    ("Michel Melchor Sanabria Ruiz", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "200 cámaras adicionales en los puntos críticos identificados con la PNP y exigir una cámara de seguridad para formalizar un comercio", 8, "Implementar 200 cámaras de videovigilancia adicionales", "200 cámaras adicionales"),
        P("seguridad", "Centro de Emergencias Municipal (CEM-SJM) con línea 24/7 articulada con bomberos, PNP y SAMU, y alumbrado LED en calles sin iluminación", 8, "Centro de Emergencias Municipal (CEM-SJM)", "Alumbrado LED en el 100% de las calles sin iluminación"),
        P("social", "Brigadas médicas domiciliarias y Clínica Móvil para adultos mayores fundadores, medicamentos a domicilio y un Policlínico Municipal", 10, "Brigadas Médicas de Atención Domiciliaria", "1,000 adultos mayores atendidos por año"),
        P("transporte", "Red «San Juan Integrado»: buses alimentadores desde Pamplona Alta y Nueva Rinconada hasta la estación Atocongo de la Línea 1, con tarifa social de S/ 1.00", 12, "Establecer tarifa social de S/ 1.00 para los buses alimentadores", "Viaje total (alimentador + Metro) no mayor a S/ 2.50; frecuencia de 4-5 minutos en hora punta"),
        P("transporte", "Ordenamiento de mototaxis: registro con código QR, GPS y botón de pánico, corredores barriales y retiro de paraderos informales", 13, "Registro Único de Vehículos Menores (RUVM-SJM)", "90% de mototaxis formalizadas en 4 años y 100% con identificación QR al 2030"),
        P("economia", "Ventanilla única municipal para formalizar negocios, marca colectiva «Sello SJM» y modernización de las zonas comerciales", 15, "reduciendo trámites de 30 días a no más de 5 días hábiles", "Trámites de 30 días a no más de 5 días hábiles"),
        P("social", "Academia Municipal Preuniversitaria gratuita en convenio con el Instituto Gilda Ballivián Rosado, con becas para hijos de fundadores y familias de bajos ingresos", 17, "Academia Municipal Preuniversitaria SJM", "2 turnos, 600 alumnos por año y 200 becas por ciclo"),
        P("social", "Copa interescolar anual en 7 disciplinas, Selección SJM, rehabilitación de losas y construcción de polideportivos", 18, "Construcción de 5 Polideportivos durante la gestión", "5 polideportivos"),
        P("ambiente", "Reemplazar el riego con camiones cisterna por aspersión en parques y goteo subterráneo en las bermas de las avenidas principales", 21, "Plan de Riego Tecnificado SJM 2027-2030", "100% tecnificado y 70% de ahorro de agua en el cuarto año"),
        P("ambiente", "Programa «SJM Verde» con siembra de árboles y recuperación de parques, y fiscalización de emisiones de empresas con medición de calidad del aire", 21, "siembra de 50,000 árboles y plantas en 4 años", "50,000 árboles y plantas en 4 años y 20 parques y bermas recuperados"),
        P("gestion", "«Portal Digital SJM» para trámites en línea y presupuesto participativo con votación digital", 23, "plataforma web y app móvil para realizar el 80% de los trámites", "80% de los trámites en línea; al menos 15% del presupuesto de inversión decidido por los vecinos"),
    ]),
    ("Edilberto Lucio Quispe Rodríguez", "PRIN", "partido-politico-prin", [
        P("seguridad", "Patrullaje integrado en 5 cuadrantes, cada uno con camionetas, motos, cámaras con reconocimiento facial e inteligencia artificial y central de monitoreo", 28, "Cada Cuadrante contará con 10 camionetas", "10 camionetas y 20 motos por cuadrante, el doble de serenos y 15 drones"),
        P("social", "Programa de Lucha contra la Violencia a la Mujer creado por ordenanza y un Centro Integral de la Mujer, el Adulto Mayor y la Cultura", 14, "En los 60 primeros días se ha creado", "Programa creado en los primeros 60 días"),
        P("social", "Construir centros de educación inicial e implementar bibliotecas virtuales y un Instituto Tecnológico Municipal de cursos técnicos", 15, "ocho Centros de Educación Inicial (CEI)", "8 centros de educación inicial y 10 bibliotecas virtuales en el primer año"),
        P("social", "Construir dos establecimientos de salud de nivel I y un Policlínico Municipal, y gestionar ante EsSalud un hospital de nivel II", 18, "dos (2) establecimientos de salud (IPRESS)", "2 establecimientos de salud de nivel I"),
        P("economia", "Empadronar y ordenar el comercio informal, construir un Mercado Municipal y crear un Centro de Desarrollo Empresarial", 24, "Creación y construcción de un Mercado Municipal", "80% del comercio informal regulado y 25% más micro y pequeñas empresas"),
        P("ambiente", "Rehabilitar la Planta de Transferencia, construir una Planta de Reciclaje y renovar la flota de recolección", 30, "adquisición de 10 Compactadoras", "10 compactadoras, 4 camiones madrina y 3 camiones baranda; 25% de residuos segregados en los domicilios"),
        P("ambiente", "Parque temático y ecológico en Pampas de San Juan y plantación de árboles y plantas típicas", 31, "Proyecto Temático y Ecológico en un área de 22,000 m2", "Parque de 22,000 m² y 4 m² de área verde por habitante"),
        P("agua_riesgos", "Convenio con una entidad sin fines de lucro para controlar la calidad del agua que reparten los camiones cisterna en los asentamientos humanos", 32, "control de la calidad del agua que distribuyen los Camiones Cisterna"),
        P("transporte", "Sensores en los semáforos de la Av. Los Héroes y «Pista Nueva» y reglamento para el transporte en vehículos menores", 37, "implementando sensores en los Semáforos", "Reducir en 35 minutos los tiempos de demora"),
        P("gestion", "Tres agencias municipales descentralizadas, un velatorio municipal y un albergue municipal para mascotas", 39, "Se han instalado tres (3) Agencias municipales", "3 agencias municipales"),
        P("gestion", "Declaración jurada de intereses de autoridades y funcionarios desde el primer día y comité de seguimiento de inversiones", 41, "Declaración Jurada de Intereses", "El promedio de la ejecución anual de inversiones supera el 90%"),
    ]),
    ("Oswaldo Graviel Taype Gutiérrez", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Programa «SJM Seguro 24/7»: red de cámaras de alta resolución con reconocimiento de placas y una Central de Control y Operaciones articulada con la PNP", 15, "Central de Control y Operaciones Municipal"),
        P("seguridad", "Sistema «Alerta Vecinal San Juan»: central de respuesta rápida con botones de pánico, alarmas comunitarias y aplicativo móvil", 16, "Central de Respuesta Rápida con atención permanente"),
        P("urbano", "Programa «Título Seguro para tu Familia»: titulación masiva con COFOPRI en Nueva Rinconada, Pampas de San Juan y Pamplona Alta, con asesoría legal gratuita", 19, "programa masivo de formalización y titulación de predios"),
        P("agua_riesgos", "Programa «Agua y Dignidad»: gestionar con SEDAPAL redes, reservorios y conexiones para las zonas que dependen de camiones cisterna", 19, "Agua y Dignidad para San Juan"),
        P("urbano", "Programa «Conectando Barrios»: pistas, veredas, escaleras y muros de contención en las zonas altas y de difícil acceso", 20, "pistas, veredas, escaleras, accesos peatonales y muros de contención"),
        P("ambiente", "Programa «Recicla San Juan»: contenedores diferenciados y puntos ecológicos en parques, mercados y colegios, con recicladores formalizados", 23, "contenedores diferenciados y puntos ecológicos de reciclaje"),
        P("economia", "Programa «Ordenemos San Juan» para reordenar el comercio ambulatorio y «Formalízate y Crece» con asistencia técnica y orientación tributaria", 24, "reordenamiento del comercio ambulatorio"),
        P("economia", "Escuela Municipal de Emprendedores con capacitación gratuita para jóvenes, mujeres y pequeños comerciantes, ferias y ruedas de negocios", 27, "Escuela Municipal de Emprendedores orientada a jóvenes"),
        P("social", "Programa «Primer Empleo Sanjuanino» con convenios para prácticas y empleo juvenil, y Bolsa Laboral Municipal", 28, "Bolsa Laboral Municipal de San Juan de Miraflores"),
        P("gestion", "Plataforma «Transparencia en Tiempo Real» con presupuesto, obras y contrataciones, y rendición pública de cuentas trimestral", 36, "Transparencia en Tiempo Real"),
        P("transporte", "Plan Integral de Ordenamiento Vehicular con la ATU en las avenidas San Juan, Los Héroes, Miguel Iglesias y accesos al Metro", 44, "Plan Integral de Ordenamiento Vehicular"),
    ]),
    ("Martín José Palomino Córdova", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Anillos de seguridad con cámaras con IA y lectura de placas enlazadas a la central de Lima Metropolitana, y despacho del serenazgo con software CAD", 2, "Sistema Distrital de Anillos de Seguridad con cámaras de IA", "Tiempo de respuesta del Serenazgo menor a 10 minutos en zonas consolidadas y a 15 minutos en laderas al 2030"),
        P("social", "Dos centros municipales de fisioterapia (Zona Urbana y Pamplona Alta) operados con convenios universitarios", 3, "Alcanzar las 20,000 terapias gratuitas de fisioterapia", "20,000 terapias gratuitas acumuladas al 2030"),
        P("social", "Programa «Sonrisas para la Inclusión» con prótesis dentales para adultos mayores y bolsa laboral para personas con discapacidad", 3, "800 prótesis dentales focalizadas", "Hasta 800 prótesis dentales y 200 personas con discapacidad con empleo al 2030"),
        P("social", "Centros municipales de desarrollo infantil, recuperación de losas deportivas y un centro de atención a mujeres víctimas de violencia", 4, "hasta 5 centros de desarrollo infantil", "Hasta 5 centros de desarrollo infantil y hasta 30 losas deportivas recuperadas"),
        P("economia", "Plataforma «SJM Digital - TUPA 24 Horas» para licencias de funcionamiento e ITSE, y ventanilla única empresarial sin papel", 4, "SJM Digital - TUPA 24 Horas", "Licencias en un máximo de 24 horas hábiles; hasta 4,000 nuevos establecimientos formalizados al 2030"),
        P("economia", "Centro de Desarrollo Empresarial con PRODUCE, Escuela de Emprendimiento e Inteligencia Artificial y bolsa laboral conectada con empresas de Lima Sur", 5, "Escuela de Emprendimiento e Inteligencia Artificial", "Hasta 5,000 comerciantes capacitados y hasta 3,000 colocaciones laborales al 2030"),
        P("ambiente", "Rutas de limpieza optimizadas por software, control por GPS del tonelaje de las concesionarias y descuentos en arbitrios por segregar residuos", 6, "erradicación y recuperación sostenible de hasta el 90%", "98% de cumplimiento de rutas y erradicar hasta el 90% de los puntos críticos de basura al 2030"),
        P("ambiente", "Programa de Parques Inteligentes con mantenimiento, reforestación y riego tecnificado", 6, "Programa de Parques Inteligentes", "Hasta 50,000 m² de áreas verdes recuperadas al 2030"),
        P("agua_riesgos", "Unidad «Destrabe Pamplona Alta» para formular expedientes de muros de contención y transitabilidad en laderas", 6, "Destrabe Pamplona Alta", "Hasta 15 expedientes técnicos para laderas críticas de Pamplona Alta al 2030"),
        P("gestion", "Tránsito al régimen SERVIR con perfiles de puestos y filtros de idoneidad para funcionarios de confianza", 7, "Filtros de Idoneidad e Ingreso Meritocrático", "100% de funcionarios de confianza con perfiles auditados desde el primer día"),
        P("gestion", "Ventanilla única digital con firma y pagos en línea, presupuesto participativo digital y tableros de datos abiertos sobre obras", 8, "Datos Abiertos y Control Ciudadano", "80% de los trámites de alta demanda del TUPA digitalizados al 2030"),
    ]),
    ("Mabel Karina Leandro Melgarejo", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Programa «SJM Seguro 360»: central inteligente de monitoreo, red de videovigilancia, bases de seguridad comunitaria y alerta vecinal digital", 22, "Instalar 500 cámaras de videovigilancia", "500 cámaras de videovigilancia y 15 bases de serenazgo"),
        P("social", "Casa de la Mujer Sanjuanina con atención psicológica y legal, escuela de emprendimiento para mujeres y programa Familias Fuertes", 23, "Una sede principal de la Casa de la Mujer Sanjuanina", "Más de 20,000 mujeres beneficiadas; una sede principal y centros descentralizados"),
        P("social", "Instituto Tecnológico Municipal (informática, IA aplicada, logística, marketing digital) y programa Primer Empleo", 24, "El instituto beneficiaría a 5,000 jóvenes", "15,000 jóvenes capacitados, 5,000 oportunidades laborales y 5,000 jóvenes en el instituto"),
        P("social", "Gestionar ante EsSalud y el Gobierno Nacional un hospital de nivel III en terrenos de EsSalud en el distrito", 24, "construcción de un Hospital Nivel III"),
        P("social", "Red de complejos deportivos «San Juan Activo» con coliseo techado, canchas y gimnasio comunitario", 27, "Construir o modernizar siete complejos deportivos", "7 complejos deportivos, uno por zona"),
        P("urbano", "Plan integral de pistas y veredas y convenios con Cementos Lima para las avenidas Pedro Miotta, Miguel Iglesias, Canevaro, San Juan y Los Héroes", 28, "especialmente con Cementos Lima", "250,000 m² de pistas y 180,000 m² de veredas"),
        P("agua_riesgos", "Plan «Cerro Seguro»: escaleras integrales y muros de contención en las zonas altas", 29, "Construcción de 120 escaleras integrales", "120 escaleras y 50 muros de contención"),
        P("economia", "«Licencia Express» y ventanilla única empresarial con atención virtual", 49, "Reducir 70% tiempos de obtención de licencias", "Reducir 70% los tiempos de obtención de licencias"),
        P("ambiente", "Planta de segregación, centro de reciclaje, compostaje de orgánicos y formalización de recicladores", 39, "Reducir en 30% la disposición final de residuos", "30% menos residuos enviados a disposición final"),
        P("ambiente", "«100 Parques para San Juan» y arborización, con riego tecnificado usando aguas residuales tratadas en convenio con SEDAPAL", 40, "Plantar más de 50,000 árboles", "100 parques recuperados, más de 50,000 árboles y 100% de parques principales con riego sostenible"),
        P("gestion", "«Municipalidad Digital 100%»: expediente electrónico, mesa de partes virtual integrada y gestión por resultados", 42, "Expediente Electrónico Municipal", "Digitalizar la totalidad de los principales procedimientos administrativos municipales"),
    ]),
    ("Andy Alan Vilca Huamán", "Visión Perú", "vision-peru", [
        P("seguridad", "Juntas o comités barriales de seguridad, patrullaje comunitario y mesas de diálogo entre policía y vecinos", 4, "Creación y fortalecimiento de Juntas o Comités Barriales de Seguridad"),
        P("seguridad", "Mesa Municipal de Seguridad Ciudadana, mejor iluminación y mobiliario urbano, y evaluación periódica del plan", 5, "Creación de una Mesa Municipal de Seguridad Ciudadana"),
        P("agua_riesgos", "Simulacros distritales, capacitación en gestión del riesgo y primeros auxilios, y equipamiento de brigadas comunitarias", 6, "Realizar 2 simulacros distritales anuales", "2 simulacros distritales al año y 5,000 vecinos capacitados"),
        P("agua_riesgos", "Actualizar el mapa distrital de riesgos e intervenir técnicamente asentamientos humanos en zonas vulnerables", 6, "Actualizar el 100% del mapa distrital de riesgos", "Mapa de riesgos actualizado antes de 2027 y al menos 15 asentamientos humanos intervenidos"),
        P("ambiente", "Rutas selectivas de reciclaje y formalización de recicladores", 6, "Aumentar la tasa de reciclaje distrital al 25%", "Reciclaje del 25% de los residuos, 5 nuevas rutas selectivas y 100% de recicladores formalizados"),
        P("ambiente", "Plantar árboles urbanos y ejecutar proyectos de infraestructura verde como biohuertos y parques sostenibles", 5, "Plantar y mantener 5,000", "5,000 árboles urbanos al 2030 y 1 m² adicional de área verde por habitante"),
        P("economia", "Formalización y fortalecimiento de MYPES, capacitación en gestión empresarial y nuevos corredores comerciales formales", 9, "Capacitar al menos 5,000", "20% más MYPES formalizadas y al menos 5,000 emprendedores y jóvenes capacitados en 4 años"),
        P("social", "Nuevos comedores populares o fortalecimiento de los existentes con asistencia técnica y alimentaria", 9, "Implementar 10 nuevos", "10 comedores populares nuevos o fortalecidos"),
        P("social", "Panadería municipal con cobertura gratuita para las instituciones educativas del distrito", 9, "panadería municipal con"),
        P("gestion", "Mesas de trabajo por zonas (Pamplona Alta, Ciudad de Dios, etc.), audiencias públicas descentralizadas y publicación de la ejecución presupuestal", 7, "Implementar al menos 10 mesas de trabajo zonales permanentes", "Al menos 10 mesas zonales y 4 audiencias públicas descentralizadas por año"),
        P("gestion", "Digitalizar trámites, app para reportar incidencias de seguridad, limpieza y pistas, y seguimiento de expedientes en línea", 8, "Digitalizar el 80% de los trámites municipales", "80% de trámites digitalizados y 40% menos tiempo de atención al vecino"),
    ]),
]
