"""Pueblo Libre (150121): propuestas principales de los 12 planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
El plan de Somos Perú es un PDF escaneado: su texto proviene de OCR y sus cifras se contrastaron con la imagen.
"""

UBIGEO = "150121"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Carlos Enrique Arana Urteaga", "Acción Popular", "accion-popular", [
        P("seguridad", "«Anillo de Seguridad Ciudadana Interdistrital»: videovigilancia con reconocimiento facial y de placas en todos los accesos del distrito, interconectada con los distritos vecinos", 12, "Anillo de Seguridad Ciudadana Interdistrital", "100 % de accesos al distrito monitoreados"),
        P("transporte", "Plan de movilidad urbana sostenible con semaforización inteligente en vías principales para evitar que las calles residenciales se usen como atajos", 13, "Plan Integral de Movilidad Urbana Sostenible"),
        P("social", "Programa «Pueblo Libre Crece Sano» contra la anemia en niños y gestantes, con talleres de alimentación, biohuertos y ferias nutricionales", 14, "Pueblo Libre Crece Sano"),
        P("social", "Programa «Pueblo Libre Plateado» para adultos mayores: envejecimiento activo, educación digital y red de apoyo comunitario", 14, "Pueblo Libre Plateado"),
        P("economia", "«Ruta Turística de los Libertadores» entre museos, Plaza Bolívar y bulevares gastronómicos, con señalética bilingüe, wifi y códigos QR, y sello «Pueblo Libre Histórico»", 18, "Ruta Turística de los Libertadores", "3 rutas turísticas integradas y 100 negocios con sello «Pueblo Libre Histórico»"),
        P("economia", "Licencia de funcionamiento digital «cero papeles» con aprobación automática para negocios de riesgo bajo o medio, y plataforma «Marketplace Pueblo Libre»", 19, "Licencia de Funcionamiento Digital"),
        P("ambiente", "Riego tecnificado de parques con agua residual tratada y reemplazo del césped de bermas por especies nativas de bajo consumo de agua", 19, "Migrar al 100% de riego tecnificado", "100 % de riego tecnificado"),
        P("agua_riesgos", "Plan de reforzamiento del patrimonio histórico con microzonificación sísmica, y rutas de evacuación con señalización solar y alertas tempranas", 21, "microzonificación sísmica"),
        P("urbano", "Soterramiento progresivo del cableado aéreo y rehabilitación de pistas y veredas, priorizando zonas como el AA.HH. 7 de Junio", 22, "soterramiento de cables aéreos"),
        P("ambiente", "Programa «Basura que Vale»: descuentos en arbitrios a las juntas vecinales que cumplan metas de segregación", 23, "Basura que Vale", "Reciclar y valorizar el 30 % de los residuos; segregación en el 100 % de sectores vecinales"),
        P("gestion", "App «Pueblo Libre Smart» para reportar incidencias, pagar tributos y seguir expedientes, y digitalización del archivo municipal («Cero Papeles»)", 24, "Pueblo Libre Smart", "100 % del archivo digitalizado y 80 % de trámites en línea"),
    ]),
    ("Óscar Raúl Cabello Acosta", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Modernizar la Central de Alerta con cámaras con inteligencia artificial y lectura de placas en los 12 accesos limítrofes del distrito", 4, "12 accesos limítrofes del distrito", "100 % de cobertura tecnológica en zonas limítrofes y avenidas"),
        P("seguridad", "Programa «Zona Segura»: patrullaje por subsectores con un efectivo de la PNP a bordo de cada unidad móvil de serenazgo", 5, "rediseñando el mapa de patrullaje", "Respuesta a emergencias en un máximo de 4 minutos"),
        P("agua_riesgos", "Nuevo plan de gestión de desastres con rutas de evacuación en las 8 zonas vecinales, brigadistas por barrio y simulacros", 5, "Rutas de evacuación por cada una de las 8 zonas vecinales", "Simulacros escolares y municipales dos veces al año"),
        P("gestion", "Audiencias vecinales en cada una de las 8 zonas del distrito, con atención directa del alcalde y sus funcionarios", 5, "audiencias vecinales en cada una de 08 zonas"),
        P("social", "Quioscos Inclusivos y talleres gratuitos de la OMAPED para que personas con discapacidad vendan sus productos", 6, "Quioscos Inclusivos"),
        P("social", "Escuela Municipal de Artes gratuita y festivales «Cultura en tu Plaza» descentralizados en parques", 6, "Escuela Municipal de Artes", "1 000 alumnos al 2030"),
        P("economia", "«Ruta de Museos Pueblo Libre»: circuito cultural con entrada única y transporte interno los domingos", 6, "Ruta de Museos Pueblo Libre"),
        P("economia", "Programa «Comercio Vecino»: ferias bimensuales de productores locales en 6 parques del distrito", 9, "ferias bimensuales de productores locales en 6 parques"),
        P("transporte", "Gestionar semáforos inteligentes en las avenidas Brasil, Bolívar, Sucre y La Mar", 11, "Semáforos inteligentes en las principales vías", "Reducir 25 % el tiempo de viaje en zonas congestionadas en hora punta"),
        P("urbano", "Convertir los parques en espacios multiuso con juegos infantiles, áreas para mascotas, minigimnasios y losas deportivas", 11, "parques multiusos"),
        P("ambiente", "Recolección de residuos diaria en zonas comerciales, de alta densidad y parques, y dos veces al día en mercados", 12, "Mercados Dos veces por día", "Cobertura del 100 %"),
    ]),
    ("Hilgo Antonio Manchego Ormeño", "Alianza Regional por el Perú", "alianza-regional-por-el-peru", [
        P("seguridad", "Fortalecer la seguridad ciudadana para reducir la percepción de inseguridad en el distrito", 3, "Reducir la percepción de inseguridad en el distrito"),
        P("social", "Ampliar la cobertura de los programas sociales y la atención a adultos mayores y población vulnerable", 3, "Incrementar la cobertura de programas sociales"),
        P("social", "Ampliar la oferta cultural y deportiva del distrito", 3, "Ampliar la oferta cultural y deportiva"),
        P("economia", "Incrementar la formalización de mypes, el empleo local y el apoyo a emprendedores", 3, "Incrementar la formalización de MYPES"),
        P("economia", "Potenciar el turismo cultural del distrito", 3, "Potenciar el turismo cultural del distrito"),
        P("ambiente", "Incrementar las áreas verdes, reducir la contaminación y mejorar la limpieza pública", 4, "Incrementar áreas verdes urbanas"),
        P("urbano", "Recuperar espacios públicos deteriorados y proteger el patrimonio histórico", 4, "Recuperar espacios públicos deteriorados"),
        P("gestion", "Implementar el gobierno digital municipal y reducir los tiempos de atención", 5, "Implementar gobierno digital municipal"),
        P("gestion", "Audiencias públicas de rendición de cuentas e informes de gestión periódicos en plataformas digitales", 5, "audiencias públicas semestrales", "Audiencias públicas semestrales"),
    ]),
    ("José Luis Casas Carrión", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Central C4 de monitoreo 24/7 que integra videovigilancia con IA, despacho de serenazgo y el aplicativo «Alerta Pueblo Libre» con botón de pánico", 37, "Integrar al menos 120 cámaras inteligentes al sistema distrital", "1 Central C4, al menos 120 cámaras inteligentes integradas y 25 % menos tiempo de respuesta"),
        P("social", "Casa del Vecino para el adulto mayor y programa de cuidadores certificados por la municipalidad", 24, "Formación de al menos 300 cuidadores certificados", "1 Casa del Vecino operativa y al menos 300 cuidadores certificados"),
        P("social", "Boticas municipales con medicamentos genéricos a bajo costo y orientación médica telefónica desde el C4", 25, "Creación de boticas municipales con medicamentos genéricos", "8 000 vecinos beneficiados por boticas municipales"),
        P("social", "Centro Preuniversitario Municipal y talleres técnicos por oficios con certificación", 26, "Creación de un Centro Preuniversitario Municipal", "2 000 vecinos capacitados en talleres técnicos y deportivos"),
        P("urbano", "Programa «Parques Familiares Inclusivos y Seguros»: juegos inclusivos, iluminación LED, videovigilancia y renovación de veredas", 28, "Parques Familiares Inclusivos y Seguros de Pueblo Libre", "20 parques recuperados, LED en 70 % de parques priorizados y videovigilancia en 15"),
        P("economia", "Programa «Pueblo Libre Trabaja y Emprende» con bolsa de trabajo, certificación laboral y coworking municipal", 30, "Pueblo Libre Trabaja y Emprende", "2 500 vecinos insertados laboralmente y 1 coworking municipal"),
        P("economia", "Plan de desarrollo turístico con circuitos temáticos, señalización patrimonial y programa «Serenos Guía» en zonas turísticas", 32, "Creación de un programa especializado de Serenos Guía", "4 circuitos turísticos y 40 Serenos Guía capacitados"),
        P("ambiente", "Programa «Pueblo Libre Limpio y Verde»: segregación en la fuente, reciclaje, más tachos y educación ambiental", 33, "Pueblo Libre Limpio y Verde", "25 % más segregación de residuos sólidos"),
        P("transporte", "Gestión del tránsito en horas pico con evaluación de carriles reversibles, renovación de señalización y ciclovías conectivas", 35, "Evaluación de carriles reversibles en ejes críticos", "15 % menos congestión en vías críticas y 25 intersecciones mejoradas"),
        P("urbano", "Plan de Desarrollo Urbano participativo con parámetros de zonificación, altura y densidad, y evaluación del impacto de nuevos proyectos", 35, "Formulación participativa del PDU distrital", "Evaluar el 100 % de proyectos inmobiliarios relevantes con criterios de impacto urbano"),
        P("gestion", "Informes semestrales de avance del plan en el portal institucional y audiencias públicas de rendición de cuentas", 42, "Se realizarán informes semestrales", "Informes semestrales"),
    ]),
    ("Josmell Absalón Muñoz Barranzuela", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("gestion", "Programa «Pueblo Libre Digital 100 %»: mesa de partes virtual, expediente y firma electrónicos, y notificaciones digitales", 14, "PUEBLO LIBRE DIGITAL 100%", "90 % de trámites digitalizados al 2030"),
        P("seguridad", "Convenio para comprar días de franco a la PNP y sumar 3 policías por zona distrital", 23, "incrementar a 24 policías adicionales", "24 policías adicionales"),
        P("seguridad", "Red de cámaras inteligentes con analítica de video, reconocimiento de placas en los accesos y una unidad de drones", 20, "RED DISTRITAL DE CÁMARAS INTELIGENTES", "Instalar 100 cámaras inteligentes durante la gestión"),
        P("economia", "Licencia express para actividades de bajo riesgo y ventanilla única empresarial", 26, "LICENCIA EXPRESS 48 HORAS", "Licencias de bajo riesgo en un máximo de 48 horas"),
        P("economia", "Centro Municipal de Emprendimiento e Innovación con capacitación en marketing digital, inteligencia artificial y comercio electrónico", 26, "CENTRO MUNICIPAL DE EMPRENDIMIENTO E INNOVACIÓN", "5 000 emprendedores capacitados"),
        P("social", "Telemedicina municipal en medicina general, nutrición, psicología y orientación geriátrica", 31, "PROGRAMA: TELEMEDICINA MUNICIPAL", "20 000 atenciones durante la gestión"),
        P("social", "Programa «Salud Cerca de Ti»: campañas médicas, vacunación, despistajes y salud mental", 34, "PROGRAMA: SALUD CERCA DE TI", "50 000 atenciones preventivas"),
        P("urbano", "Plan integral de pistas y veredas priorizando vías principales, entornos escolares, zonas comerciales y turísticas", 36, "PLAN INTEGRAL DE PISTAS Y VEREDAS", "100 % de las vías críticas intervenidas al 2030"),
        P("transporte", "Semaforización inteligente con sensores de tránsito y estacionamientos subterráneos mediante asociación público-privada", 37, "Estacionamientos subterráneos mediante APP"),
        P("ambiente", "Primer biohuerto municipal y Escuela Vivero Municipal para producir árboles y plantas para parques y bermas", 39, "Escuela Vivero Municipal", "500 m² de biohuerto"),
        P("ambiente", "Corredores verdes en las avenidas Bolívar, Sucre y Vivanco con recuperación del arbolado y miniparques en las bermas", 39, "CORREDORES VERDES EN LAS AVENIDAS"),
    ]),
    ("Jhonel Jorge Leguía Jamis", "Somos Perú", "partido-democratico-somos-peru", [
        P("gestion", "Revisión de todas las áreas y funciones municipales para eliminar duplicidades y digitalizar la gestión", 8, "Levantamiento integral de todas las áreas y funciones", "80 % de la gestión municipal digitalizada al 2030"),
        P("economia", "Censo del comercio ambulatorio, mesa de diálogo y licencias temporales para su formalización progresiva", 9, "Establecer un censo del comercio ambulatorio", "Formalizar el 40 % del comercio ambulatorio"),
        P("economia", "Simplificar los procesos para otorgar licencias de comercio, industria y servicios", 10, "Impulsar la simplificación de procesos para otorgar licencias", "Reducir en 50 % el proceso para que un negocio pueda operar"),
        P("ambiente", "Programa «En Pueblo Libre la Basura Sirve» con Bono Naranja: reciclaje con reducción progresiva del arbitrio", 7, "Pueblo Libre la Basura Sirve"),
        P("urbano", "Mejoramiento del ornato, pistas y veredas, incluida la pavimentación de las calles del AA.HH. 7 de Junio", 7, "pavimentación de las calles del AA.HH 7 de Junio"),
        P("seguridad", "Casetas de videovigilancia por sectores con serenos en motocicleta, y juntas vecinales con equipos tecnológicos en las 8 zonas", 13, "casetas de video vigilancia por sectores"),
        P("seguridad", "Cámaras con identificación de rostro conectadas con patrulleros, y serenazgo con armas no letales, canes y drones", 14, "armas no letales, canes y drones"),
        P("social", "Reactivar el Policlínico Municipal con telemedicina, ambulancias tipo II y psicólogos itinerantes", 12, "Reactivar Policlínico Municipal"),
        P("social", "Academia Preuniversitaria Municipal, biblioteca interactiva y construcción de un Teatro Municipal", 15, "Crear la Academia Pre Universitaria Municipal"),
        P("transporte", "Servicio de grúa municipal y sincronización de los semáforos de las vías metropolitanas", 14, "servicio de grúa municipal"),
        P("ambiente", "Reservorio y planta de aguas residuales en parques para riego por goteo, y arborización con árbol kiri", 18, "Crear un reservorio plantas de aguas residuales"),
    ]),
    ("Fabiola Lucero Silva Montero", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("social", "Programa «El Médico en tu casa»: atención domiciliaria con médico, enfermera, psicólogo y nutricionista para población vulnerable", 15, "programa El Medico en tu", "840 personas atendidas el primer año y 3 360 atenciones en 4 años"),
        P("ambiente", "Veterinaria Municipal «Charly» con esterilizaciones y campañas de adopción", 15, "Veterinaria Municipal de Pueblo Libre CHARLY", "1 440 mascotas atendidas el primer año"),
        P("social", "Comedor municipal con menús saludables a costos sociales para población vulnerable", 16, "Implementación de un comedor municipal", "Cobertura del 80 % de los usuarios beneficiarios"),
        P("seguridad", "Cámaras inteligentes con reconocimiento facial y estaciones de alarma vecinal", 16, "Instalación de 500 cámaras inteligente con reconocimiento facial", "500 cámaras y 100 estaciones de alarma vecinal"),
        P("social", "Academia «CEPRE MUNI» para preparar el ingreso a universidades", 17, "ACADEMIA CEPRE MUNI", "5 % de alumnos ingresantes el primer año"),
        P("economia", "Feria «De la chacra a la olla» con productores, en convenio con el Ministerio de Agricultura y PRODUCE", 18, "Feria de la chacra a la olla", "12 ferias al año"),
        P("agua_riesgos", "Pozo tubular, cisterna soterrada y cisternas en parques para el riego, y planta de tratamiento del agua de acequia", 20, "Construcción de 01 pozo tubular", "1 pozo tubular, 1 cisterna soterrada de 100 m³ y 15 cisternas de 10 m³"),
        P("ambiente", "Barredores adicionales para repaso en zonas estratégicas y flota municipal de compactadoras", 20, "Contratación de 14 barredores", "14 barredores adicionales; compactadoras 100 % municipales al cuarto año"),
        P("urbano", "Mejoramiento integral de pistas y veredas del AA.HH. 7 de Junio", 21, "Asentamiento Humano 7 de Junio", "50 % de calles y veredas ejecutadas"),
        P("transporte", "Renovar la señalética de tránsito y los nombres de las calles", 21, "Mejorar 90% de la señalética de tránsito", "90 % de la señalética de tránsito y 70 % de los nombres de calles"),
        P("gestion", "Reducir las unidades orgánicas y el personal administrativo para optimizar el gasto municipal", 21, "Reevaluación y disminución de las unidades", "20 % menos unidades orgánicas y 25 % menos personal"),
    ]),
    ("Miguel Stefano Ruiz Gutiérrez", "Partido Morado", "partido-morado", [
        P("social", "Centro de Cuidado Diurno «Manos que cuidan» en la Casa del Adulto Mayor, de 8 a. m. a 6 p. m., con tópico y cuidadores certificados", 27, "grupo inicial de 30 adultos mayores", "30 adultos mayores atendidos el primer año"),
        P("social", "Botica Municipal con medicamentos genéricos y esenciales a precios accesibles", 30, "Implementar la botica con al menos 100 medicamentos esenciales", "Al menos 100 medicamentos esenciales y 1 000 vecinos atendidos el primer año"),
        P("seguridad", "Aplicativo con geolocalización del patrullaje de serenazgo en tiempo real y evaluación vecinal de la respuesta", 31, "Reducir el tiempo promedio de respuesta de serenazgo a menos de 4 minutos", "Respuesta en menos de 4 minutos y 25 % menos delitos contra el patrimonio"),
        P("social", "Defensoría de las Juventudes con teleconsultas psicológicas nocturnas gratuitas y chats anónimos con especialistas", 32, "Realizar 25,000 tele consultas psicológicas gratuitas", "25 000 teleconsultas psicológicas"),
        P("economia", "Centro de innovación y emprendimiento en la Biblioteca Municipal con coworking, incubadora y bolsa de trabajo digital", 34, "Incubar 500 emprendimientos innovadores", "15 000 personas capacitadas, 500 emprendimientos incubados y 3 000 negocios formalizados"),
        P("economia", "Circuitos culturales, gastronómicos e históricos con tótems inteligentes, códigos QR y realidad aumentada", 36, "Implementar 10 puntos turísticos inteligentes con realidad aumentada", "10 puntos turísticos inteligentes y 50 % más flujo turístico"),
        P("transporte", "Red de ciclovías segregadas con sensores de flujo e iluminación LED solar", 38, "Implementar y modernizar 15 km de ciclovías seguras", "15 km de ciclovías"),
        P("urbano", "Programa «Nuevo 07 de Junio»: catastro 3D con drones y saneamiento físico-legal de predios", 39, "Realizar el saneamiento físico-legal de 1,000 predios urbanos", "Catastro 3D del 100 % del sector y saneamiento de 1 000 predios"),
        P("urbano", "Plan integral de pistas y veredas con materiales certificados y brigadas de mantenimiento preventivo", 40, "Reparar 15 km de veredas en zonas críticas", "15 km de veredas y 5 km de pistas en el primer año"),
        P("ambiente", "Programa «Basura Cero Digital»: contenedores inteligentes, rutas con GPS, planta de valorización y compostaje", 43, "Instalar 50 contenedores inteligentes", "50 contenedores inteligentes y 50 % más reciclaje"),
        P("gestion", "Gobierno abierto con portal de transparencia en tiempo real, observatorio ciudadano y audiencias trimestrales transmitidas", 44, "Realizar 16 audiencias públicas de rendición de cuentas", "100 % de contrataciones publicadas y 16 audiencias públicas"),
    ]),
    ("Fidel Bratzo García Durante", "PPC", "partido-popular-cristiano-ppc", [
        P("social", "Gestionar un convenio con EsSalud para construir el primer Centro de Atención Primaria del distrito", 6, "convenio con ESSALUD para construir el primer Centro de Atención Primaria"),
        P("social", "Policlínico Municipal con tarifas sociales, telemedicina y médicos especialistas", 6, "Un Policlínico Municipal con Rostro Humano"),
        P("social", "Academia Preuniversitaria Municipal y escuelas municipales de danzas peruanas, teatro y coro", 6, "La Academia Preuniversitaria Municipal"),
        P("economia", "Capacitación técnica gratuita para abrir negocios y fiscalización municipal orientada a acompañar a los comercios", 8, "capacitación técnica gratuita de vanguardia"),
        P("ambiente", "Vivero municipal, arborización con especies de bajo consumo de agua y monitoreo del arbolado con tomógrafo forestal", 9, "tomógrafo forestal, radar de raíces"),
        P("agua_riesgos", "Tratar el agua del canal Huatica con sedimentadores antes del riego y perforar un pozo tubular exclusivo para áreas verdes", 10, "sedimentadores con piedra chancada y carbón vegetal"),
        P("urbano", "Renovar las avenidas Vivanco, Paseo de los Andes, El Río y José Leguía y Meléndez como corredores accesibles con baldosas podotáctiles", 11, "Avenidas Emblemáticas Renovadas", "100 % de las avenidas priorizadas remodeladas y accesibles"),
        P("transporte", "Reductores de velocidad en las urbanizaciones Colmenares y Cueva, y señalización vertical en cada esquina", 11, "urbanizaciones Colmenares y Cueva", "100 % de esquinas del distrito señalizadas"),
        P("ambiente", "Contenedores soterrados, recolección nocturna supervisada por GPS y cuadrilla de respuesta rápida ante focos infecciosos", 12, "Cuadrilla de Respuesta Rápida", "Recolección 100 % nocturna con GPS y focos atendidos en menos de 24 horas"),
        P("seguridad", "Videovigilancia con reconocimiento de placas, bases de serenazgo en cada sector y alarmas vecinales activables desde el celular", 13, "bases descentralizadas en cada sector"),
        P("gestion", "Municipio 100 % digital para pagos, licencias y trámites, portal de transparencia en tiempo real e internet gratuito en plazas", 14, "Transformaremos la gestión en una plataforma 100% digital"),
    ]),
    ("Daniel Martín Amaya Carranza", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Centro de Monitoreo 24/7 con cámaras de reconocimiento facial y de placas, patrullaje por cuadrantes y serenazgo guiado por mapas de calor del delito", 12, "Cámaras Inteligentes de Seguridad 360", "Reducir en 90 % los robos, hurtos y extorsiones en 2027-2030"),
        P("seguridad", "Unidad Distrital Antiextorsión con la DIVINCRI y el Ministerio Público, botón de pánico vecinal y red «Alerta Pueblo Libre»", 13, "Unidad Distrital Antiextorsión"),
        P("urbano", "Plan «Infraestructura de Primera»: pistas y veredas de alta durabilidad, señalización, accesibilidad universal y ciclovías", 14, "Mejoramiento integral de pistas y veredas, con estándares de alta durabilidad", "Plan ejecutado al 100 % al 2030"),
        P("transporte", "Estacionamientos subterráneos autofinanciados en parques, con techos verdes y energía solar", 15, "Estacionamientos subterráneos Autofinanciados en Parques"),
        P("social", "Escuelas deportivas municipales gratuitas, becas deportivas y Coliseo Municipal con estacionamiento subterráneo", 16, "Escuelas Deportivas Municipales Gratuitas", "Escuelas de al menos 10 disciplinas; inicio del coliseo antes de 2028"),
        P("social", "Alimentación saludable, tamizaje y seguimiento contra la anemia en niños, adolescentes y gestantes", 17, "Reducir la tasa de anemia en niños, jóvenes y madres gestantes en el 20%", "Reducir la anemia en 20 % el primer año"),
        P("economia", "Ruta cultural-turística señalizada entre museos, casas históricas, iglesias y restaurantes, y turismo barrial vivencial", 17, "Ruta Cultural-Turística de Pueblo Libre"),
        P("economia", "Formalización de actividades económicas informales y catastro con tecnología LIDAR para ampliar la base tributaria", 24, "Programa de formalización de al menos el 80%", "Formalizar al menos el 80 % de las actividades económicas"),
        P("ambiente", "Riego tecnificado en parques, puntos limpios de reciclaje y eliminación de plásticos de un solo uso en eventos municipales", 27, "Sistema de Regadío Tecnificado en Parques", "95 % de parques con riego tecnificado"),
        P("agua_riesgos", "Diagnóstico del territorio y sistema de alerta temprana, con capacitación de líderes vecinales en gestión del riesgo", 28, "Capacitar al 95% de los lideres vecinales", "95 % de líderes vecinales capacitados"),
        P("gestion", "Programa «Pueblo Libre Transparente» con publicación mensual de gastos, contratos, licitaciones y avance de obras", 30, "Publicación mensual de gastos, contratos, licitaciones", "Publicación mensual"),
    ]),
    ("Cecilia Acosta Cajaleón", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Programa «Pueblo Libre Seguro 24/7»: patrullaje integrado con la PNP, mapa del delito, videovigilancia, alerta vecinal e iluminación de puntos críticos", 3, "Pueblo Libre Seguro 24/7"),
        P("social", "«Pueblo Libre sin Violencia Familiar»: campañas preventivas y articulación con el CEM, la PNP, la Fiscalía y servicios de salud", 3, "Pueblo Libre sin Violencia Familiar"),
        P("social", "«Pueblo Libre Saludable 2030»: campañas contra hipertensión, diabetes, obesidad y anemia, y salud mental comunitaria", 3, "Pueblo Libre Saludable 2030"),
        P("social", "«Aprende Pueblo Libre»: refuerzo escolar en lectura y matemática, clubes de lectura y tutorías con universidades", 3, "Aprende Pueblo Libre"),
        P("social", "«Pueblo Libre Inclusivo»: rampas, cruces seguros y veredas accesibles, y atención municipal inclusiva", 3, "Pueblo Libre Inclusivo y sin Discriminación"),
        P("economia", "«Pueblo Libre Emprende y Formaliza»: catastro económico, licencias simplificadas, escuela de emprendedores y reordenamiento del comercio informal", 3, "Pueblo Libre Emprende y Formaliza"),
        P("economia", "«Pueblo Libre Destino Cultural»: plan maestro de la zona monumental, Ruta de los Libertadores, señalética y marca turística", 4, "Pueblo Libre Destino Cultural"),
        P("ambiente", "Reparar el canal de regadío y almacenar agua para riego; adquirir grúa de poda, barredoras mecanizadas y camión cisterna", 4, "reparación y optimización del canal de regadío"),
        P("agua_riesgos", "«Pueblo Libre Resiliente»: mapa de riesgos, inspecciones de seguridad, brigadas vecinales por sectores y simulacros", 4, "Pueblo Libre Resiliente"),
        P("transporte", "«Movilidad Segura y Accesible»: mejora de vías locales, veredas y cruces peatonales, y zonas escolares seguras", 4, "Movilidad Segura y Accesible"),
        P("gestion", "Mesa de Gobernanza Territorial con mesas temáticas y tablero público del avance del plan de gobierno", 5, "Mesa de Gobernanza Territorial de Pueblo Libre durante el primer año", "Instalada en el primer año de gestión"),
    ]),
    ("Walter Alfonso Cavero Villanes", "Visión Perú", "vision-peru", [
        P("seguridad", "Central de Monitoreo interoperable, alarmas y sirenas vecinales activables desde el celular, y botones de pánico y drones en parques", 13, "sistemas de alarmas y sirenas vecinales", "35 % menos percepción de inseguridad y respuesta del serenazgo en menos de 7 minutos"),
        P("seguridad", "Serenazgo con cámaras corporales y Camdash, programa «Barrios Seguros con Juntas Vecinales» y voluntariado vecinal", 13, "Brigada de Intervención Inmediata en Motocicleta"),
        P("social", "Fortalecer el CIAM y la OMAPED con talleres productivos, y oportunidades de empleo para adultos mayores", 15, "Fortaleceremos el CIAM"),
        P("social", "Campañas de salud preventiva, salud mental y vacunación, y mejora de la biblioteca, los complejos deportivos y la piscina municipal", 15, "Impulsaremos campañas de salud preventiva, salud mental, vacunación", "30 % más campañas integrales de salud al año"),
        P("urbano", "Recuperar los parques 3 de Octubre y Candamo con riego tecnificado, iluminación LED, pérgola bioclimática y domo verde multifuncional", 16, "pérgola bioclimática con cobertura vegetal", "Recuperar el 100 % de parques y espacios públicos priorizados"),
        P("transporte", "Recuperar las veredas fiscalizando scooters y motos, semáforos inteligentes, más ciclovías y reordenamiento del transporte menor", 18, "Recuperaremos las veredas para el uso exclusivo de los peatones"),
        P("economia", "Programa «Emprende Libre» de empleabilidad, capacitación y digitalización de negocios, con licencias simplificadas", 20, "Emprende Libre", "30 % más formalización comercial"),
        P("economia", "Circuitos turísticos culturales con señalización moderna y audioguías, y ferias gastronómicas", 20, "señalización moderna, audioguías", "30 % más flujo turístico"),
        P("ambiente", "Segregación en la fuente, recolección selectiva y formalización de recicladores, con reconocimiento a vecinos", 21, "formalización de recicladores", "50 % más segregación de residuos"),
        P("agua_riesgos", "Uso de aguas tratadas y riego tecnificado en parques para reducir el uso de agua potable", 22, "Promoveremos el uso de aguas tratadas para el riego"),
        P("gestion", "Observatorio Ciudadano de Obras y Servicios, audiencias públicas trimestrales y trámites digitales", 24, "Implementar un Observatorio Ciudadano de Obras y Servicios Municipales", "4 audiencias públicas al año"),
    ]),
]
