"""Ate (150103): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150103"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Walter Jesús Rivera Guerra", "Acción Popular", "accion-popular", [
        P("seguridad", "Sistema distrital de seguridad con serenazgo fortalecido, videovigilancia interconectada con la PNP y juntas vecinales en Huaycán, Vitarte y Santa Clara", 1, "videovigilancia interconectada con la PNP", "Reducir en 30 % la tasa de denuncias al 2030 y 50 % más serenazgo"),
        P("social", "Centro Municipal de Atención a la Mujer y red de promotoras comunitarias contra la violencia familiar", 2, "Centro Municipal de Atención a la Mujer", "Centro operativo al 2027 y 25 % menos denuncias al 2030"),
        P("urbano", "Recuperar losas deportivas y parques con iluminación LED y ampliar programas deportivos y culturales para jóvenes", 2, "Recuperar los espacios públicos y ampliar los programas deportivos", "40 losas deportivas y parques recuperados con iluminación LED al 2030"),
        P("economia", "Programa de formalización y capacitación de MYPE con ruedas de negocio y compras locales de los centros comerciales del distrito", 2, "ruedas de negocio y compras locales", "Al menos una rueda de negocio al año con centros comerciales y grandes empresas"),
        P("economia", "Empadronar al comercio ambulatorio y reubicarlo de forma concertada en espacios autorizados", 2, "empadronamiento, formalización progresiva y reubicación concertada", "Empadronamiento de la mayoría al 2027 y 30 % reubicados o formalizados al 2030"),
        P("economia", "Ampliar la Bolsa de Trabajo Municipal con convenios con empresas, institutos y universidades para jóvenes", 3, "Bolsa de Trabajo Municipal"),
        P("agua_riesgos", "Gestionar y cofinanciar con SEDAPAL y el Ministerio de Vivienda el cierre de la brecha de agua y saneamiento en las zonas altas", 3, "SEDAPAL, el MVCS", "Cartera de proyectos inscrita en el Programa Multianual de Inversiones al 2027"),
        P("ambiente", "Renovar la flota de recojo, optimizar rutas, erradicar puntos críticos de basura y segregar con recicladores formalizados", 3, "recicladores formalizados", "100 % de puntos críticos erradicados al 2028 y recojo en el 98 % del distrito"),
        P("agua_riesgos", "Muros de contención, escaleras de evacuación y capacitación comunitaria en gestión del riesgo en laderas de cerros", 4, "muros de contención, pasajes con escaleras seguras"),
        P("gestion", "Gobierno abierto con datos abiertos, simplificación de trámites y rendiciones de cuentas descentralizadas", 4, "Dos rendiciones de cuentas públicas por año", "2 rendiciones de cuentas al año (8 en el periodo) y 100 % de cumplimiento del Portal de Transparencia"),
        P("gestion", "Fortalecer la gerencia de inversiones y usar Obras por Impuestos y convenios para acelerar el cierre de brechas", 4, "Obras por Impuestos y convenios interinstitucionales", "Ejecución presupuestal de obras de 90 % o más cada año"),
    ]),
    ("Luis Eusebio Poma Tacuri", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Centro de Comando C4 con cámaras con inteligencia artificial, reconocimiento facial y lectura de placas conectadas a las requisitorias de la PNP", 8, "500 cámaras de videovigilancia con analítica", "500 cámaras con IA"),
        P("seguridad", "Dividir el distrito en sub-cuadrantes de patrullaje integrado, cada uno con camioneta de serenazgo, dos motos y un efectivo de la PNP", 8, "45 sub-cuadrantes tácticos", "45 sub-cuadrantes y respuesta a emergencias en menos de 5 minutos"),
        P("social", "Tres policlínicos municipales «MuniSalud Ate» en Huaycán, Santa Clara y Vitarte con tarifas sociales", 9, "tres policlínicos municipales descentralizados", "3 policlínicos"),
        P("social", "Estrategia «Anemia Cero» con promotores de salud que visitan casa por casa para tamizaje y entrega de hierro", 9, "batallón de promotores de salud municipales", "Anemia infantil por debajo de 15 % al 2030"),
        P("urbano", "Renovar losas deportivas barriales con techado e iluminación LED y escuelas deportivas municipales gratuitas", 10, "Renovación total de 120 lozas deportivas", "120 losas deportivas"),
        P("economia", "Programa «Mercados de Oportunidad»: tres terrenos mediante asociaciones público-privadas para reubicar a los ambulantes de Ceres y la Carretera Central", 10, "tres grandes terrenos estratégicos", "8 000 comerciantes insertados en 3 nuevos mercados"),
        P("economia", "Plataforma «Licencia Express 48 Horas» para licencias e inspecciones técnicas de negocios de bajo y mediano riesgo", 11, "Licencia Express 48 Horas", "Licencias en un máximo de 48 horas hábiles"),
        P("ambiente", "Renovar los camiones compactadores con GPS y una app para seguir el recorrido, y planta de valorización y reciclaje", 11, "camiones compactadores municipales", "100 % de cobertura de recojo diario"),
        P("agua_riesgos", "Muros de contención en laderas habitadas de alta pendiente", 12, "Construcción prioritaria de 85 muros de contención", "85 muros de contención"),
        P("ambiente", "Arborización con especies nativas de bajo consumo de agua regadas con aguas residuales tratadas", 12, "Reforestación Urbana y Cinturón Verde", "4,5 m² de áreas verdes por habitante al 2030"),
        P("gestion", "Sede Central Virtual para pagar arbitrios, presentar reclamos y seguir expedientes con un código QR", 12, "Sede Central Virtual Municipal", "85 % de trámites totalmente virtuales al 2030"),
    ]),
    ("Arturo Jonell Peña Sánchez", "Alianza Electoral Venceremos", "alianza-electoral-venceremos", [
        P("social", "Programa «Ate Sin Anemia» con tamizaje, escuelas de padres, huertos comunitarios y educación nutricional", 33, "Contribuir a reducir la incidencia de anemia infantil", "Reducir la anemia infantil en al menos 30 % al 2030"),
        P("social", "Academia Preuniversitaria Municipal Gratuita con sedes en Salamanca, Vitarte, Santa Clara y Huaycán", 34, "Academia Preuniversitaria Municipal Gratuita Venceremos", "10 000 beneficiarios entre 2027 y 2030"),
        P("social", "Escuelas municipales de ajedrez y escuelas deportivas gratuitas en las siete zonales para prevenir drogas y violencia", 37, "Escuelas Municipales e Itinerantes de Ajedrez", "Más de 50 000 vecinos beneficiados al 2030"),
        P("economia", "Red distrital de ferias itinerantes en las siete zonales para acercar productores y emprendedores a los consumidores", 38, "Realizar más de 200 ferias", "Más de 200 ferias durante la gestión"),
        P("economia", "Centro Municipal de Desarrollo Productivo con capacitación, marketing digital, formalización y asesoría legal", 39, "Capacitar a más de 15,000 emprendedores", "Más de 15 000 emprendedores capacitados"),
        P("economia", "Bolsa laboral digital, ferias de empleo y certificación de competencias para jóvenes, mujeres y personas con discapacidad", 40, "Facilitar la inserción laboral de 10,000 vecinos", "10 000 vecinos insertados laboralmente en la gestión"),
        P("ambiente", "Programa «Ate Verde y Vivo» de arborización masiva, reforestación de cerros y recuperación de bermas", 43, "Plantación de 200,000 árboles", "200 000 árboles en 2027–2030"),
        P("urbano", "Recuperar parques y espacios públicos con mobiliario, iluminación, riego tecnificado y áreas deportivas", 44, "Recuperar y mejorar más de 150 parques", "Más de 150 parques y espacios públicos"),
        P("ambiente", "Contenedores diferenciados, programas de reciclaje y formalización de recicladores", 44, "Incrementar en 50% los niveles de reciclaje", "50 % más reciclaje distrital"),
        P("seguridad", "Red distrital de rondas comunitarias coordinadas con la municipalidad y la PNP, junto con serenazgo fortalecido y cámaras", 49, "Red Distrital de Rondas Comunitarias", "Organizaciones comunitarias de seguridad en las siete zonales"),
        P("gestion", "Espacio semanal de rendición de cuentas del alcalde transmitido en vivo, con participación de vecinos y cabildos descentralizados", 54, "espacio semanal de rendición de cuentas"),
    ]),
    ("Manuel Gaudencio Vidal Camargo", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Patrullaje integrado serenazgo-PNP, videovigilancia con IA, drones, alarmas vecinales y primer registro municipal de extranjeros", 44, "instalar 500 cámaras adicionales de videovigilancia y 100 drones", "500 cámaras adicionales y 100 drones"),
        P("social", "Estrategia «Ate Hambre Cero» con bancos de alimentos y redes de distribución solidaria", 44, "atender a 70,000 beneficiarios mediante redes de distribución solidaria", "70 000 beneficiarios"),
        P("social", "Ampliar los programas juveniles Mi Primera Chamba y Minka Joven y habilitar espacios para la juventud", 44, "habilitar al menos un espacio para la juventud", "Al menos un espacio para la juventud en cada zona prioritaria"),
        P("economia", "Licencias de funcionamiento digitales y Centro Municipal de Desarrollo Empresarial con apoyo en comercio electrónico", 45, "formalizar y fortalecer 5,000 emprendimientos", "5 000 emprendimientos y MYPE formalizados y fortalecidos"),
        P("economia", "Centro Municipal de Empleo, Bolsa de Trabajo Digital y convenios de capacitación con institutos y empresas", 45, "tasa de inserción laboral efectiva del 40%", "40 % de inserción laboral efectiva de los participantes"),
        P("economia", "Formalizar recicladores y actividades de valorización de residuos para generar empleo verde", 45, "Formalizar e incorporar 500 recicladores", "500 recicladores y asociaciones formalizados y 300 empleos verdes"),
        P("ambiente", "Recolección de residuos optimizada con inteligencia artificial y erradicación de puntos críticos de basura", 46, "Incrementar en 50% la eficiencia de la gestión de residuos", "50 % más eficiencia en la gestión de residuos y el reciclaje"),
        P("urbano", "Recuperar y ampliar áreas verdes y espacios públicos con riego tecnificado y participación vecinal", 46, "recuperar e implementar 500,000 m", "500 000 m² de áreas verdes"),
        P("agua_riesgos", "Sistemas de alerta temprana, obras de mitigación en zonas críticas y brigadas vecinales ante desastres", 46, "capacitar 200 brigadas vecinales", "100 % de sistemas de alerta en zonas de riesgo y 200 brigadas vecinales"),
        P("transporte", "Gestión del tránsito con inteligencia artificial y análisis de datos para reducir tiempos de viaje", 46, "Reducir en 20% los tiempos promedio de desplazamiento", "20 % menos tiempo de desplazamiento y monitoreo en el 80 % de vías principales"),
        P("gestion", "Plataforma digital integrada con mesa de partes virtual, app municipal y firma digital, y 5 oficinas desconcentradas", 47, "Digitalizar el 90% de los procedimientos administrativos", "90 % de trámites digitalizados y 50 % menos tiempo de atención"),
    ]),
    ("Misael Meneses Flores", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("social", "Programa «Ate Crece Sano» con tamizaje, suplementación de hierro y seguimiento de niños y gestantes", 13, "Reducir la anemia infantil de 24.7% a menos del 5%", "Anemia infantil de 24,7 % a menos de 5 % al 2030"),
        P("social", "Programa «Ate Futuro» con becas municipales, academias preuniversitarias gratuitas, centros técnico-productivos y bolsa de trabajo juvenil", 14, "Beneficiar a 18,000 jóvenes", "18 000 jóvenes beneficiados"),
        P("seguridad", "Nueva central de monitoreo con IA, más videovigilancia, patrullaje integrado con la PNP, alarmas vecinales y postes inteligentes", 14, "incrementar de 250 a 1,000 cámaras", "30 % menos delitos contra el patrimonio y de 250 a 1 000 cámaras"),
        P("urbano", "Programa «Ate Activa y Saludable»: complejos deportivos, losas y parques recuperados, iluminación LED y gimnasios al aire libre", 15, "Construir o recuperar 100 espacios deportivos", "100 espacios deportivos y recreativos al 2030"),
        P("agua_riesgos", "Gestionar con Sedapal proyectos de agua y alcantarillado, electrificación y formalización predial en barrios vulnerables", 15, "Beneficiar a 30,000 hogares", "30 000 hogares beneficiados"),
        P("economia", "Centro Municipal de Empleo, bolsa de trabajo, certificación de competencias y primer empleo para jóvenes", 16, "Beneficiar a 30,000 vecinos", "30 000 vecinos en programas de capacitación, empleo y formalización"),
        P("economia", "Modernizar mercados estratégicos con mejoras de accesibilidad, seguridad, iluminación y manejo de residuos", 17, "Modernizar al menos 15 mercados", "Al menos 15 mercados y centros de abastecimiento modernizados"),
        P("transporte", "Mejorar vías estratégicas, modernizar semáforos y gestionar conexiones con la autopista Ramiro Prialé", 18, "Mejorar 100 km de infraestructura vial", "100 km de vías mejoradas y 40 % menos tiempo de viaje en el distrito"),
        P("ambiente", "Arborización masiva, recuperación de terrenos eriazos, corredores ecológicos y viveros municipales", 19, "Plantar 100,000 árboles", "100 000 árboles y 500 000 m² de áreas verdes al 2030"),
        P("agua_riesgos", "Muros de contención, drenajes pluviales, estabilización de taludes y protección de quebradas", 19, "Intervenir el 100% de las zonas priorizadas", "100 % de las zonas priorizadas de riesgo alto y muy alto"),
        P("gestion", "Expediente electrónico, mesa de partes virtual, app municipal y seguimiento de trámites en línea", 21, "Digitalizar el 100% de los tr", "100 % de trámites prioritarios digitalizados"),
    ]),
    ("Óscar Ramírez Rojas", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Central única de videovigilancia con cámaras con IA y lectura de placas, botones de pánico y patrullaje por cuadrantes con la PNP", 13, "Reducir en 40% los delitos contra el patrimonio", "40 % menos delitos contra el patrimonio al 2030"),
        P("social", "Campañas preventivas itinerantes de salud mental, anemia y nutrición, y esterilización de mascotas", 13, "Alcanzar 100,000 atenciones preventivas", "100 000 atenciones preventivas en el periodo"),
        P("social", "Gestionar ante el MINSA un centro especializado de atención para personas con enfermedad renal crónica en Lima Este", 10, "enfermedad renal crónica en Lima Este"),
        P("social", "Actualizar padrones y fortalecer OMAPED, CIAM, DEMUNA, Vaso de Leche y comedores populares", 11, "40% de población vulnerable identificada con intervención", "40 % de la población vulnerable identificada con intervención o derivación"),
        P("economia", "Exonerar por un año el cobro de tasas de licencias de funcionamiento para nuevos emprendimientos", 11, "Exonerar por un año el cobro de tasas"),
        P("gestion", "Digitalización de trámites, mesa de partes digital y seguimiento de expedientes", 11, "80% de trámites priorizados disponibles", "80 % de trámites priorizados disponibles o iniciados en línea"),
        P("social", "Becas técnicas, formación digital y bolsa laboral juvenil", 14, "10,000 jóvenes capacitados al 2030", "10 000 jóvenes capacitados al 2030"),
        P("social", "Fortalecer la DEMUNA, centros de orientación, prevención de la violencia y emprendimiento femenino", 14, "Incrementar en 50% la cobertura de atención de mujeres", "50 % más cobertura de atención a mujeres en situación de vulnerabilidad"),
        P("ambiente", "Arborización y recuperación de la ribera del río Rímac con gimnasios y zonas de caminata", 14, "Incrementar 50,000 árboles", "50 000 árboles más en el distrito"),
        P("transporte", "Semaforización inteligente, recuperación de vías locales, mejora de paraderos y seguridad vial escolar", 14, "Reducir en 20% los puntos críticos de congestión", "20 % menos puntos críticos de congestión"),
        P("gestion", "Elección vecinal de los jefes de las agencias municipales de Huaycán, Santa Clara y Salamanca", 12, "elección de los jefes de las agencias municipales"),
    ]),
    ("Jaime Bruno Valeriano Codina", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("social", "Bibliotecas itinerantes y talleres de alfabetización", 23, "Reducir el analfabetismo en un 20%", "Reducir el analfabetismo en 20 %"),
        P("social", "Campañas de prevención de enfermedades, alimentación saludable y campañas anticaries en colegios", 23, "Campañas anti caries en colegios", "Reducir en 30 % los casos de anemia y desnutrición"),
        P("seguridad", "Brigadas vecinales contra la delincuencia, convenios con la PNP y talleres de prevención de la violencia en colegios", 23, "Conformar 50 brigadas de seguridad", "50 brigadas de seguridad"),
        P("seguridad", "Más cámaras de videovigilancia y un equipo de «cazadores de delitos»", 27, "meta 600 cámaras", "600 cámaras"),
        P("transporte", "Inspectores de transporte, convenio con la PNP para el tránsito, reparación de vías colectoras y señales viales", 24, "Implementar inspectores de transporte en las zonas claves", "20 % menos tiempo de viaje y 80 % de baches críticos reparados"),
        P("transporte", "Mejorar avenidas como Metropolitana, 22 de Julio, Nicolás de Piérola y Los Quechuas", 27, "Mejoramiento de la Av. Metropolitana"),
        P("economia", "Ferias gastronómicas y emprendedoras por zonas", 24, "Realizar 1 feria mensual por zona", "1 feria mensual por zona"),
        P("ambiente", "Tachos de basura en avenidas principales, recuperación de flora en la ribera del Rímac y ordenanza contra la contaminación sonora", 25, "2000 tachos implementados en todo el distrito", "2 000 tachos"),
        P("agua_riesgos", "Muros de contención en zonas vulnerables de Huaycán, limpieza del cauce del Rímac y alcantarillas en puntos críticos", 25, "Creación de muros de contención en las zonas vulnerables", "4 muros, 40 % menos botaderos en el río y 3 alcantarillas"),
        P("urbano", "Cruces peatonales accesibles y nivelación de veredas para personas con discapacidad", 25, "2km de veredas niveladas", "40 % de cruces accesibles y 2 km de veredas niveladas"),
        P("gestion", "Certificación antisoborno ISO 37001, canal de denuncias de corrupción y pasantías vecinales en la municipalidad", 26, "certificación ISO 37001", "Atender el 80 % de denuncias de corrupción de forma oportuna"),
    ]),
    ("Miguel Ángel Malma Valverde", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Más patrullaje y cámaras, puestos de auxilio rápido, alarmas vecinales y brigadas juveniles preventivas", 7, "Instalar 300 cámaras de seguridad", "300 cámaras de seguridad"),
        P("seguridad", "Centro Inteligente de Seguridad Distrital con cámaras en avenidas, parques y mercados, serenazgo motorizado y drones", 13, "Centro Inteligente de Seguridad Distrital"),
        P("social", "Campañas médicas gratuitas, apoyo a ollas comunes, atención psicológica comunitaria y campañas contra la anemia", 8, "Apoyo a ollas comunes"),
        P("social", "Academias deportivas municipales, talleres gratuitos, becas y recuperación de losas deportivas", 8, "Academias deportivas municipales"),
        P("economia", "Ferias laborales, bolsa de trabajo, convenios con empresas y apoyo a la formalización de pequeños negocios", 9, "Bolsa de trabajo municipal"),
        P("economia", "Reordenar el comercio ambulatorio, mejorar mercados y fiscalización sanitaria", 9, "Reordenamiento del comercio ambulatorio"),
        P("transporte", "Señalización, ordenamiento de paraderos, fiscalización del transporte informal y semaforización", 10, "Fiscalización del transporte informal"),
        P("ambiente", "Más recojo de residuos, contenedores en zonas críticas y sanciones por arrojo de basura", 10, "Sanciones por arrojo de basura"),
        P("ambiente", "Arborización, recuperación de parques abandonados y programas de reciclaje", 11, "Recuperar parques abandonados"),
        P("urbano", "Plan «Obras en tu barrio»: pistas, veredas, iluminación pública y mejoramiento de mercados", 15, "Mejoramiento de pistas y veredas"),
        P("gestion", "Publicación de gastos, audiencias públicas y plataforma virtual de transparencia", 11, "Plataforma virtual de transparencia"),
    ]),
    ("Enrique Bruno Palma Salinas", "Partido del Buen Gobierno", "partido-del-buen-gobierno", [
        P("seguridad", "Escuela de Serenazgo con filtros de ingreso, cámaras con reconocimiento facial y de placas, drones y bases zonales descentralizadas", 5, "500 cámaras de videovigilancia con reconocimiento de patrón facial", "500 cámaras, 10 drones y 4 bases zonales"),
        P("social", "Fortalecer los policlínicos municipales, ampliar la atención médica domiciliaria y campañas preventivas en zonas de difícil acceso", 6, "atención médica domiciliaria", "20 % más acceso oportuno a servicios de salud"),
        P("social", "Programa con el MINEDU y el sector privado para reducir la deserción escolar y los jóvenes que no estudian", 6, "reducir la deserción escolar", "Reducir a la mitad la deserción escolar y los jóvenes que no estudian al 2030"),
        P("agua_riesgos", "Simulacros de sismo, mantenimiento de pozos de agua de emergencia con SEDAPAL y «tambos de emergencia»", 7, "tambos de emergencia"),
        P("transporte", "Señalización, semaforización, ampliación de ciclovías y planes de descongestión en Nicolás Ayllón y la Carretera Central", 7, "se ampliarán ciclovías", "Duplicar los operativos y acciones de tránsito al 2030"),
        P("ambiente", "Planta de tratamiento de residuos con economía circular, recolección selectiva con recicladores y eco-puntos para residuos especiales", 7, "Planta de Tratamiento de Residuos S", "35 % de viviendas priorizadas segregan y 100 % de recicladores formalizados"),
        P("ambiente", "Plan Distrital de Arbolado con especies nativas de bajo consumo de agua y programa «Adopta un árbol / adopta un parque»", 8, "plantar 50,000 árboles", "50 000 árboles"),
        P("ambiente", "Proteger el Bosque Urbano Separadora Industrial y exigir al MTC actualizar el expediente del Anillo Vial Periférico", 8, "intangibilidad del Bosque Urbano Separadora Industrial", "100 % del bosque protegido (0 árboles talados)"),
        P("economia", "Ventanilla única digital de formalización y programa «Ate te compra» de compras a productores locales", 9, "Ate te compra", "100 % más emprendedores beneficiados"),
        P("economia", "Centro Logístico con ventanilla única, corredores y horarios diferenciados para carga pesada y monitoreo del aire", 10, "corredores logísticos exclusivos con horarios diferenciados", "70 % de operadores formalizados y 40 % menos congestión en horas punta"),
        P("gestion", "Crear la Oficina General de Integridad Institucional y audiencias semestrales en las tres zonas del distrito", 12, "Oficina General de Integridad Institucional", "Primer año de gestión"),
    ]),
    ("Simón Ortiz Talaverano", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Sistema integrado de seguridad con PNP, Ministerio Público, Poder Judicial y juntas vecinales en cada zona", 25, "Juntas Vecinales de Seguridad en cada organizaci"),
        P("seguridad", "Más personal de serenazgo y cámaras conectadas con la central 105 de la PNP en zonas comerciales y residenciales", 25, "conectadas con el 105 de la Polic"),
        P("social", "Ampliar la clínica municipal e implementar policlínicos municipales por zonas para atención primaria", 26, "Policlínicos Municipales en las diferentes zonas"),
        P("social", "Casa de la Juventud en cada zona con academias preuniversitarias y polideportivos", 27, "Casa de la Juventud en cada zona"),
        P("social", "Instituto Superior Tecnológico para formar mano de obra para la industria del distrito", 28, "Instituto Superior Tecnológico en el Distrito"),
        P("transporte", "Prolongar vías como la Av. Colectora, Javier Prado y José Carlos Mariátegui hasta la autopista Ramiro Prialé", 28, "Prolongación de tramos de vía"),
        P("transporte", "Semaforización en puntos de concentración, más puentes peatonales y reordenamiento de paraderos con Lima y el MTC", 28, "Construcción de más puentes peatonales"),
        P("economia", "Crear la Caja Municipal de Ate para dar crédito a microempresas e implementar un terminal pesquero municipal", 29, "Caja Municipal de Ate"),
        P("urbano", "Titulación masiva, habilitación urbana expeditiva y consulta vecinal previa a los cambios de zonificación", 29, "consulta vecinal previa los cambios de zonificaci"),
        P("ambiente", "Arborización de cerros del Estadio Monumental al futuro Parque Zonal de Huaycán y Gran Parque Ecológico de Huaycán", 30, "Gran Parque Ecológico de Huaycán"),
        P("gestion", "Línea gratuita 0-800 para sugerencias y denuncias, cabildo abierto y licencias de funcionamiento automáticas", 30, "Implementar una línea telefónica gratuita"),
    ]),
    ("Maidy Marti López Casimiro", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Mejorar el patrullaje integrado y profesionalizar al serenazgo para erradicar la delincuencia y la prostitución", 3, "Erradicar en un plazo de tres años la delincuencia", "En un plazo de tres años"),
        P("agua_riesgos", "Gestionar proyectos de inversión para abastecer de agua potable a los pueblos de Ate", 4, "Abastecer de agua potable en un plazo de cuatro años", "80 % de la población cubierta a octubre de 2030"),
        P("urbano", "Plan de titulación con COFOPRI para el saneamiento físico legal de propiedades", 4, "Gestión de convenio con COFOPRI", "90 % de la población con títulos a octubre de 2030"),
        P("economia", "Formalizar a vendedores ambulantes y empresas privadas con licencias de funcionamiento y certificados ITSE", 3, "Formalizar en un plazo de dos años a todos los vendedores ambulantes", "En dos años (diciembre de 2028)"),
        P("economia", "Ferias «de la chacra a la olla» con productores agropecuarios del distrito y de otros distritos", 5, "venta y consumo de productos agropecuarios", "En un año, con 90 % de la población de las siete zonas beneficiada"),
        P("ambiente", "Proyectos de inversión para el tratamiento e industrialización de la basura", 3, "tratamiento e industrialización de la basura", "En dos años, con 95 % de la población beneficiada"),
        P("ambiente", "Contenedores de clasificación de residuos y campañas de educación y reciclaje", 5, "campañas de educación y reciclaje", "En cuatro años (diciembre de 2030)"),
        P("gestion", "Código de ética y conducta para proveedores y funcionarios con apoyo de la Contraloría", 5, "digo de ética y conducta de proveedores", "En un año (diciembre de 2027)"),
        P("gestion", "Sistema integrado de gestión ISO 9001 con apoyo de expertos externos", 3, "sistema integrado de gestión ISO 9001", "En un año"),
    ]),
    ("Jorge Antonio Salazar Velásquez", "Partido Morado", "partido-morado", [
        P("social", "Centros de rehabilitación y apoyo psicológico para niños con autismo y sus familias", 5, "4 centros de rehabilitación para niños autistas", "4 centros de rehabilitación"),
        P("social", "Reactivar el policlínico municipal y construir policlínicos en Huaycán, Valle de Amauta, Horacio Zevallos, Salamanca y Valdiviezo", 5, "1 policlínicos en Huaycán"),
        P("social", "Ampliar el presupuesto del Vaso de Leche en 30 % para mejorar las raciones contra la anemia e incluir a adultos mayores", 6, "reducir de un 20 % a un 15% la tasa de anemia", "Reducir la anemia de 20 % a 15 % en las zonas más vulnerables"),
        P("economia", "Ferias sabatinas y dominicales en plazas y parques para que los emprendedores vendan sus productos", 7, "ferial sabatinas y dominicales", "Bajar el desempleo de 6,8 % a 2,5 %"),
        P("gestion", "Digitalizar los servicios administrativos de la municipalidad", 7, "Digitalización de los servicios administrativos municipales"),
        P("seguridad", "Centros de inteligencia de videovigilancia con cámaras de reconocimiento facial conectados al serenazgo y a la PNP", 8, "Construcción de 12 centros de inteligencia de video vigilancia", "12 centros; reducir la inseguridad de 90 % a 50 %"),
        P("seguridad", "Drones de vigilancia distribuidos en las 7 zonas de Ate", 10, "Compra de 50 DRONES DE ULTIMA GENERACION", "50 drones"),
        P("ambiente", "Comprar camiones compactadores propios para el recojo de basura en lugar de pagar el servicio", 8, "compra de 60 camiones compactadores de basura", "60 camiones; 95 % de recolección de residuos"),
        P("urbano", "Recuperar las zonas arqueológicas de Pariachi, Valle de Amauta y Catalina Huanca, con un mini museo y áreas recreativas", 8, "zona arqueológica de Pariachi de Huaycán"),
        P("urbano", "Losas deportivas, juegos infantiles y gimnasios al aire libre en terrenos abandonados recuperados", 9, "recuperación de espacios y terrenos en abandono"),
        P("gestion", "Oficina anticorrupción municipal coordinada con el Poder Judicial, la Fiscalía y la PNP", 10, "Creación de la Oficina anticorrupción municipal"),
    ]),
    ("Carlos Daniel Cuya Ponce", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Programa «Ate se Respeta» integrado con la PNP, juntas vecinales y videovigilancia distrital", 22, "dicho programa integrado con la policía"),
        P("transporte", "Establecer paraderos en la Carretera Central y mejorar vías y señalización, gestionando las obras con Lima Metropolitana", 23, "establecer paraderos en la carretera central"),
        P("social", "Policlínico municipal y botica municipal con atención las 24 horas", 23, "atención en la botica municipal las 24 horas"),
        P("social", "Programas de salud para niños menores de 5 años con desnutrición crónica y anemia", 23, "niños menores de 5 años con desnutrición crónica infantil"),
        P("social", "Primera Orquesta Sinfónica de Ate con educación musical gratuita para niños y adolescentes", 24, "PRIMER ORQUESTA SINFONICA DE ATE"),
        P("social", "Gestionar con el Minedu y la UGEL 06 la primera institución educativa municipal de Ate, de 2.º a 5.º de secundaria", 24, "primera Institución Educativa Municipal Distrital"),
        P("agua_riesgos", "Gestionar directamente con los vecinos sin servicio de agua y saneamiento, eliminando barreras burocráticas", 25, "Gestionar directamente con la población Ateña que no cuentan con"),
        P("urbano", "Planos a costo cero para personas de bajos recursos, a cargo del área de catastro", 25, "de catastro, en realizar costo cero"),
        P("economia", "Gestionar el primer terminal pesquero en Ate", 26, "Gestionar el primer terminal pesquero"),
        P("ambiente", "Supervisar a las empresas industriales que contaminan y afectan a la población, en especial a los niños", 26, "contaminación ambiental y afecte a la población en especial a los niños"),
        P("gestion", "Audiencias públicas de rendición de cuentas y página web con gestión, ingresos, egresos y plan de obras", 31, "audiencia pública cada seis meses", "Al menos una audiencia pública cada seis meses"),
    ]),
    ("Gianmarco Valentín Tobalino Castillo", "Partido Patriótico del Perú", "partido-patriotico-del-peru", [
        P("seguridad", "Central Inteligente de Seguridad Ciudadana con cámaras con IA, reconocimiento de placas y patrullaje integrado con la PNP", 6, "Implementación de la Central Inteligente de Seguridad Ciudadana", "Reducir los delitos entre 40 % y 60 % al 2030"),
        P("seguridad", "Bases descentralizadas de monitoreo y drones de vigilancia en las 7 zonas del distrito", 7, "Creación de bases descentralizadas de monitoreo"),
        P("economia", "Centro Municipal de Desarrollo Empresarial y formalización masiva de MYPES, emprendedores y comerciantes", 7, "Programa de formalización masiva de MYPES", "50 % de MYPES formalizadas al 2030"),
        P("economia", "Parque Industrial y Logístico de Lima Este o parque científico y tecnológico", 8, "Parque Industrial y Logístico de Lima Este"),
        P("social", "Centros de salud mental comunitarios, clínicas itinerantes y un centro psicológico en las 3 agencias municipales", 9, "Centro psicológico municipal"),
        P("transporte", "Plan «Cero Baches», semaforización inteligente e integración vial con la Línea 2 del Metro", 10, "Integración vial con Línea 2 del Metro", "40 % de vías principales recuperadas al 2030"),
        P("urbano", "Escaleras y muros de contención, iluminación LED y estacionamientos municipales", 10, "Escaleras y muros de contención"),
        P("ambiente", "Recuperar el río Rímac desde el límite con El Agustino hasta Chaclacayo, con parque temático y corredores peatonales", 11, "Protección y Recuperación total del río Rímac"),
        P("ambiente", "Planta de tratamiento de residuos sólidos, reciclaje vecinal y arborización masiva", 11, "Planta de Tratamiento de Residuos Sólidos", "25 % de residuos reciclados y 80 % de áreas verdes recuperadas al 2030"),
        P("agua_riesgos", "Planta de tratamiento de aguas residuales, gestión de riesgo de desastres y reforestación de laderas", 11, "Planta de Tratamiento de Aguas Residuales"),
        P("gestion", "Municipio sin papel, portal de transparencia en tiempo real y rendición de cuentas trimestral", 12, "Rendición de cuentas trimestral", "50 % de trámites digitales al 2030"),
    ]),
    ("Joel José Núñez Mendoza", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Programa «Ate Seguro 360°»: cámaras inteligentes con analítica de video, central integrada de monitoreo, botones de pánico y patrullaje integrado", 10, "Cámaras inteligentes con analítica de video"),
        P("gestion", "Atención al vecino con inteligencia artificial generativa, chat municipal 24 horas y expediente electrónico", 33, "Chat municipal inteligente 24 horas"),
        P("gestion", "Informes semestrales y anuales de cumplimiento del plan y audiencias públicas en todas las zonas", 42, "informes semestrales y anuales"),
        P("social", "Casa del Adulto Mayor con talleres, alfabetización digital, actividad física y atención psicológica", 13, "CASA DEL ADULTO MAYOR Objetivo Promover el envejecimiento activo"),
        P("social", "Programa «Ate te Cuida» de salud preventiva, salud mental comunitaria y prevención de la anemia", 17, "Salud mental comunitaria"),
        P("ambiente", "Programa «Ate Animal» con campañas veterinarias, esterilización, adopción y registro municipal de mascotas", 14, "Registro municipal de mascotas"),
        P("ambiente", "«Ate Limpio 24/7»: eliminación de puntos críticos de basura, rutas de limpieza optimizadas y fiscalización ambiental", 27, "Eliminación de puntos críticos"),
        P("economia", "Marca «Hecho en Ate», marketplace digital «Compra en Ate», expoferias y Festival Anual del Emprendimiento", 20, "Marketplace Digital Compra en Ate"),
        P("economia", "Academia Municipal de Oficios: computación, electricidad, construcción, logística y marketing digital", 23, "ACADEMIA MUNICIPAL DE OFICIOS Objetivo Fortalecer"),
        P("urbano", "Programa «Ate con Título» de formalización predial mediante convenios con COFOPRI", 28, "Convenios con COFOPRI"),
        P("urbano", "Programa «Mi Barrio»: veredas, escaleras, muros de contención, espacios deportivos e iluminación", 30, "Iluminación pública complementaria"),
    ]),
    ("José Luis Hurtado Apaico", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Centro C5 Ate Seguro con monitoreo 24/7, cámaras con IA, lectura de placas y drones en Huaycán, Santa Clara, Vitarte, Ceres y Salamanca", 30, "PROYECTO EMBLEMÁTICO: C5 ATE SEGURO", "2 000 cámaras inteligentes"),
        P("seguridad", "«Serenazgo de Élite»: Escuela Municipal de Serenos, capacitación y equipamiento con chalecos, cámaras corporales y radios", 32, "SERENAZGO DE ÉLITE ATE", "100 % del personal certificado"),
        P("transporte", "Formalizar los mototaxis con registro digital, código QR, GPS y una Escuela Municipal del Mototaxista", 39, "Escuela Municipal del Mototaxista", "100 % de asociaciones de mototaxis formalizadas"),
        P("urbano", "Programa «Recupera Ate» de parques, bermas y espacios tomados por la informalidad", 44, "PROYECTO EMBLEMÁTICO: RECUPERA ATE", "150 espacios públicos recuperados"),
        P("urbano", "Plan de pistas y veredas con pavimentación, recapeo y veredas accesibles", 47, "PLAN DE PISTAS Y VEREDAS", "300 cuadras intervenidas"),
        P("ambiente", "«Ate Verde 2030»: arborización y corredores verdes en Carretera Central, Javier Prado, Separadora Industrial y Nicolás Ayllón", 60, "Incrementar en más del 50% las áreas verdes urbanas", "50 000 árboles y más de 50 % de áreas verdes urbanas durante la gestión"),
        P("agua_riesgos", "Programa «Ate Preparado» con simulacros, brigadas comunitarias y planes familiares de emergencia", 84, "Capacitar a 100,000 vecinos", "100 000 vecinos capacitados"),
        P("economia", "Programa «Formaliza Ate» con ventanilla única empresarial, licencias rápidas y asesoría gratuita", 54, "PROYECTO: FORMALIZA ATE", "15 000 negocios formalizados"),
        P("social", "Programa «Salud Cerca de Ti» de campañas médicas, salud mental y nutrición en coordinación con el Minsa y EsSalud", 68, "SALUD CERCA DE TI", "100 000 atenciones preventivas"),
        P("social", "Casa del Adulto Mayor con actividades recreativas, atención psicológica, terapia física y asesoría legal", 69, "15,000 adultos mayores beneficiados", "15 000 adultos mayores beneficiados"),
        P("gestion", "«Municipalidad Digital 100 %»: mesa de partes virtual, licencias en línea, pagos virtuales y seguimiento de expedientes", 74, "MUNICIPALIDAD DIGITAL 100%", "80 % de trámites municipales digitalizados"),
    ]),
    ("Edde Cuellar Alegría", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Sistema Inteligente de Seguridad con cámaras de reconocimiento facial, monitoreo en tiempo real, patrullaje integrado y alertas ciudadanas", 4, "Sistema Inteligente de Seguridad", "Reducir en 30 % las denuncias por delincuencia y violencia social al 2030"),
        P("social", "Centros descentralizados de atención psicológica municipal y más atención en salud mental comunitaria", 8, "implementar 04 centros descentralizados de atención psicológica", "4 centros y el doble de atención en salud mental"),
        P("social", "Clínicas móviles municipales en zonas vulnerables, con énfasis en la anemia infantil", 4, "clínicas móviles municipales", "Reducir en 50 % la anemia infantil al 2030"),
        P("ambiente", "Registro de mascotas, campañas veterinarias y un programa permanente de bienestar animal", 9, "Lograr el registro de al menos 50% de animales domésticos", "Registro de al menos 50 % de animales domésticos y el doble de campañas veterinarias"),
        P("economia", "Bolsa de trabajo municipal digital para conectar a jóvenes con empleo formal", 11, "colocación laboral formal juvenil mediante la Bolsa de Trabajo Municipal", "Duplicar la colocación laboral formal juvenil respecto al 2026"),
        P("economia", "Ordenamiento y formalización progresiva del comercio ambulatorio", 12, "Incorporar al 80% de comerciantes informales", "80 % de comerciantes informales en formalización y 100 % de zonas críticas ordenadas"),
        P("transporte", "Intervenir los puntos críticos de congestión y semaforizar intersecciones de forma inteligente", 14, "Reducir en 40% los niveles de congestión", "Reducir en 40 % la congestión e intervenir el 100 % de puntos críticos"),
        P("ambiente", "Programa de segregación en la fuente y monitoreo de la calidad del aire", 14, "Programa de Segregación en la Fuente", "50 % de viviendas en segregación y 30 % menos contaminación del aire"),
        P("agua_riesgos", "Intervenir zonas críticas de riesgo, capacitar a organizaciones vecinales y evitar nuevas ocupaciones en zonas de alto riesgo", 15, "Lograr 0 % de nuevas ocupaciones en zonas de alto riesgo", "100 % de zonas críticas intervenidas y 0 % de nuevas ocupaciones en zonas de alto riesgo"),
        P("urbano", "Plan anual de mantenimiento urbano y recuperación de espacios públicos priorizados", 15, "Recuperar el 100% de espacios públicos priorizados", "100 % de espacios públicos priorizados recuperados"),
        P("gestion", "Gobierno digital con digitalización de trámites y plataforma única de atención al ciudadano", 17, "Digitalizar 80% de tramites", "80 % de trámites digitales y 70 % menos tiempo de atención"),
    ]),
    ("Mel Ian Vilcahuaman Medrano", "Progresemos", "progresemos", [
        P("seguridad", "Central Integrada de Seguridad Ciudadana de Ate articulada con la PNP, el serenazgo y las juntas vecinales", 28, "Implementar una Central Integrada de Seguridad Ciudadana de Ate"),
        P("seguridad", "Más cámaras de videovigilancia en puntos estratégicos y patrullaje integrado entre serenazgo y PNP", 28, "Incrementar progresivamente el sistema de videovigilancia"),
        P("social", "Fortalecer los programas de apoyo alimentario, comedores populares y ollas comunes", 29, "comedores populares, ollas comunes"),
        P("social", "Centro Municipal de Orientación Psicológica de Ate y campañas de salud mental comunitaria", 29, "Centro Municipal de Orientación Psicológica de Ate"),
        P("economia", "Programa «Ate Emprende» con capacitación para MYPES, ferias productivas y asesoría para la formalización", 30, "orientado al fortalecimiento de emprendedores locales"),
        P("ambiente", "Campañas permanentes de reciclaje y segregación, y mejora de la limpieza pública", 31, "campañas permanentes de reciclaje y segregación"),
        P("ambiente", "Protección animal con esterilización, vacunación, tenencia responsable y atención veterinaria comunitaria", 31, "Atención veterinaria comunitaria"),
        P("urbano", "Mejorar pistas y veredas y recuperar vías principales y calles vecinales", 31, "Recuperación de vías principales y calles vecinales"),
        P("transporte", "Promover un transporte público ordenado y mejorar la señalización y la seguridad vial", 31, "Mejoramiento de señalización y seguridad vial"),
        P("agua_riesgos", "Obras de prevención en zonas vulnerables e identificación de zonas de riesgo", 31, "Gestión de obras de prevención en zonas vulnerables"),
        P("gestion", "Transparencia en el uso de recursos y ejecución de obras, y rendición periódica de cuentas", 31, "Transparencia en el uso de recursos públicos y ejecución de obras"),
    ]),
    ("Elizabeth Nancy Cabezas Flores", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Ampliar la videovigilancia inteligente e integrar las cámaras municipales, de empresas y de vecinos a la central de monitoreo", 37, "Integrar 3 000 cámaras de videovigilancia públicas y privadas", "3 000 cámaras integradas a la central de monitoreo"),
        P("urbano", "Oficina especializada en saneamiento físico legal y titulación de predios", 28, "oficina especializada en saneamiento físico legal y titulación"),
        P("social", "Campañas de tamizaje, controles y suplementos con hierro contra la anemia en menores de 3 años", 38, "Reducir la prevalencia de anemia infantil por debajo del 10", "Anemia infantil por debajo de 10 %"),
        P("social", "Becas y medias becas para jóvenes de escasos recursos y fortalecimiento de la academia preuniversitaria municipal", 38, "400 alumnos de escasos recursos beneficiados con becas", "400 becas y medias becas; 40 % de ingresantes de la academia"),
        P("economia", "Centro Municipal de Empleabilidad Juvenil y programa «Mi Primera Chamba» con ferias laborales", 40, "10 000 jóvenes insertados en empleos", "10 000 jóvenes insertados en empleos"),
        P("economia", "Licencia de funcionamiento exprés y plataforma virtual única para licencias, certificados y permisos de Defensa Civil", 31, "Licencia Express en 48 Horas", "Licencia en 48 horas"),
        P("transporte", "Empadronar, capacitar y fiscalizar a los mototaxistas para formalizar el transporte menor", 40, "95% de las organizaciones autorizadas de mototaxistas", "95 % de organizaciones de mototaxis en regla y 10 000 mototaxistas capacitados"),
        P("ambiente", "Comprar una flota propia de camiones compactadores y reordenar las rutas de recolección en las 7 zonas", 41, "30 camiones compactadoras recolectoras", "30 camiones y 100 % de cobertura de recolección"),
        P("ambiente", "Plan de Arborización Urbana con especies de bajo consumo de agua en bermas de avenidas, la faja marginal del Rímac y laderas", 32, "la faja marginal del río Rímac", "De 3,16 a 4,50 m² de áreas verdes por habitante al 2030"),
        P("agua_riesgos", "Evaluaciones de vulnerabilidad estructural en viviendas sobre taludes inestables y asistencia técnica en construcción segura", 42, "2 500 evaluaciones técnicas / catastrales", "2 500 evaluaciones de vulnerabilidad"),
        P("gestion", "Semáforo de riesgo de corrupción con IA en las compras y registro en blockchain de los contratos mayores a S/ 50 000", 36, "semáforo de Riesgo ante Corrupción"),
    ]),
    ("Rodolfo Roiro Padilla", "Salvemos al Perú", "salvemos-al-peru", [
        P("seguridad", "Vigilancia predictiva con IA (reconocimiento de placas y rostros) y más bases y unidades móviles de serenazgo", 7, "500 nuevas cámaras con IA", "500 nuevas cámaras con IA y 60 unidades móviles"),
        P("social", "Red de policlínicos municipales itinerantes de salud preventiva", 7, "Policlínicos Municipales itinerantes", "100 000 atenciones médicas al año y 50 % menos anemia infantil en sectores intervenidos"),
        P("social", "«Escuelas Municipales del Deporte y la Innovación» y centros culturales gratuitos", 7, "Escuelas Municipales del Deporte y la Innovación", "20 000 niños y jóvenes al año"),
        P("social", "Equipar y capacitar a los comedores populares y comités de Vaso de Leche", 8, "Atender, reequipar y capacitar al 100% de los Comedores Populares", "100 % de comedores y comités registrados atendidos"),
        P("economia", "Bolsa Municipal de Trabajo articulada con las empresas", 8, "Bolsa Municipal de Trabajo articulada", "5 000 vecinos insertados en empleo formal por año"),
        P("economia", "Actualizar el TUPA y otorgar licencias de funcionamiento exprés por canales digitales", 9, "máximo de 24 horas hábiles", "Licencias en máximo 24 horas hábiles para riesgo bajo y medio"),
        P("ambiente", "Arborización masiva y recuperación de parques regados con aguas residuales tratadas", 10, "utilizando aguas residuales tratadas para su riego", "30 % más superficie de áreas verdes urbanas"),
        P("ambiente", "Segregación en la fuente, reciclaje y educación ambiental para vecinos, escuelas y comercios", 10, "Incrementar a 500 toneladas mensuales", "500 toneladas mensuales de material reciclable"),
        P("transporte", "Empadronamiento digital, zonificación y control biométrico de los mototaxis", 11, "control biométrico y asignación de zonas autorizadas", "100 % de mototaxis formalizados y con control biométrico"),
        P("gestion", "Control concurrente con la Contraloría en obras públicas y contrataciones, con publicación abierta", 11, "contrataciones mayores a las 8 UIT", "100 % de obras y contrataciones mayores a 8 UIT auditadas"),
        P("gestion", "Repotenciar las agencias municipales descentralizadas con ventanillas únicas y plataformas digitales", 12, "6 agencias municipales descentralizadas", "6 agencias repotenciadas"),
    ]),
    ("Netzer Alemao Chávez Flores", "Visión Perú", "vision-peru", [
        P("seguridad", "Comités distritales de seguridad ciudadana con vecinos, autoridades locales y la PNP", 2, "Crear comités distritales de seguridad ciudadana"),
        P("seguridad", "Capacitar al serenazgo con enfoque comunitario y respeto a los derechos humanos", 2, "Fortalecer la capacitación de serenazgo"),
        P("gestion", "Observatorios distritales de justicia y transparencia para vigilar la gestión municipal", 2, "observatorios distritales de justicia y transparencia"),
        P("economia", "Ferias de empleo distritales y capacitación técnica para jóvenes", 2, "Promover ferias de empleo distritales"),
        P("economia", "Polos de desarrollo económico: mercados, centros de innovación y pequeños parques industriales", 2, "Crear polos de desarrollo económico distrital"),
        P("social", "Programas de prevención del delito en colegios y actividades culturales y deportivas para jóvenes", 2, "programas de prevención del delito en colegios"),
        P("social", "Centros distritales de reinserción social para jóvenes en riesgo, con talleres de oficios y apoyo psicológico", 2, "centros distritales de reinserción social"),
        P("ambiente", "Brigadas ambientales contra la tala ilegal, la contaminación y el mal manejo de residuos", 2, "brigadas ambientales distritales"),
        P("ambiente", "Reciclaje y economía circular en mercados y barrios", 2, "economía circular en mercados y barrios"),
        P("urbano", "Espacios verdes seguros, como parques y jardines comunitarios, para mejorar la convivencia", 2, "Crear espacios verdes seguros"),
        P("gestion", "Informes trimestrales de avance, audiencias públicas y portal de transparencia actualizado cada mes", 3, "Informes trimestrales Publicar cada tres meses", "Informes trimestrales y al menos dos audiencias públicas al año"),
    ]),
]
