"""Los Olivos (150117): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150117"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Franco Enrique Cortez Gutiérrez", "Acción Popular", "accion-popular", [
        P("seguridad", "Programa «Los Olivos Seguro»: red de cámaras inteligentes, central de monitoreo con inteligencia artificial, cámaras corporales para serenos y aplicativo «Alerta Olivos»", 3, "Implementación progresiva de una red de hasta 1,000 cámaras", "1 000 cámaras operativas y 40 % menos delitos de mayor incidencia"),
        P("seguridad", "Escuela Municipal de Serenazgo, patrullaje integrado con la PNP y fortalecimiento de las juntas vecinales", 3, "Implementación de la Escuela Municipal de Serenazgo", "Al menos 150 juntas vecinales fortalecidas"),
        P("social", "Programa «Los Olivos Cuida a su Gente»: campañas médicas descentralizadas, atención psicológica comunitaria y apoyo a personas con discapacidad", 4, "Los Olivos Cuida a su Gente", "Al menos 200 campañas médicas descentralizadas"),
        P("social", "Programa «Generación Los Olivos»: preuniversitaria municipal gratuita, Centro de Innovación y Tecnología Juvenil y becas de capacitación técnica", 5, "Implementación de la PRE Municipal gratuita", "Más de 20 000 jóvenes beneficiados"),
        P("urbano", "Primer skatepark municipal, recuperación de losas deportivas y mini gimnasios al aire libre", 6, "Recuperar y modernizar 50 espacios deportivos", "50 espacios deportivos y recreativos recuperados"),
        P("economia", "Programa «Los Olivos Trabaja»: bolsa laboral permanente, ferias laborales descentralizadas y programa «Mi Primer Empleo»", 7, "Facilitar la inserción laboral de al menos 8,000", "8 000 vecinos insertados laboralmente y 40 ferias laborales"),
        P("economia", "Programa «Emprende Los Olivos»: centro de emprendimiento, escuela de negocios, digitalización de mypes y ferias productivas", 8, "Formalizar 3,000 negocios", "10 000 emprendedores capacitados y 3 000 negocios formalizados"),
        P("economia", "«Licencia Express Los Olivos»: ventanilla única empresarial digital y simplificación de licencias de funcionamiento", 9, "Licencia Express Los Olivos", "50 % menos tiempo de atención y 80 % de procedimientos empresariales digitalizados"),
        P("ambiente", "Gestión integral de residuos con reciclaje y segregación en las viviendas", 13, "Incrementar en 50% el reciclaje distrital", "50 % más de reciclaje y 30 000 viviendas en programas de segregación"),
        P("ambiente", "Arborización, recuperación de áreas verdes y modernización de parques", 14, "Plantar 20,000 árboles", "20 000 árboles, 100 000 m² de áreas verdes recuperadas y 80 parques modernizados"),
        P("gestion", "Digitalización de trámites municipales y transmisión de las sesiones del Concejo", 14, "Digitalizar el 90% de los", "90 % de trámites digitalizados y 100 % de sesiones de Concejo transmitidas"),
    ]),
    ("Lucio Hernán Cabello Morales", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "«Ojos de Águila»: nuevas cámaras con reconocimiento facial y lectura de placas en los accesos al distrito, y convenio con la UNI para drones", 5, "Sistema Integrado de Ojos de Águila", "300 nuevas cámaras"),
        P("seguridad", "Serenazgo por cuadrantes vecinales con pruebas de confianza y convenios «Serenazgo Sin Fronteras» con distritos vecinos y el Callao", 6, "Serenazgo Sin Fronteras", "300 agentes de serenazgo"),
        P("transporte", "Gestionar ante Lima y el MTC semaforización inteligente y rediseño de puntos críticos en Carlos Izaguirre, Huandoy, Naranjal y Las Palmeras", 7, "rediseño geométrico de los puntos críticos"),
        P("urbano", "Programa «Pavimento Total» de asfaltado de vías colectoras e internas", 7, "Pavimento Total", "30 km de vías"),
        P("agua_riesgos", "Muros de contención en laderas de alto riesgo y escaleras con pasamanos e iluminación solar en zonas altas", 7, "Escaleras y Muros de Contención para las Laderas"),
        P("social", "«Los Olivos Sin Anemia ni Desnutrición»: promotoras de salud que hacen tamizaje casa por casa a menores de 3 años y entregan suplementos de hierro", 8, "Los Olivos Sin Anemia ni Desnutrición", "Reducir a la mitad la anemia infantil al 2031"),
        P("social", "Policlínico municipal de atención rápida con tarifas sociales y primer Centro de Atención Psicológica Municipal", 8, "Policlínico Municipal de atención rápida", "1 policlínico municipal"),
        P("ambiente", "Fiscalizar el arrojo de desmonte en la ribera del río Chillón y reforestar con especies nativas regadas con agua tratada", 9, "sembrando 10,000 árboles", "10 000 árboles"),
        P("ambiente", "«Los Olivos Recicla»: rutas de recojo con GPS público, recicladores formalizados y descuentos en arbitrios por segregar («Bono Ecológico Vecinal»)", 9, "Bono Ecológico Vecinal", "3 asociaciones de recicladores incorporadas"),
        P("economia", "Ventanilla Única del Emprendedor con licencias y certificados ITSE virtuales para comercios de riesgo bajo y medio", 10, "Formalización Fácil y Licencias en 24 Horas", "Licencias en un plazo máximo de 24 horas"),
        P("gestion", "Portal «Transparencia 360» con consulta en tiempo real de obras, licitaciones, planillas y gastos del alcalde y regidores", 11, "Plataforma Transparencia 360", "Al menos 2 audiencias públicas al año"),
    ]),
    ("José Aníbal López Gonzales", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Cámaras de videovigilancia con inteligencia artificial y vinculación de cámaras privadas a la central municipal", 23, "Instalar 300 cámaras de video vigilancia con inteligencia artificial", "300 cámaras con IA y 200 cámaras privadas vinculadas al 2030"),
        P("seguridad", "Patrullaje con vehículos asignados por sectores y formación de juntas vecinales de seguridad", 23, "Formar y consolidar 100 Juntas Vecinales", "14 vehículos por sectores y 100 juntas vecinales al 2030"),
        P("social", "Convenios educativos con universidades, institutos y empresas para becas y descuentos a egresados de colegios públicos", 25, "Suscribir al menos 20 convenios educativos", "20 convenios y becas o descuentos para el 30 % de egresados de colegios públicos"),
        P("social", "Reapertura y fortalecimiento del Hospital Municipal con más especialidades y campañas de salud", 26, "Reapertura y fortalecimiento del Hospital Municipal", "15 especialidades y 60 % menos tiempo de espera para citas"),
        P("economia", "Programa «Amigo Emprendedor» de capacitación y certificación en gestión, marketing digital y finanzas", 28, "en gestión empresarial, marketing digital y finanzas básicas", "5 000 emprendedores capacitados y certificados"),
        P("economia", "Plan de formalización de negocios informales del distrito", 28, "Alcanzar la formalización del 50 %", "50 % de los negocios informales identificados formalizados"),
        P("economia", "Ferias y circuitos comerciales «Siempre cerca, Los Olivos» para emprendedores locales", 28, "Lograr ventas acumuladas por al menos", "S/ 20 millones en ventas acumuladas entre 2027 y 2030"),
        P("ambiente", "Programas de segregación y reciclaje para mejorar la limpieza pública", 29, "Programas de segregación y reciclaje", "30 % de reciclaje distrital al 2026"),
        P("ambiente", "Campaña «Ola Verde» de recuperación de áreas verdes", 29, "Incrementar en 40% las áreas verdes del distrito", "40 % más de áreas verdes"),
        P("gestion", "Plataforma virtual «Cero Papeles» para trámites municipales", 30, "Digitalizar el 90% de los trámites municipales", "90 % de trámites digitalizados"),
        P("gestion", "Audiencias públicas y reportes de gestión para la rendición de cuentas", 30, "Realizar 2 audiencias públicas anuales", "2 audiencias públicas al año y reportes trimestrales"),
    ]),
    ("Felipe Baldomero Castillo Alfaro", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Plan «Los Olivos Seguro»: cámaras con reconocimiento facial en sectores de alta peligrosidad, Escuela Distrital de Serenazgo y programa «Cuadrante Seguro»", 7, "Instalación de 300 cámaras de videovigilancia con reconocimiento facial", "300 cámaras"),
        P("social", "Programa «Salud para Todos»: recuperar convenios con EsSalud para policlínicos y mejorar centros de salud del primer nivel", 7, "Recuperación de 3 convenios con EsSalud", "3 convenios con EsSalud y 3 centros de salud mejorados"),
        P("social", "Equipar losas deportivas con césped sintético y crear guarderías municipales", 8, "Creación de 3 guarderías municipales", "3 guarderías y 5 losas deportivas equipadas por año"),
        P("agua_riesgos", "Proyectos de agua y alcantarillado en asentamientos humanos, en coordinación con el Ministerio de Vivienda", 8, "Ejecución de 3 proyectos de saneamiento de agua y alcantarillado", "3 proyectos de saneamiento"),
        P("urbano", "Alumbrado público LED en todo el distrito, en coordinación con ENEL", 8, "iluminación LED en el 100% del distrito", "100 % del distrito con alumbrado LED"),
        P("transporte", "Gestionar ante el MTC y Lima el bypass Trapiche–Universitaria y un túnel peatonal en la Panamericana Norte a la altura de Plaza Norte", 8, "Corredor Vial / Bypass en el tramo"),
        P("transporte", "Ciclovías en avenidas principales y auxiliares, y educación vial por ordenanza", 10, "Implementación de 10 proyectos de ciclovías", "10 proyectos de ciclovías"),
        P("economia", "Programa «Los Olivos Emprende»: plataforma virtual de negocios y centros descentralizados de servicios municipales", 9, "Creación de 2 centros descentralizados", "Plataforma al 100 % y 2 centros descentralizados"),
        P("ambiente", "Recojo diario de residuos en todo el distrito y segregación en la fuente con organizaciones vecinales", 9, "Recojo diario de residuos sólidos al 100% del distrito", "Recojo diario en el 100 % del distrito"),
        P("ambiente", "Arborización de avenidas, parques y bermas y reactivación del vivero municipal", 10, "Reactivación al 100% del vivero municipal", "5 m² de área verde por habitante"),
        P("gestion", "Digitalizar la información pública municipal e implementar la norma antisoborno ISO 37001", 10, "Norma ISO 37001 anti-corrupción", "ISO 37001 implementada al 100 %"),
    ]),
    ("Jorge Luis Salinas Paredes", "Coalición Transformadora Tierra Verde", "coalicion-transformadora-tierra-verde", [
        P("seguridad", "Seguridad por cuadrantes en 5 macrozonas y patrullajes conjuntos «Serenazgo Sin Fronteras» con distritos vecinos de Lima Norte", 54, "sectorizando el distrito en 5 macro-zonas", "Victimización por robo y hurto de 32,4 % a 11,2 % al 2030"),
        P("seguridad", "«Academia del Sereno de Lima Norte» y equipamiento de las juntas vecinales con radios y alarmas conectadas a aplicativos", 54, "Academia del Sereno de Lima Norte", "Tiempo de respuesta de 11 a 4 minutos al 2030"),
        P("gestion", "Plataforma «Los Olivos Digital» con todos los trámites del TUPA en línea", 55, "migrando el 100% de los trámites del TUPA", "100 % de trámites resueltos digitalmente al 2030"),
        P("social", "Centros Municipales de Salud Mental Familiar en zonas periféricas y campañas de tamizaje de anemia", 56, "Centros Municipales de Salud Mental Familiar", "Anemia infantil en sectores focalizados de 38,5 % a 12 % al 2030"),
        P("economia", "Programa «Emprende Los Olivos» de talleres certificados en habilidades tecnológicas y oficios con institutos y universidades", 56, "brindar talleres certificados de habilidades tecnológicas", "3 500 jóvenes y madres certificados al año al 2030"),
        P("transporte", "Empadronamiento digital con código QR de mototaxis y registro distrital de repartidores en moto con zonas de estacionamiento", 58, "Registro Distrital de Repartidores en Motocicleta", "100 % de mototaxis formalizados con control GPS al 2030"),
        P("transporte", "Semáforos inteligentes que ajustan sus tiempos según el tránsito, y ciclovías segregadas en Carlos Izaguirre y Universitaria", 58, "semáforos inteligentes que adapten sus tiempos", "25 % menos tiempo de demora en intersecciones críticas"),
        P("urbano", "Actualizar el Plan de Desarrollo Urbano alineado al PLANMET 2040 y proteger e iluminar las huacas del distrito con el Ministerio de Cultura", 59, "alineado con el PLANMET 2040", "5 sitios arqueológicos protegidos al 2030"),
        P("ambiente", "Contenedores soterrados diferenciados en avenidas comerciales y segregación en la fuente con recicladores formales", 60, "contenedores soterrados y superficiales diferenciados", "45 % de residuos inorgánicos reciclados al 2030"),
        P("ambiente", "Arborización de Universitaria y Panamericana Norte y riego nocturno con agua residual tratada en lugar de cisternas", 61, "sustituyendo gradualmente el uso de camiones cisterna", "De 2,8 a 7,5 m² de área verde por habitante al 2030"),
        P("agua_riesgos", "Centro de Alerta Temprana Distrital con sirenas conectadas al SISMATE y brigadas vecinales de Defensa Civil", 61, "Centro de Alerta Temprana Distrital", "Despliegue ante emergencias de 14 a 5 minutos al 2030"),
    ]),
    ("Tony Elbert Rojas Espinoza", "Cooperación, Verdad y Honradez", "cooperacion-verdad-y-honradez", [
        P("seguridad", "Centro Inteligente de Seguridad Ciudadana, Observatorio Municipal del Delito y botón de pánico municipal", 15, "Implementación del Centro Inteligente de Seguridad Ciudadana", "30 % menos delitos contra el patrimonio durante la gestión"),
        P("seguridad", "Corredores seguros en Las Palmeras, Huandoy, Central, Universitaria, Antúnez de Mayolo, Carlos Izaguirre y Alfredo Mendiola, y recuperación de zonas críticas", 15, "Programa Corredores Seguros de Los Olivos", "50 espacios públicos inseguros recuperados"),
        P("social", "Modernización del Hospital Municipal, farmacia municipal solidaria y programa «Médico en tu Barrio»", 16, "Programa Farmacia Municipal Solidaria", "Más de 100 000 atenciones médicas"),
        P("social", "Historia clínica digital única, programa «Cero Colas» y consultorio municipal en horario extendido", 16, "Historia Clínica digital única"),
        P("economia", "Centro Municipal del Emprendimiento Olivense, escuela de negocios, bolsa de trabajo y formalización progresiva de mypes", 16, "Centro Municipal del Emprendimiento Olivense", "Más de 10 000 oportunidades de empleo y capacitación"),
        P("social", "Becas municipales, Academia Municipal de Tecnología e Innovación y capacitación en inteligencia artificial", 17, "Academia Municipal de Tecnología e Innovación", "Más de 20 000 jóvenes capacitados y 5 000 con oportunidades laborales"),
        P("transporte", "Plan integral de movilidad: reordenamiento de paraderos, formalización de mototaxis y semaforización inteligente", 18, "Formalización y regulación de mototaxis"),
        P("economia", "Reordenamiento concertado del comercio ambulatorio y mesa de diálogo con comerciantes formales e informales", 18, "Reordenamiento concertado del comercio ambulatorio"),
        P("ambiente", "Programa «Vecino Reciclador», brigadas ambientales juveniles y modernización de la recolección de residuos", 18, "Programa Vecino Reciclador"),
        P("urbano", "Programas «100 Parques Recuperados», «Veredas Seguras» y «Pistas para tu Barrio»", 18, "Programa 100 Parques Recuperados", "100 parques recuperados y 50 km de veredas mejoradas"),
        P("gestion", "Publicación mensual de gastos y contrataciones, portal de obras en tiempo real y declaración jurada pública de funcionarios", 19, "Publicación mensual de gastos y contrataciones", "Digitalización del 100 % de trámites prioritarios"),
    ]),
    ("Fernando Lurjo Sudario Céspedes", "Fe en el Perú", "fe-en-el-peru", [
        P("seguridad", "Mapa del delito por sectores y horarios, central de monitoreo 24/7, cámaras en puntos críticos y patrullaje por cuadrantes", 37, "Mapa distrital del delito por sectores y horarios", "100 % de puntos críticos priorizados con intervención"),
        P("seguridad", "Censo distrital de población extranjera para planificar seguridad, integración, fiscalización y servicios", 25, "Censo distrital de población extranjera y control urbano"),
        P("social", "Convertir progresivamente el hospital municipal en centro de prevención y descarte temprano de cáncer, diabetes e hipertensión", 26, "Hospital Oncológico Preventivo y Enfermedades Crónicas"),
        P("social", "Programa de nutrición, vida saludable y deporte comunitario con talleres familiares, huertos urbanos y escuelas deportivas", 27, "Programa Nutrición, Vida Saludable y Deporte Comunitario"),
        P("social", "Convenios con universidades, laboratorios municipales de programación, robótica e IA y bolsa de prácticas", 47, "Laboratorios municipales de programación, robótica e IA", "100 convenios educativos y 20 000 estudiantes beneficiados"),
        P("economia", "Estudio de viabilidad de un boulevard gastronómico en tramos y horarios de la Av. Carlos Izaguirre", 28, "activar la Av. Carlos Izaguirre en tramos y horarios"),
        P("economia", "Modernización gradual de mercados con cámaras de frío, almacenes, zonas de carga y trazabilidad de productos", 29, "de la chacra y del mar a la olla"),
        P("economia", "Centro Municipal de Innovación y Emprendimiento con asesoría para financiamiento, registro de marcas y patentes", 46, "5,000 emprendedores capacitados", "5 000 emprendedores capacitados, 1 000 negocios formalizados y 500 registros de marca"),
        P("ambiente", "Modelo para separar, reciclar y valorizar residuos con recicladores formalizados y puntos limpios", 31, "Planta de Valorización de Residuos y Reciclaje Rentable"),
        P("urbano", "Renovación progresiva a luminarias LED en zonas oscuras y pilotos de energía solar", 32, "Iluminación Total, LED y Energía Solar"),
        P("gestion", "Trámites digitales, pagos en línea, mesa de partes virtual y perfiles técnicos para los funcionarios", 33, "Municipalidad Digital y Meritocrática"),
    ]),
    ("Julián Ramos Méndez", "Fuerza Popular", "fuerza-popular", [
        P("economia", "Festivales del empleo y bolsa de trabajo «Muni-chamba» para jóvenes y adultos", 4, "Organizar Festivales del Empleo en el Distrito"),
        P("economia", "Módulo de atención de servicios múltiples (MAC) y programa de modernización de mercados", 4, "Programa de promoción y modernización de los mercados del distrito"),
        P("economia", "Formalización, registro y ordenamiento de los comerciantes informales de la vía pública", 4, "formalización, registro y ordenamiento de los comerciantes informales"),
        P("urbano", "Rehabilitación y mantenimiento de pistas y veredas en todo el distrito", 5, "Rehabilitación total de pistas y veredas en el distrito"),
        P("urbano", "Actualizar el Plan de Desarrollo Urbano y la zonificación, y remodelar la Plaza de Armas", 5, "Actualizar el Plan de Desarrollo Urbano y la zonificacion"),
        P("ambiente", "Programa de reciclaje y segregación de residuos con registro y capacitación de recicladores", 5, "Registro y Capacitación a Recicladores"),
        P("ambiente", "Arborización de las zonas con mayor contaminación del aire, riego tecnificado y surtidores con atrapanieblas en zonas deportivas", 5, "Arborización de las zonas con mayor contaminación atmosférica"),
        P("transporte", "Semáforos con inteligencia artificial y ampliación de ciclovías conectadas al transporte urbano", 5, "aplicando inteligencia artificial"),
        P("transporte", "Estacionamientos subterráneos por iniciativa privada y estacionamientos para transporte escolar", 5, "Iniciativa privada para la construcción de estacionamiento subterráneo"),
        P("social", "Programa de inserción social de vecinos con discapacidad y módulos de negocios para la OMAPED", 6, "Formulación de módulos de negocios para la OMAPED"),
        P("social", "Biblioteca infantil y lúdica, física y virtual", 6, "Biblioteca infantil y lúdica"),
    ]),
    ("Heidelberger Willians Davis Suyon Díaz", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Escuadrón de drones del serenazgo para monitorear en tiempo real y apoyar búsqueda y rescate", 20, "ESCUADRÓN DE DRONES"),
        P("seguridad", "Cámaras con inteligencia artificial y reconocimiento facial y vehicular en cámaras y semáforos, con botón de pánico", 21, "reconocimiento facial y vehicular en semáforos inteligentes"),
        P("seguridad", "Patrullaje integrado de serenazgo y PNP en las 28 zonas del distrito, coordinado con las tres comisarías", 22, "patrullaje integrado en las 28 zonas del distrito", "Tres turnos diarios de 8 horas, los 365 días del año"),
        P("ambiente", "Planta de tratamiento de aguas residuales para regar parques y jardines del distrito", 26, "PARA EL REGADÍO DE PARQUES Y JARDINES DEL DISTRITO"),
        P("agua_riesgos", "Almacenes de emergencia soterrados y en contenedores en parques, para cubrir las primeras 72 horas tras un desastre", 29, "las primeras 72 horas post-desastre"),
        P("social", "Centro de salud mental comunitario mediante convenio con el Instituto Nacional de Salud Mental Honorio Delgado-Hideyo Noguchi", 33, "IMPLEMENTAR UN CENTRO DE SALUD MENTAL COMUNITARIO"),
        P("social", "Programa «Cero Anemia» con tamizaje gratuito de hemoglobina a niños de 0 a 5 años y gestantes en colegios y Vaso de Leche", 35, "tamizaje de hemoglobina"),
        P("transporte", "Semaforización inteligente con «ola verde» y controladores de velocidad para reducir accidentes", 40, "implementar el sistema de ola verde"),
        P("economia", "Centro de Emprendimiento Municipal con coworking y asesoría legal gratuita para constituir empresas", 52, "Coworking Municipal y Asesoría legal", "Formalizar al 8,5 % del público objetivo en el primer año"),
        P("urbano", "Construcción y mantenimiento de escaleras en las zonas altas de los asentamientos humanos", 63, "ESCALERAS EN LAS ZONAS ALTAS DE LOS ASENTAMIENTOS"),
        P("gestion", "Aplicativo de trámites municipales para pagar arbitrios y acceder a descuentos desde el celular", 45, "APP de trámites municipales"),
    ]),
    ("Ángel Solís Vergaray", "Libertad Popular", "libertad-popular", [
        P("seguridad", "Cámaras 4K con inteligencia artificial que detectan patrones delictivos y reconocen rostros y placas con la base de requisitorias de la PNP", 6, "Ecosistema de Cámaras Inteligentes 4K con IA", "Respuesta en menos de 5 minutos y 30 % menos delitos contra el patrimonio al 2030"),
        P("urbano", "Bacheo y repavimentación, veredas con materiales permeables e iluminación LED en zonas críticas", 7, "Pavimentación y Renovación Urbana Sostenible", "90 % de la red vial interna recuperada al 2030"),
        P("transporte", "Estacionamientos subterráneos en nudos comerciales y plazas para liberar la superficie al peatón", 7, "Plan Maestro de Cocheras Subterráneas", "De 250 a 800 plazas por estacionamiento"),
        P("transporte", "Ciclovías segregadas para bicicletas y scooters y paraderos de mototaxis georreferenciados", 8, "red conectiva de ciclovías segregadas"),
        P("ambiente", "Contenedores soterrados con sensores de llenado y créditos ecológicos descontables de los arbitrios por reciclar", 8, "Sistema de Gestión de Residuos Smart", "40 % del volumen de residuos reciclado al 2030"),
        P("economia", "Puesta en valor de las 8 huacas del distrito con anillos verdes, museos de sitio y boulevares culturales y gastronómicos", 8, "Parque Arqueológico Integrado", "8 huacas integradas al 2030"),
        P("economia", "«Olivos Tech Hub»: incubadora de startups con universidades del distrito y capital semilla concursable", 9, "Olivos Tech Hub, Sandbox e Incubadora de Startups", "100 proyectos activos al 2030"),
        P("economia", "Licencias de funcionamiento provisionales automáticas para negocios de bajo riesgo", 9, "Gobierno Digital Cero Tiempo", "Licencias en menos de 24 horas"),
        P("social", "Centro de Salud Mental «Mente Sana» con el MINSA y albergue para la reinserción de personas en situación de calle", 10, "para la reinserción social autosustentable de personas en situación de calle"),
        P("social", "Talleres de fin de semana en colegios nacionales de deporte, robótica, programación e IA, dictados por universitarios", 10, "Programa Escolar Descentralizado"),
        P("gestion", "Tablero público mensual de indicadores de cada gerencia y presupuesto participativo con votación digital", 11, "Tablero Público de KPIs", "100 % de trámites digitales («Cero Papel»)"),
    ]),
    ("Wilder Leoncio Torpoco Huayta", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Central de monitoreo con IA, cámaras con lectura de placas en accesos e integración de cámaras de negocios con las comisarías", 7, "Instalar cámaras con reconocimiento de placas vehiculares", "150 cámaras nuevas"),
        P("seguridad", "Más serenos capacitados, motos de intervención rápida y patrullaje integrado con la PNP y las juntas vecinales", 7, "Incorporar motocicletas para intervención rápida", "100 juntas vecinales fortalecidas"),
        P("urbano", "Programa «Parques Seguros» de recuperación de parques, losas deportivas y espacios públicos", 7, "Recuperar parques, losas deportivas y espacios públicos deteriorados", "50 espacios públicos recuperados"),
        P("social", "Crear la universidad de emprendedores de Lima Norte en el Edificio Cielo", 7, "universidad de emprendedores de Lima Norte en el Edificio Cielo", "Universidad funcionando con 100 alumnos"),
        P("economia", "Centro Municipal de Desarrollo Empresarial con asesoría gratuita para formalizar negocios y capacitación en comercio electrónico", 8, "Asesoría gratuita para formalización de negocios", "1 500 mypes formalizadas y 3 000 emprendedores capacitados"),
        P("economia", "Priorizar proveedores locales en las compras municipales y formalización laboral en las obras municipales", 8, "Priorizar proveedores locales en adquisiciones municipales", "100 % de formalización laboral en obras municipales"),
        P("ambiente", "Segregación en la fuente, puntos ecológicos y formalización de recicladores", 9, "Formalización de recicladores", "10 puntos ecológicos y 75 % de disposición adecuada de residuos"),
        P("ambiente", "Parque zonal turístico ecológico en el Cerro Mulería y arborización masiva con riego tecnificado", 9, "Promoción del parque zonal Turístico ecologico en el Cerro muleria", "20 000 árboles sembrados"),
        P("urbano", "Plan integral de mejoramiento de pistas y veredas", 9, "Elaboración y ejecución de un plan de mejoramiento de pistas y veredas", "60 % de pistas y veredas recuperadas"),
        P("urbano", "Formalización de predios en asociaciones, cooperativas y asentamientos humanos, y actualización del catastro", 9, "Promover la formalización de los predios, viviendas", "70 % de propiedades formalizadas"),
        P("gestion", "Ventanilla única digital, expediente electrónico y portal de seguimiento de obras en tiempo real", 10, "Portal de seguimiento de obras en tiempo real", "80 % de servicios digitalizados y 40 % menos tiempo de trámites"),
    ]),
    ("Denner Guillermo Romaldo Noblejas", "Partido del Buen Gobierno", "partido-del-buen-gobierno", [
        P("seguridad", "Reforzar el patrullaje policial y del serenazgo en puntos críticos como transporte público y colegios, con líneas confidenciales de denuncia", 10, "Reforzar patrullaje policial y Serenazgo en puntos"),
        P("seguridad", "Ampliar los comités vecinales de seguridad con capacitación continua, mejorar el alumbrado y la vigilancia electrónica en parques", 10, "Ampliar comités vecinales de seguridad ciudadana"),
        P("social", "Ampliar el Hospital Municipal con especialidades como salud mental y pediatría, y construir centros de salud en barrios alejados", 10, "Ampliar el Hospital Municipal con más especialidades"),
        P("urbano", "Construir espacios verdes y deportivos inclusivos, como piscinas públicas y canchas multipropósito, en zonas que carecen de ellos", 10, "Construir más espacios verdes y deportivos inclusivos"),
        P("economia", "Plataforma digital express de licencias de funcionamiento para actividades de riesgo bajo y medio, con declaración jurada y fiscalización posterior", 12, "Plataforma Digital Express de Licencias Comerciales", "Licencias en 24 a 48 horas"),
        P("economia", "Intervenir las avenidas comerciales Universitaria, Antúnez de Mayolo, Las Palmeras, Naranjal, Carlos Izaguirre y Alfredo Mendiola con iluminación, señalización y orden del comercio", 16, "Corredores Económicos Modernizados"),
        P("economia", "Bolsa laboral distrital que conecte a empresas locales con vecinos que buscan empleo, con prácticas y seguimiento de colocaciones", 20, "Bolsa Laboral Distrital Inteligente"),
        P("gestion", "Actualizar el catastro con GIS, drones y modelamiento 3D para detectar ampliaciones no declaradas y mejorar la recaudación sin subir tasas", 15, "Catastro Digital 3D del Distrito"),
        P("gestion", "Implementar la norma ISO antisoborno y crear un comité anticorrupción con vecinos representativos", 38, "Implementar y adecuar la norma ISO antisoborno"),
        P("transporte", "Infraestructura de micromovilidad, carriles exclusivos y mejor conexión vial en la red urbana", 30, "Infraestructura de micromovilidad, carriles exclusivos"),
        P("agua_riesgos", "Saneamiento físico legal de predios y muros de contención para mitigar el riesgo físico", 30, "mitigación del riesgo físico"),
    ]),
    ("Gabriela Huamaní Aliaga", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Postes inteligentes con cámara Full HD, megáfonos y sirena, conectados a la central de seguridad y a las comisarías", 17, "Colocaremos 500 Postes Inteligentes", "500 postes inteligentes"),
        P("seguridad", "Reclutar serenos distribuidos en los 20 cuadrantes del distrito, en tres turnos", 18, "Reclutaremos 1000 serenos", "1 000 serenos"),
        P("seguridad", "Patrulleros inteligentes y motos en los 20 cuadrantes, interconectados con la central y las comisarías", 18, "Desplegaremos 50 Patrulleros Inteligentes", "50 patrulleros y 50 motos"),
        P("social", "Programa municipal de becas integrales asignadas por examen de conocimientos, financiado con obras por impuestos", 27, "Programa Municipal de Becas Integrales", "50 becas"),
        P("social", "Construir y equipar un policlínico municipal con medicina general, control materno, vacunas, dental y oftalmología", 28, "Policlínico municipal los olivos"),
        P("economia", "Crear la Caja Municipal de Ahorro y Crédito de Los Olivos, con un local propio", 29, "La Caja Municipal de Ahorro y Crédito de Los Olivos"),
        P("economia", "Formalizar el comercio ambulatorio reubicándolo en futuros mercados municipales", 24, "Formalizar el comercio ambulatorio a través de la reubicación"),
        P("transporte", "Ordenar el transporte en vehículos menores con una comisión mixta, un estudio de demanda, una mesa de diálogo y fiscalización orientada al orden", 25, "reactivación de la comisión mixta del trasporte del vehículo menor"),
        P("ambiente", "Recolección de residuos segregados con puntos de cuatro contenedores en espacios públicos y beneficios tributarios para vecinos que reciclen", 26, "consta de 4 contenedores de recolección"),
        P("urbano", "Completar la infraestructura vial de los asentamientos humanos y rehabilitar las vías deterioradas de las urbanizaciones", 23, "Consolidar 100% la infraestructura vial de los AA.HH", "100 % de la infraestructura vial de los AA.HH."),
        P("gestion", "Sistemas tecnológicos para seguir proyectos, gastos y obras municipales e informar continuamente a la ciudadanía", 22, "Establecer sistemas tecnológicos de seguimiento de los proyectos"),
    ]),
    ("Erick Melchor Torres", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Contratar serenos y equiparlos con chalecos antibalas, pistolas eléctricas y cámaras corporales", 12, "Contratación de 800 serenos", "800 serenos"),
        P("seguridad", "Videovigilancia con analítica de datos, software de reconocimiento facial y conexión de la central con la central 105 de la PNP", 12, "Implementar software de IA, para reconocimiento facial", "100 % de cámaras de videovigilancia operativas"),
        P("agua_riesgos", "Zonas de refugio temporal y contenedores de primera asistencia en las zonas más vulnerables, con capacitación y simulacros", 13, "Implementación de 4 zonas de refugio temporal", "4 zonas de refugio temporal"),
        P("social", "Repotenciar el Hospital de Los Olivos, adquirir una ambulancia y crear programas de enfermedades crónicas y salud mental con tarifas sociales", 13, "Repotenciamiento y mejoramiento de la oferta de servicios en el Hospital"),
        P("social", "Programa «Supérate Los Olivos» con cursos, talleres y becas, y acceso gratuito a la Academia Municipal", 14, "Implementación del Programa SUPERATE Los Olivos"),
        P("urbano", "Mantenimiento de pistas y veredas en las principales avenidas y jirones, y nueva infraestructura vial de concreto", 15, "Programa de mejoramiento (mantenimiento) vial y peatonal", "30 km de mantenimiento y 20 km de nuevas vías"),
        P("ambiente", "Luces LED, juegos infantiles y riego tecnificado en los parques, además del mejoramiento de áreas verdes y bermas", 15, "Implementación del riego tecnificado en el 100% de parques", "100 % de parques"),
        P("transporte", "Bus Olivense gratuito para recorrer las principales atracciones del distrito y convenio con la ATU para regular unidades menores", 16, "Implementar el Bus Olivense (4 unidades)", "4 unidades"),
        P("economia", "Ferias comerciales temáticas, espacios de coworking, app «Los Olivos Emprende» y ferias laborales con la bolsa laboral municipal", 17, "Realización de 12 Ferias comerciales temáticas", "12 ferias comerciales y 4 ferias laborales"),
        P("ambiente", "Contenedores soterrados, islas ecológicas, recojo de desmonte y un nuevo programa de segregación en la fuente", 18, "Implementación de contenedores soterrados"),
        P("gestion", "Certificar la ISO 37001 antisoborno e implementar la ISO 9001 y canales de denuncia de corrupción", 19, "Implementar y certificar el ISO 37001"),
    ]),
    ("Ricardo Luis Grados Guevara", "Frente de la Esperanza 2021", "partido-frente-de-la-esperanza-2021", [
        P("seguridad", "Crear y mejorar Puestos de Auxilio Rápido con cámaras, dron, camioneta del serenazgo y un ambiente de detención temporal", 2, "Creación, implementación y mejoramiento de Puestos de Auxilio Rápido"),
        P("seguridad", "Pedir al Ministerio del Interior la rotación periódica del personal de las tres comisarías del distrito", 2, "rotación del personal policial cada cinco", "Rotación cada 5 meses"),
        P("seguridad", "Crear un comando de inteligencia municipal de élite", 3, "COMANDO ELITE DE INTELIGENCIA"),
        P("gestion", "Auditar las tres últimas gestiones con la Contraloría y transmitir en directo los concursos, contratos y licitaciones", 4, "Auditoria exhaustiva de las tres últimas gestiones"),
        P("social", "Hospitales móviles ambulatorios «Olivos más Salud» en las zonas norte, centro, Confraternidad y sur", 4, "Olivos más Salud"),
        P("social", "Contratar personas con discapacidad en la municipalidad", 8, "Contratar personas con discapacidad en una cuota no menor del 5%", "Al menos 5 % del personal"),
        P("ambiente", "Sembrar árboles y césped en los primeros cien días de gestión", 5, "plantar 100 mil árboles", "100 000 árboles en los primeros 100 días"),
        P("urbano", "Recuperar parques y jardines con juegos, anfiteatros, baños y minigimnasios", 5, "Recuperar los parques y jardines", "100 % de parques mejorados"),
        P("transporte", "Ciclovías en todo el distrito y cicloparqueaderos en calles y avenidas", 5, "Creación e Implementación de Ciclovías en todo el distrito"),
        P("economia", "Facilitar las licencias de funcionamiento y hacer proporcionales las multas entre negocios pequeños y grandes", 10, "Dar facilidades para las licencias de funcionamientos"),
        P("gestion", "Descuento por pronto pago de tributos e incentivos a empresas que empleen a mujeres, jóvenes y personas con discapacidad", 10, "10% descuentos por el pago oportuno", "10 % de descuento"),
    ]),
    ("María Rosario Silvestre Vilchez", "Perú Libre", "partido-politico-nacional-peru-libre", [
        P("seguridad", "Programa «Los Olivos Seguro 24/7» con serenazgo y fiscalización las 24 horas, juntas vecinales y licenciados de las Fuerzas Armadas", 2, "LOS OLIVOS SEGURO 24/7"),
        P("seguridad", "Red de vigilancia colaborativa que integre cámaras privadas de negocios, mercados, condominios y urbanizaciones", 2, "integración de cámaras privadas de negocios"),
        P("social", "Brigadas que visiten a adultos mayores de bajos recursos para tramitar subsidios y beneficios, y fondo para reforzar viviendas precarias", 2, "Ventanilla Única de Atención Itinerante"),
        P("urbano", "Rampas, pisos podotáctiles y semáforos sonoros, y adecuación de locales municipales para personas con discapacidad", 3, "Distrito 100% Accesible"),
        P("social", "Refuerzo escolar comunitario y talleres de oficios llevados a los barrios, con atención especial a madres trabajadoras", 3, "AHORA MI COMUNIDAD SE PREPARA"),
        P("social", "Programa «Jóvenes Talentos Olivenses» con capacitación y certificación artística y circuitos culturales para exponer y vender su trabajo", 3, "JÓVENES TALENTOS OLIVENSES"),
        P("economia", "Padrón y carnet para comerciantes ambulantes, con permisos temporales reservados a adultos mayores, personas con discapacidad y madres solteras pobres", 4, "Padrón y Carnetización Obligatoria"),
        P("economia", "Licencias provisionales sin costo y capacitación por rubro para que los ambulantes pasen a la microempresa formal", 4, "Otorgar licencias provisionales a costo cero"),
        P("ambiente", "Compra gradual de camiones compactadores propios, rutas con GPS, compostaje y descuentos en arbitrios para vecinos que reciclen", 6, "Adquisición Progresiva de Flota Municipal Propia"),
        P("urbano", "Recuperar parques y espacios públicos con juegos infantiles, iluminación LED, arborización y zonas para mascotas", 6, "Recuperaremos parques deteriorados y espacios públicos abandonados"),
        P("gestion", "Informes públicos, audiencias descentralizadas y cabildos abiertos sobre obras y presupuesto", 7, "informes trimestrales públicos, audiencias descentralizadas", "Informes trimestrales y cabildos semestrales"),
    ]),
    ("Arturo Alejandro Cutipa Camac", "PRIN", "partido-politico-prin", [
        P("seguridad", "Comando Distrital de Intervención Rápida con centrales de intervención rápida y unidades de flagrancia junto a la PNP", 23, "6 centrales de intervención rápida creadas", "6 centrales de intervención rápida y 6 unidades de flagrancia"),
        P("seguridad", "Convertir el serenazgo en una policía municipal especializada en crimen organizado, cibercrimen, tráfico de terrenos y extorsión", 24, "500 policías municipales especializados", "500 policías municipales especializados y equipados"),
        P("social", "Crear un seguro médico municipal con citas digitales y una ambulancia municipal para emergencias", 25, "SEGURO MEDICO MUNICIPAL"),
        P("social", "Reducir la anemia y la desnutrición infantil con los programas alimentarios municipales", 25, "Reducción a menos del 20% de anemia infantil", "Anemia infantil por debajo de 20 % y desnutrición crónica por debajo de 10 %"),
        P("agua_riesgos", "Programa distrital de reforzamiento sísmico para viviendas e infraestructura crítica y licencias de construcción con estudio geotécnico", 28, "Programa Distrital de Reforzamiento Sísmico", "100 % de licencias con estudio geotécnico"),
        P("transporte", "Plan de movilidad activa con ciclovías y redes peatonales seguras", 28, "Plan Distrital de Movilidad Activa", "10 km de red ciclista conectada y 50 % menos siniestralidad vial"),
        P("urbano", "Crear un «COFOPRI municipal» para la formalización y titulación de propiedades", 28, "Creación del COFOPRI MUNICIPAL"),
        P("economia", "Sistema de compras abiertas «Véndeme Emprendedor» para monitorear en tiempo real las compras municipales a las mypes del distrito", 29, "VENDEME EMPRENDEDOR", "50 % de los devengados en bienes y servicios por este sistema"),
        P("economia", "Ferias y expoferias mensuales y un programa de formalización del comercio", 31, "Formalizar 20% más que el 2026 de mypes informales", "20 % más mypes formalizadas que en 2026 y 500 vecinos insertados laboralmente"),
        P("ambiente", "Sembrar especies forestales nativas para recuperar áreas verdes", 32, "10,000 árboles sembrados", "10 000 árboles (10 ha)"),
        P("gestion", "Crear el primer aplicativo móvil municipal para pagos y servicios", 33, "La creación del primer aplicativo móvil municipal"),
    ]),
    ("Miguel Eduardo Figueroa Suárez", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Repotenciar la videovigilancia con inteligencia artificial para detectar vehículos y motos vinculados a delitos, y modernizar la central de monitoreo", 6, "incorporación progresiva de herramientas de inteligencia artificial"),
        P("seguridad", "Anillos de seguridad en los principales accesos del distrito con monitoreo inteligente de vehículos y motocicletas", 6, "sistema de anillos de seguridad"),
        P("seguridad", "Evaluar técnicamente las rejas instaladas en calles para que no afecten la respuesta del serenazgo ni de los servicios de emergencia", 6, "Evaluar técnicamente la ubicación y funcionalidad de las rejas"),
        P("social", "Convenios con MINSA, DIRIS Lima Norte, EsSalud y universidades para ampliar las campañas preventivas, y espacios municipales para vacunación", 7, "DIRIS Lima Norte, EsSalud"),
        P("social", "Ampliar la capacitación en oficios técnicos y herramientas digitales en el Edificio Cielo y otros espacios municipales", 10, "Edificio Cielo"),
        P("urbano", "Programa «Los Olivos Full Pistas» de mantenimiento y rehabilitación de pistas y veredas según un diagnóstico técnico de las vías", 9, "Los Olivos Full Pistas"),
        P("urbano", "Rampas, pavimentos podotáctiles y señalización inclusiva en los principales ejes peatonales y zonas de alta concurrencia", 9, "pavimentos podotáctiles"),
        P("economia", "Ferias de emprendimiento en distintos sectores del distrito, con apoyo logístico y difusión municipal", 12, "Desarrollar ferias de emprendimiento en diferentes sectores"),
        P("ambiente", "Riego tecnificado en parques y bermas, y un programa de manejo técnico del arbolado urbano", 14, "sistemas de riego tecnificado en parques, bermas centrales"),
        P("ambiente", "Luminarias con energía solar en parques y espacios públicos con poca iluminación", 14, "luminarias alimentadas mediante energía solar"),
        P("gestion", "Pagos tributarios en plataformas digitales y una administración basada en la meritocracia", 16, "Modernizar los sistemas de recaudación tributaria"),
    ]),
    ("José Gilberto Oliva Chuman", "Partido SíCreo", "partido-sicreo", [
        P("seguridad", "Convenios con la PNP, una fuerza preventiva de élite del serenazgo y las Fuerzas Armadas contra la extorsión y el delito", 11, "fuerza preventiva de elite de Serenazgo", "60 % menos denuncias por extorsión y 45 % menos delitos registrados"),
        P("urbano", "Recuperar, habilitar y mantener los parques, áreas verdes y plazas como espacios seguros y limpios", 11, "Recuperar, habilitar y mantener 100% de los parques", "100 % de parques y plazas"),
        P("agua_riesgos", "Ampliar el agua potable y el alcantarillado en las zonas residenciales y asentamientos humanos", 11, "Alcanzar la cobertura 100% de agua potable", "100 % de cobertura"),
        P("social", "Programas sociales permanentes para niñez, adolescencia, adultos mayores, personas con discapacidad y familias vulnerables", 11, "Implementar 15 programas sociales permanentes", "15 programas sociales"),
        P("economia", "Simplificar y digitalizar los trámites de licencia para aumentar la formalización de negocios", 12, "Simplificar y digitalizar 100% de los trámites de licencia", "Formalización del 45 % al 75 % al 2030; 70 % menos tiempo de espera"),
        P("economia", "Reordenar el comercio informal en espacios autorizados y crear zonas comerciales modernas", 12, "Crear 3 zonas comerciales modernas", "3 zonas comerciales"),
        P("ambiente", "Cobertura total de recolección de residuos y aumento del reciclaje", 13, "elevar la tasa de reciclaje del 41% al 70%", "Reciclaje del 41 % al 70 % al 2030"),
        P("ambiente", "Crear y recuperar áreas verdes y ampliar la superficie verde por habitante", 13, "Crear y recuperar 15 nuevas áreas verdes", "15 áreas verdes y 20 % más superficie verde por habitante"),
        P("urbano", "Reparar y renovar las pistas y veredas deterioradas", 13, "Reparar, renovar y mejorar 100% de las pistas y veredas", "100 % de pistas y veredas deterioradas al 2029"),
        P("agua_riesgos", "Modernizar el alcantarillado y el drenaje para eliminar los puntos críticos de inundación en lluvias", 13, "Modernizar y ampliar el sistema de alcantarillado y drenaje", "100 % de puntos críticos eliminados"),
        P("gestion", "Digitalizar los trámites con una plataforma virtual única y publicar cada mes el presupuesto, los gastos y las obras", 14, "Digitalizar y automatizar 80% de todos los trámites", "80 % de trámites digitales al 2028 y 100 % al 2030"),
    ]),
    (None, "Podemos Perú", "podemos-peru", [
        P("seguridad", "Incorporar inteligencia artificial a la central de monitoreo y videovigilancia", 30, "500 videocámaras con inteligencia artificial", "500 videocámaras con IA"),
        P("seguridad", "Ampliar el programa Sereno Vigilante y capacitar a todo el serenazgo en el centro de capacitación municipal", 30, "500 Serenos Vigilantes nuevos", "500 serenos vigilantes nuevos y 100 % de serenos capacitados"),
        P("social", "Brigada de salud geriátrica que atienda en los centros de adultos mayores y renovación del Hospital Municipal", 32, "2 visitas médicas al mes de la brigada geriátrica", "2 visitas médicas al mes en cada centro"),
        P("urbano", "Renovar pistas con asfalto nuevo y renovar las piscinas municipales César Vallejo, Santa Rosa y San Martín de Porres", 34, "200 000 metros cuadrados de asfalto nuevo", "200 000 m² de asfalto nuevo y 3 piscinas renovadas"),
        P("economia", "Programa «Mujer Chamba»: bolsa de trabajo con el sector privado para madres de los programas sociales", 35, "mujer chamba", "100 plazas de trabajo"),
        P("economia", "Emitir licencias de bajo riesgo el mismo día de presentado el expediente y realizar las inspecciones ITSE en una semana", 40, "emitidas dentro del primer día de ingresado expediente", "100 % de licencias de bajo riesgo en el primer día"),
        P("ambiente", "Programa de arborización «Planta un Árbol y Cosecha Vida» y riego tecnificado en parques y bermas", 42, "Sembrar y mantener 150,000 árboles", "150 000 árboles y riego tecnificado en el 100 % de parques y bermas"),
        P("ambiente", "Ampliar la segregación de residuos en los hogares, con EcoPuntos inteligentes y contenedores soterrados en ejes comerciales", 43, "participación del 70% de hogares en programas de segregación", "70 % de hogares segregando"),
        P("transporte", "Red de ciclovías seguras e interconectadas y estacionamientos para bicicletas en universidades, mercados y estaciones del Metropolitano", 44, "Construcción de 25 kilómetros de ciclovías seguras", "25 km de ciclovías y 50 estacionamientos para bicicletas"),
        P("agua_riesgos", "Sistema digital de alerta temprana ante sismos, zonas seguras señalizadas y capacitación vecinal en gestión de riesgos", 45, "Capacitar a más de 20,000 vecinos", "Más de 20 000 vecinos capacitados"),
        P("gestion", "Plataforma «Los Olivos en tus Manos» para trámites y pagos en línea, y actualización del catastro urbano", 47, "Digitalizar el 100% de los principales trámites", "100 % de los principales trámites digitales y 100 % del catastro actualizado"),
    ]),
    ("Segundo Marcos de la Cruz Vega", "Progresemos", "progresemos", [
        P("seguridad", "Centro de Seguridad Inteligente con central de monitoreo con inteligencia artificial y cámaras inteligentes", 6, "hasta 1,500 cámaras inteligentes", "Hasta 1 500 cámaras inteligentes"),
        P("seguridad", "Cámaras corporales para el serenazgo, lectura de placas, botón de pánico vecinal y el programa «Águilas Los Olivos» de atención rápida", 6, "Programa Águilas Los Olivos"),
        P("seguridad", "Programa «Fronteras Unidas» con los distritos vecinos y vigilancia con drones", 7, "Programa Fronteras Unidas con distritos vecinos"),
        P("urbano", "Programa «Bache Cero» con asfalto frío, geolocalización de incidencias, app vecinal y cuadrillas permanentes", 7, "Reparación de baches en un máximo de 48 horas", "Baches reparados en un máximo de 48 horas"),
        P("ambiente", "Parque Canino Metropolitano con veterinaria municipal, vacunación, esterilización y adopciones", 8, "Parque Canino Metropolitano"),
        P("ambiente", "Arborización, programa «Adopta un Parque», riego tecnificado y barrido mecanizado", 8, "Programa Adopta un Parque"),
        P("economia", "Centro Municipal del Emprendedor, bolsa laboral digital, ferias de empleo y marketplace municipal", 9, "Centro Municipal del Emprendedor"),
        P("economia", "«Boulevard de Lima Norte»: corredor comercial, gastronómico y cultural", 9, "Boulevard de Lima Norte"),
        P("transporte", "Empadronar mototaxis y registrar a sus conductores, con capacitación en educación vial junto al MTC, la PNP y la SUTRAN", 10, "Empadronamiento de unidades"),
        P("social", "Programa «Adulto Mayor Protegido» con puntos de atención preventiva, orientación nutricional y atención psicológica en distintos sectores", 12, "Programa Adulto Mayor Protegido"),
        P("gestion", "Audiencias públicas de rendición de cuentas transmitidas en línea y un Observatorio Vecinal que supervise obras y servicios", 13, "Audiencias Públicas de Rendición de Cuentas semestrales", "Audiencias semestrales"),
    ]),
    ("Luis Sigfredo Milla Soto", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Crear un grupo especial de inteligencia municipal e instalar un centro de monitoreo inteligente 24/7 con cámaras", 35, "Crear el GEIN Los Olivos dentro de los primeros tres meses", "En los primeros 3 meses; 500 cámaras"),
        P("seguridad", "Programa «El Serenazgo Eres Tú» de vigilancia vecinal con kits de seguridad e incentivos en arbitrios", 35, "en los 10 zonales priorizados", "10 zonales"),
        P("seguridad", "Unidad especial contra la extorsión con línea confidencial 24/7, app anónima georreferenciada y respuesta articulada con la PNP", 32, "Unidad Especial de Denuncia y Prevención de Extorsión"),
        P("transporte", "Retirar a los parqueadores informales y crear zonas de estacionamiento reguladas por la municipalidad", 32, "Retiro y formalización de parqueadores informales"),
        P("gestion", "Digitalizar los procesos administrativos y destinar la mitad del presupuesto a inversión", 28, "Digitalizar el 100% de procesos administrativos", "100 % de procesos digitales antes del segundo año; 50 % inversión y 50 % gasto corriente"),
        P("urbano", "Tribunal Urbano Municipal y registro electrónico de infracciones para sancionar la construcción ilegal y la invasión del espacio público", 78, "Implementar el Tribunal Urbano Municipal y el Registro Electrónico", "En el primer año; 60 % menos construcción ilegal"),
        P("economia", "Escuela de emprendimiento «Marca Los Olivos» y los proyectos Boulevard de Los Olivos y El Mirador de Los Olivos", 84, "Formalizar 12,000 emprendimientos", "12 000 emprendimientos formalizados y más de 30 000 personas capacitadas"),
        P("social", "Reactivar el Hospital Municipal y crear la Casa Psicológica «Bienestar Olivos» con módulos zonales", 100, "Crear la Casa Psicológica Bienestar Olivos y 6 módulos zonales", "1 casa y 6 módulos zonales"),
        P("ambiente", "Parques ecológicos temáticos en cada zonal y siembra o recuperación de árboles", 106, "10 parques ecológicos temáticos en las 10 zonales", "10 parques ecológicos y 30 000 árboles"),
        P("ambiente", "Centro Municipal de Bienestar Animal con atención veterinaria, esterilización y adopciones", 100, "Atender a más de 25,000 mascotas", "Más de 25 000 mascotas atendidas"),
        P("agua_riesgos", "Mapear las zonas de riesgo, crear comités vecinales de emergencia y un sistema de alerta temprana con sensores", 107, "Sistemas tecnológicos de monitoreo y alerta temprana", "100 % de zonas de riesgo mapeadas y 10 comités vecinales"),
    ]),
]
