"""San Luis (150134): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150134"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Diego Alejandro Hernández Huambachano", "Acción Popular", "accion-popular", [
        P("seguridad", "Proyecto «San Luis Seguro 360°»: patrullaje integrado con la PNP, central de videovigilancia modernizada y prevención comunitaria", 11, "Reducir en 30 % la percepción de inseguridad ciudadana", "30 % menos percepción de inseguridad ciudadana"),
        P("seguridad", "Cámaras inteligentes en puntos críticos, alarmas vecinales interconectadas, corredores seguros escolares y comerciales y aplicación móvil para reportes ciudadanos", 6, "Implementación de alarmas vecinales interconectadas"),
        P("economia", "Proyecto «San Luis Emprende»: asesoría gratuita para formalizar negocios, simplificación de licencias, ferias de emprendimiento y bolsa de trabajo distrital", 11, "Formalizar al menos a 1 500 negocios", "Al menos 1 500 negocios formalizados"),
        P("economia", "Alianza productiva Arriola–El Pino: mesa de desarrollo económico local, convenios de prácticas y empleo juvenil y contratación de mano de obra local", 7, "Creación de una mesa de desarrollo económico local"),
        P("urbano", "Rehabilitación de pistas y veredas priorizadas, señalización y mantenimiento preventivo en vías de alto tránsito", 12, "Rehabilitar el 80 % de las vías críticas del distrito", "80 % de las vías críticas rehabilitadas"),
        P("transporte", "Mejorar la movilidad y la gestión del tránsito con semaforización inteligente, alumbrado LED y rampas de accesibilidad", 12, "Reducir en 15 % los tiempos de desplazamiento", "15 % menos tiempo de desplazamiento"),
        P("ambiente", "Proyecto «San Luis Verde»: arborización de parques y avenidas, riego tecnificado y programa «Adopta un Parque»", 12, "Aumentar en 20 % la cobertura de áreas verdes", "20 % más cobertura de áreas verdes"),
        P("ambiente", "Proyecto «San Luis Recicla»: puntos limpios, segregación en la fuente y formalización y capacitación de recicladores", 12, "Alcanzar un 40 % de segregación en la fuente", "40 % de segregación en la fuente"),
        P("social", "Proyecto «San Luis Inclusivo»: talleres, salud preventiva, atención psicológica y fortalecimiento de la oficina de atención a personas con discapacidad", 8, "Atención psicológica y orientación familiar"),
        P("gestion", "Digitalización de trámites con expediente electrónico, plataforma virtual de atención y seguimiento en línea de expedientes", 12, "Digitalizar el 90 % de los trámites municipales", "90 % de los trámites municipales digitalizados"),
        P("gestion", "Audiencias públicas descentralizadas de rendición de cuentas, informes trimestrales de gestión y portal de seguimiento ciudadano", 13, "Publicación trimestral de informes de gestión", "2 audiencias públicas por año"),
    ]),
    ("Ever Cabanillas Menor", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Integrar las cámaras de videovigilancia y los drones serenos de la municipalidad con las dos comisarías del distrito", 12, "Contar con todas las cámaras del distrito integradas con las comisarias", "Todas las cámaras del distrito integradas con las comisarías"),
        P("seguridad", "Programas sociales de bolsas de trabajo, deporte y educación para disminuir la delincuencia, con mesas de diálogo entre comités vecinales y empresarios", 12, "Reducción de la delincuencia en SAN LUIS en un 50%", "50 % menos delincuencia"),
        P("social", "Programas sociales de lucha contra la violencia familiar para los vecinos del distrito", 12, "Reducción del maltrato físico y familiar en un 60%", "60 % menos maltrato físico y familiar"),
        P("social", "Plan de salud integral gestionado por la municipalidad, con infraestructura municipal de salud y programas de prevención para población vulnerable", 12, "Contar con un sistema de salud gestionado por", "Plan de salud ejecutado al 50 %"),
        P("social", "Actividades deportivas para jóvenes y adultos mayores aprovechando la infraestructura de la Videna", 13, "la Videna - IPD (villa deportiva nacional)"),
        P("economia", "Cámara de comercio distrital, atracción de fondos para financiar negocios y capacitación financiera a micro y pequeñas empresas", 14, "Contar con una cámara de comercio para el distrito"),
        P("gestion", "Plan antisoborno municipal para lograr la certificación ISO 37001", 15, "Ser la primera municipalidad del Perú en contar con la certificación ISO 37001", "Certificación ISO 37001 antisoborno"),
        P("gestion", "Publicación de informes económicos mensuales en un portal de transparencia y archivo municipal digitalizado de libre acceso", 16, "Publicación de informes económicos mensuales"),
        P("urbano", "Actualizar el plan de desarrollo urbano (zonificación, Línea 2) y modernizar el catastro con herramientas tecnológicas", 16, "la actualización del Plan de desarrollo urbano", "Plan de desarrollo urbano ejecutado al 50 %"),
        P("urbano", "Recuperar parques abandonados y generar estacionamientos subterráneos y parques temáticos", 16, "Incorporar el 50% de (parques)", "50 % de parques abandonados recuperados"),
        P("ambiente", "Crear una empresa municipal de reciclaje que aproveche los residuos sólidos para generar ingresos y productos biodegradables", 17, "Creación y funcionamiento de empresa de reciclaje municipal"),
    ]),
    ("Zee Carlos Corrales Romero", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Plan de cámaras de seguridad con inteligencia artificial y ampliación del alumbrado público distrital", 3, "plan de implementación de cámaras de seguridad con IA"),
        P("seguridad", "Planes para erradicar el consumo de licor en las calles, el pandillaje y los locales clandestinos de bebidas alcohólicas", 3, "Plan de Erradicación de locales clandestinos de bebidas alcohólicas"),
        P("transporte", "Plan de control y circulación de vehículos", 3, "Plan de control y circulación de vehículos"),
        P("social", "Más espacios municipales para educación, cultura, apoyo al niño, joven y adulto, velatorio y veterinaria", 3, "velatorio, veterinaria y otros"),
        P("social", "Plan de ampliación de los servicios médicos municipales", 3, "plan de ampliación de servicios médicos"),
        P("urbano", "Priorizar y gestionar proyectos de remodelación y reconstrucción de calles y avenidas", 3, "Priorizar y gestionar los proyectos de remodelación"),
        P("economia", "Capacitar a empresas en trámites de licencia e inspecciones técnicas de seguridad (ITSE) y fomentar gremios empresariales", 4, "capacitadas en procesos de tramites de licencia"),
        P("economia", "Plan de formalización del comercio ambulatorio y apoyo a emprendedores", 4, "plan de formalización de comercio ambulatorio"),
        P("ambiente", "Charlas sobre tenencia responsable de mascotas y fiscalización del recojo de excretas en la vía pública", 4, "concientización sobre tenencia responsable de mascotas"),
        P("ambiente", "Arborización de parques y calles y modernización de parques con sistemas de riego mejorados", 5, "Modernizar los parques incluyendo sistemas mejorados de riego"),
        P("gestion", "Sesiones de concejo descentralizadas en las urbanizaciones, plan de integración vecinal y fortalecimiento del órgano de control y la procuraduría", 6, "sesiones de concejo descentralizadas"),
    ]),
    ("Víctor Antonio Alegría García", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Central de videovigilancia con inteligencia artificial, cámaras de reconocimiento facial y lectura de placas, y drones de vigilancia preventiva", 16, "Instalación de cámaras inteligentes para reconocimiento facial"),
        P("seguridad", "Patrullaje integrado Serenazgo–PNP focalizado según mapas de calor del delito y comités vecinales de seguridad", 17, "patrullaje focalizado basado en mapas de calor del delito", "Respuesta a emergencias en menos de 7 minutos y 30 % menos delitos patrimoniales"),
        P("social", "Programas de salud mental comunitaria y de apoyo e inclusión para niños y jóvenes con trastorno del espectro autista (TEA)", 18, "Programas de apoyo e inclusión para niños y jóvenes con Trastorno del Espectro Autista", "5,000 beneficiarios acumulados en programas de salud mental"),
        P("social", "Centros de atención comunitaria, fortalecimiento de OMAPED, DEMUNA y CIAM y programas alimentarios para familias vulnerables", 21, "Implementar Centros de Atención Comunitaria", "2500 familias beneficiadas con programas alimentarios"),
        P("economia", "Centro Municipal de Desarrollo Empresarial, formalización progresiva del comercio ambulatorio y mercados temporales autorizados", 23, "Centro Municipal de Desarrollo Empresarial implementado", "60 % de comerciantes formalizados y 1 centro operativo"),
        P("economia", "Bolsa laboral digital municipal, convenios con empresas para empleo y prácticas, y capacitación tecnológica para jóvenes", 24, "Implementación de una Bolsa Laboral Digital Municipal", "10000 jóvenes registrados y 50 convenios con empresas"),
        P("urbano", "Rehabilitar las principales vías (Av. San Juan, Rosa Toro, San Luis), con veredas accesibles, y modernizar el Estadio Municipal", 26, "incluyendo la Av. San Juan, Av. Rosa Toro, Av. San Luis"),
        P("transporte", "Semaforización en las vías de mayor circulación y semáforos con parlante para personas con discapacidad visual", 35, "semáforos con parlante para personas con discapacidad visual"),
        P("ambiente", "Arborización masiva, recuperación de parques con riego tecnificado, corredores verdes y jardines verticales", 28, "un mínimo de 8 m² por habitante", "Mínimo 8 m² de área verde por habitante"),
        P("ambiente", "Segregación en la fuente, reciclaje casa por casa con incentivos y formalización de recicladores", 29, "incrementar al 35% la valorización de residuos sólidos", "35 % de residuos sólidos valorizados"),
        P("gestion", "Portal de datos abiertos, rendiciones de cuentas trimestrales y audiencias públicas descentralizadas por sectores", 30, "rendiciones de cuentas trimestrales obligatorias"),
    ]),
    ("Napoleón Gonzales Castillo", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Renovar la flota de patrullaje con dos serenos por sector y equipar al serenazgo con radios, cámaras corporales y fibra óptica", 7, "cobertura de dos serenos por sector"),
        P("seguridad", "Central de videovigilancia coordinada con la PNP y ampliación de cámaras a los sectores con menor cobertura", 12, "Reducir en 40% los índices de delitos contra el patrimonio", "40 % menos delitos contra el patrimonio y cámaras en el 100 % de las zonas de mayor riesgo"),
        P("social", "Mejorar y equipar el policlínico de San Luis, crear una posta médica municipal y hacer campañas itinerantes de salud", 8, "posta médica municipal de atención primaria"),
        P("social", "Programa «Sanluisino Atleta»: becas municipales para talleres deportivos de la Videna dirigidas a escolares de colegios públicos", 8, "un sistema de becas municipales"),
        P("social", "Centro Vecinal Polifuncional de la Juventud con ambientes para el CIAM, la OMAPED, salud mental y talleres juveniles", 8, "Centro Vecinal Polifuncional de la Juventud"),
        P("ambiente", "Arborización, bebederos para animales en parques, ciclovías y peatonalización progresiva de calles de menor circulación", 9, "incrementar en al menos 2 m² per cápita", "Al menos 2 m² más de área verde por habitante"),
        P("ambiente", "Renovar la flota de limpieza, instalar tachos diferenciados en parques y dar descuentos en arbitrios a quienes reciclen", 9, "descuentos en arbitrios"),
        P("economia", "Plan de reconversión comercial de San Jacinto: censo de locales, fiscalización rotativa con la PNP y Fiscalía e incentivos para formalizarse", 13, "Censar el 100% de locales de San Jacinto", "100 % de locales de San Jacinto censados"),
        P("economia", "Programa de reordenamiento comercial con incentivos a la formalización del comercio ambulatorio y reubicación de talleres", 13, "Formalizar el 60% de los comercios ambulatorios registrados", "60 % de comercios ambulatorios formalizados y 100 % de talleres reubicados"),
        P("transporte", "Mesa de coordinación vecinal con la MML y la ATU por la ampliación de la Carretera Central, con semaforización y paraderos formales", 10, "Mesa de Coordinación Vecinal con la MML y la ATU"),
        P("gestion", "Declaración jurada de intereses pública de funcionarios de compras y licencias, y ventanilla de denuncia anónima con seguimiento", 11, "ventanilla de denuncia anónima con número de seguimiento"),
    ]),
    ("Ricardo Fidel Castro Sierra", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Sistema de seguridad ciudadana integral y tecnológico, más serenos y fortalecimiento de las juntas vecinales", 10, "SISTEMA DE SEGURIDAD CIUDADANA INTEGRAL Y TECNOLOGICA"),
        P("seguridad", "Renovar el parque vehicular de patrullaje y repotenciar el PARMET", 10, "Programa de Repotenciación de PARMET"),
        P("seguridad", "Regular la venta de alcohol con el programa «Alcohol Cero»", 10, "desarrollar Programa Alcohol Cero"),
        P("seguridad", "Proyecto de seguridad ciudadana desde el aire, operativos con la PNP y programa de atención a jóvenes en riesgo", 11, "Proyecto Seguridad Ciudadana desde el Aire"),
        P("economia", "Programas «Jóvenes Emprendedores y Exitosos» y «Mujeres Emprendedoras», escuela de empresarios y redes empresariales", 11, "Programa Mujeres Emprendedoras"),
        P("economia", "Proyecto «Licencias de Funcionamiento al Toque» y ferias de desarrollo empresarial", 11, "Proyecto Licencias de Funcionamiento al Toque"),
        P("economia", "Formalización del comercio ambulatorio y bolsa de trabajo", 12, "Proyecto Bolsa de Trabajo Para Todos"),
        P("ambiente", "Plan integral de gestión ambiental de residuos sólidos (PIGARS) y formalización y capacitación de recicladores", 13, "Formalización y capacitación de los recicladores"),
        P("ambiente", "Maquinaria para eliminación de desmonte y para riego de áreas verdes, y riego tecnificado", 13, "Proyecto Maquinarias para Riego de Áreas Verdes"),
        P("social", "Centro Municipal de Atención a la Salud, plan distrital de salud, prevención del embarazo adolescente y atención al adicto", 14, "Centro Municipal de Atención a la salud"),
        P("gestion", "Revisar la estructura organizacional para eliminar duplicidad de funciones y reducir los tiempos de trámite, sobre todo en licencias", 16, "Variar la estructura organizacional de la Municipalidad"),
    ]),
    ("Germán Anselmo Chirinos Quispe", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Programa «Alerta en mi Barrio» de no violencia y convivencia pacífica adaptado a cada sector", 6, "Alerta en mi Barrio"),
        P("seguridad", "Sistema de radio vecinal para alertar emergencias, conectado a la sala de monitoreo municipal", 7, "permanente con la sala de monitoreo municipal en vivo"),
        P("seguridad", "Más cámaras de seguridad con los empresarios del distrito, interconectadas con la Policía Nacional", 7, "implementaremos un mayor número de Cámaras de Seguridad", "Llegada policial en menos de 5 minutos tras una denuncia"),
        P("urbano", "Cuadrilla municipal de mantenimiento de pistas y veredas que trabaje con las juntas vecinales sin subcontratar empresas", 9, "Creación de una cuadrilla de mantenimiento de la alcaldía"),
        P("transporte", "Gestionar rayado, señalización, ojos de gato y rompemuelles en zonas con muchos peatones, como colegios, parques e iglesias", 9, "colocar ojos de gato y rompe muelles"),
        P("ambiente", "Programa «San Luis Recicla» y brigadas ambientales por sector junto con las juntas vecinales", 10, "por sectores que se encarguen de coordinar la limpieza de calles"),
        P("ambiente", "GPS en los camiones recolectores para controlar rutas y horarios e informar a los vecinos", 10, "la instalación de GPS en los camiones recolectores"),
        P("social", "Torneo interescolar «Copa Municipalidad de San Luis», Maratón de San Luis y recuperación de losas deportivas", 11, "Copa Municipalidad de San Luis"),
        P("economia", "Programa «San Luis mi Empresa» de asistencia integral a pequeñas empresas, en coordinación con PRODUCE", 13, "con asistencia integral a las pequeñas empresas del distrito"),
        P("social", "Casa Cultural de la Juventud, centro municipal de formación en artes y oficios y becas preuniversitarias", 14, "centro de formación en artes y oficios del municipio"),
        P("social", "Gestionar la construcción de un hospital municipal con el gobierno central y entidades privadas", 16, "Gestionar la construcción de un Hospital Municipal"),
    ]),
    ("César Roberto Mendoza Valencia", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Patrullaje preventivo por cuadrantes entre Serenazgo y las comisarías de San Luis y Yerbateros, con cámaras con analítica de inteligencia artificial", 6, "red de 120 cámaras de videovigilancia interconectadas", "120 cámaras con inteligencia artificial"),
        P("urbano", "Plan de rehabilitación de pavimentos y veredas locales con diseño universal", 10, "Rehabilitar el 85% de las vías y veredas secundarias críticas", "85 % de vías y veredas secundarias críticas rehabilitadas al 2030"),
        P("social", "Equipar comedores populares y Vaso de Leche, abasteciéndolos con compras directas a la agricultura familiar", 7, "compras directas a la agricultura familiar local"),
        P("social", "Campañas itinerantes de salud preventiva y modernización de polideportivos con iluminación LED y talleres", 7, "programa anual de 24 campañas itinerantes de salud preventiva", "24 campañas de salud al año"),
        P("economia", "Programa de formalización y reubicación de ambulantes con incentivos tributarios y asistencia empresarial, en mercados y el terminal de Yerbateros", 11, "Formalizar o reubicar de manera productiva al 70%", "70 % de ambulantes identificados formalizados o reubicados"),
        P("economia", "Capacitación digital a MYPES y convenios con empresas locales para insertar laboralmente a jóvenes", 8, "insertar laboralmente a un mínimo de 400 jóvenes anualmente", "Al menos 400 jóvenes insertados al año"),
        P("economia", "Licencia de funcionamiento virtual automatizada para negocios de riesgo bajo y medio", 8, "plazo máximo improrrogable de 24 horas", "Licencia en un máximo de 24 horas"),
        P("ambiente", "Rutas de recolección nocturna optimizadas y control GPS de los camiones compactadores", 8, "controles de posicionamiento satelital GPS"),
        P("ambiente", "Programa «Recicla San Luis» con colegios y juntas vecinales, y asociaciones formales de recicladores", 9, "al menos el 45% de las viviendas del distrito", "45 % de viviendas segregando sus residuos"),
        P("agua_riesgos", "Plan distrital de prevención de riesgos: mapas de riesgo, brigadas vecinales y fiscalización contra incendios en mercados y locales", 13, "reducir de 4 a 2 las zonas vulnerables críticas", "Zonas vulnerables críticas de 4 a 2"),
        P("gestion", "Plataforma y aplicativo «Control San Luis» con visor de obras, declaraciones juradas de funcionarios y buzón de denuncias", 14, "Visor de Avance de Obras y Presupuesto"),
    ]),
    ("Ronald Eulogio Fuertes Vega", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Cámaras con inteligencia artificial para reconocimiento de placas, centrales de monitoreo y app que integra serenazgo y PNP", 3, "cámaras con inteligencia artificial (IA) para reconocimiento de placas"),
        P("seguridad", "Nuevas unidades de serenazgo (autos, motos, escúteres), unidades caninas y más patrullaje integrado", 14, "Nro. de nuevas unidades de movilidad de Serenazgo", "Al menos 15 nuevas unidades de serenazgo"),
        P("social", "Academia municipal de formación técnica, fortalecimiento del CETPRO y bolsa de trabajo municipal", 15, "Academia Municipal de Formación Técnica", "40 % más matrículas en CETPRO y programas municipales"),
        P("social", "Centro Municipal de Especialidades Médicas, campañas preventivas y programa de control de anemia", 16, "Centro Municipal de Especialidades Médicas", "25 % menos anemia en menores de 5 años"),
        P("social", "Clínica veterinaria municipal y botica veterinaria, con campañas de salud animal y registro de mascotas", 17, "Creación de clínica veterinaria municipal"),
        P("social", "Construcción y equipamiento del Palacio de la Juventud para jóvenes, adultos mayores y madres solteras", 20, "Construcción y equipamiento del Palacio de la Juventud"),
        P("transporte", "Sótano de cochera municipal a costo social, previo estudio de factibilidad", 21, "Construir un sótano para cochera municipal a costo social", "Al menos 100 plazas de estacionamiento"),
        P("economia", "Eje gastronómico en las avenidas Agustín de la Rosa Toro, Del Aire, San Juan, San Luis y Manuel Echeandía", 23, "Implementación del eje gastronómico Av. Agustín de la Rosa Toro"),
        P("ambiente", "Ampliación del sistema de riego distrital, arborización y mantenimiento de parques con premios a sectores", 24, "Proyecto de ampliación del sistema de riego distrital", "30 % más arborización de parques y calles respecto al nivel actual"),
        P("urbano", "Programa de pavimentación y rehabilitación de calles y construcción de veredas accesibles", 25, "Programa de pavimentación y rehabilitación de calles", "90 % de calles rehabilitadas y 85 % de veredas"),
        P("gestion", "Trámites municipales en línea, app municipal para pagos y reclamos y chatbot de atención", 7, "Chatbot de atención 24/7", "Trámites 100 % en línea"),
    ]),
    ("María Rosario López Solano", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Renovar 6 unidades y sumar otras 6 a la flota de serenazgo, con más personal y patrullaje aéreo con drones", 13, "RENOVAR LA FLOTA VEHICULAR DE SERENAZGO (06 UNIDADES)", "6 unidades renovadas, 6 adicionales y 2 drones"),
        P("seguridad", "Más cámaras con analítica de comportamiento para detectar situaciones de riesgo y fibra óptica de soporte", 13, "ANALÍTICA DE COMPORTAMIENTO PARA DETECTAR SITUACIONES DE RIESGO"),
        P("seguridad", "Programa «Barrio Seguro, Mente Sana»: recuperar espacios oscuros o abandonados con iluminación y actividades culturales", 13, "RECUPERACIÓN DE ESPACIOS PÚBLICOS OSCUROS O ABANDONADOS"),
        P("social", "Centro «San Luis Joven» con cursos técnicos y psicólogos para orientación vocacional y prevención de adicciones", 15, "CENTRO DE INNOVACIÓN Y EMOCIONES"),
        P("social", "DEMUNA itinerante con psicólogos y abogados en los parques los fines de semana para prevenir la violencia familiar", 15, "LLEVAR CHARLAS DE PSICÓLOGOS Y ABOGADOS A LOS PARQUES"),
        P("economia", "Incubadora municipal «Emprende San Luis» para mujeres cabeza de hogar y jóvenes, con capital semilla y capacitación", 17, "INCUBADORA DE NEGOCIOS MUNICIPAL"),
        P("economia", "Corredores gastronómicos y talleres para emprendedores gastronómicos mediante convenios con universidades", 18, "IMPLEMENTACIÓN DE CORREDORES GASTRONOMICOS"),
        P("urbano", "Remodelar los parques para que sean inclusivos, con rampas, juegos para niños con discapacidad y espacios de lectura", 20, "REMODELACIÓN DE LOS PARQUES DEL DISTRITO PARA QUE SEAN INCLUSIVOS"),
        P("ambiente", "Programa de segregación de residuos en la fuente que premia a los vecinos con el mantenimiento de sus áreas verdes", 20, "PREMIANDO A LOS VECINOS PUNTUALES"),
        P("transporte", "Reparación de veredas y rampas y semaforización inteligente en avenidas críticas como Las Torres o San Luis", 21, "SEMAFORIZACIÓN INTELIGENTE EN AVENIDAS CRÍTICAS"),
        P("gestion", "Ventanilla única digital para trámites, presupuesto participativo con las juntas vecinales y oficina anticorrupción local", 21, "DIGITALIZACIÓN DE TRÁMITES PARA EVITAR COLAS INNECESARIAS"),
    ]),
    ("Christian Israel Pardo Reyes", "Visión Perú", "vision-peru", [
        P("seguridad", "Central de monitoreo del serenazgo interconectada con las comisarías, bomberos y Central 105, y plan de reacción inmediata con la PNP", 5, "interconectada con las Comisarías de San Luis y Yerbateros"),
        P("seguridad", "Cámaras de última generación integradas al sistema de reconocimiento facial con inteligencia artificial de la PNP", 5, "sistema de reconocimiento facial con inteligencia artificial"),
        P("transporte", "Prohibir paraderos informales, ordenar estacionamientos y construir ciclovías con estacionamientos vigilados de bicicletas", 6, "espacios vigilados de estacionamientos de bicicletas"),
        P("ambiente", "Instalación de contenedores soterrados para reducir la basura en veredas y pistas e impulsar el reciclaje", 6, "instalación de contenedores soterrados"),
        P("social", "Recuperar el complejo deportivo de la Av. Circunvalación con skate park y piscina todo el año, y juegos escolares en el Parque Zonal Túpac Amaru", 6, "construcción de un skate park"),
        P("social", "Guardería municipal para madres jóvenes y puesta en valor de las huacas Túpac Amaru A y B", 7, "Crearemos la Guardería Municipal"),
        P("social", "Gestionar ante el MINSA que el Centro de Salud de San Luis sea hospital de segundo nivel y reabrir la posta de San Pablo", 8, "Convertiremos en un Hospital de Segundo Nivel"),
        P("urbano", "Construir la alameda de Túpac Amaru, el parque de Yerbateros, un velatorio municipal y el Centro Cívico de San Luis", 8, "Construiremos el Centro Cívico de San Luis"),
        P("urbano", "Pavimentación, iluminación y recuperación de las avenidas San Juan, Río Chincha, San Luis, Manuel Beingolea, Rosa Toro y otras", 8, "recuperación total de las avenidas San Juan"),
        P("gestion", "Trámites municipales en línea y zonas wifi gratuitas en parques, paraderos y centros de atención", 8, "CIUDAD DIGITAL"),
        P("economia", "Incubadora municipal de negocios para que estudiantes y profesionales del distrito desarrollen startups", 10, "incubadora de negocios que crearemos"),
    ]),
]
