"""Lurigancho-Chosica (150118): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150118"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Ilich Iván Pumacayo Palomino", "Acción Popular", "accion-popular", [
        P("seguridad", "Cámaras con reconocimiento facial y de placas, módulos de seguridad por zonas y más vehículos para el patrullaje del serenazgo", 2, "Cámaras de video de reconocimiento facial", "Reducir la delincuencia en 60 %"),
        P("social", "Talleres de prevención de la violencia familiar y juvenil con apoyo psicológico en cada zona o sector", 6, "Realizaremos 01 taller", "Un taller semanal o quincenal en cada zona o sector"),
        P("urbano", "Recuperar parques, áreas deportivas y campos deportivos, y construir el palacio de la juventud", 6, "Recuperación de parques", "100 parques y espacios deportivos recuperados al final de la gestión"),
        P("social", "Campañas médicas en los anexos, nueva ambulancia y gestión del financiamiento del hospital de Lurigancho-Chosica", 6, "48 campañas en anexos", "48 campañas en anexos"),
        P("economia", "Convenios con institutos y universidades para capacitar a jóvenes en carreras técnicas y programas de empleabilidad", 7, "Desempleo juvenil Creación de convenios", "Capacitar a 20 000 jóvenes"),
        P("economia", "Apoyo a la formalización de pequeños negocios y comerciantes", 7, "Apoyo total a nuestros pequeños comerciantes", "Formalización de 5 000 negocios o comerciantes"),
        P("ambiente", "Programas de reciclaje en todo el distrito y arborización en todas las comunas", 8, "Ejecutar programas de arborización", "60 % más de reciclaje y 1 000 árboles plantados al año"),
        P("ambiente", "Limpieza y fiscalización ambiental del río Rímac", 8, "Retirar 500 toneladas", "500 toneladas de residuos retiradas del cauce al año"),
        P("agua_riesgos", "Descolmatar más quebradas que en 2026 y ampliar los sistemas de alerta temprana ante huaicos", 8, "Reducir vulnerabilidad", "100 % más de quebradas descolmatadas que en 2026"),
        P("gestion", "Digitalizar todos los trámites municipales para reducir los tiempos de atención", 8, "Reducir tiempos en 70%", "Reducir los tiempos de trámite en 70 %"),
        P("gestion", "Construir un palacio municipal en la parte baja del distrito para descentralizar la atención", 9, "palacio municipal en la parte baja del distrito"),
    ]),
    ("Carlos Alberto Vargas Vera", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Instalar nuevas cámaras de seguridad con inteligencia artificial y capacitar a más serenos para dirigir el tránsito", 20, "Se instalarán nuevas cámaras de seguridad con inteligencia artificial"),
        P("seguridad", "Gestionar una comisaría en la zona baja del distrito y ceder a la PNP un depósito para vehículos siniestrados", 20, "Se gestionará la construcción de una Comisaría en la zona baja"),
        P("social", "Mejorar la infraestructura deportiva y construir un polideportivo en la zona baja del distrito", 20, "se construirá un Polideportivo en la zona baja del distrito"),
        P("gestion", "Descentralizar servicios con locales en la zona baja y crear una «Ventana Virtual» de transparencia", 20, "Se descentralizarán algunos servicios importantes"),
        P("gestion", "Diagnóstico y modernización de la estructura orgánica y los documentos de gestión de la municipalidad", 33, "Modernización de la estructura orgánica de la Municipalidad", "100 % al final del primer año"),
        P("economia", "Mejorar los servicios turísticos y construir un teleférico hacia la Cruz de San José", 21, "Se construirá un teleférico hacia la Cruz de San José"),
        P("transporte", "Gestionar puentes definitivos Tumi y Cadena en Cajamarquilla y un nuevo puente de acceso a La Cantuta", 21, "puentes definitivos: TUMI y CADENA"),
        P("urbano", "Asfaltado, parchado y mantenimiento de pistas y veredas priorizadas", 31, "20% de rehabilitación y/o asfaltado de pistas y veredas", "20 % de pistas y veredas rehabilitadas o asfaltadas y 40 % con mantenimiento al segundo año"),
        P("ambiente", "Programa de forestación y reforestación en todo el distrito", 21, "Programa de forestación y reforestación en todo el Distrito"),
        P("economia", "Capacitar a los artesanos del distrito y apoyarlos en la mejora de sus puestos de venta y su publicidad", 31, "25% de los artesanos de la localidad capacitados al 1° año", "25 % de los artesanos capacitados cada año"),
        P("agua_riesgos", "Mejorar y potabilizar el agua para uso doméstico y gestionar el financiamiento de obras de saneamiento", 20, "Mejorar y potabilizar el recurso hídrico para uso doméstico"),
    ]),
    ("Víctor Arturo Castillo Sánchez", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Más cámaras enlazadas con la PNP, patrullaje integrado y juntas vecinales equipadas con radios, alarmas y cámaras", 44, "Activar las Juntas Vecinales e implementarlos con equipo de radio"),
        P("transporte", "Plan integral de formalización de mototaxis, paraderos y semáforos, y gestión de vías alternas y puentes", 27, "Plan Integral de Formalización del Transporte de Vehículos Menores"),
        P("social", "Promover la construcción o mejora del Hospital de Chosica y su equipamiento con profesionales", 26, "construcción o mejoramiento de la infraestructura del Hospital de Chosica"),
        P("social", "Paquetes escolares y becas de computación e inglés para estudiantes de las instituciones educativas más pobres", 32, "becas de estudio en computación e inglés"),
        P("social", "Espacios multideportivos en los sectores y uso permanente y gratuito del Estadio Municipal", 33, "dar uso permanente y sin costo alguno del Estadio Municipal"),
        P("agua_riesgos", "Renovar las redes de agua y desagüe que administra la municipalidad, con más de 30 años de antigüedad, y gestionar plantas de tratamiento", 35, "renovar las redes de agua y desagüe de los sectores que administra la municipalidad"),
        P("economia", "Centro de distribución logística para tiendas de Lima y mercado de acopio de productos agrícolas", 38, "lo que generará más empleos que deben superar 500 empleos", "Más de 500 empleos"),
        P("ambiente", "Compactadoras para la limpieza pública, planta de tratamiento de residuos sólidos y plantas de aguas servidas", 48, "Gestionar la construcción de una planta de tratamiento de residuos sólidos"),
        P("agua_riesgos", "Maquinaria pesada para descolmatar el río Rímac y las quebradas entre abril y noviembre, muros, diques y COE descentralizados", 50, "Adquirir maquinaria pesada para desarrollar trabajos de prevención"),
        P("urbano", "Saneamiento físico legal de terrenos y asesoría a asentamientos humanos para acceder a la electrificación", 36, "Promover el saneamiento físico legal de los terrenos"),
        P("gestion", "Trámites con seguimiento en tiempo real y sesiones de concejo descentralizadas con participación de dirigentes", 43, "sesiones de concejo descentralizados"),
    ]),
    (None, "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Centrales de monitoreo del Sistema de Respuesta Inmediata Municipal, cámaras con reconocimiento facial, casetas y camionetas de serenazgo", 6, "Sistema de Respuesta Inmediata Municipal", "3 centrales de monitoreo"),
        P("social", "Construir el policlínico municipal en Cajamarquilla y ampliar campañas de salud móviles", 7, "Construcción del policlínico Municipal en Cajamarquilla"),
        P("social", "Villas deportivas, olimpiadas interescolares y campeonatos interbarrios de vóley y fútbol", 7, "VILLA DEPORTIVAS", "3 villas deportivas"),
        P("social", "Casas del Adulto Mayor en Chosica casco urbano, Chosica centro y Chosica baja", 7, "la Casa del Adulto Mayor", "3 Casas del Adulto Mayor"),
        P("social", "Nuevas sedes de la Casa de la Mujer en Cajamarquilla y La Era-Ñaña contra la violencia hacia la mujer", 7, "dos cedes para el funcionamiento", "2 nuevas sedes"),
        P("economia", "Centros de formación tecnológica municipal (CEFOTEM) y ampliación de la bolsa de trabajo", 8, "Centros de formación tecnológico municipal", "3 centros"),
        P("transporte", "Programa «Cero Congestionamiento Vehicular», semáforos en vías críticas y formalización de mototaxis", 9, "Instalar semáforos en vías críticas"),
        P("agua_riesgos", "Módulos del sistema de alerta temprana, centro de operaciones de emergencia y muros de contención en quebradas", 9, "módulos de material noble para el funcionamiento del sistema de alerta temprana", "12 módulos del sistema de alerta temprana"),
        P("ambiente", "Segregación en la fuente, concurso de buenas prácticas ambientales y arborización de cerros", 9, "arborizar algunos cerros del distrito"),
        P("urbano", "Pistas, veredas, muros de contención y escaleras en diversos sectores, y gestión de la ampliación de la autopista Ramiro Prialé", 10, "Construcción de muros de contención y escaleras"),
        P("gestion", "Descentralizar los servicios administrativos, audiencias públicas anuales y presupuesto participativo abierto a toda la ciudadanía", 11, "descentralizar los servicios administrativo"),
    ]),
    ("Rafael David Huaringa Saavedra", "Cooperación, Verdad y Honradez", "cooperacion-verdad-y-honradez", [
        P("agua_riesgos", "Aprovechar el agua subterránea con plantas de tratamiento y reservorios con potabilización", 7, "Explotación de la napa friática"),
        P("agua_riesgos", "Proyectos de descolmatación, encauzamiento, diques y mallas geodinámicas en las zonas más críticas", 7, "colocación de diques y mallas geodinámicas"),
        P("seguridad", "Videovigilancia con reconocimiento facial en puntos críticos, drones y comités de seguridad ciudadana capacitados y equipados", 7, "comités de seguridad ciudadana al cual se le capacitará"),
        P("social", "Unidades móviles con medicinas básicas y acciones contra la desnutrición crónica", 8, "con atención de medicinas básicas"),
        P("social", "Becas integrales para los mejores alumnos y gestión de equipos de cómputo para colegios", 8, "Se promoverá becas integrales"),
        P("social", "Guardería infantil municipal, fortalecimiento de la DEMUNA y microempresas en comedores populares y vaso de leche", 8, "Creación de centro de cuidados (guardería infantil)"),
        P("transporte", "Formalización de mototaxis con plazos y capacitación de fiscalizadores y conductores", 9, "Se ejecutará un plan de acción de formalización al 100%", "Formalización al 100 %"),
        P("economia", "Facilidades a empresas privadas para invertir en miradores, teleféricos, deportes de aventura y atractivos turísticos", 9, "invertir en miradores, teleféricos"),
        P("economia", "Mesas con el sector empresarial, convenios con entidades financieras para microempresas y ferias de productos", 10, "convenios con instituciones financieras"),
        P("transporte", "Plan vial distrital con prioridad al peatón y gestión de cambios en las rutas del transporte público", 10, "la creación de un plan vial distrital"),
        P("gestion", "Plataforma web de datos abiertos sobre contrataciones, sueldos y presupuesto, y audiencias descentralizadas", 11, "plataforma web de datos abiertos"),
    ]),
    ("Alfredo Javier Mujica Pastrana", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Central de monitoreo con inteligencia artificial y lectura de placas en los tres ingresos principales del distrito", 4, "Instalar una Central de Monitoreo con Inteligencia Artificial", "En el primer año"),
        P("seguridad", "Nuevas camionetas y motocicletas para patrullaje del serenazgo las 24 horas en zonas periféricas", 5, "Adquirir 30 camionetas y 50 motocicletas", "30 camionetas y 50 motocicletas; 35 % menos percepción de inseguridad al cuarto año"),
        P("seguridad", "Programa «Barrio Seguro Digital» con alarmas vecinales interconectadas y botones de pánico", 5, "entregando alarmas vecinales interconectadas", "100 comités vecinales"),
        P("agua_riesgos", "Mantenimiento de todos los pozos de extracción y construcción de nuevos pozos y reservorios automatizados", 6, "3 nuevos pozos de extracción y reservorios automatizados", "3 pozos y reservorios nuevos; duplicar las horas de abastecimiento"),
        P("social", "Plan de cloración automatizada del agua y kits de purificación comunales para reducir enfermedades infantiles", 6, "Plan de Cloración Automatizada Distrital", "40 % menos enfermedades estomacales y parasitarias en menores de 5 años en los sectores intervenidos"),
        P("ambiente", "Plan distrital de fiscalización ambiental sobre puntos críticos de contaminación", 8, "erradicando y/o mitigando 48 puntos críticos", "48 puntos críticos erradicados o mitigados en el primer año"),
        P("ambiente", "Programa «Chosica Respira Verde» con corredores ecológicos y formalización de ladrilleras", 9, "plantación de más de 10,000 árboles", "Más de 10 000 árboles y especies nativas"),
        P("agua_riesgos", "Programa «Escudo Chosica»: descolmatación del Rímac y quebradas, alerta temprana y defensas ribereñas", 12, "descolmatación total del Río Rímac y las 10 quebradas priorizadas", "10 quebradas descolmatadas y defensas en 19 puntos críticos del río"),
        P("economia", "Mercados populares techados para reubicar a ambulantes censados y recuperación de espacios públicos", 13, "Lograr la recuperación y liberación del 80%", "80 % de espacios públicos del centro de Chosica, Carapongo y Jicamarca recuperados"),
        P("transporte", "Empadronamiento digital de mototaxis con código QR y escuela municipal gratuita para conductores", 14, "Empadronamiento Distrital Único de Mototaxis"),
        P("gestion", "Portal de datos abiertos y agencias de Jicamarca y Carapongo con ventanillas completas de servicios", 15, "Reestructurar las agencias municipales de Jicamarca y Carapongo", "2 audiencias públicas al año"),
    ]),
    ("Ramón Tinta Soriano", "Partido del Buen Gobierno", "partido-del-buen-gobierno", [
        P("seguridad", "Centro integrado de videovigilancia con reconocimiento facial en puntos de mayor incidencia y serenazgo las 24 horas", 5, "en los 20 puntos de mayor incidencia delictiva", "Reducir 30 % la delincuencia y violencia al 2030"),
        P("agua_riesgos", "Sistema de alerta temprana SAT-Chosica en quebradas, brigadistas comunitarios y simulacros distritales", 19, "SAT-Chosica operativo en 15 quebradas al 2028", "15 quebradas al 2028, 800 brigadistas y 4 simulacros al año"),
        P("agua_riesgos", "Gestionar ante el Ministerio de Vivienda la reubicación de familias en zonas de riesgo no mitigable", 7, "Gestionar ante el Ministerio de Vivienda la reubicación de familias", "200 familias al 2030"),
        P("social", "Centros de atención psicológica comunitaria y unidades móviles de salud mensuales en zonas alejadas", 8, "Implementar 3 Centros de Atención Psicológica Comunitaria", "3 centros"),
        P("social", "Becas municipales de estudios técnicos y superiores y Casa de la Juventud Chosicana", 9, "Becas municipales para el 70% de jóvenes", "Becas para el 70 % de jóvenes en pobreza que quieran estudiar"),
        P("economia", "Licencias más rápidas, feria mensual «Hecho en Chosica» y centro municipal de emprendimiento", 11, "reducir de 15 a 5 días el tiempo para licencias", "Licencias en 5 días (hoy 15)"),
        P("economia", "Crear una Caja Municipal de Ahorro y Crédito para reducir la informalidad de las MYPE", 12, "Creación e implementación de una Caja Municipal de Ahorro y Crédito (2028)", "Caja municipal en 2028; informalidad de MYPE de 85 % a 61 % al 2030"),
        P("urbano", "Pavimentación de vías, losas deportivas en zonas periféricas y alumbrado LED", 13, "priorizar 50 km de vías en mal estado", "50 km de vías y 10 losas deportivas"),
        P("transporte", "Gestionar ante el MTC la Nueva Carretera Central para sacar el tránsito pesado del casco urbano", 13, "Gestionar ante el MTC la Nueva Carretera Central"),
        P("ambiente", "Reforestación de laderas y riberas del Rímac y segregación de residuos en la fuente", 14, "plantar 10,000 árboles/año en laderas", "10 000 árboles al año; segregación en el 80 % del distrito al 2029"),
        P("gestion", "Portal de transparencia en tiempo real, app de trámites y agencias descentralizadas en Huachipa, Nievería y Cajamarquilla", 16, "reducir trámites municipales de 30 días promedio a 5 días", "Trámites en 5 días (hoy 30)"),
    ]),
    ("Luis Fernando Bueno Quino", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Central integrada de videovigilancia con inteligencia artificial, patrullaje georreferenciado, alarmas vecinales y drones", 57, "Central integrada de videovigilancia con inteligencia artificial"),
        P("social", "Campañas integrales de salud preventiva y nuevas ambulancias", 47, "120 campañas ejecutadas 06 ambulancias", "120 campañas y 6 ambulancias"),
        P("social", "Programa municipal de reforzamiento escolar y habilidades digitales para niños y jóvenes", 47, "25,000 estudiantes atendidos", "25 000 estudiantes atendidos"),
        P("economia", "Programas de primer empleo y bolsa laboral juvenil", 48, "Programas de primer empleo y bolsa laboral juvenil", "8 000 jóvenes colocados"),
        P("economia", "Programa de formalización y centros municipales de desarrollo empresarial descentralizados", 49, "8,000 emprendedores formalizados", "8 000 emprendedores formalizados y 6 centros empresariales"),
        P("economia", "Plan turístico distrital con circuitos, recuperación de espacios turísticos y festivales", 50, "5 circuitos turísticos consolidados", "5 circuitos turísticos y 20 eventos al año"),
        P("urbano", "Mejoramiento integral de barrios, recuperación de espacios públicos y luminarias LED", 51, "25,000 luminarias instaladas", "50 barrios mejorados, 120 espacios públicos recuperados y 25 000 luminarias"),
        P("transporte", "Plan de movilidad con semaforización inteligente y rehabilitación de vías", 51, "52 intersecciones inteligentes", "52 intersecciones inteligentes y 120 km de vías mejoradas"),
        P("ambiente", "Recuperación de la ribera del Rímac, malecones ecológicos y arborización", 52, "120,000 árboles sembrados", "18 km de ribera recuperados, 120 000 árboles y 4 malecones"),
        P("agua_riesgos", "Protección de quebradas, descolmatación, brigadas vecinales y simulacros descentralizados", 53, "16 quebradas priorizadas", "16 quebradas intervenidas, 60 km descolmatados y 300 brigadas"),
        P("gestion", "Simplificación y digitalización de trámites y audiencias descentralizadas de rendición de cuentas", 53, "95% de trámites virtualizados", "95 % de trámites virtualizados"),
    ]),
    ("Olimpio López Mañuico", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Pórticos de seguridad con cámaras inteligentes en los accesos y más cámaras de videovigilancia", 38, "Implementar 150 cámaras y 30 pórticos inteligentes", "150 cámaras y 30 pórticos inteligentes"),
        P("social", "Clínica municipal en Cajamarquilla y telemedicina y médicos a domicilio para mayores de 65 años", 24, "Construcción de la Clínica Municipal en la zona de Cajamarquilla"),
        P("social", "Academia municipal preuniversitaria y wifi gratuito en parques y locales comunales", 26, "Incorporar wifi gratuito en 10 parques y 20 locales comunales", "Wifi en 10 parques y 20 locales comunales"),
        P("agua_riesgos", "Plantas de tratamiento para dar agua potable, también en los pueblos de la UTAPP que hoy consumen agua de regadío", 27, "Construcción de 2 plantas de tratamiento de agua"),
        P("economia", "Licencias temporales para regularizar comercios y trámites de licencias informatizados", 40, "Formalizar 3,000 negocios", "3 000 negocios formalizados"),
        P("economia", "Corredor gastronómico Carapongo–Chosica y puesta en valor de los geoglifos de Yanacoto y Cajamarquilla", 29, "Implementar de Corredor Gastronómico en Carapongo"),
        P("agua_riesgos", "Maquinaria pesada para descolmatar cauces y el río Rímac, muros, diques y mallas geodinámicas en quebradas", 32, "Compra de un pul de maquinarias pesada"),
        P("transporte", "Puentes de interconexión Caracol y La Trinchera y gestión de la avenida Cajamarquilla", 33, "puentes de interconexión: puente caracol"),
        P("urbano", "Programa municipal de titulación y habilitaciones urbanas de oficio", 42, "Gestionar 5 000 expedientes 80 habilitaciones", "5 000 expedientes de titulación y 80 habilitaciones urbanas"),
        P("ambiente", "Remodelación de parques emblemáticos y ampliación del reciclaje", 41, "Recuperar 20 parques Aumentar en 30% el reciclaje", "20 parques recuperados y 30 % más reciclaje"),
        P("gestion", "Trámites en línea, expediente electrónico, dos agencias municipales y cámaras corporales para el personal de intervención", 42, "Digitalizar el 60% de los trámites municipales", "60 % de trámites digitalizados y 50 % menos tiempo de atención"),
    ]),
    ("María Marisol Quinto Rojas", "Perú Moderno", "peru-moderno", [
        P("seguridad", "Ampliar el centro de emergencia y monitoreo con cámaras con IA y lector de placas, conectado a la app «Alerta Chosica»", 116, "a más de 200 cámaras IA operativas con lector de placas", "Más de 200 cámaras con IA y 50 000 usuarios de la app"),
        P("social", "Sedes de la Farmacia Municipal en las agencias de Ñaña, Carapongo, Huachipa, Cajamarquilla y Jicamarca", 114, "Descentralizar la Farmacia Municipal mediante la apertura de sedes en las 5 agencias municipales", "Sedes en las 5 agencias municipales"),
        P("social", "Visitas domiciliarias preventivas y acciones contra la desnutrición crónica infantil y la anemia en gestantes", 114, "Reducir la DCI en el distrito a menos del 10%", "Desnutrición crónica infantil bajo 10 % y anemia en gestantes bajo 6 %"),
        P("agua_riesgos", "Ejecutar proyectos mayores de agua y saneamiento, como el bombeo de Mariscal Castilla y las redes del Sector 144", 115, "Reducir la población sin agua por red pública a menos del 15%", "Población sin agua por red pública bajo 15 %"),
        P("social", "Culminar el Coliseo Cerrado Carmela Estrella y el Complejo Deportivo Torres de Huachipa, y construir dos polideportivos", 115, "Coliseo Cerrado Carmela Estrella", "Déficit de espacios deportivos comunales al 20 %"),
        P("transporte", "Certificados de operación de mototaxis digitales con código QR y empadronamiento en asociaciones formales", 116, "empadronando a más de 3,500 mototaxis", "Más de 3 500 mototaxis empadronados"),
        P("urbano", "Pavimentar vías locales y reconstruir veredas accesibles en zonas periféricas; gestionar el tren de cercanía Lima–Chosica", 116, "Pavimentar un acumulado mínimo de 8 kilómetros de vías locales", "Al menos 8 km de vías pavimentadas"),
        P("economia", "Ventanilla única de formalización y licencias automatizadas por web", 117, "Disminuir el índice de informalidad empresarial de las MYPEs al 40%", "Informalidad de MYPE al 40 %"),
        P("ambiente", "Primera fase de una planta de reciclaje y valorización de residuos en terrenos municipales", 118, "Implementar la primera fase de operación de la planta de reciclaje", "Más de 2 000 t de inorgánicos y 600 t de orgánicos valorizados al año"),
        P("agua_riesgos", "Descolmatación mecánica bianual de quebradas críticas, mallas dinámicas operativas y reforestación de laderas", 119, "descolmatación mecánica de un tramo de 7 kilómetros lineales en las 25 quebradas críticas", "7 km en 25 quebradas críticas, dos veces al año"),
        P("gestion", "Gobierno digital con firma digital y política de cero papel", 120, "Elevar el Índice de Desarrollo de Gobierno Digital del municipio al 75%", "Índice de gobierno digital al 75 %"),
    ]),
    ("Carlos Alberto Jesús Paucarchuco", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Modernizar el centro de videovigilancia y monitoreo, más unidades de serenazgo y patrullaje integrado con la PNP", 26, "Implementar y modernizar el Centro Integral de Videovigilancia y Monitoreo Distrital"),
        P("social", "Policlínico municipal con servicios especializados y programas contra la anemia y la desnutrición crónica", 28, "Impulsar la implementación de un policlínico municipal"),
        P("social", "Convenios con PRONIED para infraestructura escolar y ferias educativas y laborales para jóvenes", 29, "Impulsaremos convenios con el Programa Nacional de Infraestructura Educativa"),
        P("agua_riesgos", "Programa de mejoramiento de redes de agua y alcantarillado, reservorios y catastro para reducir conexiones clandestinas", 30, "Implementaremos un Programa Integral de Mejoramiento de la Infraestructura Sanitaria"),
        P("social", "Veterinaria municipal a costos sociales y campañas descentralizadas de vacunación y esterilización", 33, "Implementaremos la Veterinaria Municipal de Lurigancho-Chosica"),
        P("transporte", "Programa integral de formalización del transporte menor con paraderos señalizados y códigos de registro visibles", 34, "Implementaremos un Programa Integral de Formalización del Transporte Menor"),
        P("economia", "Centro de Desarrollo Empresarial y Emprendimiento con capacitación, asistencia técnica y formalización", 35, "Crearemos el Centro de Desarrollo Empresarial y Emprendimiento"),
        P("economia", "Marca territorial «Valle Ecológico y Destino de Bienestar», circuitos turísticos y servicios higiénicos públicos", 36, "Posicionaremos la marca territorial"),
        P("agua_riesgos", "Plan distrital de gestión del riesgo con descolmatación, muros de contención y drenaje pluvial", 36, "Elaboraremos e implementaremos el Plan Distrital de Gestión del Riesgo de Desastres"),
        P("ambiente", "Plan de arborización y ampliación de parques, con segregación en la fuente y reciclaje", 38, "Ejecutar un plan de arborización urbana"),
        P("gestion", "Audiencias semestrales de rendición de cuentas y transmisión en línea de las sesiones del Concejo", 39, "Implementar la transmisión en línea de las sesiones del Concejo Municipal"),
    ]),
    ("Timoteo Francisco Nishijima Villavicencio", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Centros integrados de emergencia y monitoreo, videovigilancia inteligente y patrullaje integrado serenazgo–PNP", 10, "500 cámaras inteligentes", "500 cámaras inteligentes, 3 centros de monitoreo y 50 % más de patrullaje integrado"),
        P("social", "Intervenir instituciones educativas, crear el CETPRO Metropolitano de Lima Este y capacitar técnicamente a jóvenes", 10, "20 instituciones educativas intervenidas", "20 colegios intervenidos, 1 CETPRO y 5 000 jóvenes capacitados"),
        P("social", "Policlínicos móviles y campañas médicas preventivas descentralizadas", 10, "100 campañas médicas descentralizadas", "100 campañas médicas y 2 policlínicos móviles"),
        P("urbano", "Recuperar parques, alamedas y plazas y construir complejos deportivos", 10, "15 parques y alamedas", "100 000 m² de espacios públicos, 15 parques y alamedas y 5 complejos deportivos"),
        P("economia", "Corredores comerciales formales, facilidades para formalizar ambulantes y modernización de mercados", 6, "Implementar corredores comerciales formales ordenados"),
        P("economia", "Marca «Chosica Vive», puesta en valor de Cajamarquilla y los geoglifos, miradores y rutas ecológicas", 6, "Posicionar la marca territorial"),
        P("agua_riesgos", "Muros de contención y defensas ribereñas, descolmatación de quebradas, alerta temprana y drenaje pluvial", 7, "Ejecutar obras de muros de contención y defensas ribereñas"),
        P("ambiente", "Gran Parque Metropolitano del Río Rímac, arborización y recuperación de las riberas del Rímac y el Huaycoloro", 7, "Desarrollar el Gran Parque Metropolitano del Río Rímac"),
        P("transporte", "Mejora de vías, semaforización inteligente, corredor vial en la margen izquierda del Rímac y teleféricos a largo plazo", 11, "50 km de vías urbanas mejoradas", "50 km de vías urbanas mejoradas"),
        P("urbano", "Catastro digital, saneamiento físico-legal de predios y actualización del Plan de Desarrollo Urbano", 8, "Implementar el catastro digital distrital"),
        P("gestion", "Audiencias públicas descentralizadas y plataforma digital de seguimiento de obras y presupuesto", 11, "04 audiencias públicas anuales", "4 audiencias públicas al año"),
    ]),
]
