"""San Juan de Lurigancho (150132): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150132"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Luis Gino Blanco Aldama", "Acción Popular", "accion-popular", [
        P("seguridad", "Cámaras con reconocimiento facial y lectura de placas, más flota del serenazgo y patrullaje por cuadrantes en las 8 macrozonas y 27 comunas", 6, "Ampliación de la flota del Serenazgo", "+200 % de cámaras, +200 % de patrullajes y reducción de la delincuencia en un 60 %"),
        P("social", "Programas de prevención de la violencia familiar y juvenil con soporte psicológico a las familias en cada comuna", 6, "Implementación de 30 programas sociales de apoyo en cada comuna", "1 taller semanal por comuna y 30 programas sociales de apoyo en cada comuna"),
        P("urbano", "Recuperar áreas verdes y gestionar ante la Municipalidad de Lima la administración del Parque Zonal Huiracocha", 6, "recuperar la administración del Parque Zonal Huiracocha"),
        P("economia", "Institutos tecnológicos gratuitos con carreras técnicas y bolsas de empleo para jóvenes", 6, "Creación de Institutos Tecnológicos", "Capacitar a 100,000 jóvenes"),
        P("economia", "Crear la Caja Municipal de Ahorro y Crédito de San Juan de Lurigancho y facilitar trámites para formalizar negocios", 6, "Informalidad comercial Facilitación de trámites", "+200 % de licencias otorgadas respecto a 2026 y 10,000 negocios formalizados"),
        P("economia", "Planificar y promover un Parque Industrial para albergar y formalizar mypes, con corredores comerciales e industriales en las 8 macrozonas", 4, "Parque Industrial de San Juan de Lurigancho"),
        P("urbano", "Plan de inversión multianual: rehabilitación y semaforización de vías, apertura de nuevas vías, pavimentación y muros de contención en comunas emergentes", 3, "Plan de Inversión Multianual en Infraestructura Pública"),
        P("ambiente", "Programas de segregación y reciclaje, arborización por comunas y reestructuración de las rutas de limpieza pública", 7, "Incrementar el reciclaje en un 60%", "Reciclaje +60 %, 1,000 árboles plantados al año y recojo en el 100 % del distrito"),
        P("gestion", "Digitalizar trámites, reestructurar el otorgamiento de licencias de funcionamiento y abrir agencias municipales en las 8 macrozonas", 4, "agencias municipales estratégicamente distribuidas"),
        P("gestion", "Audiencias públicas trimestrales, comités vecinales de vigilancia de obras y portal de transparencia actualizado en tiempo real", 8, "Audiencias Públicas Trimestrales"),
    ]),
    ("Elsa Virginia Alarcón Suárez", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Central Municipal Integrada de Emergencias, con medición del tiempo de respuesta del serenazgo y mejora de vehículos, comunicaciones y capacitación", 15, "Implementar una Central Municipal Integrada de Emergencias"),
        P("seguridad", "Patrullaje focalizado y a pie en zonas críticas, integrando cámaras municipales y vecinales a un sistema inteligente de monitoreo", 16, "Integrar progresivamente las cámaras municipales y las cámaras vecinales", "100 % de las zonas críticas priorizadas en 2030"),
        P("agua_riesgos", "Registro municipal de roturas, aniegos y cortes de agua para priorizarlos y hacer seguimiento ante SEDAPAL; asistencia a familias para tramitar conexiones", 17, "registro municipal de roturas de tuberías, aniegos"),
        P("social", "Intervenciones de salud y nutrición contra la anemia infantil y la tuberculosis, coordinadas con MINSA, DIRIS, comedores y ollas comunes", 18, "Las intervenciones se ampliarán de 6 comunas en 2027", "De 6 comunas en 2027 a las 18 comunas en 2030"),
        P("social", "Academia Preuniversitaria Municipal para jóvenes de menores recursos, talleres digitales y de educación financiera y puntos de internet gratuito", 19, "Implementar una Academia Preuniversitaria Municipal", "25 000 personas beneficiarias en 2030"),
        P("economia", "Fortalecer la Bolsa de Trabajo Municipal, ferias laborales descentralizadas y convenios para prácticas y primer empleo", 20, "Fortalecer la Bolsa de Trabajo Municipal", "8 000 personas con acceso a oportunidades laborales en 2030"),
        P("economia", "Orientación y acompañamiento para licencias y formalización de mypes, con regularización antes de aplicar cierres", 21, "apoyará la formalización o regularización de 1 500 unidades", "10 000 unidades económicas formalizadas o regularizadas en 2030"),
        P("ambiente", "Inventario de áreas verdes, recuperación de parques, arborización, fortalecimiento del vivero municipal y riego eficiente", 26, "fortalecimiento del vivero municipal", "6,3 m² de áreas verdes por habitante en 2030"),
        P("agua_riesgos", "Estabilización de laderas, muros de contención, reforzamiento de pircas y escaleras en sectores críticos, previa evaluación de riesgo", 28, "estabilización de laderas, muros de contención, reforzamiento de pircas", "80 % de los sectores críticos priorizados en 2030"),
        P("gestion", "Simplificar y digitalizar trámites con plataforma de expedientes en línea, manteniendo atención presencial", 30, "75 % de los trámites municipales prioritarios", "95 % de los trámites prioritarios atendidos dentro del plazo en 2030"),
        P("gestion", "Sistema de participación con cuatro Mesas Territoriales, una por cuadrante, que representen a las 18 comunas", 32, "Instalar una Mesa Territorial en cada uno de los cuatro cuadrantes", "4 Mesas Territoriales instaladas en 2027"),
    ]),
    ("Heisen Odorico Herrera Conopuma", "Alianza Electoral Venceremos", "alianza-electoral-venceremos", [
        P("economia", "Programa «Tu Negocio, Tu Futuro»: mesas de diálogo y registro simplificado para formalizar progresivamente a comerciantes ambulantes, sin desalojos", 20, "Implementaremos un sistema simplificado de registro y orientación"),
        P("economia", "«Cachina Plaza»: mercado popular en la zona de Juan Pablo II para formalizar a los comerciantes desalojados de La Cachina", 22, "mercado popular moderno que permitirá la transición"),
        P("social", "Academia preuniversitaria municipal con tarifa social, acceso gratuito para familias en extrema pobreza y pago de inscripción a exámenes de admisión", 24, "tarifa social no mayor a S/100 mensuales"),
        P("social", "Construir dos CETPRO en Bayóvar y Juan Pablo II con carreras técnicas y apoyo a emprendimientos juveniles", 24, "Construcción de dos CETPROS para formar juventud técnica", "2 CETPRO"),
        P("social", "Construir el Gran Centro Cultural en Montenegro y un nuevo Teatro Municipal en una zona más céntrica", 26, "Gran Centro Cultural de San Juan de Lurigancho en el sector de Montenegro"),
        P("seguridad", "Ampliar la red de videovigilancia con cámaras con inteligencia artificial y drones, y centros de monitoreo en Bayóvar y Huáscar", 30, "hasta alcanzar 1,200 cámaras inteligentes", "De 610 a 1,200 cámaras inteligentes"),
        P("transporte", "Paraderos formales de mototaxis y modernización de paraderos de combis, con ordenamiento de rutas y programa contra la extorsión a transportistas", 37, "paraderos formales de mototaxis en puntos estratégicos"),
        P("urbano", "Peatonalización progresiva de la avenida Gran Chimú y recuperación de la Plaza Palestina con áreas verdes y espacios para comercio formal", 41, "peatonalización progresiva de la avenida Gran Chimú"),
        P("ambiente", "Red de compostaje urbano con reservorios en mercados para producir abono destinado a las áreas verdes", 35, "reservorios urbanos de compostaje ubicados en mercados"),
        P("urbano", "Registro de formalización de predios con Vivienda, COFOPRI y SUNARP, y comité trimestral contra el tráfico de terrenos en zonas de riesgo", 46, "registro de formalización de predios informales"),
        P("social", "Farmacias municipales autogestionadas en las zonas altas para adultos mayores y familias en pobreza extrema", 49, "Construir 8 Farmacias", "8 farmacias municipales al 2030"),
    ]),
    ("Juan Valentín Navarro Jiménez", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Más serenos, inteligencia artificial para reconocimiento facial y programa «Calle Segura» con serenazgo permanente en puntos críticos", 31, "incrementar en 300 serenos el número existente", "300 serenos más"),
        P("seguridad", "Gestionar el retiro de los dos establecimientos penitenciarios ubicados en el distrito", 38, "Ningún penal existente en el distrito", "Ningún penal en el distrito"),
        P("social", "Construir polideportivos convencionales y especializados, incluido uno para personas con discapacidad, y un parque de la danza", 31, "10 polideportivos convencionales", "10 polideportivos convencionales, 2 para personas con habilidades especiales, 1 de patinaje y 1 de artes marciales"),
        P("social", "Academias municipales preuniversitarias en colegios en horario vespertino o nocturno, con estudiantes universitarios voluntarios", 32, "Implementar 03 academias Municipales Pre-Universitarias", "3 academias municipales"),
        P("agua_riesgos", "Estrategia de seguridad ante desastres con INDECI y construcción de muros de contención en las partes altas", 32, "Construir 3000 muros de contención", "3000 muros de contención"),
        P("urbano", "Pistas de concreto en las avenidas Próceres de la Independencia y Canto Grande y repavimentación de vías vecinales", 32, "Construcción de pistas de concreto de las principales vías"),
        P("agua_riesgos", "Gestionar expedientes técnicos y obras de los esquemas de agua potable y alcantarillado pendientes", 33, "esquemas 400 al 425 de agua potable"),
        P("economia", "Licencias de funcionamiento en 24 horas para pequeños negocios y terminal pesquero mediante inversión público-privada", 40, "Otorgar Licencias en 24 horas a los pequeños negocios", "Licencias en 24 horas y terminal pesquero antes de 2030"),
        P("ambiente", "Flota municipal propia para recolección de residuos y desmonte, con compactadores, volquetes, barredoras y cisternas", 35, "35 camiones compactadores de 21 m3", "35 compactadores, 4 volquetes, 2 barredoras mecánicas y 5 cisternas"),
        P("ambiente", "Planta de valorización de residuos sólidos y reforestación «Eco Verde» con riego de aguas residuales tratadas", 40, "Valorizar el 15% de residuos sólidos generados", "15 % de residuos valorizados y 4 m² de áreas verdes por habitante"),
        P("gestion", "Transmitir las sesiones del Concejo, capacitar al personal, actualizar instrumentos de gestión y gestionar la creación de la provincia de San Juan de Lurigancho", 41, "Transmitir el 100 % de las sesiones del Concejo Municipal", "100 % de sesiones transmitidas y 100 % del personal capacitado al segundo año"),
    ]),
    ("Sabina Alarcón Solís", "Alianza Regional por el Perú", "alianza-regional-por-el-peru", [
        P("seguridad", "Red de cámaras con inteligencia artificial para reconocimiento facial, detección de armas y lectura de placas, y recuperación de puestos de auxilio rápido", 13, "Instalar una red de 1000 cámaras de alta definición", "1000 cámaras"),
        P("seguridad", "Dividir el distrito en 4 macrocuadrantes con bases del serenazgo equipadas con drones, camionetas 4x4 y personal fijo", 15, "Reducir el tiempo de respuesta a un estándar menor de 8 minutos", "Tiempo de respuesta menor a 8 minutos al 2030"),
        P("transporte", "Convenio con la PNP: inspectores municipales en binomio con policías de tránsito contra paraderos informales y cámaras municipales visibles en comisarías", 17, "Erradicación del caos en el 90% de los puntos críticos", "90 % de los puntos críticos de congestión reordenados y 100 % de comisarías interconectadas"),
        P("social", "Academia Municipal Preuniversitaria en dos colegios emblemáticos (Bayóvar y Zárate), con precio social y becas por mérito", 18, "Lograr el ingreso de 1,500 jóvenes", "1,500 ingresantes a universidades públicas al 2030"),
        P("urbano", "Escaleras de concreto con barandas e iluminación solar en las laderas de Huáscar, Bayóvar, Mariátegui y otras comunas altas", 21, "Construir 50,000 metros lineales de escaleras", "50,000 metros lineales de escaleras al 2030"),
        P("economia", "Licencia digital exprés en 24 horas para negocios de riesgo bajo y medio, con fiscalización posterior", 28, "formalizar de manera ágil a 15,000 nuevos establecimientos", "Licencias en menos de 24 horas y 15,000 establecimientos formalizados"),
        P("economia", "Centro de Innovación Tecnológica (CITE) Textil Municipal con maquinaria compartida, control de calidad y ruedas de negocio con exportadores", 31, "Agrupar y potenciar a 1,200 talleres textiles", "1,200 talleres textiles"),
        P("agua_riesgos", "Unidad técnica para agilizar expedientes de agua y desagüe ante SEDAPAL, piletas públicas en zonas de difícil acceso y nuevos reservorios", 35, "Reducir en un 60% la brecha de viviendas sin conexión", "Brecha de viviendas sin conexión en laderas reducida en 60 %"),
        P("ambiente", "Dos plantas de tratamiento de aguas residuales para riego tecnificado, pozos para riego y forestación de cerros", 37, "02 Plantas Compactas de Tratamiento de Aguas Residuales", "De 1.8 m² a 4.5 m² de áreas verdes por habitante"),
        P("agua_riesgos", "Muros de contención estructurales y barreras dinámicas en las zonas de mayor pendiente y densidad", 38, "Construir 150 muros de contención de alta ingeniería", "150 muros de contención"),
        P("gestion", "Gobierno digital: interoperabilidad con RENIEC, SUNAT y SUNARP, firma digital y ventanilla virtual única para los trámites del TUPA", 40, "Alcanzar el 100% de los trámites municipales digitalizados", "100 % de trámites municipales digitalizados al 2030"),
    ]),
    ("Héctor Joaquín Alejandro Bustamante", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Más personal y equipamiento del serenazgo, cámaras inteligentes con lectura de placas, alarmas comunitarias y patrullaje integrado en zonas críticas", 10, "reconocimiento de placas vehiculares, alarmas comunitarias"),
        P("social", "Recuperar y modernizar todos los polideportivos y espacios recreativos municipales, con escuelas deportivas gratuitas", 10, "Recuperar y modernizar, durante el primer año de gestión", "Todos los polideportivos municipales recuperados durante el primer año"),
        P("social", "Casa de la Cultura con biblioteca, mediateca, ludoteca, auditorio y salas para talleres, y Casa de la Juventud", 11, "Una nueva y moderna biblioteca municipal"),
        P("social", "Academias preuniversitarias municipales gratuitas y reforzamiento escolar para estudiantes de bajos recursos", 11, "Academias Preuniversitarias municipales gratuitas"),
        P("social", "Casa de la Mujer para víctimas de violencia y Casa del Adulto Mayor en zonas estratégicas", 12, "Crear e implementar la Casa de la Mujer"),
        P("agua_riesgos", "Programa de muros de contención, drenajes y obras de mitigación en zonas vulnerables, con capacitación vecinal ante emergencias", 13, "construcción y mejoramiento de muros de contención, drenajes"),
        P("urbano", "Rehabilitar las principales vías y mantener pistas, veredas, escaleras y losas deportivas", 13, "modernización y rehabilitación de las principales vías estructurantes"),
        P("economia", "Centro Municipal de Desarrollo Empresarial con asesoría y capacitación para mypes, y bolsa de trabajo municipal", 14, "Centro Municipal de Desarrollo Empresarial y Emprendimiento"),
        P("economia", "Licencias de funcionamiento en 24 horas para pequeños negocios y gestión de un terminal pesquero con inversión público-privada", 23, "Otorgar Licencias en 24 horas a los pequeños negocios", "Licencias en 24 horas y terminal pesquero antes de 2030"),
        P("ambiente", "Renovar la flota de limpieza, ampliar recolección y barrido, y planta de valorización de residuos sólidos", 24, "Ampliar al 60% la cobertura adecuada del servicio de barrido", "100 % de cobertura de recolección, 60 % de barrido y 15 % de residuos valorizados"),
        P("gestion", "Plataforma «Municipalidad Transparente» con presupuesto, obras y contrataciones en tiempo real, y audiencias públicas descentralizadas", 19, "donde los vecinos puedan consultar en tiempo real"),
    ]),
    ("Adán Renee Cobeña Gómez", "Coalición Transformadora Tierra Verde", "coalicion-transformadora-tierra-verde", [
        P("seguridad", "Sectorizar el distrito en 8 zonas de comando con bases del serenazgo e interconectar la videovigilancia con las 9 comisarías del distrito", 55, "Sectorización del territorio en 8 grandes zonas de comando"),
        P("seguridad", "Fiscalización conjunta contra mercados de bienes robados y clausura de hostales, discotecas y locales de apuestas ilegales usados para extorsión", 56, "discotecas informales sin licencia y locales de apuestas ilegales", "Victimización delictiva violenta de 39.8 % (2026) a 14.5 % en 2030"),
        P("gestion", "Virtualizar todos los trámites del TUPA en la plataforma «SJL Digital» para eliminar intermediarios", 57, "emitidos de manera digital y automatizada en menos de 48 horas", "90 % de licencias de mipymes emitidas en menos de 48 horas en 2030"),
        P("gestion", "Observatorio Distrital de Integridad administrado por la sociedad civil y audiencias de rendición de cuentas tres veces al año", 56, "Observatorio Distrital de Integridad y Lucha Contra la Corrupción"),
        P("social", "Red de policlínicos municipales preventivos y centros de salud mental familiar en Huáscar, Bayóvar y laderas altas", 57, "Policlínicos Municipales Preventivos"),
        P("social", "Equipar comedores populares, Vaso de Leche y ollas comunes, con control de inventarios vinculado al SISFOH", 58, "Reducción del índice de anemia y desnutrición crónica infantil", "Anemia y desnutrición infantil de 41.2 % (2026) a 15 % en 2030"),
        P("economia", "Modernizar y formalizar mercados de abastos con certificados ITSE e inocuidad, y cerrar camales clandestinos", 59, "mercados de abastos regulados del distrito que cuentan con licencias", "100 % de mercados con licencias de DIGESA e ITSE en 2030"),
        P("transporte", "Paraderos fijos, carriles para transporte público, empadronamiento de mototaxis con QR y GPS, ciclovías y semáforos inteligentes", 60, "Reducción del tiempo promedio de viaje en hora punta", "Tiempo de viaje en hora punta de 92 a 48 minutos en 2030"),
        P("urbano", "Cercado e iluminación de las huacas Mangomarca, Canto Chico y Campoy y circuito turístico con las lomas del distrito", 61, "Huaca Mangomarca, Huaca Canto Chico y Campoy", "6 sitios recuperados en 2030"),
        P("ambiente", "Forestación con árboles nativos y riego de parques con aguas residuales tratadas en lugar de cisternas", 62, "Plan intensivo de forestación urbana sustentable", "Área verde de 1.9 a 6.2 m² por habitante y 0 puntos críticos de residuos en 2030"),
        P("agua_riesgos", "Muros de contención, andenes y mallas contra caída de rocas, sirenas de alerta en quebradas y brigadas vecinales de defensa civil", 63, "Instalación de sirenas electrónicas comunitarias", "85 % de la población en zonas de peligro muy alto protegida en 2030"),
    ]),
    ("Walter Jacobo Gutiérrez Vaisman", "Fe en el Perú", "fe-en-el-peru", [
        P("seguridad", "Contratar y capacitar agentes de serenazgo, crear una base central de seguridad y gestionar más policías con el Ministerio del Interior", 37, "Contratación de 1000 agentes y capacitación profesional al Serenazgo", "1000 agentes de serenazgo"),
        P("seguridad", "Cámaras de seguridad operativas las 24 horas y módulos de seguridad permanentes", 37, "Instalación de 500 Cámaras de seguridad", "500 cámaras"),
        P("social", "Academias municipales con talleres ocupacionales (confección, serigrafía, artesanía) y de emprendimiento", 37, "confección de carteras, serigrafía"),
        P("social", "Hospital municipal con móviles de emergencia, centro psicológico municipal y hospital veterinario", 38, "Hospital Municipal y Móviles de Emergencia"),
        P("economia", "Modernizar los mercados de abasto, formalizar emprendedores y crear un centro de desarrollo empresarial", 38, "Modernización de mercados de abasto"),
        P("transporte", "Gestionar con el Gobierno central puentes de interconexión y corredores viales, y semaforización del distrito", 39, "construcción de puentes de interconexión y corredores viales"),
        P("urbano", "Rehabilitar vías para eliminar baches en las principales avenidas y construir escaleras y muros de contención en laderas", 39, "Cero baches en las principales avenidas"),
        P("transporte", "Formalizar el transporte de mototaxis, construir paraderos y fiscalizar el transporte público", 39, "Formalización del transporte de mototaxis"),
        P("ambiente", "Planta de tratamiento de aguas residuales para regar laderas, áreas verdes y cerros", 35, "Planta de Tratamiento de Aguas Residuales para sistemas de riego"),
        P("ambiente", "Comprar camiones recolectores de basura e instalar contenedores subterráneos", 40, "Adquisición de 20 camiones recolectores de basura", "20 camiones recolectores"),
        P("gestion", "Informe semestral detallado del alcalde sobre la gestión y cabildos abiertos de diálogo con los vecinos", 40, "Cada semestre, el alcalde realizará un informe pormenorizado", "Un informe de gestión cada semestre"),
    ]),
    ("Antonio Flores Cáceres", "FREPAP", "frente-popular-agricola-fia-del-peru", [
        P("social", "Programa «SJL Crece Sano»: tamizaje y suplementación con hierro, seguimiento nutricional y biohuertos para la seguridad alimentaria", 9, "Reducir la anemia infantil a menos del 10%", "Anemia infantil menor al 10 % al 2030"),
        P("social", "Programa «Escuelas Innovadoras SJL»: infraestructura, conectividad, equipamiento tecnológico y bibliotecas en colegios públicos", 10, "mejoramiento de infraestructura, conectividad digital, equipamiento tecnológico", "60 instituciones educativas priorizadas intervenidas"),
        P("seguridad", "Programa «SJL Seguro 24/7»: central de monitoreo inteligente, videovigilancia, drones, alarmas vecinales y patrullaje integrado", 11, "central de monitoreo inteligente, videovigilancia, patrullaje integrado", "30 % menos delitos de mayor incidencia y 2,000 cámaras de videovigilancia"),
        P("agua_riesgos", "Gestionar proyectos de agua y saneamiento, mejoramiento integral de barrios y formalización urbana en zonas de expansión", 11, "gestión de proyectos de agua y saneamiento, mejoramiento integral de barrios", "40,000 hogares beneficiados"),
        P("social", "Programa «Salud Cerca de Ti»: campañas médicas itinerantes, telemedicina y vacunación", 11, "campañas médicas itinerantes, telemedicina", "1,000 campañas integrales de salud durante la gestión"),
        P("economia", "Centro Municipal de Empleo con bolsa laboral, certificación de competencias, primer empleo y asistencia técnica y digital a mypes", 12, "creación del Centro Municipal de Empleo", "50,000 vecinos beneficiados y al menos 10,000 mypes formalizadas"),
        P("economia", "Modernizar mercados y centros de abasto: infraestructura, accesibilidad, seguridad, limpieza y digitalización", 13, "Modernizar al menos 20 mercados", "Al menos 20 mercados modernizados"),
        P("transporte", "Mejorar vías estratégicas, modernizar semáforos y ordenar el transporte en los corredores comerciales", 13, "Mejorar 120 km de vías y reducir en 30% los tiempos de viaje", "120 km de vías mejoradas y 30 % menos tiempo de viaje"),
        P("ambiente", "Recuperar parques, arborizar, crear biohuertos comunitarios y escolares, viveros municipales y riego tecnificado", 14, "plantar 100,000 árboles e implementar 200 biohuertos", "3 m² de áreas verdes por habitante, 100,000 árboles y 200 biohuertos"),
        P("agua_riesgos", "Muros de contención, estabilización de taludes, drenaje pluvial, rutas de evacuación y alerta temprana en zonas de riesgo", 14, "Intervenir el 100% de las zonas priorizadas con riesgo alto y muy alto", "100 % de las zonas priorizadas de riesgo alto y muy alto intervenidas"),
        P("gestion", "Expediente electrónico, mesa de partes virtual, aplicativo móvil y seguimiento de trámites en línea", 16, "Digitalizar el 100% de los trámites prioritarios", "100 % de los trámites prioritarios digitalizados"),
    ]),
    (None, "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Fortalecer el serenazgo e implementar tecnología de vigilancia, en coordinación con la comunidad y la Policía Nacional", 6, "Fortalecimiento del serenazgo municipal"),
        P("social", "Promover la cultura de paz y la prevención de la violencia", 6, "Promoción de la cultura de paz y prevención de la violencia"),
        P("urbano", "Ordenamiento territorial, recuperación de espacios públicos y mejoramiento de vías y accesibilidad", 6, "Mejoramiento de vías y accesibilidad urbana"),
        P("agua_riesgos", "Prevenir la ocupación de zonas de riesgo", 6, "Prevención de ocupación de zonas de riesgo"),
        P("economia", "Apoyo y formalización de mypes, capacitación laboral y técnica, y promoción de mercados y ferias productivas", 6, "Promoción de mercados y ferias productivas"),
        P("social", "Programas sociales para niños, jóvenes y adultos mayores y mejora de los servicios de salud preventiva", 6, "Mejora de servicios de salud preventiva"),
        P("ambiente", "Manejo de residuos sólidos, más áreas verdes, educación ambiental y adaptación al cambio climático", 7, "Manejo adecuado de residuos sólidos"),
        P("gestion", "Digitalización de servicios, simplificación administrativa, transparencia y rendición de cuentas", 7, "Digitalización de servicios"),
        P("gestion", "Presupuesto participativo, juntas vecinales organizadas, audiencias públicas y mecanismos de control ciudadano", 7, "Juntas vecinales organizadas"),
    ]),
    ("Edwin Mejía Cerdán", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Cámaras de videovigilancia con inteligencia artificial en las 18 comunas, priorizando paraderos, colegios, mercados y avenidas principales", 5, "Instalación de 2000 cámaras de videovigilancia con inteligencia artificial", "1000 cámaras en 2027 y 2000 en 2030"),
        P("seguridad", "Incrementar el patrullaje integrado", 5, "Incremento del patrullaje integrado", "Patrullaje integrado del 40 % en 2027 al 100 % en 2030"),
        P("social", "Escuelas deportivas y culturales y talleres para jóvenes", 5, "Escuelas deportivas y culturales", "50 talleres juveniles en 2027 y 150 en 2030"),
        P("social", "Campañas médicas gratuitas y fortalecimiento de comedores populares", 5, "Campañas médicas gratuitas", "100 campañas médicas en 2027 y 250 en 2030"),
        P("economia", "Centros de capacitación técnica y laboral y programas de apoyo a mypes", 6, "Creación de centros de capacitación", "2000 emprendedores capacitados en 2027 y 8000 en 2030"),
        P("economia", "Ferias laborales y comerciales, simplificación administrativa y formalización de comerciantes", 6, "Formalización de comerciantes", "500 comercios formalizados en 2027 y 2000 en 2030; 10 a 40 ferias laborales"),
        P("urbano", "Comprar maquinaria para mejorar accesos y calles en las partes altas del distrito", 7, "Compra de maquinaria para mejoramiento de accesos en las partes altas", "Accesos mejorados en partes altas: 20 % en 2027 y 60 % en 2030"),
        P("urbano", "Comprar equipos de asfalto para la ejecución y el mantenimiento de pistas en las 18 comunas", 7, "Compra de equipos de asfalto de pistas", "Calles y avenidas con mantenimiento: 10 % en 2027 y 35 % en 2030"),
        P("agua_riesgos", "Equipos técnicos de mitigación de riesgo en las 18 comunas y diagnósticos en los sectores de las partes altas", 8, "Mitigación de riesgos en las zonas altas", "Mitigación de riesgos en zonas altas: 15 % en 2027 y 40 % en 2030"),
        P("ambiente", "Arborización, recuperación de parques, programas de reciclaje y fiscalización ambiental", 8, "Árboles sembrados Parques recuperados", "Árboles sembrados de 10,000 a 40,000; parques recuperados de 20 a 80; programas de reciclaje de 15 a 60"),
        P("gestion", "Digitalización de trámites, audiencias públicas descentralizadas y plataforma virtual de transparencia", 9, "Trámites digitalizados 30% 50% 80% 100%", "Trámites digitalizados: 30 % en 2027 y 100 % en 2030; 48 audiencias públicas"),
    ]),
    ("Carlos Jaime de la Torre Mendoza", "Partido del Buen Gobierno", "partido-del-buen-gobierno", [
        P("seguridad", "Reorganizar el serenazgo en 12 cuadrantes con patrullaje integrado con la PNP y crear 6 bases de seguridad en las zonas de mayor incidencia delictiva", 4, "Creación de 6 Bases de Seguridad", "6 bases de seguridad"),
        P("seguridad", "Centro de monitoreo inteligente con 800 cámaras con reconocimiento de placas, 10 drones nocturnos, aplicativo vecinal y 2,000 botones de pánico", 4, "Instalación de 800 cámaras de videovigilancia", "800 cámaras, 10 drones y 2,000 botones de pánico"),
        P("agua_riesgos", "Gestionar ante el Ministerio de Vivienda y SEDAPAL la priorización de SJL y la extensión de redes de agua y desagüe en las zonas altas", 6, "Conexiones domiciliarias de agua nuevas: 15,000", "15,000 conexiones domiciliarias de agua nuevas en el período"),
        P("agua_riesgos", "Construir muros de contención en laderas de alta densidad e instalar drenaje pluvial en las 15 quebradas principales", 19, "drenaje pluvial en las 15 quebradas principales", "120 muros de contención y 15 quebradas intervenidas"),
        P("transporte", "Construir y rehabilitar tramos de escaleras con pasamanos, iluminación LED y drenaje en los cerros del distrito", 7, "Construcción y rehabilitación de 80 tramos de escaleras", "80 tramos de escaleras"),
        P("social", "Implementar Centros de Atención en Salud Mental Comunitaria en zonas con más violencia y consumo de sustancias, con equipos itinerantes y línea de crisis", 8, "Implementación de 5 Centros de Atención en Salud Mental", "5 centros al 2029 y 8,000 pacientes atendidos al año"),
        P("social", "Programa «Mujer segura SJL»: atención legal y psicológica gratuita, casas de acogida temporal y 15 profesionales adicionales en la DEMUNA", 10, "Operación de 3 Casas de Acogida Temporal", "3 casas de acogida operativas al 2028"),
        P("economia", "Licencia de funcionamiento express para negocios de bajo riesgo, actualización del TUPA y ventanilla única del empresario", 12, "licencia de funcionamiento de 45 a 3 días", "Licencia en 3 días (antes 45) para negocios de bajo riesgo"),
        P("ambiente", "Planta municipal de clasificación y valorización de residuos e integración formal de recicladores con equipamiento y seguro social", 16, "capacidad de procesar 200 toneladas diarias", "Planta de 200 toneladas diarias operativa en 2029 y 800 recicladores formalizados"),
        P("ambiente", "Arborización «Un árbol por vecino» con especies nativas en avenidas, cerros erosionados y zonas de expansión", 17, "Plantación de 100,000 árboles en el período", "100,000 árboles (25,000 por año)"),
        P("gestion", "Plataforma digital única de servicios municipales con mesa de partes 24/7, aplicativo «Mi SJL» y expediente electrónico", 20, "Mesa de partes digital disponible 24/7"),
    ]),
    ("Noe Zender Mamani Espinoza", "Partido Demócrata Unido Perú", "partido-democrata-unido-peru", [
        P("seguridad", "Escuela Distrital de Serenazgo con certificaciones progresivas y convenios con INDECI, PNP, MINSA y universidades", 9, "Escuela Distrital de Serenazgo", "1,850 serenos activos al 2030, todos certificados"),
        P("seguridad", "Sistema de inteligencia territorial con serenos no uniformados y cámaras con análisis de datos, que entrega información a la PNP y la Fiscalía", 9, "300 nuevas cámaras de videovigilancia", "300 cámaras nuevas"),
        P("seguridad", "Botón de pánico digital en la app municipal que alerta a serenazgo, comisaría y contactos con ubicación GPS", 9, "protocolo de respuesta en menos de 5 minutos", "Respuesta en menos de 5 minutos"),
        P("agua_riesgos", "Gestionar con la PCM y el Ministerio de Agricultura proyectos de defensa ribereña en los puntos críticos sin protección", 10, "proyectos de inversión para defensa ribereña", "Reducir la brecha al 55 % al 2030"),
        P("transporte", "Plan Integral de Vías Urbanas: pistas, veredas y escaleras priorizando Cruz de Motupe, Mariscal Cáceres, Villa San Antonio y zonas altas", 11, "Meta acumulada: 90 km al 2030", "90 km acumulados al 2030"),
        P("social", "Invertir con recursos municipales, MINSA y obras por impuestos en la infraestructura de los establecimientos de salud de primer nivel", 15, "al menos 30 establecimientos mejorados al 2030", "Al menos 30 establecimientos mejorados al 2030"),
        P("economia", "Ventanilla única de atención empresarial presencial y virtual, con plazos máximos garantizados para licencias", 13, "3,300 comerciantes formalizados al 2030", "3,300 comerciantes formalizados al 2030"),
        P("economia", "Circuito turístico a los sitios arqueológicos de Mangomarca, Campoy y Canto Chico, con guías y señalética bilingüe", 13, "Circuito Turístico con rutas a Mangomarca"),
        P("ambiente", "Cercos vivos de vegetación nativa entre zonas urbanas y laderas para frenar la urbanización informal y estabilizar suelos", 19, "25 km de cercos vivos al 2030", "25 km al 2030"),
        P("ambiente", "Gestionar la intangibilidad de las lomas de Amancaes y Mangomarca, con guardabosques comunales y rutas ecoturísticas", 19, "declaración de intangibilidad de las áreas de lomas"),
        P("gestion", "Agencias municipales descentralizadas con trámites, DEMUNA, OMAPED, registro civil y serenazgo, más módulos itinerantes", 21, "8 Agencias Municipales Descentralizadas", "8 agencias, una por zona"),
    ]),
    ("Alex Gonzales Castillo", "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Instalar cámaras de vigilancia, contratar serenos exmilitares y expolicías y crear centros de capacitación de serenos", 27, "pondremos 300 cámaras de vigilancia en sectores estratégicos", "300 cámaras y 300 serenos más"),
        P("social", "Culminar y equipar la Casa de la Juventud en Campoy, con cursos de ofimática, computación y electricidad en convenio con universidades", 25, "Culminación y equipamiento de la Casa de la Juventud"),
        P("social", "Programa municipal de becas para egresados de secundaria de 17 a 19 años, por examen público a cargo de la UNI", 25, "el municipio concederá 50 becas", "50 becas"),
        P("social", "Impulsar la creación de la Universidad Nacional de San Juan de Lurigancho", 25, "impulsar la creación de la Universidad Nacional de S.J.L."),
        P("economia", "Crear la Caja Municipal de Ahorro y Crédito de San Juan de Lurigancho, con local propio en un terreno de 200 m²", 27, "capital inicial de 7.5 millones de soles", "Capital inicial de 7.5 millones de soles"),
        P("ambiente", "Construir una planta municipal de tratamiento de residuos sólidos", 26, "Planta Municipal de Tratamiento de Residuos Sólidos"),
        P("ambiente", "«Cinturón Verde»: cinturón forestal detrás de los asentamientos en los cerros para frenar invasiones y tráfico de tierras", 28, "Cinturón Forestal que cercará totalmente el distrito"),
        P("ambiente", "Centro de acopio de desmonte administrado por la municipalidad en cada zonal, financiado con el pago de acopiadores registrados", 28, "ubicar en cada zonal un centro de descarga de desmontes"),
        P("agua_riesgos", "Construir escaleras y muros de contención con participación de los vecinos y financiamiento compartido", 28, "siempre se hará con la participación conjunta Municipio"),
        P("transporte", "Apoyar las obras del Anillo Vial desde San Fernando hasta Independencia y mejorar la ruta de Pasamayito", 29, "mejorar la ruta Pasa mayito"),
        P("gestion", "Banco de Proyectos municipal para recopilar ideas y proyectos vecinales consultables por el público", 29, "todo municipio debería contar con un banco de proyectos"),
    ]),
    (None, "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Estrategia «SJL Seguro» con centrales de seguridad descentralizadas por sector policial y aplicación Alerta SOS SJL", 22, "Creación de aplicación Alerta SOS SJL"),
        P("seguridad", "Videovigilancia municipal con inteligencia artificial e instalación de luminarias en el distrito", 22, "Instalación de 1,000 luminarias en el distrito", "1,000 luminarias"),
        P("social", "Crear la Academia Municipal Pre-Universitaria y el programa de becas «Jóvenes con propósito»", 23, "Academia Municipal Pre-Universitaria"),
        P("social", "Crear un Centro Psicológico Municipal y gestionar un convenio con SISOL para atención de salud a precio social", 24, "Creación del Centro Psicológico Municipal"),
        P("social", "Crear la Casa de la Mujer y un nuevo local de OMAPED, y fortalecer el CIAM", 24, "Creación del nuevo local de OMAPED"),
        P("ambiente", "Primera planta municipal de tratamiento y reciclaje mediante APP, con recolección diferenciada e integración de recicladores", 28, "primera Planta Municipal de Tratamiento y Reciclaje de Residuos Sólidos"),
        P("ambiente", "Reemplazar el alumbrado de plazas y parques por luminarias LED con paneles solares autónomos", 28, "los más de 600 parques del distrito por sistemas LED"),
        P("agua_riesgos", "Proyecto «Andenería y Bosques de Protección» con vegetación nativa en cerros y laderas vulnerables", 29, "Andenería y Bosques de Protección"),
        P("economia", "Construir un terminal pesquero en el distrito", 34, "La necesidad de un Terminal Pesquero es indiscutible"),
        P("transporte", "Padrón único georreferenciado de mototaxis con paraderos autorizados y restricción de su acceso a vías principales", 38, "Padrón Único y Formalización"),
        P("gestion", "Certificar un Sistema de Gestión Antisoborno ISO 37001 en contrataciones, obras, licencias, programas sociales y fiscalización", 41, "Propuesta: Certificación ISO 37001"),
    ]),
    ("Miguel Oswaldo Huacre Méndez", "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Centro integral de monitoreo con inteligencia artificial, cámaras con reconocimiento facial y nuevas bases de serenazgo en zonas críticas", 24, "Creación y equipamiento de 15 nuevas bases de serenazgo", "15 nuevas bases de serenazgo"),
        P("social", "Crear un hospital municipal y policlínicos municipales zonales en Canto Grande, Bayóvar, Jicamarca, Campoy y Zárate", 27, "Policlínicos Municipales Zonales"),
        P("social", "Mejorar la infraestructura y el equipamiento de instituciones educativas y crear una academia preuniversitaria municipal gratuita", 25, "meta: 80% en buen estado al 2030", "80 % de instituciones educativas en buen estado al 2030"),
        P("transporte", "Intercambios viales Puente Nuevo–Próceres, Zárate–Malecón Checa y Las Flores–Wiesse", 25, "Intercambio vial Puente Nuevo – Próceres"),
        P("transporte", "Teleférico que conecte las zonas altas con las estaciones del Metro de Lima", 31, "Teleférico San Juan de Lurigancho"),
        P("agua_riesgos", "Gestión prioritaria con SEDAPAL para cerrar las brechas de agua y alcantarillado en laderas", 28, "Gestión prioritaria con SEDAPAL", "≥95% cobertura al 2030"),
        P("ambiente", "Parque Metropolitano con lagunas artificiales, ciclovías y anfiteatro, y remodelación de parques", 27, "Parque Metropolitano de San Juan de Lurigancho", "Más de 50 hectáreas; más de 500 parques remodelados"),
        P("ambiente", "Planta de tratamiento de residuos, programa «Basura Cero» y contenedores soterrados, junto con un programa masivo de arborización", 29, "Un Millón de Árboles para SJL", "Un millón de árboles"),
        P("economia", "Ventanilla única empresarial y licencias municipales rápidas", 28, "Licencias municipales rápidas en 48 horas", "Licencias en 48 horas"),
        P("economia", "Parque Industrial de SJL, terminal pesquero y mercado mayorista moderno", 28, "Terminal Pesquero Mercado Mayorista Moderno"),
        P("gestion", "Municipalidad digital con expedientes electrónicos, portal de obras en tiempo real y rendición de cuentas trimestral", 30, "Rendición de cuentas trimestral", "Ejecución presupuestal mayor al 90 %"),
    ]),
    ("Armengol Sánchez Sandoval", "PRIN", "partido-politico-prin", [
        P("seguridad", "Unidad de Inteligencia Operativa Municipal conectada con la DIRINCRI, renovación de la flota del serenazgo y cercos tácticos en Puente Nuevo y Túneles", 11, "Unidad de Inteligencia Operativa Municipal (UNIOM)", "Reducir en 70 % el índice delictivo general al 2029 y 100 % de la flota operativa"),
        P("urbano", "Programa «Obra Compartida»: el municipio pone materiales e ingenieros y los vecinos la mano de obra para veredas, muros y escaleras", 11, "Construir 600 kilómetros de veredas cofinanciadas", "600 km de veredas al 2031 y 25,000 predios con planos visados"),
        P("agua_riesgos", "Muros de contención de concreto armado y escaleras con barandas e iluminación solar en las comunidades de altura", 12, "2,500 escaleras técnicas residenciales y 1,450 muros", "2,500 escaleras y 1,450 muros de contención"),
        P("social", "Primer Estadio Olímpico Municipal multidisciplinario y remodelación de losas con grass sintético e iluminación LED", 12, "primer Estadio Municipal Olímpico multidisciplinario", "Estadio inaugurado y 190 losas remodeladas al 2031"),
        P("social", "Policlínicos municipales móviles en las 18 comunas y dos centros de acogida: Casa del Adulto Mayor y Casa de la Madre Adolescente", 13, "150,000 atenciones médicas descentralizadas", "150,000 atenciones médicas y 2 centros para 2,000 personas"),
        P("economia", "Programa «Terreno Propio»: créditos asociativos para que ambulantes compren terrenos y se reubiquen en recintos comerciales propios", 13, "reubicar de manera sostenible a 25,000 comerciantes ambulantes", "25,000 comerciantes reubicados al 2029"),
        P("economia", "Red de panaderías municipales industriales de autogestión en locales comunales (10 por comuna)", 13, "Red de 180 Panaderías Municipales Industriales", "180 módulos en funcionamiento al 2028"),
        P("economia", "Construir el primer terminal pesquero municipal mayorista, con cámaras frigoríficas, fábrica de hielo y laboratorios", 14, "primer Terminal Pesquero Municipal de escala mayorista", "Operativo al 2029 con 220 puestos"),
        P("ambiente", "Recojo nocturno obligatorio de residuos por cuadrantes con camiones con GPS y software para sancionar el arrojo de desmonte", 16, "cronograma obligatorio de recojo nocturno"),
        P("agua_riesgos", "Defensas ribereñas, barreras dinámicas y diques de retención en quebradas de alto riesgo y riberas de los ríos Rímac y Huaycoloro", 18, "recuperar 15 kilómetros de ribera fluvial degradada", "100 % de quebradas de alto riesgo intervenidas y 15 km de ribera al 2030"),
        P("gestion", "Plataforma «SJL en Línea» con licencias digitales en menos de 24 horas y programa itinerante «Alcalde en tu Barrio»", 19, "Virtualizar el 90% de los trámites municipales", "90 % de trámites virtuales al 2028 y 45 audiencias territoriales al año"),
    ]),
    (None, "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Fortalecer la Gerencia de Seguridad Ciudadana con tecnología, patrullaje integrado y participación vecinal", 2, "Fortalecer la Gerencia de Seguridad Ciudadana", "Incrementar en 100 % el patrullaje en puntos críticos y las cámaras operativas; reducir en 30 % la percepción de inseguridad"),
        P("social", "Programas de capacitación, emprendimiento, empleo, deporte y cultura para jóvenes", 2, "Beneficiar a 40,000 jóvenes", "40,000 jóvenes beneficiados durante la gestión"),
        P("urbano", "Proyectos para mejorar servicios básicos, parques y equipamiento urbano", 2, "Beneficiar al 80% de los sectores priorizados", "80 % de los sectores priorizados beneficiados"),
        P("economia", "Formalización y ordenamiento del comercio en la vía pública", 2, "Formalizar 10,000 unidades económicas", "10,000 unidades económicas formalizadas"),
        P("economia", "Capacitación y promoción de emprendedores y MYPE", 3, "Capacitar y promover a 16,000 emprendedores", "16,000 emprendedores y MYPE"),
        P("economia", "Bolsa de Trabajo Distrital y ferias laborales permanentes para jóvenes", 3, "Lograr 15,000 colocaciones laborales", "15,000 colocaciones laborales durante la gestión"),
        P("ambiente", "Mejorar la limpieza pública, la segregación de residuos y el reciclaje", 3, "95% de cobertura efectiva de limpieza pública", "95 % de cobertura de limpieza pública"),
        P("ambiente", "Recuperar y mejorar parques, jardines y áreas verdes", 3, "Incrementar en 20% las áreas verdes distritales", "20 % más áreas verdes"),
        P("ambiente", "Programas de educación ambiental y sostenibilidad para los vecinos", 3, "Alcanzar 100,000 vecinos sensibilizados", "100,000 vecinos sensibilizados"),
        P("gestion", "Transparencia, rendición de cuentas y gobierno abierto con audiencias públicas", 3, "Realizar 2 audiencias", "2 audiencias públicas por año y 100 % de la información obligatoria publicada"),
        P("gestion", "Transformación digital y simplificación administrativa de los trámites municipales", 4, "Digitalizar el 80% de los principales trámites", "80 % de los principales trámites digitalizados"),
    ]),
    (None, "Partido SíCreo", "partido-sicreo", [
        P("seguridad", "Ampliar el serenazgo por concurso público y renovar equipos con patrulleros, motocicletas y radios digitales", 5, "pasar de 720 a 1,200 serenos", "1,200 serenos (desde 720), 60 patrulleros y 80 motocicletas"),
        P("seguridad", "Centro de control y videovigilancia con cámaras en avenidas, mercados y colegios, conectado las 24 horas e integrado con la PNP", 5, "Instalación de 450 cámaras de alta definición", "450 cámaras; videovigilancia en el 95 % de puntos críticos"),
        P("seguridad", "Programa «Vecino Alerta»: nuevas juntas vecinales de seguridad equipadas, aplicación móvil y línea directa de denuncias", 5, "300 nuevas Juntas Vecinales de Seguridad Ciudadana", "300 nuevas juntas vecinales"),
        P("transporte", "Programa «San Juan Conectado»: pavimentación y mantenimiento de vías, priorizando avenidas y accesos a zonas altas, más veredas y rampas", 6, "mantenimiento de 320 kilómetros de vías", "320 km de vías y 150 km de veredas en la gestión"),
        P("agua_riesgos", "Convenios con SEDAPAL para ampliar y renovar redes de agua y alcantarillado y recolección de agua de lluvia en zonas altas", 7, "beneficiando a más de 12,000 familias", "Más de 12,000 familias beneficiadas"),
        P("urbano", "Actualizar el Plan de Desarrollo Urbano y el catastro, y formalizar predios masivamente", 7, "seguridad jurídica a 5,000 familias al año", "5,000 familias al año"),
        P("economia", "Mejorar la infraestructura de los mercados de abasto y reubicar de forma concertada el comercio ambulatorio", 8, "Mejora integral de los 22 mercados de abasto", "22 mercados de abasto"),
        P("economia", "Ventanilla única empresarial con licencia rápida, licencias 50 % más baratas para pequeños negocios y programa de formalización", 8, "Licencia de Funcionamiento en un máximo de 48 horas", "Licencia en 48 horas y 2,500 negocios formalizados por año"),
        P("social", "Descentralizar el CIAM con sedes por comuna: salud preventiva, alimentación, asesoría legal y atención domiciliaria", 9, "Creación de sedes en cada comuna"),
        P("ambiente", "Programa distrital de arborización con especies adecuadas, riego técnico y mantenimiento", 11, "Plantación de 150,000 árboles", "150,000 árboles"),
        P("gestion", "Trámites y pagos en línea, sedes de atención en zonas altas y audiencias de rendición de cuentas semestrales", 12, "Creación de 8 sedes de atención al vecino", "8 sedes de atención; 60 % menos tiempo de espera"),
    ]),
    ("José Luis Luna Morales", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Promover un convenio con el Ministerio del Interior para incorporar efectivos policiales del programa TERNA", 41, "incorporación de 200 efectivos policiales del programa TERNA", "200 efectivos policiales"),
        P("seguridad", "Integrar las cámaras municipales con las de las juntas vecinales y patrullaje integrado de PNP, serenazgo y vecinos", 42, "Integrar el sistema de vigilancia municipal con los sistemas de vigilancia vecinal"),
        P("agua_riesgos", "Coordinar con el Ministerio de Vivienda y SEDAPAL la mejora de redes de agua y alcantarillado en los sectores no atendidos", 14, "agua 24/7 en el distrito, sin cortes", "Que el 10 % de la población sin acceso al agua cuente con el servicio; agua 24/7 sin cortes"),
        P("social", "Coordinar con DEMUNA, comisarías y Ministerio Público la atención a víctimas de violencia y fundar centros de emergencia", 17, "Fundar 2 centros de emergencia la mujer", "2 centros de emergencia"),
        P("social", "Entregar al MINSA un terreno saneado para un hospital general nivel 3 y crear policlínicos municipales y un policlínico geriátrico", 38, "Implementar un Policlínico Geriátrico"),
        P("urbano", "Construir escaleras de acceso y muros de contención en los sectores del distrito", 24, "Construir escaleras de acceso y muros de contención"),
        P("economia", "Rutas turísticas «full days» a las huacas y lomas de Mangomarca y la Fortaleza de Campoy, y recuperación arqueológica con el Ministerio de Cultura", 25, "con rutas de las zonas turísticas del distrito"),
        P("economia", "Ferias de emprendimiento y capacitaciones gratuitas con institutos y universidades en tributación, marketing y herramientas digitales", 26, "Promover la realización de Ferias de emprendimiento"),
        P("ambiente", "Sistema de acopio y tratamiento de residuos con alianzas con recicladores y compra de maquinaria", 30, "Crear alianzas estratégicas con los recicladores"),
        P("agua_riesgos", "Plan de contingencia con INDECI y CENEPRED, brigadas de primera respuesta y Centro de Operaciones de Emergencia Distrital", 31, "Crear e implementar el COED"),
        P("gestion", "Gobierno electrónico, trámites virtuales y supervisión digital en tiempo real de los fiscalizadores municipales", 33, "Diseñar mecanismos de control y supervisión digital"),
    ]),
    ("Américo Zegarra Acuña", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Subcentrales de vigilancia y monitoreo en ingresos estratégicos, con cámaras con inteligencia artificial y patrullaje integrado", 37, "Subcentrales de Vigilancia y Monitoreo Interconectadas"),
        P("seguridad", "Convenio con el Ministerio del Interior y la PNP para construir una nueva comisaría que divida la jurisdicción de Santa Elizabeth", 45, "dividiendo la jurisdicción de Santa Elizabeth"),
        P("urbano", "Obras compartidas: la municipalidad aporta expedientes, materiales y maquinaria, y los vecinos mano de obra, para escaleras, muros, parques y casetas", 43, "Programa de Obras Compartidas para el Desarrollo y la Seguridad Comunitaria"),
        P("transporte", "Proyecto integral de semaforización en intersecciones estratégicas, con señalización vial complementaria", 44, "Proyecto Integral de Semaforización"),
        P("agua_riesgos", "Evaluaciones de riesgo georreferenciadas en zonas críticas para sustentar muros, andenerías y defensas ribereñas", 37, "Evaluaciones de Riesgo (EVAR) georreferenciadas"),
        P("social", "Boticas municipales con medicamentos a precio de costo social y veterinaria municipal con campañas de esterilización", 31, "boticas municipales para expender fármacos"),
        P("social", "Construir la Casa de la Mujer, la Casa del Adulto Mayor y una escuela para niños con habilidades diferentes", 31, "construcción de la casa de la mujer, casa del adulto mayor"),
        P("economia", "Plataforma «Licencia Digital en 24 Horas» para negocios de bajo riesgo y brigadas itinerantes de formalización en mercados", 33, "Licencia Digital en 24 Horas"),
        P("economia", "Marca territorial «SJL Produce y Sabor» para textiles, calzado y manufactura, con bulevares gastronómicos itinerantes", 35, "SJL Produce y Sabor"),
        P("ambiente", "Renovación de parques y alamedas abastecida por una red de viveros municipales que produzca árboles nativos", 36, "Red de Viveros y Huertos Municipales"),
        P("gestion", "Ecosistema «Municipio Digital» con aplicativo móvil y agencias municipales periféricas con módulos de atención y pago", 39, "Agencias Municipales Periféricas"),
    ]),
]
