"""Independencia (150112): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150112"

# Planes que no se resumen, con la razón que se muestra junto a la candidatura
NOTAS = {
    "fuerza-popular": "El plan inscrito ante el JNE (6 páginas) trae un diagnóstico de Independencia, pero su visión menciona La Molina y sus ejes son una lista genérica para un distrito rural (rondas campesinas, saneamiento rural, riego), sin propuestas concretas para Independencia. Por eso no se resumen sus propuestas; puedes revisarlo en Voto Informado del JNE.",
}

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Lucy Balna Falcón Campos", "Acción Popular", "accion-popular", [
        P("seguridad", "Sistema distrital integrado de seguridad: serenazgo equipado, videovigilancia interconectada con la PNP y juntas vecinales en los seis ejes zonales", 5, "Reducir en 30% la tasa de denuncias al 2030", "Reducir en 30 % la tasa de denuncias al 2030"),
        P("social", "Centro Municipal de Atención a la Mujer y red de promotoras contra la violencia en los cinco ejes residenciales", 6, "Un Centro Municipal de Atención a la Mujer operativo al 2027", "Centro operativo al 2027 y 25 % menos denuncias por violencia contra la mujer al 2030"),
        P("urbano", "Recuperar e iluminar losas deportivas y parques, con programas deportivos y culturales para niños y jóvenes", 6, "40 losas deportivas y parques recuperados con iluminación", "40 losas deportivas y parques recuperados al 2030"),
        P("economia", "Programa de formalización y capacitación de MYPE con ruedas de negocio con los centros comerciales del distrito", 7, "al menos una rueda de negocio anual", "Al menos una rueda de negocio al año"),
        P("economia", "Reordenar el comercio ambulatorio en Túpac Amaru, Carlos Izaguirre y Panamericana Norte con empadronamiento, formalización y reubicación concertada", 7, "empadronamiento, formalización progresiva y reubicación concertada", "Empadronamiento al 2027 y reubicación al 2030"),
        P("agua_riesgos", "Cartera de proyectos de agua y saneamiento para las partes altas (El Ermitaño, San Camilo, 6 de Julio) gestionada con Sedapal y el MVCS", 8, "cartera de proyectos priorizada e inscrita en el Programa Multianual", "Cartera inscrita en el Programa Multianual de Inversiones al 2027"),
        P("ambiente", "Renovar la flota de limpieza, optimizar rutas, erradicar puntos críticos y segregar en la fuente con recicladores formalizados", 9, "Erradicación del 100% de los puntos críticos al 2028", "100 % de puntos críticos erradicados al 2028 y 15 % de residuos valorizados al 2030"),
        P("ambiente", "Ampliar las áreas verdes y reducir el riesgo en laderas con muros de contención, escaleras seguras y reforestación", 9, "Incrementar en 30% el área verde mantenida al 2030", "30 % más de área verde mantenida al 2030"),
        P("gestion", "Gobierno abierto con datos abiertos, simplificación de trámites y rendición de cuentas semestral en cabildos abiertos", 9, "Dos rendiciones de cuentas públicas al año", "8 rendiciones de cuentas en el período y 100 % de cumplimiento del Portal de Transparencia"),
        P("gestion", "Fortalecer la gerencia de inversiones y usar Obras por Impuestos y convenios para cerrar brechas", 10, "igual o mayor al 90% anual desde 2028", "Ejecución de inversiones de 90 % o más al año desde 2028"),
        P("gestion", "Presupuesto participativo con votación digital y presencial, y comités de vigilancia ciudadana en los seis ejes zonales", 10, "Duplicar la participación vecinal en el presupuesto participativo al 2030", "Duplicar la participación vecinal en el presupuesto participativo al 2030"),
    ]),
    ("José Elgar Espejo Cárdenas", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Programa «Comando Municipal Serenazgo» con selección por criterios técnicos y Escuela Municipal de Formación de Serenos", 25, "Crear la Escuela Municipal de Formación de Serenos", "100 % del personal de serenazgo certificado y capacitado cada año"),
        P("seguridad", "Videovigilancia con reconocimiento de placas, integrada a las comisarías, y un Centro de Monitoreo Distrital", 26, "Implementación de reconocimiento de placas vehiculares", "100 % más de cobertura de videovigilancia en zonas críticas"),
        P("urbano", "Plan «Independencia Iluminada y Segura»: luminarias LED en parques, escaleras, losas deportivas y vías con alta incidencia delictiva", 27, "Instalar o renovar 10,000 luminarias LED", "10 000 luminarias LED instaladas o renovadas en la gestión"),
        P("social", "Fiscalizar comedores populares, ollas comunes y Vaso de Leche, y depurar los padrones de beneficiarios", 21, "Fiscalizar el 100% de los programas de Comedores Populares", "100 % de los programas alimentarios fiscalizados y 100 % de padrones actualizados"),
        P("social", "Escuela Municipal de Padres con talleres de crianza, salud emocional y prevención de la violencia familiar y escolar", 28, "beneficiando a más de 5,000 familias", "Más de 5 000 familias beneficiadas al 2030"),
        P("social", "Centro de Educación Básica Independencia (CEBAI) para culminar estudios, alfabetización digital y certificación laboral", 29, "Beneficiar a más de 3,000 jóvenes y adultos", "Más de 3 000 jóvenes y adultos beneficiados al 2030"),
        P("transporte", "Ordenar el transporte menor: actualizar la ordenanza, reempadronar mototaxis y señalizar paraderos y zonas de embarque", 43, "Formalizar y ordenar el 100% de las empresas autorizadas de transporte menor", "100 % de las empresas autorizadas de transporte menor formalizadas al 2030"),
        P("ambiente", "Plan de residuos sólidos con flota municipal propia, contenedores, monitoreo de rutas y reciclaje con recicladores formalizados", 39, "Alcanzar una cobertura superior al 95% de recolección", "Más de 95 % de cobertura de recolección al 2030"),
        P("ambiente", "Proteger las Lomas Bella Durmiente con vigilancia contra invasiones, reforestación nativa y circuitos ecoturísticos", 41, "declaración y protección efectiva de las Lomas Bella Durmiente"),
        P("economia", "Programa «Independencia Emprende» de formalización con Ventanilla Única del Emprendedor y ferias «Consume Independencia»", 48, "Formalizar a más de 3,000 comerciantes y emprendedores", "Más de 3 000 comerciantes formalizados, 20 ferias al año y 5 000 empleos al 2030"),
        P("gestion", "Plataforma «Municipio Transparente» con ejecución presupuestal mensual, avance de obras y rendiciones públicas trimestrales", 17, "Publicar y actualizar el 100% de información prioritaria de gestión", "100 % de la información prioritaria de gestión publicada al 2030"),
    ]),
    (None, "Cooperación, Verdad y Honradez", "cooperacion-verdad-y-honradez", [
        P("seguridad", "Observatorio Distrital de Seguridad con mapas del delito por cuadrantes y videovigilancia en puntos críticos", 21, "90% de efectividad en la respuesta a alertas ciudadanas", "100 % de puntos críticos con videovigilancia y 90 % de alertas atendidas en menos de 5 minutos"),
        P("seguridad", "Escuela de formación continua de serenos, patrullaje mixto con la PNP y botones de pánico para vecinos y comerciantes", 21, "Capacitar al 100% de los serenos", "100 % de serenos capacitados y 30 % menos delitos patrimoniales en la vía pública"),
        P("social", "Unidad de atención a víctimas de violencia familiar y de género, articulada con el CEM, comisarías y DEMUNA", 21, "Reducir en un 25% la reincidencia en casos de violencia familiar", "25 % menos reincidencia en violencia familiar"),
        P("social", "Brigada casa por casa para afiliar al SIS, completar vacunas en menores de 3 años y tamizar anemia y tuberculosis", 12, "alcanzar un 95% de vacunación completa", "Ningún niño sin afiliación y 95 % de vacunación completa al 2030"),
        P("transporte", "Censo y concesión de rutas para mototaxis, peatonalización en el eje Túpac Amaru y ciclovías protegidas", 14, "Se construirán 15 km de ciclovías protegidas", "15 km de ciclovías protegidas"),
        P("urbano", "Mejoramiento integral de asentamientos humanos: agua, escaleras, muros, pistas, alumbrado y espacios comunitarios", 22, "60% de los AA.HH. intervenidos integralmente", "60 % de los asentamientos humanos intervenidos al final del período"),
        P("agua_riesgos", "Infraestructura de protección en laderas: muros de contención con drenaje, aliviaderos de quebradas y forestación nativa", 27, "30 km de muros de contención con drenaje", "30 km de muros, 15 canales aliviaderos y 200 ha de forestación al 2030"),
        P("economia", "Conectar catastro y licencias para formalizar micro y pequeñas empresas, simplificando trámites en zonas compatibles", 22, "Reducir la informalidad comercial en un 30%", "30 % menos informalidad comercial en los ejes comercial-industrial y Túpac Amaru"),
        P("ambiente", "Separación obligatoria de residuos en hogares y comercios, con monitoreo por aplicación y vigilancia de puntos críticos", 24, "Separación en Fuente Obligatoria", "90 % de hogares y comercios segregando y cero puntos críticos al 2030"),
        P("ambiente", "Plan «Independencia Respira»: nuevos parques vecinales y zonales y un Parque Metropolitano de la Loma en El Ermitaño", 28, "Crearemos 25 nuevos parques vecinales", "25 parques vecinales, 5 zonales y 6 m² de área verde por habitante al 2030"),
        P("gestion", "Modernizar procesos con certificaciones ISO 9001 e ISO 37001 y una unidad de integridad con participación ciudadana", 20, "Reducir en un 50% los tiempos de atención", "50 % menos tiempo en los diez trámites más solicitados"),
    ]),
    ("María Elena Ríos Suárez", "Fuerza Popular", "fuerza-popular", []),
    ("Edgard Hugo Limaylla Montalvo", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Fortalecer el serenazgo, la videovigilancia y la prevención del delito con participación vecinal", 22, "Reducir en 30% los delitos de mayor incidencia", "30 % menos delitos de mayor incidencia y 40 % más percepción de seguridad"),
        P("social", "Programas de alimentación saludable y educación nutricional contra la anemia infantil", 22, "Reducir la anemia infantil en 20%", "20 % menos anemia infantil respecto a la línea base"),
        P("social", "Capacitación técnica y orientación laboral para jóvenes", 22, "Beneficiar a más de 10,000 jóvenes", "Más de 10 000 jóvenes en formación e inserción laboral"),
        P("social", "Prevención de la violencia familiar y de género con orientación psicológica y asistencia legal", 22, "Reducir en 20% los casos reportados de violencia familiar", "20 % menos casos reportados de violencia familiar y de género"),
        P("urbano", "Construir, recuperar y mantener parques, losas deportivas y centros culturales", 22, "Incrementar en 30% los espacios públicos recreativos", "30 % más espacios públicos recreativos y deportivos"),
        P("economia", "Programas de formalización, simplificación administrativa y asistencia técnica a emprendedores", 24, "Reducir la informalidad económica en 20%", "20 % menos informalidad económica"),
        P("economia", "Convenios con entidades financieras y programas de inclusión financiera para emprendedores", 24, "Beneficiar a 5,000 emprendedores con acceso a financiamiento", "5 000 emprendedores con acceso a financiamiento y educación financiera"),
        P("ambiente", "Fortalecer la gestión integral de residuos sólidos y la limpieza pública", 25, "Reducir en 80% los puntos críticos de acumulación", "80 % menos puntos críticos de residuos al 2030"),
        P("ambiente", "Promover la segregación en la fuente y el reciclaje en hogares y comercios", 25, "Incrementar al 50% la participación de hogares", "50 % de hogares en segregación y reciclaje"),
        P("agua_riesgos", "Riego tecnificado en áreas verdes para reducir el consumo de agua", 25, "Reducir en 20% el consumo de agua para riego", "20 % menos consumo de agua para riego"),
        P("gestion", "Simplificación administrativa y transformación digital de los trámites municipales", 27, "Reducir en 50% los tiempos de atención de los principales trámites", "50 % menos tiempo de atención en los principales trámites al 2030"),
    ]),
    ("Georgina Flores Remigio", "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Más cámaras con reconocimiento conectadas a la PNP, central de monitoreo modernizada y drones en zonas críticas", 4, "Incorporar drones para vigilancia preventiva en zonas críticas"),
        P("seguridad", "Sistema Integrado de Alerta Vecinal con aplicativo y botones de pánico, y postes inteligentes con cámaras y altavoces", 4, "Sistema Integrado de Alerta Vecinal"),
        P("social", "Redes comunitarias de protección, con dirigentes capacitados en detección temprana y atención legal rápida", 4, "Crear Redes Comunitarias de Protección"),
        P("agua_riesgos", "Mapas de riesgo actualizados, obras de mitigación en laderas, alerta temprana y brigadas comunitarias de emergencia", 4, "PROTEGER A 90,000 HABITANTES EN ZONAS DE RIESGO ALTO", "90 000 habitantes en zonas de riesgo alto protegidos"),
        P("urbano", "Pavimentar vías en zonas altas con pendiente pronunciada", 4, "Pavimentación de vías en zonas altas con pendiente"),
        P("agua_riesgos", "Gestionar con Sedapal la ampliación de redes de agua y alcantarillado en zonas altas", 5, "ampliación de redes de agua y alcantarillado para 5,000 familias", "5 000 familias en zonas altas"),
        P("ambiente", "Modernizar la limpieza pública con horarios fijos de recojo por sector y un programa de reciclaje", 5, "Reorganizar recojo de residuos en 5 sectores con horarios fijos", "Cero puntos críticos de basura; recojo con horarios fijos en 5 sectores"),
        P("ambiente", "Plan de arborización, recuperación de parques y creación de ecoparques", 5, "Creación de ecoparques y jardines sostenibles"),
        P("economia", "Centro Municipal de Desarrollo Empresarial y ventanilla única de licencias para formalizar MYPES", 5, "Ventanilla única para licencias en 24 horas", "1 000 MYPES formalizadas y licencias en 24 horas"),
        P("economia", "Reubicar el comercio ambulatorio en mercados zonales ordenados", 5, "Crear 2 mercados zonales ordenados para reubicar ambulantes", "2 mercados zonales"),
        P("gestion", "Simplificar y digitalizar los trámites municipales y el acceso a la información pública", 6, "Reducir en 70% el tiempo de atención de trámites", "70 % menos tiempo de atención de trámites"),
    ]),
    (None, "Partido Demócrata Verde", "partido-democrata-verde", [
        P("seguridad", "Mapa de puntos críticos y red de casetas, central de monitoreo y cámaras interconectadas con las comisarías", 21, "Instalar 30 casetas de vigilancias", "30 casetas, 20 motos y 20 vehículos de vigilancia; cámaras conectadas a las 5 comisarías"),
        P("seguridad", "Reforzar comités y juntas vecinales y recuperar espacios públicos tomados por la delincuencia", 21, "Incremento a 80 comités vecinales conformados", "80 comités vecinales y 50 % de espacios públicos recuperados"),
        P("social", "Campañas de salud descentralizadas y convenios con farmacias del distrito para medicinas a precios accesibles", 21, "Disminución en un 30% de ANEMIA", "30 % menos anemia en menores de 3 años y 30 % menos desnutrición crónica en menores de 5"),
        P("social", "Veterinaria municipal y campañas de atención y esterilización en los cinco ejes y la zona industrial", 22, "Implementación de (01) veterinaria Municipal", "1 veterinaria municipal"),
        P("social", "Reabrir y repotenciar el albergue municipal para personas que sufren maltrato doméstico", 23, "Reducción en un 50% el número de casos de maltrato", "50 % menos casos de maltrato a mujeres y personas vulnerables"),
        P("economia", "Empadronar y formalizar a comerciantes ambulantes residentes del distrito, con ferias mensuales de comerciantes formalizados", 26, "Empadronar a ambulantes presenten en el distrito", "Aumentar en 100 % la tasa de formalización"),
        P("economia", "Capacitación técnica con escuelas técnicas y empresas de la zona industrial para conectar oferta y demanda laboral", 26, "Reducir en 50% la tasa de desempleo", "50 % menos desempleo en el distrito"),
        P("ambiente", "Programa de segregación de residuos en los cinco ejes zonales con recicladores formalizados", 27, "30% de las viviendas acogidas al programa de segregación", "30 % de viviendas en segregación"),
        P("ambiente", "Ruta turística de lomas, riego por goteo en parques forestales y freno a invasiones en zonas de lomas", 28, "Crear una ruta turística de loma"),
        P("agua_riesgos", "Protocolos de Defensa Civil para zonas vulnerables y forestación de laderas de gran pendiente", 29, "Conformación de 30 brigadas de defensa civil", "30 brigadas de defensa civil"),
        P("urbano", "Remodelar espacios públicos emblemáticos, mejorar fachadas y completar el levantamiento catastral", 30, "Remodelación y/o implementación de 4 obras", "4 obras emblemáticas y catastro al 100 %"),
    ]),
    (None, "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Patrullaje integrado por cuadrantes, Centro de Control con inteligencia artificial y videovigilancia ciudadana", 38, "Reducir el índice de victimización por debajo del 20%", "Victimización por debajo de 20 % y percepción de inseguridad en 70 % al 2030"),
        P("seguridad", "Sereno comunitario por sectores, grupo de atención rápida y patrullaje con drones", 20, "patrullaje con aeronaves no tripuladas"),
        P("social", "Salud comunitaria descentralizada y gestión de la construcción del hospital de Independencia de categoría II-1", 38, "Reducir la tasa de anemia infantil a menos del 20%", "Anemia infantil por debajo de 20 % al 2030 y hospital de Independencia ejecutado"),
        P("social", "Preuniversitario municipal gratuito y actividades juveniles en Escuelas Abiertas", 38, "Reducir la deserción escolar a menos del 1.5%", "Deserción escolar menor a 1,5 % y 30 % de egresados de colegios públicos en educación superior"),
        P("economia", "Capacitación laboral y cursos de inteligencia artificial, robótica y programación para jóvenes", 38, "tasa de desempleo juvenil al 9%", "Desempleo juvenil de 9 % e informalidad laboral de 60 % al 2030"),
        P("economia", "Licencias de funcionamiento digitales y simplificadas para MYPE, con ferias de emprendedores y mercados temporales", 38, "Formalizar al menos 500 MYPE por año", "500 MYPE formalizadas por año e informalidad comercial de 50 % al 2030"),
        P("agua_riesgos", "Impulsar el III Esquema de agua y desagüe para las zonas altas", 30, "con el impulso del III esquema"),
        P("ambiente", "Consolidar el cinturón verde, sanear los parques forestales y mejorar el riego", 39, "Incrementar a 5 m² de área verde por habitante", "5 m² de área verde por habitante al 2030"),
        P("ambiente", "Mejorar rutas de recolección, ampliar la planta de valorización de residuos orgánicos y formalizar recicladores", 39, "Eliminar los 12 puntos críticos al 2030", "Cero puntos críticos y menos de 5 % de residuos sin recolectar al 2030"),
        P("gestion", "Gobierno electrónico para trámites y pago de tributos, y más contribuyentes en zonas periurbanas", 39, "Duplicar el número de ciudadanos que pagan tributos digitalmente", "Duplicar los pagos digitales y 25 % más recaudación propia al 2030"),
        P("gestion", "Gestión por procesos con norma ISO 9001 y capacitación de funcionarios en inteligencia artificial", 39, "capacitar al 100% de funcionarios en IA generativa", "ISO 9001 en atención al ciudadano y 100 % de funcionarios capacitados al 2030"),
    ]),
    ("Ángel Demetrio Intor Vega", "Partido Morado", "partido-morado", [
        P("social", "Establecimientos municipales de salud por eje zonal, campañas preventivas y equipos multidisciplinarios de atención", 7, "Implementar establecimientos municipales de salud por eje zonal"),
        P("social", "Programa distrital contra la anemia con tamizaje, suplementos, escuelas de alimentación para madres y apoyo a ollas comunes", 12, "programa distrital de lucha contra la anemia", "Reducir la anemia infantil y ampliar la atención nutricional preventiva antes del 2030"),
        P("agua_riesgos", "Hidrantes en zonas altas conectados a reservorios, rutas de evacuación y brigadas vecinales de emergencia", 10, "instalación de hidrantes en zonas altas", "Hidrantes en las principales zonas vulnerables antes del 2030"),
        P("urbano", "Convenio con la UNI para evaluar estructuras y diseñar el reforzamiento de colegios y locales comunales", 11, "Universidad Nacional de Ingeniería para evaluación estructural", "Evaluar y priorizar la infraestructura vulnerable antes del 2029"),
        P("urbano", "Campañas masivas de saneamiento físico-legal de predios con asistencia técnica y articulación con COFOPRI", 14, "campañas masivas de saneamiento físico-legal"),
        P("economia", "Simplificar trámites y brindar asesoría para formalizar pequeños negocios y trabajadores independientes", 13, "asesoría para la formalización empresarial"),
        P("gestion", "Revisar los arbitrios con criterios diferenciados según el acceso real a servicios en las zonas altas", 15, "establecer criterios diferenciados según acceso real a servicios", "Política de arbitrios más equitativa antes del 2028"),
        P("ambiente", "Gestionar una planta de reciclaje y programas de economía circular", 16, "implementación de una planta de reciclaje"),
        P("ambiente", "Recuperar el Parque Forestal Ecoturístico Boca de Sapo con accesos, iluminación, circuitos y arborización", 17, "Parque Forestal Ecoturístico Boca de Sapo", "Recuperación integral del parque antes del 2030"),
        P("seguridad", "Escuela de formación para serenos y coordinación con la PNP y las juntas vecinales", 19, "Crear una escuela de formación para serenos"),
        P("seguridad", "Patrullaje integrado e inteligencia territorial con la PNP contra la extorsión en zonas críticas", 19, "implementar inteligencia territorial"),
    ]),
    (None, "Partido País para Todos", "partido-pais-para-todos", [
        P("seguridad", "Cámaras de seguridad con inteligencia artificial y analítica de datos, y aplicativo Alerta Vecinal en tiempo real", 27, "aplicativo Alerta Vecinal en tiempo real"),
        P("seguridad", "Patrullaje integrado entre policía, serenazgo y juntas vecinales, y recuperación de espacios ocupados por actividades ilícitas", 30, "Fortalecer el patrullaje integrado entre la policía, serenazgo y las juntas vecinales"),
        P("urbano", "Mejorar pistas y veredas en zonas residenciales, comerciales y periféricas", 27, "3,000 Metros de pista", "3 000 m de pistas y 2 000 m de veredas"),
        P("agua_riesgos", "Construcción de muros de contención y escaleras en zonas con riesgo de derrumbes", 27, "Mínimo 20 muros de construcción", "Al menos 20 muros de contención y 30 escaleras"),
        P("social", "Campañas preventivas de salud en asentamientos humanos y convenios para mejorar establecimientos de salud", 27, "Mínimo 100 campañas", "Al menos 100 campañas y 3 establecimientos de salud intervenidos"),
        P("social", "Academia municipal preuniversitaria en los distintos ejes, con convenio con el Ministerio de Educación", 28, "Implementar academia municipal pre universitaria", "Al menos 500 jóvenes atendidos"),
        P("economia", "Flexibilizar normas para otorgar licencias de funcionamiento a pequeños negocios", 28, "Otorgar Licencias de Funcionamiento en 24 horas", "Licencias en 24 horas a pequeños negocios que cumplan el TUPA"),
        P("economia", "Programas de capacitación y asesoría a emprendedores y pequeños negocios", 28, "Crear programas de capacitación y asesoramiento a emprendedores", "30 % de los capacitados se formalizan"),
        P("ambiente", "Erradicar los puntos críticos de acumulación de basura y optimizar rutas y frecuencias de recolección", 29, "Reducir en 80% los puntos críticos de acumulación de residuos", "80 % menos puntos críticos de acumulación de residuos"),
        P("ambiente", "Arborización urbana y recuperación de parques y jardines deteriorados", 29, "Plantar 2,000 arboles durante la gestión", "2 000 árboles en la gestión y 30 % más de áreas verdes"),
        P("gestion", "Presupuestos participativos y espacios de diálogo permanente con dirigentes vecinales", 29, "Mínimo 12 reuniones por año", "Al menos 12 reuniones al año"),
    ]),
    ("Sandra Gutiérrez Aibar", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Observatorio Distrital de Seguridad Ciudadana y encuesta anual de victimización por eje zonal", 12, "Observatorio Distrital de Seguridad Ciudadana y la ejecución y publicación anual", "Encuesta de victimización publicada cada año en todos los ejes zonales"),
        P("seguridad", "Serenazgo comunitario con agentes fijos por cuadrante y alarmas y aplicativos para las juntas vecinales", 12, "bajo un enfoque estrictamente comunitario en los seis ejes zonales", "Serenazgo comunitario en los seis ejes zonales"),
        P("urbano", "Plan de pavimentación de pistas y veredas en los ejes periféricos con obras mixtas y trabajo comunitario", 9, "plan de pavimentación para el diseño, construcción y mantenimiento de pistas y veredas"),
        P("agua_riesgos", "Reordenar la zonificación, acelerar la titulación y coordinar con SEDAPAL las redes de agua y alcantarillado", 9, "coordinar con SEDAPAL el tendido regular de las redes de agua potable", "90 % del distrito con servicios básicos adecuados"),
        P("social", "Guarderías infantiles descentralizadas con equipos interdisciplinarios y mejora nutricional de ollas comunes y comedores", 10, "guardería infantil descentralizada por cada eje zonal vulnerable", "Al menos una guardería por cada eje zonal vulnerable"),
        P("social", "Recuperar, iluminar y reequipar complejos deportivos y losas, con ligas anuales que incluyen ciclismo urbano y deportes electrónicos", 15, "reequipar el 80% de los complejos deportivos", "80 % de complejos deportivos y losas recuperados"),
        P("economia", "Becas y medias becas en institutos tecnológicos y CETPRO del distrito para especialidades con demanda laboral", 20, "La municipalidad financiará becas y medias becas"),
        P("transporte", "Reducir accidentes con semáforos LED, señalización, reductores de velocidad y fiscalización electrónica en puntos críticos", 28, "Reducir en un 40% los accidentes de tránsito", "40 % menos accidentes de tránsito en puntos críticos"),
        P("ambiente", "Programa de forestación urbana y periférica en laderas y espacios públicos", 23, "plantado sostenible de más de 4,000 árboles anuales", "Más de 4 000 árboles al año"),
        P("ambiente", "Formalizar recicladores, aplicativo con la ubicación de los camiones recolectores y erradicación de botaderos informales", 26, "erradicación del 90% de botaderos informales", "90 % de botaderos informales erradicados"),
        P("gestion", "Registro Público de Integridad para seguir y canalizar casos de faltas y corrupción, y rendición de cuentas en los seis ejes zonales", 33, "Registro Público de Integridad de Independencia"),
    ]),
    ("Evans Rodolfo Sifuentes Ocaña", "PPC", "partido-popular-cristiano-ppc", [
        P("seguridad", "Modernizar la videovigilancia e implementar una central de monitoreo inteligente", 11, "100 cámaras de videovigilancia operativas", "100 cámaras operativas al 2030"),
        P("seguridad", "Fortalecer y capacitar a las juntas vecinales de seguridad ciudadana", 11, "50 juntas vecinales fortalecidas y capacitadas", "50 juntas vecinales al 2030"),
        P("urbano", "Construir o mejorar parques y losas deportivas en los sectores del distrito", 11, "100 losas deportivas construidas o rehabilitadas", "50 parques y 100 losas al 2030"),
        P("social", "Campañas preventivas de salud física y mental, nutrición y lucha contra la anemia", 10, "campañas preventivas de salud física y mental, nutrición, lucha contra la anemia"),
        P("social", "Orientación y empadronamiento para acceder a Pensión 65, Juntos, Cuna Más, SIS y Beca 18", 10, "Pensión 65, Juntos, Contigo, Cuna Más"),
        P("economia", "Capacitación en empleabilidad y emprendimiento", 14, "Capacitar a 5,000 vecinos en empleabilidad", "5 000 vecinos capacitados al 2030"),
        P("economia", "Orientación para formalizar negocios, ferias y ruedas de negocio", 14, "Gestionar la formalización de 1,500 unidades económicas", "1 500 unidades económicas formalizadas y 40 ferias al 2030"),
        P("agua_riesgos", "Programa «Cerros Seguros 2030»: muros de contención, escaleras, alerta temprana y simulacros en zonas altas", 22, "PROGRAMA EMBLEMÁTICO: CERROS SEGUROS 2030"),
        P("ambiente", "Arborización, revegetación de laderas y riego de parques con aguas residuales tratadas", 17, "Incrementar en 50 hectáreas las áreas verdes", "50 ha de áreas verdes recuperadas y mantenidas al 2030"),
        P("ambiente", "Puntos de segregación y reciclaje, y campañas de educación ambiental", 17, "Implementar 100 puntos de segregación y reciclaje", "100 puntos de reciclaje y 20 campañas al año"),
        P("gestion", "Plataforma digital de trámites y audiencias públicas de rendición de cuentas", 20, "Digitalizar el 80% de los trámites municipales más demandados", "80 % de trámites digitalizados y 16 audiencias en la gestión"),
    ]),
    ("Gregorio Bernardino Quispe Alvino", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Programa «Independencia Resplandece»: videovigilancia, más serenazgo, patrullaje integrado y recuperación de espacios públicos", 64, "Reducir en 70% la percepción de inseguridad ciudadana en el distrito", "70 % menos percepción de inseguridad"),
        P("seguridad", "Luminarias LED de luz blanca en avenidas, parques, escaleras y zonas de alta incidencia delictiva", 31, "luminarias LED de luz blanca"),
        P("seguridad", "Oficina de instrucción para capacitar a serenos y fiscalizadores con personal de la PNP o Fuerzas Armadas", 31, "Crear Una Oficina de instrucción para capacitar en forma permanente a los serenos"),
        P("urbano", "Programa «Independencia Sanea tu Hogar y Territorio»: asesoría técnica y legal gratuita para formalizar predios", 59, "Incorporar al menos 10,000 vecinos a procesos de saneamiento", "Al menos 10 000 vecinos en procesos de formalización"),
        P("transporte", "Gestionar la viabilidad del primer teleférico distrital", 60, "Gestionar la viabilidad del primer teleférico distrital"),
        P("social", "Gestionar ante las entidades competentes la construcción del Hospital Distrital", 34, "proyecto de construcción del Hospital Distrital"),
        P("social", "Ampliar la salud preventiva y crear un Centro Municipal de Atención Psicológica", 64, "Incrementar en 50% la cobertura de programas de salud preventiva", "50 % más cobertura de salud preventiva"),
        P("social", "Programas educativos, tecnológicos y de capacitación para el empleo para estudiantes y jóvenes", 64, "Beneficiar a más de 10,000 estudiantes y jóvenes", "Más de 10 000 estudiantes y jóvenes beneficiados"),
        P("economia", "Campañas de formalización empresarial, asesoría técnica y capacitación de emprendedores", 66, "Formalizar al menos 3,000 negocios locales", "Al menos 3 000 negocios formalizados y más de 5 000 personas capacitadas"),
        P("ambiente", "Reciclaje con segregación en la fuente y limpieza de los puntos críticos de residuos", 66, "reducir en 50% los puntos críticos de acumulación de residuos", "20 % más reciclaje y 50 % menos puntos críticos"),
        P("gestion", "Gobierno digital con mesa de partes virtual y simplificación de trámites", 68, "Digitalizar el 80% de los trámites y servicios municipales", "80 % de trámites digitalizados y 50 % menos tiempo de atención"),
    ]),
    ("Benigno Roberto Calderón Arones", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Programa «Independencia sin Miedo» con modelo predictivo del delito, inteligencia territorial y recuperación de espacios públicos", 4, "Modelo predictivo del delito"),
        P("social", "Programa «Independencia Saludable» de campañas preventivas articuladas con los centros de salud", 4, "INDEPENDENCIA SALUDABLE", "Beneficiar al 70 % de la población al 2030"),
        P("social", "Programa «Independencia Activa» de deporte y cultura, con un boulevard temático y un Centro Cultural Municipal", 4, "Centro Cultural Municipal", "35 % más participación al 2030"),
        P("economia", "Programa «Más Trabajo, Más Futuro» con capacitación, certificación e intermediación laboral en un Centro Municipal de Empleo", 5, "CENTRO MUNICIPAL DE EMPLEO", "60 % de participantes con empleo formal al 2030"),
        P("economia", "Programa «Crece Formal» para formalizar el comercio informal y reordenar el espacio público", 5, "CRECE FORMAL", "Formalizar y regular el 50 % del comercio informal al 2030"),
        P("economia", "Incubadora Municipal de Negocios y Centro de Desarrollo Empresarial", 5, "INCUBADORA MUNICIPAL DE NEGOCIOS", "4 000 emprendedores y empresas beneficiados al 2030"),
        P("urbano", "Programa «Independencia Ciudad del Futuro» con una Oficina Municipal de Saneamiento Físico Legal", 5, "OFICINA MUNICIPAL DE SANEAMIENTO", "50 % más áreas urbanas y espacios públicos"),
        P("ambiente", "Programa «Independencia Verde» para ampliar y proteger áreas verdes con participación vecinal", 6, "INDEPENDENCIA VERDE", "30 % más áreas verdes y espacios públicos recuperados"),
        P("ambiente", "Programa «Basura Cero» de segregación, reaprovechamiento y disposición adecuada de residuos", 6, "BASURA CERO", "30 % más aprovechamiento de residuos al 2030"),
        P("ambiente", "Centro Municipal de Salud Animal con esterilización, vacunación, adopción y registro de mascotas", 6, "CENTRO MUNICIPAL DE SALUD ANIMAL"),
        P("gestion", "Programa «Muni Digital» de digitalización total y papel cero, e implementación de la ISO 37001 antisoborno", 7, "digitalización total de los procesos de gestión municipal", "100 % de procesos sistematizados y automatizados en 2030"),
    ]),
    ("Iván Jesús Aquino Honores", "Visión Perú", "vision-peru", [
        P("social", "Clínicas móviles con medicina general, pediatría y despistaje de anemia en ollas comunes, y telemedicina municipal", 6, "Adquisición y equipamiento de clínicas móviles"),
        P("social", "Wi-Fi gratuito en plazas, parques y paraderos, y centros digitales comunitarios", 9, "acceso a Internet Wi-Fi", "150 espacios públicos con Wi-Fi gratuito y 30 000 personas certificadas en competencias digitales al 2030"),
        P("agua_riesgos", "Equipo técnico para levantar observaciones de SEDAPAL y obras por impuestos para redes de agua y desagüe", 8, "Mecanismo de Obras por Impuestos"),
        P("agua_riesgos", "Baños secos o biodigestores en asentamientos humanos de zonas altas sin red de alcantarillado", 16, "baños secos o biodigestores", "80 % de los asentamientos de zonas altas al 2030"),
        P("economia", "Fondo concursable no reembolsable para emprendimientos asociativos en los asentamientos más altos", 12, "fondo concursable municipal de financiamiento no reembolsable"),
        P("ambiente", "Erradicar y recuperar los puntos críticos de acumulación de basura", 14, "puntos críticos de acumulación de residuos sólidos", "95 % de puntos críticos erradicados y 10 000 t de residuos valorizados al año al 2030"),
        P("ambiente", "Descuentos en arbitrios para vecinos que arboricen o mantengan sus áreas verdes", 15, "Otorgar descuentos en el pago de arbitrios de parques y jardines"),
        P("seguridad", "Cámaras de videovigilancia con analítica de inteligencia artificial conectadas a la central de emergencias", 20, "con analítica de Inteligencia Artificial", "100 % de cámaras operativas con analítica de IA al 2030"),
        P("seguridad", "Centro de Comando, Control y Ciberseguridad (C4) enlazado con la central 105 de la PNP y patrullaje por cuadrantes", 22, "Centro de Comando, Control y Ciberseguridad"),
        P("gestion", "Certificación ISO 37001 antisoborno, canal de denuncias anónimas y plataforma de datos abiertos de obras", 19, "Certificación ISO 37001"),
        P("urbano", "Fiscalización satelital de habilitaciones urbanas y sistema de información territorial abierto", 24, "Fiscalización Satelital de Habilitaciones Urbanas"),
    ]),
]
