"""Breña (150105): propuestas principales de los planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
El plan del Partido Aprista Peruano es escaneado: su texto proviene de OCR (Tesseract, español).
El Partido Cívico Obras figura sin candidato a alcalde (candidatura declarada improcedente por el JNE).
"""

UBIGEO = "150105"

# Planes que no se resumen, con la razón que se muestra junto a la candidatura
NOTAS = {
    "partido-popular-cristiano-ppc": "El plan inscrito ante el JNE para Breña desarrolla otro distrito (San Antonio): solo la portada menciona Breña. Por eso no se resumen sus propuestas; puedes revisarlo en Voto Informado del JNE.",
}

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("José Dalton Li Bravo", "Acción Popular", "accion-popular", [
        P("seguridad", "Cámaras de videovigilancia en los puntos más peligrosos del distrito", 3, "videovigilancia en los puntos más peligrosos", "20 cámaras al 2030"),
        P("seguridad", "Construir el Cuartel de Serenazgo, ampliar la flota y capacitar a todo el personal", 3, "construir el Cuartel de Serenazgo", "100 % del serenazgo con capacitación certificada al 2030"),
        P("social", "Academia Preuniversitaria Municipal para jóvenes que no pueden pagar una academia privada", 3, "Academia de Preparación Pre-Universitaria Municipal", "100 jóvenes inscritos al finalizar el período"),
        P("social", "Centro Cultural de Breña con talleres permanentes y fortalecimiento de la Casa del Adulto Mayor", 3, "crear el Centro Cultural de Breña", "200 adultos mayores atendidos por año al 2030"),
        P("transporte", "Señalizar las vías del distrito y reubicar y ordenar los paraderos de mototaxis", 4, "reubicar y organizar los paraderos de mototaxis", "15 vías principales señalizadas y 8 paraderos reorganizados al 2030"),
        P("economia", "Sello «Calidad Breña» para negocios del distrito y red de asesores «Vecinos Empresarios»", 5, "Red de Asesores", "30 establecimientos con sello y 5 convenios con el sector privado al 2030"),
        P("gestion", "Equipo técnico de ingenieros y arquitectos dedicado a formular, ejecutar y supervisar las obras del distrito", 5, "equipo de ingenieros, arquitectos y técnicos especializados", "70 % de obras dentro del plazo al 2030"),
        P("ambiente", "Contenedores para el recojo selectivo en conjuntos habitacionales y programa de segregación en la fuente", 6, "contenedores individualizados para el recojo selectivo", "300 hogares en segregación y 50 contenedores al 2030"),
        P("ambiente", "Mantener todos los parques, crear nuevas áreas verdes y optimizar el riego", 6, "Sistema de Mantenimiento de Áreas Verdes", "1,5 m² de área verde por habitante y 5 parques renovados o creados al 2030"),
        P("gestion", "Código de Ética con mecanismos de denuncia y sanción, e implementación del estándar ISO 37001 Anticorrupción", 8, "estándar ISO 37001 Anticorrupción", "100 % del personal directivo capacitado en ética y anticorrupción al 2030"),
        P("gestion", "Trámites en línea desde el celular y GPS en camiones de basura y vehículos de serenazgo", 8, "GPS en los camiones de basura", "5 servicios en línea y 100 % de vehículos con GPS al 2030"),
    ]),
    ("Iván Joel Chang del Arroyo", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Central de videovigilancia con cámaras con IA de reconocimiento de placas y rostros en los accesos del distrito, y patrullaje integrado con la PNP", 7, "reconocimiento de placas y rostros"),
        P("seguridad", "Capacitar, equipar y comunicar por radio a las juntas vecinales y comités de «Vecinos Vigilantes»", 7, "100% de Juntas Vecinales y comités", "100 % de juntas vecinales y comités capacitados y equipados"),
        P("seguridad", "Iluminación LED en zonas críticas, pasajes cerrados y avenidas principales, en convenio con las empresas de energía", 8, "Iluminación con tecnología LED del 100%", "100 % de zonas críticas, pasajes y avenidas principales"),
        P("social", "Programas de prevención del acoso escolar, la violencia y el consumo de sustancias en colegios públicos", 5, "acoso escolar, violencia y consumo de sustancias", "100 % de instituciones educativas públicas"),
        P("social", "Casa de Auxilio y Refugio Rápido con asistencia legal y psicológica a víctimas de violencia familiar", 5, "Casa de Auxilio y Refugio Rápido", "1 casa implementada y equipada"),
        P("gestion", "Certificación permanente del personal en el Código de Ética y en protocolos de atención rápida al vecino", 6, "100% del personal municipal capacitado y certificado", "100 % del personal municipal certificado"),
        P("economia", "Plan de formalización comercial y ordenamiento del espacio público, ferias itinerantes reguladas y modernización de mercados", 11, "Plan Integral de Formalización Comercial"),
        P("transporte", "Reestructurar rutas y sentidos viales internos con señalización, y empadronamiento digital de mototaxis con la ATU", 13, "Rutas y Sentidos Viales Internos"),
        P("urbano", "Programa de bacheo y repavimentación de calles y jirones internos, y actualización del catastro", 12, "bacheo y repavimentación de las calles"),
        P("ambiente", "Reordenar rutas y horarios de recolección y programa de reciclaje «Breña Recicla» con segregación en la fuente", 14, "Programa Distrital de Reciclaje"),
        P("ambiente", "Plan de arborización «Un Vecino, Un Árbol» con especies de bajo consumo de agua y recuperación de todos los parques", 15, "Un Vecino, Un"),
    ]),
    ("Rommel Omar Carbajal Muñoz", "Fe en el Perú", "fe-en-el-peru", [
        P("seguridad", "Políticas preventivas y de rehabilitación para jóvenes en situación de riesgo", 3, "rehabilitadoras a los jóvenes en situación de riesgo", "Reducir entre 20 % y 30 % al año la tasa de víctimas de robos"),
        P("seguridad", "Uso de tecnología GIS para la toma de decisiones en seguridad ciudadana", 3, "Hacer uso de la tecnología GIS", "Tiempo de respuesta del serenazgo menor a 5 minutos"),
        P("seguridad", "Recuperar parques y áreas abandonadas que son focos del delito", 3, "focos del delito", "Intervenir el 100 % de los espacios identificados"),
        P("social", "Campañas preventivas de salud, con atención al adulto mayor y la salud mental", 3, "la salud mental", "Cobertura mínima de 85 % de la población vulnerable objetivo"),
        P("urbano", "Promover el saneamiento físico legal de los predios", 4, "saneamiento físico legal", "Viabilidad para al menos 80 % de las viviendas que inician el trámite"),
        P("urbano", "Instalar juegos infantiles accesibles y gimnasios en parques", 4, "Instalación de juegos infantiles y gimnasios", "Al menos 50 % de parques con juegos infantiles accesibles y/o gimnasios"),
        P("transporte", "Ordenar el transporte en vehículos menores (mototaxis)", 4, "100% de mototaxis", "100 % de mototaxis con servicio de calidad y seguro"),
        P("economia", "Fomentar el empleo de los jóvenes y capacitar a los adultos", 4, "Fomentar el empleo en los jóvenes de Breña", "Reducir el desempleo local en al menos 7 %"),
        P("ambiente", "Incrementar la cantidad de áreas verdes", 5, "Indice Verde Urbano", "Índice Verde Urbano al menos 50 % mayor"),
        P("gestion", "Transparentar, publicar e informar todos los actos públicos de la municipalidad", 5, "Transparentar, publicar e informar", "100 % de respuestas entregadas a los vecinos y 0 % de ocultamiento de información"),
        P("gestion", "Simplificar y modernizar los trámites administrativos", 5, "Simplificar y modernizar los trámites", "100 % de trámites en línea"),
    ]),
    ("Henrry Giscard de la Cruz Arana", "Fuerza Popular", "fuerza-popular", [
        P("seguridad", "Centro de Monitoreo y Vigilancia Distrital y más cámaras en avenidas, parques y zonas de alta incidencia", 2, "Centro de Monitoreo y Vigilancia Distrital"),
        P("seguridad", "Patrullaje integrado de serenazgo y PNP, alertas vecinales y botones de emergencia", 2, "Instalación de sistemas de alerta vecinal"),
        P("seguridad", "Observatorio Distrital de Seguridad Ciudadana para analizar los indicadores de forma permanente", 2, "Observatorio Distrital de Seguridad Ciudadana"),
        P("social", "Programa «Breña Saludable» con campañas médicas descentralizadas en parques y espacios comunitarios", 3, "Programa Breña Saludable"),
        P("social", "Campañas permanentes de salud mental y prevención del consumo de drogas y alcohol", 3, "Campañas permanentes de salud mental"),
        P("urbano", "Mejoramiento de pistas y veredas y recuperación de parques y espacios públicos deteriorados", 4, "Mejoramiento integral de pistas y veredas", "Recuperar la totalidad de parques y espacios públicos deteriorados"),
        P("transporte", "Corredores peatonales seguros y mejor señalización vial", 4, "corredores peatonales seguros"),
        P("gestion", "Digitalizar trámites con firma digital, expediente electrónico y seguimiento virtual", 5, "firma digital y expediente electrónico"),
        P("gestion", "Tableros de control de la gestión y portal de transparencia actualizado", 5, "Tableros de control para monitoreo"),
        P("ambiente", "Programas de reciclaje y segregación de residuos y más áreas verdes", 7, "Programas de reciclaje y segregación de residuos"),
        P("economia", "Ferias de emprendimiento, formalización de negocios y programas de empleabilidad juvenil", 8, "Ferias de emprendimiento y desarrollo empresarial"),
    ]),
    ("Urso Grajeda Reyes", "Juntos por el Perú", "juntos-por-el-peru", [
        P("seguridad", "Programa «Breña Segura» con videovigilancia inteligente, patrullaje integrado y juntas vecinales", 14, "Reducir en 30% los delitos patrimoniales", "30 % menos delitos patrimoniales y videovigilancia en el 100 % de sectores críticos"),
        P("social", "Fortalecer el Policlínico Municipal, la asistencia domiciliaria y la prevención de la anemia", 32, "Fortalecer el Policlínico Municipal, asistencia domiciliaria", "100 % de cobertura de la población vulnerable focalizada"),
        P("social", "Rehabilitar los complejos deportivos, escuelas deportivas permanentes y biblioteca virtual", 32, "Rehabilitar el 100% de complejos deportivos", "100 % de complejos deportivos rehabilitados y más de 10 disciplinas permanentes"),
        P("economia", "Programa «Breña Emprende» de formalización y asistencia técnica a MYPES", 32, "programa Breña Emprende y asistencia técnica", "40 % más MYPES formalizadas respecto a 2026"),
        P("economia", "Boulevard Gastronómico y ferias comerciales permanentes", 32, "Realizar 12 ferias comerciales anuales", "12 ferias al año y 1 Boulevard Gastronómico"),
        P("gestion", "Actualizar el catastro urbano y optimizar la recaudación tributaria", 32, "Actualizar el 100% del catastro urbano", "100 % del catastro urbano actualizado"),
        P("ambiente", "Programa «Breña Verde» con arborización, jardines verticales y azoteas verdes", 32, "Lograr que el 30% de los edificios cuenten con azoteas verdes", "30 % de edificios con azoteas verdes"),
        P("ambiente", "Contenedores soterrados y monitoreo digital de la limpieza pública", 33, "contenedores soterrados y monitoreo digital", "100 % de zonas críticas cubiertas"),
        P("agua_riesgos", "Riego tecnificado de áreas verdes con aguas tratadas", 19, "Riego tecnificado con aguas tratadas"),
        P("gestion", "Gobierno digital con la virtualización de todos los trámites municipales", 33, "Digitalizar el 100% de los trámites municipales", "100 % de trámites digitalizados"),
        P("gestion", "Cabildos abiertos, transmisión de las sesiones de concejo y Concejos de la Juventud y de los Mayores", 33, "transmitir el 100% de sesiones de concejo", "2 cabildos abiertos al año y 100 % de sesiones de concejo transmitidas"),
    ]),
    ("Jorge Henry Sarmiento Reynoso", "Libertad Popular", "libertad-popular", [
        P("seguridad", "Comando Unificado C4 que integre las cámaras municipales con las comisarías", 2, "Comando Unificado C4"),
        P("seguridad", "Inteligencia artificial preventiva para el patrullaje predictivo", 2, "patrullaje predictivo"),
        P("transporte", "Programa «Mototaxista Cívico y Seguro» con GPS y botón de pánico", 2, "Mototaxista Cívico y Seguro"),
        P("urbano", "Erradicar la chatarra urbana y recuperar espacios públicos", 2, "Erradicación de chatarra urbana"),
        P("urbano", "Alumbrado público con tecnología LED en todo el distrito", 2, "Breña Iluminada 100", "Breña 100 % LED"),
        P("ambiente", "Desratización estructural con cronograma anual coordinado con el MINSA", 2, "Desratización estructural"),
        P("social", "Línea Única de Emergencia «Yo te ayudo Breñense»", 3, "Línea Única de Emergencia"),
        P("social", "Ampliar el Policlínico Municipal con geriatría y salud mental, y red de farmacias municipales con precios sociales", 3, "Policlínico Municipal con áreas de geriatría"),
        P("urbano", "Censo de vivienda precaria para acceder a programas de reforzamiento habitacional", 3, "Censo de vivienda precaria"),
        P("economia", "Digitalizar los mercados para impulsar el comercio electrónico local", 3, "Digitalización de mercados"),
        P("gestion", "Obras por impuestos sin endeudamiento y control concurrente con la Contraloría y el OCI", 4, "Control concurrente con Contraloría"),
    ]),
    ("Raúl Alberto Sullca Maquera", "Partido Aprista Peruano", "partido-aprista-peruano", [
        P("urbano", "Promover complejos habitacionales y programas de vivienda multifamiliar en reemplazo de construcciones antiguas", 4, "promoviendo proyectos de complejos habitacionales"),
        P("urbano", "Saneamiento físico legal y titulación de predios", 4, "Promover el Saneamiento Físico Legal"),
        P("transporte", "Plan Integral del Tráfico Urbano con señalización, semaforización y educación vial", 4, "Plan Integral del Tráfico Urbano"),
        P("economia", "Capacitación gerencial y tecnológica a MYPES con universidades y programa de reclutamiento de técnicos", 5, "Programa de Reclutamiento de Técnicos de mando medio"),
        P("economia", "Ferias agropecuarias urbanas los fines de semana con productos de primera necesidad", 5, "Ferias Agropecuarias Urbanas"),
        P("social", "Farmacia municipal y policlínico municipal", 6, "Creación de la Farmacia Municipal"),
        P("social", "Cuna infantil para niños de 0 a 5 años y casa de acogida del adulto mayor", 6, "Creación de la Cuna Infantil"),
        P("ambiente", "Ampliar la arborización, recuperar parques e impulsar el vivero municipal", 6, "Impulsar el Vivero Municipal"),
        P("ambiente", "Camiones compactadores y contenedores de basura en puntos estratégicos", 7, "contenedores de basura en puntos estratégicos"),
        P("gestion", "Recaudación tributaria más efectiva y simplificación del sistema tarifario de derechos administrativos", 7, "simplificación del sistema tarifario"),
        P("seguridad", "Rondas mixtas contra la venta de drogas y cámaras con reconocimiento facial", 8, "sensores de reconocimiento facial"),
    ]),
    (None, "Partido Cívico Obras", "partido-civico-obras", [
        P("seguridad", "Sistema «Breña Vigilada» con analítica de video, patrullaje optimizado y recuperación de espacios críticos", 1, "Breña Vigilada", "Reducir 40 % la victimización delictiva al 2030"),
        P("social", "Escuelas deportivas municipales gratuitas, talleres culturales itinerantes y losas deportivas iluminadas", 2, "escuelas deportivas municipales gratuitas", "100 % de losas modernizadas al 2028 y 8 000 niños y jóvenes en talleres al 2030"),
        P("social", "Casa de la Sabiduría y Adulto Mayor y apoyo alimentario a comedores populares", 2, "Casa de la Sabiduría y Adulto Mayor de Breña", "Casa inaugurada en 2028 y 100 % de comedores con cobertura alimentaria a fines de 2027"),
        P("economia", "Licencias de funcionamiento de bajo riesgo por internet", 2, "plazo máximo de 24 horas vía web", "Licencias en máximo 24 horas en 2027"),
        P("gestion", "Plataforma única «App Breña» para los trámites vecinales habituales", 3, "Virtualizar el 100% de los trámites vecinales", "100 % de trámites habituales en línea en 2028"),
        P("social", "WiFi gratuito en plazas y parques, y alfabetización digital para adultos mayores y microempresarios", 3, "Instalar WiFi gratuito de alta velocidad", "WiFi en 8 plazas y parques para 2028 y 3 500 personas capacitadas para 2029"),
        P("economia", "Centro de Desarrollo Empresarial de Breña, ferias de empleo y convenios para insertar a jóvenes", 3, "Centro de Desarrollo Empresarial de Breña", "1 200 emprendedores formalizados para 2029 y 1 500 jóvenes en empleo formal para 2030"),
        P("transporte", "Repavimentar jirones deteriorados y semaforización inteligente en las intersecciones más congestionadas", 4, "semaforización inteligente interconectado", "90 % de calles deterioradas repavimentadas para 2029 y semáforos en 10 intersecciones para 2028"),
        P("ambiente", "Rutas de recojo con frecuencias estrictas y programa «Breña Recicla»", 4, "Erradicar el 100% de los puntos críticos", "100 % de puntos críticos de basura eliminados a fines de 2027 y 35 % de familias segregando en 2030"),
        P("agua_riesgos", "Inspeccionar quintas y casonas antiguas, señalizar zonas de evacuación y formar brigadas vecinales ante sismos", 5, "quintas históricas del distrito", "100 % de quintas inspeccionadas para 2028 y 10 000 vecinos capacitados para 2029"),
        P("gestion", "Transmisión en vivo de licitaciones, informe financiero trimestral y cuatro audiencias públicas al año", 5, "Transmisión de Licitaciones en Vivo", "100 % de procesos de licitación transmitidos en vivo"),
    ]),
    ("Luis Alberto Ojeda Samame", "Somos Perú", "partido-democratico-somos-peru", [
        P("social", "Renovar el Vaso de Leche con estándares del MINSA contra la anemia y seguimiento nutricional en centros de salud", 24, "Renovar y ampliar el programa Vaso de Leche", "Anemia en niños beneficiarios del 22,2 % al 5 % hacia 2030"),
        P("social", "Guardería Municipal para niños de 0 a 5 años, gratuita para familias en pobreza", 25, "Crear la Guardería Municipal", "Al menos 60 niños en el primer año"),
        P("social", "Unidad municipal de protección a la familia y «Ruta de atención Breña» para víctimas de violencia", 26, "Ruta de atención Breña", "200 casos anuales con seguimiento y 20 % menos reincidencia al 2030"),
        P("agua_riesgos", "Riego tecnificado en parques gestionado ante SEDAPAL para reducir el uso de agua potable", 29, "riego tecnificado (goteo o aspersión nocturna)", "Al menos 40 % menos de agua potable en el riego de parques"),
        P("ambiente", "Recuperar bermas y losas abandonadas como áreas verdes con árboles nativos", 30, "Recuperación de bermas y losas abandonadas", "1,5 m² de área verde por habitante y al menos 200 árboles al 2030"),
        P("economia", "Bolsa de empleo con ferias laborales semestrales junto al MTPE y las universidades", 30, "Bolsa de Empleo Sostenible de Breña", "400 vecinos conectados y 100 en empleo formal en los dos primeros años"),
        P("gestion", "Pago en línea de tributos con billeteras digitales y recordatorios por SMS y WhatsApp", 31, "Tu tributo se ve en tu barrio", "25 % más recaudación de arbitrios el primer año y morosidad menor al 45 % al 2030"),
        P("urbano", "Plan anual de mejoramiento de pistas y veredas en las zonas más deterioradas de Breña Vieja", 32, "Plan Anual de Mejoramiento", "5 cuadras de pistas y 10 de veredas en el primer año"),
        P("seguridad", "Centro de Monitoreo Municipal con las cámaras donadas y nuevas cámaras en 10 puntos críticos y salidas de colegios", 32, "Instalar cámaras nuevas en los 10 puntos críticos"),
        P("seguridad", "App «Breña en Alerta» con botón de pánico, reportes con geolocalización y chat con el serenazgo", 33, "Mapa de Incidencias en Tiempo Real"),
        P("gestion", "Nuevo sitio web con trámites en línea y Portal de Transparencia con informes mensuales de ejecución", 34, "Crear el Portal de Transparencia Municipal", "80 % de trámites en línea al segundo año"),
    ]),
    ("Marco Antonio Salazar Sáenz", "Partido Patriótico del Perú", "partido-patriotico-del-peru", [
        P("seguridad", "Fortalecer el serenazgo, modernizar la videovigilancia y coordinar con la PNP, priorizando zonas comerciales y avenidas de alta circulación", 6, "fortalecimiento operativo del serenazgo, modernización de los sistemas de videovigilancia"),
        P("seguridad", "Corredores urbanos seguros: patrullaje preventivo, videovigilancia e iluminación en las avenidas con más tránsito y comercio", 23, "Propuesta de fortalecimiento de corredores urbanos seguros"),
        P("urbano", "Fiscalización urbana permanente frente a la ocupación indebida de espacios públicos, el desorden comercial y la contaminación visual", 25, "ocupación indebida de espacios públicos, desorden comercial, contaminación visual"),
        P("urbano", "Recuperar y modernizar parques, bermas y áreas recreativas con mejor iluminación, mobiliario urbano y mantenimiento", 24, "Propuesta de recuperación y modernización de parques y espacios públicos"),
        P("transporte", "Mantenimiento de vías, señalización y recuperación de espacios peatonales para mejorar la circulación y la accesibilidad", 25, "recuperación progresiva de espacios peatonales"),
        P("ambiente", "Programa de recuperación de áreas verdes, refuerzo de la limpieza pública y campañas de educación ambiental", 21, "Programa de Recuperación Ambiental y Sostenibilidad Urbana"),
        P("social", "Recuperar espacios comunitarios con actividades culturales y recreativas para niños, jóvenes, adultos mayores y familias", 22, "Programa de Recuperación de Espacios Comunitarios"),
        P("economia", "Programa de desarrollo económico en coordinación con comerciantes, emprendedores e inversionistas del distrito", 22, "Programa de Desarrollo Económico, Competitividad Urbana y Fortalecimiento Empresarial"),
        P("gestion", "Programa de gobierno digital y ciudad inteligente: plataformas para atención vecinal, monitoreo urbano y fiscalización", 23, "Programa de Gobierno Digital, Innovación Urbana y Ciudad Inteligente"),
        P("gestion", "Mecanismos permanentes de participación vecinal y coordinación con vecinos, comerciantes y emprendedores", 31, "Participación vecinal y coordinación con la ciudadanía"),
    ]),
    ("Arturo Omar Maura Alfaro", "Perú Primero", "partido-politico-peru-primero", [
        P("seguridad", "Convertir la Central de Seguridad Ciudadana en un Centro Inteligente de Monitoreo y Respuesta Inmediata", 33, "Centro Inteligente de Monitoreo y Respuesta"),
        P("seguridad", "Reincorporar las unidades de serenazgo hoy fuera de servicio para patrullaje las 24 horas", 34, "Fortaleceremos la capacidad operativa del Serenazgo Municipal"),
        P("transporte", "Plan de ordenamiento de vehículos menores con formalización de mototaxis y paraderos autorizados y señalizados", 37, "Plan Integral de Ordenamiento de Vehículos Menores"),
        P("transporte", "Plan Integral de Movilidad Urbana para mejorar la conectividad y eliminar puntos críticos de congestión", 51, "Plan Integral de Movilidad Urbana"),
        P("social", "Centros municipales complementarios de orientación médica, atención psicológica y telemedicina", 21, "Centros de Atención Integral Municipal"),
        P("economia", "Programa «El vecino es primero» de capacitación laboral, certificación de competencias, emprendimiento y educación financiera", 14, "Desarrollaremos programas de capacitación laboral, certificación de competencias"),
        P("economia", "Crear el Consejo Consultivo Empresarial de Breña como espacio permanente de diálogo con el sector empresarial", 57, "Consejo Consultivo Empresarial de Breña"),
        P("agua_riesgos", "Riego tecnificado y uso eficiente del agua para el mantenimiento de las áreas verdes", 43, "Implementación de sistemas de riego tecnificado y uso eficiente del agua"),
        P("ambiente", "Programa de reciclaje con segregación de residuos y participación de asociaciones de recicladores formalizados", 50, "Impulsaremos la segregación de residuos y la economía circular"),
        P("urbano", "Mesa de coordinación con Lima Metropolitana e Invermet y monitoreo vecinal de las obras inconclusas", 48, "Mesa de Coordinación Interinstitucional"),
        P("gestion", "Digitalizar procesos, expedientes y servicios municipales para reducir la burocracia", 27, "Transformación digital de la gestión municipal"),
    ]),
    ("Haydy Lorena Breña Mejía", "Pueblo Consciente", "partido-politico-pueblo-consciente", [
        P("seguridad", "Cámaras inteligentes conectadas al serenazgo y la PNP", 6, "300 cámaras operativas", "300 cámaras operativas al 2030"),
        P("seguridad", "Más patrullaje integrado de serenazgo y PNP para mejorar la capacidad de respuesta", 6, "Incremento de patrullaje integrado Serenazgo", "Tiempo de respuesta menor a 5 minutos"),
        P("social", "Programa «Breña Te Escucha» de atención psicológica para vecinos", 2, "Breña Te Escucha", "10 000 vecinos beneficiados"),
        P("social", "Programa «Breña Inclusiva» para niños neurodivergentes (TEA, TDAH y otros) y sus familias", 2, "atención para niños neurodivergentes", "2 000 familias beneficiadas"),
        P("economia", "Programa de formalización y licencias simplificadas para el comercio ambulatorio", 3, "Programa de formalización y licencias simplificadas", "80 % de negocios formalizados al 2030"),
        P("economia", "Bolsa laboral distrital vinculada a empresas privadas", 4, "Bolsa laboral distrital vinculada a empresas privadas", "3 000 empleos generados al 2030"),
        P("ambiente", "Programa «Breña Verde» para ampliar las áreas verdes por habitante", 4, "Breña Verde", "40 % más de áreas verdes por habitante al 2030"),
        P("ambiente", "Gestión integral de residuos sólidos y reciclaje", 4, "Gestión integral de residuos y reciclaje", "60 % de residuos segregados al 2030"),
        P("urbano", "Recuperación e iluminación LED de parques y calles", 7, "Recuperación e iluminación LED de parques", "100 % de parques iluminados al 2030"),
        P("transporte", "Semaforización inteligente y ordenamiento vial", 9, "Semaforización inteligente y ordenamiento vial", "30 % menos congestión al 2030"),
        P("gestion", "Modernización digital y simplificación administrativa de los trámites municipales", 5, "Modernización digital y simplificación administrativa", "70 % menos tiempo promedio de trámite al 2030"),
    ]),
    # El PDF inscrito ante el JNE para Breña desarrolla otro distrito (San Antonio): ver NOTAS
    ("César Israel Pérez Contreras", "PPC", "partido-popular-cristiano-ppc", []),
    ("Diana Pilar León Castrillón de Oyakawa", "Partido Unidad y Paz", "partido-unidad-y-paz", [
        P("social", "Implementar la Casa del Adulto Mayor y un velatorio municipal", 10, "Implementacion del Velatorio municipal"),
        P("social", "Crear un Instituto Tecnológico Municipal de emprendimiento, calidad y competitividad para jóvenes", 10, "Creacion del Instituto Tecnologico"),
        P("social", "Casa de la Juventud y espacio «Breña LAB» para actividades artísticas y científicas de los jóvenes", 16, "Implementacion de la Casa de la juventud"),
        P("seguridad", "Plan Distrital de Seguridad Ciudadana con un mapa de las zonas más inseguras y participación de juntas vecinales", 10, "Implementar el Plan Distrital de Seguridad ciudadana"),
        P("urbano", "Construir un polideportivo municipal e instalar juegos infantiles y minigimnasios en áreas verdes", 16, "Construccion del polideportivo"),
        P("transporte", "Rediseñar las vías de tránsito del distrito con semaforización inteligente", 16, "Rediseño de las vias de transito distrital"),
        P("transporte", "Nuevas rutas de transporte público dentro del distrito y ordenamiento de las rutas de mototaxis", 17, "Agrupar todas las unidades de mototaxista"),
        P("economia", "Ferias y exposiciones para comerciantes y micro y pequeños empresarios del distrito", 12, "Promover el desarrollo de Ferias y Exposiciones"),
        P("economia", "Promover la agremiación de las pymes y su participación en las compras del Estado", 17, "participacion en las compras del estado"),
        P("ambiente", "Implementar un programa de recolección de residuos sólidos y capacitar a la población en cuidado ambiental", 15, "Implementar el programa de recoleccion de residuos solidos"),
        P("agua_riesgos", "Capacitar a la población en gestión de riesgos de desastres y elaborar un plan de contingencias", 15, "Promover la participacion y desarrollo de la poblacion y organizaciones sociales"),
    ]),
    ("Silfredo Virgilio Gamboa Usca", "Perú Moderno", "peru-moderno", [
        P("seguridad", "Sistema integrado de seguridad inteligente «Breña Protegida» con centro de monitoreo y respuesta 24/7", 22, "Implementar el 100% del sistema de videovigilancia inteligente", "100 % del sistema de videovigilancia inteligente con análisis de datos delictivos"),
        P("seguridad", "Intervención en zonas críticas de alta incidencia delictiva", 22, "Recuperar el 80% de zonas de alta incidencia delictiva", "80 % de zonas de alta incidencia delictiva recuperadas"),
        P("social", "Fortalecer la OMAPED con brigadas de campo y adecuar la infraestructura pública para personas con discapacidad", 23, "Fortalecimiento de OMAPED con brigadas de campo", "Accesibilidad universal en el 80 % de espacios públicos municipales"),
        P("social", "Servicio médico itinerante «SOS Breña» en zonas vulnerables", 24, "Atender al 70% de zonas vulnerables con campañas médicas móviles", "70 % de zonas vulnerables atendidas con campañas médicas móviles"),
        P("transporte", "Semaforización inteligente en cruces críticos", 25, "Instalar sistemas inteligentes en el 60% de cruces críticos", "Sistemas inteligentes en el 60 % de cruces críticos"),
        P("urbano", "Renovación de pistas y veredas en las vías principales", 25, "Intervenir el 70% de vías principales del distrito", "70 % de vías principales intervenidas"),
        P("economia", "Simplificar los trámites de licencias de funcionamiento", 25, "Reducir en 50% el tiempo de obtención de licencias de funcionamiento", "50 % menos tiempo para obtener una licencia de funcionamiento"),
        P("ambiente", "Vigilancia de puntos críticos de acumulación de residuos y mejora del servicio de limpieza", 26, "Reducir en 60% los puntos críticos de acumulación de residuos", "60 % menos puntos críticos de acumulación de residuos"),
        P("agua_riesgos", "Evaluaciones técnicas de edificaciones antiguas (quintas, casonas, mercados, galerías) y simulacros", 27, "Inspeccionar el 80% de edificaciones vulnerables del distrito", "80 % de edificaciones vulnerables inspeccionadas y 2 simulacros generales al año"),
        P("gestion", "Supervisión ciudadana de las obras municipales", 23, "Implementar supervisión ciudadana en el 100% de obras municipales", "100 % de obras municipales con supervisión ciudadana"),
        P("gestion", "Trámites en línea y aplicativo municipal integral", 27, "Implementar y consolidar 100% de trámites en línea", "100 % de trámites en línea"),
    ]),
    ("Luis Rolando Alejandro de la Mata Alva", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Gestionar el financiamiento del proyecto de Centro de Monitoreo, Puestos de Auxilio Rápido y cámaras ante MININTER y MEF", 37, "Construcción del Centro de Monitoreo, construcción de 10 Puestos de Auxilio Rápidos", "10 PAR y 135 cámaras de videovigilancia; costo integral S/ 15 918 558,85"),
        P("seguridad", "Una camioneta de serenazgo para cada una de las 8 zonas vecinales", 37, "Incremento de la flota de camionetas de Serenazgo", "Al tercer trimestre de gestión"),
        P("transporte", "Aplicativo «Servicio Seguro» para solicitar y controlar el servicio de mototaxis", 21, "para el control y solicitud del Servicio de Mototaxis", "Al segundo trimestre del primer año"),
        P("urbano", "Reparar los jirones Aguarico, Loreto, Pomabamba, Orbegoso y Manoa y pedir a Invermet un puente peatonal en la Av. Venezuela con Av. Arica", 22, "Reparación del Jr. Pomabamba"),
        P("social", "Ampliar la Botica Municipal y abrir otra en Chacra Colorada", 17, "Ampliar la cobertura de la Botica Municipal", "Al segundo trimestre del segundo año"),
        P("social", "Crear una guardería infantil municipal para apoyar a madres trabajadoras", 15, "Crear la Guardería Infantil Municipal", "Al tercer trimestre del primer año"),
        P("social", "Ampliar el programa «Médico en Casa» de atención domiciliaria para adultos mayores", 19, "Programa Social MEDICO EN CASA", "Al tercer trimestre del primer año"),
        P("economia", "Semana Comercial Breñense mensual con rebajas para contribuyentes al día en sus tributos", 27, "Creación de la Semana Comercial Breñense", "Al tercer trimestre del primer año"),
        P("ambiente", "Aplicativo «Breña Limpia» para controlar el recojo de residuos, desmonte y maleza en las 8 zonas vecinales", 30, "para el control del recojo de residuos sólidos, desmontes", "Al segundo trimestre del primer año"),
        P("agua_riesgos", "Riego tecnificado con aguas tratadas en los parques del distrito", 31, "Riego tecnificado con aguas tratadas en los parques", "Al segundo trimestre del segundo año"),
        P("gestion", "Publicar en tiempo real ingresos y gastos municipales y rendir cuentas trimestralmente", 39, "Rendir cuentas sobre la Gestión Municipal", "Al primer trimestre de gestión"),
    ]),
    ("Isabel María Rodríguez Vera", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Recuperar e incrementar las cámaras de videovigilancia en avenidas principales y puntos críticos", 16, "Recuperación e incremento de cámaras de video vigilancia", "200 cámaras"),
        P("seguridad", "Instalar botones de pánico e implementar Puestos de Auxilio Rápido", 16, "Implementación de Puestos de Auxilio Rápido (PAR)", "50 botones de pánico y 5 PAR"),
        P("social", "Implementar y equipar bibliotecas móviles", 18, "Implementación y equipamiento de la Biblioteca Móvil", "2 bibliotecas móviles"),
        P("social", "Servicio médico itinerante «SOS Breña» con servicio de ambulancia para las zonas más vulnerables", 19, "el cual recorrerá el distrito promocionando", "1 unidad"),
        P("social", "Crear el primer Centro de Bienestar Emocional del distrito y gestionar un centro SISOL", 20, "primer Centro de Bienestar Emocional del distrito"),
        P("transporte", "Gestionar semáforos inteligentes con la MML en las vías más congestionadas y regular el control de mototaxis", 21, "Gestionar la implementación de Semáforos Inteligentes"),
        P("urbano", "Programa «Breña linda» de pintado participativo de fachadas", 21, "para el pintado de fachadas"),
        P("economia", "Construir un boulevard gastronómico", 22, "Construcción de un Boulevard Gastronómico"),
        P("ambiente", "Empadronar y capacitar a los recicladores para erradicar el reciclaje informal", 23, "empadronando y capacitando a los recicladores", "100 % de recicladores empadronados"),
        P("agua_riesgos", "Capacitaciones con Bomberos y CENEPRED sobre zonas seguras y evaluación de viviendas antiguas con riesgo estructural", 24, "Promover en Coordinación con la compañía de Bomberos y CENEPRED", "12 capacitaciones al año"),
        P("gestion", "Hackatón de datos abiertos y central telefónica de atención vecinal 24/7", 24, "HACKATON de datos abiertos", "1 hackatón por año"),
    ]),
]
