"""La Molina (150114): propuestas principales de los 12 planes de gobierno inscritos ante el JNE.

Cada propuesta está redactada con palabras propias y lleva:
  - pagina: la página del PDF oficial donde aparece.
  - ancla: un fragmento textual del PDF que DEBE aparecer en esa página. El generador lo verifica y
    falla si no lo encuentra, para que ninguna cita apunte a una página equivocada.
Mismo criterio para todas: entre 8 y 11 propuestas por plan, repartidas en los temas que el plan desarrolla.
"""

UBIGEO = "150114"

def P(tema, texto, pagina, ancla, meta=None):
    return {"tema": tema, "texto": texto, "meta": meta, "pagina": pagina, "ancla": ancla}

# (nombre, organización, archivo PDF, propuestas)
PLANES = [
    ("Edmundo del Águila Herrera", "Acción Popular", "accion-popular", [
        P("seguridad", "Modelo «Cooperación Popular para la Seguridad»: vecinos organizados reciben cámaras y equipos de la municipalidad y hacen el primer monitoreo; serenazgo responde y la PNP interviene en casos graves", None, "Cooperación Popular para la Seguridad"),
        P("seguridad", "Serenazgo sectorizado con responsables por zona y seguridad escolar (rutas seguras y vigilancia en ingreso y salida)", None, "Serenazgo Sectorizado"),
        P("transporte", "Semaforización inteligente que ajusta los ciclos según el tránsito real y monitoreo permanente de corredores", None, "Semaforización Inteligente"),
        P("transporte", "Gestionar con Lima, Ate y el MTC la continuidad de la Av. Separadora Industrial hacia Salamanca e intervenir el óvalo La Fontana", None, "Salamanca"),
        P("agua_riesgos", "Reutilizar aguas tratadas para regar parques, bermas y nuevas áreas verdes", None, "reutilización de aguas tratadas"),
        P("urbano", "Parques para todas las edades: losas multideporte, gimnasios al aire libre, sombra y bancas para adultos mayores", None, "Gimnasios al Aire Libre"),
        P("social", "Red de CIAM descentralizados para acercar talleres y servicios a los adultos mayores de cada sector", None, "Red de CIAM Descentralizados"),
        P("economia", "Centro de Innovación y Emprendimiento con coworking, mentorías y alianzas con universidades", None, "Centro de Innovación y Emprendimiento"),
        P("economia", "Ordenar los corredores comerciales (Flora Tristán, La Fontana, Constructores) sin cambios de zonificación que afecten lo residencial", None, "Corredores Comerciales Prioritarios"),
        P("ambiente", "Contenedores soterrados en zonas comerciales y programa de arborización de cerros y laderas", None, "contenedores soterrados"),
        P("gestion", "Plataformas digitales para trámites y reportes, con inteligencia artificial en la atención al vecino y publicación del avance de obras", None, "Atención Vecinal Digital"),
    ]),
    ("Flor de María Tadeo Romero", "Ahora Nación", "ahora-nacion-an", [
        P("seguridad", "Central de Seguridad en el límite con el Estadio Monumental y mesa de trabajo para ordenar el distrito durante eventos masivos", None, "Estadio Monumental"),
        P("seguridad", "Rehabilitar los Puestos de Auxilio Rápido y más patrullaje de serenos a pie en horas punta", None, "Puestos de Auxilio Rápido"),
        P("agua_riesgos", "Convenio con la UNALM para plantas de tratamiento de aguas residuales que rieguen parques sin usar agua potable ni cisternas", 1, "Planta de Tratamiento de Aguas Residuales (PTAR)"),
        P("agua_riesgos", "Renovar muros de contención en riesgo, almacenes soterrados y brigadistas en cada sector", None, "almacenes soterrados"),
        P("transporte", "Sincronización semafórica, agentes de seguridad vial en óvalos y red de ciclovías sombreadas", None, "sincronización semafórica"),
        P("social", "Recuperar el CIAM con atención paramédica permanente y buses eléctricos gratuitos para adultos mayores", None, "buses eléctricos gratuitos"),
        P("social", "Crear el Club de la Juventud y fortalecer el CETPRO para capacitación técnica", None, "Club de la Juventud"),
        P("economia", "Panadería municipal, comedor municipal a bajo costo y una Red de Emprendedores y Mil Oficios", None, "Panadería Municipal"),
        P("ambiente", "Planta de compostaje municipal y programa «Recicla en tu Barrio» con descuentos en arbitrios", None, "Recicla en tu Barrio"),
        P("gestion", "Actualizar el catastro, auditar gestiones anteriores, revisar el contrato de alquiler de vehículos y migrar la flota a eléctricos", None, "Renting Vehicular"),
    ]),
    ("María Perla Espinoza Aquino", "Alianza para el Progreso", "alianza-para-el-progreso", [
        P("seguridad", "Central inteligente con reconocimiento de rostros y placas, Escuela del Sereno con mejor sueldo y recuperación de los Puestos de Auxilio Rápido", 25, "Escuela del Sereno", "35 camionetas al 2028 y red de fibra óptica al 100 % al 2030"),
        P("transporte", "Semáforos adaptativos («Ola Verde Inteligente»), corredor Musa–Línea 2 ante la ATU y carpooling obligatorio en colegios privados", 26, "Ola Verde Inteligente", "Reducir 30 % el tiempo de viaje al 2029"),
        P("transporte", "Nuevas ciclovías", 25, "15 km de nuevas ciclovías", "15 km al 2030"),
        P("agua_riesgos", "Estabilizar los taludes del Cerro Centinela con mallas de acero", 25, "Centinela estabilizados", "100 % de taludes estabilizados al 2029"),
        P("agua_riesgos", "Plantas de tratamiento compactas y riego por goteo automatizado", 28, "compactas y descentralizadas", "Reducir 30 % el costo de riego al 2029"),
        P("social", "Mesa técnica para reactivar la obra de la Posta de Musa y consultorios itinerantes en zonas altas", 23, "Posta de Musa"),
        P("social", "Olimpiadas intercolegiales anuales y becas universitarias para los primeros puestos", 24, "Olimpiadas Intercolegiales"),
        P("economia", "«Licencia Digital Express» para giros de bajo riesgo y una primera inspección orientativa sin multa", 26, "Licencia Digital Express", "Licencias en máximo 168 horas al 2028"),
        P("economia", "Permitir farmacias, bancos y tiendas en zonas altas para evitar viajes al centro del distrito", 27, "Molina Descentralizada"),
        P("ambiente", "Segregación de residuos en la fuente", 29, "segregación vecinal en la fuente", "40 % de viviendas al 2029"),
        P("gestion", "Trámites «Cero Papel» y una app que muestre compras y planillas municipales en gráficos, con buzón de denuncias aliado a Contraloría", 31, "Digitalizar el 100% de los trámites del TUPA", "100 % de trámites digitales al 2028"),
    ]),
    ("Sergio Joan Castromonte Chaparro", "Avanza País", "avanza-pais-partido-de-integracion-social", [
        P("seguridad", "Control territorial, patrullaje focalizado, videovigilancia operativa y coordinación con la PNP", None, "13.22", "Denuncias por delitos contra el patrimonio de 13,22 a 10,8 por cada mil habitantes al 2030"),
        P("transporte", "Gestión inteligente del tránsito y semaforización coordinada con la ATU y Lima Metropolitana", None, "11.7 km/h", "Velocidad en corredores priorizados de 11,7 a 30 km/h al 2030"),
        P("social", "Recuperar el CIAM y ampliar parques inclusivos, cultura y deporte", None, "32.45%", "Cobertura del CIAM de 32,45 % a 90 % al 2030"),
        P("economia", "Centro de Desarrollo Empresarial con programas de emprendimiento, empleo e innovación", None, "Centro de Desarrollo Empresarial", "1 centro operativo al 2030"),
        P("economia", "Planes de ordenamiento y convivencia entre comercio y vida residencial", None, "ordenamiento y convivencia", "100 % de zonas económicas priorizadas"),
        P("urbano", "Monitorear todas las solicitudes de cambio de uso, zonificación y alturas para proteger la residencialidad", None, "zonificación y alturas"),
        P("agua_riesgos", "Prevención en laderas, quebradas y taludes, con defensa civil equipada", None, "puntos críticos de riesgo", "100 % de puntos críticos priorizados atendidos al 2030"),
        P("ambiente", "Residuos gestionados con contenedores u otras soluciones ordenadas", None, "20.6%", "De 20,6 % a 60 % al 2030"),
        P("gestion", "Tablero público de gestión con reportes trimestrales y trámites trazables", None, "20.06%", "Satisfacción ciudadana de 20,06 % a 60 % al 2030"),
    ]),
    ("María Pía Paz de la Barra Freigeiro", "Fe en el Perú", "fe-en-el-peru", [
        P("seguridad", "Nuevas cámaras con inteligencia artificial en parques, losas, puntos ciegos y laderas, y patrullaje que suma un policía municipal", 16, "200 nuevas cámaras", "200 cámaras nuevas"),
        P("seguridad", "Número único de emergencias «Alerta La Molina» en reemplazo de las líneas dispersas de serenazgo", 21, "Alerta La Molina", "100 % en el primer año"),
        P("social", "Boticas municipales de genéricos, historia clínica digital y citas sin colas", 17, "Boticas municipales"),
        P("social", "Primer seguro médico municipal para jóvenes de escasos recursos y centro de capacitación técnica", 18, "Primer Seguro Médico Municipal"),
        P("urbano", "Convertir el Parque Ecológico en destino de deporte de aventura, recreación y naturaleza", 20, "deporte de aventura"),
        P("economia", "Formalización con licencias para negocios y microemprendedores", 25, "500 licencias formales", "500 licencias a negocios y 300 a microemprendedores el primer año"),
        P("agua_riesgos", "Entre 4 y 6 plantas de tratamiento (incluida la repotenciación de la PTAR Musa) para dejar de regar con agua potable", 27, "4 a 6 plantas"),
        P("transporte", "Semaforización adaptativa, corredor rojo en Javier Prado, nuevos accesos (by-pass Separadora Industrial–Salamanca) y planta de asfalto municipal", 29, "by-pass Separadora Industrial"),
        P("ambiente", "Crear la Empresa Municipal de Reciclaje y un servicio de recojo de desmonte", 28, "Empresa Municipal de Reciclaje"),
        P("gestion", "Atención omnicanal (presencial, teléfono, WhatsApp, web), expediente electrónico y asistentes virtuales 24/7", 33, "omnicanal"),
    ]),
    ("Juan Carlos Martín Zurek Pardo Figueroa", "Somos Perú", "partido-democratico-somos-peru", [
        P("seguridad", "Central «La Molina SOS» 24/7, dos centros de seguridad descentralizados y Escuela de Serenazgo", 9, "La Molina SOS", "2 centros de seguridad y 24 video-módulos"),
        P("seguridad", "Drones de vigilancia contra invasiones en los cerros", 9, "Anti-invasiones"),
        P("transporte", "Túnel La Molina–Surco, viaductos en Javier Prado (Frutales y La Molina) y Separadora Industrial, y ampliación de Javier Prado", 23, "Túnel La Molina", "4 carriles adicionales en Javier Prado"),
        P("transporte", "Semaforización inteligente y carriles reversibles en horas punta", 10, "Carriles Reversibles"),
        P("agua_riesgos", "Reservorios soterrados con agua de canal para riego y almacenes de ayuda humanitaria por sector", 21, "reservorios soterrados"),
        P("social", "Farmacias municipales de genéricos, ambulancias municipales y reactivación de postas con universidades", 13, "Farmacias Municipales"),
        P("social", "Politécnico municipal y «Escuela Digital» para jóvenes y adultos mayores", 13, "Politécnico Municipal"),
        P("economia", "Programa «Economía Plateada» para la reinserción laboral de mayores de 50 años", 11, "Economía Plateada"),
        P("ambiente", "«Mega punto limpio», más contenedores soterrados y reactivación del programa Eco Recicla", 10, "Mega punto limpio"),
        P("gestion", "Ventanilla única digital para licencias de bajo riesgo y «Alcaldía de puertas abiertas»", 22, "Alcaldía de puertas abiertas"),
    ]),
    ("Julio Adolfo Tovar Uribe", "Partido Político ADP", "partido-politico-adp", [
        P("seguridad", "Central única que integra serenazgo, PNP, vigilancia privada y juntas vecinales, con cámaras con analítica y lectura de placas", None, "Central Única de Coordinación", "200 cámaras y respuesta en menos de 5 minutos"),
        P("seguridad", "Registro voluntario del personal que trabaja en hogares, con verificación de antecedentes", None, "Censo Distrital de Personal en Hogares", "60 % del personal doméstico registrado"),
        P("urbano", "Reparar pistas y veredas críticas y cambiar el alumbrado a LED", None, "18 meses", "100 % de pistas y veredas críticas en 18 meses"),
        P("social", "Club La Molina: polideportivo con pista de atletismo, piscina semiolímpica y escuelas deportivas gratuitas", None, "Piscina semiolímpica", "Operativo al segundo año"),
        P("social", "MOLISALUD: red de centros de salud con telemedicina y psicólogo", None, "Los 5 centros operativos", "5 centros antes del segundo año"),
        P("social", "Centro Tecnológico para Jóvenes con certificación e inserción laboral", None, "300 jóvenes certificados", "300 jóvenes certificados por año"),
        P("economia", "Licencias en 24 horas para bajo riesgo, Escuela del Emprendedor y Cámara de Comercio distrital", None, "Licencias de funcionamiento en 24 horas", "1 000 vecinos capacitados por año"),
        P("economia", "Convertir Plaza Camacho en un centro empresarial moderno", 21, "Plaza Camacho"),
        P("ambiente", "Renovar áreas verdes con plantas nativas y riego eficiente", None, "Renovación de áreas verdes"),
        P("gestion", "Trámites en línea, asistente virtual con IA y una Oficina de Cumplimiento que publique el avance del plan", None, "100% de trámites disponibles", "100 % de trámites en línea el primer año"),
    ]),
    ("Meisy Blanca Rosa Núñez Ruiz", "Partido Popular Cristiano (PPC)", "partido-popular-cristiano-ppc", [
        P("seguridad", "Más cuadrantes de patrullaje integrado, renovación de la flota y cámaras vecinales conectadas con IA", 16, "victimización delictiva", "Reducir 40 % la victimización"),
        P("transporte", "Plan maestro de semaforización inteligente centralizada, accesos alternos y ciclovías conectadas a paraderos", 30, "Semaforización Inteligente Centralizada", "Reducir 35 % los tiempos en hora punta"),
        P("transporte", "Red de ciclovías interconectadas", 5, "15 kilómetros de ciclovías", "15 km"),
        P("social", "Programa «Molina Sin Anemia» con tamizajes y suplementos en zonas vulnerables", 15, "Molina Sin Anemia", "Anemia infantil por debajo de 5 %"),
        P("economia", "Centro de Innovación y Emprendimiento y más compras municipales a mypes locales", 29, "2,000 jóvenes", "2 000 jóvenes y 30 % de compras a mypes"),
        P("economia", "«Mercados Verdes»: mercados con cadena de frío, digitalización y compostaje", 29, "Mercados Verdes", "100 % de mercados tradicionales"),
        P("agua_riesgos", "Regar parques y bermas solo con agua tratada mediante plantas locales y riego por goteo", 28, "exclusivamente con agua tratada", "100 % de áreas verdes con agua de reúso"),
        P("agua_riesgos", "Muros de contención, diques en quebradas y un sistema de alerta temprana vecinal", 31, "Sistema de Alerta Temprana", "100 % de laderas en riesgo alto protegidas"),
        P("ambiente", "Observatorio del Aire y el Ruido y segregación de residuos en la fuente", 28, "Observatorio Distrital del Aire"),
        P("urbano", "Actualizar el Plan de Desarrollo Urbano y fiscalizar giros comerciales en zonas residenciales", 28, "9 metros cuadrados", "9 m² de área verde por habitante"),
        P("gestion", "Reestructurar las áreas de obras con metodología PMO para destrabar proyectos del presupuesto participativo", 31, "PMO"),
    ]),
    ("Cristopher Eldin Clemente Pérez", "Podemos Perú", "podemos-peru", [
        P("seguridad", "Centro Inteligente de Seguridad, videovigilancia con IA y sistema distrital de drones", 16, "Centro Inteligente de Seguridad"),
        P("transporte", "Centro Inteligente de Gestión del Tránsito y red semafórica modernizada", 25, "Centro Inteligente de Gestión del Tránsito"),
        P("transporte", "Planes de circulación en horarios escolares y mantenimiento de pistas y veredas", 24, "ingreso y salida escolar"),
        P("social", "Hospital municipal con laboratorio, farmacia y centro terapéutico a costo social", 34, "Hospital Municipal"),
        P("social", "Centro de reposo municipal para adultos mayores", 34, "Centro de reposo Municipal"),
        P("social", "Escuela de Talentos Deportivos y campeonatos interbarrios e interescolares", 32, "Escuela de Talentos Deportivos"),
        P("economia", "Oficina de Apoyo al Emprendedor y Cámara de Comercio de La Molina", 40, "Oficina de Apoyo al Emprendedor"),
        P("agua_riesgos", "Almacenes soterrados de defensa civil y brigadistas vecinales", 39, "almacenes soterrados de defensa civil"),
        P("ambiente", "Programa de forestación y puntos de agua purificada en espacios públicos para reducir plásticos", 44, "dispensadores de agua"),
        P("gestion", "Rendición de cuentas trimestral publicada en los canales del municipio", 48, "trimestral"),
    ]),
    ("José Miguel Rodríguez Tasayco", "Progresemos", "progresemos", [
        P("seguridad", "Programa «Un Parque, Un Sereno» y recuperación de los Puestos de Auxilio Rápido", 9, "Un Parque, Un Sereno", "Reducir la criminalidad 50 % al 2030"),
        P("seguridad", "Observatorio Distrital de Seguridad Ciudadana para analizar incidencias y percepción", 10, "Observatorio Distrital de Seguridad Ciudadana"),
        P("transporte", "Movilidad escolar gratuita y transporte nocturno gratuito para universitarios", 29, "movilidad escolar gratuita"),
        P("transporte", "Paraderos seguros y techados, y reordenamiento del tránsito en zonas críticas", 23, "paraderos seguros"),
        P("social", "Ambulancias municipales y red de gimnasios municipales", 14, "ambulancias municipales"),
        P("social", "Albergue municipal «Patitas Molinenses» y microchip para mascotas", 17, "Patitas Molinenses"),
        P("agua_riesgos", "Programa de acceso al agua potable para zonas sin suministro regular", 16, "acceso al agua potable"),
        P("economia", "Repotenciar la bolsa de trabajo municipal y ferias de empleo por sectores", 24, "Bolsa de Trabajo Municipal"),
        P("ambiente", "«La Molina Recicla», compostaje y registro digital del arbolado urbano", 30, "La Molina Recicla"),
        P("gestion", "Sesiones de Concejo en las urbanizaciones y tablero digital de indicadores del plan", 31, "sesiones de Concejo"),
    ]),
    ("Lizzi del Rocío Sueldo Matos", "Renovación Popular", "renovacion-popular-peru", [
        P("seguridad", "Postes con cámaras con IA, botón de pánico, altavoces y WiFi en parques y paraderos", 5, "200 postes", "200 postes"),
        P("seguridad", "Serenos con medios de defensa no letales y más patrullaje integrado con la PNP", 5, "uso no letal"),
        P("social", "Hospital de la Solidaridad en el distrito y más farmacias de genéricos a costo social", 9, "Hospital de la solidaridad"),
        P("social", "Academia preuniversitaria gratuita, centros de reforzamiento escolar y becas municipales", 13, "Academia Preuniversitaria"),
        P("social", "Construir el Gran Teatro Municipal", 13, "Gran Teatro Municipal"),
        P("transporte", "Más ciclovías y vías peatonales, y buses eléctricos para adultos mayores", 15, "40 % las ciclovías", "40 % más ciclovías y vías peatonales"),
        P("urbano", "Iluminación LED o solar en todas las calles y parques, y rampas en todas las veredas", 15, "luz LED o solar"),
        P("agua_riesgos", "Construir la planta de tratamiento de aguas residuales (con estudios listos) y pozos para riego", 28, "Planta de Tratamiento de Aguas Residuales"),
        P("economia", "Espacios de coworking, programa «Compra a tu Vecino» y más ferias", 27, "Compra a Tu Vecino"),
        P("ambiente", "Segregación de basura con incentivos tributarios", 29, "incentivos tributarios"),
        P("gestion", "Atención con inteligencia artificial y virtualización de la mayoría de trámites prioritarios", 32, "virtualización"),
    ]),
    ("Edwin Aníbal Mendoza Ramírez", "Visión Perú", "vision-peru", [
        P("seguridad", "Sistema de seguridad inteligente: videovigilancia con IA, drones, patrullaje integrado y botón de emergencia vecinal", None, "Uso de drones de vigilancia", "Reducir 30 % la percepción de inseguridad al 2030"),
        P("social", "Centros de atención preventiva, salud itinerante y atención integral al adulto mayor", None, "Centros municipales de atención preventiva", "50 000 atenciones preventivas"),
        P("transporte", "Centro de control de tránsito, semaforización inteligente y nuevas interconexiones viales", None, "Centro de control de tránsito", "Reducir 20 % los tiempos de viaje"),
        P("economia", "Ferias empresariales, capacitación a emprendedores y simplificación administrativa", None, "Ferias empresariales", "5 000 emprendedores capacitados"),
        P("ambiente", "Recuperar parques, corredores ecológicos y arborización urbana", None, "Corredores ecológicos", "100 000 m² de áreas verdes recuperadas"),
        P("urbano", "Defensa territorial contra invasiones con drones, monitoreo satelital y catastro georreferenciado", None, "Observatorio de Riesgos de Invasión", "100 % de predios municipales estratégicos protegidos"),
        P("agua_riesgos", "Riego tecnificado, uso eficiente del agua y energía solar en locales municipales", None, "Sistemas de riego tecnificado", "20 proyectos de sostenibilidad"),
        P("gestion", "Licencias digitales, expediente electrónico y plataforma única de atención", None, "Expediente electrónico", "80 % de trámites digitalizados"),
        P("gestion", "Portal de transparencia en tiempo real, rendiciones trimestrales y «Alcalde en tu Barrio»", None, "Portal de transparencia en tiempo real", "4 rendiciones públicas al año"),
    ]),
]
